-- Inserções para 1 Coríntios 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28456, 'nvi', '1 Coríntios', '1co', 5, 1, 'Por toda parte se ouve que há imoralidade entre vocês, imoralidade que não ocorre nem entre os pagãos, a ponto de alguém de vocês possuir a mulher de seu pai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28457, 'nvi', '1 Coríntios', '1co', 5, 2, 'E vocês estão orgulhosos! Não deviam, porém, estar cheios de tristeza e expulsar da comunhão aquele que fez isso?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28458, 'nvi', '1 Coríntios', '1co', 5, 3, 'Apesar de eu não estar presente fisicamente, estou com vocês em espírito. E já condenei aquele que fez isso, como se estivesse presente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28459, 'nvi', '1 Coríntios', '1co', 5, 4, 'Quando vocês estiverem reunidos em nome de nosso Senhor Jesus, estando eu com vocês em espírito, estando presente também o poder de nosso Senhor Jesus Cristo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28460, 'nvi', '1 Coríntios', '1co', 5, 5, 'entreguem esse homem a Satanás, para que o corpo seja destruído, e seu espírito seja salvo no dia do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28461, 'nvi', '1 Coríntios', '1co', 5, 6, 'O orgulho de vocês não é bom. Vocês não sabem que um pouco de fermento faz toda a massa ficar fermentada?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28462, 'nvi', '1 Coríntios', '1co', 5, 7, 'Livrem-se do fermento velho, para que sejam massa nova e sem fermento, como realmente são. Pois Cristo, nosso Cordeiro pascal, foi sacrificado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28463, 'nvi', '1 Coríntios', '1co', 5, 8, 'Por isso, celebremos a festa, não com o fermento velho, nem com o fermento da maldade e da perversidade, mas com os pães sem fermento da sinceridade e da verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28464, 'nvi', '1 Coríntios', '1co', 5, 9, 'Já lhes disse por carta que vocês não devem associar-se com pessoas imorais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28465, 'nvi', '1 Coríntios', '1co', 5, 10, 'Com isso não me refiro aos imorais deste mundo, nem aos avarentos, aos ladrões ou aos idólatras. Se assim fosse, vocês precisariam sair deste mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28466, 'nvi', '1 Coríntios', '1co', 5, 11, 'Mas agora estou lhes escrevendo que não devem associar-se com qualquer que, dizendo-se irmão, seja imoral, avarento, idólatra, caluniador, alcoólatra ou ladrão. Com tais pessoas vocês nem devem comer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28467, 'nvi', '1 Coríntios', '1co', 5, 12, 'Pois, como haveria eu de julgar os de fora da igreja? Não devem vocês julgar os que estão dentro?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28468, 'nvi', '1 Coríntios', '1co', 5, 13, 'Deus julgará os de fora. "Expulsem esse perverso do meio de vocês".');
