-- Inserções para 1 Coríntios 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28396, 'nvi', '1 Coríntios', '1co', 2, 1, 'Eu mesmo, irmãos, quando estive entre vocês, não fui com discurso eloqüente nem com muita sabedoria para lhes proclamar o mistério de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28397, 'nvi', '1 Coríntios', '1co', 2, 2, 'Pois decidi nada saber entre vocês, a não ser Jesus Cristo, e este, crucificado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28398, 'nvi', '1 Coríntios', '1co', 2, 3, 'E foi com fraqueza, temor e com muito tremor que estive entre vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28399, 'nvi', '1 Coríntios', '1co', 2, 4, 'Minha mensagem e minha pregação não consistiram de palavras persuasivas de sabedoria, mas consistiram de demonstração do poder do Espírito,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28400, 'nvi', '1 Coríntios', '1co', 2, 5, 'para que a fé que vocês têm não se baseasse na sabedoria humana, mas no poder de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28401, 'nvi', '1 Coríntios', '1co', 2, 6, 'Entretanto, falamos de sabedoria entre os maduros, mas não da sabedoria desta era ou dos poderosos desta era, que estão sendo reduzidos a nada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28402, 'nvi', '1 Coríntios', '1co', 2, 7, 'Pelo contrário, falamos da sabedoria de Deus, do mistério que estava oculto, o qual Deus preordenou, antes do princípio das eras, para a nossa glória.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28403, 'nvi', '1 Coríntios', '1co', 2, 8, 'Nenhum dos poderosos desta era o entendeu, pois, se o tivessem entendido, não teriam crucificado o Senhor da glória.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28404, 'nvi', '1 Coríntios', '1co', 2, 9, 'Todavia, como está escrito: "Olho nenhum viu, ouvido nenhum ouviu, mente nenhuma imaginou o que Deus preparou para aqueles que o amam";');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28405, 'nvi', '1 Coríntios', '1co', 2, 10, 'mas Deus o revelou a nós por meio do Espírito. O Espírito sonda todas as coisas, até mesmo as coisas mais profundas de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28406, 'nvi', '1 Coríntios', '1co', 2, 11, 'Pois, quem dentre os homens conhece as coisas do homem, a não ser o espírito do homem que nele está? Da mesma forma, ninguém conhece as coisas de Deus, a não ser o Espírito de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28407, 'nvi', '1 Coríntios', '1co', 2, 12, 'Nós, porém, não recebemos o espírito do mundo, mas o Espírito procedente de Deus, para que entendamos as coisas que Deus nos tem dado gratuitamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28408, 'nvi', '1 Coríntios', '1co', 2, 13, 'Delas também falamos, não com palavras ensinadas pela sabedoria humana, mas com palavras ensinadas pelo Espírito, interpretando verdades espirituais para os que são espirituais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28409, 'nvi', '1 Coríntios', '1co', 2, 14, 'Quem não tem o Espírito não aceita as coisas que vêm do Espírito de Deus, pois lhe são loucura; e não é capaz de entendê-las, porque elas são discernidas espiritualmente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28410, 'nvi', '1 Coríntios', '1co', 2, 15, 'Mas quem é espiritual discerne todas as coisas, e ele mesmo por ninguém é discernido; pois');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28411, 'nvi', '1 Coríntios', '1co', 2, 16, '"quem conheceu a mente do Senhor para que possa instruí-lo? " Nós, porém, temos a mente de Cristo.');
