-- Inserções para 1 Coríntios 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28529, 'nvi', '1 Coríntios', '1co', 8, 1, 'Com respeito aos alimentos sacrificados aos ídolos, sabemos que todos temos conhecimento. O conhecimento traz orgulho, mas o amor edifica.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28530, 'nvi', '1 Coríntios', '1co', 8, 2, 'Quem pensa conhecer alguma coisa, ainda não conhece como deveria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28531, 'nvi', '1 Coríntios', '1co', 8, 3, 'Mas quem ama a Deus, este é conhecido por Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28532, 'nvi', '1 Coríntios', '1co', 8, 4, 'Portanto, em relação ao alimento sacrificado aos ídolos, sabemos que o ídolo não significa nada no mundo e que só existe um Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28533, 'nvi', '1 Coríntios', '1co', 8, 5, 'Pois mesmo que haja os chamados deuses, quer no céu, quer na terra, ( como de fato há muitos "deuses" e muitos "senhores" ),');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28534, 'nvi', '1 Coríntios', '1co', 8, 6, 'para nós, porém, há um único Deus, o Pai, de quem vêm todas as coisas e para quem vivemos; e um só Senhor, Jesus Cristo, por meio de quem vieram todas as coisas e por meio de quem vivemos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28535, 'nvi', '1 Coríntios', '1co', 8, 7, 'Contudo, nem todos têm esse conhecimento. Alguns, ainda habituados com os ídolos, comem esse alimento como se fosse um sacrifício idólatra; e como a consciência deles é fraca, esta fica contaminada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28536, 'nvi', '1 Coríntios', '1co', 8, 8, 'A comida, porém, não nos torna aceitáveis diante de Deus; não seremos piores se não comermos, nem melhores se comermos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28537, 'nvi', '1 Coríntios', '1co', 8, 9, 'Contudo, tenham cuidado para que o exercício da liberdade de vocês não se torne uma pedra de tropeço para os fracos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28538, 'nvi', '1 Coríntios', '1co', 8, 10, 'Pois, se alguém que tem a consciência fraca vir você que tem este conhecimento comer num templo de ídolos, não será induzido a comer do que foi sacrificado a ídolos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28539, 'nvi', '1 Coríntios', '1co', 8, 11, 'Assim, esse irmão fraco, por quem Cristo morreu, é destruído por causa do conhecimento que você tem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28540, 'nvi', '1 Coríntios', '1co', 8, 12, 'Quando você peca contra seus irmãos dessa maneira, ferindo a consciência fraca deles, peca contra Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28541, 'nvi', '1 Coríntios', '1co', 8, 13, 'Portanto, se aquilo que eu como leva o meu irmão a pecar, nunca mais comerei carne, para não fazer meu irmão tropeçar.');
