-- Inserções para 1 Coríntios 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28667, 'nvi', '1 Coríntios', '1co', 13, 1, 'Ainda que eu fale as línguas dos homens e dos anjos, se não tiver amor, serei como o sino que ressoa ou como o prato que retine.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28668, 'nvi', '1 Coríntios', '1co', 13, 2, 'Ainda que eu tenha o dom de profecia e saiba todos os mistérios e todo o conhecimento, e tenha uma fé capaz de mover montanhas, mas não tiver amor, nada serei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28669, 'nvi', '1 Coríntios', '1co', 13, 3, 'Ainda que eu dê aos pobres tudo o que possuo e entregue o meu corpo para ser queimado, mas não tiver amor, nada disso me valerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28670, 'nvi', '1 Coríntios', '1co', 13, 4, 'O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28671, 'nvi', '1 Coríntios', '1co', 13, 5, 'Não maltrata, não procura seus interesses, não se ira facilmente, não guarda rancor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28672, 'nvi', '1 Coríntios', '1co', 13, 6, 'O amor não se alegra com a injustiça, mas se alegra com a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28673, 'nvi', '1 Coríntios', '1co', 13, 7, 'Tudo sofre, tudo crê, tudo espera, tudo suporta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28674, 'nvi', '1 Coríntios', '1co', 13, 8, 'O amor nunca perece; mas as profecias desaparecerão, as línguas cessarão, o conhecimento passará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28675, 'nvi', '1 Coríntios', '1co', 13, 9, 'Pois em parte conhecemos e em parte profetizamos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28676, 'nvi', '1 Coríntios', '1co', 13, 10, 'quando, porém, vier o que é perfeito, o que é imperfeito desaparecerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28677, 'nvi', '1 Coríntios', '1co', 13, 11, 'Quando eu era menino, falava como menino, pensava como menino e raciocinava como menino. Quando me tornei homem, deixei para trás as coisas de menino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28678, 'nvi', '1 Coríntios', '1co', 13, 12, 'Agora, pois, vemos apenas um reflexo obscuro, como em espelho; mas, então, veremos face a face. Agora conheço em parte; então, conhecerei plenamente, da mesma forma como sou plenamente conhecido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28679, 'nvi', '1 Coríntios', '1co', 13, 13, 'Assim, permanecem agora estes três: a fé, a esperança e o amor. O maior deles, porém, é o amor.');
