-- Inserções para 1 Crônicas 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10762, 'nvi', '1 Crônicas', '1cr', 13, 1, 'Depois de consultar todos os seus oficiais, os comandantes de mil e de cem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10763, 'nvi', '1 Crônicas', '1cr', 13, 2, 'Davi disse a toda a assembléia de Israel: "Se vocês estão de acordo e se esta é a vontade do Senhor nosso Deus, enviemos uma mensagem a nossos irmãos em todo o território de Israel, e também aos sacerdotes e aos levitas que estão com eles em suas cidades, para virem unir-se a nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10764, 'nvi', '1 Crônicas', '1cr', 13, 3, 'Vamos trazer de volta a arca de nosso Deus, pois não nos importamos com ela durante o reinado de Saul".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10765, 'nvi', '1 Crônicas', '1cr', 13, 4, 'Toda a assembléia concordou, pois isso pareceu bem a todo o povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10766, 'nvi', '1 Crônicas', '1cr', 13, 5, 'Então Davi reuniu todos os israelitas, desde o rio Sior, no Egito, até Lebo-Hamate, para trazerem de Quiriate-Jearim a arca de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10767, 'nvi', '1 Crônicas', '1cr', 13, 6, 'Davi e todos os israelitas foram a Baalá, que é Quiriate-Jearim, em Judá, para buscar a arca de Deus, o Senhor, entronizado entre os querubins; a arca sobre a qual seu nome é invocado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10768, 'nvi', '1 Crônicas', '1cr', 13, 7, 'Da casa de Abinadabe levaram a arca de Deus num carroção novo, conduzido por Uzá e Aiô.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10769, 'nvi', '1 Crônicas', '1cr', 13, 8, 'Davi e todos os israelitas iam dançando e cantando com todo o vigor diante de Deus, ao som de harpas, liras, tamborins, címbalos e cornetas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10770, 'nvi', '1 Crônicas', '1cr', 13, 9, 'Quando chegaram à eira de Quidom, Uzá esticou o braço e segurou a arca, porque os bois haviam tropeçado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10771, 'nvi', '1 Crônicas', '1cr', 13, 10, 'A ira do Senhor acendeu-se contra Uzá, e ele o feriu por ter tocado na arca. Uzá morreu ali mesmo, diante de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10772, 'nvi', '1 Crônicas', '1cr', 13, 11, 'Davi ficou contrariado porque o Senhor, em sua ira, havia fulminado Uzá. Até hoje aquele lugar é chamado Perez-Uzá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10773, 'nvi', '1 Crônicas', '1cr', 13, 12, 'Naquele dia, Davi teve medo de Deus e se perguntou: "Como vou conseguir levar a arca de Deus? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10774, 'nvi', '1 Crônicas', '1cr', 13, 13, 'Por isso desistiu de levar a arca para a cidade de Davi. Em vez disso, levou-a para a casa de Obede-Edom, de Gate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10775, 'nvi', '1 Crônicas', '1cr', 13, 14, 'A arca de Deus ficou na casa dele por três meses, e o Senhor abençoou sua família e tudo o que possuía.');
