-- Inserções para 1 Crônicas 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10456, 'nvi', '1 Crônicas', '1cr', 6, 1, 'Estes foram os filhos de Levi: Gérson, Coate e Merari.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10457, 'nvi', '1 Crônicas', '1cr', 6, 2, 'Estes foram os filhos de Coate: Anrão, Isar, Hebrom e Uziel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10458, 'nvi', '1 Crônicas', '1cr', 6, 3, 'Estes foram os filhos de Anrão: Arão, Moisés e Miriã. Estes foram os filhos de Arão: Nadabe, Abiú, Eleazar e Itamar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10459, 'nvi', '1 Crônicas', '1cr', 6, 4, 'Eleazar gerou Finéias, Finéias gerou Abisua,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10460, 'nvi', '1 Crônicas', '1cr', 6, 5, 'Abisua gerou Buqui, Buqui gerou Uzi,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10461, 'nvi', '1 Crônicas', '1cr', 6, 6, 'Uzi gerou Zeraías, Zeraías gerou Meraiote,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10462, 'nvi', '1 Crônicas', '1cr', 6, 7, 'Meraiote gerou Amarias, Amarias gerou Aitube,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10463, 'nvi', '1 Crônicas', '1cr', 6, 8, 'Aitube gerou Zadoque, Zadoque gerou Aimaás,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10464, 'nvi', '1 Crônicas', '1cr', 6, 9, 'Aimaás gerou Azarias, Azarias gerou Joanã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10465, 'nvi', '1 Crônicas', '1cr', 6, 10, 'Joanã gerou Azarias que foi sacerdote no templo construído por Salomão em Jerusalém;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10466, 'nvi', '1 Crônicas', '1cr', 6, 11, 'Azarias gerou Amarias, Amarias gerou Aitube,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10467, 'nvi', '1 Crônicas', '1cr', 6, 12, 'Aitube gerou Zadoque, Zadoque gerou Salum,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10468, 'nvi', '1 Crônicas', '1cr', 6, 13, 'Salum gerou Hilquias, Hilquias gerou Azarias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10469, 'nvi', '1 Crônicas', '1cr', 6, 14, 'Azarias gerou Seraías, e Seraías gerou Jeozadaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10470, 'nvi', '1 Crônicas', '1cr', 6, 15, 'Jeozadaque foi levado prisioneiro quando o Senhor enviou Judá e Jerusalém para o exílio por meio de Nabucodonosor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10471, 'nvi', '1 Crônicas', '1cr', 6, 16, 'Estes foram os filhos de Levi: Gérson, Coate e Merari.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10472, 'nvi', '1 Crônicas', '1cr', 6, 17, 'Estes são os nomes dos filhos de Gérson: Libni e Simei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10473, 'nvi', '1 Crônicas', '1cr', 6, 18, 'Estes foram os filhos de Coate: Anrão, Isar, Hebrom e Uziel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10474, 'nvi', '1 Crônicas', '1cr', 6, 19, 'Estes foram os filhos de Merari: Mali e Musi. Estes são os clãs dos levitas alistados de acordo com os seus antepassados:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10475, 'nvi', '1 Crônicas', '1cr', 6, 20, 'De Gérson: Seu filho Libni, que foi o pai de Jaate, pai de Zima,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10476, 'nvi', '1 Crônicas', '1cr', 6, 21, 'que foi o pai de Joá, pai de Ido, pai de Zerá, que foi o pai de Jeaterai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10477, 'nvi', '1 Crônicas', '1cr', 6, 22, 'De Coate: Seu filho Aminadabe, pai de Corá, que foi o pai de Assir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10478, 'nvi', '1 Crônicas', '1cr', 6, 23, 'pai de Elcana, pai de Ebiasafe, que foi o pai de Assir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10479, 'nvi', '1 Crônicas', '1cr', 6, 24, 'pai de Taate, pai de Uriel, pai de Uzias, que foi o pai de Saul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10480, 'nvi', '1 Crônicas', '1cr', 6, 25, 'De Elcana: Amasai, Aimote');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10481, 'nvi', '1 Crônicas', '1cr', 6, 26, 'e Elcana, pai de Zofai, pai de Naate,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10482, 'nvi', '1 Crônicas', '1cr', 6, 27, 'que foi o pai de Eliabe, pai de Jeroão, pai de Elcana, que foi o pai de Samuel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10483, 'nvi', '1 Crônicas', '1cr', 6, 28, 'De Samuel: Joel, o mais velho, e Abias, o segundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10484, 'nvi', '1 Crônicas', '1cr', 6, 29, 'De Merari: Mali, pai de Libni, pai de Simei, que foi o pai de Uzá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10485, 'nvi', '1 Crônicas', '1cr', 6, 30, 'pai de Siméia, pai de Hagias, que foi o pai de Asaías.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10486, 'nvi', '1 Crônicas', '1cr', 6, 31, 'Estes são os homens a quem Davi encarregou de dirigir os cânticos no templo do Senhor depois que a arca foi levada para lá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10487, 'nvi', '1 Crônicas', '1cr', 6, 32, 'Eles ministravam o louvor diante do tabernáculo, da Tenda do Encontro, até quando Salomão construiu o templo do Senhor em Jerusalém. Eles exerciam suas funções de acordo com as normas estabelecidas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10488, 'nvi', '1 Crônicas', '1cr', 6, 33, 'Estes são os que ministravam, junto com seus filhos: Dentre os coatitas: O músico Hemã, filho de Joel, filho de Samuel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10489, 'nvi', '1 Crônicas', '1cr', 6, 34, 'filho de Elcana, filho de Jeroão, filho de Eliel, filho de Toá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10490, 'nvi', '1 Crônicas', '1cr', 6, 35, 'filho de Zufe, filho de Elcana, filho de Maate, filho de Amasai,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10491, 'nvi', '1 Crônicas', '1cr', 6, 36, 'filho de Elcana, filho de Joel, filho de Azarias, filho de Sofonias');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10492, 'nvi', '1 Crônicas', '1cr', 6, 37, 'filho de Taate, filho de Assir, filho de Ebiasafe, filho de Corá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10493, 'nvi', '1 Crônicas', '1cr', 6, 38, 'filho de Isar, filho de Coate, filho de Levi, filho de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10494, 'nvi', '1 Crônicas', '1cr', 6, 39, 'À direita de Hemã, ficava seu parente Asafe, filho de Berequias, filho de Siméia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10495, 'nvi', '1 Crônicas', '1cr', 6, 40, 'filho de Micael, filho de Baaséias, filho de Malquias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10496, 'nvi', '1 Crônicas', '1cr', 6, 41, 'filho de Etni, filho de Zerá, filho de Adaías,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10497, 'nvi', '1 Crônicas', '1cr', 6, 42, 'filho de Etã, filho de Zima, filho de Simei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10498, 'nvi', '1 Crônicas', '1cr', 6, 43, 'filho de Jaate, filho de Gérson, filho de Levi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10499, 'nvi', '1 Crônicas', '1cr', 6, 44, 'Dentre os meraritas: À esquerda de Hemã, parente dos meraritas, ficava Etã, filho de Quisi, filho de Abdi, filho de Maluque,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10500, 'nvi', '1 Crônicas', '1cr', 6, 45, 'filho de Hasabias, filho de Amazias, filho de Hilquias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10501, 'nvi', '1 Crônicas', '1cr', 6, 46, 'filho de Anzi, filho de Bani, filho de Sêmer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10502, 'nvi', '1 Crônicas', '1cr', 6, 47, 'filho de Mali, filho de Musi, filho de Merari, filho de Levi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10503, 'nvi', '1 Crônicas', '1cr', 6, 48, 'Seus parentes, os outros levitas, foram encarregados de cuidar de todo o serviço do tabernáculo, o templo de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10504, 'nvi', '1 Crônicas', '1cr', 6, 49, 'Mas era Arão e seus descendentes que cuidavam dos sacrifícios no altar do holocausto e das ofertas no altar de incenso e de todo o serviço do Lugar Santíssimo, e dos sacrifícios de propiciação por Israel, conforme tudo o que Moisés, servo de Deus, tinha ordenado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10505, 'nvi', '1 Crônicas', '1cr', 6, 50, 'Estes foram os descendentes de Arão: o seu filho Eleazar, pai de Finéias, que foi o pai de Abisua,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10506, 'nvi', '1 Crônicas', '1cr', 6, 51, 'pai de Buqui, pai de Uzi, que foi o pai de Zeraías,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10507, 'nvi', '1 Crônicas', '1cr', 6, 52, 'pai de Meraiote, pai de Amarias, que foi o pai de Aitube,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10508, 'nvi', '1 Crônicas', '1cr', 6, 53, 'pai de Zadoque, pai de Aimaás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10509, 'nvi', '1 Crônicas', '1cr', 6, 54, 'Estas foram as cidades e as regiões dadas aos levitas para nelas habitarem. Dentre os descendentes de Arão, o clã coatita foi sorteado primeiro;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10510, 'nvi', '1 Crônicas', '1cr', 6, 55, 'foi-lhe dada Hebrom, em Judá, com suas pastagens ao redor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10511, 'nvi', '1 Crônicas', '1cr', 6, 56, 'Mas os campos e os povoados em torno da cidade foram dados a Calebe, filho de Jefoné.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10512, 'nvi', '1 Crônicas', '1cr', 6, 57, 'Assim os descendentes de Arão receberam Hebrom, cidade de refúgio, e Libna, Jatir, Estemoa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10513, 'nvi', '1 Crônicas', '1cr', 6, 58, 'Hilém, Debir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10514, 'nvi', '1 Crônicas', '1cr', 6, 59, 'Asã, Jutá e Bete-Semes, com suas respectivas pastagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10515, 'nvi', '1 Crônicas', '1cr', 6, 60, 'E da tribo de Benjamim receberam Gibeão, Geba, Alemete e Anatote, com suas respectivas pastagens. Ao todo treze cidades foram distribuídas entre os seus clãs.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10516, 'nvi', '1 Crônicas', '1cr', 6, 61, 'Para os demais descendentes de Coate foram sorteadas dez cidades pertencentes aos clãs da metade da tribo de Manassés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10517, 'nvi', '1 Crônicas', '1cr', 6, 62, 'Para os descendentes de Gérson, clã por clã, foram sorteadas treze cidades das tribos de Issacar, de Aser e de Naftali, e da metade da tribo de Manassés que fica em Basã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10518, 'nvi', '1 Crônicas', '1cr', 6, 63, 'Para os descendentes de Merari, clã por clã, foram sorteadas doze cidades das tribos de Rúben, de Gade e de Zebulom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10519, 'nvi', '1 Crônicas', '1cr', 6, 64, 'Assim os israelitas deram aos levitas essas cidades com suas respectivas pastagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10520, 'nvi', '1 Crônicas', '1cr', 6, 65, 'As cidades anteriormente mencionadas dos territórios de Judá, de Simeão e de Benjamim também lhes foram dadas por sorteio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10521, 'nvi', '1 Crônicas', '1cr', 6, 66, 'Alguns dos clãs coatitas receberam as seguintes cidades no território da tribo de Efraim:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10522, 'nvi', '1 Crônicas', '1cr', 6, 67, 'Siquém, cidade de refúgio, nos montes de Efraim, e Gezer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10523, 'nvi', '1 Crônicas', '1cr', 6, 68, 'Jocmeão, Bete-Horom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10524, 'nvi', '1 Crônicas', '1cr', 6, 69, 'Aijalom e Gate-Rimom, com suas respectivas pastagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10525, 'nvi', '1 Crônicas', '1cr', 6, 70, 'E da metade da tribo de Manassés o restante dos clãs coatitas recebeu Aner e Bileã, com suas respectivas pastagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10526, 'nvi', '1 Crônicas', '1cr', 6, 71, 'Os gersonitas receberam as seguintes cidades: Do clã da meia tribo de Manassés, Golã, em Basã, e também Asterote, com suas respectivas pastagens;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10527, 'nvi', '1 Crônicas', '1cr', 6, 72, 'da tribo de Issacar, Quedes, Daberate,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10528, 'nvi', '1 Crônicas', '1cr', 6, 73, 'Ramote e Aném, com suas respectivas pastagens;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10529, 'nvi', '1 Crônicas', '1cr', 6, 74, 'da tribo de Aser, Masal, Abdom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10530, 'nvi', '1 Crônicas', '1cr', 6, 75, 'Hucoque e Reobe, com suas respectivas pastagens;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10531, 'nvi', '1 Crônicas', '1cr', 6, 76, 'e da tribo de Naftali, Quedes, na Galiléia, Hamom e Quiriataim, com suas respectivas pastagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10532, 'nvi', '1 Crônicas', '1cr', 6, 77, 'E estas foram as cidades que os outros meraritas receberam: Da tribo de Zebulom, Rimono e Tabor, com suas respectivas pastagens;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10533, 'nvi', '1 Crônicas', '1cr', 6, 78, 'da tribo de Rúben, do outro lado do Jordão, a leste de Jericó, Bezer, no deserto, Jaza,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10534, 'nvi', '1 Crônicas', '1cr', 6, 79, 'Quedemote e Mefaate, com suas respectivas pastagens;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10535, 'nvi', '1 Crônicas', '1cr', 6, 80, 'e da tribo de Gade, Ramote, em Gileade, Maanaim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10536, 'nvi', '1 Crônicas', '1cr', 6, 81, 'Hesbom e Jazar, com suas respectivas pastagens.');
