-- Inserções para 1 Crônicas 14
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10776, 'nvi', '1 Crônicas', '1cr', 14, 1, 'Hirão, rei de Tiro, enviou a Davi uma delegação, que lhe trouxe toras de cedro, e também pedreiros e carpinteiros, para lhe construírem um palácio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10777, 'nvi', '1 Crônicas', '1cr', 14, 2, 'Então Davi teve certeza de que o Senhor o confirmara como rei de Israel e que seu reino estava prosperando por amor de seu povo Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10778, 'nvi', '1 Crônicas', '1cr', 14, 3, 'Em Jerusalém Davi tomou para si mais mulheres e gerou mais filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10779, 'nvi', '1 Crônicas', '1cr', 14, 4, 'Estes são os nomes dos que lhe nasceram ali: Samua, Sobabe, Natã, Salomão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10780, 'nvi', '1 Crônicas', '1cr', 14, 5, 'Ibar, Elisua, Elpelete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10781, 'nvi', '1 Crônicas', '1cr', 14, 6, 'Nogá, Nefegue, Jafia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10782, 'nvi', '1 Crônicas', '1cr', 14, 7, 'Elisama, Beeliada e Elifelete.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10783, 'nvi', '1 Crônicas', '1cr', 14, 8, 'Quando os filisteus ficaram sabendo que Davi tinha sido ungido rei de todo o Israel, foram com todo o exército prendê-lo, mas Davi soube disso e saiu para enfrentá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10784, 'nvi', '1 Crônicas', '1cr', 14, 9, 'Tendo os filisteus invadido o vale de Refaim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10785, 'nvi', '1 Crônicas', '1cr', 14, 10, 'Davi perguntou a Deus: "Devo atacar os filisteus? Tu os entregarás nas minhas mãos? " O Senhor lhe respondeu: "Vá, eu os entregarei nas suas mãos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10786, 'nvi', '1 Crônicas', '1cr', 14, 11, 'Então Davi e seus soldados foram a Baal-Perazim, e Davi os derrotou e disse: "Assim como as águas de uma enchente causam destruição, pelas minhas mãos Deus destruiu os meus inimigos". Então, aquele lugar passou a ser chamado Baal-Perazim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10787, 'nvi', '1 Crônicas', '1cr', 14, 12, 'Como os filisteus haviam abandonado os seus ídolos ali, Davi ordenou que fossem queimados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10788, 'nvi', '1 Crônicas', '1cr', 14, 13, 'Os filisteus voltaram a atacar o vale;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10789, 'nvi', '1 Crônicas', '1cr', 14, 14, 'então Davi consultou Deus de novo, que lhe respondeu: "Não ataque pela frente, mas dê a volta por trás deles e ataque-os em frente das amoreiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10790, 'nvi', '1 Crônicas', '1cr', 14, 15, 'Assim que você ouvir um som de passos por cima das amoreiras, saia para o combate, pois este é o sinal de que Deus saiu à sua frente para ferir o exército filisteu".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10791, 'nvi', '1 Crônicas', '1cr', 14, 16, 'E Davi fez como Deus lhe tinha ordenado, e eles derrotaram o exército filisteu, por todo o caminho, desde Gibeom até Gezer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10792, 'nvi', '1 Crônicas', '1cr', 14, 17, 'Assim, a fama de Davi espalhou-se por todas as terras, e o Senhor fez com que todas as nações o temessem.');
