-- Inserções para 1 Crônicas 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10308, 'nvi', '1 Crônicas', '1cr', 2, 1, 'Estes foram os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar, Zebulom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10309, 'nvi', '1 Crônicas', '1cr', 2, 2, 'Dã, José, Benjamim, Naftali, Gade e Aser.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10310, 'nvi', '1 Crônicas', '1cr', 2, 3, 'Estes foram os filhos de Judá: Er, Onã e Selá. Ele teve esses três filhos com uma mulher cananéia, a filha de Suá. Mas o Senhor reprovou a conduta perversa de Er, filho mais velho de Judá, e por isso o matou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10311, 'nvi', '1 Crônicas', '1cr', 2, 4, 'Tamar, nora de Judá, deu-lhe os filhos Perez e Zerá. A Judá nasceram ao todo cinco filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10312, 'nvi', '1 Crônicas', '1cr', 2, 5, 'Estes foram os filhos de Perez: Hezrom e Hamul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10313, 'nvi', '1 Crônicas', '1cr', 2, 6, 'Estes foram os filhos de Zerá: Zinri, Etã, Hemã, Calcol e Darda. Foram cinco ao todo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10314, 'nvi', '1 Crônicas', '1cr', 2, 7, 'O filho de Carmi foi Acar. Ele causou desgraça a Israel ao violar a proibição de se apossar das coisas consagradas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10315, 'nvi', '1 Crônicas', '1cr', 2, 8, 'Este foi o filho de Etã: Azarias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10316, 'nvi', '1 Crônicas', '1cr', 2, 9, 'Os filhos que nasceram a Hezrom foram Jerameel, Rão e Calebe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10317, 'nvi', '1 Crônicas', '1cr', 2, 10, 'Rão gerou Aminadabe, e Aminadabe gerou Naassom, o líder da tribo de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10318, 'nvi', '1 Crônicas', '1cr', 2, 11, 'Naassom gerou Salmom, Salmom gerou Boaz,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10319, 'nvi', '1 Crônicas', '1cr', 2, 12, 'Boaz gerou Obede, e Obede gerou Jessé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10320, 'nvi', '1 Crônicas', '1cr', 2, 13, 'Jessé gerou Eliabe, o seu filho mais velho; o segundo foi Abinadabe, o terceiro Siméia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10321, 'nvi', '1 Crônicas', '1cr', 2, 14, 'o quarto Natanael, o quinto Radai,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10322, 'nvi', '1 Crônicas', '1cr', 2, 15, 'o sexto Ozém, e o sétimo Davi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10323, 'nvi', '1 Crônicas', '1cr', 2, 16, 'As irmãs deles foram Zeruia e Abigail. Os três filhos de Zeruia foram Abisai, Joabe e Asael.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10324, 'nvi', '1 Crônicas', '1cr', 2, 17, 'Abigail deu à luz Amasa, filho do ismaelita Jéter.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10325, 'nvi', '1 Crônicas', '1cr', 2, 18, 'Calebe, filho de Hezrom, teve uma filha chamada Jeriote com sua mulher Azuba. Estes foram os filhos de Azuba: Jeser, Sobabe e Ardom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10326, 'nvi', '1 Crônicas', '1cr', 2, 19, 'Quando Azuba morreu, Calebe tomou por mulher a Efrate, com quem teve Hur.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10327, 'nvi', '1 Crônicas', '1cr', 2, 20, 'Hur gerou Uri, e Uri gerou Bezalel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10328, 'nvi', '1 Crônicas', '1cr', 2, 21, 'Depois disso, Hezrom, aos sessenta anos, tomou por mulher a filha de Maquir, pai de Gileade e ela deu-lhe um filho chamado Segube.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10329, 'nvi', '1 Crônicas', '1cr', 2, 22, 'Segube gerou Jair, que governou vinte e três cidades em Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10330, 'nvi', '1 Crônicas', '1cr', 2, 23, 'Gesur e Arã conquistaram Havote-Jair, bem como Quenate e os povoados ao redor, ao todo sessenta cidades. Todos esses foram descendentes de Maquir, pai de Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10331, 'nvi', '1 Crônicas', '1cr', 2, 24, 'Depois que Hezrom morreu em Calebe-Efrata, Abia, a mulher de Hezrom, deu-lhe Asur, fundador de Tecoa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10332, 'nvi', '1 Crônicas', '1cr', 2, 25, 'Estes foram os filhos de Jerameel, o filho mais velho de Hezrom: Rão, o mais velho, Buna, Orém, Ozém e Aías.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10333, 'nvi', '1 Crônicas', '1cr', 2, 26, 'Jerameel teve outra mulher, chamada Atara, que foi a mãe de Onã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10334, 'nvi', '1 Crônicas', '1cr', 2, 27, 'Estes foram os filhos de Rão, o filho mais velho de Jerameel: Maaz, Jamim e Equer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10335, 'nvi', '1 Crônicas', '1cr', 2, 28, 'Estes foram os filhos de Onã: Samai e Jada. Estes foram os filhos de Samai: Nadabe e Abisur.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10336, 'nvi', '1 Crônicas', '1cr', 2, 29, 'O nome da mulher de Abisur era Abiail. Ela deu-lhe dois filhos: Abã e Molide.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10337, 'nvi', '1 Crônicas', '1cr', 2, 30, 'Estes foram os filhos de Nadabe: Selede e Apaim. Selede morreu sem filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10338, 'nvi', '1 Crônicas', '1cr', 2, 31, 'O filho de Apaim foi Isi, pai de Sesã, pai de Alai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10339, 'nvi', '1 Crônicas', '1cr', 2, 32, 'Estes foram os filhos de Jada, irmão de Samai: Jéter e Jônatas. Jéter morreu sem filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10340, 'nvi', '1 Crônicas', '1cr', 2, 33, 'Estes foram os filhos de Jônatas: Pelete e Zaza. Foram esses os descendentes de Jera-meel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10341, 'nvi', '1 Crônicas', '1cr', 2, 34, 'Sesã não teve filhos, apenas filhas. Tinha ele um escravo egípcio chamado Jará,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10342, 'nvi', '1 Crônicas', '1cr', 2, 35, 'a quem deu uma de suas filhas por mulher. E ela deu-lhe um filho chamado Atai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10343, 'nvi', '1 Crônicas', '1cr', 2, 36, 'Atai gerou Natã, Natã gerou Zabade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10344, 'nvi', '1 Crônicas', '1cr', 2, 37, 'Zabade gerou Eflal, Eflal gerou Obede,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10345, 'nvi', '1 Crônicas', '1cr', 2, 38, 'Obede gerou Jeú, Jeú gerou Azarias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10346, 'nvi', '1 Crônicas', '1cr', 2, 39, 'Azarias gerou Helez, Helez gerou Eleasa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10347, 'nvi', '1 Crônicas', '1cr', 2, 40, 'Eleasa gerou Sismai, Sismai gerou Salum,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10348, 'nvi', '1 Crônicas', '1cr', 2, 41, 'Salum gerou Jecamias, e Jecamias gerou Elisama.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10349, 'nvi', '1 Crônicas', '1cr', 2, 42, 'Estes foram os filhos de Calebe, irmão de Jerameel: Messa, o mais velho, que foi o pai de Zife, e seu filho Maressa, pai de Hebrom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10350, 'nvi', '1 Crônicas', '1cr', 2, 43, 'Estes foram os filhos de Hebrom: Corá, Tapua, Requém e Sema.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10351, 'nvi', '1 Crônicas', '1cr', 2, 44, 'Sema gerou Raão, pai de Jorqueão. Requém gerou Samai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10352, 'nvi', '1 Crônicas', '1cr', 2, 45, 'O filho de Samai foi Maom, e Maom foi o pai de Bete-Zur.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10353, 'nvi', '1 Crônicas', '1cr', 2, 46, 'A concubina de Calebe, Efá teve três filhos: Harã, Mosa e Gazez. Harã gerou Gazez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10354, 'nvi', '1 Crônicas', '1cr', 2, 47, 'Estes foram os filhos de Jadai: Regém, Jotão, Gesã, Pelete, Efá e Saafe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10355, 'nvi', '1 Crônicas', '1cr', 2, 48, 'A concubina de Calebe, Maaca teve dois filhos: Seber e Tiraná.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10356, 'nvi', '1 Crônicas', '1cr', 2, 49, 'Ela também teve Saafe, pai de Madmana, e Seva, pai de Macbena e de Gibeá. A filha de Calebe chamava-se Acsa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10357, 'nvi', '1 Crônicas', '1cr', 2, 50, 'Calebe teve também estes outros descendentes: Os filhos de Hur, o filho mais velho de Efrate: Sobal, fundador de Quiriate-Jearim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10358, 'nvi', '1 Crônicas', '1cr', 2, 51, 'Salma, fundador de Belém, e Harefe, fundador de Bete-Gader.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10359, 'nvi', '1 Crônicas', '1cr', 2, 52, 'Os descendentes de Sobal, fundador de Quiriate-Jearim: O povo de Haroé, metade dos manaatitas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10360, 'nvi', '1 Crônicas', '1cr', 2, 53, 'e os clãs de Quiriate-Jearim: os itritas, os fateus, os sumateus e os misraeus. Desses descenderam os zoratitas e os estaoleus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10361, 'nvi', '1 Crônicas', '1cr', 2, 54, 'Os descendentes de Salma: O povo de Belém e de Atrote-Bete-Joabe, os netofatitas, metade dos manaatitas, os zoreus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10362, 'nvi', '1 Crônicas', '1cr', 2, 55, 'e os clãs dos escribas que viviam em Jabez: os tiratitas, os simeatitas e os sucatitas. Esses foram os queneus, descendentes de Hamate, antepassado da família de Recabe.');
