-- Inserções para 1 Crônicas 10
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10661, 'nvi', '1 Crônicas', '1cr', 10, 1, 'E aconteceu que, em combate com os filisteus, os israelitas foram postos em fuga, e muitos caíram mortos no monte Gilboa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10662, 'nvi', '1 Crônicas', '1cr', 10, 2, 'Os filisteus perseguiram Saul e seus filhos, e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10663, 'nvi', '1 Crônicas', '1cr', 10, 3, 'O combate foi se tornando cada vez mais violento em torno de Saul, até que os flecheiros o alcançaram e o feriram gravemente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10664, 'nvi', '1 Crônicas', '1cr', 10, 4, 'Então Saul ordenou ao seu escudeiro: "Tire sua espada e mate-me com ela, senão sofrerei a vergonha de cair nas mãos desses incircuncisos". Mas o seu escudeiro estava apavorado e não quis fazê-lo. Saul, então, apanhou a própria espada e jogou-se sobre ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10665, 'nvi', '1 Crônicas', '1cr', 10, 5, 'Quando o escudeiro viu que Saul estava morto, jogou-se também sobre sua espada e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10666, 'nvi', '1 Crônicas', '1cr', 10, 6, 'Dessa maneira Saul e seus três filhos morreram, e, assim, toda a descendência real.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10667, 'nvi', '1 Crônicas', '1cr', 10, 7, 'Quando os israelitas que habitavam no vale viram que o exército tinha fugido e que Saul e seus filhos estavam mortos, fugiram abandonando suas cidades. Depois os filisteus foram ocupá-las.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10668, 'nvi', '1 Crônicas', '1cr', 10, 8, 'No dia seguinte, quando os filisteus foram saquear os mortos, encontraram Saul e seus filhos caídos no monte Gilboa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10669, 'nvi', '1 Crônicas', '1cr', 10, 9, 'Cortaram a cabeça de Saul, pegaram suas armas e enviaram mensageiros por toda a terra dos filisteus proclamando a notícia entre os seus ídolos e o seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10670, 'nvi', '1 Crônicas', '1cr', 10, 10, 'Expuseram suas armas num dos templos dos seus deuses e penduraram sua cabeça no templo de Dagom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10671, 'nvi', '1 Crônicas', '1cr', 10, 11, 'Quando os habitantes de Jabes-Gileade ficaram sabendo o que os filisteus haviam feito com Saul,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10672, 'nvi', '1 Crônicas', '1cr', 10, 12, 'os mais corajosos dentre eles foram e apanharam os corpos de Saul e de seus filhos e os levaram a Jabes. Lá sepultaram seus ossos sob a Grande Árvore, e jejuaram por sete dias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10673, 'nvi', '1 Crônicas', '1cr', 10, 13, 'Saul morreu porque foi infiel ao Senhor; não guardou a palavra do Senhor e chegou a consultar uma médiun em busca de orientação,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10674, 'nvi', '1 Crônicas', '1cr', 10, 14, 'em vez de consultar o Senhor. Por isso o Senhor o entregou à morte e deu o reino a Davi, filho de Jessé.');
