-- Inserções para 1 Crônicas 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10577, 'nvi', '1 Crônicas', '1cr', 8, 1, 'Benjamim gerou Belá, seu filho mais velho; Asbel, seu segundo filho, Aará, o terceiro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10578, 'nvi', '1 Crônicas', '1cr', 8, 2, 'Noá, o quarto, e Rafa, o quinto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10579, 'nvi', '1 Crônicas', '1cr', 8, 3, 'Estes foram os filhos de Belá: Adar, Gera, pai de Eúde,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10580, 'nvi', '1 Crônicas', '1cr', 8, 4, 'Abisua, Naamã, Aoá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10581, 'nvi', '1 Crônicas', '1cr', 8, 5, 'Gera, Sefufá e Hurão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10582, 'nvi', '1 Crônicas', '1cr', 8, 6, 'Estes foram os descendentes de Eúde, chefes das famílias dos habitantes de Geba, que foram deportados para Manaate:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10583, 'nvi', '1 Crônicas', '1cr', 8, 7, 'Naamã, Aías e Gera. Esse Gera, pai de Uzá e de Aiúde, foi quem os deportou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10584, 'nvi', '1 Crônicas', '1cr', 8, 8, 'Depois de ter se divorciado de suas mulheres Husim e Baara, Saaraim teve filhos na terra de Moabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10585, 'nvi', '1 Crônicas', '1cr', 8, 9, 'Com sua mulher Hodes ele gerou Jobabe, Zíbia, Messa, Malcã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10586, 'nvi', '1 Crônicas', '1cr', 8, 10, 'Jeús, Saquias e Mirma. Esses foram seus filhos, chefes de famílias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10587, 'nvi', '1 Crônicas', '1cr', 8, 11, 'Com Husim ele gerou Abitube e Elpaal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10588, 'nvi', '1 Crônicas', '1cr', 8, 12, 'Estes foram os filhos de Elpaal: Héber, Misã, Semede, que fundou Ono e Lode com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10589, 'nvi', '1 Crônicas', '1cr', 8, 13, 'Berias e Sema foram os chefes das famílias dos habitantes de Aijalom, e foram eles que expulsaram os habitantes de Gate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10590, 'nvi', '1 Crônicas', '1cr', 8, 14, 'Aiô, Sasaque, Jeremote,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10591, 'nvi', '1 Crônicas', '1cr', 8, 15, 'Zebadias, Arade, Éder,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10592, 'nvi', '1 Crônicas', '1cr', 8, 16, 'Micael, Ispa e Joá foram descendentes de Berias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10593, 'nvi', '1 Crônicas', '1cr', 8, 17, 'Zebadias, Mesulão, Hizqui, Héber,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10594, 'nvi', '1 Crônicas', '1cr', 8, 18, 'Ismerai, Izlias e Jobabe foram descendentes de Elpaal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10595, 'nvi', '1 Crônicas', '1cr', 8, 19, 'Jaquim, Zicri, Zabdi,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10596, 'nvi', '1 Crônicas', '1cr', 8, 20, 'Elienai, Ziletai, Eliel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10597, 'nvi', '1 Crônicas', '1cr', 8, 21, 'Adaías, Beraías e Sinrate foram descendentes de Simei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10598, 'nvi', '1 Crônicas', '1cr', 8, 22, 'Ispã, Héber, Eliel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10599, 'nvi', '1 Crônicas', '1cr', 8, 23, 'Abdom, Zicri, Hanã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10600, 'nvi', '1 Crônicas', '1cr', 8, 24, 'Hananias, Elão, Antotias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10601, 'nvi', '1 Crônicas', '1cr', 8, 25, 'Ifdéias e Penuel foram descendentes de Sasaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10602, 'nvi', '1 Crônicas', '1cr', 8, 26, 'Sanserai, Searias, Atalias,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10603, 'nvi', '1 Crônicas', '1cr', 8, 27, 'Jaaresias, Elias e Zicri foram descendentes de Jeroão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10604, 'nvi', '1 Crônicas', '1cr', 8, 28, 'Todos esses foram chefes de famílias, líderes conforme alistados em suas genealogias, e moravam em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10605, 'nvi', '1 Crônicas', '1cr', 8, 29, 'Jeiel, pai de Gibeom morou na cidade de Gibeom. O nome de sua mulher era Maaca,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10606, 'nvi', '1 Crônicas', '1cr', 8, 30, 'o de seu filho mais velho, Abdom, e o de seus outros filhos, Zur, Quis, Baal, Ner, Nadabe,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10607, 'nvi', '1 Crônicas', '1cr', 8, 31, 'Gedor, Aiô, Zequer');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10608, 'nvi', '1 Crônicas', '1cr', 8, 32, 'e Miclote, que gerou Siméia. Eles também moravam perto de seus parentes, em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10609, 'nvi', '1 Crônicas', '1cr', 8, 33, 'Ner gerou Quis, que gerou Saul. Saul gerou Jônatas, Malquisua, Abinadabe e Esbaal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10610, 'nvi', '1 Crônicas', '1cr', 8, 34, 'O filho de Jônatas foi Meribe-Baal, que gerou Mica.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10611, 'nvi', '1 Crônicas', '1cr', 8, 35, 'Estes foram os filhos de Mica: Pitom, Meleque, Taréia e Acaz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10612, 'nvi', '1 Crônicas', '1cr', 8, 36, 'Acaz gerou Jeoada, Jeoada gerou Alemete, Azmavete e Zinri, e Zinri gerou Mosa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10613, 'nvi', '1 Crônicas', '1cr', 8, 37, 'Mosa gerou Bineá, pai de Rafa, que foi o pai de Eleasa, pai de Azel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10614, 'nvi', '1 Crônicas', '1cr', 8, 38, 'Azel teve seis filhos chamados Azricão, Bocru, Ismael, Searias, Obadias e Hanã. Todos esses foram filhos de Azel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10615, 'nvi', '1 Crônicas', '1cr', 8, 39, 'Estes foram os filhos de Eseque, seu irmão: Ulão, o mais velho, Jeús, o segundo e Elifelete, o terceiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10616, 'nvi', '1 Crônicas', '1cr', 8, 40, 'Os filhos de Ulão eram soldados valentes e bons flecheiros. Tiveram muitos filhos e netos; eram cento e cinqüenta ao todo. Todos esses foram descendentes de Benjamim.');
