-- Inserções para 1 Crônicas 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10254, 'nvi', '1 Crônicas', '1cr', 1, 1, 'Adão, Sete, Enos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10255, 'nvi', '1 Crônicas', '1cr', 1, 2, 'Cainã, Malaleel, Jarede,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10256, 'nvi', '1 Crônicas', '1cr', 1, 3, 'Enoque, Matusalém, Lameque, Noé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10257, 'nvi', '1 Crônicas', '1cr', 1, 4, 'Estes foram os filhos de Noé: Sem, Cam e Jafé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10258, 'nvi', '1 Crônicas', '1cr', 1, 5, 'Estes foram os filhos de Jafé: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tirás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10259, 'nvi', '1 Crônicas', '1cr', 1, 6, 'Estes foram os filhos de Gômer: Asquenaz, Rifate e Togarma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10260, 'nvi', '1 Crônicas', '1cr', 1, 7, 'Estes foram os filhos de Javã: Elisá, Társis, Quitim e Rodanim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10261, 'nvi', '1 Crônicas', '1cr', 1, 8, 'Estes foram os filhos de Cam: Cuxe, Mizraim, Fute e Canaã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10262, 'nvi', '1 Crônicas', '1cr', 1, 9, 'Estes foram os filhos de Cuxe: Sebá, Havilá, Sabtá, Raamá e Sabtecá. Estes foram os filhos de Raamá: Sabá e Dedã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10263, 'nvi', '1 Crônicas', '1cr', 1, 10, 'Cuxe gerou Ninrode, o primeiro homem poderoso na terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10264, 'nvi', '1 Crônicas', '1cr', 1, 11, 'Mizraim gerou os luditas, os anamitas, os leabitas, os naftuítas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10265, 'nvi', '1 Crônicas', '1cr', 1, 12, 'os patrusitas, os casluítas, dos quais se originaram os filisteus, e os caftoritas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10266, 'nvi', '1 Crônicas', '1cr', 1, 13, 'Canaã gerou Sidom, seu filho mais velho, e Hete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10267, 'nvi', '1 Crônicas', '1cr', 1, 14, 'como também os jebuseus, os amorreus, os girgaseus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10268, 'nvi', '1 Crônicas', '1cr', 1, 15, 'os heveus, os arqueus, os sineus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10269, 'nvi', '1 Crônicas', '1cr', 1, 16, 'os arvadeus, os zemareus e os hamateus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10270, 'nvi', '1 Crônicas', '1cr', 1, 17, 'Estes foram os filhos de Sem: Elão, Assur, Arfaxade, Lude e Arã. Estes foram os filhos de Arã: Uz, Hul, Géter e Meseque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10271, 'nvi', '1 Crônicas', '1cr', 1, 18, 'Arfaxade gerou Salá, e este gerou Héber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10272, 'nvi', '1 Crônicas', '1cr', 1, 19, 'A Héber nasceram dois filhos: Um deles se chamou Pelegue, porque em sua época a terra foi dividida; seu irmão chamou-se Joctã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10273, 'nvi', '1 Crônicas', '1cr', 1, 20, 'Joctã gerou Almodá, Salefe, Hazarmavé, Jerá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10274, 'nvi', '1 Crônicas', '1cr', 1, 21, 'Hadorão, Uzal, Dicla,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10275, 'nvi', '1 Crônicas', '1cr', 1, 22, 'Obal, Abimael, Sabá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10276, 'nvi', '1 Crônicas', '1cr', 1, 23, 'Ofir, Havilá e Jobabe. Todos esses foram filhos de Joctã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10277, 'nvi', '1 Crônicas', '1cr', 1, 24, 'Sem, Arfaxade, Salá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10278, 'nvi', '1 Crônicas', '1cr', 1, 25, 'Héber, Pelegue, Reú,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10279, 'nvi', '1 Crônicas', '1cr', 1, 26, 'Serugue, Naor, Terá');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10280, 'nvi', '1 Crônicas', '1cr', 1, 27, 'e Abrão, que é Abraão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10281, 'nvi', '1 Crônicas', '1cr', 1, 28, 'Estes foram os filhos de Abraão: Isaque e Ismael.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10282, 'nvi', '1 Crônicas', '1cr', 1, 29, 'Foram estes os seus descendentes: Nebaiote, o filho mais velho de Ismael, Quedar, Adbeel, Mibsão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10283, 'nvi', '1 Crônicas', '1cr', 1, 30, 'Misma, Dumá, Massá, Hadade, Temá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10284, 'nvi', '1 Crônicas', '1cr', 1, 31, 'Jetur, Nafis e Quedemá. Esses foram os filhos de Ismael.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10285, 'nvi', '1 Crônicas', '1cr', 1, 32, 'Estes foram os filhos de Abraão com sua concubina Quetura: Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá. Foram estes os filhos de Jocsã: Sabá e Dedã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10286, 'nvi', '1 Crônicas', '1cr', 1, 33, 'Foram estes os filhos de Midiã: Efá, Éfer, Enoque, Abida e Elda. Todos esses foram descendentes de Quetura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10287, 'nvi', '1 Crônicas', '1cr', 1, 34, 'Abraão gerou Isaque. Estes foram os filhos de Isaque: Esaú e Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10288, 'nvi', '1 Crônicas', '1cr', 1, 35, 'Estes foram os filhos de Esaú: Elifaz, Reuel, Jeús, Jalão e Corá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10289, 'nvi', '1 Crônicas', '1cr', 1, 36, 'Estes foram os filhos de Elifaz: Temã, Omar, Zefô, Gaetã e Quenaz; e Amaleque, de Timna, sua concumbina.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10290, 'nvi', '1 Crônicas', '1cr', 1, 37, 'Estes foram os filhos de Reuel: Naate, Zerá, Samá e Mizá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10291, 'nvi', '1 Crônicas', '1cr', 1, 38, 'Estes foram os filhos de Seir: Lotã, Sobal, Zibeão, Aná, Disom, Eser e Disã. Lotã tinha uma irmã chamada Timna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10292, 'nvi', '1 Crônicas', '1cr', 1, 39, 'Estes foram os filhos de Lotã: Hori e Homã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10293, 'nvi', '1 Crônicas', '1cr', 1, 40, 'Estes foram os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onã. Estes foram os filhos de Zibeão: Aiá e Aná.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10294, 'nvi', '1 Crônicas', '1cr', 1, 41, 'Este foi o filho de Aná: Disom. Estes foram os filhos de Disom: Hendã, Esbã, Itrã e Querã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10295, 'nvi', '1 Crônicas', '1cr', 1, 42, 'Estes foram os filhos de Eser: Bilã, Zaavã e Acã. Estes foram os filhos de Disã: Uz e Arã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10296, 'nvi', '1 Crônicas', '1cr', 1, 43, 'Estes foram os reis que reinaram no território de Edom antes que os israelitas tivessem um rei: Belá, filho de Beor. Sua cidade chamava-se Dinabá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10297, 'nvi', '1 Crônicas', '1cr', 1, 44, 'Belá morreu, e Jobabe, filho de Zerá, de Bozra, foi o seu sucessor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10298, 'nvi', '1 Crônicas', '1cr', 1, 45, 'Jobabe morreu, e Husã, da terra dos temanitas, foi o seu sucessor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10299, 'nvi', '1 Crônicas', '1cr', 1, 46, 'Husã morreu, e Hadade, filho de Bedade, que tinha derrotado os midianitas na terra de Moabe, foi o seu sucessor. Sua cidade chamava-se Avite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10300, 'nvi', '1 Crônicas', '1cr', 1, 47, 'Hadade morreu, e Samlá de Masreca foi o seu sucessor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10301, 'nvi', '1 Crônicas', '1cr', 1, 48, 'Samlá morreu, e Saul, de Reobote, próxima ao Eufrates, foi o seu sucessor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10302, 'nvi', '1 Crônicas', '1cr', 1, 49, 'Saul morreu, e Baal-Hanã, filho de Acbor, foi o seu sucessor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10303, 'nvi', '1 Crônicas', '1cr', 1, 50, 'Baal-Hanã morreu, e Hadade foi o seu sucessor. Sua cidade chamava-se Paú, e o nome de sua mulher era Meetabel, filha de Matrede e neta de Mezaabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10304, 'nvi', '1 Crônicas', '1cr', 1, 51, 'Após a morte de Hadade, Edom foi governada pelos seguintes chefes: Timna, Alva, Jetete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10305, 'nvi', '1 Crônicas', '1cr', 1, 52, 'Oolibama, Elá, Pinom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10306, 'nvi', '1 Crônicas', '1cr', 1, 53, 'Quenaz, Temã, Mibzar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10307, 'nvi', '1 Crônicas', '1cr', 1, 54, 'Magdiel e Irã. Foram esses os chefes de Edom.');
