-- Inserções para 1 Crônicas 18
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10892, 'nvi', '1 Crônicas', '1cr', 18, 1, 'Depois disso, Davi derrotou os filisteus e os subjugou, e tirou do controle deles a cidade de Gate e seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10893, 'nvi', '1 Crônicas', '1cr', 18, 2, 'Davi derrotou também os moabitas, que ficaram sujeitos a ele, pagando-lhe impostos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10894, 'nvi', '1 Crônicas', '1cr', 18, 3, 'Além disso, Davi derrotou Hadadezer, rei de Zobá, nas proximidades de Hamate, quando Hadadezer tentava obter o controle na região do rio Eufrates.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10895, 'nvi', '1 Crônicas', '1cr', 18, 4, 'Davi se apossou de mil dos seus carros de guerra, sete mil cavaleiros e vinte mil soldados de infantaria. Ainda levou cem cavalos de carros de guerra, e aleijou todos os outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10896, 'nvi', '1 Crônicas', '1cr', 18, 5, 'Quando os arameus de Damasco vieram ajudar Hadadezer, rei de Zobá, Davi matou vinte e dois mil deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10897, 'nvi', '1 Crônicas', '1cr', 18, 6, 'Em seguida estabeleceu guarnições militares no reino dos arameus de Damasco, sujeitando-os a lhe pagarem impostos. E o Senhor dava vitórias a Davi aonde quer que ele fosse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10898, 'nvi', '1 Crônicas', '1cr', 18, 7, 'Davi também levou para Jerusalém os escudos de ouro usados pelos oficiais de Hadadezer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10899, 'nvi', '1 Crônicas', '1cr', 18, 8, 'De Tebá e Cum, cidades que pertenciam a Hadadezer, o rei Davi levou grande quantidade de bronze, que Salomão utilizou para fazer o tanque de bronze, as colunas e vários utensílios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10900, 'nvi', '1 Crônicas', '1cr', 18, 9, 'Quando Toú, rei de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer, rei de Zobá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10901, 'nvi', '1 Crônicas', '1cr', 18, 10, 'enviou seu filho Hadorão ao rei Davi para saudá-lo e parabenizá-lo por sua vitória na batalha contra Hadadezer, que tinha estado em guerra com Toú. E, com Hadorão, mandou todo tipo de utensílios de ouro, de prata e de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10902, 'nvi', '1 Crônicas', '1cr', 18, 11, 'O rei Davi consagrou esses utensílios ao Senhor, como fizera com a prata e o ouro tomados de todas estas nações: Edom e Moabe, os amonitas e os filisteus, e Amaleque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10903, 'nvi', '1 Crônicas', '1cr', 18, 12, 'Abisai, filho de Zeruia, derrotou dezoito mil edomitas no vale do Sal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10904, 'nvi', '1 Crônicas', '1cr', 18, 13, 'Depois colocou guarnições militares em Edom, sujeitando todos os edomitas a Davi. O Senhor dava vitórias a Davi aonde quer que ele fosse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10905, 'nvi', '1 Crônicas', '1cr', 18, 14, 'Davi reinou sobre todo o Israel, administrando o direito e a justiça a todo o seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10906, 'nvi', '1 Crônicas', '1cr', 18, 15, 'Joabe, filho de Zeruia, era comandante do exército; Josafá, filho de Ailude, era o arquivista real;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10907, 'nvi', '1 Crônicas', '1cr', 18, 16, 'Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; Sausa era secretário;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10908, 'nvi', '1 Crônicas', '1cr', 18, 17, 'Benaia, filho de Joiada, comandava os queretitas e os peletitas; e os filhos do rei Davi eram seus principais oficiais.');
