-- Inserções para 1 Crônicas 20
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10928, 'nvi', '1 Crônicas', '1cr', 20, 1, 'Na primavera seguinte, na época em que os reis saem à guerra, Joabe conduziu o seu exército até a terra dos amonitas e a arrasou. Enquanto Davi ainda estava em Jerusalém, Joabe cercou Rabá, a capital, atacou-a e deixou-a em ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10929, 'nvi', '1 Crônicas', '1cr', 20, 2, 'Davi tirou a coroa da cabeça de Milcon, uma coroa de ouro de trinta e cinco quilos, ornamentada com pedras preciosas. E ela foi colocada na cabeça de Davi. Ele levou uma grande quantidade de bens da cidade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10930, 'nvi', '1 Crônicas', '1cr', 20, 3, 'e levou também os seus habitantes, designando-lhes trabalhos com serras, picaretas de ferro e machados. Davi fez assim com todas as cidades amonitas. Depois voltou com todo seu exército para Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10931, 'nvi', '1 Crônicas', '1cr', 20, 4, 'E houve depois disso uma guerra com os filisteus, em Gezer. Naquela época, Sibecai, de Husate, matou Sipai, um dos descendentes dos refains, e os filisteus foram subjugados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10932, 'nvi', '1 Crônicas', '1cr', 20, 5, 'Noutra batalha contra os filisteus, Elanã, filho de Jair, matou Lami, irmão de Golias, de Gate, que possuía uma lança cuja haste parecia uma lançadeira de tecelão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10933, 'nvi', '1 Crônicas', '1cr', 20, 6, 'Noutra batalha, em Gate, havia um homem de grande estatura e que tinha seis dedos em cada mão e seis dedos em cada pé; vinte e quatro dedos ao todo. Ele também era descendente de Rafa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10934, 'nvi', '1 Crônicas', '1cr', 20, 7, 'e ele desafiou Israel, mas Jônatas, filho de Siméia, irmão de Davi, o matou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (10935, 'nvi', '1 Crônicas', '1cr', 20, 8, 'Esses eram descendentes de Rafa, em Gate, e foram mortos por Davi e seus soldados.');
