-- Inserções para 1 João 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30542, 'nvi', '1 João', '1jo', 1, 1, 'O que era desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que contemplamos e as nossas mãos apalparam — isto proclamamos a respeito da Palavra da vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30543, 'nvi', '1 João', '1jo', 1, 2, 'A vida se manifestou; nós a vimos e dela testemunhamos, e proclamamos a vocês a vida eterna, que estava com o Pai e nos foi manifestada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30544, 'nvi', '1 João', '1jo', 1, 3, 'Nós lhes proclamamos o que vimos e ouvimos para que vocês também tenham comunhão conosco. Nossa comunhão é com o Pai e com seu Filho Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30545, 'nvi', '1 João', '1jo', 1, 4, 'Escrevemos estas coisas para que a nossa alegria seja completa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30546, 'nvi', '1 João', '1jo', 1, 5, 'Esta é a mensagem que dele ouvimos e transmitimos a vocês: Deus é luz; nele não há treva alguma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30547, 'nvi', '1 João', '1jo', 1, 6, 'Se afirmarmos que temos comunhão com ele, mas andamos nas trevas, mentimos e não praticamos a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30548, 'nvi', '1 João', '1jo', 1, 7, 'Se, porém, andamos na luz, como ele está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30549, 'nvi', '1 João', '1jo', 1, 8, 'Se afirmarmos que estamos sem pecado, enganamo-nos a nós mesmos, e a verdade não está em nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30550, 'nvi', '1 João', '1jo', 1, 9, 'Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30551, 'nvi', '1 João', '1jo', 1, 10, 'Se afirmarmos que não temos cometido pecado, fazemos de Deus um mentiroso, e a sua palavra não está em nós.');
