-- Inserções para 1 Reis 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8880, 'nvi', '1 Reis', '1rs', 5, 1, 'Quando Hirão, rei de Tiro, soube que Salomão tinha sido ungido rei, mandou seus conselheiros a Salomão, pois sempre tinha sido amigo leal de Davi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8881, 'nvi', '1 Reis', '1rs', 5, 2, 'Salomão enviou esta mensagem a Hirão:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8882, 'nvi', '1 Reis', '1rs', 5, 3, '"Tu bem sabes que foi por causa das guerras travadas de todos os lados contra meu pai Davi que ele não pôde construir um templo em honra do nome do Senhor, o seu Deus, até que o Senhor pusesse os seus inimigos debaixo dos seus pés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8883, 'nvi', '1 Reis', '1rs', 5, 4, 'Mas agora o Senhor, o meu Deus, concedeu-me paz em todas as fronteiras, e não tenho que enfrentar nem inimigos nem calamidades.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8884, 'nvi', '1 Reis', '1rs', 5, 5, 'Pretendo, por isso, construir um templo em honra do nome do Senhor, do meu Deus, conforme o Senhor disse a meu pai Davi: ‘O seu filho, a quem colocarei no trono em seu lugar, construirá o templo em honra do meu nome’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8885, 'nvi', '1 Reis', '1rs', 5, 6, '"Agora te peço que ordenes que cortem para mim cedros do Líbano. Os meus servos trabalharão com os teus, e eu pagarei a teus servos o salário que determinares. Sabes que não há entre nós ninguém tão hábil em cortar árvores quanto os sidônios".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8886, 'nvi', '1 Reis', '1rs', 5, 7, 'Hirão ficou muito alegre quando ouviu a mensagem de Salomão, e exclamou: "Bendito seja o Senhor, pois deu a Davi um filho sábio para governar essa grande nação".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8887, 'nvi', '1 Reis', '1rs', 5, 8, 'E Hirão respondeu a Salomão: "Recebi a mensagem que me enviaste e atenderei ao teu pedido, enviando-lhe madeira de cedro e de pinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8888, 'nvi', '1 Reis', '1rs', 5, 9, 'Meus servos levarão a madeira do Líbano até o mar, e eu a farei flutuar em jangadas no mar até o lugar que me indicares. Ali eu a deixarei e tu poderás levá-la. E em troca, fornecerás alimento para a minha corte".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8889, 'nvi', '1 Reis', '1rs', 5, 10, 'Assim Hirão se tornou fornecedor de toda a madeira de cedro e de pinho que Salomão desejava,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8890, 'nvi', '1 Reis', '1rs', 5, 11, 'e Salomão deu a Hirão vinte mil tonéis de trigo para suprir de mantimento a sua corte, além de vinte mil tonéis de azeite de oliva puro. Era o que Salomão dava anualmente a Hirão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8891, 'nvi', '1 Reis', '1rs', 5, 12, 'O Senhor deu sabedoria a Salomão, como lhe havia prometido. Houve paz entre Hirão e Salomão, e os dois fizeram um tratado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8892, 'nvi', '1 Reis', '1rs', 5, 13, 'O rei Salomão arregimentou trinta mil trabalhadores de todo o Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8893, 'nvi', '1 Reis', '1rs', 5, 14, 'Ele os mandou para o Líbano em grupos de dez mil por mês, e eles se revezavam: passavam um mês no Líbano e dois em casa. Adonirão chefiava o trabalho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8894, 'nvi', '1 Reis', '1rs', 5, 15, 'Salomão tinha setenta mil carregadores e oitenta mil cortadores de pedra nas colinas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8895, 'nvi', '1 Reis', '1rs', 5, 16, 'bem como três mil e trezentos capatazes que supervisionavam o trabalho e comandavam os operários.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8896, 'nvi', '1 Reis', '1rs', 5, 17, 'Por ordem do rei retiravam da pedreira grandes blocos de pedra de ótima qualidade para servirem de alicerce de pedras lavradas para o templo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8897, 'nvi', '1 Reis', '1rs', 5, 18, 'Os construtores de Salomão e de Hirão e os homens de Gebal cortavam e preparavam a madeira e as pedras para a construção do templo.');
