-- Inserções para 1 Samuel 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7353, 'nvi', '1 Samuel', '1sm', 7, 1, 'Então, os homens de Quiriate-Jearim vieram para levar a arca do Senhor. Eles a levaram para a casa de Abinadabe, na colina, e consagraram seu filho Eleazar para guardar a arca do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7354, 'nvi', '1 Samuel', '1sm', 7, 2, 'A arca permaneceu em Quiriate-Jearim muito tempo; foram vinte anos. E todo o povo de Israel buscava o Senhor com súplicas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7355, 'nvi', '1 Samuel', '1sm', 7, 3, 'E Samuel disse a toda a nação de Israel: "Se vocês querem voltar-se para o Senhor de todo o coração, livrem-se então dos deuses estrangeiros e dos postes sagrados, consagrem-se ao Senhor e prestem culto somente a ele, e ele os libertará das mãos dos filisteus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7356, 'nvi', '1 Samuel', '1sm', 7, 4, 'Assim, os israelitas se livraram dos baalins e dos postes sagrados, e começaram a prestar culto somente ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7357, 'nvi', '1 Samuel', '1sm', 7, 5, 'E Samuel prosseguiu: "Reúnam todo Israel em Mispá, e eu intercederei ao Senhor a favor de vocês".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7358, 'nvi', '1 Samuel', '1sm', 7, 6, 'Quando eles se reuniram em Mispá, tiraram água e a derramaram perante o Senhor. Naquele dia jejuaram e disseram ali: "Temos pecado contra o Senhor". E foi em Mispá que Samuel liderou os israelitas como juiz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7359, 'nvi', '1 Samuel', '1sm', 7, 7, 'Quando os filisteus souberam que os israelitas estavam reunidos em Mispá, os governantes dos filisteus saíram para atacá-los. Quando os israelitas souberam disso, ficaram com medo dos filisteus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7360, 'nvi', '1 Samuel', '1sm', 7, 8, 'E disseram a Samuel: "Não pare de clamar por nós ao Senhor nosso Deus, para que nos salve das mãos dos filisteus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7361, 'nvi', '1 Samuel', '1sm', 7, 9, 'Então Samuel pegou um cordeiro ainda não desmamado e o ofereceu inteiro como holocausto ao Senhor. Ele clamou ao Senhor em favor de Israel, e o Senhor lhe respondeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7362, 'nvi', '1 Samuel', '1sm', 7, 10, 'Enquanto Samuel oferecia o holocausto, os filisteus se aproximaram para combater Israel. Naquele dia, porém, o Senhor trovejou com fortíssimo estrondo contra os filisteus e os colocou em pânico. Então foram derrotados por Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7363, 'nvi', '1 Samuel', '1sm', 7, 11, 'Os soldados de Israel saíram de Mispá e perseguiram os filisteus até um lugar abaixo de Bete-Car, matando-os pelo caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7364, 'nvi', '1 Samuel', '1sm', 7, 12, 'Então Samuel pegou uma pedra e a ergueu entre Mispá e Sem; e deu-lhe o nome de Ebenézer, dizendo: "Até aqui o Senhor nos ajudou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7365, 'nvi', '1 Samuel', '1sm', 7, 13, 'Assim os filisteus foram dominados e não voltaram a invadir o território israelita. A mão do Senhor opôs-se aos filisteus durante toda a vida de Samuel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7366, 'nvi', '1 Samuel', '1sm', 7, 14, 'As cidades que os filisteus haviam conquistado, foram devolvidas a Israel, desde Ecrom até Gate. Israel libertou os territórios ao redor delas do poder dos filisteus. E houve também paz entre Israel e os amorreus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7367, 'nvi', '1 Samuel', '1sm', 7, 15, 'Samuel continuou como juiz de Israel durante todos os dias de sua vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7368, 'nvi', '1 Samuel', '1sm', 7, 16, 'A cada ano percorria Betel, Gilgal, e Mispá, decidindo as questões de Israel em todos esses lugares.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7369, 'nvi', '1 Samuel', '1sm', 7, 17, 'Mas sempre retornava a Ramá, onde ficava sua casa; ali ele liderava Israel como juiz e naquele lugar construiu um altar em honra do Senhor.');
