-- Inserções para 1 Samuel 11
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7446, 'nvi', '1 Samuel', '1sm', 11, 1, 'O amonita Naás avançou contra a cidade de Jabes-Gileade e a cercou. E os homens de Jabes lhe disseram: "Faça um tratado conosco, e nos sujeitaremos a você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7447, 'nvi', '1 Samuel', '1sm', 11, 2, 'Contudo, Naás, o amonita, respondeu: "Só farei um tratado com vocês sob a condição de que eu arranque o olho direito de cada um de vocês e assim humilhei todo o Israel".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7448, 'nvi', '1 Samuel', '1sm', 11, 3, 'As autoridades de Jabes lhe disseram: "Dê-nos sete dias para que possamos enviar mensageiros a todo Israel; se ninguém vier nos socorrer, nós nos renderemos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7449, 'nvi', '1 Samuel', '1sm', 11, 4, 'Quando os mensageiros chegaram a Gibeá, cidade de Saul, e relataram essas coisas ao povo, todos choraram em voz alta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7450, 'nvi', '1 Samuel', '1sm', 11, 5, 'Naquele momento, Saul estava trazendo o gado do campo e perguntou: "O que há com o povo? Por que estão chorando? " Então lhe contaram o que os homens de Jabes tinham dito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7451, 'nvi', '1 Samuel', '1sm', 11, 6, 'Quando Saul ouviu isso, o Espírito de Deus apoderou-se dele, e ele ficou furioso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7452, 'nvi', '1 Samuel', '1sm', 11, 7, 'Apanhou dois bois, cortou-os em pedaços e, por meio dos mensageiros, enviou os pedaços a todo o Israel, proclamando: "Isto é o que acontecerá aos bois de quem não seguir Saul e Samuel". Então o temor do Senhor caiu sobre o povo, e eles vieram unânimes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7453, 'nvi', '1 Samuel', '1sm', 11, 8, 'Quando Saul os reuniu em Bezeque, havia trezentos mil de Israel e trinta mil de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7454, 'nvi', '1 Samuel', '1sm', 11, 9, 'E disseram aos mensageiros de Jabes: "Digam aos homens de Jabes-Gileade: ‘Amanhã, na hora mais quente do dia, haverá libertação para vocês’ ". Quando relataram isso aos habitantes de Jabes, eles se alegraram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7455, 'nvi', '1 Samuel', '1sm', 11, 10, 'Então, os homens de Jabes disseram aos amonitas: "Amanhã nós nos renderemos a vocês, e poderão fazer conosco o que quiserem".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7456, 'nvi', '1 Samuel', '1sm', 11, 11, 'No dia seguinte, Saul dividiu seus soldados em três grupos; entraram no acampamento amonita na alta madrugada e os mataram até a hora mais quente do dia. Aqueles que sobreviveram se dispersaram, de modo que não ficaram dois juntos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7457, 'nvi', '1 Samuel', '1sm', 11, 12, 'Então o povo disse a Samuel: "Quem foi que perguntou: ‘Será que Saul vai reinar sobre nós? ’ Traga-nos esses homens, e nós os mataremos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7458, 'nvi', '1 Samuel', '1sm', 11, 13, 'Saul, porém, disse: "Hoje ninguém será morto, pois neste dia o Senhor trouxe libertação a Israel".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7459, 'nvi', '1 Samuel', '1sm', 11, 14, 'Então Samuel disse ao povo: "Venham, vamos a Gilgal e reafirmemos ali o reino".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7460, 'nvi', '1 Samuel', '1sm', 11, 15, 'Assim, todo o povo foi a Gilgal e proclamou Saul como rei na presença do Senhor. Ali ofereceram sacrifícios de comunhão ao Senhor, e Saul e todos os israelitas se alegraram muito.');
