-- Inserções para 1 Samuel 27
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7932, 'nvi', '1 Samuel', '1sm', 27, 1, 'Davi, contudo, pensou: "Algum dia serei morto por Saul. É melhor fugir para a terra dos filisteus. Então Saul desistirá de procurar-me por todo o Israel, e escaparei dele".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7933, 'nvi', '1 Samuel', '1sm', 27, 2, 'Assim, Davi e os seiscentos homens que estavam com ele foram até Aquis, filho de Maoque, rei de Gate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7934, 'nvi', '1 Samuel', '1sm', 27, 3, 'Davi e seus soldados se estabeleceram com Aquis, em Gate. Cada homem levou sua família, e Davi, suas duas mulheres, Ainoã, de Jezreel, e Abigail, mulher de Nabal, de Carmelo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7935, 'nvi', '1 Samuel', '1sm', 27, 4, 'Quando contaram a Saul que Davi havia fugido para Gate, ele parou de persegui-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7936, 'nvi', '1 Samuel', '1sm', 27, 5, 'Então Davi disse a Aquis: "Se eu conto com a sua simpatia, dá-me um lugar numa das cidades desta terra onde eu possa viver. Por que este teu servo viveria contigo na cidade real? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7937, 'nvi', '1 Samuel', '1sm', 27, 6, 'Naquele dia Aquis deu-lhe Ziclague. Por isso, Ziclague pertence aos reis de Judá até hoje.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7938, 'nvi', '1 Samuel', '1sm', 27, 7, 'Davi morou em território filisteu durante um ano e quatro meses.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7939, 'nvi', '1 Samuel', '1sm', 27, 8, 'Davi e seus soldados atacavam os gesuritas, os gersitas e os amalequitas, povos que, desde tempos antigos, habitavam a terra que se estende de Sur até o Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7940, 'nvi', '1 Samuel', '1sm', 27, 9, 'Quando Davi atacava a região, não poupava homens nem mulheres, e tomava ovelhas, bois, jumentos, camelos e roupas. Então retornava a Aquis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7941, 'nvi', '1 Samuel', '1sm', 27, 10, 'Quando Aquis perguntava: "Onde você atacou hoje? " Davi respondia: "O Neguebe de Judá" ou "O Neguebe de Jerameel" ou "O Neguebe dos queneus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7942, 'nvi', '1 Samuel', '1sm', 27, 11, 'Ele matava a todos, homens e mulheres, para que não fossem levados a Gate, pois pensava: "Eles poderão denunciar-me". Este foi o seu procedimento enquanto viveu em território filisteu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7943, 'nvi', '1 Samuel', '1sm', 27, 12, 'Aquis confiava em Davi e dizia: "Ele se tornou tão odiado por seu povo, os israelitas, que será meu servo para sempre".');
