-- Inserções para 1 Samuel 21
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7774, 'nvi', '1 Samuel', '1sm', 21, 1, 'Davi foi falar com o sacerdote Aimeleque, em Nobe. Aimeleque tremia quando se encontrou com ele, e perguntou: "Por que você está sozinho? Ninguém veio com você? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7775, 'nvi', '1 Samuel', '1sm', 21, 2, 'Respondeu Davi: "O rei me encarregou de uma certa missão e me disse: ‘Ninguém deve saber coisa alguma sobre sua missão e sobre as suas instruções’. E eu ordenei aos meus soldados que se encontrassem comigo num certo lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7776, 'nvi', '1 Samuel', '1sm', 21, 3, 'Agora, então, o que você pode oferecer-me? Dê-me cinco pães ou algo que tiver".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7777, 'nvi', '1 Samuel', '1sm', 21, 4, 'O sacerdote, contudo, respondeu a Davi: "Não tenho pão comum; somente pão consagrado; se os soldados não tiveram relações com mulheres recentemente podem comê-lo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7778, 'nvi', '1 Samuel', '1sm', 21, 5, 'Davi respondeu: "Certamente que não, conforme o nosso costume sempre que saio em campanha. Não tocamos em mulher. Esses homens mantém o corpo puro mesmo em missões comuns. Quanto mais hoje! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7779, 'nvi', '1 Samuel', '1sm', 21, 6, 'Então, o sacerdote lhe deu os pães consagrados, visto que não havia outro além do pão da Presença, que era retirado de diante do Senhor e substituído por pão quente no dia em que era tirado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7780, 'nvi', '1 Samuel', '1sm', 21, 7, 'Aconteceu que um dos servos de Saul estava ali naquele dia, cumprindo seus deveres diante do Senhor; era o edomita Doegue, chefe dos pastores de Saul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7781, 'nvi', '1 Samuel', '1sm', 21, 8, 'Davi perguntou a Aimeleque: "Você tem uma lança ou uma espada aqui? Não trouxe minha espada nem qualquer outra arma, pois o rei exigiu urgência".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7782, 'nvi', '1 Samuel', '1sm', 21, 9, 'O sacerdote respondeu: "A espada de Golias, o filisteu que você matou no vale de Elá, está enrolada num pano atrás do colete sacerdotal. Se quiser, pegue-a; não há nenhuma outra espada". Davi disse: "Não há outra melhor; dê-me essa espada".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7783, 'nvi', '1 Samuel', '1sm', 21, 10, 'Naquele dia, Davi fugiu de Saul e foi procurar Aquis, rei de Gate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7784, 'nvi', '1 Samuel', '1sm', 21, 11, 'Todavia os conselheiros de Aquis lhe disseram: "Não é este Davi, o rei da terra de Israel? Não é aquele sobre quem cantavam em suas danças: ‘Saul abateu seus milhares, e Davi suas dezenas de milhares’? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7785, 'nvi', '1 Samuel', '1sm', 21, 12, 'Davi levou a sério aquelas palavras e ficou com muito medo de Aquis, rei de Gate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7786, 'nvi', '1 Samuel', '1sm', 21, 13, 'Por isso, na presença deles ele fingiu estar louco; enquanto esteve com eles, agiu como um louco, riscando as portas da cidade e deixando escorrer saliva pela barba.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7787, 'nvi', '1 Samuel', '1sm', 21, 14, 'Aquis disse a seus conselheiros: "Vejam este homem! Ele está louco! Por que trazê-lo aqui?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7788, 'nvi', '1 Samuel', '1sm', 21, 15, 'Será que me faltam loucos para que vocês o tragam para agir como doido na minha frente? O que ele veio fazer no meu palácio? "');
