-- Inserções para 1 Samuel 31
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8011, 'nvi', '1 Samuel', '1sm', 31, 1, 'E aconteceu que, em combate com os filisteus, os israelitas foram postos em fuga e muitos caíram mortos no monte Gilboa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8012, 'nvi', '1 Samuel', '1sm', 31, 2, 'Os filisteus perseguiram Saul e seus filhos, e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8013, 'nvi', '1 Samuel', '1sm', 31, 3, 'O combate foi se tornando cada vez mais violento em torno de Saul, até que os flecheiros o alcançaram e o feriram gravemente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8014, 'nvi', '1 Samuel', '1sm', 31, 4, 'Então Saul ordenou ao seu escudeiro: "Tire sua espada e mate-me com ela, senão sofrerei a vergonha de cair nas mãos desses incircuncisos". Mas seu escudeiro estava apavorado e não quis fazê-lo. Saul, então, pegou a própria espada e jogou-se sobre ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8015, 'nvi', '1 Samuel', '1sm', 31, 5, 'Quando o escudeiro viu que Saul estava morto, jogou-se também sobre sua espada e morreu com ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8016, 'nvi', '1 Samuel', '1sm', 31, 6, 'De maneira que Saul, seus três filhos, seu escudeiro e todos os seus soldados morreram juntos naquele dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8017, 'nvi', '1 Samuel', '1sm', 31, 7, 'Quando os israelitas que habitavam do outro lado do vale e a leste do Jordão viram que o exército tinha fugido, e que Saul e seus filhos estavam mortos, fugiram abandonando suas cidades. Depois os filisteus foram ocupá-las.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8018, 'nvi', '1 Samuel', '1sm', 31, 8, 'No dia seguinte, quando os filisteus foram saquear os mortos, encontraram Saul e seus três filhos caídos no monte Gilboa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8019, 'nvi', '1 Samuel', '1sm', 31, 9, 'Cortaram a cabeça de Saul, pegaram suas armas, e enviaram mensageiros por toda a terra dos filisteus proclamando a notícia nos templos de seus ídolos e entre seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8020, 'nvi', '1 Samuel', '1sm', 31, 10, 'Expuseram as armas de Saul no templo dos postes sagrados e penduraram seu corpo no muro de Bete-Seã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8021, 'nvi', '1 Samuel', '1sm', 31, 11, 'Quando os habitantes de Jabes-Gileade ficaram sabendo do que os filisteus tinham feito com Saul,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8022, 'nvi', '1 Samuel', '1sm', 31, 12, 'os mais corajosos dentre eles foram durante a noite a Bete-Seã. Baixaram os corpos de Saul e de seus filhos do muro de Bete-Seã e foram para Jabes, onde os queimaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8023, 'nvi', '1 Samuel', '1sm', 31, 13, 'Depois enterraram seus ossos debaixo de uma tamargueira em Jabes, e jejuaram por sete dias.');
