-- Inserções para 1 Samuel 29
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7969, 'nvi', '1 Samuel', '1sm', 29, 1, 'Os filisteus reuniram todas as suas tropas em Afeque, e Israel acampou junto à fonte em Jezreel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7970, 'nvi', '1 Samuel', '1sm', 29, 2, 'Enquanto os governantes filisteus avançavam com seus grupos de cem e de mil, Davi e seus homens iam na retaguarda com Aquis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7971, 'nvi', '1 Samuel', '1sm', 29, 3, 'Os comandantes dos filisteus perguntaram: "O que estes hebreus fazem aqui? " Aquis respondeu: "Este é Davi, que era oficial de Saul, rei de Israel. Ele já está comigo há mais de um ano, e desde o dia em que deixou Saul nada fez que mereça desconfiança".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7972, 'nvi', '1 Samuel', '1sm', 29, 4, 'Contudo, os comandantes filisteus se iraram contra ele e disseram: "Mande embora este homem para a cidade que você lhe designou. Ele não deve ir para a guerra conosco, senão se tornará nosso adversário durante o combate. Qual seria a melhor maneira de recuperar a boa vontade de seu senhor, senão às custas das cabeças de nossos homens?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7973, 'nvi', '1 Samuel', '1sm', 29, 5, 'Não é ele o Davi de quem cantavam em suas danças: ‘Saul abateu seus milhares, e Davi suas dezenas de milhares’? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7974, 'nvi', '1 Samuel', '1sm', 29, 6, 'Então Aquis chamou a Davi e lhe disse: "Juro pelo nome do Senhor que você tem sido leal, e ficaria contente em tê-lo servindo comigo no exército. Desde o dia em que você veio a mim, nunca desconfiei de você, mas os governantes não o aprovam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7975, 'nvi', '1 Samuel', '1sm', 29, 7, 'Agora, volte e vá em paz! Não faça nada que desagrade os governantes filisteus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7976, 'nvi', '1 Samuel', '1sm', 29, 8, 'Davi perguntou: "O que foi que eu fiz? O que descobriste contra teu servo, desde o dia em que cheguei? Por que não posso ir e lutar contra os inimigos do rei, meu senhor? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7977, 'nvi', '1 Samuel', '1sm', 29, 9, 'Aquis respondeu: "Reconheço que você tem feito o que eu aprovo, como um anjo de Deus. Os comandantes filisteus, no entanto, dizem que você não deve ir à batalha conosco.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7978, 'nvi', '1 Samuel', '1sm', 29, 10, 'Agora, levante-se bem cedo, junto com os servos de seu senhor que vieram com você, e partam de manhã, assim que clarear o dia".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7979, 'nvi', '1 Samuel', '1sm', 29, 11, 'Então Davi e seus soldados levantaram-se de madrugada para voltar à terra dos filisteus. Os filisteus, porém, foram para Jezreel.');
