-- Inserções para 1 Timóteo 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29749, 'nvi', '1 Timóteo', '1tm', 4, 1, 'O Espírito diz claramente que nos últimos tempos alguns abandonarão a fé e seguirão espíritos enganadores e doutrinas de demônios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29750, 'nvi', '1 Timóteo', '1tm', 4, 2, 'Tais ensinamentos vêm de homens hipócritas e mentirosos, que têm a consciência cauterizada');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29751, 'nvi', '1 Timóteo', '1tm', 4, 3, 'e proíbem o casamento e o consumo de alimentos que Deus criou para serem recebidos com ação de graças pelos que crêem e conhecem a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29752, 'nvi', '1 Timóteo', '1tm', 4, 4, 'Pois tudo o que Deus criou é bom, e nada deve ser rejeitado, se for recebido com ação de graças,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29753, 'nvi', '1 Timóteo', '1tm', 4, 5, 'pois é santificado pela palavra de Deus e pela oração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29754, 'nvi', '1 Timóteo', '1tm', 4, 6, 'Se você transmitir essas instruções aos irmãos, será um bom ministro de Cristo Jesus, nutrido com as verdades da fé e da boa doutrina que tem seguido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29755, 'nvi', '1 Timóteo', '1tm', 4, 7, 'Rejeite, porém, as fábulas profanas de velhas e exercite-se na piedade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29756, 'nvi', '1 Timóteo', '1tm', 4, 8, 'O exercício físico é de pouco proveito; a piedade, porém, para tudo é proveitosa, porque tem promessa da vida presente e da futura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29757, 'nvi', '1 Timóteo', '1tm', 4, 9, 'Esta é uma afirmação fiel e digna de plena aceitação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29758, 'nvi', '1 Timóteo', '1tm', 4, 10, 'Se trabalhamos e lutamos é porque temos colocado a nossa esperança no Deus vivo, o Salvador de todos os homens, especialmente dos que crêem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29759, 'nvi', '1 Timóteo', '1tm', 4, 11, 'Ordene e ensine estas coisas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29760, 'nvi', '1 Timóteo', '1tm', 4, 12, 'Ninguém o despreze pelo fato de você ser jovem, mas seja um exemplo para os fiéis na palavra, no procedimento, no amor, na fé e na pureza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29761, 'nvi', '1 Timóteo', '1tm', 4, 13, 'Até a minha chegada, dedique-se à leitura pública da Escritura, à exortação e ao ensino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29762, 'nvi', '1 Timóteo', '1tm', 4, 14, 'Não negligencie o dom que lhe foi dado por mensagem profética com imposição de mãos dos presbíteros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29763, 'nvi', '1 Timóteo', '1tm', 4, 15, 'Seja diligente nestas coisas; dedique-se inteiramente a elas, para que todos vejam o seu progresso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29764, 'nvi', '1 Timóteo', '1tm', 4, 16, 'Atente bem para a sua própria vida e para a doutrina, perseverando nesses deveres, pois, fazendo isso, você salvará tanto a si mesmo quanto aos que o ouvem.');
