-- Inserções para 1 Timóteo 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29733, 'nvi', '1 Timóteo', '1tm', 3, 1, 'Esta afirmação é digna de confiança: se alguém deseja ser bispo, deseja uma nobre função.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29734, 'nvi', '1 Timóteo', '1tm', 3, 2, 'É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, sóbrio, prudente, respeitável, hospitaleiro e apto para ensinar;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29735, 'nvi', '1 Timóteo', '1tm', 3, 3, 'não deve ser apegado ao vinho, nem violento, mas sim amável, pacífico e não apegado ao dinheiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29736, 'nvi', '1 Timóteo', '1tm', 3, 4, 'Ele deve governar bem sua própria família, tendo os filhos sujeitos a ele, com toda a dignidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29737, 'nvi', '1 Timóteo', '1tm', 3, 5, 'Pois, se alguém não sabe governar sua própria família, como poderá cuidar da igreja de Deus?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29738, 'nvi', '1 Timóteo', '1tm', 3, 6, 'Não pode ser recém-convertido, para que não se ensoberbeça e caia na mesma condenação em que caiu o diabo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29739, 'nvi', '1 Timóteo', '1tm', 3, 7, 'Também deve ter boa reputação perante os de fora, para que não caia em descrédito nem na cilada do diabo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29740, 'nvi', '1 Timóteo', '1tm', 3, 8, 'Os diáconos igualmente devem ser dignos, homens de palavra, não amigos de muito vinho nem de lucros desonestos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29741, 'nvi', '1 Timóteo', '1tm', 3, 9, 'Devem apegar-se ao mistério da fé com a consciência limpa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29742, 'nvi', '1 Timóteo', '1tm', 3, 10, 'Devem ser primeiramente experimentados; depois, se não houver nada contra eles, que atuem como diáconos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29743, 'nvi', '1 Timóteo', '1tm', 3, 11, 'As mulheres igualmente sejam dignas, não caluniadoras, mas sóbrias e confiáveis em tudo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29744, 'nvi', '1 Timóteo', '1tm', 3, 12, 'O diácono deve ser marido de uma só mulher e governar bem seus filhos e sua própria casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29745, 'nvi', '1 Timóteo', '1tm', 3, 13, 'Os que servirem bem alcançarão uma excelente posição e grande determinação na fé em Cristo Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29746, 'nvi', '1 Timóteo', '1tm', 3, 14, 'Escrevo-lhe estas coisas embora espere ir vê-lo em breve;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29747, 'nvi', '1 Timóteo', '1tm', 3, 15, 'mas, se eu demorar, saiba como as pessoas devem comportar-se na casa de Deus, que é a igreja do Deus vivo, coluna e fundamento da verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29748, 'nvi', '1 Timóteo', '1tm', 3, 16, 'Não há dúvida de que é grande o mistério da piedade: Deus foi manifestado em corpo, justificado no Espírito, visto pelos anjos, pregado entre as nações, crido no mundo, recebido na glória.');
