-- Inserções para 1 Tessalonicenses 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29605, 'nvi', '1 Tessalonicenses', '1ts', 4, 1, 'Quanto ao mais, irmãos, já os instruímos acerca de como viver a fim de agradar a Deus e, de fato, assim vocês estão procedendo. Agora lhes pedimos e exortamos no Senhor Jesus que cresçam nisso cada vez mais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29606, 'nvi', '1 Tessalonicenses', '1ts', 4, 2, 'Pois vocês conhecem os mandamentos que lhes demos pela autoridade do Senhor Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29607, 'nvi', '1 Tessalonicenses', '1ts', 4, 3, 'A vontade de Deus é que vocês sejam santificados: abstenham-se da imoralidade sexual.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29608, 'nvi', '1 Tessalonicenses', '1ts', 4, 4, 'Cada um saiba controlar o próprio corpo de maneira santa e honrosa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29609, 'nvi', '1 Tessalonicenses', '1ts', 4, 5, 'não com a paixão de desejo desenfreado, como os pagãos que desconhecem a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29610, 'nvi', '1 Tessalonicenses', '1ts', 4, 6, 'Neste assunto, ninguém prejudique a seu irmão nem dele se aproveite. O Senhor castigará todas essas práticas, como já lhes dissemos e asseguramos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29611, 'nvi', '1 Tessalonicenses', '1ts', 4, 7, 'Porque Deus não nos chamou para a impureza, mas para a santidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29612, 'nvi', '1 Tessalonicenses', '1ts', 4, 8, 'Portanto, aquele que rejeita estas coisas não está rejeitando o homem, mas a Deus, que lhes dá o seu Espírito Santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29613, 'nvi', '1 Tessalonicenses', '1ts', 4, 9, 'Quanto ao amor fraternal, não precisamos escrever-lhes, pois vocês mesmos já foram ensinados por Deus a se amarem uns aos outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29614, 'nvi', '1 Tessalonicenses', '1ts', 4, 10, 'E, de fato, vocês amam a todos os irmãos em toda a Macedônia. Contudo, irmãos, insistimos com vocês que cada vez mais assim procedam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29615, 'nvi', '1 Tessalonicenses', '1ts', 4, 11, 'Esforcem-se para ter uma vida tranqüila, cuidar dos seus próprios negócios e trabalhar com as próprias mãos, como nós os instruímos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29616, 'nvi', '1 Tessalonicenses', '1ts', 4, 12, 'a fim de que andem decentemente aos olhos dos que são de fora e não dependam de ninguém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29617, 'nvi', '1 Tessalonicenses', '1ts', 4, 13, 'Irmãos, não queremos que vocês sejam ignorantes quanto aos que dormem, para que não se entristeçam como os outros que não têm esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29618, 'nvi', '1 Tessalonicenses', '1ts', 4, 14, 'Se cremos que Jesus morreu e ressurgiu, cremos também que Deus trará, mediante Jesus e juntamente com ele, aqueles que nele dormiram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29619, 'nvi', '1 Tessalonicenses', '1ts', 4, 15, 'Dizemos a vocês, pela palavra do Senhor, que nós, os que estivermos vivos, os que ficarmos até a vinda do Senhor, certamente não precederemos os que dormem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29620, 'nvi', '1 Tessalonicenses', '1ts', 4, 16, 'Pois, dada a ordem, com a voz do arcanjo e o ressoar da trombeta de Deus, o próprio Senhor descerá do céu, e os mortos em Cristo ressuscitarão primeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29621, 'nvi', '1 Tessalonicenses', '1ts', 4, 17, 'Depois disso, os que estivermos vivos seremos arrebatados juntamente com eles nas nuvens, para o encontro com o Senhor nos ares. E assim estaremos com o Senhor para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29622, 'nvi', '1 Tessalonicenses', '1ts', 4, 18, 'Consolem-se uns aos outros com estas palavras.');
