-- Inserções para 1 Tessalonicenses 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29562, 'nvi', '1 Tessalonicenses', '1ts', 1, 1, 'Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus Pai e no Senhor Jesus Cristo: A vocês, graça e paz da parte de Deus e de nosso Senhor Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29563, 'nvi', '1 Tessalonicenses', '1ts', 1, 2, 'Sempre damos graças a Deus por todos vocês, mencionando-os em nossas orações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29564, 'nvi', '1 Tessalonicenses', '1ts', 1, 3, 'Lembramos continuamente, diante de nosso Deus e Pai, o que vocês têm demonstrado: o trabalho que resulta da fé, o esforço motivado pelo amor e a perseverança proveniente da esperança em nosso Senhor Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29565, 'nvi', '1 Tessalonicenses', '1ts', 1, 4, 'Sabemos, irmãos, amados de Deus, que ele os escolheu');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29566, 'nvi', '1 Tessalonicenses', '1ts', 1, 5, 'porque o nosso evangelho não chegou a vocês somente em palavra, mas também em poder, no Espírito Santo e em plena convicção. Vocês sabem como procedemos entre vocês, em seu favor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29567, 'nvi', '1 Tessalonicenses', '1ts', 1, 6, 'De fato, vocês se tornaram nossos imitadores e do Senhor; apesar de muito sofrimento, receberam a palavra com alegria que vem do Espírito Santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29568, 'nvi', '1 Tessalonicenses', '1ts', 1, 7, 'E, assim, tornaram-se modelo para todos os crentes que estão na Macedônia e na Acaia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29569, 'nvi', '1 Tessalonicenses', '1ts', 1, 8, 'Porque, partindo de vocês, propagou-se a mensagem do Senhor na Macedônia e na Acaia. Não somente isso, mas também por toda parte tornou-se conhecida a fé que vocês têm em Deus. O resultado é que não temos necessidade de dizer mais nada sobre isso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29570, 'nvi', '1 Tessalonicenses', '1ts', 1, 9, 'pois eles mesmos relatam de que maneira vocês nos receberam, como se voltaram para Deus, deixando os ídolos a fim de servir ao Deus vivo e verdadeiro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29571, 'nvi', '1 Tessalonicenses', '1ts', 1, 10, 'e esperar dos céus a seu Filho, a quem ressuscitou dos mortos: Jesus, que nos livra da ira que há de vir.');
