-- Inserções para 1 Tessalonicenses 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29592, 'nvi', '1 Tessalonicenses', '1ts', 3, 1, 'Por isso, quando não pudemos mais suportar, achamos por bem permanecer sozinhos em Atenas');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29593, 'nvi', '1 Tessalonicenses', '1ts', 3, 2, 'e, assim, enviamos Timóteo, nosso irmão e cooperador de Deus no evangelho de Cristo, para fortalecê-los e dar-lhes ânimo na fé,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29594, 'nvi', '1 Tessalonicenses', '1ts', 3, 3, 'para que ninguém seja abalado por essas tribulações. Vocês sabem muito bem que fomos designados para isso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29595, 'nvi', '1 Tessalonicenses', '1ts', 3, 4, 'Quando estávamos com vocês, já lhes dizíamos que seríamos perseguidos, o que realmente aconteceu, como vocês sabem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29596, 'nvi', '1 Tessalonicenses', '1ts', 3, 5, 'Por essa razão, não suportando mais, enviei Timóteo para saber a respeito da fé que vocês têm, a fim de que o tentador não os seduzisse, tornando inútil o nosso esforço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29597, 'nvi', '1 Tessalonicenses', '1ts', 3, 6, 'Agora, porém, Timóteo acaba de chegar da parte de vocês, dando-nos boas notícias a respeito da fé e do amor que vocês têm. Ele nos falou que vocês sempre guardam boas recordações de nós, desejando ver-nos, assim como nós queremos vê-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29598, 'nvi', '1 Tessalonicenses', '1ts', 3, 7, 'Por isso, irmãos, em toda a nossa necessidade e tribulação temos bom ânimo a seu respeito, por sabermos da sua fé;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29599, 'nvi', '1 Tessalonicenses', '1ts', 3, 8, 'pois agora vivemos, visto que vocês estão firmes no Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29600, 'nvi', '1 Tessalonicenses', '1ts', 3, 9, 'Como podemos ser suficientemente gratos a Deus por vocês, por toda a alegria que temos diante dele por causa de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29601, 'nvi', '1 Tessalonicenses', '1ts', 3, 10, 'Noite e dia com perseverança oramos para que possamos vê-los pessoalmente e suprir o que falta à sua fé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29602, 'nvi', '1 Tessalonicenses', '1ts', 3, 11, 'Que o próprio Deus, nosso Pai, e nosso Senhor Jesus preparem o nosso caminho até vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29603, 'nvi', '1 Tessalonicenses', '1ts', 3, 12, 'Que o Senhor faça crescer e transbordar o amor que vocês têm uns para com os outros e para com todos, a exemplo do nosso amor por vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29604, 'nvi', '1 Tessalonicenses', '1ts', 3, 13, 'Que ele fortaleça os seus corações para serem irrepreensíveis em santidade diante de nosso Deus e Pai, na vinda de nosso Senhor Jesus com todos os seus santos.');
