-- Inserções para 2 Coríntios 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28843, 'nvi', '2 Coríntios', '2co', 3, 1, 'Será que com isso, estamos começando a nos recomendar a nós mesmos novamente? Será que precisamos, como alguns, de cartas de recomendação para vocês ou da parte de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28844, 'nvi', '2 Coríntios', '2co', 3, 2, 'Vocês mesmos são a nossa carta, escrita em nosso coração, conhecida e lida por todos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28845, 'nvi', '2 Coríntios', '2co', 3, 3, 'Vocês demonstram que são uma carta de Cristo, resultado do nosso ministério, escrita não com tinta, mas com o Espírito do Deus vivo, não em tábuas de pedra, mas em tábuas de corações humanos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28846, 'nvi', '2 Coríntios', '2co', 3, 4, 'Tal é a confiança que temos diante de Deus, por meio de Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28847, 'nvi', '2 Coríntios', '2co', 3, 5, 'Não que possamos reivindicar qualquer coisa com base em nossos próprios méritos, mas a nossa capacidade vem de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28848, 'nvi', '2 Coríntios', '2co', 3, 6, 'Ele nos capacitou para sermos ministros de uma nova aliança, não da letra, mas do Espírito; pois a letra mata, mas o Espírito vivifica.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28849, 'nvi', '2 Coríntios', '2co', 3, 7, 'O ministério que trouxe a morte foi gravado com letras em pedras; mas esse ministério veio com tal glória que os israelitas não podiam fixar os olhos na face de Moisés por causa do resplendor do seu rosto, ainda que desvanecente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28850, 'nvi', '2 Coríntios', '2co', 3, 8, 'Não será o ministério do Espírito ainda muito mais glorioso?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28851, 'nvi', '2 Coríntios', '2co', 3, 9, 'Se era glorioso o ministério que trouxe condenação, quanto mais glorioso será o ministério que produz justiça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28852, 'nvi', '2 Coríntios', '2co', 3, 10, 'Pois o que outrora foi glorioso, agora não tem glória, em comparação com a glória insuperável.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28853, 'nvi', '2 Coríntios', '2co', 3, 11, 'E se o que estava se desvanecendo se manifestou com glória, quanto maior será a glória do que permanece!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28854, 'nvi', '2 Coríntios', '2co', 3, 12, 'Portanto, visto que temos tal esperança, mostramos muita confiança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28855, 'nvi', '2 Coríntios', '2co', 3, 13, 'Não somos como Moisés, que colocava um véu sobre a face para que os israelitas não contemplassem o resplendor que se desvanecia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28856, 'nvi', '2 Coríntios', '2co', 3, 14, 'Na verdade as mentes deles se fecharam, pois até hoje o mesmo véu permanece quando é lida a antiga aliança. Não foi retirado, porque é somente em Cristo que ele é removido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28857, 'nvi', '2 Coríntios', '2co', 3, 15, 'De fato, até o dia de hoje, quando Moisés é lido, um véu cobre os seus corações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28858, 'nvi', '2 Coríntios', '2co', 3, 16, 'Mas quando alguém se converte ao Senhor, o véu é retirado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28859, 'nvi', '2 Coríntios', '2co', 3, 17, 'Ora, o Senhor é o Espírito e, onde está o Espírito do Senhor, ali há liberdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28860, 'nvi', '2 Coríntios', '2co', 3, 18, 'E todos nós, que com a face descoberta contemplamos a glória do Senhor, segundo a sua imagem estamos sendo transformados com glória cada vez maior, a qual vem do Senhor, que é o Espírito.');
