-- Inserções para 2 Coríntios 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28958, 'nvi', '2 Coríntios', '2co', 9, 1, 'Não tenho necessidade de escrever-lhes a respeito dessa assistência aos santos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28959, 'nvi', '2 Coríntios', '2co', 9, 2, 'Reconheço a sua disposição em ajudar e já mostrei aos macedônios o orgulho que tenho de vocês, dizendo-lhes que, desde o ano passado, vocês da Acaia estavam prontos a contribuir; e a dedicação de vocês motivou a muitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28960, 'nvi', '2 Coríntios', '2co', 9, 3, 'Contudo, estou enviando os irmãos para que o orgulho que temos de vocês a esse respeito não seja em vão, mas que vocês estejam preparados, como eu disse que estariam,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28961, 'nvi', '2 Coríntios', '2co', 9, 4, 'a fim de que, se alguns macedônios forem comigo e os encontrarem despreparados, nós, para não mencionar vocês, não fiquemos envergonhados por tanta confiança que tivemos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28962, 'nvi', '2 Coríntios', '2co', 9, 5, 'Assim, achei necessário recomendar que os irmãos os visitem antes e concluam os preparativos para a contribuição que vocês prometeram. Então ela estará pronta como oferta generosa, e não como algo dado com avareza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28963, 'nvi', '2 Coríntios', '2co', 9, 6, 'Lembrem-se: aquele que semeia pouco, também colherá pouco, e aquele que semeia com fartura, também colherá fartamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28964, 'nvi', '2 Coríntios', '2co', 9, 7, 'Cada um dê conforme determinou em seu coração, não com pesar ou por obrigação, pois Deus ama quem dá com alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28965, 'nvi', '2 Coríntios', '2co', 9, 8, 'E Deus é poderoso para fazer que lhes seja acrescentada toda a graça, para que em todas as coisas, em todo o tempo, tendo tudo o que é necessário, vocês transbordem em toda boa obra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28966, 'nvi', '2 Coríntios', '2co', 9, 9, 'Como está escrito: "Distribuiu, deu os seus bens aos necessitados; a sua justiça dura para sempre".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28967, 'nvi', '2 Coríntios', '2co', 9, 10, 'Aquele que supre a semente ao que semeia e o pão ao que come, também lhes suprirá e aumentará a semente e fará crescer os frutos da sua justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28968, 'nvi', '2 Coríntios', '2co', 9, 11, 'Vocês serão enriquecidos de todas as formas, para que possam ser generosos em qualquer ocasião e, por nosso intermédio, a sua generosidade resulte em ação de graças a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28969, 'nvi', '2 Coríntios', '2co', 9, 12, 'O serviço ministerial que vocês estão realizando não está apenas suprindo as necessidades do povo de Deus, mas também transbordando em muitas expressões de gratidão a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28970, 'nvi', '2 Coríntios', '2co', 9, 13, 'Por meio dessa prova de serviço ministerial, outros louvarão a Deus pela obediência que acompanha a confissão que vocês fazem do evangelho de Cristo e pela generosidade de vocês em compartilhar seus bens com eles e com todos os outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28971, 'nvi', '2 Coríntios', '2co', 9, 14, 'E nas orações que fazem por vocês, eles estarão cheios de amor por vocês, por causa da insuperável graça que Deus tem dado a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28972, 'nvi', '2 Coríntios', '2co', 9, 15, 'Graças a Deus por seu dom indescritível!');
