-- Inserções para 2 Coríntios 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28900, 'nvi', '2 Coríntios', '2co', 6, 1, 'Como cooperadores de Deus, insistimos com vocês para não receberem em vão a graça de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28901, 'nvi', '2 Coríntios', '2co', 6, 2, 'Pois ele diz: "Eu o ouvi no tempo favorável e o socorri no dia da salvação". Digo-lhes que agora é o tempo favorável, agora é o dia da salvação!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28902, 'nvi', '2 Coríntios', '2co', 6, 3, 'Não damos motivo de escândalo a ninguém, em circunstância alguma, para que o nosso ministério não caia em descrédito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28903, 'nvi', '2 Coríntios', '2co', 6, 4, 'Pelo contrário, como servos de Deus, recomendamo-nos de todas as formas: em muita perseverança; em sofrimentos, privações e tristezas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28904, 'nvi', '2 Coríntios', '2co', 6, 5, 'em açoites, prisões e tumultos; em trabalhos árduos, noites sem dormir e jejuns;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28905, 'nvi', '2 Coríntios', '2co', 6, 6, 'em pureza, conhecimento, paciência e bondade; no Espírito Santo e no amor sincero;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28906, 'nvi', '2 Coríntios', '2co', 6, 7, 'na palavra da verdade e no poder de Deus; com as armas da justiça, quer de ataque, quer de defesa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28907, 'nvi', '2 Coríntios', '2co', 6, 8, 'por honra e por desonra; por difamação e por boa fama; tidos por enganadores, sendo verdadeiros;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28908, 'nvi', '2 Coríntios', '2co', 6, 9, 'como desconhecidos, apesar de bem conhecidos; como morrendo, mas eis que vivemos; espancados, mas não mortos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28909, 'nvi', '2 Coríntios', '2co', 6, 10, 'entristecidos, mas sempre alegres; pobres, mas enriquecendo a muitos; nada tendo, mas possuindo tudo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28910, 'nvi', '2 Coríntios', '2co', 6, 11, 'Falamos abertamente a vocês, coríntios, e lhes abrimos todo o nosso coração!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28911, 'nvi', '2 Coríntios', '2co', 6, 12, 'Não lhes estamos limitando nosso afeto, mas vocês nos estão limitando o afeto que têm por nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28912, 'nvi', '2 Coríntios', '2co', 6, 13, 'Numa justa compensação, falo como a meus filhos, abram também o coração para nós!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28913, 'nvi', '2 Coríntios', '2co', 6, 14, 'Não se ponham em jugo desigual com descrentes. Pois o que têm em comum a justiça e a maldade? Ou que comunhão pode ter a luz com as trevas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28914, 'nvi', '2 Coríntios', '2co', 6, 15, 'Que harmonia entre Cristo e Belial? Que há de comum entre o crente e o descrente?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28915, 'nvi', '2 Coríntios', '2co', 6, 16, 'Que acordo há entre o templo de Deus e os ídolos? Pois somos santuário do Deus vivo. Como disse Deus: "Habitarei com eles e entre eles andarei; serei o seu Deus, e eles serão o meu povo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28916, 'nvi', '2 Coríntios', '2co', 6, 17, 'Portanto, "saiam do meio deles e separem-se", diz o Senhor. "Não toquem em coisas impuras, e eu os receberei"');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28917, 'nvi', '2 Coríntios', '2co', 6, 18, '"e lhes serei Pai, e vocês serão meus filhos e minhas filhas", diz o Senhor Todo-poderoso.');
