-- Inserções para 2 Coríntios 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28918, 'nvi', '2 Coríntios', '2co', 7, 1, 'Amados, visto que temos essas promessas, purifiquemo-nos de tudo o que contamina o corpo e o espírito, aperfeiçoando a santidade no temor de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28919, 'nvi', '2 Coríntios', '2co', 7, 2, 'Concedam-nos lugar no coração de vocês. A ninguém prejudicamos, a ninguém causamos dano, a ninguém exploramos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28920, 'nvi', '2 Coríntios', '2co', 7, 3, 'Não digo isso para condená-los; já lhes disse que vocês estão em nosso coração para juntos morrermos ou vivermos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28921, 'nvi', '2 Coríntios', '2co', 7, 4, 'Tenho grande confiança em vocês, e de vocês tenho muito orgulho. Sinto-me bastante encorajado; minha alegria transborda em todas as tribulações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28922, 'nvi', '2 Coríntios', '2co', 7, 5, 'Pois, quando chegamos à Macedônia, não tivemos nenhum descanso, mas fomos atribulados de toda forma: conflitos externos, temores internos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28923, 'nvi', '2 Coríntios', '2co', 7, 6, 'Deus, porém, que consola os abatidos, consolou-nos com a chegada de Tito,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28924, 'nvi', '2 Coríntios', '2co', 7, 7, 'e não apenas com a vinda dele, mas também com a consolação que vocês lhe ministraram. Ele nos falou da saudade, da tristeza e da preocupação de vocês por mim, de modo que a minha alegria se tornou ainda maior.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28925, 'nvi', '2 Coríntios', '2co', 7, 8, 'Mesmo que a minha carta lhes tenha causado tristeza, não me arrependo. É verdade que a princípio me arrependi, pois percebi que a minha carta os entristeceu, ainda que por pouco tempo. 9 Agora, porém, me alegro, não porque vocês foram entristecidos, mas porque a tristeza os levou ao arrependimento. Pois vocês se entristeceram como Deus desejava, e de forma alguma foram prejudicados por nossa causa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28926, 'nvi', '2 Coríntios', '2co', 7, 9, 'A tristeza segundo Deus produz um arrependimento que leva à salvação e não remorso, mas a tristeza segundo o mundo produz morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28927, 'nvi', '2 Coríntios', '2co', 7, 10, 'Vejam o que esta tristeza segundo Deus produziu em vocês: que dedicação, que desculpas, que indignação, que temor, que saudade, que preocupação, que desejo de ver a justiça feita! Em tudo vocês se mostraram inocentes a esse respeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28928, 'nvi', '2 Coríntios', '2co', 7, 11, 'Assim, se lhes escrevi, não foi por causa daquele que cometeu o erro nem daquele que foi prejudicado, mas para que diante de Deus vocês pudessem ver por si próprios como são dedicados a nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28929, 'nvi', '2 Coríntios', '2co', 7, 12, 'Por isso tudo fomos revigorados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28930, 'nvi', '2 Coríntios', '2co', 7, 13, 'de encorajados, ficamos mais contentes ainda ao ver como Tito estava alegre, porque seu espírito recebeu refrigério de todos vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28931, 'nvi', '2 Coríntios', '2co', 7, 14, 'Eu lhe tinha dito que estava orgulhoso de vocês, e vocês não me decepcionaram. Da mesma forma como era verdade tudo o que lhes dissemos, o orgulho que temos de vocês diante de Tito também mostrou-se verdadeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28932, 'nvi', '2 Coríntios', '2co', 7, 15, 'E a afeição dele por vocês fica maior ainda, quando lembra que todos vocês foram obedientes, recebendo-o com temor e tremor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28933, 'nvi', '2 Coríntios', '2co', 7, 16, 'Alegro-me por poder ter plena confiança em vocês.');
