-- Inserções para 2 Coríntios 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28826, 'nvi', '2 Coríntios', '2co', 2, 1, 'De modo que resolvi não lhes fazer outra visita que causasse tristeza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28827, 'nvi', '2 Coríntios', '2co', 2, 2, 'Pois, se os entristeço, quem me alegrará senão vocês, a quem tenho entristecido?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28828, 'nvi', '2 Coríntios', '2co', 2, 3, 'Escrevi como escrevi para que, quando eu for, não seja entristecido por aqueles que deveriam alegrar-me. Estava confiante em que todos vocês compartilhariam da minha alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28829, 'nvi', '2 Coríntios', '2co', 2, 4, 'Pois eu lhes escrevi com grande aflição e angústia de coração, e com muitas lágrimas: não para entristecê-los, mas para que soubessem como e profundo o meu amor por vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28830, 'nvi', '2 Coríntios', '2co', 2, 5, 'Se alguém tem causado tristeza, não o tem causado apenas a mim, mas também, em parte, para eu não ser demasiadamente severo, a todos vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28831, 'nvi', '2 Coríntios', '2co', 2, 6, 'A punição que lhe foi imposta pela maioria é suficiente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28832, 'nvi', '2 Coríntios', '2co', 2, 7, 'Agora, pelo contrário, vocês devem perdoar-lhe e consolá-lo, para que ele não seja dominado por excessiva tristeza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28833, 'nvi', '2 Coríntios', '2co', 2, 8, 'Portanto, eu lhes recomendo que reafirmem o amor que têm por ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28834, 'nvi', '2 Coríntios', '2co', 2, 9, 'Eu lhes escrevi com o propósito de saber se vocês seriam aprovados, isto é, se seriam obedientes em tudo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28835, 'nvi', '2 Coríntios', '2co', 2, 10, 'Se vocês perdoam a alguém, eu também perdôo; e aquilo que perdoei, se é que havia alguma coisa para perdoar, perdoei na presença de Cristo, por amor a vocês,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28836, 'nvi', '2 Coríntios', '2co', 2, 11, 'a fim de que Satanás não tivesse vantagem sobre nós; pois não ignoramos as suas intenções.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28837, 'nvi', '2 Coríntios', '2co', 2, 12, 'Quando cheguei a Trôade para pregar o evangelho de Cristo e vi que o Senhor me havia aberto uma porta,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28838, 'nvi', '2 Coríntios', '2co', 2, 13, 'ainda assim, não tive sossego em meu espírito, porque não encontrei ali meu irmão Tito. Por isso, despedi-me deles e fui para a Macedônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28839, 'nvi', '2 Coríntios', '2co', 2, 14, 'Mas graças a Deus, que sempre nos conduz vitoriosamente em Cristo e por nosso intermédio exala em todo lugar a fragrância do seu conhecimento;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28840, 'nvi', '2 Coríntios', '2co', 2, 15, 'porque para Deus somos o aroma de Cristo entre os que estão sendo salvos e os que estão perecendo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28841, 'nvi', '2 Coríntios', '2co', 2, 16, 'Para estes somos cheiro de morte; para aqueles fragrância de vida. Mas, quem está capacitado para tanto?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28842, 'nvi', '2 Coríntios', '2co', 2, 17, 'Ao contrário de muitos, não negociamos a palavra de Deus visando lucro; antes, em Cristo falamos diante de Deus com sinceridade, como homens enviados por Deus.');
