-- Inserções para 2 Coríntios 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29045, 'nvi', '2 Coríntios', '2co', 13, 1, 'Esta será minha terceira visita a vocês. "Toda questão precisa ser confirmada pelo depoimento de duas ou três testemunhas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29046, 'nvi', '2 Coríntios', '2co', 13, 2, 'Já os adverti quando estive com vocês pela segunda vez. Agora, estando ausente, escrevo aos que antes pecaram e aos demais: quando voltar, não os pouparei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29047, 'nvi', '2 Coríntios', '2co', 13, 3, 'visto que vocês estão exigindo uma prova de que Cristo fala por meu intermédio. Ele não é fraco ao tratar com vocês, mas poderoso entre vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29048, 'nvi', '2 Coríntios', '2co', 13, 4, 'Pois, na verdade, foi crucificado em fraqueza, mas vive pelo poder de Deus. Da mesma forma, somos fracos nele, mas, pelo poder de Deus, viveremos com ele para servir a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29049, 'nvi', '2 Coríntios', '2co', 13, 5, 'Examinem-se para ver se vocês estão na fé; provem-se a si mesmos. Não percebem que Cristo Jesus está em vocês? A não ser que tenham sido reprovados!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29050, 'nvi', '2 Coríntios', '2co', 13, 6, 'E espero que saibam que nós não fomos reprovados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29051, 'nvi', '2 Coríntios', '2co', 13, 7, 'Agora, oramos a Deus para que vocês não pratiquem mal algum. Não para que os outros vejam que temos sido aprovados, mas para que vocês façam o que é certo, embora pareça que tenhamos falhado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29052, 'nvi', '2 Coríntios', '2co', 13, 8, 'Pois nada podemos contra a verdade, mas somente em favor da verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29053, 'nvi', '2 Coríntios', '2co', 13, 9, 'Ficamos alegres sempre que estamos fracos, e vocês estão fortes; nossa oração é que vocês sejam aperfeiçoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29054, 'nvi', '2 Coríntios', '2co', 13, 10, 'Por isso escrevo estas coisas estando ausente, para que, quando eu for, não precise ser rigoroso no uso da autoridade que o Senhor me deu para edificá-los, e não para destruí-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29055, 'nvi', '2 Coríntios', '2co', 13, 11, 'Sem mais, irmãos, despeço-me de vocês! Procurem aperfeiçoar-se, exortem-se mutuamente, tenham um só pensamento, vivam em paz. E o Deus de amor e paz estará com vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29056, 'nvi', '2 Coríntios', '2co', 13, 12, 'Saúdem uns aos outros com beijo santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29057, 'nvi', '2 Coríntios', '2co', 13, 13, 'Todos os santos lhes enviam saudações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29058, 'nvi', '2 Coríntios', '2co', 13, 14, 'A graça do Senhor Jesus Cristo, o amor de Deus e a comunhão do Espírito Santo sejam com todos vocês.');
