-- Inserções para 2 Crônicas 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11439, 'nvi', '2 Crônicas', '2cr', 12, 1, 'Depois que Roboão se fortaleceu, firmou-se como rei, ele e todo o Israel abandonaram a lei do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11440, 'nvi', '2 Crônicas', '2cr', 12, 2, 'Por terem sido infiéis ao Senhor, Sisaque, rei do Egito, atacou Jerusalém no quinto ano do reinado de Roboão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11441, 'nvi', '2 Crônicas', '2cr', 12, 3, 'Com mil e duzentos carros de guerra, sessenta mil cavaleiros e um exército incontável de líbios, suquitas e etíopes, que vieram do Egito com ele,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11442, 'nvi', '2 Crônicas', '2cr', 12, 4, 'conquistou as cidades fortificadas de Judá e chegou até Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11443, 'nvi', '2 Crônicas', '2cr', 12, 5, 'Então o profeta Semaías apresentou-se a Roboão e aos líderes de Judá que se haviam reunido em Jerusalém, fugindo de Sisaque, e lhes disse: "Assim diz o Senhor: ‘Vocês me abandonaram; por isso eu agora os abandono, entregando-os a Sisaque’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11444, 'nvi', '2 Crônicas', '2cr', 12, 6, 'Os líderes de Israel e o rei se humilharam e disseram: "O Senhor é justo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11445, 'nvi', '2 Crônicas', '2cr', 12, 7, 'Quando o Senhor viu que eles se humilharam, veio a Semaías esta palavra do Senhor: "Visto que eles se humilharam, não os destruirei, mas em breve lhes darei livramento. Minha ira não será derramada sobre Jerusalém por meio de Sisaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11446, 'nvi', '2 Crônicas', '2cr', 12, 8, 'Eles, contudo, ficarão sujeitos a ele, para que aprendam a diferença entre servir a mim e servir aos reis de outras terras".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11447, 'nvi', '2 Crônicas', '2cr', 12, 9, 'Quando Sisaque, rei do Egito, atacou Jerusalém, levou todos os tesouros do templo do Senhor e do palácio real, inclusive os escudos de ouro que Salomão havia feito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11448, 'nvi', '2 Crônicas', '2cr', 12, 10, 'Por isso o rei Roboão mandou fazer escudos de bronze para substituí-los, e os entregou aos chefes da guarda da entrada do palácio real.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11449, 'nvi', '2 Crônicas', '2cr', 12, 11, 'Sempre que o rei ia ao templo do Senhor, os guardas empunhavam os escudos, e, em seguida, os devolviam à sala da guarda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11450, 'nvi', '2 Crônicas', '2cr', 12, 12, 'Como Roboão se humilhou, a ira do Senhor afastou-se dele, e ele não foi totalmente destruído. Aliás, ainda havia algo de bom em Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11451, 'nvi', '2 Crônicas', '2cr', 12, 13, 'O rei Roboão firmou-se no poder em Jerusalém e continuou a reinar. Tinha quarenta e um anos de idade quando começou a reinar, e reinou dezessete anos em Jerusalém, cidade que o Senhor havia escolhido dentre todas as tribos de Israel para nela pôr o seu nome. Sua mãe, uma amonita, chamava-se Naamá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11452, 'nvi', '2 Crônicas', '2cr', 12, 14, 'Ele agiu mal porque não dispôs o seu coração para buscar o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11453, 'nvi', '2 Crônicas', '2cr', 12, 15, 'Os demais acontecimentos do reinado de Roboão, do início ao fim, estão escritos nos relatos do profeta Semaías e do vidente Ido, que tratam de genealogias. Houve guerra constante entre Roboão e Jeroboão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11454, 'nvi', '2 Crônicas', '2cr', 12, 16, 'Roboão descansou com os seus antepassados e foi sepultado na cidade de Davi; seu filho Abias foi o seu sucessor.');
