-- Inserções para 2 Crônicas 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11578, 'nvi', '2 Crônicas', '2cr', 19, 1, 'Quando Josafá, rei de Judá, voltou em segurança ao seu palácio em Jerusalém,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11579, 'nvi', '2 Crônicas', '2cr', 19, 2, 'o vidente Jeú, filho de Hanani, saiu ao seu encontro e lhe disse: "Será que você devia ajudar os ímpios e amar aqueles que odeiam o Senhor? Por causa disso, a ira do Senhor está sobre você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11580, 'nvi', '2 Crônicas', '2cr', 19, 3, 'Contudo, existe em você algo de bom, pois você livrou a terra dos postes sagrados e buscou a Deus de todo o seu coração".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11581, 'nvi', '2 Crônicas', '2cr', 19, 4, 'Josafá morava em Jerusalém; e saiu de novo entre o povo, desde Berseba até os montes de Efraim, fazendo-o voltar para o Senhor, o Deus dos seus antepassados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11582, 'nvi', '2 Crônicas', '2cr', 19, 5, 'Ele nomeou juízes, em cada uma das cidades fortificadas de Judá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11583, 'nvi', '2 Crônicas', '2cr', 19, 6, 'dizendo-lhes: "Considerem atentamente aquilo que fazem, pois vocês não estão julgando para o homem, mas para o Senhor, que estará com vocês sempre que derem um veredicto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11584, 'nvi', '2 Crônicas', '2cr', 19, 7, 'Agora, que o temor do Senhor esteja sobre vocês. Julguem com cuidado, pois com o Senhor, o nosso Deus, não há injustiça nem parcialidade nem suborno".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11585, 'nvi', '2 Crônicas', '2cr', 19, 8, 'Também em Jerusalém nomeou Josafá alguns dos levitas, dos sacerdotes e dos chefes de famílias israelitas para julgarem questões da lei do Senhor e resolverem pendências dos habitantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11586, 'nvi', '2 Crônicas', '2cr', 19, 9, 'Deu-lhes as seguintes ordens: "Vocês devem servir com fidelidade e com coração íntegro, no temor do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11587, 'nvi', '2 Crônicas', '2cr', 19, 10, 'Em cada caso que chegar a vocês da parte dos seus irmãos israelitas das outras cidades, seja caso de derramamento de sangue sejam questões referentes à lei, aos mandamentos, aos decretos ou às ordenanças, vocês deverão adverti-los de que não pequem contra o Senhor; caso contrário a ira dele virá sobre vocês e sobre eles. Façam assim, e vocês não pecarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11588, 'nvi', '2 Crônicas', '2cr', 19, 11, '"Amarias, o sumo sacerdote, estará com vocês para decidir qualquer questão referente à lei do Senhor; Zebadias, filho de Ismael, líder da tribo de Judá, estará com vocês para decidir qualquer questão civil; e os levitas atuarão como oficiais diante de vocês. Cumpram seus deveres com coragem, e esteja o Senhor com aqueles que agirem corretamente".');
