-- Inserções para 2 Crônicas 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11231, 'nvi', '2 Crônicas', '2cr', 3, 1, 'Então Salomão começou a construir o templo do Senhor em Jerusalém, no monte Moriá, onde o Senhor havia aparecido a seu pai Davi, na eira de Araúna, o jebuseu. Local providenciado por Davi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11232, 'nvi', '2 Crônicas', '2cr', 3, 2, 'Ele começou a construir no segundo dia do segundo mês do quarto ano de seu reinado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11233, 'nvi', '2 Crônicas', '2cr', 3, 3, 'Os alicerces que Salomão lançou para o templo de Deus tinham vinte e sete metros de comprimento e nove metros de largura, pela medida antiga.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11234, 'nvi', '2 Crônicas', '2cr', 3, 4, 'O pórtico da entrada do templo tinha nove metros de largura e nove metros de altura. Ele revestiu de ouro puro o seu interior.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11235, 'nvi', '2 Crônicas', '2cr', 3, 5, 'Recobriu de pinho o átrio principal, revestiu-o de ouro puro e o decorou com desenhos de tamareiras e correntes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11236, 'nvi', '2 Crônicas', '2cr', 3, 6, 'Ornamentou o templo com pedras preciosas. O ouro utilizado era de Parvaim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11237, 'nvi', '2 Crônicas', '2cr', 3, 7, 'Também revestiu de ouro as vigas do forro, os batentes, as paredes e as portas do templo, e esculpiu querubins nas paredes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11238, 'nvi', '2 Crônicas', '2cr', 3, 8, 'Fez o Lugar Santíssimo, com nove metros de comprimento e nove metros de largura, igual à largura do templo. Revestiu de vinte e uma toneladas de ouro puro o seu interior.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11239, 'nvi', '2 Crônicas', '2cr', 3, 9, 'Os pregos de ouro pesavam seiscentos gramas. Também revestiu de ouro as salas superiores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11240, 'nvi', '2 Crônicas', '2cr', 3, 10, 'No Lugar Santíssimo esculpiu e revestiu de ouro dois querubins,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11241, 'nvi', '2 Crônicas', '2cr', 3, 11, 'os quais, de asas abertas, mediam juntos nove metros. Cada asa, de dois metros e vinte e cinco centímetros, tocava, de um lado, na parede do templo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11242, 'nvi', '2 Crônicas', '2cr', 3, 12, 'e do outro lado, na asa do outro querubim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11243, 'nvi', '2 Crônicas', '2cr', 3, 13, 'Assim os querubins, com asas que se estendiam por nove metros, estavam de pé, de frente para o átrio principal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11244, 'nvi', '2 Crônicas', '2cr', 3, 14, 'Ele fez o véu de tecido azul, roxo, vermelho e linho fino com querubins desenhados nele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11245, 'nvi', '2 Crônicas', '2cr', 3, 15, 'Fez na frente do templo duas colunas, que juntas tinham dezesseis metros, cada uma tendo em cima um capitel com dois metros e vinte e cinco centímetros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11246, 'nvi', '2 Crônicas', '2cr', 3, 16, 'E fez correntes entrelaçadas e colocou-as no alto das colunas. Fez também cem romãs, colocando-as nas correntes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11247, 'nvi', '2 Crônicas', '2cr', 3, 17, 'Então levantou as colunas na frente do templo, uma ao sul, outra ao norte; à que ficava ao sul deu o nome de Jaquim, e à que ficava ao norte, Boaz.');
