-- Inserções para 2 Crônicas 22
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11646, 'nvi', '2 Crônicas', '2cr', 22, 1, 'O povo de Jerusalém proclamou Acazias, filho mais novo de Jeorão, rei em seu lugar, uma vez que as tropas que vieram com os árabes haviam matado todos os outros filhos dele. Assim começou a reinar Acazias, filho de Jeorão, rei de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11647, 'nvi', '2 Crônicas', '2cr', 22, 2, 'Acazias tinha vinte e dois anos de idade quando começou a reinar, e reinou um ano em Jerusalém. O nome de sua mãe era Atalia, neta de Onri.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11648, 'nvi', '2 Crônicas', '2cr', 22, 3, 'Ele também andou nos caminhos da família de Acabe, pois sua mãe lhe dava maus conselhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11649, 'nvi', '2 Crônicas', '2cr', 22, 4, 'Ele fez o que o Senhor reprova, como a família de Acabe havia feito, pois, depois da morte de seu pai, eles se tornaram seus conselheiros, para sua ruína.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11650, 'nvi', '2 Crônicas', '2cr', 22, 5, 'Ele também seguiu o conselho deles quando aliou-se a Jorão, filho de Acabe, rei de Israel, e saiu à guerra contra Hazael, rei da Síria, em Ramote-Gileade. Jorão foi ferido');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11651, 'nvi', '2 Crônicas', '2cr', 22, 6, 'e voltou a Jezreel para recuperar-se dos ferimentos sofridos em Ramote, na batalha contra Hazael, rei da Síria. Depois Acazias, rei de Judá, foi a Jezreel visitar Jorão, que se recuperava de seus ferimentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11652, 'nvi', '2 Crônicas', '2cr', 22, 7, 'Por meio dessa visita, Deus provocou a queda de Acazias. Quando ele chegou, saiu com Jorão ao encontro de Jeú, filho de Ninsi, a quem o Senhor havia ungido para destruir a família de Acabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11653, 'nvi', '2 Crônicas', '2cr', 22, 8, 'Quando Jeú estava executando juízo sobre a família de Acabe, encontrou os líderes de Judá e os filhos dos parentes de Acazias, que o serviam, e os matou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11654, 'nvi', '2 Crônicas', '2cr', 22, 9, 'Saiu então em busca de Acazias, e seus soldados o capturaram em Samaria, onde estava escondido. Levado a Jeú, Acazias foi morto. Mas não lhe negaram sepultura, pois disseram: "Ele era neto de Josafá, que buscou o Senhor de todo o coração". Assim, a família de Acazias não tinha mais ninguém que pudesse ser rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11655, 'nvi', '2 Crônicas', '2cr', 22, 10, 'Quando Atalia, mãe de Acazias, soube que seu filho estava morto, mandou matar toda a família real de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11656, 'nvi', '2 Crônicas', '2cr', 22, 11, 'Mas Jeoseba, filha do rei Jeorão, pegou Joás, um dos filhos do rei Acazias que iam ser assassinados, e o colocou num quarto, junto com a sua ama. Assim Jeoseba, filha do rei Jeorão, mulher do sacerdote Joiada e irmã de Acazias, escondeu Joás de Atalia, de forma que ela não pôde matá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11657, 'nvi', '2 Crônicas', '2cr', 22, 12, 'Seis anos ele ficou escondido com elas no templo de Deus, enquanto Atalia governava o país.');
