-- Inserções para 2 Crônicas 27
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11757, 'nvi', '2 Crônicas', '2cr', 27, 1, 'Jotão tinha vinte e cinco anos de idade quando começou a reinar, e reinou dezesseis anos em Jerusalém. O nome da sua mãe era Jerusa, filha de Zadoque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11758, 'nvi', '2 Crônicas', '2cr', 27, 2, 'Ele fez o que o Senhor aprova, tal como seu pai, mas, ao contrário deste, não entrou no templo do Senhor. O povo, contudo, prosseguiu em suas práticas corruptas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11759, 'nvi', '2 Crônicas', '2cr', 27, 3, 'Jotão reconstruiu a porta superior do templo do Senhor e fez amplos trabalhos no muro, na colina de Ofel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11760, 'nvi', '2 Crônicas', '2cr', 27, 4, 'Construiu cidades nos montes de Judá, bem como fortes e torres nas matas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11761, 'nvi', '2 Crônicas', '2cr', 27, 5, 'Jotão guerreou contra o rei dos amonitas e o derrotou. Então os amonitas pagaram-lhe três toneladas e meia de prata, dez mil barris de trigo e dez mil de cevada durante três anos seguidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11762, 'nvi', '2 Crônicas', '2cr', 27, 6, 'Jotão tornou-se cada vez mais poderoso, pois andava firmemente segundo a vontade do Senhor, o seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11763, 'nvi', '2 Crônicas', '2cr', 27, 7, 'Os demais acontecimentos do reinado de Jotão, inclusive todas as suas guerras e as suas outras realizações, estão escritos nos registros históricos dos reis de Israel e de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11764, 'nvi', '2 Crônicas', '2cr', 27, 8, 'Tinha vinte e cinco anos de idade quando começou a reinar, e reinou dezesseis anos em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11765, 'nvi', '2 Crônicas', '2cr', 27, 9, 'Jotão descansou com os seus antepassados e foi sepultado na cidade de Davi. Seu filho Acaz foi o seu sucessor.');
