-- Inserções para 2 Crônicas 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11348, 'nvi', '2 Crônicas', '2cr', 8, 1, 'Depois de vinte anos, durante os quais Salomão construiu o templo do Senhor e o seu próprio palácio,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11349, 'nvi', '2 Crônicas', '2cr', 8, 2, 'ele reconstruiu as cidades que Hirão lhe tinha dado, e nelas estabeleceu israelitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11350, 'nvi', '2 Crônicas', '2cr', 8, 3, 'Depois atacou Hamate-Zobá e a conquistou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11351, 'nvi', '2 Crônicas', '2cr', 8, 4, 'Também reconstruiu Tadmor, no deserto, e todas as cidades-armazéns que havia construído em Hamate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11352, 'nvi', '2 Crônicas', '2cr', 8, 5, 'Reconstruiu Bete-Horom Alta e Bete-Horom Baixa, cidades fortificadas com muros, portas e trancas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11353, 'nvi', '2 Crônicas', '2cr', 8, 6, 'e também Baalate e todas as cidades-armazéns que possuía, e todas as cidades onde ficavam os seus carros e os seus cavalos. Construiu tudo o que desejou em Jerusalém, no Líbano e em todo o território que governou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11354, 'nvi', '2 Crônicas', '2cr', 8, 7, 'Todos os não israelitas, descendentes dos hititas, dos amorreus, dos ferezeus, dos heveus e dos jebuseus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11355, 'nvi', '2 Crônicas', '2cr', 8, 8, 'que não tinham sido mortos pelos israelitas, Salomão recrutou para o trabalho forçado, como continuam até hoje.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11356, 'nvi', '2 Crônicas', '2cr', 8, 9, 'Mas Salomão não obrigou nenhum israelita a trabalhos forçados; eles eram seus homens de guerra, chefes de seus capitães, comandantes dos seus carros e condutores de carros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11357, 'nvi', '2 Crônicas', '2cr', 8, 10, 'Também eram israelitas os principais funcionários do rei Salomão, duzentos e cinqüenta funcionários que supervisionavam os trabalhadores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11358, 'nvi', '2 Crônicas', '2cr', 8, 11, 'Salomão levou a filha do faraó da cidade de Davi para o palácio que ele havia construído para ela, pois dissera: "Minha mulher não deve morar no palácio de Davi, rei de Israel, pois os lugares onde entrou a arca do Senhor são sagrados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11359, 'nvi', '2 Crônicas', '2cr', 8, 12, 'Sobre o altar do Senhor, que havia construído diante do pórtico, Salomão passou a sacrificar holocaustos ao Senhor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11360, 'nvi', '2 Crônicas', '2cr', 8, 13, 'conforme as determinações de Moisés acerca das ofertas diárias e dos sábados, das luas novas e das três festas anuais: a festa dos pães sem fermento, a festa das semanas e a festa das cabanas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11361, 'nvi', '2 Crônicas', '2cr', 8, 14, 'De acordo com a ordem de seu pai Davi, designou os grupos dos sacerdotes para as suas tarefas, e os levitas para conduzirem o louvor e ajudarem os sacerdotes, conforme as determinações diárias. Também designou, por divisões, os porteiros das várias portas, conforme o que Davi, homem de Deus, tinha ordenado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11362, 'nvi', '2 Crônicas', '2cr', 8, 15, 'Todas as ordens dadas pelo rei aos sacerdotes e aos levitas, inclusive as ordens relativas aos tesouros, foram seguidas à risca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11363, 'nvi', '2 Crônicas', '2cr', 8, 16, 'Todo o trabalho de Salomão foi executado, desde o dia em que foram lançados os alicerces do templo do Senhor até seu término. Assim foi concluído o templo do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11364, 'nvi', '2 Crônicas', '2cr', 8, 17, 'Depois Salomão foi a Eziom-Geber e a Elate, no litoral de Edom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11365, 'nvi', '2 Crônicas', '2cr', 8, 18, 'E Hirão enviou-lhe navios comandados por seus próprios marinheiros, homens que conheciam o mar. Eles navegavam com os marinheiros de Salomão até Ofir, e de lá trouxeram quinze toneladas e setecentos e cinqüenta quilos de ouro para o rei Salomão.');
