-- Inserções para 2 Crônicas 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11196, 'nvi', '2 Crônicas', '2cr', 1, 1, 'Salomão, filho de Davi, estabeleceu-se com firmeza sobre o seu reino, pois o Senhor, o seu Deus, estava com ele e tornou-o muito poderoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11197, 'nvi', '2 Crônicas', '2cr', 1, 2, 'Salomão reuniu todo o Israel: os líderes de mil e de cem, os juízes, todos os líderes de Israel e os chefes de famílias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11198, 'nvi', '2 Crônicas', '2cr', 1, 3, 'E foi com toda a assembléia ao lugar sagrado, no alto de Gibeom, pois ali estava a Tenda do Encontro que Moisés, servo do Senhor, havia feito no deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11199, 'nvi', '2 Crônicas', '2cr', 1, 4, 'Davi tinha transportado a arca de Deus de Quiriate-Jearim para a tenda que ele tinha armado para ela em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11200, 'nvi', '2 Crônicas', '2cr', 1, 5, 'O altar de bronze que Bezalel, filho de Uri e neto de Hur, fizera, estava em Gibeom, em frente do tabernáculo do Senhor; ali Salomão e a assembléia consultaram o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11201, 'nvi', '2 Crônicas', '2cr', 1, 6, 'Salomão ofereceu ao Senhor mil holocaustos sobre o altar de bronze, na Tenda do Encontro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11202, 'nvi', '2 Crônicas', '2cr', 1, 7, 'Naquela noite Deus apareceu a Salomão e lhe disse: "Peça-me o que quiser, e eu lhe darei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11203, 'nvi', '2 Crônicas', '2cr', 1, 8, 'Salomão respondeu: "Tu foste muito bondoso para com meu pai Davi e me fizeste rei em seu lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11204, 'nvi', '2 Crônicas', '2cr', 1, 9, 'Agora, Senhor Deus, que se confirme a tua promessa a meu pai Davi, pois me fizeste rei sobre um povo tão numeroso quanto o pó da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11205, 'nvi', '2 Crônicas', '2cr', 1, 10, 'Dá-me sabedoria e conhecimento, para que eu possa liderar esta nação, pois, quem pode governar este teu grande povo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11206, 'nvi', '2 Crônicas', '2cr', 1, 11, 'Deus disse a Salomão: "Já que este é o desejo de seu coração e você não pediu riquezas, nem bens, nem honra, nem a morte dos seus inimigos, nem vida longa, mas sabedoria e conhecimento para governar o meu povo, sobre o qual o fiz rei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11207, 'nvi', '2 Crônicas', '2cr', 1, 12, 'você receberá o que pediu, mas também lhe darei riquezas, bens e honra, como nenhum rei antes de você teve e nenhum depois de você terá".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11208, 'nvi', '2 Crônicas', '2cr', 1, 13, 'Então Salomão voltou de Gibeom, de diante da Tenda do Encontro, para Jerusalém. E reinou sobre Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11209, 'nvi', '2 Crônicas', '2cr', 1, 14, 'Salomão juntou carros e cavalos; possuía mil e quatrocentos carros e doze mil cavalos, dos quais mantinha uma parte nas guarnições de algumas cidades e a outra perto dele, em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11210, 'nvi', '2 Crônicas', '2cr', 1, 15, 'O rei tornou tão comuns a prata e o ouro em Jerusalém quanto as pedras, e o cedro tão numeroso quanto as figueiras bravas da Sefelá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11211, 'nvi', '2 Crônicas', '2cr', 1, 16, 'Os cavalos de Salomão eram importados do Egito e da Cilícia, onde os fornecedores do rei os compravam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (11212, 'nvi', '2 Crônicas', '2cr', 1, 17, 'Importavam do Egito um carro por sete quilos e duzentos gramas de prata, e um cavalo por um quilo e oitocentos gramas, e os exportavam para todos os reis dos hititas e dos arameus.');
