-- Inserções para 2 João 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30647, 'nvi', '2 João', '2jo', 1, 1, 'O presbítero à senhora eleita e aos seus filhos, a quem amo na verdade, — e não apenas eu os amo, mas também todos os que conhecem a verdade —');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30648, 'nvi', '2 João', '2jo', 1, 2, 'por causa da verdade que permanece em nós e estará conosco para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30649, 'nvi', '2 João', '2jo', 1, 3, 'A graça, a misericórdia e a paz da parte de Deus Pai e de Jesus Cristo, seu Filho, estarão conosco em verdade e em amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30650, 'nvi', '2 João', '2jo', 1, 4, 'Ao encontrar alguns dos seus filhos, muito me alegrei, pois eles estão andando na verdade, conforme o mandamento que recebemos do Pai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30651, 'nvi', '2 João', '2jo', 1, 5, 'E agora eu lhe peço, senhora — não como se estivesse escrevendo um mandamento novo, o que já tínhamos desde o princípio — que nos amemos uns aos outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30652, 'nvi', '2 João', '2jo', 1, 6, 'E este é o amor: que andemos em obediência aos seus mandamentos. Como vocês já têm ouvido desde o princípio, o mandamento é este: que vocês andem em amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30653, 'nvi', '2 João', '2jo', 1, 7, 'De fato, muitos enganadores têm saído pelo mundo, os quais não confessam que Jesus Cristo veio em corpo. Tal é o enganador e o anticristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30654, 'nvi', '2 João', '2jo', 1, 8, 'Tenham cuidado, para que vocês não destruam o fruto do nosso trabalho, antes sejam recompensados plenamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30655, 'nvi', '2 João', '2jo', 1, 9, 'Todo aquele que não permanece no ensino de Cristo, mas vai além dele, não tem Deus; quem permanece no ensino tem o Pai e também o Filho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30656, 'nvi', '2 João', '2jo', 1, 10, 'Se alguém chega a vocês e não trouxer esse ensino, não o recebam em casa nem o saúdem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30657, 'nvi', '2 João', '2jo', 1, 11, 'Pois quem o saúda torna-se participante das suas obras malignas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30658, 'nvi', '2 João', '2jo', 1, 12, 'Tenho muito que lhes escrever, mas não é meu propósito fazê-lo com papel e tinta. Em vez disso, espero visitá-los e falar com vocês face a face, para que a nossa alegria seja completa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30659, 'nvi', '2 João', '2jo', 1, 13, 'Os filhos da sua irmã eleita lhe enviam saudações.');
