-- Inserções para 2 Reis 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9535, 'nvi', '2 Reis', '2rs', 1, 1, 'Depois da morte de Acabe, Moabe rebelou-se contra Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9536, 'nvi', '2 Reis', '2rs', 1, 2, 'Certo dia, Acazias caiu da sacada do seu quarto no palácio de Samaria, e ficou muito ferido. Então enviou mensageiros para consultar Baal-Zebube, deus de Ecrom, para saber se ele se recuperaria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9537, 'nvi', '2 Reis', '2rs', 1, 3, 'Mas o anjo do Senhor disse ao tesbita Elias: "Vá encontrar-se com os mensageiros do rei de Samaria e lhes pergunte: ‘Acaso não há Deus em Israel? Por que vocês vão consultar Baal-Zebube, deus de Ecrom? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9538, 'nvi', '2 Reis', '2rs', 1, 4, 'Por isso, assim diz o Senhor: ‘Você não se levantará mais dessa cama e certamente morrerá! ’ " E assim Elias se foi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9539, 'nvi', '2 Reis', '2rs', 1, 5, 'Quando os mensageiros voltaram ao rei, ele lhes perguntou: "Por que vocês voltaram? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9540, 'nvi', '2 Reis', '2rs', 1, 6, 'Eles responderam: "Um homem veio ao nosso encontro e nos disse: ‘Voltem ao rei que os enviou e digam-lhe: Assim diz o Senhor: "Acaso não há Deus em Israel? Por que você mandou consultar Baal-Zebube, deus de Ecrom? Por isso você não se levantará mais dessa cama e certamente morrerá! " ’ "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9541, 'nvi', '2 Reis', '2rs', 1, 7, 'O rei lhes perguntou: "Como era o homem que os encontrou e lhes disse isso? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9542, 'nvi', '2 Reis', '2rs', 1, 8, 'Eles responderam: "Ele vestia roupas de pêlos e usava um cinto de couro". O rei concluiu: "Era o tesbita Elias".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9543, 'nvi', '2 Reis', '2rs', 1, 9, 'Em seguida mandou um oficial com cinqüenta soldados procurar Elias. O oficial o encontrou sentado no alto de uma colina, e lhe disse: "Homem de Deus, o rei ordena que você desça"');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9544, 'nvi', '2 Reis', '2rs', 1, 10, 'Elias respondeu ao oficial: "Se sou homem de Deus, que desça fogo do céu e consuma você e seus cinqüenta soldados! " E desceu fogo do céu e consumiu o oficial e seus soldados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9545, 'nvi', '2 Reis', '2rs', 1, 11, 'Depois disso o rei enviou outro oficial com mais cinqüenta soldados. E ele disse a Elias: "Homem de Deus o rei ordena que você desça imediatamente".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9546, 'nvi', '2 Reis', '2rs', 1, 12, 'Respondeu Elias: "Se sou homem de Deus, que desça fogo do céu e consuma você e seus cinqüenta soldados! " De novo fogo de Deus desceu do céu e consumiu o oficial e seus soldados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9547, 'nvi', '2 Reis', '2rs', 1, 13, 'Então o rei enviou um terceiro oficial com outros cinqüenta soldados. O oficial subiu o monte, caiu de joelhos diante de Elias e implorou: "Homem de Deus, tenha consideração por minha vida e pela vida destes cinqüenta soldados, teus servos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9548, 'nvi', '2 Reis', '2rs', 1, 14, 'Sei que desceu fogo do céu e consumiu os dois primeiros oficiais com todos os seus soldados. Mas agora tenha consideração por minha vida! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9549, 'nvi', '2 Reis', '2rs', 1, 15, 'O anjo do Senhor disse a Elias: "Acompanhe-o; não tenha medo dele". Então Elias se levantou, desceu com ele e foi falar com o rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9550, 'nvi', '2 Reis', '2rs', 1, 16, 'Ao chegar, disse ao rei: "Assim diz o Senhor: Acaso não há Deus em Israel? Por que você mandou consultar Baal-Zebube, deus de Ecrom? Por isso, você não se levantará mais dessa cama e certamente morrerá! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9551, 'nvi', '2 Reis', '2rs', 1, 17, 'E Acazias morreu, conforme a palavra do Senhor, anunciada por Elias. Como não tinha filhos, Jorão foi o seu sucessor no segundo ano do reinado de Jeorão, rei de Judá, filho de Josafá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (9552, 'nvi', '2 Reis', '2rs', 1, 18, 'Os demais acontecimentos do reinado de Acazias e suas realizações estão escritos nos registros históricos dos reis de Israel.');
