-- Inserções para 2 Samuel 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8122, 'nvi', '2 Samuel', '2sm', 4, 1, 'Ao saber que Abner havia morrido em Hebrom, Is-Bosete, filho de Saul, perdeu a coragem, e todo Israel ficou alarmado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8123, 'nvi', '2 Samuel', '2sm', 4, 2, 'Ora, o filho de Saul tinha a seu serviço dois líderes de grupos de ataque. Um deles chamava-se Baaná e o outro, Recabe; ambos filhos de Rimom, de Beerote, da tribo de Benjamim; a cidade de Beerote era considerada parte de Benjamim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8124, 'nvi', '2 Samuel', '2sm', 4, 3, 'O povo de Beerote fugiu para Gitaim e até hoje vive ali como estrangeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8125, 'nvi', '2 Samuel', '2sm', 4, 4, '( Jônatas, filho de Saul, tinha um filho aleijado dos pés. Ele tinha cinco anos de idade quando chegou a notícia de Jezreel de que Saul e Jônatas haviam morrido. Sua ama o apanhou e fugiu, mas, na pressa, ele o deixou cair e ele ficou manco. Seu nome era Mefibosete. )');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8126, 'nvi', '2 Samuel', '2sm', 4, 5, 'Aconteceu então que Recabe e Baaná, filhos de Rimom, de Beerote, foram à casa de Is-Bosete na hora mais quente do dia, na hora do seu descanso do meio-dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8127, 'nvi', '2 Samuel', '2sm', 4, 6, 'Os dois entraram na casa como se fossem buscar trigo, transpassaram-lhe o estômago e depois fugiram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8128, 'nvi', '2 Samuel', '2sm', 4, 7, 'Eles haviam entrado na casa enquanto Is-Bosete estava deitado, em seu quarto. Depois de o transpassarem e o matarem, cortaram-lhe a cabeça. E levando-a consigo, viajaram toda a noite pela rota da Arabá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8129, 'nvi', '2 Samuel', '2sm', 4, 8, 'Levaram a cabeça de Is-Bosete a Davi, em Hebrom, e disseram-lhe: "Aqui está a cabeça de Is-Bosete, filho de Saul, teu inimigo, que tentou tirar-te a vida. Hoje o Senhor vingou o nosso rei e senhor, de Saul e de sua descendência".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8130, 'nvi', '2 Samuel', '2sm', 4, 9, 'Davi respondeu a Recabe e a Baaná, seu irmão, filhos de Rimom, de Beerote: "Juro pelo nome do Senhor, que me tem livrado de todas as aflições.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8131, 'nvi', '2 Samuel', '2sm', 4, 10, 'Quando um homem me disse que Saul estava morto, pensando que me trazia boa notícia, eu o agarrei e o matei em Ziclague, como recompensa pela notícia que trouxe!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8132, 'nvi', '2 Samuel', '2sm', 4, 11, 'Muito mais agora, que homens ímpios mataram um inocente em sua própria casa e em sua própria cama! Vou castigá-los e eliminá-los da face da terra porque vocês fizeram correr o sangue dele! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8133, 'nvi', '2 Samuel', '2sm', 4, 12, 'Então Davi ordenou a seus soldados, e eles os mataram. E cortaram as mãos e os pés deles e penduraram os corpos junto ao açude de Hebrom. Mas sepultaram a cabeça de Is-Bosete no túmulo de Abner, em Hebrom.');
