-- Inserções para 2 Samuel 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8211, 'nvi', '2 Samuel', '2sm', 8, 1, 'Depois disso, Davi derrotou os filisteus e os subjugou, e tirou do controle deles Metegue-Amá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8212, 'nvi', '2 Samuel', '2sm', 8, 2, 'Davi derrotou também os moabitas. Ele os fez deitarem-se no chão e mandou que os medissem com uma corda; os moabitas que ficavam dentro das duas primeiras medidas da corda foram mortos, mas os que ficavam dentro da terceira foram poupados. Assim, os moabitas ficaram sujeitos a Davi, pagando-lhe impostos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8213, 'nvi', '2 Samuel', '2sm', 8, 3, 'Além disso, Davi derrotou Hadadezer, filho de Reobe, rei de Zobá, quando Hadadezer tentava recuperar o controle na região do rio Eufrates.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8214, 'nvi', '2 Samuel', '2sm', 8, 4, 'Davi se apossou de mil dos seus carros de guerra, sete mil cavaleiros e vinte mil soldados de infantaria. Ainda levou cem cavalos de carros de guerra, e aleijou todos o outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8215, 'nvi', '2 Samuel', '2sm', 8, 5, 'Quando os arameus de Damasco vieram ajudar Hadadezer, rei de Zobá, Davi matou vinte e dois mil deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8216, 'nvi', '2 Samuel', '2sm', 8, 6, 'Em seguida estabeleceu guarnições militares no reino dos arameus de Damasco, sujeitando-os a lhe pagarem impostos. E o Senhor dava vitórias a Davi aonde quer que ele fosse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8217, 'nvi', '2 Samuel', '2sm', 8, 7, 'Davi também levou para Jerusalém os escudos de ouro usados pelos oficiais de Hadadezer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8218, 'nvi', '2 Samuel', '2sm', 8, 8, 'De Tebá e Berotai, cidades que pertenciam a Hadadezer, o rei Davi levou grande quantidade de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8219, 'nvi', '2 Samuel', '2sm', 8, 9, 'Quando Toú, rei de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8220, 'nvi', '2 Samuel', '2sm', 8, 10, 'enviou seu filho Jorão ao rei Davi para saudá-lo e parabenizá-lo por sua vitória na batalha contra Hadadezer, que tinha estado em guerra com Toú. E, com Jorão, mandou todo tipo de utensílios de prata, de ouro e de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8221, 'nvi', '2 Samuel', '2sm', 8, 11, 'O rei Davi consagrou esses utensílios ao Senhor, como fizera com a prata e com o ouro tomados de todas as nações que havia subjugado:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8222, 'nvi', '2 Samuel', '2sm', 8, 12, 'Edom e Moabe, os amonitas e os filisteus, e Amaleque. Também consagrou os bens tomados de Hadadezer, filho de Reobe, rei de Zobá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8223, 'nvi', '2 Samuel', '2sm', 8, 13, 'Davi ficou ainda mais famoso ao retornar da batalha em que matou dezoito mil edomitas no vale do Sal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8224, 'nvi', '2 Samuel', '2sm', 8, 14, 'Ele estabeleceu guarnições militares por todo o território de Edom, sujeitando todos os edomitas. O Senhor dava vitórias a Davi aonde quer que ele fosse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8225, 'nvi', '2 Samuel', '2sm', 8, 15, 'Davi reinou sobre todo o Israel, administrando o direito e a justiça a todo o seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8226, 'nvi', '2 Samuel', '2sm', 8, 16, 'Joabe, filho de Zeruia, era comandante do exército; Josafá, filho de Ailude, era o arquivista real;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8227, 'nvi', '2 Samuel', '2sm', 8, 17, 'Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes; Seraías era secretário;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (8228, 'nvi', '2 Samuel', '2sm', 8, 18, 'Benaia, filho de Joiada, comandava os queretitas e os peletitas; e os filhos de Davi eram sacerdotes.');
