-- Inserções para 2 Timóteo 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29855, 'nvi', '2 Timóteo', '2tm', 3, 1, 'Saiba disto: nos últimos dias sobrevirão tempos terríveis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29856, 'nvi', '2 Timóteo', '2tm', 3, 2, 'Os homens serão egoístas, avarentos, presunçosos, arrogantes, blasfemos, desobedientes aos pais, ingratos, ímpios,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29857, 'nvi', '2 Timóteo', '2tm', 3, 3, 'sem amor pela família, irreconciliáveis, caluniadores, sem domínio próprio, cruéis, inimigos do bem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29858, 'nvi', '2 Timóteo', '2tm', 3, 4, 'traidores, precipitados, soberbos, mais amantes dos prazeres do que amigos de Deus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29859, 'nvi', '2 Timóteo', '2tm', 3, 5, 'tendo aparência de piedade, mas negando o seu poder. Afaste-se também destes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29860, 'nvi', '2 Timóteo', '2tm', 3, 6, 'São estes os que se introduzem pelas casas e conquistam mulherzinhas sobrecarregadas de pecados, as quais se deixam levar por toda espécie de desejos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29861, 'nvi', '2 Timóteo', '2tm', 3, 7, 'Elas estão sempre aprendendo, mas não conseguem nunca de chegar ao conhecimento da verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29862, 'nvi', '2 Timóteo', '2tm', 3, 8, 'Como Janes e Jambres se opuseram a Moisés, esses também resistem à verdade. A mente deles é depravada; são reprovados na fé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29863, 'nvi', '2 Timóteo', '2tm', 3, 9, 'Não irão longe, porém; como no caso daqueles, a sua insensatez se tornará evidente a todos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29864, 'nvi', '2 Timóteo', '2tm', 3, 10, 'Mas você tem seguido de perto o meu ensino, a minha conduta, o meu propósito, a minha fé, a minha paciência, o meu amor, a minha perseverança,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29865, 'nvi', '2 Timóteo', '2tm', 3, 11, 'as perseguições e os sofrimentos que enfrentei, coisas que me aconteceram em Antioquia, Icônio e Listra. Quanta perseguição suportei! Mas, de todas essas coisas o Senhor me livrou!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29866, 'nvi', '2 Timóteo', '2tm', 3, 12, 'De fato, todos os que desejam viver piedosamente em Cristo Jesus serão perseguidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29867, 'nvi', '2 Timóteo', '2tm', 3, 13, 'Contudo, os perversos e impostores irão de mal a pior, enganando e sendo enganados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29868, 'nvi', '2 Timóteo', '2tm', 3, 14, 'Quanto a você, porém, permaneça nas coisas que aprendeu e das quais tem convicção, pois você sabe de quem o aprendeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29869, 'nvi', '2 Timóteo', '2tm', 3, 15, 'Porque desde criança você conhece as sagradas letras, que são capazes de torná-lo sábio para a salvação mediante a fé em Cristo Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29870, 'nvi', '2 Timóteo', '2tm', 3, 16, 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29871, 'nvi', '2 Timóteo', '2tm', 3, 17, 'para que o homem de Deus seja apto e plenamente preparado para toda boa obra.');
