-- Inserções para 2 Timóteo 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29811, 'nvi', '2 Timóteo', '2tm', 1, 1, 'Paulo, apóstolo de Cristo Jesus pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29812, 'nvi', '2 Timóteo', '2tm', 1, 2, 'a Timóteo, meu amado filho: Graça, misericórdia e paz da parte de Deus Pai e de Cristo Jesus, nosso Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29813, 'nvi', '2 Timóteo', '2tm', 1, 3, 'Dou graças a Deus, a quem sirvo com a consciência limpa, como o serviram os meus antepassados, ao lembrar-me constantemente de você noite e dia em minhas orações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29814, 'nvi', '2 Timóteo', '2tm', 1, 4, 'Lembro-me das suas lágrimas e desejo muito vê-lo, para que a minha alegria seja completa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29815, 'nvi', '2 Timóteo', '2tm', 1, 5, 'Recordo-me da sua fé não fingida, que primeiro habitou em sua avó Lóide e em sua mãe Eunice, e estou convencido de que também habita em você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29816, 'nvi', '2 Timóteo', '2tm', 1, 6, 'Por essa razão, torno a lembrar-lhe que mantenha viva a chama do dom de Deus que está em você mediante a imposição das minhas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29817, 'nvi', '2 Timóteo', '2tm', 1, 7, 'Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29818, 'nvi', '2 Timóteo', '2tm', 1, 8, 'Portanto, não se envergonhe de testemunhar do Senhor, nem de mim, que sou prisioneiro dele, mas suporte comigo os sofrimentos pelo evangelho, segundo o poder de Deus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29819, 'nvi', '2 Timóteo', '2tm', 1, 9, 'que nos salvou e nos chamou com uma santa vocação, não em virtude das nossas obras, mas por causa da sua própria determinação e graça. Esta graça nos foi dada em Cristo Jesus desde os tempos eternos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29820, 'nvi', '2 Timóteo', '2tm', 1, 10, 'sendo agora revelada pela manifestação de nosso Salvador, Cristo Jesus. Ele tornou inoperante a morte e trouxe à luz a vida e a imortalidade por meio do evangelho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29821, 'nvi', '2 Timóteo', '2tm', 1, 11, 'Deste evangelho fui constituído pregador, apóstolo e mestre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29822, 'nvi', '2 Timóteo', '2tm', 1, 12, 'Por essa causa também sofro, mas não me envergonho, porque sei em quem tenho crido e estou bem certo de que ele é poderoso para guardar o meu depósito até aquele dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29823, 'nvi', '2 Timóteo', '2tm', 1, 13, 'Retenha, com fé e amor em Cristo Jesus, o modelo da sã doutrina que você ouviu de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29824, 'nvi', '2 Timóteo', '2tm', 1, 14, 'Quanto ao bom depósito, guarde-o por meio do Espírito Santo que habita em nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29825, 'nvi', '2 Timóteo', '2tm', 1, 15, 'Você sabe que todos os da província da Ásia me abandonaram, inclusive Fígelo e Hermógenes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29826, 'nvi', '2 Timóteo', '2tm', 1, 16, 'O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes ele me reanimou e não se envergonhou por eu estar preso;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29827, 'nvi', '2 Timóteo', '2tm', 1, 17, 'pelo contrário, quando chegou a Roma procurou-me diligentemente até me encontrar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29828, 'nvi', '2 Timóteo', '2tm', 1, 18, 'Conceda-lhe o Senhor que, naquele dia, encontre misericórdia da parte do Senhor! Você sabe muito bem quantos serviços ele me prestou em Éfeso.');
