-- Inserções para 2 Tessalonicenses 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29651, 'nvi', '2 Tessalonicenses', '2ts', 1, 1, 'Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus nosso Pai e no Senhor Jesus Cristo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29652, 'nvi', '2 Tessalonicenses', '2ts', 1, 2, 'A vocês, graça e paz da parte de Deus Pai e do Senhor Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29653, 'nvi', '2 Tessalonicenses', '2ts', 1, 3, 'Irmãos, devemos sempre dar graças a Deus por vocês; e isso é apropriado, porque a fé que vocês têm cresce cada vez mais, e muito aumenta o amor que todos vocês têm uns pelos outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29654, 'nvi', '2 Tessalonicenses', '2ts', 1, 4, 'Por esta causa nos gloriamos em vocês entre as igrejas de Deus pela perseverança e fé que mostram em todas as perseguições e tribulações que vocês estão suportando.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29655, 'nvi', '2 Tessalonicenses', '2ts', 1, 5, 'Elas dão prova do justo juízo de Deus, que deseja que vocês sejam considerados dignos do seu Reino, pelo qual vocês também estão sofrendo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29656, 'nvi', '2 Tessalonicenses', '2ts', 1, 6, 'É justo da parte de Deus retribuir com tribulação aos que lhes causam tribulação,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29657, 'nvi', '2 Tessalonicenses', '2ts', 1, 7, 'e dar alívio a vocês, que estão sendo atribulados, e a nós também. Isso acontecerá quando o Senhor Jesus for revelado lá do céu, com os seus anjos poderosos, em meio a chamas flamejantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29658, 'nvi', '2 Tessalonicenses', '2ts', 1, 8, 'Ele punirá os que não conhecem a Deus e os que não obedecem ao evangelho de nosso Senhor Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29659, 'nvi', '2 Tessalonicenses', '2ts', 1, 9, 'Eles sofrerão a pena de destruição eterna, a separação da presença do Senhor e da majestade do seu poder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29660, 'nvi', '2 Tessalonicenses', '2ts', 1, 10, 'Isso acontecerá no dia em que ele vier para ser glorificado em seus santos e admirado em todos os que creram, inclusive vocês que creram em nosso testemunho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29661, 'nvi', '2 Tessalonicenses', '2ts', 1, 11, 'Conscientes disso, oramos constantemente por vocês, para que o nosso Deus os faça dignos da vocação e, com poder, cumpra todo bom propósito e toda obra que procede da fé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29662, 'nvi', '2 Tessalonicenses', '2ts', 1, 12, 'Assim o nome de nosso Senhor Jesus será glorificado em vocês, e vocês nele, segundo a graça de nosso Deus e do Senhor Jesus Cristo.');
