-- Inserções para 2 Tessalonicenses 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29663, 'nvi', '2 Tessalonicenses', '2ts', 2, 1, 'Irmãos, quanto à vinda de nosso Senhor Jesus Cristo e à nossa reencontro com ele, rogamos a vocês');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29664, 'nvi', '2 Tessalonicenses', '2ts', 2, 2, 'que não se deixem abalar nem alarmar tão facilmente, quer por profecia, quer por palavra, quer por carta supostamente vinda de nós, como se o dia do Senhor já tivesse chegado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29665, 'nvi', '2 Tessalonicenses', '2ts', 2, 3, 'Não deixem que ninguém os engane de modo algum. Antes daquele dia virá a apostasia e, então, será revelado o homem do pecado, o filho da perdição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29666, 'nvi', '2 Tessalonicenses', '2ts', 2, 4, 'Este se opõe e se exalta acima de tudo o que se chama Deus ou é objeto de adoração, a ponto de se assentar no santuário de Deus, proclamando que ele mesmo é Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29667, 'nvi', '2 Tessalonicenses', '2ts', 2, 5, 'Não se lembram de que quando eu ainda estava com vocês costumava lhes falar essas coisas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29668, 'nvi', '2 Tessalonicenses', '2ts', 2, 6, 'E agora vocês sabem o que o está detendo, para que ele seja revelado no seu devido tempo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29669, 'nvi', '2 Tessalonicenses', '2ts', 2, 7, 'A verdade é que o mistério da iniqüidade já está em ação, restando apenas que seja afastado aquele que agora o detém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29670, 'nvi', '2 Tessalonicenses', '2ts', 2, 8, 'Então será revelado o perverso, a quem o Senhor Jesus matará com o sopro de sua boca e destruirá pela manifestação de sua vinda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29671, 'nvi', '2 Tessalonicenses', '2ts', 2, 9, 'A vinda desse perverso é segundo a ação de Satanás, com todo o poder, com sinais e com maravilhas enganadoras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29672, 'nvi', '2 Tessalonicenses', '2ts', 2, 10, 'Ele fará uso de todas as formas de engano da injustiça para os que estão perecendo, porquanto rejeitaram o amor à verdade que os poderia salvar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29673, 'nvi', '2 Tessalonicenses', '2ts', 2, 11, 'Por essa razão Deus lhes envia um poder sedutor, a fim de que creiam na mentira,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29674, 'nvi', '2 Tessalonicenses', '2ts', 2, 12, 'e sejam condenados todos os que não creram na verdade, mas tiveram prazer na injustiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29675, 'nvi', '2 Tessalonicenses', '2ts', 2, 13, 'Mas nós, devemos sempre dar graças a Deus por vocês, irmãos amados pelo Senhor, porque desde o princípio Deus os escolheu para serem salvos mediante a obra santificadora do Espírito e a fé na verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29676, 'nvi', '2 Tessalonicenses', '2ts', 2, 14, 'Ele os chamou para isso por meio de nosso evangelho, a fim de tomarem posse da glória de nosso Senhor Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29677, 'nvi', '2 Tessalonicenses', '2ts', 2, 15, 'Portanto, irmãos, permaneçam firmes e apeguem-se às tradições que lhes foram ensinadas, quer de viva voz, quer por carta nossa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29678, 'nvi', '2 Tessalonicenses', '2ts', 2, 16, 'Que o próprio Senhor Jesus Cristo e Deus nosso Pai, que nos amou e nos deu eterna consolação e boa esperança pela graça,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29679, 'nvi', '2 Tessalonicenses', '2ts', 2, 17, 'dê ânimo aos seus corações e os fortaleça para fazerem sempre o bem, tanto em atos como em palavras.');
