-- Inserções para 2 Tessalonicenses 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29680, 'nvi', '2 Tessalonicenses', '2ts', 3, 1, 'Finalmente, irmãos, orem por nós, para que a palavra do Senhor se propague rapidamente e receba a hora merecida, como aconteceu entre vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29681, 'nvi', '2 Tessalonicenses', '2ts', 3, 2, 'Orem também para que sejamos libertos dos homens perversos e maus, pois a fé não é de todos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29682, 'nvi', '2 Tessalonicenses', '2ts', 3, 3, 'Mas o Senhor é fiel; ele os fortalecerá e os guardará do Maligno.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29683, 'nvi', '2 Tessalonicenses', '2ts', 3, 4, 'Confiamos no Senhor que vocês estão fazendo e continuarão a fazer as coisas que lhes ordenamos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29684, 'nvi', '2 Tessalonicenses', '2ts', 3, 5, 'O Senhor conduza os seus corações ao amor de Deus e à perseverança de Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29685, 'nvi', '2 Tessalonicenses', '2ts', 3, 6, 'Irmãos, em nome do nosso Senhor Jesus Cristo nós lhes ordenamos que se afastem de todo irmão que vive ociosamente e não conforme a tradição que receberam de nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29686, 'nvi', '2 Tessalonicenses', '2ts', 3, 7, 'Pois vocês mesmos sabem como devem seguir o nosso exemplo, porque não vivemos ociosamente quando estivemos entre vocês,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29687, 'nvi', '2 Tessalonicenses', '2ts', 3, 8, 'nem comemos coisa alguma à custa de ninguém. Pelo contrário, trabalhamos arduamente e com fadiga, dia e noite, para não sermos pesados a nenhum de vocês,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29688, 'nvi', '2 Tessalonicenses', '2ts', 3, 9, 'não por que não tivéssemos tal direito, mas para que nos tornássemos um modelo para ser imitado por vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29689, 'nvi', '2 Tessalonicenses', '2ts', 3, 10, 'Quando ainda estávamos com vocês, nós lhes ordenamos isto: se alguém não quiser trabalhar, também não coma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29690, 'nvi', '2 Tessalonicenses', '2ts', 3, 11, 'Pois ouvimos que alguns de vocês estão ociosos; não trabalham, mas andam se intrometendo na vida alheia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29691, 'nvi', '2 Tessalonicenses', '2ts', 3, 12, 'A tais pessoas ordenamos e exortamos no Senhor Jesus Cristo que trabalhem tranqüilamente e comam o seu próprio pão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29692, 'nvi', '2 Tessalonicenses', '2ts', 3, 13, 'Quanto a vocês, irmãos, nunca se cansem de fazer o bem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29693, 'nvi', '2 Tessalonicenses', '2ts', 3, 14, 'Se alguém não obedecer à nossa palavra por esta carta, marquem-no e não se associem com ele, para que se sinta envergonhado;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29694, 'nvi', '2 Tessalonicenses', '2ts', 3, 15, 'contudo, não o considerem como inimigo, mas chamem a atenção dele como irmão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29695, 'nvi', '2 Tessalonicenses', '2ts', 3, 16, 'O próprio Senhor da paz lhes dê a paz em todo o tempo e de todas as formas. O Senhor seja com todos vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29696, 'nvi', '2 Tessalonicenses', '2ts', 3, 17, 'Eu, Paulo, escrevo esta saudação de próprio punho, a qual é um sinal em todas as minhas cartas. É dessa forma que escrevo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29697, 'nvi', '2 Tessalonicenses', '2ts', 3, 18, 'A graça de nosso Senhor Jesus Cristo seja com todos vocês.');
