-- Inserções para 3 João 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30660, 'nvi', '3 João', '3jo', 1, 1, 'O presbítero ao amado Gaio, a quem amo na verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30661, 'nvi', '3 João', '3jo', 1, 2, 'Amado, oro para que você tenha boa saúde e tudo lhe corra bem, assim como vai bem a sua alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30662, 'nvi', '3 João', '3jo', 1, 3, 'Muito me alegrei ao receber a visita de alguns irmãos que falaram a respeito da sua fidelidade, de como você continua andando na verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30663, 'nvi', '3 João', '3jo', 1, 4, 'Não tenho alegria maior do que ouvir que meus filhos estão andando na verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30664, 'nvi', '3 João', '3jo', 1, 5, 'Amado, você é fiel no que está fazendo pelos irmãos, apesar de lhe serem desconhecidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30665, 'nvi', '3 João', '3jo', 1, 6, 'Eles falaram à igreja a respeito deste seu amor. Você fará bem se os encaminhar em sua viagem de modo agradável a Deus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30666, 'nvi', '3 João', '3jo', 1, 7, 'pois foi por causa do Nome que eles saíram, sem receber ajuda alguma dos gentios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30667, 'nvi', '3 João', '3jo', 1, 8, 'É, pois, nosso dever receber com hospitalidade a irmãos como esses, para que nos tornemos cooperadores em favor da verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30668, 'nvi', '3 João', '3jo', 1, 9, 'Escrevi à igreja, mas Diótrefes, que gosta muito de ser o mais importante entre eles, não nos recebe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30669, 'nvi', '3 João', '3jo', 1, 10, 'Portanto, se eu for, chamarei a atenção dele para o que está fazendo com suas palavras maldosas contra nós. Não satisfeito com isso, ele se recusa a receber os irmãos, impede os que desejam recebê-los e os expulsa da igreja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30670, 'nvi', '3 João', '3jo', 1, 11, 'Amado, não imite o que é mau, mas sim o que é bom. Aquele que faz o bem é de Deus; aquele que faz o mal não viu a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30671, 'nvi', '3 João', '3jo', 1, 12, 'Quanto a Demétrio, todos dão bom testemunho dele, inclusive a própria verdade. Nós também damos, e você sabe que o nosso testemunho é verdadeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30672, 'nvi', '3 João', '3jo', 1, 13, 'Tenho muito que lhe escrever, mas não desejo fazê-lo com pena e tinta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30673, 'nvi', '3 João', '3jo', 1, 14, 'Espero vê-lo em breve, e então conversaremos face a face.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30674, 'nvi', '3 João', '3jo', 1, 15, 'A paz seja com você. Os amigos daqui lhe enviam saudações. Saúde os amigos daí, um por um.');
