-- Inserções para Ageu 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22842, 'nvi', 'Ageu', 'ag', 1, 1, 'No primeiro dia do sexto mês do segundo ano do reinado de Dario, a palavra do Senhor veio por meio do profeta Ageu ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22843, 'nvi', 'Ageu', 'ag', 1, 2, '"Assim diz o Senhor dos Exércitos: Este povo afirma: ‘Ainda não chegou o tempo de reconstruir a casa do Senhor’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22844, 'nvi', 'Ageu', 'ag', 1, 3, 'Por isso, a palavra do Senhor veio novamente por meio do profeta Ageu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22845, 'nvi', 'Ageu', 'ag', 1, 4, '"Acaso é tempo de vocês morarem em casas de fino acabamento, enquanto a minha casa continua destruída? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22846, 'nvi', 'Ageu', 'ag', 1, 5, 'Agora, assim diz o Senhor dos Exércitos: "Vejam aonde os seus caminhos os levaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22847, 'nvi', 'Ageu', 'ag', 1, 6, 'Vocês têm plantado muito, e colhido pouco. Vocês comem, mas não se fartam. Bebem, mas não se satisfazem. Vestem-se, mas não se aquecem. Aquele que recebe salário, recebe-o para colocá-lo numa bolsa furada".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22848, 'nvi', 'Ageu', 'ag', 1, 7, 'Assim diz o Senhor dos Exércitos: "Vejam aonde os seus caminhos os levaram!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22849, 'nvi', 'Ageu', 'ag', 1, 8, 'Subam o monte para trazer madeira. Construam o templo, para que eu me alegre e nele seja glorificado", diz o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22850, 'nvi', 'Ageu', 'ag', 1, 9, '"Vocês esperavam muito, mas, para surpresa de vocês, acabou sendo pouco. E o que vocês trouxeram para casa eu dissipei com um sopro. E por que fiz isso? ", pergunta o Senhor dos Exércitos. "Por causa do meu templo, que ainda está destruído, enquanto cada um de vocês se ocupa com a sua própria casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22851, 'nvi', 'Ageu', 'ag', 1, 10, 'Por isso, por causa de vocês, o céu reteu o orvalho e a terra deixou de dar o seu fruto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22852, 'nvi', 'Ageu', 'ag', 1, 11, 'Provoquei uma seca nos campos e nos montes, que atingiu o trigo, o vinho, o azeite e tudo mais que a terra produz, e também os homens e o gado. O trabalho das mãos de vocês foi prejudicado".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22853, 'nvi', 'Ageu', 'ag', 1, 12, 'Zorobabel, filho de Sealtiel, o sumo sacerdote Josué, filho de Jeozadaque, e todo o restante do povo obedeceram à voz do Senhor, o seu Deus, por causa das palavras do profeta Ageu, a quem o Senhor, o seu Deus, enviara. E o povo temeu ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22854, 'nvi', 'Ageu', 'ag', 1, 13, 'Então Ageu, o mensageiro do Senhor, trouxe esta mensagem do Senhor para o povo: "Eu estou com vocês", declara o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22855, 'nvi', 'Ageu', 'ag', 1, 14, 'Assim o Senhor encorajou o governador de Judá, Zorobabel, filho de Sealtiel, o sumo sacerdote Josué, filho de Jeozadaque, e todo o restante do povo, de modo que eles começaram a trabalhar no templo do Senhor dos Exércitos, o seu Deus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22856, 'nvi', 'Ageu', 'ag', 1, 15, 'no dia vinte e quatro do sexto mês do segundo ano do reinado de Dario.');
