-- Inserções para Amós 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22466, 'nvi', 'Amós', 'am', 7, 1, 'Foi isto que o SENHOR, o Soberano, me mostrou: ele estava preparando enxames de gafanhotos depois da colheita do rei, justo quando brotava a segunda safra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22467, 'nvi', 'Amós', 'am', 7, 2, 'Depois que eles devoraram todas as plantas dos campos, eu clamei: “SENHOR Soberano, perdoa! Como Jacó poderá sobreviver? Ele é tão pequeno! ”');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22468, 'nvi', 'Amós', 'am', 7, 3, 'Então o SENHOR arrependeu-se e declarou: “Isso não acontecerá”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22469, 'nvi', 'Amós', 'am', 7, 4, 'O Soberano, o SENHOR, mostrou-me também que, para o julgamento, estava chamando o fogo, o qual secou o grande abismo e devorou a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22470, 'nvi', 'Amós', 'am', 7, 5, 'Então eu clamei: “Soberano SENHOR, eu te imploro que pares! Como Jacó poderá sobreviver? Ele é tão pequeno! ”');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22471, 'nvi', 'Amós', 'am', 7, 6, 'Então o SENHOR arrependeu-se e declarou: “Isso também não acontecerá”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22472, 'nvi', 'Amós', 'am', 7, 7, 'Ele me mostrou ainda isto: o Senhor, com um prumo na mão, estava junto a um muro construído no rigor do prumo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22473, 'nvi', 'Amós', 'am', 7, 8, 'E o SENHOR me perguntou: “O que você está vendo, Amós? ” “Um prumo”, respondi. Então disse o Senhor: “Veja! Estou pondo um prumo no meio de Israel, o meu povo; não vou poupá-lo mais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22474, 'nvi', 'Amós', 'am', 7, 9, '“Os altares idólatras de Isaque serão destruídos, e os santuários de Israel ficarão em ruínas; com a espada me levantarei contra a dinastia de Jeroboão”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22475, 'nvi', 'Amós', 'am', 7, 10, 'Então o sacerdote de Betel, Amazias, enviou esta mensagem a Jeroboão, rei de Israel: “Amós está tramando uma conspiração contra ti no centro de Israel. A nação não suportará as suas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22476, 'nvi', 'Amós', 'am', 7, 11, 'Amós está dizendo o seguinte: ‘Jeroboão morrerá à espada, e certamente Israel irá para o exílio, para longe da sua terra natal’ ”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22477, 'nvi', 'Amós', 'am', 7, 12, 'Depois Amazias disse a Amós: “Vá embora, vidente! Vá profetizar em Judá; vá ganhar lá o seu pão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22478, 'nvi', 'Amós', 'am', 7, 13, 'Não profetize mais em Betel, porque este é o santuário do rei e o templo do reino”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22479, 'nvi', 'Amós', 'am', 7, 14, 'Amós respondeu a Amazias: “Eu não sou profeta nem pertenço a nenhum grupo de profetasc, apenas cuido do gado e faço colheita de figos silvestres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22480, 'nvi', 'Amós', 'am', 7, 15, 'Mas o SENHOR me tirou do serviço junto ao rebanho e me disse: ‘Vá, profetize a Israel, o meu povo’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22481, 'nvi', 'Amós', 'am', 7, 16, 'Agora ouça, então, a palavra do SENHOR. Você diz: “ ‘Não profetize contra Israel, e pare de pregar contra a descendência de Isaque’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22482, 'nvi', 'Amós', 'am', 7, 17, '“Mas, o SENHOR lhe diz: “ ‘Sua mulher se tornará uma prostituta na cidade, e os seus filhos e as suas filhas morrerão à espada. Suas terras serão loteadas, e você mesmo morrerá numa terra pagãa. E Israel certamente irá para o exílio, para longe da sua terra natal’ ”.');
