-- Inserções para Amós 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22366, 'nvi', 'Amós', 'am', 1, 1, 'Palavras que Amós, criador de ovelhas em Tecoa, recebeu em visões, a respeito de Israel dois anos antes do terremoto. Nesse tempo, Uzias era rei de Judá e Jeroboão, filho de Jeoás, era rei de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22367, 'nvi', 'Amós', 'am', 1, 2, 'Ele disse: "O SENHOR ruge de Sião e troveja de Jerusalém; secam-se as pastagens dos pastores, e murcha o topo do Carmelo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22368, 'nvi', 'Amós', 'am', 1, 3, 'Assim diz o SENHOR: "Por três transgressões de Damasco e ainda mais por quatro, não anularei o castigo. Porque trilhou Gileade com trilhos de ferro pontudos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22369, 'nvi', 'Amós', 'am', 1, 4, 'porei fogo na casa de Hazael que consumirá as fortalezas de Ben-Hadade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22370, 'nvi', 'Amós', 'am', 1, 5, 'Derrubarei a porta de Damasco; destruirei o rei que está no vale de Áven e aquele que segura o cetro em Bete-Éden. O povo da Síria irá para o exílio em Quir", diz o SENHOR.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22371, 'nvi', 'Amós', 'am', 1, 6, 'Assim diz o SENHOR: "Por três transgressões de Gaza, e ainda mais por quatro, não anularei o castigo. Porque levou cativas comunidades inteiras e as vendeu a Edom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22372, 'nvi', 'Amós', 'am', 1, 7, 'porei fogo nos muros de Gaza, que consumirá as suas fortalezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22373, 'nvi', 'Amós', 'am', 1, 8, 'Destruirei o rei de Asdode e aquele que segura o cetro em Ascalom. Erguerei a minha mão contra Ecrom, até que morra o último dos filisteus", diz o SENHOR Soberano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22374, 'nvi', 'Amós', 'am', 1, 9, 'Assim diz o SENHOR: "Por três transgressões de Tiro, e ainda mais por quatro, não anularei o castigo. Porque vendeu comunidades inteiras de cativos a Edom, desprezando irmãos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22375, 'nvi', 'Amós', 'am', 1, 10, 'porei fogo nos muros de Tiro, que consumirá as suas fortalezas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22376, 'nvi', 'Amós', 'am', 1, 11, 'Assim diz o SENHOR: "Por três transgressões de Edom, e ainda mais por quatro, não anularei o castigo. Porque com a espada perseguiu seu irmão, e reprimiu toda a compaixão, mutilando-o furiosamente e perpetuando para sempre a sua ira,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22377, 'nvi', 'Amós', 'am', 1, 12, 'porei fogo em Temã, que consumirá as fortalezas de Bozra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22378, 'nvi', 'Amós', 'am', 1, 13, 'Assim diz o SENHOR: "Por três transgressões de Amom, e ainda mais por quatro, não anularei o castigo. Porque rasgou ao meio as grávidas de Gileade a fim de ampliar as suas fronteiras,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22379, 'nvi', 'Amós', 'am', 1, 14, 'porei fogo nos muros de Rabá, que consumirá as suas fortalezas em meio a gritos de guerra no dia do combate, em meio a ventos violentos num dia de tempestade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22380, 'nvi', 'Amós', 'am', 1, 15, 'O seu rei irá para o exílio, ele e toda a sua corte", diz o SENHOR.');
