-- Inserções para Amós 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22483, 'nvi', 'Amós', 'am', 8, 1, 'O SENHOR, o Soberano, me mostrou um cesto de frutas maduras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22484, 'nvi', 'Amós', 'am', 8, 2, '“O que você está vendo, Amós? ”, ele perguntou. Um cesto de frutas maduras, respondi. Então o SENHOR me disse: “Chegou o fim de Israel, o meu povo; não mais o pouparei”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22485, 'nvi', 'Amós', 'am', 8, 3, '“Naquele dia”, declara o SENHOR, o Soberano, “as canções no templo se tornarão lamentos. Muitos, muitos serão os corpos, atirados por todos os lados! Silêncio! ”');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22486, 'nvi', 'Amós', 'am', 8, 4, 'Ouçam, vocês que pisam os pobres e arruínam os necessitados da terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22487, 'nvi', 'Amós', 'am', 8, 5, 'dizendo: “Quando acabará a lua nova para que vendamos o cereal? E quando terminará o sábado para que comercializemos o trigo, diminuindo a medida, aumentando o preço, enganando com balanças desonestas e');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22488, 'nvi', 'Amós', 'am', 8, 6, 'comprando o pobre com prata e o necessitado por um par de sandálias, vendendo até palha com o trigo? ”');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22489, 'nvi', 'Amós', 'am', 8, 7, 'O SENHOR jurou contra o orgulho de Jacó: “Jamais esquecerei coisa alguma do que eles fizeram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22490, 'nvi', 'Amós', 'am', 8, 8, '“Acaso não tremerá a terra por causa disso, e não chorarão todos os que nela vivem? Toda esta terra se levantará como o Nilo; será agitada e depois afundará como o ribeiro do Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22491, 'nvi', 'Amós', 'am', 8, 9, '“Naquele dia”, declara o SENHOR, o Soberano: “Farei o sol se pôr ao meio-dia e em plena luz do dia escurecerei a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22492, 'nvi', 'Amós', 'am', 8, 10, 'Transformarei as suas festas em velório e todos os seus cânticos em lamentação. Farei que todos vocês vistam roupas de luto e rapem a cabeça. Farei daquele dia um dia de luto por um filho único, e o fim dele, como um dia de amargura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22493, 'nvi', 'Amós', 'am', 8, 11, '“Estão chegando os dias”, declara o SENHOR, o Soberano, “em que enviarei fome a toda esta terra; não fome de comida nem sede de água, mas fome e sede de ouvir as palavras do SENHOR.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22494, 'nvi', 'Amós', 'am', 8, 12, 'Os homens vaguearão de um mar a outro, do Norte ao Oriente, buscando a palavra do SENHOR, mas não a encontrarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22495, 'nvi', 'Amós', 'am', 8, 13, '“Naquele dia as jovens belas e os rapazes fortes desmaiarão de sede.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22496, 'nvi', 'Amós', 'am', 8, 14, 'Aqueles que juram pela vergonhaa de Samaria, e os que dizem: ‘Juro pelo nome do seu deus, ó Dã’ ou ‘Juro pelo nome do deusb de Berseba’, cairão, para nunca mais se levantar! ”');
