-- Inserções para Amós 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22397, 'nvi', 'Amós', 'am', 3, 1, 'Ouçam esta palavra que o SENHOR falou contra vocês, ó israelitas; contra toda esta família que tirei do Egito:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22398, 'nvi', 'Amós', 'am', 3, 2, '"Escolhi apenas vocês de todas as famílias da terra; por isso eu os castigarei por causa de todas as suas maldades".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22399, 'nvi', 'Amós', 'am', 3, 3, 'Duas pessoas andarão juntas se não tiverem de acordo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22400, 'nvi', 'Amós', 'am', 3, 4, 'O leão ruge na floresta se não apanhou presa alguma? O leão novo ruge em sua toca se nada caçou?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22401, 'nvi', 'Amós', 'am', 3, 5, 'Cai o pássaro num laço se não há nenhuma armadilha? Será que a armadilha do laço se desarma se nada foi apanhado?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22402, 'nvi', 'Amós', 'am', 3, 6, 'Quando a trombeta toca na cidade, o povo não treme? Ocorre alguma desgraça na cidade, sem que o SENHOR a tenha mandado?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22403, 'nvi', 'Amós', 'am', 3, 7, 'Certamente o SENHOR Soberano não faz coisa alguma sem revelar o seu plano aos seus servos, os profetas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22404, 'nvi', 'Amós', 'am', 3, 8, 'O leão rugiu, quem não temerá? O SENHOR Soberano falou, quem não profetizará?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22405, 'nvi', 'Amós', 'am', 3, 9, 'Proclamem os palácios de Asdode e do Egito: "Reúnam-se nos montes de Samaria para verem o grande tumulto que há ali e a opressão no meio do seu povo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22406, 'nvi', 'Amós', 'am', 3, 10, '"Eles não sabem como agir direito", declara o SENHOR, "eles, que acumulam em seus palácios o que roubaram e saquearam".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22407, 'nvi', 'Amós', 'am', 3, 11, 'Portanto, assim diz o SENHOR Soberano: "Um inimigo está cercando o país. Ele derrubará as suas fortalezas e saqueará os seus palácios".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22408, 'nvi', 'Amós', 'am', 3, 12, 'Assim diz o SENHOR: "Assim como o pastor arranca da boca do leão só dois ossos da perna ou um pedaço da orelha, assim serão arrancados os israelitas de Samaria, com um canto de cama e um pedaço de sofá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22409, 'nvi', 'Amós', 'am', 3, 13, '"Ouçam isto e testemunhem contra a descendência de Jacó", declara o SENHOR Soberano, o Deus dos Exércitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22410, 'nvi', 'Amós', 'am', 3, 14, '"No dia em que eu castigar Israel por causa dos seus pecados, destruirei os altares de Betel; as pontas do altar serão cortadas e cairão no chão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22411, 'nvi', 'Amós', 'am', 3, 15, 'Derrubarei a casa de inverno junto com a casa de verão; as casas enfeitadas de marfim serão destruídas, e as mansões desaparecerão", declara o SENHOR.');
