-- Inserções para Amós 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22452, 'nvi', 'Amós', 'am', 6, 1, 'Ai de vocês que vivem tranqüilos em Sião, e que se sentem seguros no monte de Samaria; vocês, homens notáveis da primeira entre as nações, aos quais o povo de Israel recorre!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22453, 'nvi', 'Amós', 'am', 6, 2, 'Vão a Calné e olhem para ela; depois prossigam até a grande Hamate e em seguida desçam até Gate, na Filístia. São elas melhores do que os seus dois reinos? O território delas é maior do que o de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22454, 'nvi', 'Amós', 'am', 6, 3, 'Vocês acham que estão afastando o dia mau mas na verdade estão atraindo o reinado do terror.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22455, 'nvi', 'Amós', 'am', 6, 4, 'Vocês se deitam em camas de marfim e se espreguiçam em seus sofás. Comem os melhores cordeiros e os novilhos mais gordos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22456, 'nvi', 'Amós', 'am', 6, 5, 'Dedilham em suas liras como Davi e improvisam em instrumentos musicais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22457, 'nvi', 'Amós', 'am', 6, 6, 'Vocês bebem vinho em grandes taças e se ungem com os mais finos óleos, mas não se entristecem com a ruína de José.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22458, 'nvi', 'Amós', 'am', 6, 7, 'Por isso vocês estarão entre os primeiros a ir para o exílio; cessarão os banquetes dos que vivem no ócio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22459, 'nvi', 'Amós', 'am', 6, 8, 'O SENHOR Soberano jurou por si mesmo! Assim declara o SENHOR, o Deus dos Exércitos: "Eu detesto o orgulho de Jacó e odeio os seus palácios; entregarei a cidade e tudo que nela existe".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22460, 'nvi', 'Amós', 'am', 6, 9, 'Se dez homens forem deixados numa casa, também eles morrerão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22461, 'nvi', 'Amós', 'am', 6, 10, 'E se um parente que tiver que queimar os corpos vier para tirá-los da casa e perguntar a alguém que ainda estiver escondido ali: “Há mais alguém com você? ”, e a resposta for: “Não”, ele dirá: “Calado! Não devemos sequer mencionar o nome do SENHOR”.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22462, 'nvi', 'Amós', 'am', 6, 11, 'Pois o SENHOR deu a ordem, e ele despedaçará a casa grande e fará em pedacinhos a casa pequena.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22463, 'nvi', 'Amós', 'am', 6, 12, 'Acaso correm os cavalos sobre os rochedos? Poderá alguém ará-los com bois? Mas vocês transformaram o direito em veneno, e o fruto da justiça em amargura;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22464, 'nvi', 'Amós', 'am', 6, 13, 'vocês que se regozijam pela conquista de Lo-Debara e dizem: “Acaso não conquistamos Carnaimb com a nossa própria força? ”');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22465, 'nvi', 'Amós', 'am', 6, 14, 'Palavra do SENHOR, o Deus dos Exércitos: “Farei vir uma nação contra você, ó nação de Israel, e ela a oprimirá desde Lebo-Hamate até o vale da Arabá”.');
