-- Inserções para Apocalipse 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30830, 'nvi', 'Apocalipse', 'ap', 8, 1, 'Quando ele abriu o sétimo selo, houve silêncio no céu por volta de meia hora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30831, 'nvi', 'Apocalipse', 'ap', 8, 2, 'Vi os sete anjos que se acham em pé diante de Deus; a eles foram dadas sete trombetas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30832, 'nvi', 'Apocalipse', 'ap', 8, 3, 'Outro anjo, que trazia um incensário de ouro, aproximou-se e se colocou de pé junto ao altar. A ele foi dado muito incenso para oferecer com as orações de todos os santos sobre o altar de ouro diante do trono.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30833, 'nvi', 'Apocalipse', 'ap', 8, 4, 'E da mão do anjo subiu diante de Deus a fumaça do incenso juntamente com as orações dos santos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30834, 'nvi', 'Apocalipse', 'ap', 8, 5, 'Então o anjo pegou o incensário, encheu-o com fogo do altar e lançou-o sobre a terra; e houve trovões, vozes, relâmpagos e um terremoto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30835, 'nvi', 'Apocalipse', 'ap', 8, 6, 'Então os sete anjos, que tinham as sete trombetas, prepararam-se para tocá-las.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30836, 'nvi', 'Apocalipse', 'ap', 8, 7, 'O primeiro anjo tocou a sua trombeta, e granizo e fogo misturado com sangue foram lançados sobre a terra. Foi queimado um terço da terra, um terço das árvores e toda a planta verde.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30837, 'nvi', 'Apocalipse', 'ap', 8, 8, 'O segundo anjo tocou a sua trombeta, e algo como um grande monte em chamas foi lançado ao mar. Um terço do mar transformou-se em sangue,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30838, 'nvi', 'Apocalipse', 'ap', 8, 9, 'morreu um terço das criaturas vivas do mar e foi destruído um terço das embarcações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30839, 'nvi', 'Apocalipse', 'ap', 8, 10, 'O terceiro anjo tocou a sua trombeta, e caiu do céu uma grande estrela, queimando como tocha, sobre um terço dos rios e das fontes de águas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30840, 'nvi', 'Apocalipse', 'ap', 8, 11, 'o nome da estrela é Absinto. Tornou-se amargo um terço das águas, e muitos morreram pela ação das águas que se tornaram amargas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30841, 'nvi', 'Apocalipse', 'ap', 8, 12, 'O quarto anjo tocou a sua trombeta, e foi ferido um terço do sol, um terço da lua e um terço das estrelas, de forma que um terço deles escureceu. Um terço do dia ficou sem luz, e também um terço da noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30842, 'nvi', 'Apocalipse', 'ap', 8, 13, 'Enquanto eu olhava, ouvi uma águia que voava pelo meio do céu e dizia em alta voz: "Ai, ai, ai dos que habitam na terra, por causa do toque das trombetas que está prestes a ser dado pelos três outros anjos! "');
