-- Inserções para Apocalipse 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30813, 'nvi', 'Apocalipse', 'ap', 7, 1, 'Depois disso vi quatro anjos de pé nos quatro cantos da terra, retendo os quatro ventos, para impedir que qualquer vento soprasse na terra, no mar ou em qualquer árvore.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30814, 'nvi', 'Apocalipse', 'ap', 7, 2, 'Então vi outro anjo subindo do Oriente, tendo o selo do Deus vivo. Ele bradou em alta voz aos quatro anjos a quem havia sido dado poder para danificar a terra e o mar:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30815, 'nvi', 'Apocalipse', 'ap', 7, 3, '"Não danifiquem nem a terra, nem o mar nem as árvores, até que selemos as testas dos servos do nosso Deus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30816, 'nvi', 'Apocalipse', 'ap', 7, 4, 'Então ouvi o número dos que foram selados: cento e quarenta e quatro mil, de todas as tribos de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30817, 'nvi', 'Apocalipse', 'ap', 7, 5, 'Da tribo de Judá foram selados doze mil, da tribo de Rúben, doze mil, da tribo de Gade, doze mil,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30818, 'nvi', 'Apocalipse', 'ap', 7, 6, 'da tribo de Aser, doze mil, da tribo de Naftali, doze mil, da tribo de Manassés, doze mil,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30819, 'nvi', 'Apocalipse', 'ap', 7, 7, 'da tribo de Simeão, doze mil, da tribo de Levi, doze mil, da tribo de Issacar, doze mil,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30820, 'nvi', 'Apocalipse', 'ap', 7, 8, 'da tribo de Zebulom, doze mil, da tribo de José, doze mil, da tribo de Benjamim, doze mil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30821, 'nvi', 'Apocalipse', 'ap', 7, 9, 'Depois disso olhei, e diante de mim estava uma grande multidão que ninguém podia contar, de todas as nações, tribos, povos e línguas, de pé, diante do trono e do Cordeiro, com vestes brancas e segurando palmas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30822, 'nvi', 'Apocalipse', 'ap', 7, 10, 'E clamavam em alta voz: "A salvação pertence ao nosso Deus, que se assenta no trono, e ao Cordeiro".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30823, 'nvi', 'Apocalipse', 'ap', 7, 11, 'Todos os anjos estavam de pé ao redor do trono, dos anciãos e dos quatro seres viventes. Eles se prostraram com o rosto em terra diante do trono e adoraram a Deus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30824, 'nvi', 'Apocalipse', 'ap', 7, 12, 'dizendo: "Amém! Louvor e glória, sabedoria, ação de graças, honra, poder e força sejam ao nosso Deus para todo o sempre. Amém! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30825, 'nvi', 'Apocalipse', 'ap', 7, 13, 'Então um dos anciãos me perguntou: "Quem são estes que estão vestidos de branco, e de onde vieram? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30826, 'nvi', 'Apocalipse', 'ap', 7, 14, 'Respondi: "Senhor, tu o sabes". E ele disse: "Estes são os que vieram da grande tribulação e lavaram as suas vestes e as branquearam no sangue do Cordeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30827, 'nvi', 'Apocalipse', 'ap', 7, 15, 'Por isso, eles estão diante do trono de Deus e o servem dia e noite em seu santuário; e aquele que está assentado no trono estenderá sobre eles o seu tabernáculo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30828, 'nvi', 'Apocalipse', 'ap', 7, 16, 'Nunca mais terão fome, nunca mais terão sede. Não cairá sobre eles sol, e nenhum calor abrasador,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30829, 'nvi', 'Apocalipse', 'ap', 7, 17, 'pois o Cordeiro que está no centro do trono será o seu Pastor; ele os guiará às fontes de água viva. E Deus enxugará dos seus olhos toda lágrima".');
