-- Inserções para Apocalipse 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30894, 'nvi', 'Apocalipse', 'ap', 12, 1, 'Apareceu no céu um sinal extraordinário: uma mulher vestida do sol, com a lua debaixo dos seus pés e uma coroa de doze estrelas sobre a cabeça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30895, 'nvi', 'Apocalipse', 'ap', 12, 2, 'Ela estava grávida e gritava de dor, pois estava para dar à luz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30896, 'nvi', 'Apocalipse', 'ap', 12, 3, 'Então apareceu no céu outro sinal: um enorme dragão vermelho com sete cabeças e dez chifres, tendo sobre as cabeças sete coroas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30897, 'nvi', 'Apocalipse', 'ap', 12, 4, 'Sua cauda arrastou consigo um terço das estrelas do céu, lançando-as na terra. O dragão colocou-se diante da mulher que estava para dar à luz, para devorar o seu filho no momento em que nascesse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30898, 'nvi', 'Apocalipse', 'ap', 12, 5, 'Ela deu à luz um filho, um homem, que governará todas as nações com cetro de ferro. Seu filho foi arrebatado para junto de Deus e de seu trono.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30899, 'nvi', 'Apocalipse', 'ap', 12, 6, 'A mulher fugiu para o deserto, para um lugar que lhe havia sido preparado por Deus, para que ali a sustentassem durante mil duzentos e sessenta dias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30900, 'nvi', 'Apocalipse', 'ap', 12, 7, 'Houve então uma guerra no céu. Miguel e seus anjos lutaram contra o dragão, e o dragão e os seus anjos revidaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30901, 'nvi', 'Apocalipse', 'ap', 12, 8, 'Mas estes não foram suficientemente fortes, e assim perderam o seu lugar no céu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30902, 'nvi', 'Apocalipse', 'ap', 12, 9, 'O grande dragão foi lançado fora. Ele é a antiga serpente chamada diabo ou Satanás, que engana o mundo todo. Ele e os seus anjos foram lançado à terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30903, 'nvi', 'Apocalipse', 'ap', 12, 10, 'Então ouvi uma forte voz do céu que dizia: "Agora veio a salvação, o poder e o Reino do nosso Deus, e a autoridade do seu Cristo, pois foi lançado fora o acusador dos nossos irmãos, que os acusa diante do nosso Deus, dia e noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30904, 'nvi', 'Apocalipse', 'ap', 12, 11, 'Eles o venceram pelo sangue do Cordeiro e pela palavra do testemunho que deram; diante da morte, não amaram a própria vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30905, 'nvi', 'Apocalipse', 'ap', 12, 12, 'Portanto, celebrem, ó céus, e os que neles habitam! Mas, ai da terra e do mar, pois o diabo desceu até vocês! Ele está cheio de fúria, pois sabe que lhe resta pouco tempo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30906, 'nvi', 'Apocalipse', 'ap', 12, 13, 'Quando o dragão viu que havia sido lançado à terra, começou a perseguir a mulher que dera à luz o menino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30907, 'nvi', 'Apocalipse', 'ap', 12, 14, 'Foram dadas à mulher as duas asas da grande águia, para que ela pudesse voar para o lugar que lhe havia sido preparado no deserto, onde seria sustentada durante um tempo, tempos e meio tempo, fora do alcance da serpente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30908, 'nvi', 'Apocalipse', 'ap', 12, 15, 'Então a serpente fez jorrar da sua boca água como um rio, para alcançar a mulher e arrastá-la com a correnteza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30909, 'nvi', 'Apocalipse', 'ap', 12, 16, 'A terra, porém, ajudou a mulher, abrindo a boca e engolindo o rio que o dragão fizera jorrar da sua boca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30910, 'nvi', 'Apocalipse', 'ap', 12, 17, 'O dragão irou-se contra a mulher e saiu para guerrear contra o restante da sua descendência, os que obedecem aos mandamentos de Deus e se mantêm fiéis ao testemunho de Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30911, 'nvi', 'Apocalipse', 'ap', 12, 18, 'Então o dragão se pôs em pé na areia do mar.');
