-- Inserções para Apocalipse 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30912, 'nvi', 'Apocalipse', 'ap', 13, 1, 'Vi uma besta que saía do mar. Tinha dez chifres e sete cabeças, com dez coroas, uma sobre cada chifre, e em cada cabeça um nome de blasfêmia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30913, 'nvi', 'Apocalipse', 'ap', 13, 2, 'A besta que vi era semelhante a um leopardo, mas tinha pés como os de urso e boca como a de leão. O dragão deu à besta o seu poder, o seu trono e grande autoridade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30914, 'nvi', 'Apocalipse', 'ap', 13, 3, 'Uma das cabeças da besta parecia ter sofrido um ferimento mortal, mas o ferimento mortal foi curado. Todo o mundo ficou maravilhado e seguiu a besta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30915, 'nvi', 'Apocalipse', 'ap', 13, 4, 'Adoraram o dragão, que tinha dado autoridade à besta, e também adoraram a besta, dizendo: "Quem é como a besta? Quem pode guerrear contra ela? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30916, 'nvi', 'Apocalipse', 'ap', 13, 5, 'À besta foi dada uma boca para falar palavras arrogantes e blasfemas, e lhe foi autoridade para agir durante quarenta e dois meses.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30917, 'nvi', 'Apocalipse', 'ap', 13, 6, 'Ela abriu a boca para blasfemar contra Deus e amaldiçoar o seu nome e o seu tabernáculo, os que habitam no céu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30918, 'nvi', 'Apocalipse', 'ap', 13, 7, 'Foi-lhe dado poder para guerrear contra os santos e vencê-los. Foi-lhe dada autoridade sobre toda tribo, povo, língua e nação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30919, 'nvi', 'Apocalipse', 'ap', 13, 8, 'Todos os habitantes da terra adorarão a besta, a saber, todos aqueles que não tiveram seus nomes escritos no livro da vida do Cordeiro que foi morto desde a criação do mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30920, 'nvi', 'Apocalipse', 'ap', 13, 9, 'Aquele que tem ouvidos ouça:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30921, 'nvi', 'Apocalipse', 'ap', 13, 10, 'Se alguém há de ir para o cativeiro, para o cativeiro irá. Se alguém há de ser morto à espada, à espada haverá de ser morto. Aqui estão a perseverança e a fidelidade dos santos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30922, 'nvi', 'Apocalipse', 'ap', 13, 11, 'Então vi outra besta que saía da terra, com dois chifres como cordeiro, mas que falava como dragão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30923, 'nvi', 'Apocalipse', 'ap', 13, 12, 'Exercia toda a autoridade da primeira besta, em nome dela, e fazia a terra e seus habitantes adorarem a primeira besta, cujo ferimento mortal havia sido curado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30924, 'nvi', 'Apocalipse', 'ap', 13, 13, 'E realizava grandes sinais, chegando a fazer descer fogo do céu à terra, à vista dos homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30925, 'nvi', 'Apocalipse', 'ap', 13, 14, 'Por causa dos sinais que lhe foi permitido realizar em nome da primeira besta, ela enganou os habitantes da terra. Ordenou-lhes que fizessem uma imagem em honra da besta que fora ferida pela espada e contudo revivera.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30926, 'nvi', 'Apocalipse', 'ap', 13, 15, 'Foi-lhe dado poder para dar fôlego à imagem da primeira besta, de modo que ela podia falar e fazer que fossem mortos todos os que se recusassem a adorar a imagem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30927, 'nvi', 'Apocalipse', 'ap', 13, 16, 'Também obrigou todos, pequenos e grandes, ricos e pobres, livres e escravos, a receberem certa marca na mão direita ou na testa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30928, 'nvi', 'Apocalipse', 'ap', 13, 17, 'para que ninguém pudesse comprar nem vender, a não ser quem tivesse a marca, que é o nome da besta ou o número do seu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30929, 'nvi', 'Apocalipse', 'ap', 13, 18, 'Aqui há sabedoria. Aquele que tem entendimento calcule o número da besta, pois é número de homem. Seu número é seiscentos e sessenta e seis.');
