-- Inserções para Atos 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27103, 'nvi', 'Atos', 'atos', 6, 1, 'Naqueles dias, crescendo o número de discípulos, os judeus de fala grega entre eles queixaram-se dos judeus de fala hebraica, porque suas viúvas estavam sendo esquecidas na distribuição diária de alimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27104, 'nvi', 'Atos', 'atos', 6, 2, 'Por isso os Doze reuniram todos os discípulos e disseram: "Não é certo negligenciarmos o ministério da palavra de Deus, a fim de servir às mesas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27105, 'nvi', 'Atos', 'atos', 6, 3, 'Irmãos, escolham entre vocês sete homens de bom testemunho, cheios do Espírito e de sabedoria. Passaremos a eles essa tarefa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27106, 'nvi', 'Atos', 'atos', 6, 4, 'e nos dedicaremos à oração e ao ministério da palavra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27107, 'nvi', 'Atos', 'atos', 6, 5, 'Tal proposta agradou a todos. Então escolheram Estêvão, homem cheio de fé e do Espírito Santo, além de Filipe, Prócoro, Nicanor, Timom, Pármenas e Nicolau, um convertido ao judaísmo, proveniente de Antioquia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27108, 'nvi', 'Atos', 'atos', 6, 6, 'Apresentaram esses homens aos apóstolos, os quais oraram e lhes impuseram as mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27109, 'nvi', 'Atos', 'atos', 6, 7, 'Assim, a palavra de Deus se espalhava. Crescia rapidamente o número de discípulos em Jerusalém; também um grande número de sacerdotes obedecia à fé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27110, 'nvi', 'Atos', 'atos', 6, 8, 'Estêvão, homem cheio da graça e do poder de Deus, realizava grandes maravilhas e sinais entre o povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27111, 'nvi', 'Atos', 'atos', 6, 9, 'Contudo, levantou-se oposição dos membros da chamada Sinagoga dos Libertos, dos judeus de Cirene e de Alexandria, bem como das províncias da Cilícia e da Ásia. Esses homens começaram a discutir com Estêvão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27112, 'nvi', 'Atos', 'atos', 6, 10, 'mas não podiam resistir à sabedoria e ao Espírito com que ele falava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27113, 'nvi', 'Atos', 'atos', 6, 11, 'Então subornaram alguns homens para dizerem: "Ouvimos Estêvão falar palavras blasfemas contra Moisés e contra Deus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27114, 'nvi', 'Atos', 'atos', 6, 12, 'Com isso agitaram o povo, os líderes religiosos e os mestres da lei. E, prendendo Estêvão, levaram-no ao Sinédrio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27115, 'nvi', 'Atos', 'atos', 6, 13, 'Ali apresentaram falsas testemunhas que diziam: "Este homem não pára de falar contra este lugar santo e contra a lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27116, 'nvi', 'Atos', 'atos', 6, 14, 'Pois o ouvimos dizer que esse Jesus, o Nazareno, destruirá este lugar e mudará os costumes que Moisés nos legou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (27117, 'nvi', 'Atos', 'atos', 6, 15, 'Olhando para ele, todos os que estavam sentados no Sinédrio viram que o seu rosto parecia o rosto de um anjo.');
