-- Inserções para Colossenses 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29544, 'nvi', 'Colossenses', 'cl', 4, 1, 'Senhores, dêem aos seus escravos o que é justo e direito, sabendo que vocês também têm um Senhor no céu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29545, 'nvi', 'Colossenses', 'cl', 4, 2, 'Dediquem-se à oração, estejam alertas e sejam agradecidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29546, 'nvi', 'Colossenses', 'cl', 4, 3, 'Ao mesmo tempo, orem também por nós, para que Deus abra uma porta para a nossa mensagem, a fim de que possamos proclamar o mistério de Cristo, pelo qual estou preso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29547, 'nvi', 'Colossenses', 'cl', 4, 4, 'Orem para que eu possa manifestá-lo abertamente, como me cumpre fazê-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29548, 'nvi', 'Colossenses', 'cl', 4, 5, 'Sejam sábios no procedimento para com os de fora; aproveitem ao máximo todas as oportunidades.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29549, 'nvi', 'Colossenses', 'cl', 4, 6, 'O seu falar seja sempre agradável e temperado com sal, para que saibam como responder a cada um.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29550, 'nvi', 'Colossenses', 'cl', 4, 7, 'Tíquico lhes informará todas as coisas a meu respeito. Ele é um irmão amado, ministro fiel e cooperador no serviço do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29551, 'nvi', 'Colossenses', 'cl', 4, 8, 'Eu o envio a vocês precisamente com o propósito de que saibam de tudo o que se passa conosco, e para que ele fortaleça os seus corações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29552, 'nvi', 'Colossenses', 'cl', 4, 9, 'Ele irá com Onésimo, fiel e amado irmão, que é um de vocês. Eles irão contar-lhes tudo o que está acontecendo aqui.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29553, 'nvi', 'Colossenses', 'cl', 4, 10, 'Aristarco, meu companheiro de prisão, envia-lhes saudações, bem como Marcos, primo de Barnabé. Vocês receberam instruções a respeito de Marcos, e se ele for visitá-los, recebam-no.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29554, 'nvi', 'Colossenses', 'cl', 4, 11, 'Jesus, chamado Justo, também envia saudações. Estes são os únicos da circuncisão que são meus cooperadores em favor do Reino de Deus. Eles têm sido uma fonte de ânimo para mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29555, 'nvi', 'Colossenses', 'cl', 4, 12, 'Epafras, que é um de vocês e servo de Cristo Jesus, envia saudações. Ele está sempre batalhando por vocês em oração, para que, como pessoas maduras e plenamente convictas, continuem firmes em toda a vontade de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29556, 'nvi', 'Colossenses', 'cl', 4, 13, 'Dele dou testemunho de que se esforça muito por vocês e pelos que estão em Laodicéia e em Hierápolis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29557, 'nvi', 'Colossenses', 'cl', 4, 14, 'Lucas, o médico amado, e Demas, enviam saudações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29558, 'nvi', 'Colossenses', 'cl', 4, 15, 'Saúdem os irmãos de Laodicéia, bem como Ninfa e a igreja que se reúne em sua casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29559, 'nvi', 'Colossenses', 'cl', 4, 16, 'Depois que esta carta for lida entre vocês, façam que também seja lida na igreja dos laodicenses, e que vocês igualmente leiam a carta de Laodicéia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29560, 'nvi', 'Colossenses', 'cl', 4, 17, 'Digam a Arquipo: "Cuide em cumprir o ministério que você recebeu no Senhor".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29561, 'nvi', 'Colossenses', 'cl', 4, 18, 'Eu, Paulo, escrevo esta saudação de próprio punho. Lembrem-se das minhas algemas. A graça seja com vocês.');
