-- Inserções para Cânticos 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17600, 'nvi', 'Cânticos', 'ct', 5, 1, 'Entrei em meu jardim, minha irmã, minha noiva; ajuntei a minha mirra com as minhas especiarias. Comi o meu favo e o meu mel; Bebi o meu vinho e o meu leite. Comam, amigos, bebam e embriaguem-se, ó amados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17601, 'nvi', 'Cânticos', 'ct', 5, 2, 'Eu estava quase dormindo, mas o meu coração estava acordado. Escutem! O meu amado está batendo: Abra-me a porta, minha irmã, minha querida, minha pomba, minha mulher ideal, pois a minha cabeça está encharcada de orvalho, o meu cabelo, da umidade da noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17602, 'nvi', 'Cânticos', 'ct', 5, 3, 'Já tirei a túnica; terei que vestir-me de novo? Já lavei os pés; terei que sujá-los de novo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17603, 'nvi', 'Cânticos', 'ct', 5, 4, 'O meu amado pôs a mão por uma abertura da tranca; meu coração começou a palpitar por causa dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17604, 'nvi', 'Cânticos', 'ct', 5, 5, 'Levantei-me para abrir-lhe a porta; minhas mãos destilavam mirra, meus dedos vertiam mirra, na maçaneta da tranca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17605, 'nvi', 'Cânticos', 'ct', 5, 6, 'Eu abri, mas o meu amado se fora; o meu amado já havia partido. Eu quase desmaiei de tristeza! Procurei-o, mas não o encontrei. Eu o chamei, mas ele não respondeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17606, 'nvi', 'Cânticos', 'ct', 5, 7, 'As sentinelas me encontraram enquanto faziam a ronda na cidade. Bateram-me, feriram-me; e tomaram o meu manto, as sentinelas dos muros!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17607, 'nvi', 'Cânticos', 'ct', 5, 8, 'Ó mulheres de Jerusalém, eu lhes faço jurar: se encontrarem o meu amado, o que dirão a ele? Digam-lhe que estou doente de amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17608, 'nvi', 'Cânticos', 'ct', 5, 9, 'Que diferença há entre o seu amado e outro qualquer, ó você, das mulheres a mais linda? Que diferença há entre o seu amado e outro qualquer, para você nos obrigar a tal promessa?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17609, 'nvi', 'Cânticos', 'ct', 5, 10, 'O meu amado tem a pele bronzeada; ele se destaca entre dez mil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17610, 'nvi', 'Cânticos', 'ct', 5, 11, 'Sua cabeça é ouro, o ouro mais puro; seus cabelos ondulam ao vento como ramos de palmeira; são negros como o corvo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17611, 'nvi', 'Cânticos', 'ct', 5, 12, 'Seus olhos são como pombas junto aos regatos de água, lavados em leite, incrustados como jóias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17612, 'nvi', 'Cânticos', 'ct', 5, 13, 'Suas faces são como um jardim de especiarias que exalam perfume. Seus lábios são como lírios que destilam mirra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17613, 'nvi', 'Cânticos', 'ct', 5, 14, 'Seus braços são cilindros de ouro engastados com berilo. Seu tronco é como marfim polido adornado de safiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17614, 'nvi', 'Cânticos', 'ct', 5, 15, 'Suas pernas são colunas de mármore firmadas em bases de ouro puro. Sua aparência é como o Líbano; ele é elegante como os cedros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17615, 'nvi', 'Cânticos', 'ct', 5, 16, 'Sua boca é a própria doçura; ele é mui desejável. Esse é o meu amado, esse é o meu querido, ó mulheres de Jerusalém.');
