-- Inserções para Cânticos 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17556, 'nvi', 'Cânticos', 'ct', 2, 1, 'Sou uma flor de Sarom, um lírio dos vales.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17557, 'nvi', 'Cânticos', 'ct', 2, 2, 'Como um lírio entre os espinhos é a minha amada entre as jovens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17558, 'nvi', 'Cânticos', 'ct', 2, 3, 'Como uma macieira entre as árvores da floresta é o meu amado entre os jovens. Tenho prazer em sentar-me à sua sombra; o seu fruto é doce ao meu paladar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17559, 'nvi', 'Cânticos', 'ct', 2, 4, 'Ele me levou ao salão de banquetes, e o seu estandarte sobre mim é o amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17560, 'nvi', 'Cânticos', 'ct', 2, 5, 'Por favor, sustentem-me com passas, revigorem-me com maçãs, pois estou doente de amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17561, 'nvi', 'Cânticos', 'ct', 2, 6, 'O seu braço esquerdo esteja debaixo da minha cabeça, e o seu braço direito me abrace.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17562, 'nvi', 'Cânticos', 'ct', 2, 7, 'Mulheres de Jerusalém, eu as faço jurar pelas gazelas e pelas corças do campo: não despertem nem provoquem o amor enquanto ele não o quiser.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17563, 'nvi', 'Cânticos', 'ct', 2, 8, 'Escutem! É o meu amado! Vejam! Aí vem ele, saltando pelos montes, pulando sobre as colinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17564, 'nvi', 'Cânticos', 'ct', 2, 9, 'O meu amado é como uma gazela, como um cervo novo. Vejam! Lá está ele atrás do nosso muro, observando pelas janelas, espiando pelas grades.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17565, 'nvi', 'Cânticos', 'ct', 2, 10, 'O meu amado falou e me disse: Levante-se, minha querida, minha bela, e venha comigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17566, 'nvi', 'Cânticos', 'ct', 2, 11, 'Veja! O inverno passou; as chuvas acabaram e já se foram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17567, 'nvi', 'Cânticos', 'ct', 2, 12, 'Aparecem flores sobre a terra, e chegou o tempo de cantar; já se ouve em nossa terra o arrulhar dos pombos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17568, 'nvi', 'Cânticos', 'ct', 2, 13, 'A figueira produz os primeiros frutos; as vinhas florescem e espalham sua fragrância. Levante-se, venha, minha querida; minha bela, venha comigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17569, 'nvi', 'Cânticos', 'ct', 2, 14, 'Minha pomba que está nas fendas da rocha, nos esconderijos, nas encostas dos montes, mostre-me o seu rosto, deixe-me ouvir a sua voz; pois a sua voz é suave, e o seu rosto é lindo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17570, 'nvi', 'Cânticos', 'ct', 2, 15, 'Apanhem para nós as raposas, as raposinhas que estragam as vinhas, pois as nossas vinhas estão floridas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17571, 'nvi', 'Cânticos', 'ct', 2, 16, 'O meu amado é meu, e eu sou dele; ele pastoreia entre os lírios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17572, 'nvi', 'Cânticos', 'ct', 2, 17, 'Volte, amado meu, antes que rompa o dia e fujam as sombras, e seja como a gazela ou como o cervo novo nas colinas escarpadas.');
