-- Inserções para Cânticos 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17573, 'nvi', 'Cânticos', 'ct', 3, 1, 'A noite toda procurei em meu leito aquele a quem o meu coração ama, mas não o encontrei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17574, 'nvi', 'Cânticos', 'ct', 3, 2, 'Vou levantar-me agora e percorrer a cidade, irei por suas ruas e praças; buscarei aquele a quem o meu coração ama. Eu o procurei, mas não o encontrei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17575, 'nvi', 'Cânticos', 'ct', 3, 3, 'As sentinelas me encontraram quando faziam as suas rondas na cidade. "Vocês viram aquele a quem o meu coração ama? ", perguntei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17576, 'nvi', 'Cânticos', 'ct', 3, 4, 'Mal havia passado por elas, quando encontrei aquele a quem o meu coração ama. Eu o segurei e não o deixei ir até que o trouxe para a casa de minha mãe, para o quarto daquela que me concebeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17577, 'nvi', 'Cânticos', 'ct', 3, 5, 'Mulheres de Jerusalém, eu as faço jurar pelas gazelas e pelas corças do campo: Não despertem nem incomodem o amor enquanto ele não o quiser.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17578, 'nvi', 'Cânticos', 'ct', 3, 6, 'Que é que vem subindo do deserto, como uma coluna de fumaça, perfumado com mirra e incenso com extrato de todas as especiarias dos mercadores?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17579, 'nvi', 'Cânticos', 'ct', 3, 7, 'Vejam! É a liteira de Salomão, escoltada por sessenta guerreiros, os mais nobres de Israel;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17580, 'nvi', 'Cânticos', 'ct', 3, 8, 'todos eles trazem espada, todos são experientes na guerra, cada um com a sua espada, preparado para enfrentar os pavores da noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17581, 'nvi', 'Cânticos', 'ct', 3, 9, 'O rei Salomão fez para si uma liteira; ele a fez com madeira do Líbano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17582, 'nvi', 'Cânticos', 'ct', 3, 10, 'Suas traves ele fez de prata, seu teto, de ouro. Seu banco foi estofado em púrpura, seu interior foi cuidadosamente preparado pelas mulheres de Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17583, 'nvi', 'Cânticos', 'ct', 3, 11, 'Mulheres de Sião, saiam! Venham ver o rei Salomão! Ele está usando a coroa, a coroa que sua mãe lhe colocou no dia do seu casamento, no dia em que o seu coração se alegrou.');
