-- Inserções para Cânticos 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17584, 'nvi', 'Cânticos', 'ct', 4, 1, 'Como você é linda, minha querida! Ah, como é linda! Seus olhos, por trás do véu, são pombas. Seu cabelo é como um rebanho de cabras que vem descendo do monte Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17585, 'nvi', 'Cânticos', 'ct', 4, 2, 'Seus dentes são como um rebanho de ovelhas recém-tosquiadas que vão subindo do lavadouro. Cada uma tem o seu par; não há nenhuma sem crias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17586, 'nvi', 'Cânticos', 'ct', 4, 3, 'Seus lábios são como um fio vermelho; sua boca é belíssima. Suas faces, por trás do véu, são como as metades de uma romã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17587, 'nvi', 'Cânticos', 'ct', 4, 4, 'Seu pescoço é como a torre de Davi, construída como arsenal. Nela estão pendurados mil escudos, todos eles escudos de heróicos guerreiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17588, 'nvi', 'Cânticos', 'ct', 4, 5, 'Seus dois seios são como filhotes de cervo, como filhotes gêmeos de uma gazela que repousam entre os lírios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17589, 'nvi', 'Cânticos', 'ct', 4, 6, 'Enquanto não raia o dia e as sombras não fogem, irei à montanha da mirra e à colina do incenso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17590, 'nvi', 'Cânticos', 'ct', 4, 7, 'Você é toda linda, minha querida; em você não há defeito algum.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17591, 'nvi', 'Cânticos', 'ct', 4, 8, 'Venha do Líbano comigo, minha noiva, venha do Líbano comigo. Desça do alto do Amana, do topo do Senir, do alto do Hermom, das covas dos leões e das tocas dos leopardos nas montanhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17592, 'nvi', 'Cânticos', 'ct', 4, 9, 'Você fez disparar o meu coração, minha irmã, minha noiva; fez disparar o meu coração com um simples olhar, com uma simples jóia dos seus colares.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17593, 'nvi', 'Cânticos', 'ct', 4, 10, 'Quão deliciosas são as suas carícias, minha irmã, minha noiva! Suas carícias são mais agradáveis que o vinho, e a fragrância do seu perfume supera o de qualquer especiaria!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17594, 'nvi', 'Cânticos', 'ct', 4, 11, 'Os seus lábios gotejam a doçura dos favos de mel, minha noiva; leite e mel estão debaixo da sua língua. A fragrância das suas vestes é como a fragrância do Líbano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17595, 'nvi', 'Cânticos', 'ct', 4, 12, 'Você é um jardim fechado, minha irmã, minha noiva; você é uma nascente fechada, uma fonte selada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17596, 'nvi', 'Cânticos', 'ct', 4, 13, 'De você brota um pomar de romãs com frutos seletos, com flores de hena e nardo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17597, 'nvi', 'Cânticos', 'ct', 4, 14, 'nardo e açafrão, cálamo e canela, com todas as madeiras aromáticas, mirra e aloés e as mais finas especiarias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17598, 'nvi', 'Cânticos', 'ct', 4, 15, 'Você é uma fonte de jardim, um poço de águas vivas, que descem do Líbano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17599, 'nvi', 'Cânticos', 'ct', 4, 16, 'Acorde, vento norte! Venha, vento sul! Soprem em meu jardim, para que a sua fragrância se espalhe ao seu redor. Que o meu amado entre em seu jardim e saboreie os seus deliciosos frutos.');
