-- Inserções para Cânticos 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17539, 'nvi', 'Cânticos', 'ct', 1, 1, 'Cântico dos Cânticos de Salomão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17540, 'nvi', 'Cânticos', 'ct', 1, 2, 'Ah, se ele me beijasse, se a sua boca me cobrisse de beijos... Sim, as suas carícias são mais agradáveis que o vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17541, 'nvi', 'Cânticos', 'ct', 1, 3, 'A fragrância dos seus perfumes é suave; o seu nome é como perfume derramado. Não é à toa que as jovens o amam!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17542, 'nvi', 'Cânticos', 'ct', 1, 4, 'Leve-me com você! Vamos depressa! Leve-me o rei para os seus aposentos! Estamos alegres e felizes por sua causa; celebraremos o seu amor mais do que o vinho. Com toda a razão você é amado!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17543, 'nvi', 'Cânticos', 'ct', 1, 5, 'Estou escura, mas sou bela, ó mulheres de Jerusalém; escura como as tendas de Quedar, bela como as cortinas de Salomão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17544, 'nvi', 'Cânticos', 'ct', 1, 6, 'Não me fiquem olhando assim porque estou escura; foi o sol que me queimou a pele. Os filhos de minha mãe zangaram-se comigo e fizeram-me tomar conta das vinhas; da minha própria vinha, porém, eu não pude cuidar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17545, 'nvi', 'Cânticos', 'ct', 1, 7, 'Conte-me, você a quem amo, onde faz pastar o seu rebanho e onde faz as suas ovelhas descansarem ao meio-dia? Se eu não o souber, serei como uma mulher coberta com véu junto aos rebanhos dos seus amigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17546, 'nvi', 'Cânticos', 'ct', 1, 8, 'Se você, a mais linda das mulheres, se você não o sabe, siga a trilha das ovelhas e faça as suas cabritas pastarem junto às tendas dos pastores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17547, 'nvi', 'Cânticos', 'ct', 1, 9, 'Comparo você, minha querida, a uma égua das carruagens do faraó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17548, 'nvi', 'Cânticos', 'ct', 1, 10, 'Como são belas as suas faces entre os brincos, e o seu pescoço com os colares de jóias!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17549, 'nvi', 'Cânticos', 'ct', 1, 11, 'Faremos para você brincos de ouro com incrustações de prata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17550, 'nvi', 'Cânticos', 'ct', 1, 12, 'Enquanto o rei estava em seus aposentos, o meu nardo espalhou a sua fragrância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17551, 'nvi', 'Cânticos', 'ct', 1, 13, 'O meu amado é para mim como uma pequenina bolsa de mirra que passa a noite entre os meus seios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17552, 'nvi', 'Cânticos', 'ct', 1, 14, 'O meu amado é para mim um ramalhete de flores de hena das vinhas de En-Gedi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17553, 'nvi', 'Cânticos', 'ct', 1, 15, 'Como você é linda, minha querida! Ah, como é linda! Seus olhos são pombas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17554, 'nvi', 'Cânticos', 'ct', 1, 16, 'Como você é belo, meu amado! Ah, como é encantador! Verdejante é o nosso leito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17555, 'nvi', 'Cânticos', 'ct', 1, 17, 'De cedro são as vigas da nossa casa, e de cipreste os caibros do nosso telhado.');
