-- Inserções para Cânticos 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17616, 'nvi', 'Cânticos', 'ct', 6, 1, 'Para onde foi o seu amado, ó mais linda das mulheres? Diga-nos para onde foi o seu amado e o procuraremos junto com você!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17617, 'nvi', 'Cânticos', 'ct', 6, 2, 'O meu amado desceu ao seu jardim, aos canteiros de especiarias, para descansar nos jardins e colher lírios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17618, 'nvi', 'Cânticos', 'ct', 6, 3, 'Eu sou do meu amado, e o meu amado é meu; ele descansa entre os lírios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17619, 'nvi', 'Cânticos', 'ct', 6, 4, 'Minha querida, você é linda como Tirza, bela como Jerusalém, admirável como um exército e suas bandeiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17620, 'nvi', 'Cânticos', 'ct', 6, 5, 'Desvie de mim os seus olhos, pois eles me perturbam. Seu cabelo é como um rebanho de cabras que desce de Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17621, 'nvi', 'Cânticos', 'ct', 6, 6, 'Seus dentes são como um rebanho de ovelhas que sobem do lavadouro. Cada uma tem o seu par, não há nenhuma sem crias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17622, 'nvi', 'Cânticos', 'ct', 6, 7, 'Suas faces, por trás do véu, são como as metades de uma romã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17623, 'nvi', 'Cânticos', 'ct', 6, 8, 'Pode haver sessenta rainhas, e oitenta concubinas, e um número sem fim de virgens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17624, 'nvi', 'Cânticos', 'ct', 6, 9, 'mas ela é única, a minha pomba, minha mulher ideal! Ela é a filha favorita de sua mãe, a predileta daquela que a deu à luz. Quando outras jovens a vêem, dizem que ela é muito feliz; as rainhas e as concubinas a elogiam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17625, 'nvi', 'Cânticos', 'ct', 6, 10, 'Quem é essa que aparece como o alvorecer, bela como a lua, brilhante como o sol, admirável como um exército e suas bandeiras?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17626, 'nvi', 'Cânticos', 'ct', 6, 11, 'Desci ao bosque das nogueiras para ver os renovos no vale, para ver se as videiras tinham brotado e se as romãs estavam em flor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17627, 'nvi', 'Cânticos', 'ct', 6, 12, 'Antes que eu o percebesse, você me colocou entre as carruagens, com um príncipe ao meu lado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17628, 'nvi', 'Cânticos', 'ct', 6, 13, 'Volte, volte, Sulamita; volte, volte, para que a contemplemos. Por que vocês querem contemplar a Sulamita, como na dança de Maanaim?');
