-- Inserções para Cânticos 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17629, 'nvi', 'Cânticos', 'ct', 7, 1, 'Como são lindos os seus pés calçados com sandálias, ó filha do príncipe! As curvas das suas coxas são como jóias, obra das mãos de um artífice.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17630, 'nvi', 'Cânticos', 'ct', 7, 2, 'Seu umbigo é uma taça redonda onde nunca falta o vinho de boa mistura. Sua cintura é um monte de trigo cercado de lírios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17631, 'nvi', 'Cânticos', 'ct', 7, 3, 'Seus seios são como dois filhotes de corça, gêmeos de uma gazela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17632, 'nvi', 'Cânticos', 'ct', 7, 4, 'Seu pescoço é como uma torre de marfim. Seus olhos são como os açudes de Hesbom, junto à porta de Bate-Rabim. Seu nariz é como a torre do Líbano voltada para Damasco.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17633, 'nvi', 'Cânticos', 'ct', 7, 5, 'Sua cabeça se eleva como o monte Carmelo. Seus cabelos soltos têm reflexos de púrpura; o rei caiu prisioneiro das suas ondas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17634, 'nvi', 'Cânticos', 'ct', 7, 6, 'Como você é linda! Como você me agrada! Ó amor, com suas delícias!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17635, 'nvi', 'Cânticos', 'ct', 7, 7, 'Seu porte é como o da palmeira, e os seus seios como cachos de frutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17636, 'nvi', 'Cânticos', 'ct', 7, 8, 'Eu disse: Subirei à palmeira; eu me apossarei dos seus frutos. Sejam os seus seios como os cachos da videira, o aroma da sua respiração como maçãs,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17637, 'nvi', 'Cânticos', 'ct', 7, 9, 'e a sua boca como o melhor vinho... vinho que flui suavemente para o meu amado, escorrendo suavemente sobre os lábios de quem já vai adormecendo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17638, 'nvi', 'Cânticos', 'ct', 7, 10, 'Eu pertenço ao meu amado, e ele me deseja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17639, 'nvi', 'Cânticos', 'ct', 7, 11, 'Venha, meu amado, vamos fugir para o campo, passemos a noite nos povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17640, 'nvi', 'Cânticos', 'ct', 7, 12, 'Vamos cedo para as vinhas para ver se as videiras brotaram, se as suas flores se abriram, e se as romãs estão em flor; ali eu lhe darei o meu amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17641, 'nvi', 'Cânticos', 'ct', 7, 13, 'As mandrágoras exalam o seu perfume, e à nossa porta há todo tipo de frutos finos, secos e frescos, que reservei para você, meu amado.');
