-- Inserções para Daniel 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22083, 'nvi', 'Daniel', 'dn', 12, 1, '"Naquela ocasião Miguel, o grande príncipe que protege o seu povo, se levantará. Haverá um tempo de angústia tal como nunca houve desde o início das nações e até então. Mas naquela ocasião o seu povo, todo aquele cujo nome está escrito no livro, será liberto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22084, 'nvi', 'Daniel', 'dn', 12, 2, 'Multidões que dormem no pó da terra acordarão: uns para a vida eterna, outros para a vergonha, para o desprezo eterno.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22085, 'nvi', 'Daniel', 'dn', 12, 3, 'Aqueles que são sábios reluzirão como o brilho do céu, e aqueles que conduzem muitos à justiça serão como as estrelas, para todo o sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22086, 'nvi', 'Daniel', 'dn', 12, 4, 'Mas você, Daniel, feche com um selo as palavras do livro até o tempo do fim. Muitos irão ali e acolá para aumentarem o conhecimento".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22087, 'nvi', 'Daniel', 'dn', 12, 5, 'Então eu, Daniel, olhei, e diante de mim estavam dois outros, um na margem de cá do rio e outro na margem de lá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22088, 'nvi', 'Daniel', 'dn', 12, 6, 'Um deles disse ao homem vestido de linho, que estava acima das águas do rio: "Quanto tempo decorrerá antes de se cumprirem essas coisas estupendas? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22089, 'nvi', 'Daniel', 'dn', 12, 7, 'O homem vestido de linho, que estava acima das águas do rio, ergueu para o céu a mão direita e a mão esquerda, e eu o ouvi jurar por aquele que vive para sempre, dizendo: "Haverá um tempo, tempos e meio tempo. Quando o poder do povo santo for finalmente quebrado, todas essas coisas se cumprirão".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22090, 'nvi', 'Daniel', 'dn', 12, 8, 'Eu ouvi, mas não compreendi. Por isso perguntei: "Meu senhor, qual será o resultado disso tudo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22091, 'nvi', 'Daniel', 'dn', 12, 9, 'Ele respondeu: "Siga o seu caminho, Daniel, pois as palavras estão seladas e lacradas até o tempo do fim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22092, 'nvi', 'Daniel', 'dn', 12, 10, 'Muitos serão purificados, alvejados e refinados, mas os ímpios continuarão ímpios. Nenhum dos ímpios levará isto em consideração, mas os sábios sim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22093, 'nvi', 'Daniel', 'dn', 12, 11, '"A partir do momento em que for abolido o sacrifício diário e for colocado o sacrilégio terrível, haverá mil e duzentos e noventa dias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22094, 'nvi', 'Daniel', 'dn', 12, 12, 'Feliz aquele que esperar e alcançar o fim dos mil trezentos e trinta e cinco dias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22095, 'nvi', 'Daniel', 'dn', 12, 13, '"Quanto a você, siga o seu caminho até o fim. Você descansará, e então, no final dos dias, você se levantará para receber a herança que lhe cabe".');
