-- Inserções para Deuteronômio 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5273, 'nvi', 'Deuteronômio', 'dt', 13, 1, 'Se aparecer entre vocês um profeta ou alguém que faz predições por meio de sonhos e lhes anunciar um sinal miraculoso ou um prodígio,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5274, 'nvi', 'Deuteronômio', 'dt', 13, 2, 'e se o sinal ou prodígio de que ele falou acontecer, e ele disser: "Vamos seguir outros deuses que vocês não conhecem e vamos adorá-los",');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5275, 'nvi', 'Deuteronômio', 'dt', 13, 3, 'não dêem ouvidos às palavras daquele profeta ou sonhador. O Senhor, o seu Deus, está pondo vocês à prova para ver se o amam de todo o coração e de toda a alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5276, 'nvi', 'Deuteronômio', 'dt', 13, 4, 'Sigam somente o Senhor, o seu Deus, e temam a ele somente. Cumpram os seus mandamentos e obedeçam-lhe; sirvam-no e apeguem-se a ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5277, 'nvi', 'Deuteronômio', 'dt', 13, 5, 'Aquele profeta ou sonhador terá que ser morto, pois pregou rebelião contra o Senhor, contra o seu Deus, que os tirou do Egito e os redimiu da terra da escravidão; ele tentou afastá-los do caminho que o Senhor, o seu Deus, lhes ordenou que seguissem. Eliminem o mal do meio de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5278, 'nvi', 'Deuteronômio', 'dt', 13, 6, 'Se o seu próprio irmão ou filho ou filha, ou a mulher que você ama ou o seu amigo mais chegado secretamente instigá-lo, dizendo: "Vamos adorar outros deuses! " — deuses que nem você nem os seus antepassados conheceram,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5279, 'nvi', 'Deuteronômio', 'dt', 13, 7, 'deuses dos povos que vivem ao seu redor, quer próximos, quer distantes, de um ao outro lado da terra —');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5280, 'nvi', 'Deuteronômio', 'dt', 13, 8, 'não se deixe convencer nem ouça o que ele diz. Não tenha piedade nem compaixão dele e não o proteja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5281, 'nvi', 'Deuteronômio', 'dt', 13, 9, 'Você terá que matá-lo. Seja a sua mão a primeira a levantar-se para matá-lo, e depois as mãos de todo o povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5282, 'nvi', 'Deuteronômio', 'dt', 13, 10, 'Apedreje-o até à morte, porque tentou desviá-lo do Senhor, o seu Deus, que o tirou do Egito, da terra da escravidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5283, 'nvi', 'Deuteronômio', 'dt', 13, 11, 'Então todo o Israel saberá disso; todos temerão e ninguém tornará a cometer uma maldade dessas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5284, 'nvi', 'Deuteronômio', 'dt', 13, 12, 'Se vocês ouvirem dizer que numa das cidades que o Senhor, o seu Deus, lhes dá para nelas morarem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5285, 'nvi', 'Deuteronômio', 'dt', 13, 13, 'surgiram homens perversos e desviaram os seus habitantes, dizendo: "Vamos adorar outros deuses! ", deuses que vocês não conhecem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5286, 'nvi', 'Deuteronômio', 'dt', 13, 14, 'vocês deverão verificar e investigar. Se for verdade e ficar comprovado que se praticou esse ato detestável entre vocês,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5287, 'nvi', 'Deuteronômio', 'dt', 13, 15, 'matem ao fio da espada todos os que viverem naquela cidade. Destruam totalmente a cidade, matando tanto os seus habitantes quanto os seus animais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5288, 'nvi', 'Deuteronômio', 'dt', 13, 16, 'Ajuntem todos os despojos no meio da praça pública e queimem totalmente a cidade e todos os seus despojos, como oferta ao Senhor, ao seu Deus. Fique ela em ruínas para sempre, e nunca mais seja reconstruída.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5289, 'nvi', 'Deuteronômio', 'dt', 13, 17, 'Não seja encontrado em suas mãos nada do que foi destinado à destruição, para que o Senhor se afaste do fogo da sua ira; terá misericórdia e compaixão de vocês, e os fará multiplicar, conforme prometeu sob juramento aos seus antepassados,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5290, 'nvi', 'Deuteronômio', 'dt', 13, 18, 'somente se obedecerem ao Senhor, ao seu Deus, guardando todos os seus mandamentos, que lhes estou dando, e fazendo o que é justo aos seus olhos.');
