-- Inserções para Eclesiastes 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17383, 'nvi', 'Eclesiastes', 'ec', 4, 1, 'De novo voltei a minha atenção e vi toda a opressão que ocorre debaixo do sol: Vi as lágrimas dos oprimidos, mas não há quem os console; o poder estava do lado dos seus opressores, e não há quem os console.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17384, 'nvi', 'Eclesiastes', 'ec', 4, 2, 'Por isso considerei os mortos, mais felizes do que os vivos, pois estes ainda têm que viver!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17385, 'nvi', 'Eclesiastes', 'ec', 4, 3, 'No entanto, melhor do que ambos é aquele que ainda não nasceu, que não viu o mal que se faz debaixo do sol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17386, 'nvi', 'Eclesiastes', 'ec', 4, 4, 'Descobri que todo trabalho e toda realização surgem da competição que existe entre as pessoas. Mas isso também é absurdo, é correr atrás do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17387, 'nvi', 'Eclesiastes', 'ec', 4, 5, 'O tolo cruza os braços e destrói a própria vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17388, 'nvi', 'Eclesiastes', 'ec', 4, 6, 'Melhor é ter um punhado com tranqüilidade do que dois punhados à custa de muito esforço e de correr atrás do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17389, 'nvi', 'Eclesiastes', 'ec', 4, 7, 'Descobri ainda outra situação absurda debaixo do sol:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17390, 'nvi', 'Eclesiastes', 'ec', 4, 8, 'Havia um homem totalmente solitário; não tinha filho nem irmão. Trabalhava sem parar! Contudo, os seus olhos não se satisfaziam com a sua riqueza. Ele sequer perguntava: "Para quem estou trabalhando tanto, e por que razão deixo de me divertir? " Isso também é absurdo. É um trabalho muito ingrato!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17391, 'nvi', 'Eclesiastes', 'ec', 4, 9, 'É melhor ter companhia do que estar sozinho, porque maior é a recompensa do trabalho de duas pessoas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17392, 'nvi', 'Eclesiastes', 'ec', 4, 10, 'Se um cair, o amigo pode ajudá-lo a levantar-se. Mas pobre do homem que cai e não tem quem o ajude a levantar-se!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17393, 'nvi', 'Eclesiastes', 'ec', 4, 11, 'E se dois dormirem juntos, vão manter-se aquecidos. Como, porém, manter-se aquecido sozinho?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17394, 'nvi', 'Eclesiastes', 'ec', 4, 12, 'Um homem sozinho pode ser vencido, mas dois conseguem defender-se. Um cordão de três dobras não se rompe com facilidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17395, 'nvi', 'Eclesiastes', 'ec', 4, 13, 'Melhor é um jovem pobre e sábio, do que um rei idoso e tolo, que não mais aceita repreensão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17396, 'nvi', 'Eclesiastes', 'ec', 4, 14, 'O jovem pode ter saído da prisão e chegado ao trono, ou pode ter nascido pobre no país daquele rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17397, 'nvi', 'Eclesiastes', 'ec', 4, 15, 'Percebi que, ainda assim, o povo que vivia debaixo do sol seguia o jovem, o sucessor do rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17398, 'nvi', 'Eclesiastes', 'ec', 4, 16, 'O número dos que aderiram a ele era incontável. A geração seguinte, porém, não ficou satisfeita com o sucessor. Isso também não faz sentido, é correr atrás do vento.');
