-- Inserções para Eclesiastes 11
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17515, 'nvi', 'Eclesiastes', 'ec', 11, 1, 'Atire o seu pão sobre as águas, e depois de muitos dias você tornará a encontrá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17516, 'nvi', 'Eclesiastes', 'ec', 11, 2, 'Reparta o que você tem com sete, até mesmo com oito, pois você não sabe que desgraça poderá cair sobre a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17517, 'nvi', 'Eclesiastes', 'ec', 11, 3, 'Quando as nuvens estão cheias de água, derramam chuva sobre a terra. Quer uma árvore caia para o sul quer para o norte, no lugar em que cair ficará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17518, 'nvi', 'Eclesiastes', 'ec', 11, 4, 'Quem observa o vento não plantará; e quem olha para as nuvens não colherá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17519, 'nvi', 'Eclesiastes', 'ec', 11, 5, 'Assim como você não conhece o caminho do vento, nem como o corpo é formado no ventre de uma mulher, também não pode compreender as obras de Deus, o Criador de todas as coisas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17520, 'nvi', 'Eclesiastes', 'ec', 11, 6, 'Plante de manhã a sua semente, e mesmo ao entardecer não deixe as suas mãos ficarem à toa, pois você não sabe o que acontecerá, se esta ou aquela produzirá, ou se as duas serão igualmente boas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17521, 'nvi', 'Eclesiastes', 'ec', 11, 7, 'A luz é agradável, é bom ver o sol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17522, 'nvi', 'Eclesiastes', 'ec', 11, 8, 'Por mais que um homem viva, deve desfrutar sua vida toda. Lembre-se, porém, dos dias de trevas, pois serão muitos. Tudo o que está para vir não faz sentido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17523, 'nvi', 'Eclesiastes', 'ec', 11, 9, 'Alegre-se, jovem, na sua mocidade! Seja feliz o seu coração nos dias da sua juventude! Siga por onde seu coração mandar, até onde a sua vista alcançar; mas saiba que por todas essas coisas Deus o trará a julgamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17524, 'nvi', 'Eclesiastes', 'ec', 11, 10, 'Afaste do coração a ansiedade e acabe com o sofrimento do seu corpo, pois a juventude e o vigor são passageiros.');
