-- Inserções para Eclesiastes 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17460, 'nvi', 'Eclesiastes', 'ec', 8, 1, 'Quem é como o sábio? Quem sabe interpretar as coisas? A sabedoria de um homem Alcança o favor do rei e muda o seu semblante carregado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17461, 'nvi', 'Eclesiastes', 'ec', 8, 2, 'Este é o meu conselho: obedeça às ordens do rei porque você fez um juramento diante de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17462, 'nvi', 'Eclesiastes', 'ec', 8, 3, 'Não se apresse em deixar a presença do rei, nem se levante em favor de uma causa errada, pois o rei faz o que bem entende.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17463, 'nvi', 'Eclesiastes', 'ec', 8, 4, 'Pois a palavra do rei é soberana, e ninguém lhe pode perguntar: "Que é que estás fazendo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17464, 'nvi', 'Eclesiastes', 'ec', 8, 5, 'Quem obedece às suas ordens não sofrerá mal algum, pois o coração sábio saberá a hora e a maneira certa de agir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17465, 'nvi', 'Eclesiastes', 'ec', 8, 6, 'Pois há uma hora certa e também uma maneira certa de agir para cada situação. O sofrimento de um homem, no entanto, pesa muito sobre ele,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17466, 'nvi', 'Eclesiastes', 'ec', 8, 7, 'visto que ninguém conhece o futuro. Quem lhe poderá dizer o que vai acontecer?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17467, 'nvi', 'Eclesiastes', 'ec', 8, 8, 'Ninguém tem o poder de conter o próprio espírito; tampouco tem poder sobre o dia da sua morte, e de escapar dos efeitos da guerra; nem mesmo a maldade livra aqueles que a praticam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17468, 'nvi', 'Eclesiastes', 'ec', 8, 9, 'Tudo isso vi quando me pus a refletir em tudo o que se faz debaixo do sol. Há ocasiões em que um homem domina sobre outros para a sua própria infelicidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17469, 'nvi', 'Eclesiastes', 'ec', 8, 10, 'Nessas ocasiões, vi ímpios serem sepultados e gente indo e vindo do lugar onde eles foram enterrados. Todavia, os que haviam praticado o bem foram esquecidos na cidade. Isso também não faz sentido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17470, 'nvi', 'Eclesiastes', 'ec', 8, 11, 'Quando os crimes não são castigados logo, o coração do homem se enche de planos para fazer o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17471, 'nvi', 'Eclesiastes', 'ec', 8, 12, 'O ímpio pode cometer uma centena de crimes e até ter vida longa, mas sei muito bem que as coisas serão melhores para os que temem a Deus, para os que mostram respeito diante dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17472, 'nvi', 'Eclesiastes', 'ec', 8, 13, 'Para os ímpios, no entanto, nada irá bem, porque não temem a Deus, e os seus dias, como sombras, serão poucos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17473, 'nvi', 'Eclesiastes', 'ec', 8, 14, 'Há mais uma coisa sem sentido na terra: justos que recebem o que os ímpios merecem, e ímpios que recebem o que os justos merecem. Isto também, penso eu, não faz sentido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17474, 'nvi', 'Eclesiastes', 'ec', 8, 15, 'Por isso recomendo que se desfrute a vida, porque debaixo do sol não há nada melhor para o homem do que comer, beber e alegrar-se. Sejam esses os seus companheiros no seu duro trabalho durante todos os dias da vida que Deus lhe der debaixo do sol!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17475, 'nvi', 'Eclesiastes', 'ec', 8, 16, 'Quando voltei a mente para conhecer a sabedoria e observar as atividades do homem sobre a terra, daquele cujos olhos não vêem sono nem de dia nem de noite,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17476, 'nvi', 'Eclesiastes', 'ec', 8, 17, 'então percebi tudo o que Deus tem feito. Ninguém é capaz de entender o que se faz debaixo do sol. Por mais que se esforce para descobrir o sentido das coisas, o homem não o encontrará. O sábio pode até afirmar que entende, mas, na realidade não o consegue encontrar.');
