-- Inserções para Eclesiastes 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17317, 'nvi', 'Eclesiastes', 'ec', 1, 1, 'As palavras do Mestre, filho de Davi, rei em Jerusalém:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17318, 'nvi', 'Eclesiastes', 'ec', 1, 2, '"Que grande inutilidade! ", diz o Mestre. "Que grande inutilidade! Nada faz sentido! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17319, 'nvi', 'Eclesiastes', 'ec', 1, 3, 'O que o homem ganha com todo o seu trabalho em que tanto se esforça debaixo do sol?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17320, 'nvi', 'Eclesiastes', 'ec', 1, 4, 'Gerações vêm e gerações vão, mas a terra permanece para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17321, 'nvi', 'Eclesiastes', 'ec', 1, 5, 'O sol se levanta e o sol se põe, e depressa volta ao lugar de onde se levanta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17322, 'nvi', 'Eclesiastes', 'ec', 1, 6, 'O vento sopra para o sul e vira para o norte; dá voltas e mais voltas, seguindo sempre o seu curso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17323, 'nvi', 'Eclesiastes', 'ec', 1, 7, 'Todos os rios vão para o mar, contudo o mar nunca se enche; ainda que sempre corram para lá, para lá voltam a correr.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17324, 'nvi', 'Eclesiastes', 'ec', 1, 8, 'Todas as coisas trazem canseira. O homem não é capaz de descrevê-las; os olhos nunca se saciam de ver, nem os ouvidos de ouvir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17325, 'nvi', 'Eclesiastes', 'ec', 1, 9, 'O que foi tornará a ser, o que foi feito se fará novamente; não há nada novo debaixo do sol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17326, 'nvi', 'Eclesiastes', 'ec', 1, 10, 'Haverá algo de que se possa dizer: "Veja! Isto é novo! "? Não! Já existiu há muito tempo; bem antes da nossa época.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17327, 'nvi', 'Eclesiastes', 'ec', 1, 11, 'Ninguém se lembra dos que viveram na antigüidade, e aqueles que ainda virão tampouco serão lembrados pelos que vierem depois deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17328, 'nvi', 'Eclesiastes', 'ec', 1, 12, 'Eu, o mestre, fui rei de Israel em Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17329, 'nvi', 'Eclesiastes', 'ec', 1, 13, 'Dediquei-me a investigar e a usar a sabedoria para explorar tudo que é feito debaixo do céu. Que fardo pesado Deus pôs sobre os homens!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17330, 'nvi', 'Eclesiastes', 'ec', 1, 14, 'Tenho visto tudo o que é feito debaixo do sol; tudo é inútil, é correr atrás do vento!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17331, 'nvi', 'Eclesiastes', 'ec', 1, 15, 'O que é torto não pode ser endireitado; o que está faltando não pode ser contado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17332, 'nvi', 'Eclesiastes', 'ec', 1, 16, 'Pensei comigo mesmo: Eu me tornei famoso e ultrapassei em sabedoria todos os que governaram Jerusalém antes de mim; de fato adquiri muita sabedoria e conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17333, 'nvi', 'Eclesiastes', 'ec', 1, 17, 'Assim eu me esforcei para compreender a sabedoria, bem como a loucura e a insensatez, mas aprendi que isso também é correr atrás do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17334, 'nvi', 'Eclesiastes', 'ec', 1, 18, 'Pois quanto maior a sabedoria maior o sofrimento; e quanto maior o conhecimento, maior o desgosto.');
