-- Inserções para Eclesiastes 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17419, 'nvi', 'Eclesiastes', 'ec', 6, 1, 'Vi ainda outro mal debaixo do sol, que pesa bastante sobre a humanidade:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17420, 'nvi', 'Eclesiastes', 'ec', 6, 2, 'Deus dá riquezas, bens e honra ao homem, de modo que não lhe falta nada que os seus olhos desejam; mas Deus não lhe permite desfrutar tais coisas, e outro as desfruta em seu lugar. Isso não faz sentido; é um mal terrível.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17421, 'nvi', 'Eclesiastes', 'ec', 6, 3, 'Um homem pode ter cem filhos e viver muitos anos. No entanto, se não desfrutar as coisas boas da vida, digo que uma criança que nasce morta e nem recebe um enterro digno, tem melhor sorte do que ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17422, 'nvi', 'Eclesiastes', 'ec', 6, 4, 'Ela nasce em vão, e parte em trevas, e nas trevas o seu nome fica escondido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17423, 'nvi', 'Eclesiastes', 'ec', 6, 5, 'Embora jamais tenha visto o sol ou conhecido qualquer coisa, ela tem mais descanso do que tal homem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17424, 'nvi', 'Eclesiastes', 'ec', 6, 6, 'Pois, de que lhe valeria viver dois mil anos, e não poder desfrutar a sua prosperidade? Afinal, não vão todos para o mesmo lugar?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17425, 'nvi', 'Eclesiastes', 'ec', 6, 7, 'Todo o esforço do homem é feito para a sua boca, contudo, o seu apetite jamais se satisfaz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17426, 'nvi', 'Eclesiastes', 'ec', 6, 8, 'Que vantagem tem o sábio em relação ao tolo? Que vantagem tem o pobre em saber como se portar diante dos outros?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17427, 'nvi', 'Eclesiastes', 'ec', 6, 9, 'Melhor é contentar-se com o que os olhos vêem do que vaguear o apetite. Isso também não faz sentido, é correr atrás do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17428, 'nvi', 'Eclesiastes', 'ec', 6, 10, 'Tudo o que existe já recebeu um nome, e já se sabe o que o homem é; não se pode lutar contra alguém mais forte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17429, 'nvi', 'Eclesiastes', 'ec', 6, 11, 'Quanto mais palavras, mais tolices, e sem nenhum proveito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17430, 'nvi', 'Eclesiastes', 'ec', 6, 12, 'Pois, quem sabe o que é bom para o homem, nos poucos dias de sua vida vazia, em que ele passa como uma sombra? Quem poderá lhe contar o que acontecerá debaixo do sol depois que ele partir?');
