-- Inserções para Eclesiastes 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17525, 'nvi', 'Eclesiastes', 'ec', 12, 1, 'Lembre-se do seu Criador nos dias da sua juventude, antes que venham os dias difíceis e antes que se aproximem os anos em que você dirá: "Não tenho satisfação neles";');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17526, 'nvi', 'Eclesiastes', 'ec', 12, 2, 'antes que se escureçam o sol e a luz, a lua e as estrelas, e as nuvens voltem depois da chuva;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17527, 'nvi', 'Eclesiastes', 'ec', 12, 3, 'quando os guardas da casa tremerem e os homens fortes caminharem encurvados, e pararem os moedores por serem poucos, e aqueles que olham pelas janelas enxergarem embaçado;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17528, 'nvi', 'Eclesiastes', 'ec', 12, 4, 'quando as portas da rua forem fechadas e diminuir o som da moagem; quando o barulho das aves o fizer despertar, mas o som de todas as canções lhe parecer fraco;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17529, 'nvi', 'Eclesiastes', 'ec', 12, 5, 'quando você tiver medo de altura, e dos perigos das ruas; quando florir a amendoeira, o gafanhoto for um peso e o desejo já não se despertar. Então o homem se vai para o seu lar eterno, e os pranteadores já vagueiam pelas ruas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17530, 'nvi', 'Eclesiastes', 'ec', 12, 6, 'Sim, lembre-se dele, antes que se rompa o cordão de prata, ou se quebre a taça de ouro; antes que o cântaro se despedace junto à fonte, a roda se quebre junto ao poço,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17531, 'nvi', 'Eclesiastes', 'ec', 12, 7, 'o pó volte à terra, de onde veio, e o espírito volte a Deus, que o deu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17532, 'nvi', 'Eclesiastes', 'ec', 12, 8, '"Tudo sem sentido! Sem sentido! ", diz o mestre. "Nada faz sentido! Nada faz sentido! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17533, 'nvi', 'Eclesiastes', 'ec', 12, 9, 'Além de ser sábio, o mestre também ensinou conhecimento ao povo. Ele escutou, examinou e colecionou muitos provérbios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17534, 'nvi', 'Eclesiastes', 'ec', 12, 10, 'Procurou também encontrar as palavras certas, e o que ele escreveu era reto e verdadeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17535, 'nvi', 'Eclesiastes', 'ec', 12, 11, 'As palavras dos sábios são como aguilhões, a coleção dos seus ditos como pregos bem fixados, provenientes do único Pastor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17536, 'nvi', 'Eclesiastes', 'ec', 12, 12, 'Cuidado, meu filho; nada acrescente a eles. Não há limite para a produção de livros, e estudar demais deixa exausto o corpo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17537, 'nvi', 'Eclesiastes', 'ec', 12, 13, 'Agora que já se ouviu tudo, aqui está a conclusão: Tema a Deus e guarde os seus mandamentos, pois isso é o essencial para o homem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17538, 'nvi', 'Eclesiastes', 'ec', 12, 14, 'Pois Deus trará a julgamento tudo o que foi feito, inclusive tudo o que está escondido, seja bom, seja mal.');
