-- Inserções para Esdras 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12029, 'nvi', 'Esdras', 'ed', 2, 1, 'Esta é a lista dos homens da província que Nabucodonosor, rei da Babilônia, tinha levado prisioneiros para a Babilônia. Eles voltaram para Jerusalém e Judá, cada um para a sua própria cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12030, 'nvi', 'Esdras', 'ed', 2, 2, 'Vieram na companhia de Zorobabel, Jesua, Neemias, Seraías, Reelaías, Mardoqueu, Bilsã, Mispar, Bigvai, Reum e Baaná. Esta é a lista dos israelitas:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12031, 'nvi', 'Esdras', 'ed', 2, 3, 'os descendentes de Parós 2. 172');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12032, 'nvi', 'Esdras', 'ed', 2, 4, 'de Sefatias 372');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12033, 'nvi', 'Esdras', 'ed', 2, 5, 'de Ara 775');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12034, 'nvi', 'Esdras', 'ed', 2, 6, 'de Paate-Moabe, por meio da linhagem de Jesua e Joabe, 2. 812');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12035, 'nvi', 'Esdras', 'ed', 2, 7, 'de Elão 1. 254');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12036, 'nvi', 'Esdras', 'ed', 2, 8, 'de Zatu 945');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12037, 'nvi', 'Esdras', 'ed', 2, 9, 'de Zacai 760');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12038, 'nvi', 'Esdras', 'ed', 2, 10, 'de Bani 642');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12039, 'nvi', 'Esdras', 'ed', 2, 11, 'de Bebai 623');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12040, 'nvi', 'Esdras', 'ed', 2, 12, 'de Azgade 1. 222');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12041, 'nvi', 'Esdras', 'ed', 2, 13, 'de Adonicão 666');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12042, 'nvi', 'Esdras', 'ed', 2, 14, 'de Bigvai 2. 056');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12043, 'nvi', 'Esdras', 'ed', 2, 15, 'de Adim 454');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12044, 'nvi', 'Esdras', 'ed', 2, 16, 'de Ater, por meio de Ezequias, 98');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12045, 'nvi', 'Esdras', 'ed', 2, 17, 'de Besai 323');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12046, 'nvi', 'Esdras', 'ed', 2, 18, 'de Jora 112');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12047, 'nvi', 'Esdras', 'ed', 2, 19, 'de Hasum 223');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12048, 'nvi', 'Esdras', 'ed', 2, 20, 'de Gibar 95');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12049, 'nvi', 'Esdras', 'ed', 2, 21, 'os da cidade de Belém 123');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12050, 'nvi', 'Esdras', 'ed', 2, 22, 'de Netofate 56');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12051, 'nvi', 'Esdras', 'ed', 2, 23, 'de Anatote 128');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12052, 'nvi', 'Esdras', 'ed', 2, 24, 'de Azmavete 42');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12053, 'nvi', 'Esdras', 'ed', 2, 25, 'de Quiriate-Jearim, Quefira e Beerote 743');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12054, 'nvi', 'Esdras', 'ed', 2, 26, 'de Ramá e Geba 621');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12055, 'nvi', 'Esdras', 'ed', 2, 27, 'de Micmás 122');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12056, 'nvi', 'Esdras', 'ed', 2, 28, 'de Betel e Ai 223');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12057, 'nvi', 'Esdras', 'ed', 2, 29, 'de Nebo 52');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12058, 'nvi', 'Esdras', 'ed', 2, 30, 'de Magbis 156');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12059, 'nvi', 'Esdras', 'ed', 2, 31, 'da outra Elão 1. 254');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12060, 'nvi', 'Esdras', 'ed', 2, 32, 'de Harim 320');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12061, 'nvi', 'Esdras', 'ed', 2, 33, 'de Lode, Hadide e Ono 725');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12062, 'nvi', 'Esdras', 'ed', 2, 34, 'de Jericó 345');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12063, 'nvi', 'Esdras', 'ed', 2, 35, 'de Senaá 3. 630');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12064, 'nvi', 'Esdras', 'ed', 2, 36, 'Os sacerdotes: os descendentes de Jedaías, por meio da família de Jesua 973');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12065, 'nvi', 'Esdras', 'ed', 2, 37, 'de Imer 1. 052');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12066, 'nvi', 'Esdras', 'ed', 2, 38, 'de Pasur 1. 247');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12067, 'nvi', 'Esdras', 'ed', 2, 39, 'de Harim 1. 017');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12068, 'nvi', 'Esdras', 'ed', 2, 40, 'Os levitas: os descendentes de Jesua e de Cadmiel, por meio da linhagem de Hodavias 74');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12069, 'nvi', 'Esdras', 'ed', 2, 41, 'Os cantores: os descendentes de Asafe 128');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12070, 'nvi', 'Esdras', 'ed', 2, 42, 'Os porteiros do templo: os descendentes de Salum, Ater, Talmom, Acube, Hatita e Sobai 139');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12071, 'nvi', 'Esdras', 'ed', 2, 43, 'Os servidores do templo: os descendentes de Zia, Hasufa, Tabaote,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12072, 'nvi', 'Esdras', 'ed', 2, 44, 'Queros, Sia, Padom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12073, 'nvi', 'Esdras', 'ed', 2, 45, 'Lebana, Hagaba, Acube,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12074, 'nvi', 'Esdras', 'ed', 2, 46, 'Hagabe, Sanlai, Hanã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12075, 'nvi', 'Esdras', 'ed', 2, 47, 'Gidel, Gaar, Reaías,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12076, 'nvi', 'Esdras', 'ed', 2, 48, 'Rezim, Necoda, Gazão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12077, 'nvi', 'Esdras', 'ed', 2, 49, 'Uzá, Paséia, Besai,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12078, 'nvi', 'Esdras', 'ed', 2, 50, 'Asná, Meunim, Nefusim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12079, 'nvi', 'Esdras', 'ed', 2, 51, 'Bacbuque, Hacufa, Harur,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12080, 'nvi', 'Esdras', 'ed', 2, 52, 'Baslute, Meída, Harsa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12081, 'nvi', 'Esdras', 'ed', 2, 53, 'Barcos, Sísera, Tamá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12082, 'nvi', 'Esdras', 'ed', 2, 54, 'Nesias e Hatifa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12083, 'nvi', 'Esdras', 'ed', 2, 55, 'Os descendentes dos servos de Salomão: os descendentes de Sotai, Soferete, Peruda,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12084, 'nvi', 'Esdras', 'ed', 2, 56, 'Jaala, Darcom, Gidel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12085, 'nvi', 'Esdras', 'ed', 2, 57, 'Sefatias, Hatil, Poquerete-Hazebaim e Ami.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12086, 'nvi', 'Esdras', 'ed', 2, 58, 'O total dos servidores do templo e dos descendentes dos servos de Salomão 392');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12087, 'nvi', 'Esdras', 'ed', 2, 59, 'Os que chegaram das cidades de Tel-Melá, Tel-Harsa, Querube, Adã e Imer, mas não puderam comprovar que suas famílias descendiam de Israel, foram os seguintes:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12088, 'nvi', 'Esdras', 'ed', 2, 60, 'Os descendentes de Delaías, Tobias e Necoda 652');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12089, 'nvi', 'Esdras', 'ed', 2, 61, 'E dentre os sacerdotes: Os descendentes de Habaías, Coz e Barzilai, homem que se casou com uma filha de Barzilai, de Gileade, e que era chamado pelo nome do sogro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12090, 'nvi', 'Esdras', 'ed', 2, 62, 'Eles procuraram pelos seus registros de família, mas não conseguiram achá-los e foram considerados impuros para o sacerdócio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12091, 'nvi', 'Esdras', 'ed', 2, 63, 'Por isso o governador os proibiu de comer alimentos sagrados enquanto não houvesse um sacerdote capaz de consultar a Deus por meio do Urim e do Tumim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12092, 'nvi', 'Esdras', 'ed', 2, 64, 'A totalidade dos que voltaram do exílio atingiu o número de 42. 360 homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12093, 'nvi', 'Esdras', 'ed', 2, 65, 'além dos seus 7. 337 servos e servas; havia entre eles 200 cantores e cantoras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12094, 'nvi', 'Esdras', 'ed', 2, 66, 'Possuíam 736 cavalos, 245 mulas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12095, 'nvi', 'Esdras', 'ed', 2, 67, '435 camelos e 6. 720 jumentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12096, 'nvi', 'Esdras', 'ed', 2, 68, 'Quando chegaram ao templo do Senhor em Jerusalém, alguns dos chefes das famílias deram ofertas voluntárias para a reconstrução do templo de Deus no seu antigo local.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12097, 'nvi', 'Esdras', 'ed', 2, 69, 'De acordo com as suas possibilidades, deram à tesouraria para essa obra quinhentos quilos de ouro, três toneladas de prata e cem vestes sacerdotais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12098, 'nvi', 'Esdras', 'ed', 2, 70, 'Os sacerdotes, os levitas, os cantores, os porteiros e os servidores do templo, bem como os demais israelitas, estabeleceram-se em suas cidades de origem.');
