-- Inserções para Esdras 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12136, 'nvi', 'Esdras', 'ed', 5, 1, 'Ora, os profetas Ageu e Zacarias, descendente de Ido, profetizaram aos judeus de Judá e de Jerusalém, em nome do Deus de Israel, que estava sobre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12137, 'nvi', 'Esdras', 'ed', 5, 2, 'Então Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, começaram a reconstruir o templo de Deus em Jerusalém. E os profetas de Deus estavam com eles e os ajudavam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12138, 'nvi', 'Esdras', 'ed', 5, 3, 'Naquela época Tatenai, governador do território a oeste do Eufrates, Setar-Bozenai e seus companheiros foram perguntar a eles: "Quem os autorizou a reconstruir este templo e estes muros?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12139, 'nvi', 'Esdras', 'ed', 5, 4, 'E como se chamam os homens que estão construíndo este edifício? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12140, 'nvi', 'Esdras', 'ed', 5, 5, 'Mas os olhos do seu Deus estavam sobre os líderes dos judeus, e eles não foram impedidos de trabalhar até que um relatório fosse enviado a Dario e dele se recebesse uma ordem oficial a respeito do assunto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12141, 'nvi', 'Esdras', 'ed', 5, 6, 'Temos aqui uma cópia da carta que Tatenai, governador do território a oeste do Eufrates, Setar-Bozenai e seus companheiros, os funcionários do oeste do Eufrates, enviaram ao rei Dario.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12142, 'nvi', 'Esdras', 'ed', 5, 7, 'O relatório que lhe enviaram dizia o seguinte: "Ao rei Dario: Paz e prosperidade!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12143, 'nvi', 'Esdras', 'ed', 5, 8, 'Informamos ao rei que fomos à província de Judá, ao templo do grande Deus. O povo o está reconstruindo com grandes pedras e colocando vigas de madeira nas paredes. A obra está sendo executada com diligência e está tendo rápido progresso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12144, 'nvi', 'Esdras', 'ed', 5, 9, 'Então perguntamos aos líderes: Quem os autorizou a reconstruir este templo e estes muros?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12145, 'nvi', 'Esdras', 'ed', 5, 10, 'Também perguntamos os nomes dos líderes deles, para que registrássemos para a tua informação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12146, 'nvi', 'Esdras', 'ed', 5, 11, 'Esta é a resposta que nos deram: Somos servos do Deus dos céus e da terra, e estamos reconstruindo o templo construído há muitos anos, templo que foi construído e terminado por um grande rei de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12147, 'nvi', 'Esdras', 'ed', 5, 12, 'Mas, visto que os nossos antepassados irritaram o Deus dos céus, ele os entregou nas mãos do babilônio Nabucodonosor, rei da Babilônia, que destruiu este templo e deportou o povo para a Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12148, 'nvi', 'Esdras', 'ed', 5, 13, 'Contudo, no seu primeiro ano como rei de Babilônia, o rei Ciro emitiu um decreto ordenando a reconstrução desta casa de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12149, 'nvi', 'Esdras', 'ed', 5, 14, 'Ele até mesmo tirou do templo da Babilônia os utensílios de ouro e de prata da casa de Deus, os quais Nabucodonosor havia tirado do templo de Jerusalém e levara para o templo da Babilônia. O rei Ciro os confiou a um homem chamado Sesbazar, ao qual tinha nomeado governador,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12150, 'nvi', 'Esdras', 'ed', 5, 15, 'e lhe disse: ‘Leve estes utensílios e coloque-os no templo de Jerusalém, e reconstrua a casa de Deus em seu antigo local’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12151, 'nvi', 'Esdras', 'ed', 5, 16, 'Então Sesbazar veio e lançou os alicerces do templo de Deus em Jerusalém. Desde aquele dia ela tem estado em construção, mas ainda não foi concluída.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12152, 'nvi', 'Esdras', 'ed', 5, 17, 'Agora, se for do agrado do rei que se faça uma pesquisa nos arquivos reais da Babilônia para verificar se o rei Ciro de fato emitiu um decreto ordenando a reconstrução da casa de Deus de Jerusalém. E que o rei nos envie sua decisão sobre o assunto".');
