-- Inserções para Ester 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12749, 'nvi', 'Ester', 'et', 3, 1, 'Depois desses acontecimentos, o rei Xerxes honrou a Hamã, filho de Hamedata, descendente de Agague, promovendo-o e dando-lhe uma posição mais elevada do que a de todos os demais nobres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12750, 'nvi', 'Ester', 'et', 3, 2, 'Todos os oficiais do palácio real curvavam-se e prostravam-se diante de Hamã, conforme as ordens do rei. Mardoqueu, porém, não se curvava nem se prostrava diante dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12751, 'nvi', 'Ester', 'et', 3, 3, 'Então os oficiais do palácio real perguntaram a Mardoqueu: "Por que você desobedece à ordem do rei? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12752, 'nvi', 'Ester', 'et', 3, 4, 'Dia após dia eles lhe falavam, mas ele não lhes dava atenção e dizia que era judeu. Então contaram tudo a Hamã para ver se o comportamento de Mardoqueu seria tolerado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12753, 'nvi', 'Ester', 'et', 3, 5, 'Quando Hamã viu que Mardoqueu não se curvava nem se prostrava, ficou muito irado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12754, 'nvi', 'Ester', 'et', 3, 6, 'Contudo, sabendo quem era o povo de Mardoqueu, achou que não bastava matá-lo. Em vez disso, Hamã procurou uma forma de exterminar todos os judeus, o povo de Mardoqueu, em todo o império de Xerxes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12755, 'nvi', 'Ester', 'et', 3, 7, 'No primeiro mês do décimo segundo ano do reinado do rei Xerxes, no mês de nisã, lançaram o pur, isto é a sorte, na presença de Hamã para escolher um dia e um mês para executar o plano, e foi sorteado o décimo segundo mês, o mês de adar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12756, 'nvi', 'Ester', 'et', 3, 8, 'Então Hamã disse ao rei Xerxes: "Existe certo povo disperso e espalhado entre os povos de todas as províncias de teu império, cujos costumes são diferentes dos de todos os outros povos e que não obedecem às leis do rei; não convém ao rei tolerá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12757, 'nvi', 'Ester', 'et', 3, 9, 'Se for do agrado do rei, que se decrete a destruição deles; e colocarei trezentas e cinqüenta toneladas de prata na tesouraria real à disposição para que se execute esse trabalho".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12758, 'nvi', 'Ester', 'et', 3, 10, 'Então o rei tirou seu anel-selo do dedo, deu-o a Hamã, o inimigo dos judeus, filho de Hamedata, descendente de Agague, e lhe disse:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12759, 'nvi', 'Ester', 'et', 3, 11, '"Fique com a prata e faça com o povo o que você achar melhor".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12760, 'nvi', 'Ester', 'et', 3, 12, 'Assim, no décimo terceiro dia do primeiro mês os secretários do rei foram convocados. Hamã ordenou que escrevessem cartas na língua e na escrita de cada povo aos sátrapas do rei, aos governadores das várias províncias e aos chefes de cada povo. Tudo foi escrito em nome do rei Xerxes e selado com o seu anel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12761, 'nvi', 'Ester', 'et', 3, 13, 'As cartas foram enviadas por mensageiros a todas as províncias do império com a ordem de exterminar e aniquilar completamente todos os judeus, jovens e idosos, mulheres e crianças, num único dia, o décimo terceiro dia do décimo segundo mês, o mês de adar, e de saquear os seus bens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12762, 'nvi', 'Ester', 'et', 3, 14, 'Uma cópia do decreto deveria ser publicada como lei em cada província e levada ao conhecimento do povo de cada nação, a fim de que estivessem prontos para aquele dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12763, 'nvi', 'Ester', 'et', 3, 15, 'Por ordem do rei, os mensageiros saíram às pressas, e o decreto foi publicado na cidadela de Susã. O rei e Hamã assentaram-se para beber, mas a cidade de Susã estava confusa.');
