-- Inserções para Ester 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12781, 'nvi', 'Ester', 'et', 5, 1, 'Três dias depois, Ester vestiu seus trajes de rainha e colocou-se no pátio interno do palácio, em frente ao salão do rei. O rei estava no trono, de frente para a entrada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12782, 'nvi', 'Ester', 'et', 5, 2, 'Quando viu a rainha Ester ali no pátio, teve misericórdia dela e estendeu-lhe o cetro de ouro que tinha na mão. Ester aproximou-se e tocou a ponta do cetro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12783, 'nvi', 'Ester', 'et', 5, 3, 'E o rei lhe perguntou: "Que há, rainha Ester? Qual é o seu pedido? Mesmo que seja a metade do reino, lhe será dado".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12784, 'nvi', 'Ester', 'et', 5, 4, 'Respondeu Ester: "Se for do agrado do rei, venha com Hamã a um banquete que lhe preparei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12785, 'nvi', 'Ester', 'et', 5, 5, 'Disse o rei: "Tragam Hamã imediatamente, para que ele atenda ao pedido de Ester". Então o rei e Hamã foram ao banquete que Ester havia preparado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12786, 'nvi', 'Ester', 'et', 5, 6, 'Enquanto bebiam vinho, o rei tornou a perguntar a Ester: "Qual é o seu pedido? Você será atendida. Qual o seu desejo? Mesmo que seja a metade do reino, lhe será concedido".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12787, 'nvi', 'Ester', 'et', 5, 7, 'E Ester respondeu: "Este é o meu pedido e o meu desejo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12788, 'nvi', 'Ester', 'et', 5, 8, 'Se o rei tem consideração por mim, e se lhe agrada atender e conceder o meu pedido, que o rei e Hamã venham amanhã ao banquete que lhes prepararei. Então responderei à pergunta do rei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12789, 'nvi', 'Ester', 'et', 5, 9, 'Naquele dia Hamã saiu alegre e contente. Mas, ficou furioso quando viu que Mardoqueu, que estava junto à porta do palácio real, não se levantou nem mostrou respeito em sua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12790, 'nvi', 'Ester', 'et', 5, 10, 'Hamã, porém, controlou-se e foi para casa. Reunindo seus amigos e Zeres, sua mulher,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12791, 'nvi', 'Ester', 'et', 5, 11, 'Hamã vangloriou-se de sua grande riqueza, de seus muitos filhos e de como o rei o havia honrado e promovido acima de todos os outros nobres e oficiais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12792, 'nvi', 'Ester', 'et', 5, 12, 'E acrescentou Hamã: "Além disso, sou o único que a rainha Ester convidou para acompanhar o rei ao banquete que ela lhe ofereceu. Ela me convidou para comparecer amanhã, junto com o rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12793, 'nvi', 'Ester', 'et', 5, 13, 'Mas tudo isso não me dará satisfação, enquanto eu vir aquele judeu Mardoqueu sentado junto à porta do palácio real".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12794, 'nvi', 'Ester', 'et', 5, 14, 'Então Zeres, sua mulher, e todos os seus amigos lhe sugeriram: "Mande fazer uma forca, de mais de vinte metros de altura, e logo pela manhã peça ao rei que Mardoqueu seja enforcado nela. Assim você poderá acompanhar o rei ao jantar e alegrar-se". A sugestão agradou Hamã, e ele mandou fazer a forca.');
