-- Inserções para Ester 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12764, 'nvi', 'Ester', 'et', 4, 1, 'Quando Mardoqueu soube de tudo o que tinha acontecido, rasgou as vestes, vestiu-se de pano de saco e cinza, e saiu pela cidade, chorando amargamente em alta voz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12765, 'nvi', 'Ester', 'et', 4, 2, 'Foi até a porta do palácio real, mas não entrou, porque ninguém vestido de pano de saco tinha permissão de entrar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12766, 'nvi', 'Ester', 'et', 4, 3, 'Em cada província onde chegou o decreto com a ordem do rei, houve grande pranto entre os judeus, com jejum, choro e lamento. Muitos se deitavam em pano de saco e em cinza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12767, 'nvi', 'Ester', 'et', 4, 4, 'Quando as criadas de Ester e os oficiais responsáveis pelo harém lhe contaram sobre Mardoqueu, ela ficou muito aflita e mandou-lhe roupas para que ele as vestisse e tirasse o pano de saco; mas ele não quis aceitá-las.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12768, 'nvi', 'Ester', 'et', 4, 5, 'Então Ester convocou Hatá, um dos oficiais do rei, nomeado para ajudá-la, e deu-lhe ordens para descobrir o que estava perturbando Mardoqueu e porque ele estava agindo assim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12769, 'nvi', 'Ester', 'et', 4, 6, 'Hatá foi a Mardoqueu na praça da cidade, em frente à porta do palácio real.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12770, 'nvi', 'Ester', 'et', 4, 7, 'Mardoqueu contou-lhe tudo o que lhe tinha acontecido e quanta prata Hamã tinha prometido depositar na tesouraria real para a destruição dos judeus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12771, 'nvi', 'Ester', 'et', 4, 8, 'Deu-lhe também uma cópia do decreto que falava do extermínio, que tinha sido anunciado em Susã, para que ele o mostrasse a Ester e insistisse com ela para que fosse à presença do rei implorar misericórdia e interceder em favor do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12772, 'nvi', 'Ester', 'et', 4, 9, 'Hatá retornou e relatou a Ester tudo o que Mardoqueu tinha dito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12773, 'nvi', 'Ester', 'et', 4, 10, 'Então ela o instruiu que dissesse o seguinte a Mardoqueu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12774, 'nvi', 'Ester', 'et', 4, 11, '"Todos os oficiais do rei e o povo das províncias do império sabem que existe somente uma lei para qualquer homem ou mulher que se aproxime do rei no pátio interno sem por ele ser chamado: será morto, a não ser que o rei estenda o cetro de ouro para a pessoa e lhe poupe a vida. E eu não sou chamada à presença do rei há mais de trinta dias".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12775, 'nvi', 'Ester', 'et', 4, 12, 'Quando Mardoqueu recebeu a resposta de Ester,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12776, 'nvi', 'Ester', 'et', 4, 13, 'mandou dizer-lhe: "Não pense que pelo fato de estar no palácio do rei, de todos os judeus só você escapará,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12777, 'nvi', 'Ester', 'et', 4, 14, 'pois, se você ficar calada nesta hora, socorro e livramento surgirão de outra parte para os judeus, mas você e a família de seu pai morrerão. Quem sabe se não foi para um momento como este que você chegou à posição de rainha? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12778, 'nvi', 'Ester', 'et', 4, 15, 'Então Ester mandou esta resposta a Mardoqueu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12779, 'nvi', 'Ester', 'et', 4, 16, '"Vá reunir todos os judeus que estão em Susã, e jejuem em meu favor. Não comam nem bebam durante três dias e três noites. Eu e minhas criadas jejuaremos como vocês. Depois disso irei ao rei, ainda que seja contra a lei. Se eu tiver que morrer, morrerei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12780, 'nvi', 'Ester', 'et', 4, 17, 'Mardoqueu retirou-se e cumpriu todas as instruções de Ester.');
