-- Inserções para Êxodo 31
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2421, 'nvi', 'Êxodo', 'ex', 31, 1, 'Disse então o Senhor a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2422, 'nvi', 'Êxodo', 'ex', 31, 2, '"Eu escolhi a Bezalel, filho de Uri, filho de Hur, da tribo de Judá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2423, 'nvi', 'Êxodo', 'ex', 31, 3, 'e o enchi do Espírito de Deus, dando-lhes destreza, habilidade e plena capacidade artística');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2424, 'nvi', 'Êxodo', 'ex', 31, 4, 'para desenhar e executar trabalhos em ouro, prata e bronze,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2425, 'nvi', 'Êxodo', 'ex', 31, 5, 'para talhar e esculpir pedras, para entalhar madeira e executar todo tipo de obra artesanal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2426, 'nvi', 'Êxodo', 'ex', 31, 6, 'Além disso, designei Aoliabe, filho de Aisamaque, da tribo de Dã, para auxiliá-lo. Também capacitei a todos os artesãos para que executem tudo o que lhe ordenei:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2427, 'nvi', 'Êxodo', 'ex', 31, 7, 'A Tenda do Encontro, a arca da aliança e a tampa que está sobre ela, e todos os outros utensílios da tenda —');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2428, 'nvi', 'Êxodo', 'ex', 31, 8, 'a mesa com os seus utensílios, o candelabro de ouro puro e os seus utensílios, o altar do incenso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2429, 'nvi', 'Êxodo', 'ex', 31, 9, 'o altar do holocausto com os seus utensílios, a bacia com a sua base —');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2430, 'nvi', 'Êxodo', 'ex', 31, 10, 'assim como as vestes litúrgicas, tanto as vestes sagradas para Arão, o sacerdote, como as vestes para os seus filhos, quando servirem como sacerdotes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2431, 'nvi', 'Êxodo', 'ex', 31, 11, 'bem como o óleo para as unções e o incenso aromático para o Lugar Santo. Tudo deve ser feito exatamente como eu lhe ordenei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2432, 'nvi', 'Êxodo', 'ex', 31, 12, 'Disse ainda o Senhor a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2433, 'nvi', 'Êxodo', 'ex', 31, 13, '"Diga aos israelitas que guardem os meus sábados. Isso será um sinal entre mim e vocês, geração após geração, a fim de que saibam que eu sou o Senhor, que os santifica.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2434, 'nvi', 'Êxodo', 'ex', 31, 14, '"Guardem o sábado, pois para vocês é santo. Aquele que o profanar terá que ser executado; quem fizer algum trabalho nesse dia será eliminado do meio do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2435, 'nvi', 'Êxodo', 'ex', 31, 15, 'Em seis dias qualquer trabalho poderá ser feito, mas o sétimo dia é o sábado, o dia de descanso, consagrado ao Senhor. Quem fizer algum trabalho no sábado terá que ser executado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2436, 'nvi', 'Êxodo', 'ex', 31, 16, 'Os israelitas terão que guardar o sábado, eles e os seus descendentes, como uma aliança perpétua.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2437, 'nvi', 'Êxodo', 'ex', 31, 17, 'Isso será um sinal perpétuo entre mim e os israelitas, pois em seis dias o Senhor fez os céus e a terra, e no sétimo dia ele não trabalhou e descansou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2438, 'nvi', 'Êxodo', 'ex', 31, 18, 'Quando o Senhor terminou de falar com Moisés no monte Sinai, deu-lhe as duas tábuas da aliança, tábuas de pedra, escritas pelo dedo de Deus.');
