-- Inserções para Êxodo 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1984, 'nvi', 'Êxodo', 'ex', 17, 1, 'Toda a comunidade de Israel partiu do deserto de Sim, andando de um lugar para outro, conforme a ordem do Senhor. Acamparam em Refidim, mas lá não havia água para beber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1985, 'nvi', 'Êxodo', 'ex', 17, 2, 'Por essa razão queixaram-se a Moisés e exigiram: "Dê-nos água para beber". Ele respondeu: "Por que se queixam a mim? Por que colocam o Senhor à prova? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1986, 'nvi', 'Êxodo', 'ex', 17, 3, 'Mas o povo estava sedento e reclamou a Moisés: "Por que você nos tirou do Egito? Foi para matar de sede a nós, aos nossos filhos e aos nossos rebanhos? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1987, 'nvi', 'Êxodo', 'ex', 17, 4, 'Então Moisés clamou ao Senhor: "Que farei com este povo? Estão a ponto de apedrejar-me! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1988, 'nvi', 'Êxodo', 'ex', 17, 5, 'Respondeu-lhe o Senhor: "Passe à frente do povo. Leve com você algumas das autoridades de Israel, tenha na mão a vara com a qual você feriu o Nilo e vá adiante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1989, 'nvi', 'Êxodo', 'ex', 17, 6, 'Eu estarei à sua espera no alto da rocha que está em Horebe. Bata na rocha, e dela sairá água para o povo beber". Assim fez Moisés, à vista das autoridades de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1990, 'nvi', 'Êxodo', 'ex', 17, 7, 'E chamou aquele lugar Massá e Meribá, porque ali os israelitas reclamaram e puseram o Senhor à prova, dizendo: "O Senhor está entre nós, ou não? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1991, 'nvi', 'Êxodo', 'ex', 17, 8, 'Sucedeu que os amalequitas vieram atacar os israelitas em Refidim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1992, 'nvi', 'Êxodo', 'ex', 17, 9, 'Então Moisés disse a Josué: "Escolha alguns dos nossos homens e lute contra os amalequitas. Amanhã tomarei posição no alto da colina, com a vara de Deus em minhas mãos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1993, 'nvi', 'Êxodo', 'ex', 17, 10, 'Josué foi então lutar contra os amalequitas, conforme Moisés tinha ordenado. Moisés, Arão e Hur, porém, subiram ao alto da colina.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1994, 'nvi', 'Êxodo', 'ex', 17, 11, 'Enquanto Moisés mantinha as mãos erguidas, os israelitas venciam; quando, porém, as abaixava, os amalequitas venciam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1995, 'nvi', 'Êxodo', 'ex', 17, 12, 'Quando as mãos de Moisés já estavam cansadas, eles pegaram uma pedra e a colocaram debaixo dele, para que nela se assentasse. Arão e Hur mantinham erguidas as mãos de Moisés, um de cada lado, de modo que as mãos permaneceram firmes até o pôr-do-sol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1996, 'nvi', 'Êxodo', 'ex', 17, 13, 'E Josué derrotou o exército amalequita ao fio da espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1997, 'nvi', 'Êxodo', 'ex', 17, 14, 'Depois o Senhor disse a Moisés: "Escreva isto num rolo, como memorial, e declare a Josué que farei que os amalequitas sejam esquecidos para sempre debaixo do céu".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1998, 'nvi', 'Êxodo', 'ex', 17, 15, 'Moisés construiu um altar e chamou-lhe "o Senhor é minha bandeira".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (1999, 'nvi', 'Êxodo', 'ex', 17, 16, 'E jurou: "Pelo trono do Senhor! O Senhor fará guerra contra os amalequitas de geração em geração".');
