-- Inserções para Êxodo 24
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2178, 'nvi', 'Êxodo', 'ex', 24, 1, 'Depois Deus disse a Moisés: "Subam o monte para encontrar-se com o Senhor, você e Arão, Nadabe e Abiú, e setenta autoridades de Israel. Adorem à distância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2179, 'nvi', 'Êxodo', 'ex', 24, 2, 'Somente Moisés se aproximará do Senhor; os outros não. O povo também não subirá com ele".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2180, 'nvi', 'Êxodo', 'ex', 24, 3, 'Quando Moisés se dirigiu ao povo e transmitiu-lhes todas as palavras e ordenanças do Senhor, eles responderam em uníssono: "Faremos tudo o que o Senhor ordenou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2181, 'nvi', 'Êxodo', 'ex', 24, 4, 'Moisés, então, escreveu tudo o que o Senhor dissera. Na manhã seguinte Moisés levantou-se, construiu um altar ao pé do monte e ergueu doze colunas de pedra, representando as doze tribos de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2182, 'nvi', 'Êxodo', 'ex', 24, 5, 'Em seguida enviou jovens israelitas, que ofereceram holocaustos e novilhos como sacrifícios de comunhão ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2183, 'nvi', 'Êxodo', 'ex', 24, 6, 'Moisés colocou metade do sangue em tigelas e a outra metade derramou sobre o altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2184, 'nvi', 'Êxodo', 'ex', 24, 7, 'Em seguida, leu o Livro da Aliança para o povo, e eles disseram: "Faremos fielmente tudo o que o Senhor ordenou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2185, 'nvi', 'Êxodo', 'ex', 24, 8, 'Depois Moisés aspergiu o sangue sobre o povo, dizendo: "Este é o sangue da aliança que o Senhor fez com vocês de acordo com todas essas palavras".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2186, 'nvi', 'Êxodo', 'ex', 24, 9, 'Moisés, Arão, Nadabe, Abiú e setenta autoridades de Israel subiram');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2187, 'nvi', 'Êxodo', 'ex', 24, 10, 'e viram o Deus de Israel, sob cujos pés havia algo semelhante a um pavimento de safira, como o céu em seu esplendor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2188, 'nvi', 'Êxodo', 'ex', 24, 11, 'Deus, porém, não estendeu a mão para punir esses líderes do povo de Israel; eles viram a Deus, e depois comeram e beberam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2189, 'nvi', 'Êxodo', 'ex', 24, 12, 'Disse o Senhor a Moisés: "Suba a mim, ao monte, e fique aqui; e lhe darei as tábuas de pedra com a lei e os mandamentos que escrevi para a instrução do povo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2190, 'nvi', 'Êxodo', 'ex', 24, 13, 'Moisés partiu com Josué, seu auxiliar, e subiu ao monte de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2191, 'nvi', 'Êxodo', 'ex', 24, 14, 'Disse ele às autoridades de Israel: "Esperem-nos aqui, até que retornemos. Arão e Hur ficarão com vocês; quem tiver alguma questão para resolver, poderá procurá-los".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2192, 'nvi', 'Êxodo', 'ex', 24, 15, 'Quando Moisés subiu, a nuvem cobriu o monte,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2193, 'nvi', 'Êxodo', 'ex', 24, 16, 'e a glória do Senhor permaneceu sobre o monte Sinai. Durante seis dias a nuvem cobriu o monte. No sétimo dia o Senhor chamou Moisés do interior da nuvem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2194, 'nvi', 'Êxodo', 'ex', 24, 17, 'Aos olhos dos israelitas a glória do Senhor parecia um fogo consumidor no topo do monte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2195, 'nvi', 'Êxodo', 'ex', 24, 18, 'Moisés entrou na nuvem e foi subindo o monte. E permaneceu no monte quarenta dias e quarenta noites.');
