-- Inserções para Ezequiel 15
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20756, 'nvi', 'Ezequiel', 'ez', 15, 1, 'A palavra do Senhor veio a mim. Disse ele:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20757, 'nvi', 'Ezequiel', 'ez', 15, 2, '"Filho do homem, em que a madeira da videira é melhor do que o galho de qualquer das árvores da floresta?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20758, 'nvi', 'Ezequiel', 'ez', 15, 3, 'Alguma vez a madeira dela é usada para fazer algo útil? Alguém faz suportes com ela para neles pendurar coisas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20759, 'nvi', 'Ezequiel', 'ez', 15, 4, 'E, depois de ser lançada no fogo como combustível e o fogo queimar as duas extremidades e carbonizar o meio, servirá para alguma coisa?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20760, 'nvi', 'Ezequiel', 'ez', 15, 5, 'Se não foi útil para coisa alguma enquanto estava inteira, muito menos o será quando o fogo a queimar e ela estiver carbonizada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20761, 'nvi', 'Ezequiel', 'ez', 15, 6, '"Por isso diz o Soberano Senhor: Assim como destinei a madeira da videira dentre as árvores da floresta para servir de lenha para o fogo, também tratarei os habitantes de Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20762, 'nvi', 'Ezequiel', 'ez', 15, 7, 'Voltarei contra eles o meu rosto. Do fogo saíram, mas o fogo os consumirá. E, quando eu voltar o meu rosto contra eles, vocês saberão que eu sou o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20763, 'nvi', 'Ezequiel', 'ez', 15, 8, 'Arrasarei a terra porque eles foram infiéis, palavra do Soberano Senhor".');
