-- Inserções para Ezequiel 25
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21085, 'nvi', 'Ezequiel', 'ez', 25, 1, 'Esta palavra do Senhor veio a mim:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21086, 'nvi', 'Ezequiel', 'ez', 25, 2, '"Filho do homem, vire o rosto contra os amonitas e profetize contra eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21087, 'nvi', 'Ezequiel', 'ez', 25, 3, 'Diga-lhes: ‘Ouçam a palavra do Soberano Senhor. Assim diz o Soberano Senhor: Visto que vocês exclamaram: "Ah! Ah! " quando o meu santuário foi profanado, quando a terra de Israel foi arrasada e quando a nação de Judá foi para o exílio,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21088, 'nvi', 'Ezequiel', 'ez', 25, 4, 'vou entregar vocês como propriedade do povo do oriente. Eles instalarão seus acampamentos e armarão suas tendas no meio de vocês; comerão suas frutas e beberão seu leite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21089, 'nvi', 'Ezequiel', 'ez', 25, 5, 'Farei de Rabá num cercado para camelos e Amom um local de descanso para ovelhas. Então vocês saberão que eu sou o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21090, 'nvi', 'Ezequiel', 'ez', 25, 6, 'Porque assim diz o Soberano Senhor: Visto que vocês bateram palmas e pularam de alegria com o coração cheio de maldade contra Israel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21091, 'nvi', 'Ezequiel', 'ez', 25, 7, 'por essa razão estenderei o meu braço contra vocês e os darei às nações como despojo. Eliminarei vocês do meio das nações e os exterminarei do meio dos povos. Eu os destruirei, e vocês saberão que eu sou o Senhor’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21092, 'nvi', 'Ezequiel', 'ez', 25, 8, '"Assim diz o Soberano Senhor: ‘Uma vez que Moabe e Seir disseram: "Vejam, a nação de Judá se tornou como todas as outras nações",');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21093, 'nvi', 'Ezequiel', 'ez', 25, 9, 'por essa razão abrirei o flanco de Moabe, começando por suas cidades fronteiriças, Bete-Jesimote, Baal-Meom e Quiriataim, que são a glória dessa terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21094, 'nvi', 'Ezequiel', 'ez', 25, 10, 'Darei Moabe junto com os amonitas como propriedade ao povo do oriente. Os amonitas não serão lembrados entre as nações,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21095, 'nvi', 'Ezequiel', 'ez', 25, 11, 'e a Moabe trarei castigo. Então eles saberão que eu sou o Senhor’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21096, 'nvi', 'Ezequiel', 'ez', 25, 12, '"Assim diz o Soberano Senhor: ‘Visto que Edom vingou-se da nação de Judá e com isso trouxe grande culpa sobre si,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21097, 'nvi', 'Ezequiel', 'ez', 25, 13, 'assim diz o Soberano Senhor: Estenderei o braço contra Edom e matarei os seus homens e os seus animais. Eu o arrasarei, e desde Temã até Dedã eles cairão pela espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21098, 'nvi', 'Ezequiel', 'ez', 25, 14, 'Eu me vingarei de Edom pelas mãos do meu povo Israel, e este lidará com Edom de acordo com a minha ira e a minha indignação; eles conhecerão a minha vingança, palavra do Soberano Senhor’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21099, 'nvi', 'Ezequiel', 'ez', 25, 15, '"Assim diz o Soberano Senhor: ‘Uma vez que a Filístia agiu por vingança e com maldade no coração, e com antiga hostilidade buscou destruir Judá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21100, 'nvi', 'Ezequiel', 'ez', 25, 16, 'assim diz o Soberano Senhor: estou a ponto de estender meu braço contra os filisteus. Eliminarei os queretitas e destruirei os que restarem no litoral.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21101, 'nvi', 'Ezequiel', 'ez', 25, 17, 'Executarei neles grande vingança e os castigarei na minha ira. Então, quando eu me vingar deles, saberão que eu sou o Senhor’ ".');
