-- Inserções para Ezequiel 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20494, 'nvi', 'Ezequiel', 'ez', 2, 1, 'Ele me disse: "Filho do homem, fique de pé, que eu vou falar com você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20495, 'nvi', 'Ezequiel', 'ez', 2, 2, 'Enquanto ele falava, o Espírito entrou em mim e me pôs de pé, e ouvi aquele que me falava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20496, 'nvi', 'Ezequiel', 'ez', 2, 3, 'Ele disse: "Filho do homem, vou enviá-lo aos israelitas, nação rebelde que se revoltou contra mim; até hoje eles e os seus antepassados têm se revoltado contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20497, 'nvi', 'Ezequiel', 'ez', 2, 4, 'O povo a quem vou enviá-lo é obstinado e rebelde. Diga-lhe: Assim diz o Senhor Soberano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20498, 'nvi', 'Ezequiel', 'ez', 2, 5, 'E, quer aquela nação rebelde ouça, quer deixe de ouvir, saberá que um profeta esteve no meio dela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20499, 'nvi', 'Ezequiel', 'ez', 2, 6, 'E você, filho do homem, não tenha medo dessa gente nem das suas palavras. Não tenha medo, ainda que o cerquem espinheiros, e você viva entre escorpiões. Não tenha medo do que disserem, nem fique apavorado ao vê-los, embora sejam uma nação rebelde.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20500, 'nvi', 'Ezequiel', 'ez', 2, 7, 'Você lhes falará as minhas palavras, quer ouçam quer deixem de ouvir, pois são rebeldes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20501, 'nvi', 'Ezequiel', 'ez', 2, 8, 'Mas você, filho do homem, ouça o que lhe digo. Não seja rebelde como aquela nação; abra a boca e coma o que lhe vou dar".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20502, 'nvi', 'Ezequiel', 'ez', 2, 9, 'Então olhei, e vi a mão de alguém estendida para mim. Nela estava o rolo de um livro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20503, 'nvi', 'Ezequiel', 'ez', 2, 10, 'que ele desenrolou diante de mim. Em ambos os lados dele estavam escritas palavras de lamento, pranto e ais.');
