-- Inserções para Ezequiel 35
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21346, 'nvi', 'Ezequiel', 'ez', 35, 1, 'Esta palavra do Senhor veio a mim:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21347, 'nvi', 'Ezequiel', 'ez', 35, 2, '"Filho do homem, vire o rosto contra o monte Seir; profetize contra ele');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21348, 'nvi', 'Ezequiel', 'ez', 35, 3, 'e diga: ‘Assim diz o Soberano Senhor: Estou contra você, monte Seir, e estenderei o meu braço contra você e farei de você um deserto arrasado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21349, 'nvi', 'Ezequiel', 'ez', 35, 4, 'Transformarei as suas cidades em ruínas, e você ficará arrasado. Então você saberá que eu sou o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21350, 'nvi', 'Ezequiel', 'ez', 35, 5, '" ‘Visto que você guardou uma velha hostilidade e entregou os israelitas à espada na hora da desgraça, na hora em que o castigo deles chegou,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21351, 'nvi', 'Ezequiel', 'ez', 35, 6, 'por isso, juro pela minha vida, palavra do Soberano Senhor, que entregarei você ao espírito sanguinário, e este o perseguirá. Uma vez que você não detestou o espírito sanguinário, o espírito sanguinário o perseguirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21352, 'nvi', 'Ezequiel', 'ez', 35, 7, 'Farei do monte Seir um deserto arrasado e dele eliminarei todo o que vem e todo o que vai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21353, 'nvi', 'Ezequiel', 'ez', 35, 8, 'Encherei seus montes de mortos; os mortos à espada cairão em suas colinas e em seus vales e em todas as suas ravinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21354, 'nvi', 'Ezequiel', 'ez', 35, 9, 'Arrasarei você para sempre; suas cidades ficarão inabitáveis. Então você saberá que eu sou o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21355, 'nvi', 'Ezequiel', 'ez', 35, 10, '" ‘Uma vez que você disse: "Estas duas nações e povos serão nossos e nos apossaremos deles", sendo que eu, o Senhor, estava ali,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21356, 'nvi', 'Ezequiel', 'ez', 35, 11, 'juro pela minha vida, palavra do Soberano Senhor, que tratarei você de acordo com a ira e o ciúme que você mostrou em seu ódio para com eles, e me farei conhecido entre eles quando eu julgar você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21357, 'nvi', 'Ezequiel', 'ez', 35, 12, 'Então você saberá que eu, o Senhor, ouvi todas as coisas desprezíveis que você disse contra os montes de Israel. Você disse: "Eles foram arrasados e nos foram entregues para que os devoremos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21358, 'nvi', 'Ezequiel', 'ez', 35, 13, 'Você encheu-se de orgulho contra mim e falou contra mim sem se conter, e eu o ouvi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21359, 'nvi', 'Ezequiel', 'ez', 35, 14, 'Pois assim diz o Soberano Senhor: Enquanto a terra toda se regozija, eu o arrasarei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (21360, 'nvi', 'Ezequiel', 'ez', 35, 15, 'Como você se regozijou quando a herança da nação de Israel foi arrasada, é assim que eu a tratarei. Você ficará arrasado, ó monte Seir, você e todo o Edom. Então eles saberão que eu sou o Senhor’ ".');
