-- Inserções para Ezequiel 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20565, 'nvi', 'Ezequiel', 'ez', 6, 1, 'Esta palavra do Senhor veio a mim:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20566, 'nvi', 'Ezequiel', 'ez', 6, 2, '"Filho do homem, vire o rosto contra os montes de Israel; profetize contra eles');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20567, 'nvi', 'Ezequiel', 'ez', 6, 3, 'e diga: ‘Ó montes de Israel, ouçam a palavra do Soberano Senhor. Assim diz o Soberano Senhor aos montes e às colinas, às ravinas e aos vales: Estou para trazer a espada contra vocês; vou destruir os seus altares idólatras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20568, 'nvi', 'Ezequiel', 'ez', 6, 4, 'Seus altares serão arrasados, seus altares de incenso serão esmigalhados, e abaterei o seu povo na frente dos seus ídolos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20569, 'nvi', 'Ezequiel', 'ez', 6, 5, 'Porei os cadáveres dos israelitas em frente de seus ídolos, e espalharei os seus ossos ao redor dos seus altares.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20570, 'nvi', 'Ezequiel', 'ez', 6, 6, 'Onde quer que você viva, as cidades serão devastadas e os altares idólatras serão arrasados e devastados, seus ídolos serão esmigalhados e transformados em ruínas, seus altares de incenso serão derrubados e tudo o que vocês realizaram será apagado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20571, 'nvi', 'Ezequiel', 'ez', 6, 7, 'Seu povo cairá morto no meio de vocês, e vocês saberão que eu sou o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20572, 'nvi', 'Ezequiel', 'ez', 6, 8, '" ‘Mas pouparei alguns; alguns de vocês escaparão da espada quando forem espalhados entre as terras e nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20573, 'nvi', 'Ezequiel', 'ez', 6, 9, 'Ali, nas nações para onde vocês tiverem sido levados cativos, aqueles que escaparem se lembrarão de mim; lembrarão de como fui entristecido por seus corações adúlteros, que se desviaram de mim, e, por seus olhos, que cobiçaram os seus ídolos. Terão nojo de si mesmos por causa do mal que fizeram e por causa de todas as suas práticas repugnantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20574, 'nvi', 'Ezequiel', 'ez', 6, 10, 'E saberão que eu sou o Senhor, que não ameacei em vão trazer esta desgraça sobre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20575, 'nvi', 'Ezequiel', 'ez', 6, 11, '" ‘Assim diz o Soberano Senhor: Esfregue as mãos, bata os pés e grite "Ai! ", por causa de todas as práticas ímpias e repugnantes da nação de Israel, pois eles morrerão pela espada, pela fome e pela peste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20576, 'nvi', 'Ezequiel', 'ez', 6, 12, 'Quem está longe morrerá da peste, quem está perto cairá pela espada, e quem sobreviver e for poupado morrerá de fome. Assim mandarei a minha ira sobre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20577, 'nvi', 'Ezequiel', 'ez', 6, 13, 'E saberão que eu sou o Senhor, quando o seu povo estiver estirado, morto entre os seus ídolos, ao redor de seus altares, em todo monte alto e em todo topo de montanha, debaixo de toda árvore frondosa e de todo carvalho viçoso — em todos os lugares nos quais eles ofereciam incenso aromático a todos os seus ídolos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20578, 'nvi', 'Ezequiel', 'ez', 6, 14, 'E estenderei meu braço contra eles e tornarei a terra uma imensidão desoladora, desde o deserto até Dibla — onde quer que estiverem vivendo. Então saberão que eu sou o Senhor’ ".');
