-- Inserções para Ezequiel 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20883, 'nvi', 'Ezequiel', 'ez', 19, 1, '"Levante um lamento pelos príncipes de Israel');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20884, 'nvi', 'Ezequiel', 'ez', 19, 2, 'e diga: " ‘Que leoa era a sua mãe entre os leões! Ela se deitava entre os leõezinhos e criava os seus filhotes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20885, 'nvi', 'Ezequiel', 'ez', 19, 3, 'Criou um dos seus filhotes, e ele se tornou um leão forte. Ele aprendeu a despedaçar a presa e devorou homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20886, 'nvi', 'Ezequiel', 'ez', 19, 4, 'As nações ouviram a seu respeito, e ele foi pego na cova delas. Elas o levaram com ganchos para o Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20887, 'nvi', 'Ezequiel', 'ez', 19, 5, '" ‘Quando ela viu que a sua esperança não se cumpria, quando viu que se havia ido a sua expectativa, escolheu outro de seus filhotes e fez dele um leão forte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20888, 'nvi', 'Ezequiel', 'ez', 19, 6, 'Ele vagueou entre os leões, pois agora era um leão forte. Ele aprendeu a despedaçar a presa e devorou homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20889, 'nvi', 'Ezequiel', 'ez', 19, 7, 'Arrebentou suas fortalezas e devastou suas cidades. A terra e todos que nela estavam ficaram aterrorizados com o seu rugido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20890, 'nvi', 'Ezequiel', 'ez', 19, 8, 'Então as nações vizinhas o atacaram. Estenderam sua rede para apanhá-lo, e ele foi pego na armadilha que fizeram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20891, 'nvi', 'Ezequiel', 'ez', 19, 9, 'Com ganchos elas o puxaram para dentro de uma jaula e o levaram ao rei da Babilônia. Elas o colocaram na prisão, de modo que não se ouviu mais o seu rugido nos montes de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20892, 'nvi', 'Ezequiel', 'ez', 19, 10, '" ‘Sua mãe era como uma vide em sua vinha plantada junto à água; era frutífera e cheia de ramos, graças às muitas águas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20893, 'nvi', 'Ezequiel', 'ez', 19, 11, 'Seus ramos eram fortes, próprios para o cetro de um governante. Ela cresceu e subiu muito, sobressaindo à folhagem espessa; chamava a atenção por sua altura e por seus muitos ramos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20894, 'nvi', 'Ezequiel', 'ez', 19, 12, 'Mas foi desarraigada com fúria e atirada ao chão. O vento oriental a fez murchar, seus frutos foram arrancados, seus fortes galhos secaram e o fogo os consumiu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20895, 'nvi', 'Ezequiel', 'ez', 19, 13, 'Agora está plantada no deserto, numa terra seca e sedenta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20896, 'nvi', 'Ezequiel', 'ez', 19, 14, 'O fogo espalhou-se de um dos seus ramos principais e consumiu toda a ramagem. Nela não resta nenhum ramo forte que seja próprio para o cetro de um governante’. Esse é um lamento e como lamento deverá ser empregado".');
