-- Inserções para Ezequiel 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20624, 'nvi', 'Ezequiel', 'ez', 9, 1, 'Então o ouvi clamar em alta voz: "Tragam aqui os guardas da cidade, cada um com uma arma na mão".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20625, 'nvi', 'Ezequiel', 'ez', 9, 2, 'E vi seis homens que vinham da porta superior, que está voltada para o norte, cada um com uma arma mortal na mão. Com eles estava um homem vestido de linho e que tinha um estojo de escrevente à cintura. Eles entraram e se puseram ao lado do altar de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20626, 'nvi', 'Ezequiel', 'ez', 9, 3, 'Então a glória do Deus de Israel subiu de cima do querubim, onde havia estado, e se moveu para a entrada do templo. E o Senhor chamou o homem vestido de linho e que tinha o estojo de escrevente à cintura');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20627, 'nvi', 'Ezequiel', 'ez', 9, 4, 'e lhe disse: "Percorra a cidade de Jerusalém e ponha um sinal na testa daqueles que suspiram e gemem por causa de todas as práticas repugnantes que são feitas nela".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20628, 'nvi', 'Ezequiel', 'ez', 9, 5, 'Enquanto eu escutava, ele disse aos outros: "Sigam-no por toda a cidade e matem, sem piedade ou compaixão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20629, 'nvi', 'Ezequiel', 'ez', 9, 6, 'velhos, rapazes e moças, mulheres e crianças. Mas não toquem em ninguém que tenha o sinal. Comecem no meu santuário". Então eles começaram com as autoridades que estavam em frente do templo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20630, 'nvi', 'Ezequiel', 'ez', 9, 7, 'E ele lhes disse: "Contaminem o templo e encham de mortos os pátios. Podem ir! " Eles saíram e começaram a matança em toda a cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20631, 'nvi', 'Ezequiel', 'ez', 9, 8, 'Enquanto isso eu fiquei sozinho. Então prostrei-me, rosto em terra, clamando: "Ah! Soberano Senhor! Vais destruir todo o remanescente de Israel lançando a tua ira sobre Jerusalém? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20632, 'nvi', 'Ezequiel', 'ez', 9, 9, 'Ele me respondeu: "A iniqüidade da nação de Israel e de Judá é enorme; a terra está cheia de sangue derramado e a cidade está cheia de injustiça. Eles dizem: ‘O Senhor abandonou o país; o Senhor não nos vê’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20633, 'nvi', 'Ezequiel', 'ez', 9, 10, 'Então eu, de minha parte, não olharei para eles com piedade nem os pouparei, mas farei cair sobre as suas cabeças o que eles têm feito".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20634, 'nvi', 'Ezequiel', 'ez', 9, 11, 'Então o homem de linho com o estojo de escrevente à cintura voltou com um relatório, e disse: "Fiz o que me ordenaste".');
