-- Inserções para Ezequiel 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20606, 'nvi', 'Ezequiel', 'ez', 8, 1, 'No quinto dia do sexto mês do sexto ano do exílio, eu e as autoridades de Judá estávamos sentados em minha casa quando a mão do Soberano Senhor veio ali sobre mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20607, 'nvi', 'Ezequiel', 'ez', 8, 2, 'Olhei e vi uma figura como a de um homem. Do que parecia ser a sua cintura para baixo, ele era como fogo, e dali para cima sua aparência era tão brilhante como metal reluzente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20608, 'nvi', 'Ezequiel', 'ez', 8, 3, 'Ele estendeu o que parecia um braço e pegou-me pelo cabelo. O Espírito levantou-me entre a terra e o céu e, em visões de Deus, ele me levou a Jerusalém, à entrada da porta do norte do pátio interno, onde estava colocado o ídolo que desperta o zelo de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20609, 'nvi', 'Ezequiel', 'ez', 8, 4, 'E ali, diante de mim, estava a glória do Deus de Israel, como na visão que eu havia tido na planície.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20610, 'nvi', 'Ezequiel', 'ez', 8, 5, 'Então ele me disse: "Filho do homem, olhe para o norte". Olhei e, no lado norte, à porta do altar, vi o ídolo que desperta o zelo de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20611, 'nvi', 'Ezequiel', 'ez', 8, 6, 'E ele me disse: "Filho do homem, vê você o que estão fazendo? As grandes práticas repugnantes da nação de Israel, coisas que me levarão para longe do meu santuário? Mas você verá práticas ainda piores que estas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20612, 'nvi', 'Ezequiel', 'ez', 8, 7, 'Então ele me levou para a entrada do pátio. Olhei e vi um buraco no muro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20613, 'nvi', 'Ezequiel', 'ez', 8, 8, 'Ele me disse: "Filho do homem, agora escave o muro". Escavei o muro e vi a abertura de uma porta ali.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20614, 'nvi', 'Ezequiel', 'ez', 8, 9, 'E ele me disse: "Entre e veja as coisas repugnantes e más que estão fazendo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20615, 'nvi', 'Ezequiel', 'ez', 8, 10, 'Eu entrei e olhei. Lá eu vi, desenhadas por todas as paredes, todo tipo de criaturas rastejantes e animais impuros e todos os ídolos da nação de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20616, 'nvi', 'Ezequiel', 'ez', 8, 11, 'Na frente deles estavam setenta autoridades da nação de Israel, e Jazanias, filho de Safã, estava no meio deles. Cada um tinha um incensário na mão, e se elevava uma nuvem aromática de incenso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20617, 'nvi', 'Ezequiel', 'ez', 8, 12, 'Ele me disse: "Filho do homem, você viu o que as autoridades da nação de Israel estão fazendo nas trevas, cada um no santuário de sua própria imagem esculpida? Eles dizem: ‘O Senhor não nos vê; o Senhor abandonou o país’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20618, 'nvi', 'Ezequiel', 'ez', 8, 13, 'E de novo disse: "Você os verá cometerem práticas ainda mais repugnantes".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20619, 'nvi', 'Ezequiel', 'ez', 8, 14, 'Então ele me levou para a entrada da porta norte da casa do Senhor. Lá eu vi mulheres sentadas, chorando por Tamuz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20620, 'nvi', 'Ezequiel', 'ez', 8, 15, 'Ele me disse: "Você vê isso, filho do homem? Você verá práticas ainda mais repugnantes do que essa".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20621, 'nvi', 'Ezequiel', 'ez', 8, 16, 'Ele então me levou para dentro do pátio interno da casa do Senhor, e ali, à entrada do templo, entre o pórtico e o altar, havia uns vinte e cinco homens. Com as costas para o templo do Senhor e os rostos voltados para o oriente, estavam se prostrando na direção do sol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20622, 'nvi', 'Ezequiel', 'ez', 8, 17, 'Ele me disse: "Você viu isso, filho do homem? Será algo corriqueiro para a nação de Judá essas práticas repugnantes? Deverão também encher a terra de violência e continuamente me provocar a ira? E veja! Eles estão pondo o ramo perto do nariz!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20623, 'nvi', 'Ezequiel', 'ez', 8, 18, 'Por isso com ira eu os tratarei; não olharei com piedade para eles nem os pouparei. Mesmo que gritem aos meus ouvidos, não os ouvirei".');
