-- Inserções para Gálatas 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29190, 'nvi', 'Gálatas', 'gl', 6, 1, 'Irmãos, se alguém for surpreendido em algum pecado, vocês, que são espirituais deverão restaurá-lo com mansidão. Cuide-se, porém, cada um para que também não seja tentado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29191, 'nvi', 'Gálatas', 'gl', 6, 2, 'Levem os fardos pesados uns dos outros e, assim, cumpram a lei de Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29192, 'nvi', 'Gálatas', 'gl', 6, 3, 'Se alguém se considera alguma coisa, não sendo nada, engana-se a si mesmo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29193, 'nvi', 'Gálatas', 'gl', 6, 4, 'Cada um examine os próprios atos, e então poderá orgulhar-se de si mesmo, sem se comparar com ninguém,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29194, 'nvi', 'Gálatas', 'gl', 6, 5, 'pois cada um deverá levar a própria carga.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29195, 'nvi', 'Gálatas', 'gl', 6, 6, 'O que está sendo instruído na palavra partilhe todas as coisas boas com quem o instrui.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29196, 'nvi', 'Gálatas', 'gl', 6, 7, 'Não se deixem enganar: de Deus não se zomba. Pois o que o homem semear, isso também colherá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29197, 'nvi', 'Gálatas', 'gl', 6, 8, 'Quem semeia para a sua carne, da carne colherá destruição; mas quem semeia para o Espírito, do Espírito colherá a vida eterna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29198, 'nvi', 'Gálatas', 'gl', 6, 9, 'E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29199, 'nvi', 'Gálatas', 'gl', 6, 10, 'Portanto, enquanto temos oportunidade, façamos o bem a todos, especialmente aos da família da fé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29200, 'nvi', 'Gálatas', 'gl', 6, 11, 'Vejam com que letras grandes estou lhes escrevendo de próprio punho!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29201, 'nvi', 'Gálatas', 'gl', 6, 12, 'Os que desejam causar boa impressão exteriormente, tentando obrigá-los a se circuncidarem, agem desse modo apenas para não serem perseguidos por causa da cruz de Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29202, 'nvi', 'Gálatas', 'gl', 6, 13, 'Nem mesmo os que são circuncidados cumprem a lei; querem, no entanto, que vocês sejam circuncidados a fim de se gloriarem no corpo de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29203, 'nvi', 'Gálatas', 'gl', 6, 14, 'Quanto a mim, que eu jamais me glorie, a não ser na cruz de nosso Senhor Jesus Cristo, por meio da qual o mundo foi crucificado para mim, e eu para o mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29204, 'nvi', 'Gálatas', 'gl', 6, 15, 'De nada vale ser circuncidado ou não. O que importa é ser uma nova criação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29205, 'nvi', 'Gálatas', 'gl', 6, 16, 'Paz e misericórdia estejam sobre todos os que andam conforme essa regra, e também sobre o Israel de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29206, 'nvi', 'Gálatas', 'gl', 6, 17, 'Sem mais, que ninguém me perturbe, pois trago em meu corpo as marcas de Jesus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29207, 'nvi', 'Gálatas', 'gl', 6, 18, 'Irmãos, que a graça de nosso Senhor Jesus Cristo seja com o espírito de vocês. Amém.');
