-- Inserções para Gênesis 10
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (235, 'nvi', 'Gênesis', 'gn', 10, 1, 'Este é o registro da descendência de Sem, Cam e Jafé, filhos de Noé. Os filhos deles nasceram depois do Dilúvio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (236, 'nvi', 'Gênesis', 'gn', 10, 2, 'Estes foram os filhos de Jafé: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tirás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (237, 'nvi', 'Gênesis', 'gn', 10, 3, 'Estes foram os filhos de Gômer: Asquenaz, Rifate e Togarma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (238, 'nvi', 'Gênesis', 'gn', 10, 4, 'Estes foram os filhos de Javã: Elisá, Társis, Quitim e Rodanim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (239, 'nvi', 'Gênesis', 'gn', 10, 5, 'Deles procedem os povos marítimos, os quais se separaram em seu território, conforme a sua língua, cada um segundo os clãs de suas nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (240, 'nvi', 'Gênesis', 'gn', 10, 6, 'Estes foram os filhos de Cam: Cuxe, Mizraim, Fute e Canaã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (241, 'nvi', 'Gênesis', 'gn', 10, 7, 'Estes foram os filhos de Cuxe: Sebá, Havilá, Sabtá, Raamá e Sabtecá. Estes foram os filhos de Raamá: Sabá e Dedã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (242, 'nvi', 'Gênesis', 'gn', 10, 8, 'Cuxe gerou também Ninrode, o primeiro homem poderoso na terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (243, 'nvi', 'Gênesis', 'gn', 10, 9, 'Ele foi o mais valente dos caçadores, e por isso se diz: "Valente como Ninrode".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (244, 'nvi', 'Gênesis', 'gn', 10, 10, 'No início o seu reino abrangia Babel, Ereque, Acade e Calné, na terra de Sinear.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (245, 'nvi', 'Gênesis', 'gn', 10, 11, 'Dessa terra ele partiu para a Assíria, onde fundou Nínive, Reobote-Ir, Calá');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (246, 'nvi', 'Gênesis', 'gn', 10, 12, 'e Resém, que fica entre Nínive e Calá, a grande cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (247, 'nvi', 'Gênesis', 'gn', 10, 13, 'Mizraim gerou os luditas, os anamitas, os leabitas, os naftuítas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (248, 'nvi', 'Gênesis', 'gn', 10, 14, 'os patrusitas, os casluítas, dos quais se originaram os filisteus, e os caftoritas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (249, 'nvi', 'Gênesis', 'gn', 10, 15, 'Canaã gerou Sidom, seu filho mais velho, e Hete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (250, 'nvi', 'Gênesis', 'gn', 10, 16, 'como também os jebuseus, os amorreus, os girgaseus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (251, 'nvi', 'Gênesis', 'gn', 10, 17, 'os heveus, os arqueus, os sineus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (252, 'nvi', 'Gênesis', 'gn', 10, 18, 'os arvadeus, os zemareus e os hamateus. Posteriormente, os clãs cananeus se espalharam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (253, 'nvi', 'Gênesis', 'gn', 10, 19, 'As fronteiras de Canaã estendiam-se desde Sidom, iam até Gerar, e chegavam a Gaza e, de lá, prosseguiam até Sodoma, Gomorra, Admá e Zeboim, chegando até Lasa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (254, 'nvi', 'Gênesis', 'gn', 10, 20, 'São esses os descendentes de Cam, conforme seus clãs e línguas, em seus territórios e nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (255, 'nvi', 'Gênesis', 'gn', 10, 21, 'Sem, irmão mais velho de Jafé, também gerou filhos. Sem foi o antepassado de todos os filhos de Héber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (256, 'nvi', 'Gênesis', 'gn', 10, 22, 'Estes foram os filhos de Sem: Elão, Assur, Arfaxade, Lude e Arã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (257, 'nvi', 'Gênesis', 'gn', 10, 23, 'Estes foram os filhos de Arã: Uz, Hul, Géter e Meseque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (258, 'nvi', 'Gênesis', 'gn', 10, 24, 'Arfaxade gerou Salá, e este gerou Héber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (259, 'nvi', 'Gênesis', 'gn', 10, 25, 'A Héber nasceram dois filhos: Um deles se chamou Pelegue, porque em sua época a terra foi dividida; seu irmão chamou-se Joctã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (260, 'nvi', 'Gênesis', 'gn', 10, 26, 'Joctã gerou Almodá, Salefe, Hazarmavé, Jerá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (261, 'nvi', 'Gênesis', 'gn', 10, 27, 'Hadorão, Uzal, Dicla,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (262, 'nvi', 'Gênesis', 'gn', 10, 28, 'Obal, Abimael, Sabá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (263, 'nvi', 'Gênesis', 'gn', 10, 29, 'Ofir, Havilá e Jobabe. Todos esses foram filhos de Joctã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (264, 'nvi', 'Gênesis', 'gn', 10, 30, 'A região onde viviam estendia-se de Messa até Sefar, nas colinas ao leste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (265, 'nvi', 'Gênesis', 'gn', 10, 31, 'São esses os descendentes de Sem, conforme seus clãs e línguas, em seus territórios e nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (266, 'nvi', 'Gênesis', 'gn', 10, 32, 'São esses os clãs dos filhos de Noé, distribuídos em suas nações, conforme a história da sua descendência. A partir deles, os povos se dispersaram pela terra, depois do Dilúvio.');
