-- Inserções para Gênesis 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (319, 'nvi', 'Gênesis', 'gn', 13, 1, 'Saiu, pois, Abrão do Egito e foi para o Neguebe, com sua mulher e com tudo o que possuía, e Ló foi com ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (320, 'nvi', 'Gênesis', 'gn', 13, 2, 'Abrão tinha enriquecido muito, tanto em gado como em prata e ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (321, 'nvi', 'Gênesis', 'gn', 13, 3, 'Ele partiu do Neguebe em direção a Betel, indo de um lugar a outro, até que chegou ao lugar entre Betel e Ai onde já havia armado acampamento anteriormente');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (322, 'nvi', 'Gênesis', 'gn', 13, 4, 'e onde, pela primeira vez, tinha construído um altar. Ali Abrão invocou o nome do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (323, 'nvi', 'Gênesis', 'gn', 13, 5, 'Ló, que acompanhava Abrão, também possuía rebanhos e tendas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (324, 'nvi', 'Gênesis', 'gn', 13, 6, 'E não podiam morar os dois juntos na mesma região, porque possuíam tantos bens que a terra não podia sustentá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (325, 'nvi', 'Gênesis', 'gn', 13, 7, 'Por isso surgiu uma desavença entre os pastores dos rebanhos de Abrão e os de Ló. Nessa época os cananeus e os ferezeus habitavam aquela terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (326, 'nvi', 'Gênesis', 'gn', 13, 8, 'Então Abrão disse a Ló: "Não haja desavença entre mim e você, ou entre os seus pastores e os meus; afinal somos irmãos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (327, 'nvi', 'Gênesis', 'gn', 13, 9, 'Aí está a terra inteira diante de você. Vamos nos separar! Se você for para a esquerda, irei para a direita; se for para a direita, irei para a esquerda".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (328, 'nvi', 'Gênesis', 'gn', 13, 10, 'Olhou então Ló e viu todo o vale do Jordão, todo ele bem irrigado, até Zoar; era como o jardim do Senhor, como a terra do Egito. Isto se deu antes do Senhor destruir Sodoma e Gomorra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (329, 'nvi', 'Gênesis', 'gn', 13, 11, 'Ló escolheu todo o vale do Jordão e partiu em direção ao Leste. Assim os dois se separaram:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (330, 'nvi', 'Gênesis', 'gn', 13, 12, 'Abrão ficou na terra de Canaã, mas Ló mudou seu acampamento para um lugar próximo a Sodoma, entre as cidades do vale.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (331, 'nvi', 'Gênesis', 'gn', 13, 13, 'Ora, os homens de Sodoma eram extremamente perversos e pecadores contra o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (332, 'nvi', 'Gênesis', 'gn', 13, 14, 'Disse o Senhor a Abrão, depois que Ló separou-se dele: "De onde você está, olhe para o Norte, para o Sul, para o Leste e para o Oeste:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (333, 'nvi', 'Gênesis', 'gn', 13, 15, 'Toda a terra que você está vendo darei a você e à sua descendência para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (334, 'nvi', 'Gênesis', 'gn', 13, 16, 'Tornarei a sua descendência tão numerosa como o pó da terra. Se for possível contar o pó da terra, também se poderá contar a sua descendência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (335, 'nvi', 'Gênesis', 'gn', 13, 17, 'Percorra esta terra de alto a baixo, de um lado a outro, porque eu a darei a você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (336, 'nvi', 'Gênesis', 'gn', 13, 18, 'Então Abrão mudou seu acampamento e passou a viver próximo aos carvalhos de Manre, em Hebrom, onde construiu um altar dedicado ao Senhor.');
