-- Inserções para Gênesis 20
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (496, 'nvi', 'Gênesis', 'gn', 20, 1, 'Abraão partiu dali para a região do Neguebe e foi viver entre Cades e Sur. Depois morou algum tempo em Gerar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (497, 'nvi', 'Gênesis', 'gn', 20, 2, 'Ele dizia que Sara, sua mulher, era sua irmã. Então Abimeleque, rei de Gerar, mandou buscar Sara e tomou-a para si.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (498, 'nvi', 'Gênesis', 'gn', 20, 3, 'Certa noite Deus veio a Abimeleque num sonho e lhe disse: "Você morrerá! A mulher que você tomou é casada".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (499, 'nvi', 'Gênesis', 'gn', 20, 4, 'Mas Abimeleque, que ainda não havia tocado nela, disse: "Senhor, destruirias um povo inocente?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (500, 'nvi', 'Gênesis', 'gn', 20, 5, 'Não foi ele que me disse: ‘Ela é minha irmã’? E ela também não disse: ‘Ele é meu irmão’? O que fiz foi de coração puro e de mãos limpas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (501, 'nvi', 'Gênesis', 'gn', 20, 6, 'Então Deus lhe respondeu no sonho: "Sim, eu sei que você fez isso de coração puro. Eu mesmo impedi que você pecasse contra mim e por isso não lhe permiti tocá-la.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (502, 'nvi', 'Gênesis', 'gn', 20, 7, 'Agora devolva a mulher ao marido dela. Ele é profeta, e orará em seu favor, para que você não morra. Mas se não a devolver, esteja certo de que você e todos os seus morrerão".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (503, 'nvi', 'Gênesis', 'gn', 20, 8, 'Na manhã seguinte, Abimeleque convocou todos os seus conselheiros e, quando lhes contou tudo o que acontecera, tiveram muito medo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (504, 'nvi', 'Gênesis', 'gn', 20, 9, 'Depois Abimeleque chamou Abraão e disse: "O que fizeste conosco? Em que foi que pequei contra ti para que trouxesses tamanha culpa sobre mim e sobre o meu reino? O que me fizeste não se faz a ninguém! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (505, 'nvi', 'Gênesis', 'gn', 20, 10, 'E perguntou Abimeleque a Abraão: "O que te levou a fazer isso? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (506, 'nvi', 'Gênesis', 'gn', 20, 11, 'Abraão respondeu: "Eu disse a mim mesmo: Certamente ninguém teme a Deus neste lugar, e irão matar-me por causa da minha mulher.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (507, 'nvi', 'Gênesis', 'gn', 20, 12, 'Além disso, na verdade ela é minha irmã por parte de pai, mas não por parte de mãe; e veio a ser minha mulher.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (508, 'nvi', 'Gênesis', 'gn', 20, 13, 'E quando Deus me fez sair errante da casa de meu pai, eu disse a ela: Assim você me provará sua lealdade: em qualquer lugar aonde formos, diga que sou seu irmão".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (509, 'nvi', 'Gênesis', 'gn', 20, 14, 'Então Abimeleque trouxe ovelhas e bois, servos e servas, deu-os a Abraão e devolveu-lhe Sara, sua mulher.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (510, 'nvi', 'Gênesis', 'gn', 20, 15, 'E disse Abimeleque: "Minha terra está diante de ti; podes ficar onde quiseres".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (511, 'nvi', 'Gênesis', 'gn', 20, 16, 'A Sara ele disse: "Estou dando a seu irmão mil peças de prata, para reparar a ofensa feita a você diante de todos os seus; assim todos saberão que você é inocente".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (512, 'nvi', 'Gênesis', 'gn', 20, 17, 'A seguir Abraão orou a Deus, e Deus curou Abimeleque, sua mulher e suas servas, de forma que puderam novamente ter filhos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (513, 'nvi', 'Gênesis', 'gn', 20, 18, 'porque o Senhor havia tornado estéreis todas as mulheres da casa de Abimeleque por causa de Sara, mulher de Abraão.');
