-- Inserções para Gênesis 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (106, 'nvi', 'Gênesis', 'gn', 5, 1, 'Este é o registro da descendência de Adão: Quando Deus criou o homem, à semelhança de Deus o fez;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (107, 'nvi', 'Gênesis', 'gn', 5, 2, 'homem e mulher os criou. Quando foram criados, ele os abençoou e os chamou Homem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (108, 'nvi', 'Gênesis', 'gn', 5, 3, 'Aos 130 anos, Adão gerou um filho à sua semelhança, conforme a sua imagem; e deu-lhe o nome de Sete.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (109, 'nvi', 'Gênesis', 'gn', 5, 4, 'Depois que gerou Sete, Adão viveu 800 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (110, 'nvi', 'Gênesis', 'gn', 5, 5, 'Viveu ao todo 930 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (111, 'nvi', 'Gênesis', 'gn', 5, 6, 'Aos 105 anos, Sete gerou Enos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (112, 'nvi', 'Gênesis', 'gn', 5, 7, 'Depois que gerou Enos, Sete viveu 807 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (113, 'nvi', 'Gênesis', 'gn', 5, 8, 'Viveu ao todo 912 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (114, 'nvi', 'Gênesis', 'gn', 5, 9, 'Aos 90 anos, Enos gerou Cainã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (115, 'nvi', 'Gênesis', 'gn', 5, 10, 'Depois que gerou Cainã, Enos viveu 815 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (116, 'nvi', 'Gênesis', 'gn', 5, 11, 'Viveu ao todo 905 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (117, 'nvi', 'Gênesis', 'gn', 5, 12, 'Aos 70 anos, Cainã gerou Maalaleel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (118, 'nvi', 'Gênesis', 'gn', 5, 13, 'Depois que gerou Maalaleel, Cainã viveu 840 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (119, 'nvi', 'Gênesis', 'gn', 5, 14, 'Viveu ao todo 910 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (120, 'nvi', 'Gênesis', 'gn', 5, 15, 'Aos 65 anos, Maalaleel gerou Jarede.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (121, 'nvi', 'Gênesis', 'gn', 5, 16, 'Depois que gerou Jarede, Maalaleel viveu 830 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (122, 'nvi', 'Gênesis', 'gn', 5, 17, 'Viveu ao todo 895 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (123, 'nvi', 'Gênesis', 'gn', 5, 18, 'Aos 162 anos, Jarede gerou Enoque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (124, 'nvi', 'Gênesis', 'gn', 5, 19, 'Depois que gerou Enoque, Jarede viveu 800 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (125, 'nvi', 'Gênesis', 'gn', 5, 20, 'Viveu ao todo 962 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (126, 'nvi', 'Gênesis', 'gn', 5, 21, 'Aos 65 anos, Enoque gerou Matusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (127, 'nvi', 'Gênesis', 'gn', 5, 22, 'Depois que gerou Matusalém, Enoque andou com Deus 300 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (128, 'nvi', 'Gênesis', 'gn', 5, 23, 'Viveu ao todo 365 anos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (129, 'nvi', 'Gênesis', 'gn', 5, 24, 'Enoque andou com Deus; e já não foi encontrado, pois Deus o havia arrebatado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (130, 'nvi', 'Gênesis', 'gn', 5, 25, 'Aos 187 anos, Matusalém gerou Lameque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (131, 'nvi', 'Gênesis', 'gn', 5, 26, 'Depois que gerou Lameque, Matusalém viveu 782 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (132, 'nvi', 'Gênesis', 'gn', 5, 27, 'Viveu ao todo 969 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (133, 'nvi', 'Gênesis', 'gn', 5, 28, 'Aos 182 anos, Lameque gerou um filho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (134, 'nvi', 'Gênesis', 'gn', 5, 29, 'Deu-lhe o nome de Noé e disse: "Ele nos aliviará do nosso trabalho e do sofrimento de nossas mãos, causados pela terra que o SENHOR amaldiçoou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (135, 'nvi', 'Gênesis', 'gn', 5, 30, 'Depois que Noé nasceu, Lameque viveu 595 anos e gerou outros filhos e filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (136, 'nvi', 'Gênesis', 'gn', 5, 31, 'Viveu ao todo 777 anos e morreu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (137, 'nvi', 'Gênesis', 'gn', 5, 32, 'Aos 500 anos, Noé tinha gerado Sem, Cam e Jafé.');
