-- Inserções para Gênesis 16
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (382, 'nvi', 'Gênesis', 'gn', 16, 1, 'Ora, Sarai, mulher de Abrão, não lhe dera nenhum filho. Como tinha uma serva egípcia, chamada Hagar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (383, 'nvi', 'Gênesis', 'gn', 16, 2, 'disse a Abrão: "Já que o Senhor me impediu de ter filhos, possua a minha serva; talvez eu possa formar família por meio dela". Abrão atendeu à proposta de Sarai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (384, 'nvi', 'Gênesis', 'gn', 16, 3, 'Quando isso aconteceu já fazia dez anos que Abrão, seu marido, vivia em Canaã. Foi nessa ocasião que Sarai, sua mulher, entregou sua serva egípcia Hagar a Abrão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (385, 'nvi', 'Gênesis', 'gn', 16, 4, 'Ele possuiu Hagar, e ela engravidou. Quando se viu grávida, começou a olhar com desprezo para a sua senhora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (386, 'nvi', 'Gênesis', 'gn', 16, 5, 'Então Sarai disse a Abrão: "Caia sobre você a afronta que venho sofrendo. Coloquei minha serva em seus braços, e agora que ela sabe que engravidou, despreza-me. Que o Senhor seja o juiz entre mim e você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (387, 'nvi', 'Gênesis', 'gn', 16, 6, 'Respondeu Abrão a Sarai: "Sua serva está em suas mãos. Faça com ela o que achar melhor". Então Sarai tanto maltratou Hagar que esta acabou fugindo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (388, 'nvi', 'Gênesis', 'gn', 16, 7, 'O Anjo do Senhor encontrou Hagar perto de uma fonte no deserto, no caminho de Sur,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (389, 'nvi', 'Gênesis', 'gn', 16, 8, 'e perguntou-lhe: "Hagar, serva de Sarai, de onde você vem? Para onde vai? " Respondeu ela: "Estou fugindo de Sarai, a minha senhora".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (390, 'nvi', 'Gênesis', 'gn', 16, 9, 'Disse-lhe então o Anjo do Senhor: "Volte à sua senhora e sujeite-se a ela".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (391, 'nvi', 'Gênesis', 'gn', 16, 10, 'Disse mais o anjo: "Multiplicarei tanto os seus descendentes que ninguém os poderá contar".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (392, 'nvi', 'Gênesis', 'gn', 16, 11, 'Disse-lhe ainda o Anjo do Senhor: "Você está grávida e terá um filho, e lhe dará o nome de Ismael, porque o Senhor a ouviu em seu sofrimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (393, 'nvi', 'Gênesis', 'gn', 16, 12, 'Ele será como jumento selvagem; sua mão será contra todos, e a mão de todos contra ele, e ele viverá em hostilidade contra todos os seus irmãos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (394, 'nvi', 'Gênesis', 'gn', 16, 13, 'Este foi o nome que ela deu ao Senhor que lhe havia falado: "Tu és o Deus que me vê", pois dissera: "Teria eu visto Aquele que me vê? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (395, 'nvi', 'Gênesis', 'gn', 16, 14, 'Por isso o poço, que fica entre Cades e Berede, foi chamado Beer-Laai-Roi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (396, 'nvi', 'Gênesis', 'gn', 16, 15, 'Hagar teve um filho de Abrão, e este lhe deu o nome de Ismael.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (397, 'nvi', 'Gênesis', 'gn', 16, 16, 'Abrão estava com oitenta e seis anos de idade quando Hagar lhe deu Ismael.');
