-- Inserções para Hebreus 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30094, 'nvi', 'Hebreus', 'hb', 8, 1, 'O mais importante do que estamos tratando é que temos um sumo sacerdote como esse, o qual se assentou à direita do trono da Majestade nos céus');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30095, 'nvi', 'Hebreus', 'hb', 8, 2, 'e serve no santuário, no verdadeiro tabernáculo que o Senhor erigiu, e não o homem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30096, 'nvi', 'Hebreus', 'hb', 8, 3, 'Todo sumo sacerdote é constituído para apresentar ofertas e sacrifícios, e por isso era necessário que também este tivesse algo a oferecer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30097, 'nvi', 'Hebreus', 'hb', 8, 4, 'Se ele estivesse na terra, nem seria sumo sacerdote, visto que já existem aqueles que apresentam as ofertas prescritas pela lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30098, 'nvi', 'Hebreus', 'hb', 8, 5, 'Eles servem num santuário que é cópia e sombra daquele que está nos céus, já que Moisés foi avisado quando estava para construir o tabernáculo: "Tenha o cuidado de fazer tudo segundo o modelo que lhe foi mostrado no monte".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30099, 'nvi', 'Hebreus', 'hb', 8, 6, 'Agora, porém, o ministério que Jesus recebeu é superior ao deles, assim como também a aliança da qual ele é mediador é superior à antiga, sendo baseada em promessas superiores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30100, 'nvi', 'Hebreus', 'hb', 8, 7, 'Pois se aquela primeira aliança fosse perfeita, não seria necessário procurar lugar para outra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30101, 'nvi', 'Hebreus', 'hb', 8, 8, 'Deus, porém, achou o povo em falta e disse: "Estão chegando os dias, declara o Senhor, quando farei uma nova aliança com a comunidade de Israel e com a comunidade de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30102, 'nvi', 'Hebreus', 'hb', 8, 9, 'Não será como a aliança que fiz com os seus antepassados quando os tomei pela mão para tirá-los do Egito; visto que eles não permaneceram fiéis à minha aliança, eu me afastei deles", diz o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30103, 'nvi', 'Hebreus', 'hb', 8, 10, '"Esta é a aliança que farei com a comunidade de Israel depois daqueles dias", declara o Senhor. "Porei minhas leis em suas mentes e as escreverei em seus corações. Serei o Deus deles, e eles serão o meu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30104, 'nvi', 'Hebreus', 'hb', 8, 11, 'Ninguém mais ensinará ao seu próximo nem ao seu irmão, dizendo: ‘Conheça ao Senhor’, porque todos eles me conhecerão, desde o menor até o maior.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30105, 'nvi', 'Hebreus', 'hb', 8, 12, 'Porque eu lhes perdoarei a maldade e não me lembrarei mais dos seus pecados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30106, 'nvi', 'Hebreus', 'hb', 8, 13, 'Chamando "nova" esta aliança, ele tornou antiquada a primeira; e o que se torna antiquado e envelhecido, está a ponto de desaparecer.');
