-- Inserções para Hebreus 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30016, 'nvi', 'Hebreus', 'hb', 4, 1, 'Visto que nos foi deixada a promessa de entrarmos no descanso de Deus, temamos que algum de vocês pense que tenha falhado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30017, 'nvi', 'Hebreus', 'hb', 4, 2, 'Pois as boas novas foram pregadas também a nós, tanto quanto a eles; mas a mensagem que eles ouviram de nada lhes valeu, pois não foi acompanhada de fé por aqueles que a ouviram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30018, 'nvi', 'Hebreus', 'hb', 4, 3, 'Pois nós, os que cremos, é que entramos naquele descanso, conforme Deus disse: "Assim jurei na minha ira: Jamais entrarão no meu descanso" — embora as suas obras estivessem concluídas desde a criação do mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30019, 'nvi', 'Hebreus', 'hb', 4, 4, 'Pois em certo lugar ele falou sobre o sétimo dia, nestas palavras: "No sétimo dia Deus descansou de toda obra que realizara".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30020, 'nvi', 'Hebreus', 'hb', 4, 5, 'E de novo, na passagem citada há pouco, diz: "Jamais entrarão no meu descanso".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30021, 'nvi', 'Hebreus', 'hb', 4, 6, 'Entretanto, resta entrarem alguns naquele descanso, e aqueles a quem anteriormente as boas novas foram pregadas não entraram, por causa da desobediência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30022, 'nvi', 'Hebreus', 'hb', 4, 7, 'Por isso Deus estabelece outra vez um determinado dia, chamando-o "hoje", ao declarar muito tempo depois, por meio de Davi, de acordo com o que fora dito antes: "Se hoje vocês ouvirem a sua voz, não endureçam o coração".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30023, 'nvi', 'Hebreus', 'hb', 4, 8, 'Porque, se Josué lhes tivesse dado descanso, Deus não teria falado posteriormente a respeito de outro dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30024, 'nvi', 'Hebreus', 'hb', 4, 9, 'Assim, ainda resta um descanso sabático para o povo de Deus;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30025, 'nvi', 'Hebreus', 'hb', 4, 10, 'pois todo aquele que entra no descanso de Deus, também descansa das suas obras, como Deus descansou das suas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30026, 'nvi', 'Hebreus', 'hb', 4, 11, 'Portanto, esforcemo-nos por entrar nesse descanso, para que ninguém venha a cair, seguindo aquele exemplo de desobediência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30027, 'nvi', 'Hebreus', 'hb', 4, 12, 'Pois a palavra de Deus é viva e eficaz, e mais afiada que qualquer espada de dois gumes; ela penetra ao ponto de dividir alma e espírito, juntas e medulas, e julga os pensamentos e intenções do coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30028, 'nvi', 'Hebreus', 'hb', 4, 13, 'Nada, em toda a criação, está oculto aos olhos de Deus. Tudo está descoberto e exposto diante dos olhos daquele a quem havemos de prestar contas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30029, 'nvi', 'Hebreus', 'hb', 4, 14, 'Portanto, visto que temos um grande sumo sacerdote que adentrou os céus, Jesus, o Filho de Deus, apeguemo-nos com toda a firmeza à fé que professamos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30030, 'nvi', 'Hebreus', 'hb', 4, 15, 'pois não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas, mas sim alguém que, como nós, passou por todo tipo de tentação, porém, sem pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30031, 'nvi', 'Hebreus', 'hb', 4, 16, 'Assim sendo, aproximemo-nos do trono da graça com toda a confiança, a fim de recebermos misericórdia e encontrarmos graça que nos ajude no momento da necessidade.');
