-- Inserções para Hebreus 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30032, 'nvi', 'Hebreus', 'hb', 5, 1, 'Todo sumo sacerdote é escolhido dentre os homens e designado para representá-los em questões relacionadas com Deus e apresentar ofertas e sacrifícios pelos pecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30033, 'nvi', 'Hebreus', 'hb', 5, 2, 'Ele é capaz de se compadecer dos que não têm conhecimento e se desviam, visto que ele próprio está sujeito à fraqueza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30034, 'nvi', 'Hebreus', 'hb', 5, 3, 'Por isso ele precisa oferecer sacrifícios por seus próprios pecados, bem como pelos pecados do povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30035, 'nvi', 'Hebreus', 'hb', 5, 4, 'Ninguém toma esta honra para si mesmo, mas deve ser chamado por Deus, como de fato o foi Arão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30036, 'nvi', 'Hebreus', 'hb', 5, 5, 'Da mesma forma, Cristo não tomou para si a glória de se tornar sumo sacerdote, mas Deus lhe disse: "Tu és meu Filho; eu hoje te gerei".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30037, 'nvi', 'Hebreus', 'hb', 5, 6, 'E diz noutro lugar: "Tu és sacerdote para sempre, segundo a ordem de Melquisedeque".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30038, 'nvi', 'Hebreus', 'hb', 5, 7, 'Durante os seus dias de vida na terra, Jesus ofereceu orações e súplicas, em alta voz e com lágrimas, àquele que o podia salvar da morte, sendo ouvido por causa da sua reverente submissão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30039, 'nvi', 'Hebreus', 'hb', 5, 8, 'Embora sendo Filho, ele aprendeu a obedecer por meio daquilo que sofreu;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30040, 'nvi', 'Hebreus', 'hb', 5, 9, 'e, uma vez aperfeiçoado, tornou-se a fonte de eterna salvação para todos os que lhe obedecem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30041, 'nvi', 'Hebreus', 'hb', 5, 10, 'sendo designado por Deus sumo sacerdote, segundo a ordem de Melquisedeque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30042, 'nvi', 'Hebreus', 'hb', 5, 11, 'Quanto a isso, temos muito que dizer, coisas difíceis de explicar, porque vocês se tornaram lentos para aprender.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30043, 'nvi', 'Hebreus', 'hb', 5, 12, 'De fato, embora a esta altura já devessem ser mestres, vocês precisam de alguém que lhes ensine novamente os princípios elementares da palavra de Deus. Estão precisando de leite, e não de alimento sólido!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30044, 'nvi', 'Hebreus', 'hb', 5, 13, 'Quem se alimenta de leite ainda é criança, e não tem experiência no ensino da justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30045, 'nvi', 'Hebreus', 'hb', 5, 14, 'Mas o alimento sólido é para os adultos, os quais, pelo exercício constante, tornaram-se aptos para discernir tanto o bem quanto o mal.');
