-- Inserções para Hebreus 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29965, 'nvi', 'Hebreus', 'hb', 1, 1, 'Há muito tempo Deus falou muitas vezes e de várias maneiras aos nossos antepassados por meio dos profetas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29966, 'nvi', 'Hebreus', 'hb', 1, 2, 'mas nestes últimos dias falou-nos por meio do Filho, a quem constituiu herdeiro de todas as coisas e por meio de quem fez o universo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29967, 'nvi', 'Hebreus', 'hb', 1, 3, 'O Filho é o resplendor da glória de Deus e a expressão exata do seu ser, sustentando todas as coisas por sua palavra poderosa. Depois de ter realizado a purificação dos pecados, ele se assentou à direita da Majestade nas alturas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29968, 'nvi', 'Hebreus', 'hb', 1, 4, 'tornando-se tão superior aos anjos quanto o nome que herdou é superior ao deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29969, 'nvi', 'Hebreus', 'hb', 1, 5, 'Pois a qual dos anjos Deus alguma vez disse: "Tu és meu Filho; eu hoje te gerei"? E outra vez: "Eu serei seu Pai, e ele será meu Filho"?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29970, 'nvi', 'Hebreus', 'hb', 1, 6, 'E ainda, quando Deus introduz o Primogênito no mundo, diz: "Todos os anjos de Deus o adorem".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29971, 'nvi', 'Hebreus', 'hb', 1, 7, 'Quanto aos anjos, ele diz: "Ele faz dos seus anjos ventos, e dos seus servos, clarões reluzentes".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29972, 'nvi', 'Hebreus', 'hb', 1, 8, 'Mas a respeito do Filho, diz: "O teu trono, ó Deus, subsiste para todo o sempre; cetro de eqüidade é o cetro do teu Reino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29973, 'nvi', 'Hebreus', 'hb', 1, 9, 'Amas a justiça e odeias a iniqüidade; por isso, Deus, o teu Deus, escolheu-te dentre os teus companheiros, ungindo-te com óleo de alegria".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29974, 'nvi', 'Hebreus', 'hb', 1, 10, 'E também diz: "No princípio, Senhor, firmaste os fundamentos da terra, e os céus são obras das tuas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29975, 'nvi', 'Hebreus', 'hb', 1, 11, 'Eles perecerão, mas tu permanecerás; envelhecerão como vestimentas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29976, 'nvi', 'Hebreus', 'hb', 1, 12, 'Tu os enrolarás como um manto, como roupas eles serão trocados. Mas tu permaneces o mesmo, e os teus dias jamais terão fim".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29977, 'nvi', 'Hebreus', 'hb', 1, 13, 'A qual dos anjos Deus alguma vez disse: "Senta-te à minha direita, até que eu faça dos teus inimigos um estrado para os teus pés"?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29978, 'nvi', 'Hebreus', 'hb', 1, 14, 'Os anjos não são, todos eles, espíritos ministradores enviados para servir aqueles que hão de herdar a salvação?');
