-- Inserções para Habacuque 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22733, 'nvi', 'Habacuque', 'hc', 1, 1, 'Advertência do profeta Habacuque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22734, 'nvi', 'Habacuque', 'hc', 1, 2, 'Até quando, Senhor, clamarei por socorro, sem que tu ouças? Até quando gritarei a ti: "Violência! " sem que tragas salvação?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22735, 'nvi', 'Habacuque', 'hc', 1, 3, 'Por que me fazes ver a injustiça, e contemplar a maldade? A destruição e a violência estão diante de mim; há luta e conflito por todo lado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22736, 'nvi', 'Habacuque', 'hc', 1, 4, 'Por isso a lei se enfraquece e a justiça nunca prevalece. Os ímpios prejudicam os justos, e assim a justiça é pervertida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22737, 'nvi', 'Habacuque', 'hc', 1, 5, '"Olhem as nações e contemplem-nas, fiquem atônitos e pasmem; pois nos dias de vocês farei algo em que não creriam, se lhes fosse contado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22738, 'nvi', 'Habacuque', 'hc', 1, 6, 'Estou trazendo os babilônios, nação cruel e impetuosa, que marcha por toda a extensão da terra para apoderar-se de moradias que não lhe pertencem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22739, 'nvi', 'Habacuque', 'hc', 1, 7, 'É uma nação apavorante e temível, que cria a sua própria justiça e promove a sua própria honra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22740, 'nvi', 'Habacuque', 'hc', 1, 8, 'Seus cavalos são mais velozes que os leopardos, mais ferozes que os lobos no crepúsculo. Sua cavalaria vem de longe. Seus cavalos vêm a galope; vêm voando como ave de rapina que mergulha para devorar;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22741, 'nvi', 'Habacuque', 'hc', 1, 9, 'todos vêm prontos para a violência. Suas hordas avançam como o vento do deserto e fazendo tantos prisioneiros como a areia da praia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22742, 'nvi', 'Habacuque', 'hc', 1, 10, 'Menosprezam os reis e zombam dos governantes. Riem de todas as cidades fortificadas, pois constroem rampas de terra e por elas as conquistam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22743, 'nvi', 'Habacuque', 'hc', 1, 11, 'Depois passam como o vento e prosseguem; homens carregados de culpa, e que têm por deus a sua própria força".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22744, 'nvi', 'Habacuque', 'hc', 1, 12, 'Senhor, tu não és desde a eternidade? Meu Deus, meu Santo, tu não morrerás. Senhor, tu designaste essa nação para executar juízo; ó Rocha, determinaste a ela que aplicasse castigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22745, 'nvi', 'Habacuque', 'hc', 1, 13, 'Teus olhos são tão puros, que não suportam ver o mal; não podes tolerar a maldade. Por que toleras então esses perversos? Por que ficas calado enquanto os ímpios engolem os que são mais justos do que eles?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22746, 'nvi', 'Habacuque', 'hc', 1, 14, 'Tornaste os homens como peixes do mar, como animais, que não são governados por ninguém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22747, 'nvi', 'Habacuque', 'hc', 1, 15, 'Esses ímpios puxam a todos com anzóis, apanham-nos em suas redes e nelas os arrastam; então alegram-se e exultam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22748, 'nvi', 'Habacuque', 'hc', 1, 16, 'E por essa razão eles oferecem sacrifício às suas redes e queimam incenso em sua honra, pois, graças às suas redes, vivem em grande conforto e desfrutam iguarias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22749, 'nvi', 'Habacuque', 'hc', 1, 17, 'Mas, continuará ele esvaziando a sua rede, destruindo sem misericórdia as nações?');
