-- Inserções para Isaías 46
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18588, 'nvi', 'Isaías', 'is', 46, 1, 'Bel se inclina, Nebo se abaixa; os seus ídolos são levados por animais de carga. As imagens que são levadas por aí, são pesadas, um fardo para os exaustos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18589, 'nvi', 'Isaías', 'is', 46, 2, 'Juntos eles se abaixam e se inclinam; incapazes de salvar o fardo, eles mesmos vão para o cativeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18590, 'nvi', 'Isaías', 'is', 46, 3, '"Escute-me, ó casa de Jacó, todos vocês que restam da nação de Israel, vocês a quem tenho sustentado desde que foram concebidos, e que tenho carregado desde o seu nascimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18591, 'nvi', 'Isaías', 'is', 46, 4, 'Mesmo na sua velhice, quando tiverem cabelos brancos, sou eu aquele, aquele que os susterá. Eu os fiz e eu os levarei; eu os susterei e eu os salvarei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18592, 'nvi', 'Isaías', 'is', 46, 5, '"Com quem vocês me compararão ou a quem me considerarão igual? Com quem vocês me assemelharão para que sejamos comparados?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18593, 'nvi', 'Isaías', 'is', 46, 6, 'Alguns derramam ouro de suas bolsas e pesam prata na balança; contratam um ourives para transformá-lo num deus, inclinam-se e o adoram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18594, 'nvi', 'Isaías', 'is', 46, 7, 'Erguem-no ao ombro e o carregam; põem-no de pé em seu local, e ali ele fica. Daquele local não consegue se mexer. Embora alguém o invoque, ele não responde; é incapaz de salvá-lo de seus problemas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18595, 'nvi', 'Isaías', 'is', 46, 8, '"Lembrem-se disto, gravem-no na mente, acolham no íntimo, ó rebeldes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18596, 'nvi', 'Isaías', 'is', 46, 9, 'Lembrem-se das coisas passadas, das coisas muito antigas! Eu sou Deus, e não há nenhum outro; eu sou Deus, e não há nenhum como eu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18597, 'nvi', 'Isaías', 'is', 46, 10, 'Desde o início faço conhecido o fim, desde tempos remotos, o que ainda virá. Digo: Meu propósito ficará de pé, e farei tudo o que me agrada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18598, 'nvi', 'Isaías', 'is', 46, 11, 'Do oriente convoco uma ave de rapina; de uma terra bem distante, um homem para cumprir o meu propósito. O que eu disse, isso eu farei acontecer; o que planejei, isso farei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18599, 'nvi', 'Isaías', 'is', 46, 12, 'Escutem-me, vocês de coração obstinado, vocês que estão longe da retidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18600, 'nvi', 'Isaías', 'is', 46, 13, 'Estou trazendo para perto a minha retidão, ela não está distante; e a minha salvação não será adiada. Concederei salvação a Sião, meu esplendor a Israel.');
