-- Inserções para Isaías 25
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18120, 'nvi', 'Isaías', 'is', 25, 1, 'Senhor, tu és o meu Deus; eu te exaltarei e louvarei o teu nome, pois com grande perfeição tens feito maravilhas, coisas há muito planejadas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18121, 'nvi', 'Isaías', 'is', 25, 2, 'Fizeste da cidade um monte de entulho, da cidade fortificada uma ruína, da cidadela dos estrangeiros uma cidade inexistente, que jamais será reconstruída.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18122, 'nvi', 'Isaías', 'is', 25, 3, 'Por isso um povo forte te honrará; a cidade das nações cruéis te temerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18123, 'nvi', 'Isaías', 'is', 25, 4, 'Tens sido refúgio para os pobres, refúgio para o necessitado em sua aflição, abrigo contra a tempestade e sombra contra o calor quando o sopro dos cruéis é como tempestade contra um muro');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18124, 'nvi', 'Isaías', 'is', 25, 5, 'e como o calor do deserto. Tu silencias o bramido dos estrangeiros; assim como diminui o calor com a sombra de uma nuvem, também a canção dos temíveis é emudecida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18125, 'nvi', 'Isaías', 'is', 25, 6, 'Neste monte o Senhor dos Exércitos preparará um farto banquete para todos os povos, um banquete de vinho envelhecido, com carnes suculentas e o melhor vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18126, 'nvi', 'Isaías', 'is', 25, 7, 'Neste monte ele destruirá o véu que envolve todos os povos, a cortina que cobre todas as nações;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18127, 'nvi', 'Isaías', 'is', 25, 8, 'destruirá a morte para sempre. O Soberano Senhor enxugará as lágrimas de todo o rosto e retirará de toda a terra a zombaria do seu povo. Foi o Senhor quem disse!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18128, 'nvi', 'Isaías', 'is', 25, 9, 'Naquele dia dirão: "Esse é o nosso Deus; nós confiamos nele, e ele nos salvou. Esse é o Senhor, nós confiamos nele; exultemos e alegremo-nos, pois ele nos salvou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18129, 'nvi', 'Isaías', 'is', 25, 10, 'Pois a mão do Senhor repousará sobre este monte; mas Moabe será pisoteado em seu próprio lugar, como a palha é pisoteada na esterqueira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18130, 'nvi', 'Isaías', 'is', 25, 11, 'Ali Moabe estenderá as mãos, como faz o nadador para nadar, mas o Senhor abaterá o seu orgulho, apesar da habilidade das suas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18131, 'nvi', 'Isaías', 'is', 25, 12, 'Abaterá as torres altas dos seus altos muros e os derrubará; ele os lançará ao pó da terra.');
