-- Inserções para Isaías 16
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17971, 'nvi', 'Isaías', 'is', 16, 1, 'Enviem cordeiros como tributo ao governante da terra, desde Selá, atravessando o deserto, até o monte Sião.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17972, 'nvi', 'Isaías', 'is', 16, 2, 'Como aves perdidas, lançadas fora do ninho, assim são os habitantes de Moabe nos lugares de passagem do Arnom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17973, 'nvi', 'Isaías', 'is', 16, 3, '"Dá conselhos e propõe uma decisão. Torna a tua sombra como a noite em pleno meio-dia e esconde os fugitivos; não deixes ninguém saber onde estão os refugiados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17974, 'nvi', 'Isaías', 'is', 16, 4, 'Que os fugitivos moabitas habitem contigo; sê para eles abrigo contra o destruidor. " O opressor há de ter fim, a destruição se acabará e o agressor desaparecerá da terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17975, 'nvi', 'Isaías', 'is', 16, 5, 'então, em amor será firmado um trono; em fidelidade um homem se assentará nele na tenda de Davi: um Juiz que busca a justiça e se apressa em defender o que é justo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17976, 'nvi', 'Isaías', 'is', 16, 6, 'Ouvimos acerca da soberba de Moabe: da sua arrogância exagerada, de todo o seu orgulho e do seu ódio; mas tudo isso não vale nada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17977, 'nvi', 'Isaías', 'is', 16, 7, 'Por isso choram os moabitas, todos choram por Moabe. Cada um lamenta e se entristece pelos bolos de passas de Quir-Haresete.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17978, 'nvi', 'Isaías', 'is', 16, 8, 'As lavouras de Hesbom estão murchas, como também as videiras de Sibma. Os governantes das nações pisotearam as melhores videiras, que antes chegavam até Jazar e estendiam-se para o deserto. Seus brotos espalhavam-se e chegavam ao mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17979, 'nvi', 'Isaías', 'is', 16, 9, 'Por isso eu choro, como Jazar chora, por causa das videiras de Sibma. Hesbom, Eleale, com minhas lágrimas eu as encharco! Pois não se ouvem mais os gritos de alegria por seus frutos e por suas colheitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17980, 'nvi', 'Isaías', 'is', 16, 10, 'Foram-se a alegria e a exultação dos pomares; ninguém canta nem grita nas vinhas; ninguém pisa as uvas nos lagares, pois fiz cessar os gritos de alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17981, 'nvi', 'Isaías', 'is', 16, 11, 'Por isso as minhas entranhas gemem como harpa por Moabe; o íntimo do meu ser estremece por Quir-Heres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17982, 'nvi', 'Isaías', 'is', 16, 12, 'Quando Moabe se apresentar cansado nos lugares altos, e for ao seu santuário, nada conseguirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17983, 'nvi', 'Isaías', 'is', 16, 13, 'Essa palavra o Senhor já havia falado acerca de Moabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17984, 'nvi', 'Isaías', 'is', 16, 14, 'Mas agora o Senhor diz: "Dentro de três anos, e nem um dia a mais, o esplendor de Moabe e toda a sua grande população serão desprezados, e os seus sobreviventes serão poucos e fracos".');
