-- Inserções para Isaías 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17985, 'nvi', 'Isaías', 'is', 17, 1, 'Advertência contra Damasco: "Damasco deixará de ser cidade; e se tornará um monte de ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17986, 'nvi', 'Isaías', 'is', 17, 2, 'Suas cidades serão abandonadas; serão entregues aos rebanhos que ali se deitarão, e ninguém os espantará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17987, 'nvi', 'Isaías', 'is', 17, 3, 'Efraim deixará de ser uma fortaleza, e Damasco uma realeza; o remanescente de Arã será como a glória dos israelitas", anuncia o Senhor dos Exércitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17988, 'nvi', 'Isaías', 'is', 17, 4, '"Naquele dia a glória de Jacó se definhará, e a gordura do seu corpo se consumirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17989, 'nvi', 'Isaías', 'is', 17, 5, 'Será como quando um ceifeiro junta o trigo e colhe as espigas com o braço, como quando se apanham os feixes de trigo no vale de Refaim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17990, 'nvi', 'Isaías', 'is', 17, 6, 'Contudo, restarão algumas espigas, como quando se sacode uma oliveira, ficam duas ou três azeitonas nos galhos mais altos e umas quatro ou cinco nos ramos mais produtivos", anuncia o Senhor, o Deus de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17991, 'nvi', 'Isaías', 'is', 17, 7, 'Naquele dia os homens olharão para aquele que os fez e voltarão os olhos para o Santo de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17992, 'nvi', 'Isaías', 'is', 17, 8, 'Não olharão para os altares, obra de suas mãos, e não darão a mínima atenção aos postes sagrados e aos altares de incenso que os seus dedos fizeram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17993, 'nvi', 'Isaías', 'is', 17, 9, 'Naquele dia as suas cidades fortes, que tinham sido abandonadas por causa dos israelitas, serão como lugares entregues aos bosques e ao mato. E tudo será desolação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17994, 'nvi', 'Isaías', 'is', 17, 10, 'Porque vocês se esqueceram de Deus, do seu Salvador e não se lembraram da Rocha, da fortaleza de vocês; então vocês cultivarão as melhores plantas, videiras importadas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17995, 'nvi', 'Isaías', 'is', 17, 11, 'No dia em que as semearem as farão crescer, e de manhã florescerão. Contudo, não haverá colheita no dia da tristeza e do mal irremediável.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17996, 'nvi', 'Isaías', 'is', 17, 12, 'Ah! O bramido das numerosas nações; bramam como o mar! Ah, o rugido dos povos; rugem como águas impetuosas!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17997, 'nvi', 'Isaías', 'is', 17, 13, 'Embora os povos rujam como ondas encapeladas, quando ele os repreender, fugirão para longe, carregados pelo vento como palha nas colinas, como galhos arrancados pela ventania.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17998, 'nvi', 'Isaías', 'is', 17, 14, 'Ao cair da tarde, pavor repentino! Antes do amanhecer, já se foram! Esse é o destino dos que nos saqueiam, essa é a parte que caberá aos que roubam.');
