-- Inserções para Isaías 62
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18856, 'nvi', 'Isaías', 'is', 62, 1, 'Por amor de Sião eu não sossegarei, por amor de Jerusalém não descansarei enquanto a sua justiça não resplandecer como a alvorada, e a sua salvação, como as chamas de uma tocha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18857, 'nvi', 'Isaías', 'is', 62, 2, 'As nações verão a sua justiça, e todos os reis, a sua glória; você será chamada por um novo nome que a boca do Senhor lhe dará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18858, 'nvi', 'Isaías', 'is', 62, 3, 'Será uma esplêndida coroa na mão do Senhor, um diadema real na mão do seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18859, 'nvi', 'Isaías', 'is', 62, 4, 'Não mais a chamarão abandonada, nem desamparada à sua terra. Você, porém, será chamada Hefizibá, e a sua terra, Beulá, pois o Senhor terá prazer em você, e a sua terra estará casada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18860, 'nvi', 'Isaías', 'is', 62, 5, 'Assim como um jovem se casa com sua noiva, os seus filhos se casarão com você; assim como o noivo se regozija por sua noiva, assim o seu Deus se regozija por você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18861, 'nvi', 'Isaías', 'is', 62, 6, 'Coloquei sentinelas em seus muros, ó Jerusalém; jamais descansarão, dia e noite. Vocês que clamam pelo Senhor, não se entreguem ao repouso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18862, 'nvi', 'Isaías', 'is', 62, 7, 'e não lhe concedam descanso até que ele estabeleça Jerusalém e faça dela o louvor da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18863, 'nvi', 'Isaías', 'is', 62, 8, 'O Senhor jurou por sua mão direita e por seu braço poderoso: "Nunca mais darei o seu trigo como alimento para os seus inimigos, e nunca mais estrangeiros beberão o vinho novo pelo qual se afadigaram;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18864, 'nvi', 'Isaías', 'is', 62, 9, 'mas aqueles que colherem o trigo, dele comerão e louvarão o Senhor, e aqueles que recolherem as uvas delas beberão nos pátios do meu santuário".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18865, 'nvi', 'Isaías', 'is', 62, 10, 'Passem, passem pelas portas! Preparem o caminho para o povo. Construam, construam a estrada! Removam as pedras. Ergam uma bandeira para as nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18866, 'nvi', 'Isaías', 'is', 62, 11, 'O Senhor proclamou aos confins da terra: "Digam à cidade de Sião: Veja! O seu Salvador vem! Veja! Ele traz a sua recompensa e o seu galardão o acompanha".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18867, 'nvi', 'Isaías', 'is', 62, 12, 'Eles serão chamados povo santo, redimidos do Senhor; e você será chamada procurada, cidade não abandonada.');
