-- Inserções para Isaías 47
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18601, 'nvi', 'Isaías', 'is', 47, 1, '"Desça, sente-se no pó, Virgem cidade de Babilônia; sente-se no chão sem um trono, Filha dos babilônios. Você não será mais chamada mimosa e delicada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18602, 'nvi', 'Isaías', 'is', 47, 2, 'Apanhe pedras de moinha e faça farinha; retire o seu véu. Levante a saia, desnude as suas pernas e atravesse os riachos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18603, 'nvi', 'Isaías', 'is', 47, 3, 'Sua nudez será exposta e sua vergonha será revelada. Eu me vingarei; não pouparei ninguém. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18604, 'nvi', 'Isaías', 'is', 47, 4, 'Nosso redentor, o Senhor dos Exércitos é o seu nome, é o Santo de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18605, 'nvi', 'Isaías', 'is', 47, 5, '"Sente-se em silêncio, entre nas trevas, cidade dos babilônios; você não será mais chamada rainha dos reinos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18606, 'nvi', 'Isaías', 'is', 47, 6, 'Fiquei irado contra o meu povo e profanei minha herança; eu os entreguei nas suas mãos, e você não mostrou misericórdia para com eles. Mesmo sobre os idosos você pôs um jugo muito pesado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18607, 'nvi', 'Isaías', 'is', 47, 7, 'Você disse: ‘Continuarei sempre sendo a rainha eterna! ’ Mas você não ponderou estas coisas nem refletiu no que poderia acontecer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18608, 'nvi', 'Isaías', 'is', 47, 8, '"Agora, então, escute, criatura provocadora, que age despreocupada e preguiçosamente em sua segurança, e diz a si mesma: ‘Somente eu, e mais ninguém. Jamais ficarei viúva nem sofrerei a perda de filhos’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18609, 'nvi', 'Isaías', 'is', 47, 9, 'Estas duas coisas acontecerão a você num mesmo instante, num único dia, perda de filhos e viuvez; virão sobre você com todo peso, a despeito de suas muitas feitiçarias e de todas as suas poderosas palavras de encantamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18610, 'nvi', 'Isaías', 'is', 47, 10, 'Você confiou em sua impiedade e disse: ‘Ninguém me vê’. Sua sabedoria e conhecimento a enganam quando você diz a si mesma: ‘Somente eu, e mais ninguém além de mim’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18611, 'nvi', 'Isaías', 'is', 47, 11, 'A desgraça a alcançará e você não saberá como esconjurá-la. Cairá sobre você um mal do qual você não poderá proteger-se com um resgate; uma catástrofe que você não pode prever cairá repentinamente sobre você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18612, 'nvi', 'Isaías', 'is', 47, 12, '"Continue, então, com suas palavras mágicas de encantamento e com suas muitas feitiçarias, nas quais você tem se afadigado desde a infância. Talvez você consiga, talvez provoque pavor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18613, 'nvi', 'Isaías', 'is', 47, 13, 'Todos os conselhos que você recebeu só a extenuaram! Deixe seus astrólogos se apresentarem, aqueles fitadores de estrelas que fazem predições de mês a mês, que eles a salvem daquilo que está vindo sobre você;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18614, 'nvi', 'Isaías', 'is', 47, 14, 'sem dúvida eles são como restolho, o fogo os consumirá. Eles não podem nem mesmo salvar-se do poder das chamas. Aqui não existem brasas para aquecer ninguém; não há fogueira para sentar-se ao lado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18615, 'nvi', 'Isaías', 'is', 47, 15, 'Isso é tudo o que eles podem fazer por você, esses com quem você se afadigou e com quem teve negócios excusos desde a infância. Cada um deles prossegue em seu erro; não há ninguém que possa salvá-la.');
