-- Inserções para Isaías 21
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18037, 'nvi', 'Isaías', 'is', 21, 1, 'Advertência contra o deserto junto ao mar: Como um vendaval em redemoinhos que varre todo o Neguebe, um invasor vem do deserto, de uma terra pavorosa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18038, 'nvi', 'Isaías', 'is', 21, 2, 'Eu tive uma visão terrível: O traidor fora traído, o saqueador saqueado. Elão, vá à luta! Média, feche o cerco! Pois, ponho fim a todo gemido que ela provocou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18039, 'nvi', 'Isaías', 'is', 21, 3, 'Diante disso fiquei tomado de angústia, Tive dores como as de uma mulher em trabalho de parto; estou tão transtornado que não posso ouvir, tão atônito que não posso ver.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18040, 'nvi', 'Isaías', 'is', 21, 4, 'O meu coração se estremece, o temor toma conta de mim; o anoitecer que tanto aguardava transformou-se em terror para mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18041, 'nvi', 'Isaías', 'is', 21, 5, 'Eles põem as mesas, estendem a toalha, comem, bebem! Levantem-se, líderes, preparem os escudos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18042, 'nvi', 'Isaías', 'is', 21, 6, 'Assim me diz o Senhor: "Vá, coloque um vigia de prontidão para que anuncie tudo o que se aproximar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18043, 'nvi', 'Isaías', 'is', 21, 7, 'Quando ele vir carros com parelhas de cavalos, homens montados em jumentos ou em camelos, fique alerta, bem alerta".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18044, 'nvi', 'Isaías', 'is', 21, 8, 'Então o vigia gritou: "Dia após dia, meu senhor, eu fico na torre de vigia; todas as noites permaneço em meu posto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18045, 'nvi', 'Isaías', 'is', 21, 9, 'Veja! Ali vem um homem num carro com uma parelha de cavalos. E ele responde: ‘Caiu! A Babilônia caiu! Todas as imagens dos seus deuses estão despedaçados no chão! ’ "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18046, 'nvi', 'Isaías', 'is', 21, 10, 'Ah, meu povo malhado na eira! Eu lhes conto o que ouvi da parte do Senhor dos Exércitos, da parte do Deus de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18047, 'nvi', 'Isaías', 'is', 21, 11, 'Advertência contra Dumá: Alguém de Seir me pergunta: "Guarda, quanto ainda falta para acabar a noite? Guarda, quanto falta para acabar a noite? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18048, 'nvi', 'Isaías', 'is', 21, 12, 'O guarda responde: "Logo chega o dia mas a noite também vem. Se vocês quiserem perguntar de novo, voltem e perguntem".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18049, 'nvi', 'Isaías', 'is', 21, 13, 'Advertência contra a Arábia: Vocês, caravanas de dedanitas, que acampam nos bosques da Arábia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18050, 'nvi', 'Isaías', 'is', 21, 14, 'tragam água para os sedentos; vocês, que vivem em Temá, tragam comida para os fugitivos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18051, 'nvi', 'Isaías', 'is', 21, 15, 'Eles fogem da espada, da espada desembainhada, do arco preparado e da crueldade da batalha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18052, 'nvi', 'Isaías', 'is', 21, 16, 'Assim me diz o Senhor: "Dentro de um ano, e nem um dia a mais, toda a pompa de Quedar chegará ao fim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18053, 'nvi', 'Isaías', 'is', 21, 17, 'Poucos serão os sobreviventes dos flecheiros, dos guerreiros de Quedar". O Senhor, o Deus de Israel, falou.');
