-- Inserções para Isaías 23
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18079, 'nvi', 'Isaías', 'is', 23, 1, 'Advertência contra Tiro: Pranteiem, navios de Társis! Pois Tiro foi destruída e ficou sem casa e sem porto. De Chipre lhe veio essa mensagem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18080, 'nvi', 'Isaías', 'is', 23, 2, 'Fiquem calados, habitantes das regiões litorâneas, e vocês, mercadores de Sidom, enriquecidos pelos que atravessam o mar');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18081, 'nvi', 'Isaías', 'is', 23, 3, 'e as grandes águas. O trigo de Sior e a colheita do Nilo eram a sua renda, e vocês se tornaram o suprimento das nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18082, 'nvi', 'Isaías', 'is', 23, 4, 'Envergonhe-se, Sidom, pois o mar, a fortaleza do mar, falou: "Não estive em trabalho de parto nem dei à luz; não criei filhos nem eduquei filhas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18083, 'nvi', 'Isaías', 'is', 23, 5, 'Quando a notícia chegar ao Egito, ficarão angustiados com as novidades de Tiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18084, 'nvi', 'Isaías', 'is', 23, 6, 'Cruzem o mar para Társis; pranteiem, vocês, habitantes das regiões litorâneas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18085, 'nvi', 'Isaías', 'is', 23, 7, 'É esta a cidade jubilosa que existe desde tempos muito antigos, cujos pés levaram a conquistar terras distantes?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18086, 'nvi', 'Isaías', 'is', 23, 8, 'Quem planejou isso contra Tiro, contra aquela que dava coroas, cujos comerciantes são príncipes, cujos negociantes são famosos em toda terra?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18087, 'nvi', 'Isaías', 'is', 23, 9, 'O Senhor dos Exércitos o planejou para abater todo orgulho e vaidade e humilhar todos os que tem fama na terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18088, 'nvi', 'Isaías', 'is', 23, 10, 'Cultive a sua terra como se cultiva as margens do Nilo, ó povo de Társis, pois você não tem mais porto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18089, 'nvi', 'Isaías', 'is', 23, 11, 'O Senhor estendeu a mão sobre o mar e fez tremer seus reinos. Acerca da Fenícia ordenou que as suas fortalezas sejam destruídas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18090, 'nvi', 'Isaías', 'is', 23, 12, 'e disse: "Você não se alegrará mais, ó cidade de Sidom, virgem derrotada! "Levante-se, atravesse o mar até Chipre; nem lá você terá descanso".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18091, 'nvi', 'Isaías', 'is', 23, 13, 'Olhem para a terra dos babilônios, esse é o povo que não existe mais! Os assírios o deixaram para as criaturas do deserto; ergueram torres de vigia, despojaram suas cidadelas e fizeram dela uma ruína.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18092, 'nvi', 'Isaías', 'is', 23, 14, 'Pranteiem, vocês, navios de Társis; destruída está a sua fortaleza!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18093, 'nvi', 'Isaías', 'is', 23, 15, 'Naquele tempo Tiro será esquecida por setenta anos, o tempo da vida de um rei. Mas no fim dos setenta anos, acontecerá com Tiro o que diz a canção da prostituta:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18094, 'nvi', 'Isaías', 'is', 23, 16, '"Pegue a harpa, vá pela cidade, ó prostituta esquecida; toque a harpa, cante muitas canções, para se lembrarem de você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18095, 'nvi', 'Isaías', 'is', 23, 17, 'No fim dos setenta anos o Senhor se lembrará de Tiro. Esta voltará ao seu ofício de prostituta e servirá a todos os reinos que há na face da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18096, 'nvi', 'Isaías', 'is', 23, 18, 'Mas o seu lucro e a sua renda serão separados para o Senhor; não serão guardados nem depositados. Seus lucros irão para os que vivem na presença do Senhor, para que tenham bastante comida e roupas finas.');
