-- Inserções para Isaías 35
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18322, 'nvi', 'Isaías', 'is', 35, 1, 'O deserto e a terra ressequida se regozijarão; o ermo exultará e florescerá como a tulipa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18323, 'nvi', 'Isaías', 'is', 35, 2, 'irromperá em flores, mostrará grande regozijo e cantará de alegria. A glória do Líbano lhe será dada, como também o resplendor do Carmelo e de Sarom; verão a glória do Senhor, o resplendor do nosso Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18324, 'nvi', 'Isaías', 'is', 35, 3, 'Fortaleçam as mãos cansadas, firmem os joelhos vacilantes;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18325, 'nvi', 'Isaías', 'is', 35, 4, 'digam aos desanimados de coração: "Sejam fortes, não temam! Seu Deus virá, virá com vingança; com divina retribuição virá para salvá-los".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18326, 'nvi', 'Isaías', 'is', 35, 5, 'Então se abrirão os olhos dos cegos e se destaparão os ouvidos dos surdos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18327, 'nvi', 'Isaías', 'is', 35, 6, 'Então os coxos saltarão como o cervo, e a língua do mudo cantará de alegria. Águas irromperão no ermo e riachos no deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18328, 'nvi', 'Isaías', 'is', 35, 7, 'A areia abrasadora se tornará um lago; a terra seca, fontes borbulhantes. Nos antros onde outrora havia chacais, crescerão a relva, o junco e o papiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18329, 'nvi', 'Isaías', 'is', 35, 8, 'E ali haverá uma grande estrada, um caminho que será chamado Caminho de Santidade. Os impuros não passarão por ele; servirá apenas aos que são do Caminho; os insensatos não o tomarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18330, 'nvi', 'Isaías', 'is', 35, 9, 'Ali não haverá leão algum, e nenhum animal feroz passará por ele; não se acharão ali. Só os redimidos andarão por ele,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18331, 'nvi', 'Isaías', 'is', 35, 10, 'e os que o Senhor resgatou voltarão. Entrarão em Sião com cantos de alegria; duradoura alegria coroará suas cabeças. Júbilo e alegria se apoderarão deles, e a tristeza e o suspiro fugirão.');
