-- Inserções para Isaías 64
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18887, 'nvi', 'Isaías', 'is', 64, 1, 'Ah, se rompesses os céus e descesses! Os montes tremeriam diante de ti!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18888, 'nvi', 'Isaías', 'is', 64, 2, 'Como quando o fogo acende os gravetos e faz a água ferver, desce, para que os teus inimigos conheçam o teu nome e as nações tremam diante de ti!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18889, 'nvi', 'Isaías', 'is', 64, 3, 'Pois, quando fizeste coisas tremendas, coisas que não esperávamos, desceste, e os montes tremeram diante de ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18890, 'nvi', 'Isaías', 'is', 64, 4, 'Desde os tempos antigos ninguém ouviu, nenhum ouvido percebeu, e olho nenhum viu outro Deus, além de ti, que trabalha para aqueles que nele esperam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18891, 'nvi', 'Isaías', 'is', 64, 5, 'Vens ajudar aqueles que praticam a justiça com alegria, que se lembram de ti e dos teus caminhos. Mas, prosseguindo nós em nossos pecados, tu te iraste. Como, então, seremos salvos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18892, 'nvi', 'Isaías', 'is', 64, 6, 'Somos como o impuro — todos nós! Todos os nossos atos de justiça são como trapo imundo. Murchamos como folhas, e como o vento as nossas iniqüidades nos levam para longe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18893, 'nvi', 'Isaías', 'is', 64, 7, 'Não há ninguém que clame pelo teu nome, que se anime a apegar-se a ti, pois escondeste de nós o teu rosto e nos deixaste perecer por causa das nossas iniqüidades.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18894, 'nvi', 'Isaías', 'is', 64, 8, 'Contudo, Senhor, tu és o nosso Pai. Nós somos o barro; tu és o oleiro. Todos nós somos obra das tuas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18895, 'nvi', 'Isaías', 'is', 64, 9, 'Não te ires demais, ó Senhor! Não te lembres constantemente das nossas maldades. Olha para nós! Somos o teu povo!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18896, 'nvi', 'Isaías', 'is', 64, 10, 'As tuas cidades sagradas transformaram-se em deserto. Até Sião virou um deserto, e Jerusalém, uma desolação!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18897, 'nvi', 'Isaías', 'is', 64, 11, 'O nosso templo santo e glorioso, onde os nossos antepassados te louvavam, foi destruído pelo fogo, e tudo o que nos era precioso está em ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18898, 'nvi', 'Isaías', 'is', 64, 12, 'e depois disso tudo, Senhor, ainda irás te conter? Ficarás calado e nos castigarás além da conta?');
