-- Inserções para Isaías 34
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18305, 'nvi', 'Isaías', 'is', 34, 1, 'Aproximem-se, nações, e escutem: prestem atenção, ó povos! Que o ouçam a terra e tudo o que nela há, o mundo e tudo o que dele procede!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18306, 'nvi', 'Isaías', 'is', 34, 2, 'O Senhor está indignado contra todas as nações; sua ira está contra todos os seus exércitos. Ele os destruirá totalmente, ele os entregará à matança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18307, 'nvi', 'Isaías', 'is', 34, 3, 'Seus mortos serão lançados fora e os seus cadáveres exalarão mau cheiro; os montes se encharcarão do sangue deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18308, 'nvi', 'Isaías', 'is', 34, 4, 'As estrelas dos céus serão todas dissolvidas, e os ceús se enrolarão como um pergaminho; todo o exército celeste cairá como folhas secas da videira e da figueira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18309, 'nvi', 'Isaías', 'is', 34, 5, 'Quando minha espada embriagar-se nos céus, saibam que ela descerá para julgar Edom, povo que condenei à destruição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18310, 'nvi', 'Isaías', 'is', 34, 6, 'A espada do Senhor está banhada em sangue, está coberta de gordura, sangue de cordeiros e de bodes, gordura dos rins de carneiros. Pois o Senhor exige sacrifício em Bozra e grande matança em Edom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18311, 'nvi', 'Isaías', 'is', 34, 7, 'E os bois selvagens cairão com eles, e os novilhos com os touros. A terra deles ficará ensopada de sangue, e o pó se encharcará de gordura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18312, 'nvi', 'Isaías', 'is', 34, 8, 'Pois o Senhor terá seu dia de vingança, um ano de retribuição, para defender a causa de Sião.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18313, 'nvi', 'Isaías', 'is', 34, 9, 'Os riachos de Edom se transformarão em piche, em enxofre, o seu pó; sua terra se tornará betume ardente!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18314, 'nvi', 'Isaías', 'is', 34, 10, 'Não se apagará de dia nem de noite; sua fumaça subirá para sempre. De geração em geração ficará abandonada; ninguém voltará a passar por ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18315, 'nvi', 'Isaías', 'is', 34, 11, 'A coruja-do-deserto e a coruja estridente a possuirão; o corujão e o corvo farão nela os seus ninhos. Deus estenderá sobre Edom o caos como linha de medir, e a desolação como fio de prumo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18316, 'nvi', 'Isaías', 'is', 34, 12, 'Seus nobres nada terão ali que possa chamar-se reino, e todos os seus líderes desaparecerão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18317, 'nvi', 'Isaías', 'is', 34, 13, 'Espinhos tomarão de assalto as suas cidadelas; urtigas e sarças cobrirão as suas fortalezas. Será um antro de chacais e moradia de corujas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18318, 'nvi', 'Isaías', 'is', 34, 14, 'Criaturas do deserto se encontrarão com hienas, e bodes selvagens balirão uns para os outros; ali também descansarão as criaturas noturnas e acharão para si locais de descanso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18319, 'nvi', 'Isaías', 'is', 34, 15, 'Nela a coruja fará ninho, chocará seus ovos e cuidará dos seus filhotes à sombra de suas asas; os falcões também se ajuntarão ali, cada um com o seu par.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18320, 'nvi', 'Isaías', 'is', 34, 16, 'Procurem no livro do Senhor e leiam: Nenhum deles estará faltando; nenhum estará sem o seu par. Pois foi a sua boca que deu a ordem, e o seu Espírito os ajuntará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18321, 'nvi', 'Isaías', 'is', 34, 17, 'Ele designa as porções de cada um; sua mão os distribui por medida. Eles se apossarão dela para sempre, e ali habitarão de geração em geração.');
