-- Inserções para Isaías 53
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18713, 'nvi', 'Isaías', 'is', 53, 1, 'Quem creu em nossa mensagem e a quem foi revelado o braço do Senhor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18714, 'nvi', 'Isaías', 'is', 53, 2, 'Ele cresceu diante dele como um broto tenro, e como uma raiz saída de uma terra seca. Ele não tinha qualquer beleza ou majestade que nos atraísse, nada em sua aparência para que o desejássemos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18715, 'nvi', 'Isaías', 'is', 53, 3, 'Foi desprezado e rejeitado pelos homens, um homem de tristeza e familiarizado com o sofrimento. Como alguém de quem os homens escondem o rosto, foi desprezado, e nós não o tínhamos em estima.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18716, 'nvi', 'Isaías', 'is', 53, 4, 'Certamente ele tomou sobre si as nossas enfermidades e sobre si levou as nossas doenças, contudo nós o consideramos castigado por Deus, por ele atingido e afligido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18717, 'nvi', 'Isaías', 'is', 53, 5, 'Mas ele foi transpassado por causa das nossas transgressões, foi esmagado por causa de nossas iniqüidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18718, 'nvi', 'Isaías', 'is', 53, 6, 'Todos nós, tal qual ovelhas, nos desviamos, cada um de nós se voltou para o seu próprio caminho; e o Senhor fez cair sobre ele a iniqüidade de todos nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18719, 'nvi', 'Isaías', 'is', 53, 7, 'Ele foi oprimido e afligido, contudo não abriu a sua boca; como um cordeiro foi levado para o matadouro, e como uma ovelha que diante de seus tosquiadores fica calada, ele não abriu a sua boca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18720, 'nvi', 'Isaías', 'is', 53, 8, 'Com julgamento opressivo ele foi levado. E quem pode falar dos seus descendentes? Pois ele foi eliminado da terra dos viventes; por causa da transgressão do meu povo ele foi golpeado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18721, 'nvi', 'Isaías', 'is', 53, 9, 'Foi-lhe dado um túmulo com os ímpios, e com os ricos em sua morte, embora não tivesse cometido qualquer violência nem houvesse qualquer mentira em sua boca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18722, 'nvi', 'Isaías', 'is', 53, 10, 'Contudo foi da vontade do Senhor esmagá-lo e fazê-lo sofrer, e, embora o Senhor faça da vida dele uma oferta pela culpa, ele verá sua prole e prolongará seus dias, e a vontade do Senhor prosperará em sua mão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18723, 'nvi', 'Isaías', 'is', 53, 11, 'Depois do sofrimento de sua alma, ele verá a luz e ficará satisfeito; pelo seu conhecimento meu servo justo justificará a muitos, e levará a iniqüidade deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18724, 'nvi', 'Isaías', 'is', 53, 12, 'Por isso eu lhe darei uma porção entre os grandes, e ele dividirá os despojos com os fortes, porquanto ele derramou sua vida até à morte, e foi contado entre os transgressores. Pois ele carregou o pecado de muitos, e intercedeu pelos transgressores.');
