-- Inserções para Isaías 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17771, 'nvi', 'Isaías', 'is', 6, 1, 'No ano em que o rei Uzias morreu, eu vi o Senhor assentado num trono alto e exaltado, e a aba de sua veste enchia o templo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17772, 'nvi', 'Isaías', 'is', 6, 2, 'Acima dele estavam serafins; cada um deles tinha seis asas: com duas cobriam o rosto, com duas cobriam os pés, e com duas voavam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17773, 'nvi', 'Isaías', 'is', 6, 3, 'E proclamavam uns aos outros: "Santo, santo, santo é o Senhor dos Exércitos, a terra inteira está cheia da sua glória".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17774, 'nvi', 'Isaías', 'is', 6, 4, 'Ao som das suas vozes os batentes das portas tremeram, e o templo ficou cheio de fumaça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17775, 'nvi', 'Isaías', 'is', 6, 5, 'Então gritei: Ai de mim! Estou perdido! Pois sou um homem de lábios impuros e vivo no meio de um povo de lábios impuros; e os meus olhos viram o Rei, o Senhor dos Exércitos! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17776, 'nvi', 'Isaías', 'is', 6, 6, 'Então um dos serafins voou até mim trazendo uma brasa viva, que havia tirado do altar com uma tenaz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17777, 'nvi', 'Isaías', 'is', 6, 7, 'Com ela tocou a minha boca e disse: "Veja, isto tocou os seus lábios; por isso, a sua culpa será removida, e o seu pecado será perdoado".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17778, 'nvi', 'Isaías', 'is', 6, 8, 'Então ouvi a voz do Senhor, conclamando: "Quem enviarei? Quem irá por nós? " E eu respondi: "Eis-me aqui. Envia-me! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17779, 'nvi', 'Isaías', 'is', 6, 9, 'Ele disse: "Vá, e diga a este povo: "Estejam sempre ouvindo, mas nunca entendam; estejam sempre vendo, e jamais percebam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17780, 'nvi', 'Isaías', 'is', 6, 10, 'Torne insensível o coração desse povo; torne surdos os ouvidos dele e feche os seus olhos. Que eles não vejam com os olhos, não ouçam com os ouvidos, e não entendam com o coração, para que não se convertam e sejam curados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17781, 'nvi', 'Isaías', 'is', 6, 11, 'Então eu perguntei: "Até quando, Senhor? " E ele respondeu: "Até que as cidades estejam em ruínas e sem habitantes, até que as casas fiquem abandonadas e os campos estejam totalmente devastados,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17782, 'nvi', 'Isaías', 'is', 6, 12, 'até que o Senhor tenha enviado todos para longe e a terra esteja totalmente desolada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17783, 'nvi', 'Isaías', 'is', 6, 13, 'E ainda que um décimo fique no país, esses também serão destruídos. Mas, assim como o terebinto e o carvalho deixam o tronco quando são derrubados, assim a santa semente será o seu tronco".');
