-- Inserções para Isaías 58
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18788, 'nvi', 'Isaías', 'is', 58, 1, '"Grite alto, não se contenha! Levante a voz como trombeta. Anuncie ao meu povo a rebelião dele, e à comunidade de Jacó, os seus pecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18789, 'nvi', 'Isaías', 'is', 58, 2, 'Pois dia a dia me procuram; parecem desejosos de conhecer os meus caminhos, como se fossem uma nação que faz o que é direito e que não abandonou os mandamentos do seu Deus. Pedem-me decisões justas e parecem desejosos de que Deus se aproxime deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18790, 'nvi', 'Isaías', 'is', 58, 3, '‘Por que jejuamos’, dizem, ‘e não o viste? Por que nos humilhamos, e não reparaste? ’ Contudo, no dia do seu jejum vocês fazem o que é do agrado de vocês, e exploram os seus empregados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18791, 'nvi', 'Isaías', 'is', 58, 4, 'Seu jejum termina em discussão e rixa, e em brigas de socos brutais. Vocês não podem jejuar como fazem hoje e esperar que a sua voz seja ouvida no alto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18792, 'nvi', 'Isaías', 'is', 58, 5, 'Será esse o jejum que escolhi, que apenas um dia o homem se humilhe, incline a cabeça como o junco e se deite sobre pano de saco e cinzas? É isso que vocês chamam jejum, um dia aceitável ao Senhor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18793, 'nvi', 'Isaías', 'is', 58, 6, '"O jejum que desejo não é este: soltar as correntes da injustiça, desatar as cordas do jugo, pôr em liberdade os oprimidos e romper todo jugo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18794, 'nvi', 'Isaías', 'is', 58, 7, 'Não é partilhar sua comida com o faminto, abrigar o pobre desamparado, vestir o nu que você encontrou, e não recusar ajuda ao próximo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18795, 'nvi', 'Isaías', 'is', 58, 8, 'Aí sim, a sua luz irromperá como a alvorada, e prontamente surgirá a sua cura; a sua retidão irá adiante de você, e a glória do Senhor estará na sua retaguarda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18796, 'nvi', 'Isaías', 'is', 58, 9, 'Aí sim, você clamará ao Senhor, e ele responderá; você gritará por socorro, e ele dirá: Aqui estou. "Se você eliminar do seu meio o jugo opressor, o dedo acusador e a falsidade do falar;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18797, 'nvi', 'Isaías', 'is', 58, 10, 'se com renúncia própria você beneficiar os famintos e satisfizer o anseio dos aflitos, então a sua luz despontará nas trevas, e a sua noite será como o meio-dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18798, 'nvi', 'Isaías', 'is', 58, 11, 'O Senhor o guiará constantemente; satisfará os seus desejos numa terra ressequida pelo sol e fortalecerá os seus ossos. Você será como um jardim bem regado, como uma fonte cujas águas nunca faltam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18799, 'nvi', 'Isaías', 'is', 58, 12, 'Seu povo reconstruirá as velhas ruínas e restaurará os alicerces antigos; você será chamado reparador de muros, restaurador de ruas e moradias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18800, 'nvi', 'Isaías', 'is', 58, 13, '"Se você vigiar seus pés para não profanar o sábado e para não fazer o que bem quiser em meu santo dia; se você chamar delícia o sábado e honroso o santo dia do Senhor, e se honrá-lo, deixando de seguir seu próprio caminho, de fazer o que bem quiser e de falar futilidades,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18801, 'nvi', 'Isaías', 'is', 58, 14, 'então você terá no Senhor a sua alegria, e eu farei com que você cavalgue nos altos da terra e se banqueteie com a herança de Jacó, seu pai. " Pois é o Senhor quem fala.');
