-- Inserções para Isaías 27
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18153, 'nvi', 'Isaías', 'is', 27, 1, 'Naquele dia, o Senhor com sua espada severa, longa e forte, castigará o Leviatã, serpente veloz, o Leviatã, serpente tortuosa; matará no mar a serpente aquática.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18154, 'nvi', 'Isaías', 'is', 27, 2, 'Naquele dia, cantem sobre a vinha frutífera:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18155, 'nvi', 'Isaías', 'is', 27, 3, '"Eu, o Senhor, sou o seu vigia, rego-a constantemente e a protejo dia e noite para impedir que lhe façam dano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18156, 'nvi', 'Isaías', 'is', 27, 4, 'Não estou irado. Se espinheiros e roseiras bravas me enfrentassem, eu marcharia contra eles em combate e poria fogo neles todos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18157, 'nvi', 'Isaías', 'is', 27, 5, 'Se não, que venham buscar refúgio em mim; que façam as pazes comigo. Sim, que façam as pazes comigo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18158, 'nvi', 'Isaías', 'is', 27, 6, 'Nos dias vindouros Jacó lançará raízes, Israel terá botões e flores e encherá o mundo de frutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18159, 'nvi', 'Isaías', 'is', 27, 7, 'Acaso o Senhor o feriu como feriu aqueles que o feriram? Acaso ele foi morto como foram mortos os que o feriram?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18160, 'nvi', 'Isaías', 'is', 27, 8, 'Pelo desterro e pelo exílio o julga, com seu sopro violento ele o expulsa, como num dia de rajadas do vento oriental.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18161, 'nvi', 'Isaías', 'is', 27, 9, 'Assim será perdoada a maldade de Jacó, e será este o fruto da remoção do seu pecado: Quando ele fizer com que as pedras do altar sejam esmigalhadas e fiquem como pó de giz, os postes sagrados e os altares de incenso não ficarão de pé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18162, 'nvi', 'Isaías', 'is', 27, 10, 'A cidade fortificada está abandonada, desabitada e esquecida como o deserto; ali os bezerros pastam e se deitam, e desfolham os seus ramos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18163, 'nvi', 'Isaías', 'is', 27, 11, 'Quando os seus ramos estão secos e quebram-se, as mulheres fazem fogo com eles, pois esse é um povo sem entendimento. Por isso aquele que o fez não tem compaixão dele, aquele que o formou não lhe mostra misericórdia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18164, 'nvi', 'Isaías', 'is', 27, 12, 'Naquele dia o Senhor debulhará desde as margens do Eufrates até o ribeiro do Egito, e vocês, israelitas, serão ajuntados um a um.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18165, 'nvi', 'Isaías', 'is', 27, 13, 'E naquele dia soará uma grande trombeta. Os que estavam perecendo na Assíria e os que estavam exilados no Egito virão e adorarão o Senhor no monte santo, em Jerusalém.');
