-- Inserções para Isaías 15
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17962, 'nvi', 'Isaías', 'is', 15, 1, 'Advertência contra Moabe: Sim, na noite em que foi destruída, Ar, em Moabe, ficou arruinada! E na noite em que foi destruída, Quir, em Moabe, ficou arruinada!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17963, 'nvi', 'Isaías', 'is', 15, 2, 'Sobe-se ao templo em Dibom, a seus altares idólatras, para chorar; Por causa de Nebo e de Medeba Moabe pranteia. Todas as cabeças estão rapadas e toda barba foi cortada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17964, 'nvi', 'Isaías', 'is', 15, 3, 'Nas ruas andam vestidos de roupas de lamento; nos terraços e nas praças públicas todos pranteiam e se prostram chorando.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17965, 'nvi', 'Isaías', 'is', 15, 4, 'Hesbom e Eleale clamam; até Jaaz as suas vozes são ouvidas. Por isso os homens armados de Moabe gritam, e o coração deles treme.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17966, 'nvi', 'Isaías', 'is', 15, 5, 'O meu coração clama por causa de Moabe! Os seus fugitivos vão até Zoar, até Eglate-Selisia. Sobem pelo caminho de Luíte, caminhando e chorando. Pela estrada de Horonaim levantam clamor em face da destruição,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17967, 'nvi', 'Isaías', 'is', 15, 6, 'porque as águas de Ninrim secaram-se, a pastagem secou-se e a vegetação morreu; todo o verde desapareceu!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17968, 'nvi', 'Isaías', 'is', 15, 7, 'Por isso, a riqueza que adquiriram e armazenaram eles levam para além do riacho dos Salgueiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17969, 'nvi', 'Isaías', 'is', 15, 8, 'Com efeito, seu clamor espalha-se por todo o território de Moabe; sua lamentação até Eglaim, até Beer-Elim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17970, 'nvi', 'Isaías', 'is', 15, 9, 'Ainda que as águas de Dimom estejam cheias de sangue, trarei mais mal sobre Dimom; um leão sobre os fugitivos de Moabe e sobre aqueles que permanecem na terra.');
