-- Inserções para Isaías 54
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18725, 'nvi', 'Isaías', 'is', 54, 1, '"Cante, ó estéril, você que nunca teve um filho; irrompa em canto, grite de alegria, você que nunca esteve em trabalho de parto; porque mais são os filhos da mulher abandonada do que os daquela que tem marido", diz o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18726, 'nvi', 'Isaías', 'is', 54, 2, '"Alargue o lugar de sua tenda, estenda bem as cortinas de sua tenda, não o impeça; estique suas cordas, firme suas estacas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18727, 'nvi', 'Isaías', 'is', 54, 3, 'Pois você se estenderá para a direita e para a esquerda; seus descendentes desapossarão nações e se instalarão em suas cidades abandonadas. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18728, 'nvi', 'Isaías', 'is', 54, 4, '"Não tenha medo; você não sofrerá vergonha. Não tema o constrangimento; você não será humilhada. Você esquecerá a vergonha de sua juventude e não se lembrará mais da humilhação de sua viuvez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18729, 'nvi', 'Isaías', 'is', 54, 5, 'Pois o seu Criador é o seu marido, o Senhor dos Exércitos é o seu nome, o Santo de Israel é seu Redentor; ele é chamado o Deus de toda a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18730, 'nvi', 'Isaías', 'is', 54, 6, 'O Senhor chamará você de volta como se você fosse uma mulher abandonada e aflita de espírito, uma mulher que se casou nova, apenas para ser rejeitada", diz o seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18731, 'nvi', 'Isaías', 'is', 54, 7, '"Por um breve instante eu a abandonei, mas com profunda compaixão eu a trarei de volta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18732, 'nvi', 'Isaías', 'is', 54, 8, 'Num impulso de indignação escondi de você por um instante o meu rosto, mas com bondade eterna terei compaixão de você", diz o Senhor, o seu Redentor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18733, 'nvi', 'Isaías', 'is', 54, 9, '"Para mim isso é como os dias de Noé, quando jurei que as águas de Noé nunca mais tornariam a cobrir a terra. De modo que agora jurei não ficar irado contra você, nem tornar a repreendê-la.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18734, 'nvi', 'Isaías', 'is', 54, 10, 'Embora os montes sejam sacudidos e as colinas sejam removidas, ainda assim a minha fidelidade para com você não será abalada, nem a minha aliança de paz será removida", diz o Senhor, que tem compaixão de você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18735, 'nvi', 'Isaías', 'is', 54, 11, '"Ó cidade aflita, açoitada por tempestades e não consolada, eu a edificarei com turquesas, edificarei seus alicerces com safiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18736, 'nvi', 'Isaías', 'is', 54, 12, 'Farei de rubis os seus escudos, de carbúnculos as suas portas, e de pedras preciosas todos os seus muros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18737, 'nvi', 'Isaías', 'is', 54, 13, 'Todos os seus filhos serão ensinados pelo Senhor, e grande será a paz de suas crianças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18738, 'nvi', 'Isaías', 'is', 54, 14, 'Em retidão você será estabelecida: A tirania estará distante; você não terá nada a temer. O pavor estará removido para longe; ele não se aproximará de você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18739, 'nvi', 'Isaías', 'is', 54, 15, 'Se alguém a atacar, não será por obra minha; todo aquele que a atacar se renderá a você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18740, 'nvi', 'Isaías', 'is', 54, 16, '"Veja, sou eu quem criou o ferreiro, que sopra as brasas até darem chama e forja uma arma própria para o seu fim. E fui eu quem criou o destruidor para gerar o caos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (18741, 'nvi', 'Isaías', 'is', 54, 17, 'nenhuma arma forjada contra você prevalecerá, e você refutará toda língua que a acusar. Esta é a herança dos servos do Senhor, e esta é a defesa que faço do nome deles", declara o Senhor.');
