-- Inserções para Isaías 11
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17886, 'nvi', 'Isaías', 'is', 11, 1, 'Um ramo surgirá do tronco de Jessé, e das suas raízes brotará um renovo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17887, 'nvi', 'Isaías', 'is', 11, 2, 'O Espírito do Senhor repousará sobre ele, o Espírito que dá sabedoria e entendimento, o Espírito que traz conselho e poder, o Espírito que dá conhecimento e temor do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17888, 'nvi', 'Isaías', 'is', 11, 3, 'E ele se inspirará no temor do Senhor. Não julgará pela aparência, nem decidirá com base no que ouviu;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17889, 'nvi', 'Isaías', 'is', 11, 4, 'mas com retidão julgará os necessitados, com justiça tomará decisões em favor dos pobres. Com suas palavras, como se fossem um cajado, ferirá a terra; com o sopro de sua boca matará os ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17890, 'nvi', 'Isaías', 'is', 11, 5, 'A retidão será a faixa de seu peito, e a fidelidade o seu cinturão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17891, 'nvi', 'Isaías', 'is', 11, 6, 'O lobo viverá com o cordeiro, o leopardo se deitará com o bode, o bezerro, o leão e o novilho gordo pastarão juntos; e uma criança os guiará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17892, 'nvi', 'Isaías', 'is', 11, 7, 'A vaca se alimentará com o urso, seus filhotes se deitarão juntos, e o leão comerá palha como o boi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17893, 'nvi', 'Isaías', 'is', 11, 8, 'A criancinha brincará perto do esconderijo da cobra, a criança colocará a mão no ninho da víbora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17894, 'nvi', 'Isaías', 'is', 11, 9, 'Ninguém fará nenhum mal, nem destruirá coisa alguma em todo o meu santo monte, pois a terra se encherá do conhecimento do Senhor como as águas cobrem o mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17895, 'nvi', 'Isaías', 'is', 11, 10, 'Naquele dia as nações buscarão a Raiz de Jessé, que será como uma bandeira para os povos, e o seu lugar de descanso será glorioso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17896, 'nvi', 'Isaías', 'is', 11, 11, 'Naquele dia o Senhor estenderá o braço pela segunda vez para reivindicar o remanescente do seu povo que for deixado na Assíria, no Egito, em Patros, na Etiópia, em Elão, em Sinear, em Hamate e nas ilhas do mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17897, 'nvi', 'Isaías', 'is', 11, 12, 'Ele erguerá uma bandeira para as nações a fim de reunir os exilados de Israel; ajuntará o povo disperso de Judá desde os quatro cantos da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17898, 'nvi', 'Isaías', 'is', 11, 13, 'O ciúme de Efraim desaparecerá, e a hostilidade de Judá será eliminada; Efraim não terá ciúme de Judá, nem Judá será hostil a Efraim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17899, 'nvi', 'Isaías', 'is', 11, 14, 'Eles se infiltrarão pelas encostas da Filístia, a oeste; juntos saquearão o povo do leste. Porão as mãos sobre Edom e Moabe, e os amonitas lhes estarão sujeitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17900, 'nvi', 'Isaías', 'is', 11, 15, 'O Senhor fará secar o golfo do mar do Egito; com um forte vento varrerá com a mão o Eufrates, e o dividirá em sete riachos, para que se possa atravessá-lo de sandálias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17901, 'nvi', 'Isaías', 'is', 11, 16, 'Haverá uma estrada para o remanescente do seu povo que for deixado na Assíria, como houve para Israel quando saiu do Egito.');
