-- Inserções para Jonas 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22533, 'nvi', 'Jonas', 'jn', 1, 1, 'A palavra do Senhor veio a Jonas, filho de Amitai com esta ordem:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22534, 'nvi', 'Jonas', 'jn', 1, 2, '"Vá depressa à grande cidade de Nínive e pregue contra ela, porque a sua maldade subiu até a minha presença".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22535, 'nvi', 'Jonas', 'jn', 1, 3, 'Mas Jonas fugiu da presença do Senhor, dirigindo-se para Társis. Desceu à cidade de Jope, onde encontrou um navio que se destinava àquele porto. Depois de pagar a passagem, embarcou para Társis, para fugir do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22536, 'nvi', 'Jonas', 'jn', 1, 4, 'O Senhor, porém, fez soprar um forte vento sobre o mar, e caiu uma tempestade tão violenta que o barco ameaçava arrebentar-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22537, 'nvi', 'Jonas', 'jn', 1, 5, 'Todos os marinheiros ficaram com medo e cada um clamava ao seu próprio deus. E atiraram as cargas ao mar para tornar mais leve o navio. Enquanto isso, Jonas, que tinha descido para o porão e se deitado, dormia profundamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22538, 'nvi', 'Jonas', 'jn', 1, 6, 'O capitão dirigiu-se a ele e disse: "Como você pode ficar aí dormindo? Levante-se e clame ao seu deus! Talvez ele tenha piedade de nós e não morramos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22539, 'nvi', 'Jonas', 'jn', 1, 7, 'Então os marinheiros combinaram entre si: "Vamos tirar sortes para descobrir quem é o responsável por esta desgraça que se abateu sobre nós". Tiraram sortes, e a sorte caiu sobre Jonas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22540, 'nvi', 'Jonas', 'jn', 1, 8, 'Por isso lhe perguntaram: "Diga-nos, quem é o responsável por esta calamidade? Qual é a sua profissão? De onde você vem? Qual é a sua terra? A que povo você pertence? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22541, 'nvi', 'Jonas', 'jn', 1, 9, 'Ele respondeu: "Eu sou hebreu, adorador do Senhor, o Deus dos céus, que fez o mar e a terra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22542, 'nvi', 'Jonas', 'jn', 1, 10, 'Com isso eles ficaram apavorados e perguntaram: "O que foi que você fez? ", pois sabiam que Jonas estava fugindo do Senhor, porque ele já lhes tinha dito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22543, 'nvi', 'Jonas', 'jn', 1, 11, 'Visto que o mar estava cada vez mais agitado, eles lhe perguntaram: "O que devemos fazer com você, para que o mar se acalme? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22544, 'nvi', 'Jonas', 'jn', 1, 12, 'Respondeu ele: "Peguem-me e joguem-me ao mar, e ele se acalmará. Pois eu sei que é por minha causa que esta violenta tempestade caiu sobre vocês".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22545, 'nvi', 'Jonas', 'jn', 1, 13, 'Ao invés disso, os homens se esforçaram ao máximo para remar de volta à terra. Mas não conseguiram, porque o mar tinha ficado ainda mais violento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22546, 'nvi', 'Jonas', 'jn', 1, 14, 'Então eles clamaram ao Senhor: "Senhor, nós suplicamos, não nos deixes morrer por tirarmos a vida deste homem. Não caia sobre nós a culpa de matar um inocente, porque tu, ó Senhor, fizeste o que desejavas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22547, 'nvi', 'Jonas', 'jn', 1, 15, 'Então, pegaram Jonas e o lançaram ao mar enfurecido, e este se aquietou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22548, 'nvi', 'Jonas', 'jn', 1, 16, 'Ao verem isso, os homens adoraram ao Senhor com temor, oferecendo-lhe sacrifício e fazendo-lhe votos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22549, 'nvi', 'Jonas', 'jn', 1, 17, 'Então o Senhor fez com que um grande peixe engolisse Jonas, e ele ficou dentro do peixe três dias e três noites.');
