-- Inserções para Jeremias 39
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19925, 'nvi', 'Jeremias', 'jr', 39, 1, 'Foi assim que Jerusalém foi tomada: No nono ano do reinado de Zedequias, rei de Judá, no décimo mês, Nabucodonosor, rei da Babilônia, marchou contra Jerusalém com todo seu exército e a sitiou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19926, 'nvi', 'Jeremias', 'jr', 39, 2, 'E no dia novo do quarto mês do décimo primeiro ano do reinado de Zedequias, o muro da cidade foi rompido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19927, 'nvi', 'Jeremias', 'jr', 39, 3, 'Então todos os oficiais do rei da Babilônia vieram e se assentaram junto à porta do Meio: Nergal-Sarezer de Sangar, Nebo-Sarsequim, um dos chefes dos oficiais, Nergal-Sarezer, um alto oficial, e todos os outros oficiais do rei da Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19928, 'nvi', 'Jeremias', 'jr', 39, 4, 'Quando Zedequias, rei de Judá, e todos os soldados os viram, fugiram e saíram da cidade, à noite, na direção do jardim real, pela porta entre os dois muros; e foram para a Arabá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19929, 'nvi', 'Jeremias', 'jr', 39, 5, 'Mas o exército babilônio os perseguiu e alcançou Zedequias na planície de Jericó. Eles o capturaram e o levaram a Nabucodonosor, rei da Babilônia, em Ribla, na terra de Hamate, que o sentenciou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19930, 'nvi', 'Jeremias', 'jr', 39, 6, 'Em Ribla, o rei da Babilônia mandou executar os filhos de Zedequias diante dos seus olhos, e também matou todos os nobres de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19931, 'nvi', 'Jeremias', 'jr', 39, 7, 'Mandou furar os olhos de Zedequias e prendê-lo com correntes de bronze para levá-lo para a Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19932, 'nvi', 'Jeremias', 'jr', 39, 8, 'Os babilônios incendiaram o palácio real e as casas do povo, e derrubaram os muros de Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19933, 'nvi', 'Jeremias', 'jr', 39, 9, 'Nebuzaradã, o comandante da guarda imperial, deportou para a Babilônia o povo que restou na cidade, juntamente com aqueles que tinham se rendido a ele, e o restante dos artesãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19934, 'nvi', 'Jeremias', 'jr', 39, 10, 'Somente alguns dos mais pobres do povo, que nada tinham, Nebuzaradã, o comandante da guarda imperial, deixou para trás em Judá. E, naquela ocasião, ele lhes deu vinhas e campos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19935, 'nvi', 'Jeremias', 'jr', 39, 11, 'Mas Nabucodonosor, rei da Babilônia, deu ordens a respeito de Jeremias a Nebuzaradã, o comandante da guarda imperial:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19936, 'nvi', 'Jeremias', 'jr', 39, 12, '"Vá buscá-lo e cuide bem dele; não o maltrate, mas faça o que ele pedir".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19937, 'nvi', 'Jeremias', 'jr', 39, 13, 'Então Nebuzaradã, o comandante da guarda imperial, Nebusazbã, um dos chefes dos oficiais, Nergal-Sarezer, um alto oficial, e todos os outros oficiais do rei da Babilônia');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19938, 'nvi', 'Jeremias', 'jr', 39, 14, 'mandaram tirar Jeremias do pátio da guarda e o entregaram a Gedalias, filho de Aicam, filho de Safã, para que o levasse à residência do governador. Assim, Jeremias permaneceu no meio do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19939, 'nvi', 'Jeremias', 'jr', 39, 15, 'Enquanto Jeremias esteve preso no pátio da guarda, o Senhor lhe dirigiu a palavra:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19940, 'nvi', 'Jeremias', 'jr', 39, 16, '"Vá dizer a Ebede-Meleque, o etíope: ‘Assim diz o Senhor dos Exércitos, Deus de Israel: Estou para cumprir as minhas advertências contra esta cidade, com desgraça e não com prosperidade. Naquele dia, elas se cumprirão diante dos seus olhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19941, 'nvi', 'Jeremias', 'jr', 39, 17, 'Mas eu o resgatarei naquele dia’, declara o Senhor; ‘você não será entregue nas mãos daqueles a quem teme.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19942, 'nvi', 'Jeremias', 'jr', 39, 18, 'Eu certamente o resgatarei; você não morrerá pela espada, mas escapará com vida, porque você confia em mim’ ", declara o Senhor.');
