-- Inserções para Jeremias 28
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19620, 'nvi', 'Jeremias', 'jr', 28, 1, 'No quinto mês daquele mesmo ano, o quarto ano, no início do reinado de Zedequias, rei de Judá, Hananias, filho de Azur, profeta natural de Gibeom, disse-me no templo do Senhor, na presença dos sacerdotes e de todo o povo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19621, 'nvi', 'Jeremias', 'jr', 28, 2, '"Assim diz o Senhor dos Exércitos, Deus de Israel: ‘Quebrarei o jugo do rei da Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19622, 'nvi', 'Jeremias', 'jr', 28, 3, 'Em dois anos trarei de volta a este lugar todos os utensílios do templo do Senhor que Nabucodonosor, rei da Babilônia, tirou daqui e levou para a Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19623, 'nvi', 'Jeremias', 'jr', 28, 4, 'Também trarei de volta para este lugar Joaquim, filho de Jeoaquim, rei de Judá, e todos os exilados de Judá que foram para a Babilônia’, diz o Senhor, ‘pois quebrarei o jugo do rei da Babilônia’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19624, 'nvi', 'Jeremias', 'jr', 28, 5, 'Então o profeta Jeremias respondeu ao profeta Hananias diante dos sacerdotes e de todo o povo que estava no templo do Senhor:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19625, 'nvi', 'Jeremias', 'jr', 28, 6, '"Amém! Que assim faça o Senhor! Que o Senhor cumpra as palavras que você profetizou, trazendo os utensílios do templo do Senhor e todos os exilados da Babilônia para este lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19626, 'nvi', 'Jeremias', 'jr', 28, 7, 'Entretanto, ouça o que tenho a dizer a você e a todo o povo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19627, 'nvi', 'Jeremias', 'jr', 28, 8, 'Os profetas que precederam a você e a mim, desde os tempos antigos, profetizaram guerra, desgraça e peste contra muitas nações e grandes reinos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19628, 'nvi', 'Jeremias', 'jr', 28, 9, 'Mas o profeta que profetiza prosperidade será reconhecido como verdadeiro enviado do Senhor se aquilo que profetizou se realizar".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19629, 'nvi', 'Jeremias', 'jr', 28, 10, 'Então o profeta Hananias tirou o jugo do pescoço de Jeremias e o quebrou,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19630, 'nvi', 'Jeremias', 'jr', 28, 11, 'e disse diante de todo o povo: "Assim diz o Senhor: ‘É deste modo que quebrarei o jugo de Nabucodonosor, rei da Babilônia, e o tirarei do pescoço de todas as nações no prazo de dois anos’ ". Diante disso, o profeta Jeremias retirou-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19631, 'nvi', 'Jeremias', 'jr', 28, 12, 'Depois que o profeta Hananias quebrou o jugo do pescoço do profeta Jeremias, o Senhor dirigiu a palavra a Jeremias:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19632, 'nvi', 'Jeremias', 'jr', 28, 13, '"Vá dizer a Hananias: ‘Assim diz o Senhor: Você quebrou um jugo de madeira, mas em seu lugar você fará um jugo de ferro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19633, 'nvi', 'Jeremias', 'jr', 28, 14, 'Assim diz o Senhor dos Exércitos, o Deus de Israel: Porei um jugo sobre o pescoço de todas essas nações, para fazê-las sujeitas a Nabucodonosor, rei da Babilônia, e elas se sujeitarão a ele. Até mesmo os animais selvagens estarão sujeitos a ele’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19634, 'nvi', 'Jeremias', 'jr', 28, 15, 'Disse, pois, o profeta Jeremias ao profeta Hananias: "Escute, Hananias! O Senhor não o enviou, mas assim mesmo você persuadiu esta nação a confiar em mentiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19635, 'nvi', 'Jeremias', 'jr', 28, 16, 'Por isso, assim diz Senhor: ‘Vou tirá-lo da face da terra. Este ano você morrerá, porque pregou rebelião contra o Senhor’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19636, 'nvi', 'Jeremias', 'jr', 28, 17, 'E o profeta Hananias morreu no sétimo mês daquele mesmo ano.');
