-- Inserções para Jeremias 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19409, 'nvi', 'Jeremias', 'jr', 19, 1, 'Assim diz o Senhor: "Vá comprar um vaso de barro de um oleiro. Leve com você alguns líderes do povo e alguns sacerdotes');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19410, 'nvi', 'Jeremias', 'jr', 19, 2, 'e vá em direção ao vale de Ben-Hinom, perto da entrada da porta dos Cacos. Proclame ali as palavras que eu lhe disser.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19411, 'nvi', 'Jeremias', 'jr', 19, 3, 'Diga: ‘Ouçam a palavra do Senhor, reis de Judá e habitantes de Jerusalém. Assim diz o Senhor dos Exércitos, Deus de Israel: Trarei desgraça tal sobre este lugar que fará retinir os ouvidos daqueles que ouvirem isso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19412, 'nvi', 'Jeremias', 'jr', 19, 4, 'Porque eles me abandonaram e profanaram este lugar, oferecendo sacrifícios a deuses estranhos, que nem eles nem seus antepassados nem os reis de Judá conheceram; e encheram este lugar com o sangue de inocentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19413, 'nvi', 'Jeremias', 'jr', 19, 5, 'Construíram nos montes os altares dedicados a Baal, para queimarem os seus filhos como holocaustos oferecidos a Baal, coisa que não ordenei, da qual nunca falei nem jamais me veio à mente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19414, 'nvi', 'Jeremias', 'jr', 19, 6, 'Por isso, certamente vêm os dias, declara o Senhor, em que não mais chamarão este lugar Tofete ou vale de Ben-Hinom, mas vale da Matança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19415, 'nvi', 'Jeremias', 'jr', 19, 7, '" ‘Esvaziarei neste lugar os planos de Judá e de Jerusalém: eu os farei morrer pela espada perante os seus inimigos, pelas mãos daqueles que os perseguem; e darei os seus cadáveres como comida para as aves e os animais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19416, 'nvi', 'Jeremias', 'jr', 19, 8, 'Farei com que esta cidade fique deserta e seja tema de zombaria. Todos os que por ela passarem ficarão chocados e zombarão de todos os seus ferimentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19417, 'nvi', 'Jeremias', 'jr', 19, 9, 'Eu farei com que comam a carne dos seus filhos e das suas filhas; e cada um comerá a carne do seu próximo, por causa do sofrimento que lhes infligirão durante o cerco feito pelos inimigos, os quais procuram tirar-lhes a vida’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19418, 'nvi', 'Jeremias', 'jr', 19, 10, '"Depois quebre o vaso de barro diante dos homens que o acompanharam,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19419, 'nvi', 'Jeremias', 'jr', 19, 11, 'e diga-lhes: ‘Assim diz o Senhor dos Exércitos: Assim como se quebra o vaso de oleiro, que não pode ser mais restaurado, quebrarei este povo e esta cidade, e os mortos em Tofete serão sepultados até que não haja mais lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19420, 'nvi', 'Jeremias', 'jr', 19, 12, 'Assim farei a este lugar e aos seus habitantes", declara o Senhor, "tornarei esta cidade como Tofete.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19421, 'nvi', 'Jeremias', 'jr', 19, 13, 'As casas de Jerusalém e os palácios reais de Judá serão profanados, como este lugar de Tofete: todas as casas em cujos terraços queimaram incenso a todos os corpos celestes, e derramaram ofertas de bebidas aos seus deuses estrangeiros’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19422, 'nvi', 'Jeremias', 'jr', 19, 14, 'Jeremias, voltou então de Tofete para onde o Senhor o mandara profetizar e, entrando no pátio do templo do Senhor, disse a todo o povo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19423, 'nvi', 'Jeremias', 'jr', 19, 15, '"Assim diz o Senhor dos Exércitos, o Deus de Israel: ‘Ouçam! Trarei sobre esta cidade, e sobre todos os povoados ao redor, todas as desgraças contra eles anunciadas, porque se obstinaram e não quiseram obedecer às minhas palavras’ ".');
