-- Inserções para Jeremias 43
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19999, 'nvi', 'Jeremias', 'jr', 43, 1, 'Quando Jeremias acabou de dizer ao povo tudo o que o Senhor, o seu Deus, lhe mandara dizer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20000, 'nvi', 'Jeremias', 'jr', 43, 2, 'Azarias, filho de Hosaías, e Joanã, filho de Careá, e todos os homens arrogantes disseram a Jeremias: "Você está mentindo! O Senhor não lhe mandou dizer que não fôssemos residir no Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20001, 'nvi', 'Jeremias', 'jr', 43, 3, 'Mas é Baruque, filho de Nerias, que o está instigando contra nós para que sejamos entregues nas mãos dos babilônios, a fim de que nos matem ou nos levem para o exílio na Babilônia".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20002, 'nvi', 'Jeremias', 'jr', 43, 4, 'Assim Joanã, filho de Careá, e todos os comandantes do exército e todo o povo desobedeceram à ordem do Senhor de que permanecessem na terra de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20003, 'nvi', 'Jeremias', 'jr', 43, 5, 'Mas Joanã, filho de Careá, e todos os comandantes do exército, levaram todo o remanescente de Judá que tinha voltado de todas as nações para onde haviam sido espalhados a fim de viver na terra de Judá:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20004, 'nvi', 'Jeremias', 'jr', 43, 6, 'todos os homens, mulheres e crianças, as filhas do rei, todos os que Nebuzaradã, o comandante da guarda imperial, deixara com Gedalias, filho de Aicam, neto de Safã; além do profeta Jeremias e de Baruque, filho de Nerias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20005, 'nvi', 'Jeremias', 'jr', 43, 7, 'Eles foram para o Egito, desobedecendo ao Senhor, e foram até Tafnes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20006, 'nvi', 'Jeremias', 'jr', 43, 8, 'Em Tafnes, o Senhor dirigiu a palavra a Jeremias, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20007, 'nvi', 'Jeremias', 'jr', 43, 9, '"Pegue algumas pedras grandes e, à vista dos homens de Judá, enterre-as no barro do pavimento na entrada do palácio do faraó, em Tafnes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20008, 'nvi', 'Jeremias', 'jr', 43, 10, 'Então diga-lhes: ‘Assim diz o Senhor dos Exércitos, Deus de Israel: Mandarei chamar meu servo Nabucodonosor, rei da Babilônia, e ele colocará o seu trono sobre essas pedras que enterrei, e estenderá a sua tenda real sobre elas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20009, 'nvi', 'Jeremias', 'jr', 43, 11, 'Ele virá e atacará o Egito, trará a morte aos destinados a morte, cativeiro aos destinados ao cativeiro, e espada aos destinados a morrer pela espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20010, 'nvi', 'Jeremias', 'jr', 43, 12, 'Ele incendiará os templos dos deuses do Egito; queimará seus templos e levará embora cativos os seus deuses. Como um pastor tira os piolhos do seu manto, assim ele despiolhará o seu Egito, e sairá em paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20011, 'nvi', 'Jeremias', 'jr', 43, 13, 'Ele despedaçará as colunas no templo do sol, no Egito, e incendiará os templos dos deuses do Egito’ ".');
