-- Inserções para Jeremias 21
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19442, 'nvi', 'Jeremias', 'jr', 21, 1, 'Esta é a palavra que veio a Jeremias da parte do Senhor, quando o rei Zedequias enviou-lhe Pasur, filho de Malquias, e o sacerdote Sofonias, filho de Maaséias. Eles disseram:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19443, 'nvi', 'Jeremias', 'jr', 21, 2, '"Consulte agora o Senhor por nós porque Nabucodonosor, rei da Babilônia, está nos atacando. Talvez o Senhor faça por nós uma de suas maravilhas e, assim, ele se retire de nós".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19444, 'nvi', 'Jeremias', 'jr', 21, 3, 'Jeremias, porém, respondeu-lhes: "Digam a Zedequias:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19445, 'nvi', 'Jeremias', 'jr', 21, 4, '‘Assim diz o Senhor, o Deus de Israel: Estou a ponto de voltar contra vocês as armas de guerra que estão em suas mãos, as quais vocês estão usando para combater o rei da Babilônia e os babilônios, os quais cercam vocês do lado de fora do muro. E eu os reunirei dentro desta cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19446, 'nvi', 'Jeremias', 'jr', 21, 5, 'Eu mesmo lutarei contra vocês com mão poderosa e braço forte, com ira, furor e grande indignação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19447, 'nvi', 'Jeremias', 'jr', 21, 6, 'Matarei os habitantes desta cidade, tanto homens como animais; eles morrerão de uma peste terrível.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19448, 'nvi', 'Jeremias', 'jr', 21, 7, 'Depois disso, declara o Senhor, entregarei Zedequias, rei de Judá, seus conselheiros e o povo desta cidade que sobreviver, à peste, à espada e à fome, e nas mãos de Nabucodonosor, rei da Babilônia, dos inimigos deles e daqueles que querem tirar-lhes a vida. Ele os matará à espada sem piedade nem misericórdia; não terá deles nenhuma compaixão’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19449, 'nvi', 'Jeremias', 'jr', 21, 8, '"Diga a este povo: ‘Assim diz o Senhor: Ponho diante de vocês o caminho da vida e o caminho da morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19450, 'nvi', 'Jeremias', 'jr', 21, 9, 'Todo aquele que ficar nesta cidade morrerá pela espada, pela fome ou pela peste. Mas todo o que sair e render-se aos babilônios, que os cercam vocês, viverá; este escapará com vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19451, 'nvi', 'Jeremias', 'jr', 21, 10, 'Decidi fazer o mal e não o bem a esta cidade, diz o Senhor. Ela será entregue nas mãos do rei da Babilônia, e ele a incendiará’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19452, 'nvi', 'Jeremias', 'jr', 21, 11, '"Digam à casa real de Judá: ‘Ouçam a palavra do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19453, 'nvi', 'Jeremias', 'jr', 21, 12, 'Ó dinastia de Davi, assim diz o Senhor: " ‘Administrem justiça cada manhã: livrem o explorado das mãos do opressor; se não a minha ira se acenderá e queimará como fogo inextinguível, por causa do mal que vocês têm feito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19454, 'nvi', 'Jeremias', 'jr', 21, 13, 'Eu estou contra você, Jerusalém! Você que está entronizada acima deste vale, na rocha do planalto, declara o Senhor, vocês que dizem: "Quem nos atacará? Quem poderá invadir nossas moradas? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (19455, 'nvi', 'Jeremias', 'jr', 21, 14, 'Eu os castigarei de acordo com as suas obras, diz o Senhor, Porei fogo em sua floresta, que consumirá tudo ao redor’ ".');
