-- Inserções para Josué 23
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6461, 'nvi', 'Josué', 'js', 23, 1, 'Passado muito tempo, depois que o Senhor concedeu a Israel descanso de todos os inimigos ao redor, Josué, agora velho, de idade muito avançada,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6462, 'nvi', 'Josué', 'js', 23, 2, 'convocou todo o Israel, com as autoridades, os líderes, os juízes e os oficiais, e lhes disse: "Estou velho, com idade muito avançada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6463, 'nvi', 'Josué', 'js', 23, 3, 'Vocês mesmos viram tudo o que o Senhor, o seu Deus, fez com todas essas nações por amor a vocês; foi o Senhor, o seu Deus, que lutou por vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6464, 'nvi', 'Josué', 'js', 23, 4, 'Lembrem-se de que eu reparti por herança para as tribos de vocês toda a terra das nações, tanto as que ainda restam como as que conquistei entre o Jordão e o mar Grande, a oeste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6465, 'nvi', 'Josué', 'js', 23, 5, 'O Senhor, o seu Deus, as expulsará da presença de vocês. Ele as empurrará de diante de vocês, e vocês se apossarão da terra delas, como o Senhor lhes prometeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6466, 'nvi', 'Josué', 'js', 23, 6, '"Façam todo o esforço para obedecer e cumprir tudo o que está escrito no Livro da Lei de Moisés, sem se desviar, nem para a direita nem para a esquerda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6467, 'nvi', 'Josué', 'js', 23, 7, 'Não se associem com essas nações que restam no meio de vocês. Não invoquem os nomes dos seus deuses nem jurem por eles. Não lhes prestem culto nem se inclinem perante eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6468, 'nvi', 'Josué', 'js', 23, 8, 'Mas apeguem-se somente ao Senhor, ao seu Deus, como fizeram até hoje.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6469, 'nvi', 'Josué', 'js', 23, 9, '"O Senhor expulsou de diante de vocês nações grandes e poderosas; até hoje ninguém conseguiu resistir a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6470, 'nvi', 'Josué', 'js', 23, 10, 'Um só de vocês faz fugir mil, pois o Senhor, o seu Deus, luta por vocês, conforme prometeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6471, 'nvi', 'Josué', 'js', 23, 11, 'Por isso dediquem-se com zelo a amar o Senhor, o seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6472, 'nvi', 'Josué', 'js', 23, 12, '"Se, todavia, vocês se afastarem e se aliarem aos sobreviventes dessas nações que restam no meio de vocês, e se casarem com eles e se associarem com eles,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6473, 'nvi', 'Josué', 'js', 23, 13, 'estejam certos de que o Senhor, o seu Deus, já não expulsará essas nações de diante de vocês. Ao contrário, elas se tornarão armadilhas e laços para vocês, chicote em suas costas e espinhos em seus olhos, até que vocês desapareçam desta boa terra que o Senhor, o seu Deus, deu a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6474, 'nvi', 'Josué', 'js', 23, 14, '"Agora estou prestes a ir pelo caminho de toda a terra. Vocês sabem, lá no fundo do coração e da alma, que nenhuma das boas promessas que o Senhor, o seu Deus, lhes fez deixou de cumprir-se. Todas se cumpriram; nenhuma delas falhou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6475, 'nvi', 'Josué', 'js', 23, 15, 'Mas, assim como cada uma das boas promessas do Senhor, do seu Deus, se cumpriu, também o Senhor fará cumprir-se em vocês todo o mal com que os ameaçou, até eliminá-los desta boa terra que lhes deu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6476, 'nvi', 'Josué', 'js', 23, 16, 'Se vocês violarem a aliança que o Senhor, o seu Deus, lhes ordenou, e passarem a cultuar outros deuses e a inclinar-se diante deles, a ira do Senhor se acenderá contra vocês, e vocês logo desaparecerão da boa terra que ele lhes deu".');
