-- Inserções para Josué 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5894, 'nvi', 'Josué', 'js', 3, 1, 'De manhã bem cedo Josué e todos os israelitas partiram de Sitim e foram para o Jordão, onde acamparam antes de atravessar o rio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5895, 'nvi', 'Josué', 'js', 3, 2, 'Três dias depois, os oficiais percorreram o acampamento,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5896, 'nvi', 'Josué', 'js', 3, 3, 'e deram esta ordem ao povo: "Quando virem a arca da aliança do Senhor, o seu Deus, e os sacerdotes levitas carregando a arca, saiam das suas posições e sigam-na.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5897, 'nvi', 'Josué', 'js', 3, 4, 'Mas mantenham a distância de cerca de novecentos metros entre vocês e a arca; não se aproximem! Desse modo saberão que caminho seguir, pois vocês nunca passaram por lá".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5898, 'nvi', 'Josué', 'js', 3, 5, 'Josué ordenou ao povo: "Santifiquem-se, pois amanhã o Senhor fará maravilhas entre vocês".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5899, 'nvi', 'Josué', 'js', 3, 6, 'E disse aos sacerdotes: "Levantem a arca da aliança e passem à frente do povo". Eles a levantaram e foram na frente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5900, 'nvi', 'Josué', 'js', 3, 7, 'E o Senhor disse a Josué: "Hoje começarei a exaltá-lo à vista de todo o Israel, para que saibam que estarei com você como estive com Moisés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5901, 'nvi', 'Josué', 'js', 3, 8, 'Portanto, você é quem dará a seguinte ordem aos sacerdotes que carregam a arca da aliança: ‘Quando chegarem às margens das águas do Jordão, parem junto ao rio’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5902, 'nvi', 'Josué', 'js', 3, 9, 'Então Josué disse aos israelitas: "Venham ouvir as palavras do Senhor, o seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5903, 'nvi', 'Josué', 'js', 3, 10, 'Assim saberão que o Deus vivo está no meio de vocês e que certamente expulsará de diante de vocês os cananeus, os hititas, os heveus, os ferezeus, os girgaseus, os amorreus e os jebuseus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5904, 'nvi', 'Josué', 'js', 3, 11, 'Vejam, a arca da aliança do Soberano de toda a terra atravessará o Jordão à frente de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5905, 'nvi', 'Josué', 'js', 3, 12, 'Agora, escolham doze israelitas, um de cada tribo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5906, 'nvi', 'Josué', 'js', 3, 13, 'Quando os sacerdotes que carregam a arca do Senhor, o Soberano de toda a terra, puserem os pés no Jordão, a correnteza será represada e as águas formarão uma muralha".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5907, 'nvi', 'Josué', 'js', 3, 14, 'Quando, pois, o povo desmontou o acampamento para atravessar o Jordão, os sacerdotes que carregavam a arca da aliança foram adiante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5908, 'nvi', 'Josué', 'js', 3, 15, '( O Jordão transborda em ambas as margens na época da colheita. ) Assim que os sacerdotes que carregavam a arca da aliança chegaram ao Jordão e seus pés tocaram as águas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5909, 'nvi', 'Josué', 'js', 3, 16, 'a correnteza que descia parou de correr e formou uma muralha a grande distância, perto de uma cidade chamada Adã, nas proximidades de Zaretã; e as águas que desciam para o mar da Arabá, o mar Salgado, escoaram totalmente. E assim o povo atravessou o rio em frente de Jericó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5910, 'nvi', 'Josué', 'js', 3, 17, 'Os sacerdotes que carregavam a arca da aliança do Senhor ficaram parados em terra seca no meio do Jordão, enquanto todo o Israel passava, até que toda a nação o atravessou também em terra seca.');
