-- Inserções para Josué 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6322, 'nvi', 'Josué', 'js', 19, 1, 'Na segunda vez, a sorte saiu para a tribo de Simeão, clã por clã. A herança deles ficava dentro do território de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6323, 'nvi', 'Josué', 'js', 19, 2, 'Eles receberam: Berseba ou Seba, Moladá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6324, 'nvi', 'Josué', 'js', 19, 3, 'Hazar-Sual, Balá, Ázen,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6325, 'nvi', 'Josué', 'js', 19, 4, 'Eltolade, Betul, Hormá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6326, 'nvi', 'Josué', 'js', 19, 5, 'Ziclague, Bete-Marcabote, Hazar-Susa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6327, 'nvi', 'Josué', 'js', 19, 6, 'Bete-Lebaote e Saruém. Eram treze cidades com os seus povoados;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6328, 'nvi', 'Josué', 'js', 19, 7, 'Aim, Rimom, Eter e Asã, quatro cidades com os seus povoados,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6329, 'nvi', 'Josué', 'js', 19, 8, 'e todos os povoados ao redor dessas cidades, até Baalate-Beer, que é Ramá, no Neguebe. Essa foi a herança da tribo dos simeonitas, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6330, 'nvi', 'Josué', 'js', 19, 9, 'A herança dos simeonitas foi tirada de Judá, pois Judá recebera mais terras do que precisava. Assim os simeonitas receberam a sua herança dentro do território de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6331, 'nvi', 'Josué', 'js', 19, 10, 'Na terceira vez, a sorte saiu para Zebulom, clã por clã. A fronteira da sua herança ia até Saride.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6332, 'nvi', 'Josué', 'js', 19, 11, 'De lá ia para o oeste, chegava a Maralá, alcançava Dabesete, e se estendia até o ribeiro próximo a Jocneão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6333, 'nvi', 'Josué', 'js', 19, 12, 'De Saride fazia uma curva para o leste, para o lado do nascente, em direção ao território de Quislote-Tabor, prosseguia até Daberate e subia para Jafia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6334, 'nvi', 'Josué', 'js', 19, 13, 'Depois continuava para o leste, até Gate-Hefer e Ete-Cazim, chegava a Rimom e fazia uma curva na direção de Neá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6335, 'nvi', 'Josué', 'js', 19, 14, 'Do norte a fronteira voltava até Hanatom e terminava no vale de Iftá-El.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6336, 'nvi', 'Josué', 'js', 19, 15, 'Aí também estavam Catate, Naalal, Sinrom, Idala e Belém. Eram doze cidades com os seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6337, 'nvi', 'Josué', 'js', 19, 16, 'Essas cidades com os seus povoados foram a herança de Zebulom, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6338, 'nvi', 'Josué', 'js', 19, 17, 'Na quarta vez, a sorte saiu para Issacar, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6339, 'nvi', 'Josué', 'js', 19, 18, 'Seu território abrangia: Jezreel, Quesulote, Suném,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6340, 'nvi', 'Josué', 'js', 19, 19, 'Hafaraim, Siom, Anaarate,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6341, 'nvi', 'Josué', 'js', 19, 20, 'Rabite, Quisiom, Ebes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6342, 'nvi', 'Josué', 'js', 19, 21, 'Remete, En-Ganim, En-Hadá e Bete-Pazes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6343, 'nvi', 'Josué', 'js', 19, 22, 'A fronteira chegava a Tabor, Saazima e Bete-Semes, e terminava no Jordão. Eram dezesseis cidades com os seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6344, 'nvi', 'Josué', 'js', 19, 23, 'Essas cidades com os seus povoados foram a herança da tribo de Issacar, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6345, 'nvi', 'Josué', 'js', 19, 24, 'Na quinta vez, a sorte saiu para Aser, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6346, 'nvi', 'Josué', 'js', 19, 25, 'Seu território abrangia: Helcate, Hali, Béten, Acsafe,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6347, 'nvi', 'Josué', 'js', 19, 26, 'Alameleque, Amade e Misal. A oeste a fronteira alcançava o Carmelo e Sior-Libnate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6348, 'nvi', 'Josué', 'js', 19, 27, 'De lá virava para o leste em direção a Bete-Dagom, alcançava Zebulom e o vale de Iftá-El, e ia para o norte, para Bete-Emeque e Neiel, passando por Cabul, à esquerda,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6349, 'nvi', 'Josué', 'js', 19, 28, 'Ebrom, Reobe, Hamom e Caná, até Sidom, a grande.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6350, 'nvi', 'Josué', 'js', 19, 29, 'Depois a fronteira voltava para Ramá e ia para a cidade fortificada de Tiro, virava na direção de Hosa e terminava no mar, na região de Aczibe,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6351, 'nvi', 'Josué', 'js', 19, 30, 'Umá, Afeque e Reobe. Eram vinte e duas cidades com os seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6352, 'nvi', 'Josué', 'js', 19, 31, 'Essas cidades com os seus povoados foram a herança da tribo de Aser, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6353, 'nvi', 'Josué', 'js', 19, 32, 'Na sexta vez, a sorte saiu para Naftali, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6354, 'nvi', 'Josué', 'js', 19, 33, 'Sua fronteira ia desde Helefe e do Carvalho de Zaanim, passava por Adami-Neguebe e Jabneel, e ia até Lacum, terminando no Jordão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6355, 'nvi', 'Josué', 'js', 19, 34, 'Voltando para o oeste, a fronteira passava por Aznote-Tabor e ia para Hucoque. Atingia Zebulom ao sul, Aser a oeste e o Jordão a leste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6356, 'nvi', 'Josué', 'js', 19, 35, 'As cidades fortificadas eram Zidim, Zer, Hamate, Racate, Quinerete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6357, 'nvi', 'Josué', 'js', 19, 36, 'Adamá, Ramá, Hazor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6358, 'nvi', 'Josué', 'js', 19, 37, 'Quedes, Edrei, En-Hazor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6359, 'nvi', 'Josué', 'js', 19, 38, 'Irom, Migdal-El, Horém, Bete-Anate e Bete-Semes. Eram dezenove cidades com os seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6360, 'nvi', 'Josué', 'js', 19, 39, 'Essas cidades com os seus povoados foram a herança da tribo de Naftali, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6361, 'nvi', 'Josué', 'js', 19, 40, 'Na sétima vez, a sorte saiu para Dã, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6362, 'nvi', 'Josué', 'js', 19, 41, 'O território da sua herança abrangia: Zorá, Estaol, Ir-Semes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6363, 'nvi', 'Josué', 'js', 19, 42, 'Saalabim, Aijalom, Itla,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6364, 'nvi', 'Josué', 'js', 19, 43, 'Elom, Timna, Ecrom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6365, 'nvi', 'Josué', 'js', 19, 44, 'Elteque, Gibetom, Baalate,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6366, 'nvi', 'Josué', 'js', 19, 45, 'Jeúde, Bene-Beraque, Gate-Rimom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6367, 'nvi', 'Josué', 'js', 19, 46, 'Me-Jarcom e Racom, e a região defronte de Jope.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6368, 'nvi', 'Josué', 'js', 19, 47, 'Mas a tribo de Dã teve dificuldade para tomar posse do seu território. Por isso atacaram Lesém, conquistaram-na, passaram-na ao fio da espada e a ocuparam. Estabeleceram-se em Lesém e lhe deram o nome de Dã, por causa do seu antepassado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6369, 'nvi', 'Josué', 'js', 19, 48, 'Essas cidades com os seus povoados foram a herança da tribo de Dã, clã por clã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6370, 'nvi', 'Josué', 'js', 19, 49, 'Quando terminaram de dividir a terra em territórios delimitados, os israelitas deram a Josué, filho de Num, uma herança no meio deles,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6371, 'nvi', 'Josué', 'js', 19, 50, 'como o Senhor tinha ordenado. Deram-lhe a cidade que ele havia pedido, Timnate-Sera, nos montes de Efraim, onde ele reconstruiu a cidade e se estabeleceu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6372, 'nvi', 'Josué', 'js', 19, 51, 'Foram esses os territórios que o sacerdote Eleazar, Josué, filho de Num, e os chefes dos clãs das tribos de Israel repartiram por sorteio em Siló, na presença do Senhor, à entrada da Tenda do Encontro. E assim terminaram de dividir a terra.');
