-- Inserções para Josué 14
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6188, 'nvi', 'Josué', 'js', 14, 1, 'Foram estas as terras que os israelitas receberam por herança em Canaã, e que o sacerdote Eleazar, Josué, filho de Num, e os chefes dos clãs das tribos dos israelitas repartiram entre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6189, 'nvi', 'Josué', 'js', 14, 2, 'A divisão da herança foi decidida por sorteio entre as nove tribos e meia, como o Senhor tinha ordenado por meio de Moisés,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6190, 'nvi', 'Josué', 'js', 14, 3, 'pois Moisés já tinha dado herança às duas tribos e meia a leste do Jordão. Mas aos levitas não dera herança entre os demais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6191, 'nvi', 'Josué', 'js', 14, 4, 'Os filhos de José formaram as duas tribos de Manassés e Efraim. Os levitas não receberam porção alguma da terra; receberam apenas cidades onde viver, com pastagens para os seus rebanhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6192, 'nvi', 'Josué', 'js', 14, 5, 'Os israelitas dividiram a terra conforme o Senhor tinha ordenado a Moisés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6193, 'nvi', 'Josué', 'js', 14, 6, 'Os homens de Judá vieram a Josué em Gilgal, e Calebe, filho do quenezeu Jefoné, lhe disse: "Você sabe o que o Senhor disse a Moisés, homem de Deus, em Cades-Barnéia, sobre mim e sobre você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6194, 'nvi', 'Josué', 'js', 14, 7, 'Eu tinha quarenta anos quando Moisés, servo do Senhor, enviou-me de Cades-Barnéia para espionar a terra. Eu lhe dei um relatório digno de confiança,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6195, 'nvi', 'Josué', 'js', 14, 8, 'mas os meus irmãos israelitas que foram comigo fizeram o povo desanimar-se de medo. Eu, porém, fui inteiramente fiel ao Senhor, ao meu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6196, 'nvi', 'Josué', 'js', 14, 9, 'Por isso naquele dia Moisés me jurou: ‘Certamente a terra em que você pisou será uma herança perpétua para você e para os seus descendentes, porquanto você foi inteiramente fiel ao Senhor, ao meu Deus’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6197, 'nvi', 'Josué', 'js', 14, 10, '"Pois bem, o Senhor manteve-me vivo, como prometeu. E foi há quarenta e cinco anos que ele disse isso a Moisés, quando Israel caminhava pelo deserto. Por isso aqui estou hoje, com oitenta e cinco anos de idade!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6198, 'nvi', 'Josué', 'js', 14, 11, 'Ainda estou tão forte como no dia em que Moisés me enviou; tenho agora tanto vigor para ir à guerra como naquela época.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6199, 'nvi', 'Josué', 'js', 14, 12, 'Dê-me, pois, a região montanhosa que naquela ocasião o Senhor me prometeu. Na época, você ficou sabendo que os enaquins lá viviam com suas cidades grandes e fortificadas; mas, se o Senhor estiver comigo, eu os expulsarei de lá, como ele prometeu".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6200, 'nvi', 'Josué', 'js', 14, 13, 'Então Josué abençoou Calebe, filho de Jefoné, e lhe deu Hebrom por herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6201, 'nvi', 'Josué', 'js', 14, 14, 'Por isso, até hoje, Hebrom pertence aos descendentes de Calebe, filho do quenezeu Jefoné, pois ele foi inteiramente fiel ao Senhor, ao Deus de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6202, 'nvi', 'Josué', 'js', 14, 15, 'Hebrom era chamada Quiriate-Arba, em homenagem a Arba, o maior dos enaquins. E a terra teve descanso da guerra.');
