-- Inserções para Josué 20
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6373, 'nvi', 'Josué', 'js', 20, 1, 'Disse o Senhor a Josué:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6374, 'nvi', 'Josué', 'js', 20, 2, '"Diga aos israelitas que designem as cidades de refúgio, como lhes ordenei por meio de Moisés,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6375, 'nvi', 'Josué', 'js', 20, 3, 'para que todo aquele que matar alguém sem intenção e acidentalmente possa fugir para lá e proteger-se do vingador da vítima.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6376, 'nvi', 'Josué', 'js', 20, 4, '"Quando o homicida involuntário fugir para uma dessas cidades, terá que colocar-se junto à porta da cidade e expor o caso às autoridades daquela cidade. Eles o receberão e lhe darão um local para morar entre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6377, 'nvi', 'Josué', 'js', 20, 5, 'Caso o vingador da vítima o persiga, eles não o entregarão, pois matou seu próximo acidentalmente, sem maldade e sem premeditação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6378, 'nvi', 'Josué', 'js', 20, 6, 'Todavia, ele terá que permanecer naquela cidade até comparecer a julgamento perante a comunidade e até morrer o sumo sacerdote que estiver servindo naquele período. Então poderá voltar para a sua própria casa, à cidade de onde fugiu".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6379, 'nvi', 'Josué', 'js', 20, 7, 'Assim eles separaram Quedes, na Galiléia, nos montes de Naftali, Siquém, nos montes de Efraim, e Quiriate-Arba, que é Hebrom, nos montes de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6380, 'nvi', 'Josué', 'js', 20, 8, 'No lado leste do Jordão, perto de Jericó designaram Bezer, no planalto desértico da tribo de Rúben; Ramote, em Gileade, na tribo de Gade; e Golã, em Basã, na tribo de Manassés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6381, 'nvi', 'Josué', 'js', 20, 9, 'Qualquer israelita ou estrangeiro residente que matasse alguém sem intenção, poderia fugir para qualquer dessas cidades para isso designadas e escapar do vingador da vítima, antes de comparecer a julgamento perante a comunidade.');
