-- Inserções para Josué 15
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6203, 'nvi', 'Josué', 'js', 15, 1, 'As terras distribuídas à tribo de Judá, clã por clã, estendiam-se para o sul até a fronteira com Edom, até o deserto de Zim, no extremo sul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6204, 'nvi', 'Josué', 'js', 15, 2, 'Sua fronteira sul começava na ponta de terra do extremo sul do mar Salgado,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6205, 'nvi', 'Josué', 'js', 15, 3, 'passava pelo sul da subida de Acrabim, prosseguia até Zim e daí até o sul de Cades-Barnéia. Depois passava por Hezrom, indo até Adar e fazia uma curva em direção a Carca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6206, 'nvi', 'Josué', 'js', 15, 4, 'Dali continuava até Azmom, indo até o ribeiro do Egito e terminando no mar. Essa é a fronteira sul deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6207, 'nvi', 'Josué', 'js', 15, 5, 'A fronteira oriental é o mar Salgado, até a foz do Jordão. A fronteira norte começava na enseada, na foz do Jordão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6208, 'nvi', 'Josué', 'js', 15, 6, 'subia até Bete-Hogla e passava ao norte de Bete-Arabá, até a Pedra de Boã, filho de Rúben.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6209, 'nvi', 'Josué', 'js', 15, 7, 'A fronteira subia então do vale de Acor até Debir, e virava para o norte, na direção de Gilgal, que fica defronte da subida de Adumim, ao sul do ribeiro. Passava pelas águas de En-Semes, indo até En-Rogel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6210, 'nvi', 'Josué', 'js', 15, 8, 'Depois subia pelo vale de Ben-Hinom, ao longo da encosta sul da cidade dos jebuseus, isto é, Jerusalém. Dali subia até o alto da montanha, a oeste do vale de Hinom, no lado norte do vale de Refaim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6211, 'nvi', 'Josué', 'js', 15, 9, 'Do alto da montanha a fronteira prosseguia para a fonte de Neftoa, ia para as cidades do monte Efrom e descia na direção de Baalá, que é Quiriate-Jearim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6212, 'nvi', 'Josué', 'js', 15, 10, 'De Baalá fazia uma curva em direção ao oeste, até o monte Seir, prosseguia pela encosta norte do monte Jearim, isto é Quesalom; em seguida continuava descendo até Bete-Semes e passava por Timna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6213, 'nvi', 'Josué', 'js', 15, 11, 'Depois ia para a encosta norte de Ecrom, virava na direção de Sicrom, continuava até o monte Baalá e chegava a Jabneel, terminando no mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6214, 'nvi', 'Josué', 'js', 15, 12, 'A fronteira ocidental era o litoral do mar Grande. Eram essas as fronteiras que demarcavam Judá por todos os lados, de acordo com os seus clãs.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6215, 'nvi', 'Josué', 'js', 15, 13, 'Conforme a ordem dada pelo Senhor, Josué deu a Calebe, filho de Jefoné, uma porção de terra em Judá, que foi Quiriate-Arba, isto é, Hebrom. Arba era antepassado de Enaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6216, 'nvi', 'Josué', 'js', 15, 14, 'Calebe expulsou de Hebrom os três enaquins: Sesai, Aimã e Talmai, descendentes de Enaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6217, 'nvi', 'Josué', 'js', 15, 15, 'Dali avançou contra o povo de Debir, anteriormente chamada Quiriate-Sefer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6218, 'nvi', 'Josué', 'js', 15, 16, 'E Calebe disse: "Darei minha filha Acsa por mulher ao homem que atacar e conquistar Quiriate-Sefer".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6219, 'nvi', 'Josué', 'js', 15, 17, 'Otoniel, filho de Quenaz, irmão de Calebe, a conquistou; e Calebe lhe deu sua filha Acsa por mulher.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6220, 'nvi', 'Josué', 'js', 15, 18, 'Quando Acsa foi viver com Otoniel, ela o pressionou para que pedisse um campo ao pai dela. Assim que ela desceu do jumento, perguntou-lhe Calebe: "O que você quer? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6221, 'nvi', 'Josué', 'js', 15, 19, '"Quero um presente", respondeu ela. "Já que me deu terras no Neguebe, dê-me também fontes de água. " Então Calebe lhe deu as fontes superiores e as inferiores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6222, 'nvi', 'Josué', 'js', 15, 20, 'Esta é a herança da tribo de Judá, clã por clã:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6223, 'nvi', 'Josué', 'js', 15, 21, 'As cidades que ficavam no extremo sul da tribo de Judá, no Neguebe, na direção da fronteira de Edom, eram: Cabzeel, Eder, Jagur,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6224, 'nvi', 'Josué', 'js', 15, 22, 'Quiná, Dimona, Adada,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6225, 'nvi', 'Josué', 'js', 15, 23, 'Quedes, Hazor, Itnã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6226, 'nvi', 'Josué', 'js', 15, 24, 'Zife, Telém, Bealote,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6227, 'nvi', 'Josué', 'js', 15, 25, 'Hazor-Hadata, Queriote-Hezrom, que é Hazor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6228, 'nvi', 'Josué', 'js', 15, 26, 'Amã, Sema, Moladá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6229, 'nvi', 'Josué', 'js', 15, 27, 'Hazar-Gada, Hesmom, Bete-Pelete,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6230, 'nvi', 'Josué', 'js', 15, 28, 'Hazar-Sual, Berseba, Biziotiá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6231, 'nvi', 'Josué', 'js', 15, 29, 'Baalá, Iim, Azém,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6232, 'nvi', 'Josué', 'js', 15, 30, 'Eltolade, Quesil, Hormá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6233, 'nvi', 'Josué', 'js', 15, 31, 'Ziclague, Madmana, Sansana,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6234, 'nvi', 'Josué', 'js', 15, 32, 'Lebaote, Silim, Aim e Rimom. Eram um total de vinte e nove cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6235, 'nvi', 'Josué', 'js', 15, 33, 'Na Sefelá: Estaol, Zorá, Asná,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6236, 'nvi', 'Josué', 'js', 15, 34, 'Zanoa, En-Ganim, Tapua, Enã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6237, 'nvi', 'Josué', 'js', 15, 35, 'Jarmute, Adulão, Socó, Azeca,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6238, 'nvi', 'Josué', 'js', 15, 36, 'Saaraim, Aditaim, e Gederá ou Gederotaim. Eram catorze cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6239, 'nvi', 'Josué', 'js', 15, 37, 'Zenã, Hadasa, Migdal-Gade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6240, 'nvi', 'Josué', 'js', 15, 38, 'Dileã, Mispá, Jocteel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6241, 'nvi', 'Josué', 'js', 15, 39, 'Láquis, Bozcate, Eglom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6242, 'nvi', 'Josué', 'js', 15, 40, 'Cabom, Laamás, Quitlis,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6243, 'nvi', 'Josué', 'js', 15, 41, 'Gederote, Bete-Dagom, Naamá e Maquedá. Eram dezesseis cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6244, 'nvi', 'Josué', 'js', 15, 42, 'Libna, Eter, Asã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6245, 'nvi', 'Josué', 'js', 15, 43, 'Iftá, Asná, Nezibe,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6246, 'nvi', 'Josué', 'js', 15, 44, 'Queila, Aczibe e Maressa. Eram nove cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6247, 'nvi', 'Josué', 'js', 15, 45, 'Ecrom, com suas vilas e seus povoados;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6248, 'nvi', 'Josué', 'js', 15, 46, 'de Ecrom até o mar, todas as cidades nas proximidades de Asdode, juntamente com os seus povoados;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6249, 'nvi', 'Josué', 'js', 15, 47, 'Asdode, com suas vilas e seus povoados; e Gaza, com suas vilas e seus povoados, até o ribeiro do Egito e o litoral do mar Grande.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6250, 'nvi', 'Josué', 'js', 15, 48, 'Na região montanhosa: Samir, Jatir, Socó,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6251, 'nvi', 'Josué', 'js', 15, 49, 'Daná, Quiriate-Sana, que é Debir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6252, 'nvi', 'Josué', 'js', 15, 50, 'Anabe, Estemo, Anim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6253, 'nvi', 'Josué', 'js', 15, 51, 'Gósen, Holom e Gilo. Eram onze cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6254, 'nvi', 'Josué', 'js', 15, 52, 'Arabe, Dumá, Esã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6255, 'nvi', 'Josué', 'js', 15, 53, 'Janim, Bete-Tapua, Afeca,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6256, 'nvi', 'Josué', 'js', 15, 54, 'Hunta, Quiriate-Arba, que é Hebrom e Zior. Eram nove cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6257, 'nvi', 'Josué', 'js', 15, 55, 'Maom, Carmelo, Zife, Jutá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6258, 'nvi', 'Josué', 'js', 15, 56, 'Jezreel, Jocdeão, Zanoa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6259, 'nvi', 'Josué', 'js', 15, 57, 'Caim, Gibeá e Timna. Eram dez cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6260, 'nvi', 'Josué', 'js', 15, 58, 'Halul, Bete-Zur, Gedor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6261, 'nvi', 'Josué', 'js', 15, 59, 'Maarate, Bete-Anote e Eltecom. Eram seis cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6262, 'nvi', 'Josué', 'js', 15, 60, 'Quiriate-Baal, que é Quiriate-Jearim e Rabá. Eram duas cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6263, 'nvi', 'Josué', 'js', 15, 61, 'No deserto: Bete-Arabá, Midim, Secacá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6264, 'nvi', 'Josué', 'js', 15, 62, 'Nibsã, Cidade do Sal e En-Gedi. Eram seis cidades com seus povoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6265, 'nvi', 'Josué', 'js', 15, 63, 'Os descendentes de Judá não conseguiram expulsar os jebuseus, que viviam em Jerusalém; até hoje os jebuseus vivem ali com o povo de Judá.');
