-- Inserções para Josué 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6131, 'nvi', 'Josué', 'js', 12, 1, 'São estes os reis que os israelitas derrotaram, e de cujo território se apossaram a leste do Jordão, desde o ribeiro do Arnom até o monte Hermom, inclusive todo o lado leste da Arabá:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6132, 'nvi', 'Josué', 'js', 12, 2, 'Seom, rei dos amorreus, que reinou em Hesbom. Governou desde Aroer, na borda do ribeiro do Arnom, desde o meio do ribeiro, até o rio Jaboque, que é a fronteira dos amonitas. Esse território incluía a metade de Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6133, 'nvi', 'Josué', 'js', 12, 3, 'Também governou a Arabá oriental, desde o mar de Quinerete até o mar da Arabá, o mar Salgado, até Bete-Jesimote, e mais ao sul, ao pé das encostas do Pisga.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6134, 'nvi', 'Josué', 'js', 12, 4, 'Tomaram o território de Ogue, rei de Basã, um dos últimos refains, que reinou em Asterote e Edrei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6135, 'nvi', 'Josué', 'js', 12, 5, 'Ele governou o monte Hermom, Salcá, toda a Basã, até a fronteira do povo de Gesur e de Maaca, e metade de Gileade, até a fronteira de Seom, rei de Hesbom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6136, 'nvi', 'Josué', 'js', 12, 6, 'Moisés, servo do Senhor, e os israelitas os derrotaram. E Moisés, servo do Senhor, deu a terra deles como propriedade às tribos de Rúben, de Gade e à metade da tribo de Manassés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6137, 'nvi', 'Josué', 'js', 12, 7, 'São estes os reis que Josué e os israelitas derrotaram no lado ocidental do Jordão, desde Baal-Gade, no vale do Líbano, até o monte Halaque, que se ergue na direção de Seir. Josué deu a terra deles por herança às tribos de Israel, repartindo-a entre elas —');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6138, 'nvi', 'Josué', 'js', 12, 8, 'a serra central, a Sefelá, a Arabá, as encostas das montanhas, o deserto e o Neguebe — as terras dos hititas, dos amorreus, dos cananeus, dos ferezeus, dos heveus e dos jebuseus:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6139, 'nvi', 'Josué', 'js', 12, 9, 'o rei de Jericó, o rei de Ai, próxima a Betel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6140, 'nvi', 'Josué', 'js', 12, 10, 'o rei de Jerusalém, o rei de Hebrom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6141, 'nvi', 'Josué', 'js', 12, 11, 'o rei de Jarmute, o rei de Láquis,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6142, 'nvi', 'Josué', 'js', 12, 12, 'o rei de Eglom, o rei de Gezer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6143, 'nvi', 'Josué', 'js', 12, 13, 'o rei de Debir, o rei de Geder,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6144, 'nvi', 'Josué', 'js', 12, 14, 'o rei de Hormá, o rei de Arade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6145, 'nvi', 'Josué', 'js', 12, 15, 'o rei de Libna, o rei de Adulão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6146, 'nvi', 'Josué', 'js', 12, 16, 'o rei de Maquedá, o rei de Betel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6147, 'nvi', 'Josué', 'js', 12, 17, 'o rei de Tapua, o rei de Héfer,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6148, 'nvi', 'Josué', 'js', 12, 18, 'o rei de Afeque, o rei de Lasarom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6149, 'nvi', 'Josué', 'js', 12, 19, 'o rei de Madom, o rei de Hazor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6150, 'nvi', 'Josué', 'js', 12, 20, 'o rei de Sinrom-Merom, o rei de Acsafe,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6151, 'nvi', 'Josué', 'js', 12, 21, 'o rei de Taanaque, o rei de Megido,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6152, 'nvi', 'Josué', 'js', 12, 22, 'o rei de Quedes, o rei de Jocneão do Carmelo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6153, 'nvi', 'Josué', 'js', 12, 23, 'o rei de Dor em Nafote-Dor, o rei de Goim de Gilgal,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6154, 'nvi', 'Josué', 'js', 12, 24, 'e o rei de Tirza. Trinta e um reis ao todo.');
