-- Inserções para Josué 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5935, 'nvi', 'Josué', 'js', 5, 1, 'Todos os reis amorreus que habitavam a oeste do Jordão e todos os reis cananeus que viviam ao longo do litoral souberam como o Senhor tinha secado o Jordão diante dos israelitas até que tivéssemos atravessado. Por isso, desanimaram-se e perderam a coragem de enfrentar os israelitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5936, 'nvi', 'Josué', 'js', 5, 2, 'Naquela ocasião o Senhor disse a Josué: "Faça facas de pedra e circuncide os israelitas de novo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5937, 'nvi', 'Josué', 'js', 5, 3, 'Josué fez facas de pedra e circuncidou os israelitas em Gibeate-Aralote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5938, 'nvi', 'Josué', 'js', 5, 4, 'Ele fez isso porque todos os homens aptos para a guerra morreram no deserto depois de terem saído do Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5939, 'nvi', 'Josué', 'js', 5, 5, 'Todos os que saíram haviam sido circuncidados, mas todos os que nasceram no deserto, no caminho, depois da saída do Egito, não passaram pela circuncisão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5940, 'nvi', 'Josué', 'js', 5, 6, 'Os israelitas tinham andado quarenta anos pelo deserto, até que todos os guerreiros que saíram do Egito morressem, visto que não tinham obedecido ao Senhor. Pois o Senhor lhes havia jurado que não veriam a terra que prometera aos seus antepassados que nos daria, terra onde manam leite e mel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5941, 'nvi', 'Josué', 'js', 5, 7, 'Assim, em lugar deles colocou os seus filhos, e foram os filhos que Josué circuncidou. Ainda estavam incircuncisos porque não tinham sido circuncidados durante a viagem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5942, 'nvi', 'Josué', 'js', 5, 8, 'E, depois que a nação inteira foi circuncidada, eles ficaram onde estavam, no acampamento, até se recuperarem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5943, 'nvi', 'Josué', 'js', 5, 9, 'Então o Senhor disse a Josué: "Hoje removi de vocês a humilhação sofrida no Egito". Por isso até hoje o lugar se chama Gilgal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5944, 'nvi', 'Josué', 'js', 5, 10, 'Na tarde do décimo quarto dia do mês, enquanto estavam acampados em Gilgal, na planície de Jericó, os israelitas celebraram a Páscoa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5945, 'nvi', 'Josué', 'js', 5, 11, 'No dia seguinte ao da Páscoa, nesse mesmo dia, eles comeram pães sem fermento e grãos de trigo tostados, produtos daquela terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5946, 'nvi', 'Josué', 'js', 5, 12, 'Um dia depois de comerem do produto da terra, o maná cessou. Já não havia maná para os israelitas, e naquele mesmo ano eles comeram do fruto da terra de Canaã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5947, 'nvi', 'Josué', 'js', 5, 13, 'Estando Josué já perto de Jericó, olhou para cima e viu um homem de pé, empunhando uma espada. Aproximou-se dele e perguntou-lhe: "Você é por nós, ou por nossos inimigos? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5948, 'nvi', 'Josué', 'js', 5, 14, '"Nem uma coisa nem outra", respondeu ele. "Venho na qualidade de comandante do exército do Senhor". Então Josué prostrou-se, rosto em terra, em sinal de respeito, e lhe perguntou: "Que mensagem o meu senhor tem para o seu servo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (5949, 'nvi', 'Josué', 'js', 5, 15, 'O comandante do exército do Senhor respondeu: "Tire as sandálias dos pés, pois o lugar em que você está é santo". E Josué as tirou.');
