-- Inserções para Juízes 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6870, 'nvi', 'Juízes', 'jz', 12, 1, 'Os homens de Efraim foram convocados para a batalha; dirigiram-se para Zafom e disseram a Jefté: "Por que você foi lutar contra os amonitas sem nos chamar para irmos juntos? Vamos queimar a sua casa e você junto! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6871, 'nvi', 'Juízes', 'jz', 12, 2, 'Jefté respondeu: "Eu e meu povo estávamos envolvidos numa grande contenda com os amonitas, e, embora eu os tenha chamado, vocês não me livraram das mãos deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6872, 'nvi', 'Juízes', 'jz', 12, 3, 'Quando vi que vocês não ajudariam, arrisquei a vida e fui lutar contra os amonitas, e o Senhor me deu a vitória sobre eles. E, por que vocês vieram para cá hoje? Para lutar contra mim? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6873, 'nvi', 'Juízes', 'jz', 12, 4, 'Jefté reuniu então todos os homens de Gileade e lutou contra Efraim. Os gileaditas feriram os efraimitas porque estes tinham dito: "Vocês, gileaditas, são desertores de Efraim e de Manassés".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6874, 'nvi', 'Juízes', 'jz', 12, 5, 'Os gileaditas tomaram as passagens do Jordão que conduziam a Efraim. Sempre que um fugitivo de Efraim dizia: "Deixem-me atravessar", os homens de Gileade perguntavam: "Você é efraimita? " Se respondesse que não,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6875, 'nvi', 'Juízes', 'jz', 12, 6, 'diziam "Então diga: ‘Chibolete’ ". Se ele dissesse: "Sibolete", sem conseguir pronunciar corretamente a palavra, prendiam-no e matavam-no no lugar de passagem do Jordão. Quarenta e dois mil efraimitas foram mortos naquela ocasião.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6876, 'nvi', 'Juízes', 'jz', 12, 7, 'Jefté liderou Israel durante seis anos. Então o gileadita Jefté morreu, e foi sepultado numa cidade de Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6877, 'nvi', 'Juízes', 'jz', 12, 8, 'Depois de Jefté, Ibsã, de Belém, liderou Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6878, 'nvi', 'Juízes', 'jz', 12, 9, 'Teve trinta filhos e trinta filhas. Deu suas filhas em casamento a homens de fora do seu clã, e trouxe para os seus filhos trinta mulheres de fora do seu clã. Ibsã liderou Israel durante sete anos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6879, 'nvi', 'Juízes', 'jz', 12, 10, 'Então Ibsã morreu, e foi sepultado em Belém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6880, 'nvi', 'Juízes', 'jz', 12, 11, 'Depois dele, Elom, da tribo de Zebulom, liderou Israel durante dez anos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6881, 'nvi', 'Juízes', 'jz', 12, 12, 'Elom morreu, e foi sepultado em Aijalom, na terra de Zebulom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6882, 'nvi', 'Juízes', 'jz', 12, 13, 'Depois dele, Abdom, filho de Hilel, de Piratom, liderou Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6883, 'nvi', 'Juízes', 'jz', 12, 14, 'Teve quarenta filhos e trinta netos, que montavam setenta jumentos. Abdom liderou Israel durante oito anos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6884, 'nvi', 'Juízes', 'jz', 12, 15, 'Então Abdom, filho de Hilel, morreu, e foi sepultado em Piratom, na terra de Efraim, na serra dos amalequitas.');
