-- Inserções para Juízes 10
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6812, 'nvi', 'Juízes', 'jz', 10, 1, 'Depois de Abimeleque, um homem de Issacar chamado Tolá, filho de Puá, filho de Dodô, levantou-se para libertar Israel. Ele morava em Samir, nos montes de Efraim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6813, 'nvi', 'Juízes', 'jz', 10, 2, 'e liderou Israel durante vinte e três anos; então morreu e foi sepultado em Samir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6814, 'nvi', 'Juízes', 'jz', 10, 3, 'Depois dele veio Jair, de Gileade, que liderou Israel durante vinte e dois anos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6815, 'nvi', 'Juízes', 'jz', 10, 4, 'Teve trinta filhos, que montavam trinta jumentos. Eles tinham autoridade sobre trinta cidades, as quais até hoje são chamadas povoados de Jair e ficam em Gileade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6816, 'nvi', 'Juízes', 'jz', 10, 5, 'Quando Jair morreu, foi sepultado em Camom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6817, 'nvi', 'Juízes', 'jz', 10, 6, 'Mais uma vez os israelitas fizeram o que o Senhor reprova. Serviram aos baalins e aos postes sagrados, e aos deuses de Arã, aos deuses de Sidom, aos deuses de Moabe, aos deuses dos amonitas e aos deuses dos filisteus. E como os israelitas abandonaram o Senhor e não mais lhe prestaram culto,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6818, 'nvi', 'Juízes', 'jz', 10, 7, 'a ira do Senhor se acendeu contra eles. Ele os entregou nas mãos dos filisteus e dos amonitas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6819, 'nvi', 'Juízes', 'jz', 10, 8, 'que naquele ano os humilharam e os oprimiram. Durante dezoito anos oprimiram a todos os israelitas do lado leste do Jordão, em Gileade, terra dos amorreus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6820, 'nvi', 'Juízes', 'jz', 10, 9, 'Os amonitas também atravessaram o Jordão para lutar contra Judá, contra Benjamim e contra a tribo de Efraim; e grande angústia dominou Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6821, 'nvi', 'Juízes', 'jz', 10, 10, 'Então os israelitas clamaram ao Senhor, dizendo: "Temos pecado contra ti, pois abandonamos o nosso Deus e prestamos culto aos baalins! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6822, 'nvi', 'Juízes', 'jz', 10, 11, 'O Senhor respondeu: "Quando os egípcios, os amorreus, os amonitas, os filisteus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6823, 'nvi', 'Juízes', 'jz', 10, 12, 'os sidônios, os amalequitas e os maonitas os oprimiram, e vocês clamaram a mim, e eu os libertei das mãos deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6824, 'nvi', 'Juízes', 'jz', 10, 13, 'Mas vocês me abandonaram e prestaram culto a outros deuses. Por isso não os livrarei mais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6825, 'nvi', 'Juízes', 'jz', 10, 14, 'Clamem aos deuses que vocês escolheram. Que eles os livrem na hora do aperto! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6826, 'nvi', 'Juízes', 'jz', 10, 15, 'Os israelitas, porém, disseram ao Senhor: "Nós pecamos. Faze conosco o que achares melhor, mas te rogamos, livra-nos agora".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6827, 'nvi', 'Juízes', 'jz', 10, 16, 'Então eles se desfizeram dos deuses estrangeiros que havia entre eles e prestaram culto ao Senhor. E ele não pôde mais suportar o sofrimento de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6828, 'nvi', 'Juízes', 'jz', 10, 17, 'Quando os amonitas foram convocados e acamparam em Gileade, os israelitas reuniram-se e acamparam em Mispá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6829, 'nvi', 'Juízes', 'jz', 10, 18, 'Os líderes do povo de Gileade disseram uns aos outros: "Quem iniciar o ataque contra os amonitas será chefe dos que vivem em Gileade".');
