-- Inserções para Juízes 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6981, 'nvi', 'Juízes', 'jz', 17, 1, 'Havia um homem chamado Mica, dos montes de Efraim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6982, 'nvi', 'Juízes', 'jz', 17, 2, 'que disse certa vez à sua mãe: "Os treze quilos de prata que lhe foram roubados e pelos quais eu a ouvi pronunciar uma maldição. Na verdade a prata está comigo; eu a peguei". Disse-lhe sua mãe: "O Senhor o abençoe, meu filho! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6983, 'nvi', 'Juízes', 'jz', 17, 3, 'Quando ele devolveu os treze quilos de prata à mãe, ela disse: "Consagro solenemente a minha prata ao Senhor para que o meu filho faça uma imagem esculpida e um ídolo de metal. Eu a devolvo a você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6984, 'nvi', 'Juízes', 'jz', 17, 4, 'Mas ele devolveu a prata à sua mãe, e ela separou dois quilos e quatrocentos gramas, e os deu a um ourives, que deles fez a imagem e o ídolo. E estes foram postos na casa de Mica.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6985, 'nvi', 'Juízes', 'jz', 17, 5, 'Ora, esse homem, Mica, possuía um santuário, e fez um manto sacerdotal e alguns ídolos da família e pôs um dos seus filhos como seu sacerdote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6986, 'nvi', 'Juízes', 'jz', 17, 6, 'Naquela época não havia rei em Israel; cada um fazia o que lhe parecia certo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6987, 'nvi', 'Juízes', 'jz', 17, 7, 'Um jovem levita de Belém de Judá, procedente do clã de Judá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6988, 'nvi', 'Juízes', 'jz', 17, 8, 'saiu daquela cidade em busca de outro lugar para morar. Em sua viagem, chegou à casa de Mica, nos montes de Efraim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6989, 'nvi', 'Juízes', 'jz', 17, 9, 'Mica lhe perguntou: "De onde você vem? " "Sou levita, de Belém de Judá", respondeu ele. "Estou procurando um lugar para morar. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6990, 'nvi', 'Juízes', 'jz', 17, 10, '"Fique comigo", disse-lhe Mica. "Seja meu pai e sacerdote, e eu lhe darei cento e vinte gramas de prata por ano, roupas e comida. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6991, 'nvi', 'Juízes', 'jz', 17, 11, 'O jovem levita concordou em ficar com Mica, e tornou-se como um dos seus filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6992, 'nvi', 'Juízes', 'jz', 17, 12, 'Mica acolheu o levita, e o jovem se tornou seu sacerdote, e ficou morando em sua casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (6993, 'nvi', 'Juízes', 'jz', 17, 13, 'E Mica disse: "Agora sei que o Senhor me tratará com bondade, pois esse levita se tornou meu sacerdote".');
