-- Inserções para Jó 22
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13391, 'nvi', 'Jó', 'jó', 22, 1, 'Então, de Temã, Elifaz respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13392, 'nvi', 'Jó', 'jó', 22, 2, '"Pode alguém ser útil a Deus? Mesmo um sábio, pode ser-lhe de algum proveito?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13393, 'nvi', 'Jó', 'jó', 22, 3, 'Que prazer você daria ao Todo-poderoso se você fosse justo? Que é que ele ganharia se os seus caminhos fossem irrepreensíveis?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13394, 'nvi', 'Jó', 'jó', 22, 4, '"É por sua piedade que ele o repreende e lhe faz acusações?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13395, 'nvi', 'Jó', 'jó', 22, 5, 'Não é grande a sua maldade? Não são infindos os seus pecados?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13396, 'nvi', 'Jó', 'jó', 22, 6, 'Sem motivo você exigia penhores dos seus irmãos; você despojava das roupas os que quase nenhuma tinham.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13397, 'nvi', 'Jó', 'jó', 22, 7, 'Você não deu água ao sedento e reteve a comida do faminto,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13398, 'nvi', 'Jó', 'jó', 22, 8, 'sendo você poderoso, e dono de terras, delas vivendo, e honrado diante de todos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13399, 'nvi', 'Jó', 'jó', 22, 9, 'Você mandou embora de mãos vazias as viúvas e quebrou a força dos órfãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13400, 'nvi', 'Jó', 'jó', 22, 10, 'Por isso está cercado de armadilhas e o perigo repentino o apavora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13401, 'nvi', 'Jó', 'jó', 22, 11, 'Também por isso você se vê envolto em escuridão que o cega, e o cobrem as águas, em tremenda inundação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13402, 'nvi', 'Jó', 'jó', 22, 12, '"Não está Deus nas alturas dos céus? E em que altura estão as estrelas mais distantes!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13403, 'nvi', 'Jó', 'jó', 22, 13, 'Contudo você diz: ‘Que é que Deus sabe? Poderá julgar através de tão grande escuridão?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13404, 'nvi', 'Jó', 'jó', 22, 14, 'Nuvens espessas o cobrem, e ele não pode nos ver, quando percorre a abóbada dos céus’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13405, 'nvi', 'Jó', 'jó', 22, 15, 'Você vai continuar no velho caminho que os perversos palmilharam?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13406, 'nvi', 'Jó', 'jó', 22, 16, 'Estes foram levados antes da hora; seus alicerces foram arrastados por uma enchente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13407, 'nvi', 'Jó', 'jó', 22, 17, 'Eles disseram a Deus: ‘Deixa-nos! Que é que o Todo-poderoso poderá fazer conosco? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13408, 'nvi', 'Jó', 'jó', 22, 18, 'Contudo, foi ele que encheu de bens as casas deles; por isso fico longe do conselho dos ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13409, 'nvi', 'Jó', 'jó', 22, 19, '"Os justos vêem a ruína deles, e se regozijam; os inocentes zombam deles, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13410, 'nvi', 'Jó', 'jó', 22, 20, '‘Certo é que os nossos inimigos foram destruídos, e o fogo devorou a sua riqueza’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13411, 'nvi', 'Jó', 'jó', 22, 21, '"Sujeite-se a Deus, fique em paz com ele, e a prosperidade virá a você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13412, 'nvi', 'Jó', 'jó', 22, 22, 'Aceite a instrução que vem da sua boca e ponha no coração as suas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13413, 'nvi', 'Jó', 'jó', 22, 23, 'Se você voltar-se para o Todo-poderoso, voltará ao seu lugar: Se afastar da sua tenda a injustiça,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13414, 'nvi', 'Jó', 'jó', 22, 24, 'lançar ao pó as suas pepitas, o seu ouro puro de Ofir às rochas dos vales,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13415, 'nvi', 'Jó', 'jó', 22, 25, 'o Todo-poderoso será o seu ouro, será para você prata seleta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13416, 'nvi', 'Jó', 'jó', 22, 26, 'É certo que você achará prazer no Todo-poderoso e erguerá o rosto para Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13417, 'nvi', 'Jó', 'jó', 22, 27, 'A ele orará, e ele o ouvirá, e você cumprirá os seus votos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13418, 'nvi', 'Jó', 'jó', 22, 28, 'O que você decidir se fará, e a luz brilhará em seus caminhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13419, 'nvi', 'Jó', 'jó', 22, 29, 'Quando os homens forem humilhados e você disser: ‘Levanta-os! ’, ele salvará o abatido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13420, 'nvi', 'Jó', 'jó', 22, 30, 'Livrará até o que não é inocente, que será liberto graças à pureza que há nas suas mãos".');
