-- Inserções para Jó 31
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13590, 'nvi', 'Jó', 'jó', 31, 1, '"Fiz acordo com os meus olhos de não olhar com cobiça para as moças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13591, 'nvi', 'Jó', 'jó', 31, 2, 'Pois qual é a porção que o homem recebe de Deus, lá de cima? Qual a sua herança do Todo-poderoso, que habita nas alturas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13592, 'nvi', 'Jó', 'jó', 31, 3, 'Não é ruína para os ímpios, desgraça para os que fazem o mal?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13593, 'nvi', 'Jó', 'jó', 31, 4, 'Não vê ele os meus caminhos, e não considera cada um de meus passos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13594, 'nvi', 'Jó', 'jó', 31, 5, '"Se me conduzi com falsidade, ou se meus pés se apressaram a enganar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13595, 'nvi', 'Jó', 'jó', 31, 6, 'Deus me pese em balança justa, e saberá que não tenho culpa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13596, 'nvi', 'Jó', 'jó', 31, 7, 'se meus passos desviaram-se do caminho, se o meu coração foi conduzido por meus olhos, ou se minhas mãos foram contaminadas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13597, 'nvi', 'Jó', 'jó', 31, 8, 'que outros comam o que semeei, e que as minhas plantações sejam arrancadas pelas raízes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13598, 'nvi', 'Jó', 'jó', 31, 9, '"Se o meu coração foi seduzido por mulher, ou se fiquei à espreita junto à porta do meu próximo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13599, 'nvi', 'Jó', 'jó', 31, 10, 'que a minha esposa moa cereal de outro homem, e que outros durmam com ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13600, 'nvi', 'Jó', 'jó', 31, 11, 'Pois fazê-lo seria vergonhoso, crime merecedor de julgamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13601, 'nvi', 'Jó', 'jó', 31, 12, 'Isso é um fogo que consome até a Destruição; teria extirpado a minha colheita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13602, 'nvi', 'Jó', 'jó', 31, 13, '"Se neguei justiça aos meus servos e servas, quando reclamaram contra mim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13603, 'nvi', 'Jó', 'jó', 31, 14, 'que farei quando Deus me confrontar? Que responderei quando chamado a prestar contas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13604, 'nvi', 'Jó', 'jó', 31, 15, 'Aquele que me fez no ventre materno não fez também a eles? Não foi ele quem formou a mim e a eles No interior de nossas mães?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13605, 'nvi', 'Jó', 'jó', 31, 16, '"Se não atendi aos desejos do pobre, ou se fatiguei os olhos da viúva,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13606, 'nvi', 'Jó', 'jó', 31, 17, 'se comi meu pão sozinho, sem compartilhá-lo com o órfão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13607, 'nvi', 'Jó', 'jó', 31, 18, 'sendo que desde a minha juventude o criei como se fosse seu pai, e desde o nascimento guiei a viúva;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13608, 'nvi', 'Jó', 'jó', 31, 19, 'se vi alguém morrendo por falta de roupa, ou um necessitado sem cobertor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13609, 'nvi', 'Jó', 'jó', 31, 20, 'e o seu coração não me abençoou porque o aqueci com a lã de minhas ovelhas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13610, 'nvi', 'Jó', 'jó', 31, 21, 'se levantei a mão contra o órfão, ciente da minha influência no tribunal,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13611, 'nvi', 'Jó', 'jó', 31, 22, 'que o meu braço descaia do ombro, e se quebre nas juntas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13612, 'nvi', 'Jó', 'jó', 31, 23, 'Pois eu tinha medo que Deus me destruísse, e, temendo o seu esplendor, não podia fazer tais coisas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13613, 'nvi', 'Jó', 'jó', 31, 24, '"Se pus no ouro a minha confiança e disse ao ouro puro: Você é a minha garantia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13614, 'nvi', 'Jó', 'jó', 31, 25, 'se me regozijei por ter grande riqueza, pela fortuna que as minhas mãos obtiveram,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13615, 'nvi', 'Jó', 'jó', 31, 26, 'se contemplei o sol em seu fulgor e a lua a mover-se esplêndida,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13616, 'nvi', 'Jó', 'jó', 31, 27, 'e em segredo o meu coração foi seduzido e a minha mão lhes ofereceu beijos de veneração,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13617, 'nvi', 'Jó', 'jó', 31, 28, 'esses também seriam pecados merecedores de condenação, pois eu teria sido infiel a Deus, que está nas alturas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13618, 'nvi', 'Jó', 'jó', 31, 29, '"Se a desgraça do meu inimigo me alegrou, ou se os problemas que teve me deram prazer;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13619, 'nvi', 'Jó', 'jó', 31, 30, 'eu, que nunca deixei minha boca pecar, lançando maldição sobre ele;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13620, 'nvi', 'Jó', 'jó', 31, 31, 'se os que moram em minha casa nunca tivessem dito: ‘Quem não recebeu de Jó um pedaço de carne? ’,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13621, 'nvi', 'Jó', 'jó', 31, 32, 'sendo que nenhum estrangeiro teve que passar a noite na rua, pois a minha porta sempre esteve aberta para o viajante;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13622, 'nvi', 'Jó', 'jó', 31, 33, 'se escondi o meu pecado, como outros fazem, acobertando no coração a minha culpa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13623, 'nvi', 'Jó', 'jó', 31, 34, 'com tanto medo da multidão e do desprezo dos familiares que me calei e não saí de casa...');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13624, 'nvi', 'Jó', 'jó', 31, 35, '( "Ah, se alguém me ouvisse! Agora assino a minha defesa. Que o Todo-poderoso me responda; que o meu acusador faça a acusação por escrito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13625, 'nvi', 'Jó', 'jó', 31, 36, 'Eu bem que a levaria nos ombros e a usaria como coroa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13626, 'nvi', 'Jó', 'jó', 31, 37, 'Eu lhe falaria sobre todos os meus passos; como um príncipe eu me aproximaria dele. )');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13627, 'nvi', 'Jó', 'jó', 31, 38, '"Se a minha terra se queixar de mim e todos os seus sulcos chorarem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13628, 'nvi', 'Jó', 'jó', 31, 39, 'se consumi os seus produtos sem nada pagar, ou se causei desânimo aos seus ocupantes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13629, 'nvi', 'Jó', 'jó', 31, 40, 'que me venham espinhos em lugar de trigo e ervas daninhas em lugar de cevada". Aqui terminam as palavras de Jó.');
