-- Inserções para Jó 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13031, 'nvi', 'Jó', 'jó', 8, 1, 'Então Bildade, de Suá, respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13032, 'nvi', 'Jó', 'jó', 8, 2, '"Até quando você vai falar desse modo? Suas palavras são um grande vendaval!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13033, 'nvi', 'Jó', 'jó', 8, 3, 'Acaso Deus torce a justiça? Será que o Todo-poderoso torce o que é direito?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13034, 'nvi', 'Jó', 'jó', 8, 4, 'Quando os seus filhos pecaram contra ele, ele os castigou pelo mal que fizeram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13035, 'nvi', 'Jó', 'jó', 8, 5, 'Mas, se você procurar a Deus e implorar junto ao Todo-poderoso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13036, 'nvi', 'Jó', 'jó', 8, 6, 'se você for íntegro e puro, ele se levantará agora mesmo em seu favor e o restabelecerá no lugar que por justiça cabe a você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13037, 'nvi', 'Jó', 'jó', 8, 7, 'O seu começo parecerá modesto, mas o seu futuro será de grande prosperidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13038, 'nvi', 'Jó', 'jó', 8, 8, '"Pergunte às gerações anteriores e veja o que os seus pais aprenderam,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13039, 'nvi', 'Jó', 'jó', 8, 9, 'pois nós nascemos ontem e não sabemos nada. Nossos dias na terra não passam de uma sombra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13040, 'nvi', 'Jó', 'jó', 8, 10, 'Acaso eles não o instruirão, não lhe falarão? Não proferirão palavras vindas do entendimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13041, 'nvi', 'Jó', 'jó', 8, 11, 'Poderá o papiro crescer senão no pântano? Sem água cresce o junco?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13042, 'nvi', 'Jó', 'jó', 8, 12, 'Mal cresce e, antes de ser colhido, seca-se, mais depressa que qualquer grama.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13043, 'nvi', 'Jó', 'jó', 8, 13, 'Esse é o destino de todo o que se esquece de Deus; assim perece a esperança dos ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13044, 'nvi', 'Jó', 'jó', 8, 14, 'Aquilo em que ele confia é frágil, aquilo em que se apóia é uma teia de aranha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13045, 'nvi', 'Jó', 'jó', 8, 15, 'Encosta-se em sua teia, mas ela cede; agarra-se a ela, mas ela não agüenta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13046, 'nvi', 'Jó', 'jó', 8, 16, 'Ele é como uma planta bem regada ao brilho do sol, espalhando seus brotos pelo jardim;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13047, 'nvi', 'Jó', 'jó', 8, 17, 'entrelaça as raízes em torno de um monte de pedras e procura um lugar entre as rochas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13048, 'nvi', 'Jó', 'jó', 8, 18, 'Mas, quando é arrancada do seu lugar, este o rejeita e diz: ‘Nunca o vi’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13049, 'nvi', 'Jó', 'jó', 8, 19, 'Esse é o fim da sua vida, e do solo brotam outras plantas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13050, 'nvi', 'Jó', 'jó', 8, 20, '"Pois o certo é que Deus não rejeita o íntegro, e não fortalece as mãos dos que fazem o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13051, 'nvi', 'Jó', 'jó', 8, 21, 'Mas, quanto a você, ele encherá de riso a sua boca e de brados de alegria os seus lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13052, 'nvi', 'Jó', 'jó', 8, 22, 'Seus inimigos se vestirão de vergonha, e as tendas dos ímpios não mais existirão".');
