-- Inserções para Jó 33
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13652, 'nvi', 'Jó', 'jó', 33, 1, '"Mas agora, Jó, escute as minhas palavras; preste atenção a tudo o que vou dizer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13653, 'nvi', 'Jó', 'jó', 33, 2, 'Estou prestes a abrir a boca; minhas palavras estão na ponta da língua.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13654, 'nvi', 'Jó', 'jó', 33, 3, 'Minhas palavras procedem de um coração íntegro; meus lábios falam com sinceridade o que eu sei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13655, 'nvi', 'Jó', 'jó', 33, 4, 'O Espírito de Deus me fez; o sopro do Todo-poderoso me dá vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13656, 'nvi', 'Jó', 'jó', 33, 5, 'Responda-me, então, se puder; prepare-se para enfrentar-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13657, 'nvi', 'Jó', 'jó', 33, 6, 'Sou igual a você diante de Deus; eu também fui feito do barro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13658, 'nvi', 'Jó', 'jó', 33, 7, 'Por isso não lhe devo inspirar temor, e a minha mão não há de ser pesada sobre você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13659, 'nvi', 'Jó', 'jó', 33, 8, '"Mas você disse ao meu alcance, eu ouvi bem as palavras:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13660, 'nvi', 'Jó', 'jó', 33, 9, '‘Estou limpo e sem pecado; estou puro e sem culpa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13661, 'nvi', 'Jó', 'jó', 33, 10, 'Contudo, Deus procurou em mim motivos para inimizade; ele me considera seu inimigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13662, 'nvi', 'Jó', 'jó', 33, 11, 'Ele acorrenta os meus pés; vigia de perto todos os meus caminhos. ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13663, 'nvi', 'Jó', 'jó', 33, 12, '"Mas eu lhe digo que você não está certo, porquanto Deus é maior do que o homem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13664, 'nvi', 'Jó', 'jó', 33, 13, 'Por que você se queixa a ele de que não responde às palavras dos homens?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13665, 'nvi', 'Jó', 'jó', 33, 14, 'Pois a verdade é que Deus fala, ora de um modo, ora de outro, mesmo que o homem não o perceba.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13666, 'nvi', 'Jó', 'jó', 33, 15, 'Em sonho ou em visão durante a noite, quando o sono profundo cai sobre os homens e eles dormem em suas camas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13667, 'nvi', 'Jó', 'jó', 33, 16, 'ele pode falar aos ouvidos deles e aterrorizá-los com advertências');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13668, 'nvi', 'Jó', 'jó', 33, 17, 'para previnir o homem das suas más ações e livrá-lo do orgulho,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13669, 'nvi', 'Jó', 'jó', 33, 18, 'para preservar da cova a sua alma, e a sua vida da espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13670, 'nvi', 'Jó', 'jó', 33, 19, 'Ou o homem pode ser castigado no leito de dor, com os seus ossos em constante agonia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13671, 'nvi', 'Jó', 'jó', 33, 20, 'levando-o a achar a comida repulsiva e a detestar na alma sua refeição preferida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13672, 'nvi', 'Jó', 'jó', 33, 21, 'Já não se vê sua carne, e seus ossos, que não se viam, agora aparecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13673, 'nvi', 'Jó', 'jó', 33, 22, 'Sua alma aproxima-se da cova, e sua vida, dos mensageiros da morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13674, 'nvi', 'Jó', 'jó', 33, 23, '"Havendo, porém, um anjo ao seu lado, como mediador dentre mil, que diga ao homem o que é certo a seu respeito,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13675, 'nvi', 'Jó', 'jó', 33, 24, 'para ser-lhe favorável e dizer: ‘Poupa-o de descer à cova; encontrei resgate para ele’,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13676, 'nvi', 'Jó', 'jó', 33, 25, 'então sua carne se renova voltando a ser como de criança; ele se rejuvenece.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13677, 'nvi', 'Jó', 'jó', 33, 26, 'Ele ora a Deus e recebe o seu favor; vê o rosto de Deus e dá gritos de alegria, e Deus lhe restitui a condição de justo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13678, 'nvi', 'Jó', 'jó', 33, 27, 'Depois ele vem aos homens e diz: ‘Pequei e torci o que era certo, mas ele não me deu o que eu merecia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13679, 'nvi', 'Jó', 'jó', 33, 28, 'Ele resgatou a minha alma, impedindo-a de descer à cova, e viverei para desfrutar a luz’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13680, 'nvi', 'Jó', 'jó', 33, 29, '"Deus faz dessas coisas ao homem, duas ou três vezes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13681, 'nvi', 'Jó', 'jó', 33, 30, 'para recuperar sua alma da cova, a fim de que refulja sobre ele a luz da vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13682, 'nvi', 'Jó', 'jó', 33, 31, '"Preste atenção, Jó, e escute-me; fique em silêncio, e falarei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13683, 'nvi', 'Jó', 'jó', 33, 32, 'Se você tem algo para dizer, responda-me; fale logo, pois quero que você seja absolvido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13684, 'nvi', 'Jó', 'jó', 33, 33, 'Se não tem nada a dizer, ouça-me, fique em silêncio, e eu lhe ensinarei a sabedoria".');
