-- Inserções para Jó 34
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13685, 'nvi', 'Jó', 'jó', 34, 1, 'Disse então Eliú:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13686, 'nvi', 'Jó', 'jó', 34, 2, '"Ouçam as minhas palavras, vocês que são sábios; escutem-me, vocês que têm conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13687, 'nvi', 'Jó', 'jó', 34, 3, 'Pois o ouvido prova as palavras como a língua prova o alimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13688, 'nvi', 'Jó', 'jó', 34, 4, 'Tratemos de discernir juntos o que é certo e de aprender o que é bom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13689, 'nvi', 'Jó', 'jó', 34, 5, '"Jó afirma: ‘Sou inocente, mas Deus me nega justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13690, 'nvi', 'Jó', 'jó', 34, 6, 'Apesar de eu estar certo, sou considerado mentiroso; apesar de estar sem culpa, sua flecha me causa ferida incurável’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13691, 'nvi', 'Jó', 'jó', 34, 7, 'Que homem existe como Jó, que bebe zombaria como água?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13692, 'nvi', 'Jó', 'jó', 34, 8, 'Ele é companheiro dos que fazem o mal, e anda com os ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13693, 'nvi', 'Jó', 'jó', 34, 9, 'Pois diz: ‘Não dá lucro agradar a Deus’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13694, 'nvi', 'Jó', 'jó', 34, 10, '"Por isso escutem-me, vocês que têm conhecimento. Longe de Deus esteja o fazer o mal, e do Todo-poderoso o praticar a iniqüidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13695, 'nvi', 'Jó', 'jó', 34, 11, 'Ele retribui ao homem conforme o que este fez, e lhe dá o que a sua conduta merece.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13696, 'nvi', 'Jó', 'jó', 34, 12, 'Não se pode nem pensar que Deus faça o mal, que o Todo-poderoso perverta a justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13697, 'nvi', 'Jó', 'jó', 34, 13, 'Quem o nomeou para governar a terra? Quem o encarregou de cuidar do mundo inteiro?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13698, 'nvi', 'Jó', 'jó', 34, 14, 'Se fosse intenção dele, e de fato retirasse o seu espírito e o seu sopro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13699, 'nvi', 'Jó', 'jó', 34, 15, 'a humanidade pereceria toda de uma vez, e o homem voltaria ao pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13700, 'nvi', 'Jó', 'jó', 34, 16, '"Portanto, se você tem entendimento, ouça-me, escute o que lhe digo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13701, 'nvi', 'Jó', 'jó', 34, 17, 'Acaso quem odeia a justiça poderá governar? Será que você condenará aquele que é justo e poderoso?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13702, 'nvi', 'Jó', 'jó', 34, 18, 'Não é ele que diz aos reis: ‘Vocês nada valem’, e aos nobres: ‘Vocês são ímpios’?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13703, 'nvi', 'Jó', 'jó', 34, 19, 'Não é verdade que ele não mostra parcialidade a favor dos príncipes, e não favorece o rico em detrimento do pobre, uma vez que todos são obra de suas mãos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13704, 'nvi', 'Jó', 'jó', 34, 20, 'Morrem num momento, em plena noite; cambaleiam e passam. Os poderosos são retirados sem a intervenção de mãos humanas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13705, 'nvi', 'Jó', 'jó', 34, 21, '"Pois Deus vê o caminho dos homens; ele enxerga cada um dos seus passos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13706, 'nvi', 'Jó', 'jó', 34, 22, 'Não há sombra densa o bastante, onde os que fazem o mal possam esconder-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13707, 'nvi', 'Jó', 'jó', 34, 23, 'Deus não precisa de maior tempo para examinar os homens, e levá-los à sua presença para julgamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13708, 'nvi', 'Jó', 'jó', 34, 24, 'Sem depender de investigações, ele destrói os poderosos e coloca outros em seu lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13709, 'nvi', 'Jó', 'jó', 34, 25, 'Visto que ele repara nos atos que eles praticam, derruba-os, e eles são esmagados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13710, 'nvi', 'Jó', 'jó', 34, 26, 'Pela impiedade deles, ele os castiga onde todos podem vê-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13711, 'nvi', 'Jó', 'jó', 34, 27, 'Isso porque deixaram de segui-lo e não deram atenção aos caminhos por ele traçados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13712, 'nvi', 'Jó', 'jó', 34, 28, 'Fizeram chegar a ele o grito do pobre, e ele ouviu o clamor do necessitado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13713, 'nvi', 'Jó', 'jó', 34, 29, 'Mas, se ele permanecer calado, quem poderá condená-lo? Se esconder o rosto, quem poderá vê-lo? No entanto, ele domina igualmente sobre homens e nações,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13714, 'nvi', 'Jó', 'jó', 34, 30, 'para evitar que o ímpio governe e prepare armadilhas para o povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13715, 'nvi', 'Jó', 'jó', 34, 31, '"Suponhamos que um homem diga a Deus: ‘Sou culpado, mas não vou mais pecar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13716, 'nvi', 'Jó', 'jó', 34, 32, 'Mostra-me o que não estou vendo; se agi mal, não tornarei a fazê-lo’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13717, 'nvi', 'Jó', 'jó', 34, 33, 'Quanto a você, deveria Deus recompensá-lo quando você nega a sua culpa? É você que tem que decidir, não eu; conte-me, pois, o que você sabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13718, 'nvi', 'Jó', 'jó', 34, 34, '"Os homens de bom senso, os sábios que me ouvem, me declaram:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13719, 'nvi', 'Jó', 'jó', 34, 35, '‘Jó não sabe o que diz; não há discernimento em suas palavras’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13720, 'nvi', 'Jó', 'jó', 34, 36, 'Ah, se Jó sofresse a mais dura prova, por sua resposta de ímpio!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13721, 'nvi', 'Jó', 'jó', 34, 37, 'Ao seu pecado ele acrescenta a revolta; com desprezo bate palmas entre nós e multiplica suas palavras contra Deus".');
