-- Inserções para Jó 16
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13240, 'nvi', 'Jó', 'jó', 16, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13241, 'nvi', 'Jó', 'jó', 16, 2, '"Já ouvi muitas palavras como essas. Pobres consoladores são vocês todos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13242, 'nvi', 'Jó', 'jó', 16, 3, 'Esses discursos inúteis nunca acabarão? O que o leva a continuar discutindo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13243, 'nvi', 'Jó', 'jó', 16, 4, 'Bem que eu poderia falar como vocês, se estivessem em meu lugar; eu poderia condená-los com belos discursos, e menear a cabeça contra vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13244, 'nvi', 'Jó', 'jó', 16, 5, 'Mas a minha boca procuraria encorajá-los; a consolação dos meus lábios lhes daria alívio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13245, 'nvi', 'Jó', 'jó', 16, 6, '"Contudo, se falo, a minha dor não se alivia; se me calo, ela não desaparece.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13246, 'nvi', 'Jó', 'jó', 16, 7, 'Sem dúvida, ó Deus, tu me esgotaste as forças; deste fim a toda a minha família.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13247, 'nvi', 'Jó', 'jó', 16, 8, 'Tu me deixaste deprimido, o que é uma testemunha disso; a minha magreza se levanta e depõe contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13248, 'nvi', 'Jó', 'jó', 16, 9, 'Deus, em sua ira, ataca-me e faz-me em pedaços, e range os dentes contra mim; meus inimigos fitam-me com olhar penetrante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13249, 'nvi', 'Jó', 'jó', 16, 10, 'Os homens abrem sua boca contra mim, esmurram meu rosto com zombaria e se unem contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13250, 'nvi', 'Jó', 'jó', 16, 11, 'Deus fez-me cair nas mãos dos ímpios, e atirou-me nas garras dos maus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13251, 'nvi', 'Jó', 'jó', 16, 12, 'Eu estava tranqüilo, mas ele me arrebentou; agarrou-me pelo pescoço e esmagou-me. Fez de mim o seu alvo;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13252, 'nvi', 'Jó', 'jó', 16, 13, 'seus flecheiros me cercam. Ele traspassou sem dó os meus rins e derramou na terra a minha bílis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13253, 'nvi', 'Jó', 'jó', 16, 14, 'Lança-se sobre mim uma e outra vez; ataca-me como um guerreiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13254, 'nvi', 'Jó', 'jó', 16, 15, '"Costurei veste de lamento sobre a minha pele e enterrei a minha testa no pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13255, 'nvi', 'Jó', 'jó', 16, 16, 'Meu rosto está rubro de tanto eu chorar, e sombras densas circundam os meus olhos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13256, 'nvi', 'Jó', 'jó', 16, 17, 'apesar de que não há violência em minhas mãos e de que é pura a minha oração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13257, 'nvi', 'Jó', 'jó', 16, 18, '"Ó terra, não cubra o meu sangue! Não haja lugar de repouso para o meu clamor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13258, 'nvi', 'Jó', 'jó', 16, 19, 'Saibam que agora mesmo a minha testemunha está nos céus; nas alturas está o meu advogado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13259, 'nvi', 'Jó', 'jó', 16, 20, 'O meu intercessor é meu amigo, quando diante de Deus correm lágrimas dos meus olhos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13260, 'nvi', 'Jó', 'jó', 16, 21, 'ele defende a causa do homem perante Deus, como quem defende a causa do amigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13261, 'nvi', 'Jó', 'jó', 16, 22, '"Pois mais alguns anos apenas, e farei a viagem sem retorno.');
