-- Inserções para Jó 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12932, 'nvi', 'Jó', 'jó', 4, 1, 'Então respondeu Elifaz, de Temã:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12933, 'nvi', 'Jó', 'jó', 4, 2, '"Se alguém se aventurar a dizer-lhe uma palavra, você ficará impaciente? Mas quem pode refrear as palavras?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12934, 'nvi', 'Jó', 'jó', 4, 3, 'Pense bem! Você ensinou a tantos; fortaleceu mãos fracas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12935, 'nvi', 'Jó', 'jó', 4, 4, 'Suas palavras davam firmeza aos que tropeçavam; você fortaleceu joelhos vacilantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12936, 'nvi', 'Jó', 'jó', 4, 5, 'Mas agora que se vê em dificuldade, você se desanima; quando você é atingido, fica prostrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12937, 'nvi', 'Jó', 'jó', 4, 6, 'Sua vida piedosa não lhe inspira confiança, e o seu procedimento irrepreensível não lhe dá esperança?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12938, 'nvi', 'Jó', 'jó', 4, 7, '"Reflita agora: Qual foi o inocente que chegou a perecer? Onde foi que os íntegros sofreram destruição?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12939, 'nvi', 'Jó', 'jó', 4, 8, 'Pelo que tenho observado, quem cultiva o mal e semeia maldade, isso também colherá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12940, 'nvi', 'Jó', 'jó', 4, 9, 'Pelo sopro de Deus são destruídos; pelo vento de sua ira eles perecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12941, 'nvi', 'Jó', 'jó', 4, 10, 'Os leões podem rugir e rosnar, mas até os dentes dos leões fortes se quebram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12942, 'nvi', 'Jó', 'jó', 4, 11, 'O leão morre por falta de presa, e os filhotes da leoa se dispersam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12943, 'nvi', 'Jó', 'jó', 4, 12, '"Disseram-me uma palavra em segredo, da qual os meus ouvidos captaram um murmúrio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12944, 'nvi', 'Jó', 'jó', 4, 13, 'Em meio a sonhos perturbadores da noite, quando cai sono profundo sobre os homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12945, 'nvi', 'Jó', 'jó', 4, 14, 'temor e tremor se apoderaram de mim e fizeram estremecer todos os meus ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12946, 'nvi', 'Jó', 'jó', 4, 15, 'Um espírito roçou o meu rosto, e os pêlos do meu corpo se arrepiaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12947, 'nvi', 'Jó', 'jó', 4, 16, 'Ele parou, mas não pude identificá-lo. Um vulto se pôs diante dos meus olhos, e ouvi uma voz suave, que dizia:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12948, 'nvi', 'Jó', 'jó', 4, 17, '‘Poderá algum mortal ser mais justo que Deus? Poderá algum homem ser mais puro que o seu Criador?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12949, 'nvi', 'Jó', 'jó', 4, 18, 'Se Deus não confia em seus servos, se vê erro em seus anjos e os acusa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12950, 'nvi', 'Jó', 'jó', 4, 19, 'quanto mais nos que moram em casas de barro, cujos alicerces estão no pó! São mais facilmente esmagados que uma traça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12951, 'nvi', 'Jó', 'jó', 4, 20, 'Entre o alvorecer e o crepúsculo são despedaçados; perecem para sempre, sem sequer serem notados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12952, 'nvi', 'Jó', 'jó', 4, 21, 'Não é certo que as cordas de suas tendas são arrancadas, e eles morrem sem sabedoria? ’');
