-- Inserções para Jó 39
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13836, 'nvi', 'Jó', 'jó', 39, 1, '"Você sabe quando as cabras monteses dão à luz? Você está atento quando a corça tem o seu filhote?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13837, 'nvi', 'Jó', 'jó', 39, 2, 'Acaso você conta os meses até elas darem à luz? Sabe em que época elas têm as suas crias?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13838, 'nvi', 'Jó', 'jó', 39, 3, 'Elas se agacham, dão à luz os seus filhotes, e suas dores se vão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13839, 'nvi', 'Jó', 'jó', 39, 4, 'Seus filhotes crescem nos campos e ficam fortes; partem, e não voltam mais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13840, 'nvi', 'Jó', 'jó', 39, 5, '"Quem pôs em liberdade o jumento selvagem? Quem soltou suas cordas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13841, 'nvi', 'Jó', 'jó', 39, 6, 'Eu lhe dei o deserto como lar, os leito seco de lagos salgados como sua morada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13842, 'nvi', 'Jó', 'jó', 39, 7, 'Ele se ri da agitação da cidade; não ouve os gritos do tropeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13843, 'nvi', 'Jó', 'jó', 39, 8, 'Vagueia pelas colinas em busca de pasto e vai em busca daquilo que é verde.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13844, 'nvi', 'Jó', 'jó', 39, 9, '"Será que o boi selvagem consentirá em servir você? e em passar a noite ao lado dos cochos do seu curral?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13845, 'nvi', 'Jó', 'jó', 39, 10, 'Poderá você prendê-lo com arreio na vala? Irá atrás de você arando os vales?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13846, 'nvi', 'Jó', 'jó', 39, 11, 'Você vai confiar nele, por causa da sua grande força? Vai deixar a cargo dele o trabalho pesado que você tem que fazer?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13847, 'nvi', 'Jó', 'jó', 39, 12, 'Poderá você estar certo de que ele recolherá o seu trigo e o ajuntará na sua eira?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13848, 'nvi', 'Jó', 'jó', 39, 13, '"A avestruz bate as asas alegremente. Que se dirá então das asas e da plumagem da cegonha?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13849, 'nvi', 'Jó', 'jó', 39, 14, 'Ela abandona os ovos no chão e deixa que a areia os aqueça,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13850, 'nvi', 'Jó', 'jó', 39, 15, 'esquecida de que um pé poderá esmagá-los, que algum animal selvagem poderá pisoteá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13851, 'nvi', 'Jó', 'jó', 39, 16, 'Ela trata mal os seus filhotes, como se não fossem dela, e não se importa se o seu trabalho é inútil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13852, 'nvi', 'Jó', 'jó', 39, 17, 'Isso porque Deus não lhe deu sabedoria nem parcela alguma de bom senso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13853, 'nvi', 'Jó', 'jó', 39, 18, 'Contudo, quando estende as penas para correr, ela ri do cavalo e daquele que o cavalga.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13854, 'nvi', 'Jó', 'jó', 39, 19, '"É você que dá força ao cavalo ou veste o seu pescoço com sua crina tremulante?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13855, 'nvi', 'Jó', 'jó', 39, 20, 'Você o faz saltar como gafanhoto, espalhando terror com o seu orgulhoso resfolegar?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13856, 'nvi', 'Jó', 'jó', 39, 21, 'Ele escarva com fúria, mostra com prazer a sua força, e sai para enfrentar as armas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13857, 'nvi', 'Jó', 'jó', 39, 22, 'Ele ri do medo, e nada teme; não recua diante da espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13858, 'nvi', 'Jó', 'jó', 39, 23, 'A aljava balança ao seu lado, com a lança e o dardo flamejantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13859, 'nvi', 'Jó', 'jó', 39, 24, 'Num furor frenético ele devora o chão; não consegue esperar pelo toque da trombeta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13860, 'nvi', 'Jó', 'jó', 39, 25, 'Ao toque da trombeta, ele relincha: ‘Eia! ’ De longe sente cheiro de combate, o brado de comando e o grito de guerra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13861, 'nvi', 'Jó', 'jó', 39, 26, '"É graças a inteligência que você tem que o falcão alça vôo e estende as asas rumo sul?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13862, 'nvi', 'Jó', 'jó', 39, 27, 'É porque você manda, que a águia se eleva, e no alto constrói o seu ninho?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13863, 'nvi', 'Jó', 'jó', 39, 28, 'Um penhasco é sua morada, e ali passa a noite; uma escarpa rochosa é a sua fortaleza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13864, 'nvi', 'Jó', 'jó', 39, 29, 'De lá sai ela em busca de alimento; de longe os seus olhos o vêem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13865, 'nvi', 'Jó', 'jó', 39, 30, 'Seus filhotes bebem sangue, e, onde há mortos, ali ela está".');
