-- Inserções para Jó 28
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13506, 'nvi', 'Jó', 'jó', 28, 1, '"Existem minas de prata e locais onde se refina ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13507, 'nvi', 'Jó', 'jó', 28, 2, 'O ferro é extraído da terra, e do minério se funde o cobre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13508, 'nvi', 'Jó', 'jó', 28, 3, 'O homem dá fim à escuridão; e vasculha os recônditos mais remotos em busca de minério, nas mais escuras trevas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13509, 'nvi', 'Jó', 'jó', 28, 4, 'Longe das moradias ele cava um poço, em local esquecido pelos pés dos homens; longe de todos, ele se pendura e balança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13510, 'nvi', 'Jó', 'jó', 28, 5, 'A terra, da qual vem o alimento, é revolvida embaixo como que pelo fogo;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13511, 'nvi', 'Jó', 'jó', 28, 6, 'das suas rochas saem safiras, e seu pó contém pepitas de ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13512, 'nvi', 'Jó', 'jó', 28, 7, 'Nenhuma ave de rapina conhece aquele caminho oculto, e os olhos de nenhum falcão o viram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13513, 'nvi', 'Jó', 'jó', 28, 8, 'Os animais altivos não põem os pés nele, e nenhum leão ronda por ali.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13514, 'nvi', 'Jó', 'jó', 28, 9, 'As mãos dos homens atacam a pederneira e transtornam as raízes das montanhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13515, 'nvi', 'Jó', 'jó', 28, 10, 'Fazem túneis através da rocha, e os seus olhos enxergam todos os tesouros dali.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13516, 'nvi', 'Jó', 'jó', 28, 11, 'Eles vasculham as nascentes dos rios e trazem à luz coisas ocultas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13517, 'nvi', 'Jó', 'jó', 28, 12, '"Onde, porém, se poderá achar a sabedoria? Onde habita o entendimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13518, 'nvi', 'Jó', 'jó', 28, 13, 'O homem não percebe o valor da sabedoria; ela não se encontra na terra dos viventes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13519, 'nvi', 'Jó', 'jó', 28, 14, 'O abismo diz: ‘Em mim não está’; o mar diz: ‘Não está comigo’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13520, 'nvi', 'Jó', 'jó', 28, 15, 'Não pode ser comprada, mesmo com o ouro mais puro, nem se pode pesar o seu preço em prata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13521, 'nvi', 'Jó', 'jó', 28, 16, 'Não pode ser comprada nem com o ouro puro de Ofir, nem com o precioso ônix ou com safiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13522, 'nvi', 'Jó', 'jó', 28, 17, 'O ouro e o cristal não se comparam com ela, e é impossível tê-la em troca de jóias de ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13523, 'nvi', 'Jó', 'jó', 28, 18, 'O coral e o jaspe nem merecem menção; o preço da sabedoria ultrapassa o dos rubis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13524, 'nvi', 'Jó', 'jó', 28, 19, 'O topázio da Etiópia não se compara com ela; não se compra a sabedoria nem com ouro puro!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13525, 'nvi', 'Jó', 'jó', 28, 20, '"De onde vem, então, a sabedoria? Onde habita o entendimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13526, 'nvi', 'Jó', 'jó', 28, 21, 'Escondida está dos olhos de toda criatura viva, até das aves dos céus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13527, 'nvi', 'Jó', 'jó', 28, 22, 'A Destruição e a Morte dizem: ‘Aos nossos ouvidos só chegou um leve rumor dela’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13528, 'nvi', 'Jó', 'jó', 28, 23, 'Deus conhece o caminho; só ele sabe onde ela habita,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13529, 'nvi', 'Jó', 'jó', 28, 24, 'pois ele enxerga os confins da terra e vê tudo o que há debaixo dos céus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13530, 'nvi', 'Jó', 'jó', 28, 25, 'Quando ele determinou a força do vento e estabeleceu a medida exata para as águas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13531, 'nvi', 'Jó', 'jó', 28, 26, 'quando fez um decreto para a chuva e o caminho para a tempestade trovejante,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13532, 'nvi', 'Jó', 'jó', 28, 27, 'ele olhou para a sabedoria e a avaliou; confirmou-a e a pôs à prova.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13533, 'nvi', 'Jó', 'jó', 28, 28, 'Disse então ao homem: ‘No temor do Senhor está a sabedoria, e evitar o mal é ter entendimento’ ".');
