-- Inserções para Jó 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13299, 'nvi', 'Jó', 'jó', 19, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13300, 'nvi', 'Jó', 'jó', 19, 2, '"Até quando vocês continuarão a atormentar-me, e a esmagar-me com palavras?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13301, 'nvi', 'Jó', 'jó', 19, 3, 'Vocês já me repreenderam dez vezes; não se envergonham de agredir-me!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13302, 'nvi', 'Jó', 'jó', 19, 4, 'Se é verdade que me desviei, meu erro só interessa a mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13303, 'nvi', 'Jó', 'jó', 19, 5, 'Se de fato vocês se exaltam acima de mim e usam contra mim a minha humilhação,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13304, 'nvi', 'Jó', 'jó', 19, 6, 'saibam que foi Deus que me tratou mal e me envolveu em sua rede.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13305, 'nvi', 'Jó', 'jó', 19, 7, '"Se grito: É injustiça! Não obtenho resposta; clamo por socorro, todavia não há justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13306, 'nvi', 'Jó', 'jó', 19, 8, 'Ele bloqueou o meu caminho, e não consigo passar; cobriu de trevas as minhas veredas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13307, 'nvi', 'Jó', 'jó', 19, 9, 'Despiu-me da minha honra e tirou a coroa de minha cabeça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13308, 'nvi', 'Jó', 'jó', 19, 10, 'Ele me arrasa por todos os lados, enquanto eu não me vou; desarraiga a minha esperança como se arranca uma planta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13309, 'nvi', 'Jó', 'jó', 19, 11, 'Sua ira acendeu-se contra mim; ele me vê como inimigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13310, 'nvi', 'Jó', 'jó', 19, 12, 'Suas tropas avançam poderosamente; cercam-me e acampam ao redor da minha tenda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13311, 'nvi', 'Jó', 'jó', 19, 13, '"Ele afastou de mim os meus irmãos; até os meus conhecidos estão longe de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13312, 'nvi', 'Jó', 'jó', 19, 14, 'Os meus parentes me abandonaram e os meus amigos esqueceram-se de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13313, 'nvi', 'Jó', 'jó', 19, 15, 'Os meus hóspedes e as minhas servas consideram-me estrangeiro; vêem-me como um estranho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13314, 'nvi', 'Jó', 'jó', 19, 16, 'Chamo o meu servo, mas ele não me responde, ainda que eu lhe implore pessoalmente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13315, 'nvi', 'Jó', 'jó', 19, 17, 'Minha mulher acha repugnante o meu hálito; meus próprios irmãos têm nojo de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13316, 'nvi', 'Jó', 'jó', 19, 18, 'Até os meninos zombam de mim, e dão risada quando apareço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13317, 'nvi', 'Jó', 'jó', 19, 19, 'Todos os meus amigos chegados me detestam; aqueles a quem amo voltaram-se contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13318, 'nvi', 'Jó', 'jó', 19, 20, 'Não passo de pele e ossos; só escapei com a pele dos meus dentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13319, 'nvi', 'Jó', 'jó', 19, 21, '"Misericórdia, meus amigos! Misericórdia! Pois a mão de Deus me feriu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13320, 'nvi', 'Jó', 'jó', 19, 22, 'Por que vocês me perseguem como Deus o faz? Nunca vão saciar-se da minha carne?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13321, 'nvi', 'Jó', 'jó', 19, 23, '"Quem dera as minhas palavras fossem registradas! Quem dera fossem escritas num livro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13322, 'nvi', 'Jó', 'jó', 19, 24, 'fossem talhadas a ferro no chumbo, ou gravadas para sempre na rocha!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13323, 'nvi', 'Jó', 'jó', 19, 25, 'Eu sei que o meu Redentor vive, e que no fim se levantará sobre a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13324, 'nvi', 'Jó', 'jó', 19, 26, 'E depois que o meu corpo estiver destruído e sem carne, verei a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13325, 'nvi', 'Jó', 'jó', 19, 27, 'Eu o verei, com os meus próprios olhos; eu mesmo, e não outro! Como anseia no meu peito o coração!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13326, 'nvi', 'Jó', 'jó', 19, 28, '"Se vocês disserem: ‘Vejamos como vamos persegui-lo, pois a raiz do problema está nele’,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13327, 'nvi', 'Jó', 'jó', 19, 29, 'melhor será que temam a espada, porquanto por meio dela a ira lhes trará castigo, e então vocês saberão que há julgamento".');
