-- Inserções para Jó 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12893, 'nvi', 'Jó', 'jó', 2, 1, 'Num outro dia os anjos vieram apresentar-se ao Senhor, e Satanás também veio com eles para apresentar-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12894, 'nvi', 'Jó', 'jó', 2, 2, 'E o Senhor disse a Satanás, "De onde você vem? " Satanás respondeu ao Senhor: "De perambular pela terra e andar por ela".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12895, 'nvi', 'Jó', 'jó', 2, 3, 'Disse então o Senhor a Satanás: "Reparou em meu servo Jó? Não há ninguém na terra como ele, irrepreensível, íntegro, homem que teme a Deus e evita o mal. Ele se mantém íntegro, apesar de você me haver instigado contra ele para arruiná-lo sem motivo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12896, 'nvi', 'Jó', 'jó', 2, 4, '"Pele por pele! ", respondeu Satanás. "Um homem dará tudo o que tem por sua vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12897, 'nvi', 'Jó', 'jó', 2, 5, 'Estende a tua mão e fere a sua carne e os seus ossos, e com certeza ele te amaldiçoará na tua face. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12898, 'nvi', 'Jó', 'jó', 2, 6, 'O Senhor disse a Satanás: "Pois bem, ele está nas suas mãos; apenas poupe a vida dele".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12899, 'nvi', 'Jó', 'jó', 2, 7, 'Saiu, pois, Satanás da presença do Senhor e afligiu Jó com feridas terríveis, da sola dos pés ao alto da cabeça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12900, 'nvi', 'Jó', 'jó', 2, 8, 'Então Jó apanhou um caco de louça com o qual se raspava, sentado entre as cinzas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12901, 'nvi', 'Jó', 'jó', 2, 9, 'Então sua mulher lhe disse: "Você ainda mantém a sua integridade? Amaldiçoe a Deus, e morra! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12902, 'nvi', 'Jó', 'jó', 2, 10, 'Ele respondeu: "Você fala como uma insensata. Aceitaremos o bem dado por Deus, e não o mal? " Em tudo isso Jó não pecou com os lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12903, 'nvi', 'Jó', 'jó', 2, 11, 'Quando três amigos de Jó, Elifaz, de Temã, Bildade, de Suá, e Zofar, de Naamate, souberam de todos os males que o haviam atingido, saíram, cada um da sua região, e combinaram encontrar-se para mostrar solidariedade a Jó e consolá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12904, 'nvi', 'Jó', 'jó', 2, 12, 'Quando o viram à distância, mal puderam reconhecê-lo e começaram a chorar em alta voz. Cada um deles rasgou o manto e colocou terra sobre a cabeça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12905, 'nvi', 'Jó', 'jó', 2, 13, 'Depois se assentaram no chão com ele, durante sete dias e sete noites. Ninguém lhe disse uma palavra, pois viam como era grande o seu sofrimento.');
