-- Inserções para Jó 41
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13890, 'nvi', 'Jó', 'jó', 41, 1, '"Você consegue pescar com anzol o leviatã ou prender sua língua com uma corda?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13891, 'nvi', 'Jó', 'jó', 41, 2, 'Consegue fazer passar um cordão pelo seu nariz ou atravessar seu queixo com um gancho?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13892, 'nvi', 'Jó', 'jó', 41, 3, 'Pensa que ele vai lhe implorar misericórdia e lhe vai falar palavras amáveis?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13893, 'nvi', 'Jó', 'jó', 41, 4, 'Acha que ele vai fazer acordo com você, para que você o tenha como escravo pelo resto da vida?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13894, 'nvi', 'Jó', 'jó', 41, 5, 'Acaso você consegue fazer dele um bichinho de estimação, como se ele fosse um passarinho, ou pôr-lhe uma coleira para as suas filhas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13895, 'nvi', 'Jó', 'jó', 41, 6, 'Poderão os negociantes vendê-lo? Ou reparti-lo entre os comerciantes?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13896, 'nvi', 'Jó', 'jó', 41, 7, 'Você consegue encher de arpões o seu couro, e de lanças de pesca a sua cabeça?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13897, 'nvi', 'Jó', 'jó', 41, 8, 'Se puser a mão nele, a luta ficará em sua memória, e nunca mais você tornará a fazê-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13898, 'nvi', 'Jó', 'jó', 41, 9, 'Esperar vencê-lo é ilusão; só vê-lo já é assustador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13899, 'nvi', 'Jó', 'jó', 41, 10, 'Ninguém é suficientemente corajoso para despertá-lo. Quem então será capaz de resistir a mim?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13900, 'nvi', 'Jó', 'jó', 41, 11, 'Quem primeiro me deu alguma coisa, que eu lhe deva pagar? Tudo o que há debaixo dos céus me pertence.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13901, 'nvi', 'Jó', 'jó', 41, 12, '"Não deixarei de falar de seus membros, de sua força e de seu porte gracioso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13902, 'nvi', 'Jó', 'jó', 41, 13, 'Quem consegue arrancar sua capa externa? Quem se aproximaria dele com uma rédea?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13903, 'nvi', 'Jó', 'jó', 41, 14, 'Quem ousa abrir as portas de sua boca, cercada com seus dentes temíveis?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13904, 'nvi', 'Jó', 'jó', 41, 15, 'Suas costas possuem fileiras de escudos firmemente unidos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13905, 'nvi', 'Jó', 'jó', 41, 16, 'cada um está tão junto do outro que nem o ar passa entre eles;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13906, 'nvi', 'Jó', 'jó', 41, 17, 'estão tão interligados, que é impossível separá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13907, 'nvi', 'Jó', 'jó', 41, 18, 'Seu forte sopro atira lampejos de luz; seus olhos são como os raios da alvorada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13908, 'nvi', 'Jó', 'jó', 41, 19, 'Tições saem da sua boca; fagulhas de fogo estalam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13909, 'nvi', 'Jó', 'jó', 41, 20, 'Das suas narinas sai fumaça como de panela fervente sobre fogueira de juncos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13910, 'nvi', 'Jó', 'jó', 41, 21, 'Seu sopro faz o carvão pegar fogo, e da sua boca saltam chamas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13911, 'nvi', 'Jó', 'jó', 41, 22, 'Tanta força reside em seu pescoço que o terror vai adiante dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13912, 'nvi', 'Jó', 'jó', 41, 23, 'As dobras da sua carne são fortemente unidas; são tão firmes que não se movem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13913, 'nvi', 'Jó', 'jó', 41, 24, 'Seu peito é duro como pedra, rijo como a pedra inferior do moinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13914, 'nvi', 'Jó', 'jó', 41, 25, 'Quando ele se ergue, os poderosos se apavoram; fogem com medo dos seus golpes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13915, 'nvi', 'Jó', 'jó', 41, 26, 'A espada que o atinge não lhe faz nada, nem a lança nem a flecha nem o dardo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13916, 'nvi', 'Jó', 'jó', 41, 27, 'Ferro ele trata como palha, e bronze como madeira podre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13917, 'nvi', 'Jó', 'jó', 41, 28, 'As flechas não o afugentam, as pedras das fundas são como cisco para ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13918, 'nvi', 'Jó', 'jó', 41, 29, 'O bastão lhe parece fiapo de palha; o brandir da grande lança o faz rir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13919, 'nvi', 'Jó', 'jó', 41, 30, 'Seu ventre é como caco denteado, e deixa rastro na lama como o trilho de debulhar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13920, 'nvi', 'Jó', 'jó', 41, 31, 'Ele faz as profundezas se agitarem como caldeirão fervente, e revolve o mar como pote de ungüento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13921, 'nvi', 'Jó', 'jó', 41, 32, 'Deixa atrás de si um rastro cintilante; como se fossem os cabelos brancos do abismo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13922, 'nvi', 'Jó', 'jó', 41, 33, 'Nada na terra se equipara a ele; criatura destemida!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13923, 'nvi', 'Jó', 'jó', 41, 34, 'Com desdém olha todos os altivos; reina soberano sobre todos os orgulhosos".');
