-- Inserções para Jó 30
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13559, 'nvi', 'Jó', 'jó', 30, 1, '"Mas agora eles zombam de mim, homens mais jovens que eu, homens cujos pais eu teria rejeitado, não lhes permitindo sequer estar com os cães de guarda do rebanho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13560, 'nvi', 'Jó', 'jó', 30, 2, 'De que me serviria a força de suas mãos, já que desapareceu o seu vigor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13561, 'nvi', 'Jó', 'jó', 30, 3, 'Desfigurados de tanta necessidade e fome, perambulavam pela terra ressequida, em sombrios e devastados desertos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13562, 'nvi', 'Jó', 'jó', 30, 4, 'Nos campos de mato rasteiro colhiam ervas, e a raiz da giesta era a sua comida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13563, 'nvi', 'Jó', 'jó', 30, 5, 'Da companhia dos amigos foram expulsos aos gritos, como se fossem ladrões.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13564, 'nvi', 'Jó', 'jó', 30, 6, 'Foram forçados a morar nos leitos secos dos rios, entre as rochas e nos buracos da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13565, 'nvi', 'Jó', 'jó', 30, 7, 'Rugiam entre os arbustos e se encolhiam sob a vegetação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13566, 'nvi', 'Jó', 'jó', 30, 8, 'Prole desprezível e sem nome, foram expulsos da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13567, 'nvi', 'Jó', 'jó', 30, 9, '"E agora os filhos deles zombam de mim com suas canções; tornei-me um provérbio entre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13568, 'nvi', 'Jó', 'jó', 30, 10, 'Eles me detestam e se mantêm à distância; não hesitam em cuspir em meu rosto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13569, 'nvi', 'Jó', 'jó', 30, 11, 'Agora que Deus afrouxou a corda do meu arco e me afligiu, eles ficam sem freios na minha presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13570, 'nvi', 'Jó', 'jó', 30, 12, 'À direita os embrutecidos me atacam; preparam armadilhas para os meus pés, e constroem rampas de cerco contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13571, 'nvi', 'Jó', 'jó', 30, 13, 'Destroem o meu caminho; conseguem destruir-me, sem a ajuda de ninguém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13572, 'nvi', 'Jó', 'jó', 30, 14, 'Avançam como através de uma grande brecha; arrojam-se entre as ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13573, 'nvi', 'Jó', 'jó', 30, 15, 'Pavores apoderam-se de mim; a minha dignidade é levada como pelo vento, a minha segurança se desfaz como nuvem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13574, 'nvi', 'Jó', 'jó', 30, 16, '"E agora esvai-se a minha vida; estou preso a dias de sofrimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13575, 'nvi', 'Jó', 'jó', 30, 17, 'A noite penetra os meus ossos; minhas dores me corroem sem cessar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13576, 'nvi', 'Jó', 'jó', 30, 18, 'Em seu grande poder Deus é como a minha roupa; ele me envolve como a gola da minha veste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13577, 'nvi', 'Jó', 'jó', 30, 19, 'Lança-me na lama, e sou reduzido a pó e cinza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13578, 'nvi', 'Jó', 'jó', 30, 20, '"Clamo a ti, ó Deus, mas não respondes; fico de pé, mas apenas olhas para mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13579, 'nvi', 'Jó', 'jó', 30, 21, 'Contra mim te voltas com dureza e me atacas com a força de tua mão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13580, 'nvi', 'Jó', 'jó', 30, 22, 'Tu me apanhas e me levas contra o vento, e me jogas de um lado a outro na tempestade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13581, 'nvi', 'Jó', 'jó', 30, 23, 'Sei que me farás descer até a morte, ao lugar destinado a todos os viventes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13582, 'nvi', 'Jó', 'jó', 30, 24, '"A verdade é que ninguém dá a mão ao homem arruinado, quando este, em sua aflição, grita por socorro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13583, 'nvi', 'Jó', 'jó', 30, 25, 'Não é certo que chorei por causa dos que passavam dificuldade? E que a minha alma entristeceu-se por causa dos pobres?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13584, 'nvi', 'Jó', 'jó', 30, 26, 'Mesmo assim, quando eu esperava o bem, veio o mal; quando eu procurava luz, vieram trevas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13585, 'nvi', 'Jó', 'jó', 30, 27, 'Nunca pára a agitação dentro de mim; dias de sofrimento me confrontam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13586, 'nvi', 'Jó', 'jó', 30, 28, 'Perambulo escurecido, mas não pelo sol; levanto-me na assembléia e clamo por ajuda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13587, 'nvi', 'Jó', 'jó', 30, 29, 'Tornei-me irmão dos chacais, companheiro das corujas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13588, 'nvi', 'Jó', 'jó', 30, 30, 'Minha pele escurece e cai; meu corpo queima de febre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13589, 'nvi', 'Jó', 'jó', 30, 31, 'Minha harpa está afinada para cantos fúnebres, e minha flauta para o som de pranto.');
