-- Inserções para Jó 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13053, 'nvi', 'Jó', 'jó', 9, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13054, 'nvi', 'Jó', 'jó', 9, 2, '"Bem sei que isso é verdade. Mas como pode o mortal ser justo diante de Deus?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13055, 'nvi', 'Jó', 'jó', 9, 3, 'Ainda que quisesse discutir com ele, não conseguiria argumentar nem uma vez em mil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13056, 'nvi', 'Jó', 'jó', 9, 4, 'Sua sabedoria é profunda, seu poder é imenso. Quem tentou resisti-lo e saiu ileso?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13057, 'nvi', 'Jó', 'jó', 9, 5, 'Ele transporta montanhas sem que elas o saibam, e em sua ira as põe de cabeça para baixo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13058, 'nvi', 'Jó', 'jó', 9, 6, 'Sacode a terra e a tira do lugar, e faz suas colunas tremerem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13059, 'nvi', 'Jó', 'jó', 9, 7, 'Fala com o sol, e ele não brilha; ele veda e esconde a luz das estrelas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13060, 'nvi', 'Jó', 'jó', 9, 8, 'Só ele estende os céus e anda sobre as ondas do mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13061, 'nvi', 'Jó', 'jó', 9, 9, 'Ele é o Criador da Ursa e do Órion, das Plêiades e das constelações do sul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13062, 'nvi', 'Jó', 'jó', 9, 10, 'Realiza maravilhas que não se podem perscrutar, milagres incontáveis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13063, 'nvi', 'Jó', 'jó', 9, 11, 'Quando passa por mim, não posso vê-lo; se passa junto de mim, não o percebo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13064, 'nvi', 'Jó', 'jó', 9, 12, 'Se ele apanha algo, quem pode pará-lo? Quem pode dizer-lhe: ‘O que fazes? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13065, 'nvi', 'Jó', 'jó', 9, 13, 'Deus não refreia a sua ira; até o séquito de Raabe encolheu-se diante dos seus pés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13066, 'nvi', 'Jó', 'jó', 9, 14, '"Como então poderei eu discutir com ele? Como achar palavras para com ele argumentar?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13067, 'nvi', 'Jó', 'jó', 9, 15, 'Embora inocente, eu seria incapaz de responder-lhe; poderia apenas implorar misericórdia ao meu Juiz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13068, 'nvi', 'Jó', 'jó', 9, 16, 'Mesmo que eu o chamasse e ele me respondesse, não creio que me daria ouvidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13069, 'nvi', 'Jó', 'jó', 9, 17, 'Ele me esmagaria com uma tempestade e sem motivo multiplicaria minhas feridas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13070, 'nvi', 'Jó', 'jó', 9, 18, 'Não me permitiria recuperar o fôlego, mas me engolfaria em agruras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13071, 'nvi', 'Jó', 'jó', 9, 19, 'Se é questão de força, ele é poderoso! E se é questão de justiça, quem o intimará?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13072, 'nvi', 'Jó', 'jó', 9, 20, 'Mesmo sendo eu inocente, minha boca me condenaria; se eu fosse íntegro, ela me declararia culpado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13073, 'nvi', 'Jó', 'jó', 9, 21, '"Conquanto eu seja íntegro, já não me importo comigo; desprezo a minha própria vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13074, 'nvi', 'Jó', 'jó', 9, 22, 'É tudo a mesma coisa; por isso digo: Ele destrói tanto o íntegro como o ímpio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13075, 'nvi', 'Jó', 'jó', 9, 23, 'Quando um flagelo causa morte repentina, ele zomba do desespero dos inocentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13076, 'nvi', 'Jó', 'jó', 9, 24, 'Quando um país cai nas mãos dos ímpios, ele venda os olhos de seus juízes. Se não é ele, quem é então? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13077, 'nvi', 'Jó', 'jó', 9, 25, '"Meus dias correm mais velozes que um atleta; eles voam sem um vislumbre de alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13078, 'nvi', 'Jó', 'jó', 9, 26, 'Passam como barcos de papiro, como águias que mergulham sobre as presas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13079, 'nvi', 'Jó', 'jó', 9, 27, 'Se eu disser: Vou esquecer a minha queixa, vou mudar o meu semblante e sorrir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13080, 'nvi', 'Jó', 'jó', 9, 28, 'ainda assim me apavoro com todos os meus sofrimentos, pois sei que não me considerarás inocente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13081, 'nvi', 'Jó', 'jó', 9, 29, 'Uma vez que já fui considerado culpado, por que deveria eu lutar em vão?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13082, 'nvi', 'Jó', 'jó', 9, 30, 'Mesmo que eu me lavasse com sabão e limpasse as minhas mãos com soda de lavadeira,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13083, 'nvi', 'Jó', 'jó', 9, 31, 'tu me atirarias num poço de lodo, para que até as minhas roupas me detestassem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13084, 'nvi', 'Jó', 'jó', 9, 32, '"Ele não é homem como eu, para que eu lhe responda, e nos enfrentemos em juízo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13085, 'nvi', 'Jó', 'jó', 9, 33, 'Se tão-somente houvesse alguém para servir de árbitro entre nós, para impor as mãos sobre nós dois,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13086, 'nvi', 'Jó', 'jó', 9, 34, 'alguém que afastasse de mim a vara de Deus, para que o seu terror não mais me assustasse!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13087, 'nvi', 'Jó', 'jó', 9, 35, 'Então eu falaria sem medo; mas não é esse o caso.');
