-- Inserções para Jó 38
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13795, 'nvi', 'Jó', 'jó', 38, 1, 'Então o Senhor respondeu a Jó do meio da tempestade. Disse ele:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13796, 'nvi', 'Jó', 'jó', 38, 2, '"Quem é esse que obscurece o meu conselho com palavras sem conhecimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13797, 'nvi', 'Jó', 'jó', 38, 3, 'Prepare-se como simples homem; vou fazer-lhe perguntas, e você me responderá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13798, 'nvi', 'Jó', 'jó', 38, 4, '"Onde você estava quando lancei os alicerces da terra? Responda-me, se é que você sabe tanto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13799, 'nvi', 'Jó', 'jó', 38, 5, 'Quem marcou os limites das suas dimensões? Vai ver que você sabe! E quem estendeu sobre ela a linha de medir?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13800, 'nvi', 'Jó', 'jó', 38, 6, 'E as suas bases, sobre o que foram postas? E quem colocou sua pedra de esquina,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13801, 'nvi', 'Jó', 'jó', 38, 7, 'enquanto as estrelas matutinas juntas cantavam e todos os anjos se regozijavam?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13802, 'nvi', 'Jó', 'jó', 38, 8, '"Quem represou o mar pondo-lhe portas, quando ele irrompeu do ventre materno,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13803, 'nvi', 'Jó', 'jó', 38, 9, 'quando o vesti de nuvens e em densas trevas o envolvi,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13804, 'nvi', 'Jó', 'jó', 38, 10, 'quando fixei os seus limites e lhe coloquei portas e barreiras,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13805, 'nvi', 'Jó', 'jó', 38, 11, 'quando eu lhe disse: Até aqui você pode vir, além deste ponto não, aqui faço parar suas ondas orgulhosas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13806, 'nvi', 'Jó', 'jó', 38, 12, '"Você já deu ordens à manhã ou mostrou à alvorada o seu lugar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13807, 'nvi', 'Jó', 'jó', 38, 13, 'para que ela apanhasse a terra pelas pontas e sacudisse dela os ímpios?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13808, 'nvi', 'Jó', 'jó', 38, 14, 'A terra toma forma como o barro sob o sinete; e tudo nela se vê como uma veste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13809, 'nvi', 'Jó', 'jó', 38, 15, 'Aos ímpios é negada a sua luz, e quebra-se o seu braço levantado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13810, 'nvi', 'Jó', 'jó', 38, 16, '"Você já foi até às nascentes do mar, ou já passeou pelas obscuras profundezas do abismo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13811, 'nvi', 'Jó', 'jó', 38, 17, 'As portas da morte lhe foram mostradas? Você viu as portas das densas trevas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13812, 'nvi', 'Jó', 'jó', 38, 18, 'Você faz idéia de quão imensas são as áreas da terra? Fale-me, se é que você sabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13813, 'nvi', 'Jó', 'jó', 38, 19, '"Como se vai ao lugar onde mora a luz? E onde está a residência das trevas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13814, 'nvi', 'Jó', 'jó', 38, 20, 'Poderá você conduzi-las ao lugar que lhes pertence? Conhece o caminho da habitação delas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13815, 'nvi', 'Jó', 'jó', 38, 21, 'Vai ver que conhece, pois você já tinha nascido! Você já viveu tantos anos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13816, 'nvi', 'Jó', 'jó', 38, 22, '"Acaso você entrou nos reservatórios de neve, já viu os depósitos de saraiva,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13817, 'nvi', 'Jó', 'jó', 38, 23, 'que eu guardo para os períodos de tribulação, para os dias de guerra e de combate?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13818, 'nvi', 'Jó', 'jó', 38, 24, 'Qual o caminho por onde se repartem os relâmpagos? Onde é que os ventos orientais são distribuídos sobre a terra?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13819, 'nvi', 'Jó', 'jó', 38, 25, 'Quem é que abre um canal para a chuva torrencial, e um caminho para a tempestade trovejante,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13820, 'nvi', 'Jó', 'jó', 38, 26, 'para fazer chover na terra em que não vive nenhum homem, no deserto onde não há ninguém,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13821, 'nvi', 'Jó', 'jó', 38, 27, 'para matar a sede do deserto árido e nele fazer brotar vegetação?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13822, 'nvi', 'Jó', 'jó', 38, 28, 'Acaso a chuva tem pai? Quem é o pai das gotas de orvalho?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13823, 'nvi', 'Jó', 'jó', 38, 29, 'De que ventre materno vem o gelo? E quem dá à luz a geada que cai dos céus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13824, 'nvi', 'Jó', 'jó', 38, 30, 'quando as águas se tornam duras como pedra e a superfície do abismo se congela?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13825, 'nvi', 'Jó', 'jó', 38, 31, '"Você pode amarrar as lindas Plêiades? Pode afrouxar as cordas do Órion?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13826, 'nvi', 'Jó', 'jó', 38, 32, 'Pode fazer surgir no tempo certo as constelações ou fazer sair a Ursa com os seus filhotes?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13827, 'nvi', 'Jó', 'jó', 38, 33, 'Você conhece as leis dos céus? Voce pode determinar o domínio de Deus sobre a terra?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13828, 'nvi', 'Jó', 'jó', 38, 34, '"Você é capaz de levantar a voz até às nuvens e cobrir-se com uma inundação?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13829, 'nvi', 'Jó', 'jó', 38, 35, 'É você que envia os relâmpagos, e eles lhe dizem: ‘Aqui estamos’?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13830, 'nvi', 'Jó', 'jó', 38, 36, 'Quem foi que deu sabedoria ao coração e entendimento à mente?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13831, 'nvi', 'Jó', 'jó', 38, 37, 'Quem é que tem sabedoria para avaliar as nuvens? Quem é capaz de despejar os cântaros de água dos céus,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13832, 'nvi', 'Jó', 'jó', 38, 38, 'quando o pó se endurece e os torrões de terra grudam uns nos outros?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13833, 'nvi', 'Jó', 'jó', 38, 39, '"É você que caça a presa para a leoa e satisfaz a fome dos leões,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13834, 'nvi', 'Jó', 'jó', 38, 40, 'quando se agacham em suas tocas ou ficam à espreita no matagal?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13835, 'nvi', 'Jó', 'jó', 38, 41, 'Quem dá alimento aos corvos quando os seus filhotes clamam a Deus e vagueiam por falta de comida?');
