-- Inserções para Jó 36
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13738, 'nvi', 'Jó', 'jó', 36, 1, 'Disse mais Eliú:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13739, 'nvi', 'Jó', 'jó', 36, 2, '"Peço-lhe que seja um pouco mais paciente comigo, e lhe mostrarei que se pode dizer mais verdades em defesa de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13740, 'nvi', 'Jó', 'jó', 36, 3, 'Vem de longe o meu conhecimento; atribuirei justiça ao meu Criador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13741, 'nvi', 'Jó', 'jó', 36, 4, 'Não tenha dúvida de que as minhas palavras não são falsas; quem está com você é a perfeição no conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13742, 'nvi', 'Jó', 'jó', 36, 5, '"Deus é poderoso, mas não despreza os homens; é poderoso e firme em seu propósito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13743, 'nvi', 'Jó', 'jó', 36, 6, 'Não poupa a vida dos ímpios, mas garante os direitos dos aflitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13744, 'nvi', 'Jó', 'jó', 36, 7, 'Não tira os seus olhos do justo; ele o coloca nos tronos com os reis e o exalta para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13745, 'nvi', 'Jó', 'jó', 36, 8, 'Mas, se os homens forem acorrentados, presos firmemente com as cordas da aflição,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13746, 'nvi', 'Jó', 'jó', 36, 9, 'e lhes dirá o que fizeram, que pecaram com arrogância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13747, 'nvi', 'Jó', 'jó', 36, 10, 'Ele os fará ouvir a correção e lhes ordenará que se arrependam do mal que praticaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13748, 'nvi', 'Jó', 'jó', 36, 11, 'Se lhe obedecerem e o servirem, serão prósperos até o fim dos seus dias e terão contentamento nos anos que lhes restam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13749, 'nvi', 'Jó', 'jó', 36, 12, 'Mas, se não obedecerem, perecerão à espada e morrerão na ignorância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13750, 'nvi', 'Jó', 'jó', 36, 13, '"Os que têm coração ímpio guardam ressentimento; mesmo quando ele os agrilhoa eles não clamam por socorro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13751, 'nvi', 'Jó', 'jó', 36, 14, 'Morrem em plena juventude entre os prostitutos dos santuários.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13752, 'nvi', 'Jó', 'jó', 36, 15, 'Mas aos que sofrem ele os livra em meio ao sofrimento; em sua aflição ele lhes fala.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13753, 'nvi', 'Jó', 'jó', 36, 16, '"Ele está atraindo você para longe das mandíbulas da aflição, para um lugar amplo e livre, para o conforto da mesa farta e seleta que você terá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13754, 'nvi', 'Jó', 'jó', 36, 17, 'Mas agora, farto sobre você é o julgamento que cabe aos ímpios; o julgamento e a justiça o pegaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13755, 'nvi', 'Jó', 'jó', 36, 18, 'Cuidado! Que ninguém o seduza com riquezas; não se deixe desviar por suborno, por maior que este seja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13756, 'nvi', 'Jó', 'jó', 36, 19, 'Acaso a sua riqueza, ou mesmo todos os seus grandes esforços, dariam a você apoio e alívio da aflição?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13757, 'nvi', 'Jó', 'jó', 36, 20, 'Não anseie pela noite, quando o povo é tirado dos seus lares.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13758, 'nvi', 'Jó', 'jó', 36, 21, 'Cuidado! Não se volte para a iniqüidade, que você parece preferir à aflição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13759, 'nvi', 'Jó', 'jó', 36, 22, '"Deus é exaltado em seu poder. Quem é mestre como ele?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13760, 'nvi', 'Jó', 'jó', 36, 23, 'Quem lhe prescreveu os seus caminhos, ou lhe disse: ‘Agiste mal’?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13761, 'nvi', 'Jó', 'jó', 36, 24, 'Lembre-se de exaltar as suas obras, às quais os homens dedicam cânticos de louvor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13762, 'nvi', 'Jó', 'jó', 36, 25, 'Toda a humanidade as vê; de lugares distantes os homens as contemplam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13763, 'nvi', 'Jó', 'jó', 36, 26, 'Como Deus é grande! Ultrapassa o nosso entendimento! Não há como calcular os anos da sua existência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13764, 'nvi', 'Jó', 'jó', 36, 27, '"Ele atrai as gotas de água, que se dissolvem e descem como chuva para os regatos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13765, 'nvi', 'Jó', 'jó', 36, 28, 'as nuvens as despejam em aguaceiros sobre a humanidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13766, 'nvi', 'Jó', 'jó', 36, 29, 'Quem pode entender como ele estende as suas nuvens, como ele troveja desde o seu pavilhão?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13767, 'nvi', 'Jó', 'jó', 36, 30, 'Observe como ele espalha os seus relâmpagos ao redor, iluminando até as profundezas do mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13768, 'nvi', 'Jó', 'jó', 36, 31, 'É assim que ele governa as nações e lhes fornece grande fartura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13769, 'nvi', 'Jó', 'jó', 36, 32, 'Ele enche as mãos de relâmpagos e lhes determina o alvo que deverão atingir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13770, 'nvi', 'Jó', 'jó', 36, 33, 'Seu trovão anuncia a tempestade que está a caminho; até o gado a pressente.');
