-- Inserções para Jó 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13130, 'nvi', 'Jó', 'jó', 12, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13131, 'nvi', 'Jó', 'jó', 12, 2, '"Sem dúvida vocês são o povo, e a sabedoria morrerá com vocês!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13132, 'nvi', 'Jó', 'jó', 12, 3, 'Mas eu tenho a mesma capacidade de pensar que vocês têm; não sou inferior a vocês. Quem não sabe dessas coisas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13133, 'nvi', 'Jó', 'jó', 12, 4, '"Tornei-me objeto de riso para os meus amigos, eu que clamava a Deus e ele me respondia, eu, íntegro e irrepreensível, um mero objeto de riso!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13134, 'nvi', 'Jó', 'jó', 12, 5, 'Quem está bem despreza a desgraça, o destino daqueles cujos pés escorregam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13135, 'nvi', 'Jó', 'jó', 12, 6, 'As tendas dos saqueadores não sofrem perturbação, e aqueles que provocam a Deus estão seguros, aqueles que transportam o seu deus em suas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13136, 'nvi', 'Jó', 'jó', 12, 7, '"Pergunte, porém, aos animais, e eles o ensinarão, ou às aves do céu, e elas lhe contarão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13137, 'nvi', 'Jó', 'jó', 12, 8, 'fale com a terra, e ela o instruirá, deixe que os peixes do mar o informem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13138, 'nvi', 'Jó', 'jó', 12, 9, 'Quem de todos eles ignora que a mão do Senhor fez isso?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13139, 'nvi', 'Jó', 'jó', 12, 10, 'Em sua mão está a vida de cada criatura e o fôlego de toda a humanidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13140, 'nvi', 'Jó', 'jó', 12, 11, 'O ouvido não experimenta as palavras como a língua experimenta a comida?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13141, 'nvi', 'Jó', 'jó', 12, 12, 'A sabedoria se acha entre os idosos? A vida longa traz entendimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13142, 'nvi', 'Jó', 'jó', 12, 13, '"Deus é que tem sabedoria e poder; a ele pertencem o conselho e o entendimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13143, 'nvi', 'Jó', 'jó', 12, 14, 'O que ele derruba não se pode reconstruir; aquele a quem ele aprisiona ninguém pode libertar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13144, 'nvi', 'Jó', 'jó', 12, 15, 'Se ele retém as águas, predomina a seca; se as solta, devastam a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13145, 'nvi', 'Jó', 'jó', 12, 16, 'A ele pertencem a força e a sabedoria; tanto o enganado quanto o enganador a ele pertencem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13146, 'nvi', 'Jó', 'jó', 12, 17, 'Ele despoja e demite os conselheiros, e faz os juízes de tolos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13147, 'nvi', 'Jó', 'jó', 12, 18, 'Tira as algemas postas pelos reis, e amarra uma faixa em torno da cintura deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13148, 'nvi', 'Jó', 'jó', 12, 19, 'Despoja e demite os sacerdotes, e arruína os homens de sólida posição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13149, 'nvi', 'Jó', 'jó', 12, 20, 'Cala os lábios dos conselheiros de confiança, e tira o discernimento dos anciãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13150, 'nvi', 'Jó', 'jó', 12, 21, 'Derrama desprezo sobre os nobres, e desarma os poderosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13151, 'nvi', 'Jó', 'jó', 12, 22, 'Revela coisas profundas das trevas, e traz à luz densas sombras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13152, 'nvi', 'Jó', 'jó', 12, 23, 'Dá grandeza às nações, e as destrói; faz crescer as nações, e as dispersa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13153, 'nvi', 'Jó', 'jó', 12, 24, 'Priva da razão os líderes da terra, e os envia a perambular num deserto sem caminhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13154, 'nvi', 'Jó', 'jó', 12, 25, 'Andam tateando nas trevas, sem nenhuma luz; ele os faz cambalear como bêbados.');
