-- Inserções para Jó 42
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13924, 'nvi', 'Jó', 'jó', 42, 1, 'Então Jó respondeu ao Senhor:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13925, 'nvi', 'Jó', 'jó', 42, 2, '"Sei que podes fazer todas as coisas; nenhum dos teus planos pode ser frustrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13926, 'nvi', 'Jó', 'jó', 42, 3, 'Tu perguntaste: ‘Quem é esse que obscurece o meu conselho sem conhecimento? ’ Certo é que falei de coisas que eu não entendia, coisas tão maravilhosas que eu não poderia saber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13927, 'nvi', 'Jó', 'jó', 42, 4, '"Tu disseste: ‘Agora escute, e eu falarei; vou fazer-lhe perguntas, e você me responderá’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13928, 'nvi', 'Jó', 'jó', 42, 5, 'Meus ouvidos já tinham ouvido a teu respeito, mas agora os meus olhos te viram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13929, 'nvi', 'Jó', 'jó', 42, 6, 'Por isso menosprezo a mim mesmo e me arrependo no pó e na cinza".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13930, 'nvi', 'Jó', 'jó', 42, 7, 'Depois que o Senhor disse essas palavras a Jó, disse também ao Elifaz, de Temã: "Estou indignado com você e com os seus dois amigos, pois vocês não falaram o que é certo a meu respeito, como fez meu servo Jó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13931, 'nvi', 'Jó', 'jó', 42, 8, 'Vão agora até meu servo Jó, levem sete novilhos e sete carneiros, e com eles apresentem holocaustos em favor de vocês mesmos. Meu servo Jó orará por vocês; eu aceitarei a oração dele e não farei com vocês o que vocês merecem pela loucura que cometeram. Vocês não falaram o que é certo a meu respeito, como fez meu servo Jó".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13932, 'nvi', 'Jó', 'jó', 42, 9, 'Então Elifaz, de Temã, Bildade, de Suá, e Zofar, de Naamate, fizeram o que o Senhor lhes ordenara; e o Senhor aceitou a oração de Jó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13933, 'nvi', 'Jó', 'jó', 42, 10, 'Depois que Jó orou por seus amigos, o Senhor o tornou novamente próspero e lhe deu em dobro tudo o que tinha antes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13934, 'nvi', 'Jó', 'jó', 42, 11, 'Todos os seus irmãos e irmãs, e todos os que o haviam conhecido anteriormente vieram comer com ele em sua casa. Eles o consolaram e o confortaram por todas as tribulações que o Senhor tinha trazido sobre ele, e cada um lhe deu uma peça de prata e um anel de ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13935, 'nvi', 'Jó', 'jó', 42, 12, 'O Senhor abençoou o final da vida de Jó mais do que o início. Ele teve catorze mil ovelhas, seis mil camelos, mil juntas de boi e mil jumentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13936, 'nvi', 'Jó', 'jó', 42, 13, 'Também teve ainda sete filhos e três filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13937, 'nvi', 'Jó', 'jó', 42, 14, 'À primeira filha deu o nome de Jemima, à segunda o de Quézia e à terceira o de Quéren-Hapuque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13938, 'nvi', 'Jó', 'jó', 42, 15, 'Em parte alguma daquela terra havia mulheres tão bonitas como as filhas de Jó, e seu pai lhes deu herança junto com os seus irmãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13939, 'nvi', 'Jó', 'jó', 42, 16, 'Depois disso Jó viveu cento e quarenta anos; viu seus filhos e os descendentes deles até a quarta geração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13940, 'nvi', 'Jó', 'jó', 42, 17, 'E então morreu, em idade muito avançada.');
