-- Inserções para Jó 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12953, 'nvi', 'Jó', 'jó', 5, 1, '"Clame, se quiser, mas quem o ouvirá? Para qual dos seres celestes você se voltará?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12954, 'nvi', 'Jó', 'jó', 5, 2, 'O ressentimento mata o insensato, e a inveja destrói o tolo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12955, 'nvi', 'Jó', 'jó', 5, 3, 'Eu mesmo já vi um insensato lançar raízes, mas de repente a sua casa foi amaldiçoada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12956, 'nvi', 'Jó', 'jó', 5, 4, 'Seus filhos longe estão de desfrutar segurança, maltratados nos tribunais, não há quem os defenda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12957, 'nvi', 'Jó', 'jó', 5, 5, 'Os famintos devoram a sua colheita, tirando-a até do meio dos espinhos, e os sedentos sugam a sua riqueza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12958, 'nvi', 'Jó', 'jó', 5, 6, 'Pois o sofrimento não brota do pó, e as dificuldades não nascem do chão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12959, 'nvi', 'Jó', 'jó', 5, 7, 'No entanto o homem nasce para as dificuldades tão certamente como as fagulhas voam para cima.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12960, 'nvi', 'Jó', 'jó', 5, 8, '"Mas, se fosse comigo, eu apelaria para Deus; apresentaria a ele a minha causa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12961, 'nvi', 'Jó', 'jó', 5, 9, 'Ele realiza maravilhas insondáveis, milagres que não se pode contar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12962, 'nvi', 'Jó', 'jó', 5, 10, 'Derrama chuva sobre a terra, e envia água sobre os campos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12963, 'nvi', 'Jó', 'jó', 5, 11, 'Os humildes, ele os exalta, e traz os que pranteiam a um lugar de segurança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12964, 'nvi', 'Jó', 'jó', 5, 12, 'Ele frustra os planos dos astutos, para que fracassem as mãos deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12965, 'nvi', 'Jó', 'jó', 5, 13, 'Apanha os sábios na astúcia deles, e as maquinações dos astutos são malogradas por sua precipitação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12966, 'nvi', 'Jó', 'jó', 5, 14, 'As trevas vêm sobre eles em pleno dia; ao meio-dia eles tateiam como se fosse noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12967, 'nvi', 'Jó', 'jó', 5, 15, 'Ele salva o oprimido da espada que trazem na boca; salva-o das garras dos poderosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12968, 'nvi', 'Jó', 'jó', 5, 16, 'Por isso os pobres têm esperança, e a injustiça cala a boca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12969, 'nvi', 'Jó', 'jó', 5, 17, '"Como é feliz o homem a quem Deus corrige; portanto, não despreze a disciplina do Todo-poderoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12970, 'nvi', 'Jó', 'jó', 5, 18, 'Pois ele fere, mas dela vem tratar; ele machuca, mas suas mãos também curam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12971, 'nvi', 'Jó', 'jó', 5, 19, 'De seis desgraças ele o livrará; em sete delas você nada sofrerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12972, 'nvi', 'Jó', 'jó', 5, 20, 'Na fome ele o livrará da morte, e na guerra o livrará do golpe da espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12973, 'nvi', 'Jó', 'jó', 5, 21, 'Você será protegido do açoite da língua, e não precisará ter medo quando a destruição chegar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12974, 'nvi', 'Jó', 'jó', 5, 22, 'Você rirá da destruição e da fome, e não precisará temer as feras da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12975, 'nvi', 'Jó', 'jó', 5, 23, 'Pois fará aliança com as pedras do campo, e os animais selvagens estarão em paz com você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12976, 'nvi', 'Jó', 'jó', 5, 24, 'Você saberá que a sua tenda é segura; contará os seus bens da tua morada e de nada achará falta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12977, 'nvi', 'Jó', 'jó', 5, 25, 'Você saberá que os seus filhos serão muitos, e que os seus descendentes serão como a relva da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12978, 'nvi', 'Jó', 'jó', 5, 26, 'Você irá para a sepultura em pleno vigor, como um feixe recolhido no devido tempo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12979, 'nvi', 'Jó', 'jó', 5, 27, '"Foi isso que verificamos ser verdade. Portanto, ouça e aplique isso à sua vida".');
