-- Inserções para Jó 15
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13205, 'nvi', 'Jó', 'jó', 15, 1, 'Então Elifaz, de Temã, respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13206, 'nvi', 'Jó', 'jó', 15, 2, '"Responderia o sábio com idéias vãs, ou encheria o estômago com o vento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13207, 'nvi', 'Jó', 'jó', 15, 3, 'Será que argumentaria com palavras inúteis, com discursos sem valor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13208, 'nvi', 'Jó', 'jó', 15, 4, 'Mas você sufoca a piedade e diminui a devoção a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13209, 'nvi', 'Jó', 'jó', 15, 5, 'O seu pecado motiva a sua boca; você adota a linguagem dos astutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13210, 'nvi', 'Jó', 'jó', 15, 6, 'É a sua própria boca que o condena, e não a minha; os seus próprios lábios depõem contra você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13211, 'nvi', 'Jó', 'jó', 15, 7, '"Será que você foi o primeiro a nascer? Acaso foi gerado antes das colinas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13212, 'nvi', 'Jó', 'jó', 15, 8, 'Você costuma ouvir o conselho secreto de Deus? Só a você pertence a sabedoria?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13213, 'nvi', 'Jó', 'jó', 15, 9, 'Que é que você sabe, que nós não sabemos? Que compreensão têm você, que nós não temos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13214, 'nvi', 'Jó', 'jó', 15, 10, 'Temos do nosso lado homens de cabelos brancos, muito mais velhos que o seu pai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13215, 'nvi', 'Jó', 'jó', 15, 11, 'Não lhe bastam as consolações divinas, e as nossas palavras amáveis?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13216, 'nvi', 'Jó', 'jó', 15, 12, 'Por que você se deixa levar pelo coração, e por que esse brilho nos seus olhos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13217, 'nvi', 'Jó', 'jó', 15, 13, 'Pois contra Deus é que você dirige a sua ira e despeja da sua boca essas palavras!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13218, 'nvi', 'Jó', 'jó', 15, 14, '"Como o homem pode ser puro? Como pode ser justo quem nasce de mulher?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13219, 'nvi', 'Jó', 'jó', 15, 15, 'Pois se nem nos seus Deus confia, e se nem os céus são puros aos seus olhos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13220, 'nvi', 'Jó', 'jó', 15, 16, 'quanto menos o homem, que é impuro e corrupto, e que bebe iniqüidade como água.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13221, 'nvi', 'Jó', 'jó', 15, 17, '"Escute-me, e eu lhe explicarei; vou dizer-lhe o que vi,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13222, 'nvi', 'Jó', 'jó', 15, 18, 'o que os sábios declaram, sem esconder o que receberam dos seus pais,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13223, 'nvi', 'Jó', 'jó', 15, 19, 'a quem foi dada a terra, e a mais ninguém; nenhum estrangeiro passou entre eles:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13224, 'nvi', 'Jó', 'jó', 15, 20, 'O ímpio sofre tormentos a vida toda, como também o homem cruel, nos poucos anos que lhe são reservados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13225, 'nvi', 'Jó', 'jó', 15, 21, 'Só ouve ruídos aterrorizantes; quando se sente em paz, ladrões o atacam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13226, 'nvi', 'Jó', 'jó', 15, 22, 'Não tem esperança de escapar das trevas; sente-se destinado ao fio da espada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13227, 'nvi', 'Jó', 'jó', 15, 23, 'Fica perambulando; é comida para os abutres; sabe muito bem que logo virão sobre ele as trevas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13228, 'nvi', 'Jó', 'jó', 15, 24, 'A aflição e a angústia o apavoram e o dominam; como um rei pronto para bater,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13229, 'nvi', 'Jó', 'jó', 15, 25, 'porque agitou os punhos contra Deus, e desafiou o Todo-poderoso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13230, 'nvi', 'Jó', 'jó', 15, 26, 'afrontando-o com arrogância com um escudo grosso e resistente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13231, 'nvi', 'Jó', 'jó', 15, 27, '"Apesar de ter o rosto coberto de gordura e a cintura estufada de carne,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13232, 'nvi', 'Jó', 'jó', 15, 28, 'habitará em cidades prestes a arruinar-se, em casas inabitáveis, caindo aos pedaços.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13233, 'nvi', 'Jó', 'jó', 15, 29, 'Nunca mais será rico; sua riqueza não durará, e os seus bens não se propagarão pela terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13234, 'nvi', 'Jó', 'jó', 15, 30, 'Não poderá escapar das trevas; o fogo chamuscará os seus renovos, e o sopro da boca de Deus o arrebatará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13235, 'nvi', 'Jó', 'jó', 15, 31, 'Que ele não se iluda em confiar no que não tem valor, pois nada receberá como compensação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13236, 'nvi', 'Jó', 'jó', 15, 32, 'Terá completa paga antes do tempo, e os seus ramos não florescerão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13237, 'nvi', 'Jó', 'jó', 15, 33, 'Ele será como a vinha despojada de suas uvas verdes, como a oliveira que perdeu a sua floração,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13238, 'nvi', 'Jó', 'jó', 15, 34, 'pois o companheirismo dos ímpios nada lhe trará, e o fogo devorará as tendas dos que gostam de subornar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13239, 'nvi', 'Jó', 'jó', 15, 35, 'Eles concebem maldade e dão à luz a iniqüidade; seu ventre gera engano".');
