-- Inserções para Jó 18
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13278, 'nvi', 'Jó', 'jó', 18, 1, 'Então Bildade, de Suá, respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13279, 'nvi', 'Jó', 'jó', 18, 2, '"Quando você vai parar de falar? Proceda com sensatez, e depois poderemos conversar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13280, 'nvi', 'Jó', 'jó', 18, 3, 'Por que somos considerados como animais, e somos ignorantes aos seus olhos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13281, 'nvi', 'Jó', 'jó', 18, 4, 'Ah você, que se dilacera de ira! Deve-se abandonar a terra por sua causa? Ou devem as rochas mudar de lugar?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13282, 'nvi', 'Jó', 'jó', 18, 5, '"A lâmpada do ímpio se apaga, e a chama do seu fogo se extingue.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13283, 'nvi', 'Jó', 'jó', 18, 6, 'Na sua tenda a luz se escurece; a lâmpada de sua vida se apaga.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13284, 'nvi', 'Jó', 'jó', 18, 7, 'O vigor dos seus passos se enfraquece, e os seus próprios planos lançam por terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13285, 'nvi', 'Jó', 'jó', 18, 8, 'Por seus próprios pés você se prende na rede, e se perde na sua malha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13286, 'nvi', 'Jó', 'jó', 18, 9, 'A armadilha o pega pelo calcanhar; o laço o prende firme.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13287, 'nvi', 'Jó', 'jó', 18, 10, 'O nó corredio está escondido na terra para pegá-lo, há uma armadilha em seu caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13288, 'nvi', 'Jó', 'jó', 18, 11, 'Terrores de todos os lados o assustam e o perseguem em todos os seus passos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13289, 'nvi', 'Jó', 'jó', 18, 12, 'A calamidade tem fome para alcançá-la, e a desgraça está à espera de sua queda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13290, 'nvi', 'Jó', 'jó', 18, 13, 'Ela consome partes da sua pele; o primogênito da morte devora os membros do seu corpo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13291, 'nvi', 'Jó', 'jó', 18, 14, 'Ele é arrancado da segurança de sua tenda, e o levam à força ao rei dos terrores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13292, 'nvi', 'Jó', 'jó', 18, 15, 'O fogo mora na tenda dele; espalham enxofre ardente sobre a sua habitação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13293, 'nvi', 'Jó', 'jó', 18, 16, 'Suas raízes secam-se embaixo, e seus ramos murcham em cima.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13294, 'nvi', 'Jó', 'jó', 18, 17, 'Sua lembrança desaparece da terra, e nome não tem, em parte alguma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13295, 'nvi', 'Jó', 'jó', 18, 18, 'É lançado da luz para as trevas; é banido do mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13296, 'nvi', 'Jó', 'jó', 18, 19, 'Não tem filhos nem descendentes entre o seu povo, nem lhe restou sobrevivente algum nos lugares onde antes vivia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13297, 'nvi', 'Jó', 'jó', 18, 20, 'Os homens do ocidente assustam-se com a sua ruína, e os do oriente enchem-se de pavor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13298, 'nvi', 'Jó', 'jó', 18, 21, 'É assim a habitação do perverso; essa é a situação de quem não conhece a Deus".');
