-- Inserções para Jó 21
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13357, 'nvi', 'Jó', 'jó', 21, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13358, 'nvi', 'Jó', 'jó', 21, 2, '"Escutem com atenção as minhas palavras; seja esse o consolo que vocês haverão de dar-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13359, 'nvi', 'Jó', 'jó', 21, 3, 'Suportem-me enquanto eu estiver falando; depois que eu falar poderão zombar de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13360, 'nvi', 'Jó', 'jó', 21, 4, '"Acaso é dos homens que me queixo? Por que não deveria eu estar impaciente?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13361, 'nvi', 'Jó', 'jó', 21, 5, 'Olhem para mim, e ficarão atônitos; tapem a boca com a mão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13362, 'nvi', 'Jó', 'jó', 21, 6, 'Quando penso nisso, fico aterrorizado; todo o meu corpo se põe a tremer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13363, 'nvi', 'Jó', 'jó', 21, 7, 'Por que vivem os ímpios? Por que chegam à velhice e aumentam seu poder?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13364, 'nvi', 'Jó', 'jó', 21, 8, 'Eles vêem os seus filhos estabelecidos ao seu redor, e os seus descendentes diante dos seus olhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13365, 'nvi', 'Jó', 'jó', 21, 9, 'Seus lares estão seguros e livres de medo; a vara de Deus não os vem ferir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13366, 'nvi', 'Jó', 'jó', 21, 10, 'Seus touros nunca deixam de procriar; suas vacas dão crias e não abortam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13367, 'nvi', 'Jó', 'jó', 21, 11, 'Eles soltam os seus filhos como um rebanho; seus pequeninos põem-se a dançar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13368, 'nvi', 'Jó', 'jó', 21, 12, 'Cantam, acompanhando a música do tamborim e da harpa; alegram-se ao som da flauta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13369, 'nvi', 'Jó', 'jó', 21, 13, 'Passam a vida na prosperidade e descem à sepultura em paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13370, 'nvi', 'Jó', 'jó', 21, 14, 'Contudo, dizem eles a Deus: ‘Deixa-nos! Não queremos conhecer os teus caminhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13371, 'nvi', 'Jó', 'jó', 21, 15, 'Quem é o Todo-poderoso, para que o sirvamos? Que vantagem nos dá orar a ele? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13372, 'nvi', 'Jó', 'jó', 21, 16, 'Mas não depende deles a prosperidade de que desfrutam; por isso fico longe do conselho dos ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13373, 'nvi', 'Jó', 'jó', 21, 17, '"Pois, quantas vezes a lâmpada dos ímpios se apaga? Quantas vezes a desgraça cai sobre eles, o destino que em sua ira Deus lhes dá?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13374, 'nvi', 'Jó', 'jó', 21, 18, 'Quantas vezes o vento os leva como palha, e o furacão os arrebata como cisco?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13375, 'nvi', 'Jó', 'jó', 21, 19, 'Dizem que Deus reserva o castigo de um homem para os seus filhos. Que ele mesmo o receba, para que aprenda a lição!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13376, 'nvi', 'Jó', 'jó', 21, 20, 'Que os seus próprios olhos vejam a sua ruína; que ele mesmo beba da ira do Todo-poderoso!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13377, 'nvi', 'Jó', 'jó', 21, 21, 'Pois, que lhe importará a família que deixa atrás de si quando chegar ao fim os meses que lhe foram destinados?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13378, 'nvi', 'Jó', 'jó', 21, 22, '"Haverá alguém que o ensine a conhecer a Deus, uma vez que ele julga até os de mais alta posição?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13379, 'nvi', 'Jó', 'jó', 21, 23, 'Um homem morre em pleno vigor, quando se sentia bem e seguro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13380, 'nvi', 'Jó', 'jó', 21, 24, 'tendo o corpo bem nutrido e os ossos cheios de tutano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13381, 'nvi', 'Jó', 'jó', 21, 25, 'Já outro morre tendo a alma amargurada, sem nada ter desfrutado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13382, 'nvi', 'Jó', 'jó', 21, 26, 'Um e outro jazem no pó, ambos cobertos de vermes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13383, 'nvi', 'Jó', 'jó', 21, 27, '"Sei muito bem o que vocês estão pensando, as suas conspirações contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13384, 'nvi', 'Jó', 'jó', 21, 28, '‘Onde está agora a casa do grande homem? ’, vocês perguntam. ‘Onde a tenda dos ímpios? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13385, 'nvi', 'Jó', 'jó', 21, 29, 'Vocês nunca fizeram perguntas aos que viajam? Não deram atenção ao que contam?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13386, 'nvi', 'Jó', 'jó', 21, 30, 'Que o mau é poupado da calamidade, e que do dia da ira recebe livramento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13387, 'nvi', 'Jó', 'jó', 21, 31, 'Quem o acusa lançando em rosto a sua conduta? Quem lhe retribui pelo mal que fez?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13388, 'nvi', 'Jó', 'jó', 21, 32, 'Pois o levam para o túmulo, e sobre a sua sepultura se mantém vigilância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13389, 'nvi', 'Jó', 'jó', 21, 33, 'Para ele é macio o terreno do vale; todos o seguem, e uma multidão incontável o precede.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13390, 'nvi', 'Jó', 'jó', 21, 34, '"Por isso, como podem vocês consolar-me com esses absurdos? O que sobra das suas respostas é pura falsidade! "');
