-- Inserções para Jó 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12906, 'nvi', 'Jó', 'jó', 3, 1, 'Depois disso Jó abriu a boca e amaldiçoou o dia do seu nascimento,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12907, 'nvi', 'Jó', 'jó', 3, 2, 'dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12908, 'nvi', 'Jó', 'jó', 3, 3, '"Pereça o dia do meu nascimento e a noite em que se disse: ‘Nasceu um menino! ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12909, 'nvi', 'Jó', 'jó', 3, 4, 'Transforme-se aquele dia em trevas, e Deus, lá do alto, não se importe com ele; não resplandeça a luz sobre ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12910, 'nvi', 'Jó', 'jó', 3, 5, 'Chamem-no de volta as trevas e a mais densa escuridão; coloque-se uma nuvem sobre ele e o negrume aterrorize a sua luz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12911, 'nvi', 'Jó', 'jó', 3, 6, 'Apoderem-se daquela noite densas trevas! Não seja ela incluída entre os dias do ano, nem faça parte de nenhum dos meses.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12912, 'nvi', 'Jó', 'jó', 3, 7, 'Seja aquela noite estéril, e nela não se ouçam brados de alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12913, 'nvi', 'Jó', 'jó', 3, 8, 'Amaldiçoem aquele dia os que amaldiçoam os dias e são capazes de atiçar o Leviatã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12914, 'nvi', 'Jó', 'jó', 3, 9, 'Fiquem escuras as suas estrelas matutinas, e espere ele em vão pela luz do sol e não veja os primeiros raios da alvorada,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12915, 'nvi', 'Jó', 'jó', 3, 10, 'pois não fechou as portas do ventre materno para evitar que eu contemplasse males.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12916, 'nvi', 'Jó', 'jó', 3, 11, '"Por que não morri ao nascer, e não pereci quando saí do ventre?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12917, 'nvi', 'Jó', 'jó', 3, 12, 'Por que houve joelhos para me receberem e seios para me amamentarem?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12918, 'nvi', 'Jó', 'jó', 3, 13, 'Agora eu bem poderia estar deitado em paz e achar repouso');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12919, 'nvi', 'Jó', 'jó', 3, 14, 'junto aos reis e conselheiros da terra, que construíram para si lugares que agora jazem em ruínas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12920, 'nvi', 'Jó', 'jó', 3, 15, 'com governantes que possuíam ouro, que enchiam suas casas de prata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12921, 'nvi', 'Jó', 'jó', 3, 16, 'Por que não me sepultaram como criança abortada, como um bebê que nunca viu a luz do dia?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12922, 'nvi', 'Jó', 'jó', 3, 17, 'Ali os ímpios já não se agitam, e ali os cansados permanecem em repouso;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12923, 'nvi', 'Jó', 'jó', 3, 18, 'os prisioneiros também desfrutam sossego, já não ouvem mais os gritos do feitor de escravos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12924, 'nvi', 'Jó', 'jó', 3, 19, 'Os simples e os poderosos ali estão, e o escravo está livre de seu senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12925, 'nvi', 'Jó', 'jó', 3, 20, '"Por que se dá luz aos infelizes, e vida aos de alma amargurada,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12926, 'nvi', 'Jó', 'jó', 3, 21, 'aos que anseiam pela morte, e esta não vem, e a procuram mais do que a um tesouro oculto,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12927, 'nvi', 'Jó', 'jó', 3, 22, 'aos que se enchem de alegria e exultam quando vão para a sepultura?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12928, 'nvi', 'Jó', 'jó', 3, 23, 'Por que se dá vida àquele cujo caminho é oculto, e a quem Deus fechou as saídas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12929, 'nvi', 'Jó', 'jó', 3, 24, 'Pois me vêm suspiros em vez de comida; meus gemidos transbordam como água.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12930, 'nvi', 'Jó', 'jó', 3, 25, 'O que eu temia veio sobre mim; o que eu receava me aconteceu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12931, 'nvi', 'Jó', 'jó', 3, 26, 'Não tenho paz, nem tranqüilidade, nem descanso; somente inquietação".');
