-- Inserções para Jó 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12980, 'nvi', 'Jó', 'jó', 6, 1, 'Então Jó respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12981, 'nvi', 'Jó', 'jó', 6, 2, '"Se tão-somente pudessem pesar a minha aflição e pôr na balança a minha desgraça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12982, 'nvi', 'Jó', 'jó', 6, 3, 'Veriam que o seu peso é maior que o da areia dos mares. Por isso as minhas palavras são tão impetuosas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12983, 'nvi', 'Jó', 'jó', 6, 4, 'As flechas do Todo-poderoso estão cravadas em mim, e o meu espírito suga delas o veneno; os terrores de Deus estão posicionados contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12984, 'nvi', 'Jó', 'jó', 6, 5, 'Zurra o jumento selvagem, se tiver capim? Muge o boi, se tiver forragem?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12985, 'nvi', 'Jó', 'jó', 6, 6, 'Come-se sem sal uma comida insípida? E a clara do ovo, tem algum sabor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12986, 'nvi', 'Jó', 'jó', 6, 7, 'Recuso-me a tocar nisso; esse tipo de comida causa-me repugnância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12987, 'nvi', 'Jó', 'jó', 6, 8, '"Se tão-somente fosse atendido o meu pedido, se Deus me concedesse o meu desejo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12988, 'nvi', 'Jó', 'jó', 6, 9, 'se Deus se dispusesse a esmagar-me, a soltar a mão protetora e eliminar-me!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12989, 'nvi', 'Jó', 'jó', 6, 10, 'Pois eu ainda teria o consolo, minha alegria em meio à dor implacável, de não ter negado as palavras do Santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12990, 'nvi', 'Jó', 'jó', 6, 11, '"Que esperança posso ter, se já não tenho forças? Como posso ter paciência, se não tenho futuro?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12991, 'nvi', 'Jó', 'jó', 6, 12, 'Acaso tenho a força da pedra? Acaso a minha carne é de bronze?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12992, 'nvi', 'Jó', 'jó', 6, 13, 'Haverá poder que me ajude, agora que os meus recursos se foram?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12993, 'nvi', 'Jó', 'jó', 6, 14, '"Um homem desesperado deve receber a compaixão de seus amigos, muito embora ele tenha abandonado o temor do Todo-poderoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12994, 'nvi', 'Jó', 'jó', 6, 15, 'Mas os meus irmãos enganaram-me como riachos temporários, como os riachos que transbordam');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12995, 'nvi', 'Jó', 'jó', 6, 16, 'quando o degelo os torna turvos e a neve que se derrete os faz encher,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12996, 'nvi', 'Jó', 'jó', 6, 17, 'mas que param de fluir no tempo da seca, e no calor desaparecem dos seus leitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12997, 'nvi', 'Jó', 'jó', 6, 18, 'As caravanas se desviam de suas rotas; sobem para lugares desertos e perecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12998, 'nvi', 'Jó', 'jó', 6, 19, 'Procuram água as caravanas de Temá, olham esperançosos os mercadores de Sabá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12999, 'nvi', 'Jó', 'jó', 6, 20, 'Ficam tristes, porque estavam confiantes; lá chegaram tão-somente para sofrer decepção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13000, 'nvi', 'Jó', 'jó', 6, 21, 'Pois agora vocês de nada me valeram; contemplam minha temível situação, e se enchem de medo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13001, 'nvi', 'Jó', 'jó', 6, 22, 'Alguma vez lhes pedi que me dessem alguma coisa? Ou que da sua riqueza pagassem resgate por mim?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13002, 'nvi', 'Jó', 'jó', 6, 23, 'Ou que me livrassem das mãos do inimigo? Ou que me libertassem das garras de quem me oprime?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13003, 'nvi', 'Jó', 'jó', 6, 24, '"Ensinem-me, e eu me calarei; mostrem-me onde errei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13004, 'nvi', 'Jó', 'jó', 6, 25, 'Como doem as palavras verdadeiras! Mas o que provam os argumentos de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13005, 'nvi', 'Jó', 'jó', 6, 26, 'Vocês pretendem corrigir o que digo e tratar como vento as palavras de um homem desesperado?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13006, 'nvi', 'Jó', 'jó', 6, 27, 'Vocês seriam capazes de pôr em sorteio o órfão e de vender um amigo por uma bagatela!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13007, 'nvi', 'Jó', 'jó', 6, 28, '"Mas agora, tenham a bondade de olhar para mim. Será que eu mentiria na frente de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13008, 'nvi', 'Jó', 'jó', 6, 29, 'Reconsiderem a questão, não sejam injutos; tornem a analisá-la, pois a minha integridade está em jogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13009, 'nvi', 'Jó', 'jó', 6, 30, 'Há alguma iniqüidade em meus lábios? Será que a minha boca não consegue discernir a maldade?');
