-- Inserções para Jó 32
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13630, 'nvi', 'Jó', 'jó', 32, 1, 'Então esses três homens pararam de responder a Jó, pois este se julgava justo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13631, 'nvi', 'Jó', 'jó', 32, 2, 'Mas Eliú, filho de Baraquel, de Buz, da família de Rão, indignou-se muito contra Jó, porque este se justificava a si mesmo diante de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13632, 'nvi', 'Jó', 'jó', 32, 3, 'Também se indignou contra os três amigos, pois não encontraram meios de refutar a Jó, e mesmo assim o tinham condenado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13633, 'nvi', 'Jó', 'jó', 32, 4, 'Eliú tinha ficado esperando para falar a Jó, porque eles eram mais velhos que ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13634, 'nvi', 'Jó', 'jó', 32, 5, 'Mas, quando viu que os três não tinham mais nada a dizer, indignou-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13635, 'nvi', 'Jó', 'jó', 32, 6, 'Então Eliú, filho de Baraquel, de Buz, falou: "Eu sou jovem, vocês têm idade. Por isso tive receio e não ousei dizer-lhes o que sei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13636, 'nvi', 'Jó', 'jó', 32, 7, 'Os que têm idade é que devem falar, pensava eu, os anos avançados é que devem ensinar sabedoria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13637, 'nvi', 'Jó', 'jó', 32, 8, 'Mas é o espírito dentro do homem que lhe dá entendimento, o sopro do Todo-poderoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13638, 'nvi', 'Jó', 'jó', 32, 9, 'Não são só os mais velhos, os sábios, não são só os de idade que entendem o que é certo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13639, 'nvi', 'Jó', 'jó', 32, 10, '"Por isso digo: Escutem-me; também vou dizer o que sei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13640, 'nvi', 'Jó', 'jó', 32, 11, 'Enquanto vocês estavam falando, esperei; fiquei ouvindo os seus arrazoados; enquanto vocês estavam procurando palavras,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13641, 'nvi', 'Jó', 'jó', 32, 12, 'dei-lhes total atenção. Mas não é que nenhum de vocês demonstrou que Jó está errado? Nenhum de vocês respondeu aos seus argumentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13642, 'nvi', 'Jó', 'jó', 32, 13, 'Não digam: ‘Encontramos a sabedoria; que Deus o refute, não o homem’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13643, 'nvi', 'Jó', 'jó', 32, 14, 'Só que não foi contra mim que Jó dirigiu as suas palavras, e não vou responder a ele com os argumentos de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13644, 'nvi', 'Jó', 'jó', 32, 15, '"Vejam eles estão consternados e não têm mais o que dizer; as palavras lhes fugiram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13645, 'nvi', 'Jó', 'jó', 32, 16, 'Devo aguardar, agora que estão calados e sem resposta?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13646, 'nvi', 'Jó', 'jó', 32, 17, 'Também vou dar a minha opinião, também vou dizer o que sei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13647, 'nvi', 'Jó', 'jó', 32, 18, 'pois não me faltam palavras, e dentro de mim o espírito me impulsiona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13648, 'nvi', 'Jó', 'jó', 32, 19, 'Por dentro estou como vinho arrolhado, como vasilhas de couro novas prestes a romper.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13649, 'nvi', 'Jó', 'jó', 32, 20, 'Tenho que falar. Isso me aliviará. Tenho que abrir os lábios e responder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13650, 'nvi', 'Jó', 'jó', 32, 21, 'Não serei parcial com ninguém, e a ninguém bajularei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13651, 'nvi', 'Jó', 'jó', 32, 22, 'porque não sou bom em bajular; se fosse, o meu Criador em breve me levaria.');
