-- Inserções para Jó 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13155, 'nvi', 'Jó', 'jó', 13, 1, '"Meus olhos viram tudo isso, meus ouvidos o ouviram e entenderam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13156, 'nvi', 'Jó', 'jó', 13, 2, 'O que vocês sabem, eu também sei; não sou inferior a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13157, 'nvi', 'Jó', 'jó', 13, 3, 'Mas desejo falar ao Todo-poderoso e defender a minha causa diante de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13158, 'nvi', 'Jó', 'jó', 13, 4, 'Vocês, porém, me difamam com mentiras; todos vocês são médicos que de nada valem!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13159, 'nvi', 'Jó', 'jó', 13, 5, 'Se tão-somente ficassem calados! Mostrariam sabedoria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13160, 'nvi', 'Jó', 'jó', 13, 6, 'Escutem agora o meu argumento; prestem atenção à réplica de meus lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13161, 'nvi', 'Jó', 'jó', 13, 7, 'Vocês vão falar com maldade em nome de Deus? Vão falar enganosamente a favor dele?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13162, 'nvi', 'Jó', 'jó', 13, 8, 'Vão revelar parcialidade por ele? Vão defender a causa a favor de Deus?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13163, 'nvi', 'Jó', 'jó', 13, 9, 'Tudo iria bem, se ele os examinasse? Vocês conseguiriam enganá-lo, como podem enganar os homens?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13164, 'nvi', 'Jó', 'jó', 13, 10, 'Com certeza ele os repreenderia, se no íntimo vocês fossem parciais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13165, 'nvi', 'Jó', 'jó', 13, 11, 'O esplendor dele não os aterrorizaria? O pavor dele não cairia sobre vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13166, 'nvi', 'Jó', 'jó', 13, 12, 'As máximas que vocês citam são provérbios de cinza; suas defesas não passam de barro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13167, 'nvi', 'Jó', 'jó', 13, 13, '"Aquietem-se e deixem-me falar; e aconteça-me o que me acontecer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13168, 'nvi', 'Jó', 'jó', 13, 14, 'Por que me ponho em perigo e tomo a minha vida em minhas mãos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13169, 'nvi', 'Jó', 'jó', 13, 15, 'Embora ele me mate, ainda assim esperarei nele; certo é que defenderei os meus caminhos diante dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13170, 'nvi', 'Jó', 'jó', 13, 16, 'Aliás, isso será a minha libertação, pois nenhum ímpio ousaria apresentar-se a ele!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13171, 'nvi', 'Jó', 'jó', 13, 17, 'Escutem atentamente as minhas palavras; que os seus ouvidos acolham o que eu digo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13172, 'nvi', 'Jó', 'jó', 13, 18, 'Agora que preparei a minha defesa, sei que serei justificado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13173, 'nvi', 'Jó', 'jó', 13, 19, 'Haverá quem me acuse? Se houver, ficarei calado e morrerei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13174, 'nvi', 'Jó', 'jó', 13, 20, '"Concede-me só estas duas coisas, ó Deus, e não me esconderei de ti:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13175, 'nvi', 'Jó', 'jó', 13, 21, 'Afasta de mim a tua mão, e não mais me assuste com os teus terrores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13176, 'nvi', 'Jó', 'jó', 13, 22, 'Chama-me, e eu responderei, ou deixa-me falar, e tu responderás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13177, 'nvi', 'Jó', 'jó', 13, 23, 'Quantos erros e pecados cometi? Mostra-me a minha falta e o meu pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13178, 'nvi', 'Jó', 'jó', 13, 24, 'Por que escondes o teu rosto e consideras-me teu inimigo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13179, 'nvi', 'Jó', 'jó', 13, 25, 'Atormentarás uma folha levada pelo vento? Perseguirás a palha?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13180, 'nvi', 'Jó', 'jó', 13, 26, 'Pois fazes constar contra mim coisas amargas e fazes-me herdar os pecados da minha juventude.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13181, 'nvi', 'Jó', 'jó', 13, 27, 'Acorrentas os meus pés e vigias todos os meus caminhos, pondo limites aos meus passos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13182, 'nvi', 'Jó', 'jó', 13, 28, '"Assim o homem se consome como coisa podre, como a roupa que a traça vai roendo.');
