-- Inserções para Jó 20
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13328, 'nvi', 'Jó', 'jó', 20, 1, 'Então Zofar, de Naamate, respondeu:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13329, 'nvi', 'Jó', 'jó', 20, 2, '"Agitam-se os meus pensamentos e levam-me a responder porque estou profundamente perturbado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13330, 'nvi', 'Jó', 'jó', 20, 3, 'Ouvi uma repreensão que me desonra, e o meu entendimento faz-me contestar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13331, 'nvi', 'Jó', 'jó', 20, 4, '"Certamente você sabe que sempre foi assim, desde a antigüidade; desde que o homem foi posto na terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13332, 'nvi', 'Jó', 'jó', 20, 5, 'o riso dos maus é passageiro, e a alegria dos ímpios dura apenas um instante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13333, 'nvi', 'Jó', 'jó', 20, 6, 'Mesmo que o seu orgulho chegue aos céus e a sua cabeça toque as nuvens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13334, 'nvi', 'Jó', 'jó', 20, 7, 'ele perecerá para sempre, como o seu próprio excremento; os que o tinham visto perguntarão: ‘Onde ele foi parar? ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13335, 'nvi', 'Jó', 'jó', 20, 8, 'Ele voa e vai-se como um sonho, para nunca mais ser encontrado, banido como uma visão noturna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13336, 'nvi', 'Jó', 'jó', 20, 9, 'O olho que o viu não o verá mais, nem o seu lugar o tornará a ver.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13337, 'nvi', 'Jó', 'jó', 20, 10, 'Seus filhos têm que indenizar os pobres; ele próprio, com suas mãos, terá que refazer sua riqueza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13338, 'nvi', 'Jó', 'jó', 20, 11, 'O vigor juvenil que enche os seus ossos jazerá com ele no pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13339, 'nvi', 'Jó', 'jó', 20, 12, '"Mesmo que o mal seja doce em sua boca e ele o esconda sob a língua,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13340, 'nvi', 'Jó', 'jó', 20, 13, 'mesmo que o retenha na boca para saboreá-lo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13341, 'nvi', 'Jó', 'jó', 20, 14, 'ainda assim a sua comida azedará no estômago; e será como veneno de cobra em seu interior.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13342, 'nvi', 'Jó', 'jó', 20, 15, 'Ele vomitará as riquezas que engoliu; Deus fará seu estômago lançá-las fora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13343, 'nvi', 'Jó', 'jó', 20, 16, 'Sugará veneno de cobra; as presas de uma víbora o matarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13344, 'nvi', 'Jó', 'jó', 20, 17, 'Não terá gosto na contemplação dos regatos, e dos rios que vertem mel e nata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13345, 'nvi', 'Jó', 'jó', 20, 18, 'Terá que devolver aquilo pelo que lutou, sem aproveitá-lo, e não desfrutará dos lucros do seu comércio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13346, 'nvi', 'Jó', 'jó', 20, 19, 'Sim, pois ele tem oprimido os pobres e os tem deixado desamparados; apoderou-se de casas que não construiu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13347, 'nvi', 'Jó', 'jó', 20, 20, '"Certo é que a sua cobiça não lhe trará descanso, e o seu tesouro não o salvará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13348, 'nvi', 'Jó', 'jó', 20, 21, 'Nada lhe restou para devorar; sua prosperidade não durará muito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13349, 'nvi', 'Jó', 'jó', 20, 22, 'Em meio à sua fartura, a aflição o dominará; a força total da desgraça o atingirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13350, 'nvi', 'Jó', 'jó', 20, 23, 'Quando ele estiver de estômago cheio, Deus dará vazão às tremendas chamas de sua ira, e sobre ele despejará o seu furor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13351, 'nvi', 'Jó', 'jó', 20, 24, 'Se escapar da arma de ferro, o bronze da sua flecha o atravessará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13352, 'nvi', 'Jó', 'jó', 20, 25, 'Ele o arrancará das suas costas, a ponta reluzente saindo do seu fígado. Grande pavor virá sobre ele;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13353, 'nvi', 'Jó', 'jó', 20, 26, 'densas trevas estarão à espera dos seus tesouros. Um fogo não assoprado o consumirá e devorará o que sobrar em sua tenda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13354, 'nvi', 'Jó', 'jó', 20, 27, 'Os céus porão à mostra a sua culpa; a terra se levantará contra ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13355, 'nvi', 'Jó', 'jó', 20, 28, 'Uma inundação arrastará a sua casa, águas avassaladoras, no dia da ira de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (13356, 'nvi', 'Jó', 'jó', 20, 29, 'Esse é o destino que Deus dá aos ímpios, é a herança designada por Deus para eles".');
