-- Inserções para Lamentações de Jeremias 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20356, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 1, 'Eu sou o homem que viu a aflição trazida pela vara da sua ira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20357, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 2, 'Ele me impeliu e me fez andar na escuridão, e não na luz;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20358, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 3, 'sim, ele voltou sua mão contra mim vez após vez, o tempo todo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20359, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 4, 'Fez que a minha pele e a minha carne envelhecessem e quebrou os meus ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20360, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 5, 'Ele me sitiou e me cercou de amargura e de pesar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20361, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 6, 'Fez-me habitar na escuridão como os que há muito morreram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20362, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 7, 'Cercou-me de muros, e não posso escapar; atou-me a pesadas correntes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20363, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 8, 'Mesmo quando chamo ou grito por socorro, ele rejeita a minha oração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20364, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 9, 'Ele impediu o meu caminho com blocos de pedra; e fez tortuosas as minhas sendas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20365, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 10, 'Como um urso à espreita, como um leão escondido,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20366, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 11, 'arrancou-me do caminho e despedaçou-me, deixando-me abandonado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20367, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 12, 'Preparou o seu arco e me fez alvo de suas flechas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20368, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 13, 'Atingiu o meu coração com flechas de sua aljava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20369, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 14, 'Tornei-me motivo de riso de todo o meu povo; nas suas canções eles zombam de mim o tempo todo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20370, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 15, 'Fez-me comer ervas amargas e fartou-me de fel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20371, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 16, 'Quebrou os meus dentes com pedras; e pisoteou-me no pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20372, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 17, 'Tirou-me a paz; esqueci-me do que significa prosperidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20373, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 18, 'Por isso digo: "Meu esplendor já se foi, bem como tudo o que eu esperava do Senhor".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20374, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 19, 'Lembro-me da minha aflição e do meu delírio, da minha amargura e do meu pesar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20375, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 20, 'Lembro-me bem disso tudo, e a minha alma desfalece dentro de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20376, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 21, 'Todavia, lembro-me também do que pode dar-me esperança:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20377, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 22, 'Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20378, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 23, 'Renovam-se cada manhã; grande é a tua fidelidade!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20379, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 24, 'Digo a mim mesmo: A minha porção é o Senhor; portanto, nele porei a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20380, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 25, 'O Senhor é bom para com aqueles cuja esperança está nele, para com aqueles que o buscam;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20381, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 26, 'é bom esperar tranqüilo pela salvação do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20382, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 27, 'É bom que o homem suporte o jugo enquanto é jovem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20383, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 28, 'Leve-o sozinho e em silêncio, porque o Senhor o pôs sobre ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20384, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 29, 'Ponha o seu rosto no pó; talvez ainda haja esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20385, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 30, 'Ofereça o rosto a quem o quer ferir, e engula a desonra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20386, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 31, 'Porque o Senhor não o desprezará para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20387, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 32, 'Embora ele traga tristeza, mostrará compaixão, tão grande é o seu amor infalível.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20388, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 33, 'Porque não é do seu agrado trazer aflição e tristeza aos filhos dos homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20389, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 34, 'Esmagar com os pés todos os prisioneiros da terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20390, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 35, 'negar a alguém os seus direitos, enfrentando o Altíssimo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20391, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 36, 'impedir a alguém o acesso à justiça; não veria o Senhor tais coisas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20392, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 37, 'Quem poderá falar e fazer acontecer, se o Senhor não o tiver decretado?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20393, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 38, 'Não é da boca do Altíssimo que vêm tanto as desgraças como as bênçãos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20394, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 39, 'Como pode um homem reclamar quando é punido por seus pecados?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20395, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 40, 'Examinemos e submetamos à prova os nossos caminhos, e depois voltemos ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20396, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 41, 'Levantemos o coração e as mãos para Deus, que está nos céus, e digamos:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20397, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 42, '"Pecamos e nos rebelamos, e tu não nos perdoaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20398, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 43, 'Tu te cobriste de ira e nos perseguiste, massacraste-nos sem piedade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20399, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 44, 'Tu te escondeste atrás de uma nuvem para que nenhuma oração chegasse a ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20400, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 45, 'Tu nos tornaste escória e refugo entre as nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20401, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 46, 'Todos os nossos inimigos escancaram a boca contra nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20402, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 47, 'Sofremos terror e ciladas, ruína e destruição".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20403, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 48, 'Rios de lágrimas correm dos meus ohos porque o meu povo foi destruído.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20404, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 49, 'Meus olhos choram sem parar, sem nenhum descanso,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20405, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 50, 'até que o Senhor contemple dos céus e veja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20406, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 51, 'O que eu enxergo enche-me a alma de tristeza, de pena de todas as mulheres da minha cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20407, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 52, 'Aqueles que, sem motivo, eram meus inimigos caçaram-me como a um passarinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20408, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 53, 'Procuraram fazer minha vida acabar na cova e me jogaram pedras;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20409, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 54, 'as águas me encobriram a cabeça, e cheguei a pensar que o fim de tudo tinha chegado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20410, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 55, 'Clamei pelo teu nome, Senhor, das profundezas da cova.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20411, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 56, 'Tu ouviste o meu clamor: "Não feches os teus ouvidos aos meus gritos de socorro".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20412, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 57, 'Tu te aproximaste quando a ti clamei, e disseste: "Não tenha medo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20413, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 58, 'Senhor, tu assumiste a minha causa; e redimiste a minha vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20414, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 59, 'Tu tens visto, Senhor, o mal que me tem sido feito. Toma a teu cargo a minha causa!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20415, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 60, 'Tu viste como é terrível a vingança deles, todas as suas ciladas contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20416, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 61, 'Senhor, tu ouviste os seus insultos, todas as suas ciladas contra mim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20417, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 62, 'aquilo que os meus inimigos sussurram e murmuram o tempo todo contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20418, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 63, 'Olha para eles! Sentados ou em pé, zombam de mim com as suas canções.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20419, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 64, 'Dá-lhes o que merecem, Senhor, conforme o que as suas mãos têm feito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20420, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 65, 'Coloca um véu sobre os seus corações e esteja a tua maldição sobre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (20421, 'nvi', 'Lamentações de Jeremias', 'lm', 3, 66, 'Persegue-os com fúria e elimina-os de debaixo dos teus céus, ó Senhor.');
