-- Inserções para Levítico 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3236, 'nvi', 'Levítico', 'lv', 17, 1, 'O Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3237, 'nvi', 'Levítico', 'lv', 17, 2, '"Diga o seguinte a Arão e seus filhos e a todos os israelitas: Foi isto o que o Senhor ordenou:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3238, 'nvi', 'Levítico', 'lv', 17, 3, 'Qualquer israelita que sacrificar um boi, um cordeiro ou um cabrito dentro ou fora do acampamento,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3239, 'nvi', 'Levítico', 'lv', 17, 4, 'e não o trouxer à entrada da Tenda do Encontro para apresentá-lo como oferta ao Senhor, diante do tabernáculo do Senhor, será considerado culpado de sangue; derramou sangue e será eliminado do meio do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3240, 'nvi', 'Levítico', 'lv', 17, 5, 'Os sacrifícios, que os israelitas agora fazem em campo aberto, passarão a trazer ao Senhor, entregando-os ao sacerdote, para oferecê-los ao Senhor, à entrada da Tenda do Encontro, e os sacrificarão como ofertas de comunhão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3241, 'nvi', 'Levítico', 'lv', 17, 6, 'O sacerdote aspergirá o sangue no altar do Senhor, à entrada da Tenda do Encontro, e queimará a gordura como aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3242, 'nvi', 'Levítico', 'lv', 17, 7, 'Não oferecerão mais sacrifícios aos ídolos em forma de bode, aos quais prestam culto imoral. Este é um decreto perpétuo para eles e para as suas gerações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3243, 'nvi', 'Levítico', 'lv', 17, 8, '"Diga-lhes: Todo israelita ou estrangeiro residente que oferecer holocausto ou sacrifício,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3244, 'nvi', 'Levítico', 'lv', 17, 9, 'e não o trouxer à entrada da Tenda do Encontro para oferecê-lo ao Senhor, será eliminado do meio do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3245, 'nvi', 'Levítico', 'lv', 17, 10, '"Todo israelita ou estrangeiro residente que comer sangue de qualquer animal eu me voltarei contra esse que comeu sangue, e o eliminarei do meio do seu povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3246, 'nvi', 'Levítico', 'lv', 17, 11, 'Pois a vida da carne está no sangue, e eu o dei a vocês para fazerem propiciação por si mesmos no altar; é o sangue que faz propiciação pela vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3247, 'nvi', 'Levítico', 'lv', 17, 12, 'Por isso digo aos israelitas: nenhum de vocês poderá comer sangue, nem também o estrangeiro residente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3248, 'nvi', 'Levítico', 'lv', 17, 13, '"Qualquer israelita ou estrangeiro residente que caçar um animal ou ave que se pode comer, derramará o sangue e o cobrirá com terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3249, 'nvi', 'Levítico', 'lv', 17, 14, 'porque a vida de toda carne é o seu sangue. Por isso eu disse aos israelitas: vocês não poderão comer o sangue de nenhum animal, porque a vida de toda carne é o seu sangue; todo aquele que o comer será eliminado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3250, 'nvi', 'Levítico', 'lv', 17, 15, '"Todo aquele que, natural da terra ou estrangeiro, comer um animal encontrado morto ou despedaçado por animais selvagens, lavará suas roupas e se banhará com água, e ficará impuro até à tarde; então estará puro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3251, 'nvi', 'Levítico', 'lv', 17, 16, 'Mas, se não lavar as suas roupas nem se banhar, sofrerá as conseqüências da sua iniqüidade".');
