-- Inserções para Levítico 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2763, 'nvi', 'Levítico', 'lv', 2, 1, '"Quando alguém trouxer uma oferta de cereal ao Senhor, terá que ser da melhor farinha. Sobre ela derramará óleo, colocará incenso');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2764, 'nvi', 'Levítico', 'lv', 2, 2, 'e a levará aos descendentes de Arão, os sacerdotes. Um deles apanhará um punhado da melhor farinha com óleo, juntamente com todo o incenso, e o queimará no altar como porção memorial. É oferta preparada no fogo, de aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2765, 'nvi', 'Levítico', 'lv', 2, 3, 'O que restar da oferta de cereal pertence a Arão e a seus descendentes; é parte santíssima das ofertas dedicadas ao Senhor preparadas no fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2766, 'nvi', 'Levítico', 'lv', 2, 4, '"Se um de vocês trouxer uma oferta de cereal assada no forno, seja da melhor farinha: bolos feitos sem fermento, amassados com óleo, ou pães finos sem fermento e untados com óleo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2767, 'nvi', 'Levítico', 'lv', 2, 5, 'Se a sua oferta de cereal for preparada numa assadeira, seja da melhor farinha, amassada com óleo e sem fermento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2768, 'nvi', 'Levítico', 'lv', 2, 6, 'Divida-as em pedaços e derrame óleo sobre ela; é uma oferta de cereal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2769, 'nvi', 'Levítico', 'lv', 2, 7, 'Se a sua oferta de cereal for cozida numa panela, seja da melhor farinha com óleo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2770, 'nvi', 'Levítico', 'lv', 2, 8, 'Traga ao Senhor a oferta de cereal feita desses ingredientes, apresente-a ao sacerdote, que a levará ao altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2771, 'nvi', 'Levítico', 'lv', 2, 9, 'Ele apanhará a porção memorial da oferta de cereal e a queimará no altar; é oferta preparada no fogo, de aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2772, 'nvi', 'Levítico', 'lv', 2, 10, 'O restante da oferta de cereal pertence a Arão e a seus descendentes; é parte santíssima das ofertas dedicadas ao Senhor preparadas no fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2773, 'nvi', 'Levítico', 'lv', 2, 11, '"Nenhuma oferta de cereal que vocês trouxerem ao Senhor será feita com fermento, pois vocês não queimarão fermento nem mel como oferta preparada no fogo ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2774, 'nvi', 'Levítico', 'lv', 2, 12, 'Podem trazê-los como oferta dos primeiros frutos ao Senhor, mas não poderão oferecê-los no altar como aroma agradável.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2775, 'nvi', 'Levítico', 'lv', 2, 13, 'Tempere com sal todas as suas ofertas de cereal. Não exclua de suas ofertas de cereal o sal da aliança do seu Deus; acrescente sal a todas as suas ofertas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2776, 'nvi', 'Levítico', 'lv', 2, 14, '"Se você trouxer ao Senhor uma oferta de cereal dos primeiros frutos, ofereça grãos esmagados de cereal novo, tostados no fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2777, 'nvi', 'Levítico', 'lv', 2, 15, 'Sobre ela derrame óleo e coloque incenso; é oferta de cereal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2778, 'nvi', 'Levítico', 'lv', 2, 16, 'O sacerdote queimará a porção memorial do cereal esmagado e do óleo, juntamente com todo o incenso, como uma oferta ao Senhor, preparada no fogo. "');
