-- Inserções para Levítico 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2746, 'nvi', 'Levítico', 'lv', 1, 1, 'Da Tenda do Encontro o Senhor chamou Moisés e lhe ordenou:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2747, 'nvi', 'Levítico', 'lv', 1, 2, '"Diga o seguinte aos israelitas: Quando alguém trouxer um animal como oferta ao Senhor, que seja do gado ou do rebanho de ovelhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2748, 'nvi', 'Levítico', 'lv', 1, 3, '"Se o holocausto for de gado, oferecerá um macho sem defeito. Ele o apresentará à entrada da Tenda do Encontro para que seja aceito pelo Senhor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2749, 'nvi', 'Levítico', 'lv', 1, 4, 'e porá a mão sobre a cabeça do animal do holocausto para que seja aceito como propiciação em seu lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2750, 'nvi', 'Levítico', 'lv', 1, 5, 'Então o novilho será morto perante o Senhor, e os sacerdotes, descendentes de Arão, trarão o sangue e o derramarão nos lados do altar, que está na entrada da Tenda do Encontro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2751, 'nvi', 'Levítico', 'lv', 1, 6, 'Depois se tirará a pele do animal, que será cortado em pedaços.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2752, 'nvi', 'Levítico', 'lv', 1, 7, 'Então os descendentes do sacerdote Arão acenderão o fogo do altar e arrumarão a lenha sobre o fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2753, 'nvi', 'Levítico', 'lv', 1, 8, 'Em seguida arrumarão os pedaços, inclusive a cabeça e a gordura, sobre a lenha que está no fogo do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2754, 'nvi', 'Levítico', 'lv', 1, 9, 'As vísceras e as pernas serão lavadas com água. E o sacerdote queimará tudo isso no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2755, 'nvi', 'Levítico', 'lv', 1, 10, '"Se a oferta for um holocausto do rebanho, quer de cordeiros quer de cabritos, oferecerá um macho sem defeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2756, 'nvi', 'Levítico', 'lv', 1, 11, 'O animal será morto no lado norte do altar, perante o Senhor; os sacerdotes, descendentes de Arão, derramarão o sangue nos lados do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2757, 'nvi', 'Levítico', 'lv', 1, 12, 'Então o animal será cortado em pedaços. O sacerdote arrumará os pedaços, inclusive a cabeça e a gordura, sobre a lenha que está no fogo do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2758, 'nvi', 'Levítico', 'lv', 1, 13, 'As vísceras e as pernas serão lavadas com água. O sacerdote trará tudo isso como oferta e o queimará no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2759, 'nvi', 'Levítico', 'lv', 1, 14, '"Se a sua oferta ao Senhor for um holocausto de aves, traga uma rolinha ou um pombinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2760, 'nvi', 'Levítico', 'lv', 1, 15, 'O sacerdote trará a ave ao altar, destroncará o pescoço dela e a queimará, e deixará escorrer o sangue da ave na parede do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2761, 'nvi', 'Levítico', 'lv', 1, 16, 'Ele retirará o papo com o seu conteúdo e o jogará ao lado leste do altar, onde ficam as cinzas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2762, 'nvi', 'Levítico', 'lv', 1, 17, 'Rasgará a ave pelas asas, sem dividi-la totalmente, e então o sacerdote a queimará sobre a lenha acesa no altar. É um holocausto, oferta preparada no fogo, de aroma agradável ao Senhor".');
