-- Inserções para Levítico 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3045, 'nvi', 'Levítico', 'lv', 12, 1, 'Disse o Senhor a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3046, 'nvi', 'Levítico', 'lv', 12, 2, '"Diga aos israelitas: Quando uma mulher engravidar e der à luz um menino, estará impura por sete dias, assim como está impura durante o seu período menstrual.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3047, 'nvi', 'Levítico', 'lv', 12, 3, 'No oitavo dia o menino terá que ser circuncidado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3048, 'nvi', 'Levítico', 'lv', 12, 4, 'Então a mulher aguardará trinta e três dias para ser purificada do seu sangramento. Não poderá tocar em nenhuma coisa sagrada e não poderá ir ao santuário, até que se completem os dias da sua purificação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3049, 'nvi', 'Levítico', 'lv', 12, 5, 'Se der à luz uma menina, estará impura por duas semanas, como durante o seu período menstrual. Nesse caso aguardará sessenta e seis dias para ser purificada do seu sangramento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3050, 'nvi', 'Levítico', 'lv', 12, 6, '"Quando se completarem os dias da sua purificação pelo nascimento de um menino ou de uma menina, ela trará ao sacerdote, à entrada da Tenda do Encontro, um cordeiro de um ano para o holocausto e um pombinho ou uma rolinha como oferta pelo pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3051, 'nvi', 'Levítico', 'lv', 12, 7, 'Ele os oferecerá ao Senhor para fazer propiciação por ela, que ficará pura do fluxo do seu sangramento. Essa é a regulamentação para a mulher que der à luz um menino ou uma menina.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3052, 'nvi', 'Levítico', 'lv', 12, 8, 'Se ela não tiver recursos para oferecer um cordeiro, poderá trazer duas rolinhas ou dois pombinhos, um para o holocausto e o outro para a oferta pelo pecado. Assim o sacerdote fará propiciação por ela, e ela ficará pura".');
