-- Inserções para Levítico 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2779, 'nvi', 'Levítico', 'lv', 3, 1, '"Quando a oferta de alguém for sacrifício de comunhão, assim se fará: se oferecer um animal do gado, seja macho ou fêmea, apresentará ao Senhor um animal sem defeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2780, 'nvi', 'Levítico', 'lv', 3, 2, 'Porá a mão sobre a cabeça do animal, que será morto na entrada da Tenda do Encontro. Os descendentes de Arão, os sacerdotes, derramarão o sangue nos lados do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2781, 'nvi', 'Levítico', 'lv', 3, 3, 'Desse sacrifício de comunhão, oferta preparada no fogo, ele trará ao Senhor toda a gordura que cobre as vísceras e está ligada a elas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2782, 'nvi', 'Levítico', 'lv', 3, 4, 'os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2783, 'nvi', 'Levítico', 'lv', 3, 5, 'Os descendentes de Arão queimarão tudo isso em cima do holocausto que está sobre a lenha acesa no altar como oferta preparada no fogo, de aroma agradável ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2784, 'nvi', 'Levítico', 'lv', 3, 6, '"Se oferecer um animal do rebanho como sacrifício de comunhão ao Senhor, traga um macho ou fêmea sem defeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2785, 'nvi', 'Levítico', 'lv', 3, 7, 'Se oferecer um cordeiro, apresente-o ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2786, 'nvi', 'Levítico', 'lv', 3, 8, 'Porá a mão sobre a cabeça do animal, que será morto diante da Tenda do Encontro. Então os descendentes de Arão derramarão o sangue nos lados do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2787, 'nvi', 'Levítico', 'lv', 3, 9, 'Desse sacrifício de comunhão, oferta preparada no fogo, ele trará ao Senhor a gordura, tanto a da cauda gorda cortada rente à espinha, como toda a gordura que cobre as vísceras e está ligada a elas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2788, 'nvi', 'Levítico', 'lv', 3, 10, 'os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2789, 'nvi', 'Levítico', 'lv', 3, 11, 'O sacerdote os queimará no altar como alimento oferecido ao Senhor, preparado no fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2790, 'nvi', 'Levítico', 'lv', 3, 12, '"Se a sua oferta for um cabrito, ele o apresentará ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2791, 'nvi', 'Levítico', 'lv', 3, 13, 'Porá a mão sobre a cabeça do animal, que será morto diante da Tenda do Encontro. Então os descendentes de Arão derramarão o sangue nos lados do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2792, 'nvi', 'Levítico', 'lv', 3, 14, 'Desse animal, que é uma oferta preparada no fogo, trará ao Senhor a gordura que cobre as vísceras e está ligada a elas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2793, 'nvi', 'Levítico', 'lv', 3, 15, 'os dois rins com a gordura que os cobre e que está perto dos lombos, e o lóbulo do fígado, que ele removerá junto com os rins.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2794, 'nvi', 'Levítico', 'lv', 3, 16, 'O sacerdote os queimará no altar como alimento, como oferta feita com fogo, de aroma agradável. Toda a gordura será do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (2795, 'nvi', 'Levítico', 'lv', 3, 17, '"Este é um decreto perpétuo para as suas gerações, onde quer que vivam: Não comam gordura alguma, nem sangue algum".');
