-- Inserções para Miquéias 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22650, 'nvi', 'Miquéias', 'mq', 6, 1, 'Ouçam o que diz o Senhor: "Fique de pé, abra processo perante os montes; que as colinas ouçam o que você tem a dizer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22651, 'nvi', 'Miquéias', 'mq', 6, 2, 'Ouçam, ó montes, a acusação do Senhor; escutem, alicerces eternos da terra. Pois o Senhor tem uma acusação contra o seu povo; ele está entrando em juízo contra Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22652, 'nvi', 'Miquéias', 'mq', 6, 3, '"Meu povo, que foi que eu fiz contra você? Fui muito exigente? Responda-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22653, 'nvi', 'Miquéias', 'mq', 6, 4, 'Eu o tirei do Egito, e o redimi da terra da escravidão; enviei Moisés, Arão e Miriã para conduzi-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22654, 'nvi', 'Miquéias', 'mq', 6, 5, 'Meu povo, lembre-se do que Balaque, rei de Moabe, pediu e do que Balaão, filho de Beor, respondeu. Recorde a viagem que você fez desde Sitim até Gilgal, e reconheça que os atos do Senhor são justos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22655, 'nvi', 'Miquéias', 'mq', 6, 6, 'Com que eu poderia comparecer diante do Senhor e curvar-me perante o Deus exaltado? Deveria oferecer holocaustos de bezerros de um ano?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22656, 'nvi', 'Miquéias', 'mq', 6, 7, 'Ficaria o Senhor satisfeito com milhares de carneiros, com dez mil ribeiros de azeite? Devo oferecer o meu filho mais velho por causa da minha transgressão, o fruto do meu corpo por causa do meu próprio pecado?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22657, 'nvi', 'Miquéias', 'mq', 6, 8, 'Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige: Pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22658, 'nvi', 'Miquéias', 'mq', 6, 9, 'A voz do Senhor está clamando à cidade; é sensato temer o teu nome! "Ouçam, tribo de Judá e assembléia da cidade!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22659, 'nvi', 'Miquéias', 'mq', 6, 10, 'Não há, na casa do ímpio, o tesouro da impiedade, e a medida falsificada, que é maldita?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22660, 'nvi', 'Miquéias', 'mq', 6, 11, 'Poderia alguém ser puro com balanças desonestas e pesos falsos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22661, 'nvi', 'Miquéias', 'mq', 6, 12, 'Os ricos dentre vocês são violentos; o seu povo é mentiroso, e as suas línguas falam enganosamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22662, 'nvi', 'Miquéias', 'mq', 6, 13, 'Por isso, eu mesmo os farei sofrer e os arruinarei por causa dos seus pecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22663, 'nvi', 'Miquéias', 'mq', 6, 14, 'Vocês comerão, mas não ficarão satisfeitos; continuarão de estômago vazio. Vocês ajuntarão, mas nada preservarão, porquanto o que guardarem, à espada entregarei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22664, 'nvi', 'Miquéias', 'mq', 6, 15, 'Vocês plantarão, mas não colherão; espremerão azeitonas, mas não se ungirão com o azeite; espremerão uvas, mas não beberão o vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22665, 'nvi', 'Miquéias', 'mq', 6, 16, 'Porque vocês têm obedecido aos decretos de Onri e a todas as práticas da família de Acabe, e têm seguido as tradições deles. Por isso os entregarei à ruína e o seu povo ao desprezo; vocês sofrerão a zombaria das nações. "');
