-- Inserções para Miquéias 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22597, 'nvi', 'Miquéias', 'mq', 2, 1, 'Ai daqueles que planejam maldade, dos que tramam o mal em suas camas! Quando alvorece, eles o executam, porque isso eles podem fazer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22598, 'nvi', 'Miquéias', 'mq', 2, 2, 'Cobiçam terrenos e se apoderam deles; cobiçam casas e as tomam. Fazem violência ao homem e à sua família, a ele e aos seus herdeiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22599, 'nvi', 'Miquéias', 'mq', 2, 3, 'Portanto, assim diz o Senhor: "Estou planejando contra essa gente uma desgraça, da qual vocês não poderão salvar-se. Vocês já não vão andar com arrogância, pois será tempo de desgraça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22600, 'nvi', 'Miquéias', 'mq', 2, 4, 'Naquele dia vocês serão ridicularizados; zombarão de vocês com esta triste canção: ‘Estamos totalmente arruinados; dividida foi a propriedade do meu povo. Ele tirou-a de mim! Entregou a invasores as nossas terras’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22601, 'nvi', 'Miquéias', 'mq', 2, 5, 'Portanto, vocês não estarão na assembléia do Senhor para a divisão da terra por sorteio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22602, 'nvi', 'Miquéias', 'mq', 2, 6, '"Não preguem", dizem os seus profetas. "Não preguem acerca dessas coisas; a desgraça não nos alcançará". Ó descendência de Jacó,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22603, 'nvi', 'Miquéias', 'mq', 2, 7, 'é isto que está sendo falado: "O Espírito do Senhor perdeu a paciência? É assim que ele age? " "As minhas palavras não fazem bem àquele cujos caminhos são retos?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22604, 'nvi', 'Miquéias', 'mq', 2, 8, 'Mas ultimamente como inimigos vocês atacam o meu povo. Além da túnica arrancam a capa daqueles que passam confiantes, como quem volta da guerra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22605, 'nvi', 'Miquéias', 'mq', 2, 9, 'Vocês tiram as mulheres do meu povo de seus lares agradáveis. De seus filhos vocês removem a minha dignidade para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22606, 'nvi', 'Miquéias', 'mq', 2, 10, 'Levantem-se, vão embora! Pois este não é o lugar de descanso, porque ele está contaminado, está arruinado, sem que haja remédio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22607, 'nvi', 'Miquéias', 'mq', 2, 11, 'Se um mentiroso e enganador vier e disser: ‘Eu pregarei para vocês fartura de vinho e de bebida fermentada’, ele será o profeta deste povo! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22608, 'nvi', 'Miquéias', 'mq', 2, 12, '"Eu vou de fato ajuntar todos vocês, ó Jacó; sim, vou reunir o remanescente de Israel. Eu os ajuntarei como ovelhas num aprisco, como um rebanho numa pastagem; haverá barulho de muita gente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22609, 'nvi', 'Miquéias', 'mq', 2, 13, 'Aquele que abre o caminho irá adiante deles; passarão pela porta e sairão. O rei deles, o Senhor, os guiará".');
