-- Inserções para Miquéias 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22610, 'nvi', 'Miquéias', 'mq', 3, 1, 'Então eu disse: "Ouçam, vocês que são chefes de Jacó, governantes da nação de Israel. Vocês deveriam conhecer a justiça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22611, 'nvi', 'Miquéias', 'mq', 3, 2, 'Mas odeiam o bem e amam o mal; arrancam a pele do meu povo e a carne dos seus ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22612, 'nvi', 'Miquéias', 'mq', 3, 3, 'Aqueles que comem a carne do meu povo, arrancam a sua pele, despedaçam os seus ossos e cortam-no como se fosse carne para a panela,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22613, 'nvi', 'Miquéias', 'mq', 3, 4, 'um dia clamarão ao Senhor, mas ele não lhes responderá. Naquela tempo ele esconderá deles o rosto por causa do mal que eles têm feito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22614, 'nvi', 'Miquéias', 'mq', 3, 5, 'Assim diz o Senhor aos profetas que fazem o meu povo desviar-se; quando lhes dão o que mastigar, proclamam paz, mas proclamam guerra santa contra quem não lhes enche a boca:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22615, 'nvi', 'Miquéias', 'mq', 3, 6, 'Por tudo isso a noite virá sobre vocês, noite sem visões; haverá trevas, sem adivinhações. O sol se porá para os profetas, e o dia se escurecerá para eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22616, 'nvi', 'Miquéias', 'mq', 3, 7, 'Os videntes ficarão envergonhados, e os adivinhos constrangidos. Todos cobrirão o rosto porque não haverá resposta da parte de Deus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22617, 'nvi', 'Miquéias', 'mq', 3, 8, 'Mas, quanto a mim, graças ao poder do Espírito do Senhor, estou cheio de força e de justiça, para declarar a Jacó a sua transgressão, e a Israel o seu pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22618, 'nvi', 'Miquéias', 'mq', 3, 9, 'Ouçam isto, vocês que são chefes da descendência de Jacó, governantes da nação de Israel, que detestam a justiça e pervertem tudo o que é justo;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22619, 'nvi', 'Miquéias', 'mq', 3, 10, 'que constroem Sião com derramamento de sangue, e Jerusalém com impiedade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22620, 'nvi', 'Miquéias', 'mq', 3, 11, 'Seus líderes julgam a troco de suborno, seus sacerdotes ensinam por lucro, e seus profetas adivinham em troca de prata. E ainda se apóiam no Senhor, dizendo: "O Senhor está no meio de nós. Nenhuma desgraça vai nos acontecer".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22621, 'nvi', 'Miquéias', 'mq', 3, 12, 'Por isso, por causa de vocês, Sião será arada como um campo, Jerusalém se tornará um monte de entulho, e a colina do templo, um matagal.');
