-- Inserções para Miquéias 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22581, 'nvi', 'Miquéias', 'mq', 1, 1, 'A palavra do Senhor que veio a Miquéias de Moresete durante os reinados de Jotão, Acaz e Ezequias, reis de Judá; a visão que ele teve acerca de Samaria e de Jerusalém:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22582, 'nvi', 'Miquéias', 'mq', 1, 2, 'Ouçam, todos os povos; prestem atenção, ó terra e todos os que nela habitam; que o Senhor Soberano, do seu santo templo, testemunhe contra vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22583, 'nvi', 'Miquéias', 'mq', 1, 3, 'Vejam! O Senhor já está saindo da sua habitação; ele desce e pisa os lugares altos da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22584, 'nvi', 'Miquéias', 'mq', 1, 4, 'Debaixo dele os montes se derretem como cera diante do fogo, e os vales racham ao meio, como que rasgados pelas águas que descem velozes encosta abaixo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22585, 'nvi', 'Miquéias', 'mq', 1, 5, 'Tudo por causa da transgressão de Jacó, dos pecados da nação de Israel. Qual é a transgressão de Jacó? Acaso não é Samaria? Qual é o altar idólatra de Judá? Acaso não é Jerusalém?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22586, 'nvi', 'Miquéias', 'mq', 1, 6, '"Por isso farei de Samaria um monte de entulho em campo aberto, um lugar para plantação de vinhas; atirarei as suas pedras no vale e porei a descoberto os seus alicerces.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22587, 'nvi', 'Miquéias', 'mq', 1, 7, 'Todas as suas imagens esculpidas serão despedaçadas e todos os seus ganhos imorais serão consumidos pelo fogo; destruirei todas as suas imagens. Visto que o que ela ajuntou foi como ganho da prostituição, como salário de prostituição tornará a ser usado. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22588, 'nvi', 'Miquéias', 'mq', 1, 8, 'Por causa disso chorarei e lamentarei; andarei descalço e nu. Uivarei como um chacal e gemerei como um filhote de coruja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22589, 'nvi', 'Miquéias', 'mq', 1, 9, 'Pois a ferida de Samaria é incurável; e chegou a Judá. O flagelo alcançou até mesmo a porta do meu povo, até a própria Jerusalém!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22590, 'nvi', 'Miquéias', 'mq', 1, 10, 'Não contem isso em Gate, e não chorem. Habitantes de Bete-Ofra, revolvam-se no pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22591, 'nvi', 'Miquéias', 'mq', 1, 11, 'Saiam nus e cobertos de vergonha, vocês que moram em Safir. Os habitantes de Zaanã não sairão de sua cidade. Bete-Ezel está em prantos; foi-lhe tirada a proteção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22592, 'nvi', 'Miquéias', 'mq', 1, 12, 'Os que vivem em Marote se contorcem de dor aguardando alívio, porque a desgraça veio da parte do Senhor até às portas de Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22593, 'nvi', 'Miquéias', 'mq', 1, 13, 'Habitantes de Láquis, atrelem aos carros as parelhas de cavalos. Esse foi o início do pecado da cidade de Sião, pois as transgressões de Israel foram aprendidas com vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22594, 'nvi', 'Miquéias', 'mq', 1, 14, 'Por isso vocês darão presentes de despedida a Moresete-Gate. A cidade de Aczibe se revelará enganosa aos reis de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22595, 'nvi', 'Miquéias', 'mq', 1, 15, 'Trarei um conquistador contra vocês, que vivem em Maressa. A glória de Israel irá a Adulão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22596, 'nvi', 'Miquéias', 'mq', 1, 16, 'Rapem as suas cabeças em pranto por causa dos filhos nos quais vocês se tanto alegram; fiquem calvos como a águia, pois eles serão levados de vocês para o exílio.');
