-- Inserções para Mateus 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23194, 'nvi', 'Mateus', 'mt', 3, 1, 'Naqueles dias surgiu João Batista, pregando no deserto da Judéia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23195, 'nvi', 'Mateus', 'mt', 3, 2, 'Ele dizia: "Arrependam-se, porque o Reino dos céus está próximo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23196, 'nvi', 'Mateus', 'mt', 3, 3, 'Este é aquele que foi anunciado pelo profeta Isaías: "Voz do que clama no deserto: ‘Preparem o caminho para o Senhor, façam veredas retas para ele’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23197, 'nvi', 'Mateus', 'mt', 3, 4, 'As roupas de João eram feitas de pêlos de camelo, e ele usava um cinto de couro na cintura. O seu alimento era gafanhotos e mel silvestre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23198, 'nvi', 'Mateus', 'mt', 3, 5, 'A ele vinha gente de Jerusalém, de toda a Judéia e de toda a região ao redor do Jordão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23199, 'nvi', 'Mateus', 'mt', 3, 6, 'Confessando os seus pecados, eram batizados por ele no rio Jordão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23200, 'nvi', 'Mateus', 'mt', 3, 7, 'Quando viu que muitos fariseus e saduceus vinham para onde ele estava batizando, disse-lhes: "Raça de víboras! Quem lhes deu a idéia de fugir da ira que se aproxima?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23201, 'nvi', 'Mateus', 'mt', 3, 8, 'Dêem fruto que mostre o arrependimento!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23202, 'nvi', 'Mateus', 'mt', 3, 9, 'Não pensem que vocês podem dizer a si mesmos: ‘Abraão é nosso pai’. Pois eu lhes digo que destas pedras Deus pode fazer surgir filhos a Abraão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23203, 'nvi', 'Mateus', 'mt', 3, 10, 'O machado já está posto à raiz das árvores, e toda árvore que não der bom fruto será cortada e lançada ao fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23204, 'nvi', 'Mateus', 'mt', 3, 11, '"Eu os batizo com água para arrependimento. Mas depois de mim vem alguém mais poderoso do que eu, tanto que não sou digno nem de levar as suas sandálias. Ele os batizará com o Espírito Santo e com fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23205, 'nvi', 'Mateus', 'mt', 3, 12, 'Ele traz a pá em sua mão e limpará sua eira, juntando seu trigo no celeiro, mas queimará a palha com fogo que nunca se apaga".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23206, 'nvi', 'Mateus', 'mt', 3, 13, 'Então Jesus veio da Galiléia ao Jordão para ser batizado por João.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23207, 'nvi', 'Mateus', 'mt', 3, 14, 'João, porém, tentou impedi-lo, dizendo: "Eu preciso ser batizado por ti, e tu vens a mim? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23208, 'nvi', 'Mateus', 'mt', 3, 15, 'Respondeu Jesus: "Deixe assim por enquanto; convém que assim façamos, para cumprir toda a justiça". E João concordou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23209, 'nvi', 'Mateus', 'mt', 3, 16, 'Assim que Jesus foi batizado, saiu da água. Naquele momento os céus se abriram, e ele viu o Espírito de Deus descendo como pomba e pousando sobre ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23210, 'nvi', 'Mateus', 'mt', 3, 17, 'Então uma voz dos céus disse: "Este é o meu Filho amado, em quem me agrado".');
