-- Inserções para Mateus 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23146, 'nvi', 'Mateus', 'mt', 1, 1, 'Registro da genealogia de Jesus Cristo, filho de Davi, filho de Abraão:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23147, 'nvi', 'Mateus', 'mt', 1, 2, 'Abraão gerou Isaque; Isaque gerou Jacó; Jacó gerou Judá e seus irmãos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23148, 'nvi', 'Mateus', 'mt', 1, 3, 'Judá gerou Perez e Zerá, cuja mãe foi Tamar; Perez gerou Esrom; Esrom gerou Arão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23149, 'nvi', 'Mateus', 'mt', 1, 4, 'Arão gerou Aminadabe; Aminadabe gerou Naassom; Naassom gerou Salmom;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23150, 'nvi', 'Mateus', 'mt', 1, 5, 'Salmom gerou Boaz, cuja mãe foi Raabe; Boaz gerou Obede, cuja mãe foi Rute; Obede gerou Jessé;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23151, 'nvi', 'Mateus', 'mt', 1, 6, 'e Jessé gerou o rei Davi. Davi gerou Salomão, cuja mãe tinha sido mulher de Urias;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23152, 'nvi', 'Mateus', 'mt', 1, 7, 'Salomão gerou Roboão; Roboão gerou Abias; Abias gerou Asa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23153, 'nvi', 'Mateus', 'mt', 1, 8, 'Asa gerou Josafá; Josafá gerou Jorão; Jorão gerou Uzias;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23154, 'nvi', 'Mateus', 'mt', 1, 9, 'Uzias gerou Jotão; Jotão gerou Acaz; Acaz gerou Ezequias;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23155, 'nvi', 'Mateus', 'mt', 1, 10, 'Ezequias gerou Manassés; Manassés gerou Amom; Amom gerou Josias;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23156, 'nvi', 'Mateus', 'mt', 1, 11, 'e Josias gerou Jeconias e seus irmãos, no tempo do exílio na Babilônia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23157, 'nvi', 'Mateus', 'mt', 1, 12, 'Depois do exílio na Babilônia: Jeconias gerou Salatiel; Salatiel gerou Zorobabel;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23158, 'nvi', 'Mateus', 'mt', 1, 13, 'Zorobabel gerou Abiúde; Abiúde gerou Eliaquim; Eliaquim gerou Azor;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23159, 'nvi', 'Mateus', 'mt', 1, 14, 'Azor gerou Sadoque; Sadoque gerou Aquim; Aquim gerou Eliúde;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23160, 'nvi', 'Mateus', 'mt', 1, 15, 'Eliúde gerou Eleazar; Eleazar gerou Matã; Matã gerou Jacó;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23161, 'nvi', 'Mateus', 'mt', 1, 16, 'e Jacó gerou José, marido de Maria, da qual nasceu Jesus, que é chamado Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23162, 'nvi', 'Mateus', 'mt', 1, 17, 'Assim, ao todo houve catorze gerações de Abraão a Davi, catorze de Davi até o exílio na Babilônia e catorze do exílio até o Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23163, 'nvi', 'Mateus', 'mt', 1, 18, 'Foi assim o nascimento de Jesus Cristo: Maria, sua mãe, estava prometida em casamento a José, mas, antes que se unissem, achou-se grávida pelo Espírito Santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23164, 'nvi', 'Mateus', 'mt', 1, 19, 'Por ser José, seu marido, um homem justo, e não querendo expô-la à desonra pública, pretendia anular o casamento secretamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23165, 'nvi', 'Mateus', 'mt', 1, 20, 'Mas, depois de ter pensado nisso, apareceu-lhe um anjo do Senhor em sonho e disse: "José, filho de Davi, não tema receber Maria como sua esposa, pois o que nela foi gerado procede do Espírito Santo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23166, 'nvi', 'Mateus', 'mt', 1, 21, 'Ela dará à luz um filho, e você deverá dar-lhe o nome de Jesus, porque ele salvará o seu povo dos seus pecados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23167, 'nvi', 'Mateus', 'mt', 1, 22, 'Tudo isso aconteceu para que se cumprisse o que o Senhor dissera pelo profeta:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23168, 'nvi', 'Mateus', 'mt', 1, 23, '"A virgem ficará grávida e dará à luz um filho, e lhe chamarão Emanuel" que significa "Deus conosco".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23169, 'nvi', 'Mateus', 'mt', 1, 24, 'Ao acordar, José fez o que o anjo do Senhor lhe tinha ordenado e recebeu Maria como sua esposa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23170, 'nvi', 'Mateus', 'mt', 1, 25, 'Mas não teve relações com ela enquanto ela não deu à luz um filho. E ele lhe pôs o nome de Jesus.');
