-- Inserções para Naum 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22701, 'nvi', 'Naum', 'na', 2, 1, 'O destruidor avança contra você, Nínive! Guarde a fortaleza! Vigie a estrada! Prepare a resistência! Reúna todas as suas forças!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22702, 'nvi', 'Naum', 'na', 2, 2, 'O SENHOR restaurará o esplendor de Jacó; restaurará o esplendor de Israel, embora os saqueadores tenham devastado e destruído as suas videiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22703, 'nvi', 'Naum', 'na', 2, 3, 'Os escudos e os uniformes dos soldados inimigos são vermelhos. Os seus carros de guerra reluzem quando se alinham para a batalha; agitam-se as lanças de pinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22704, 'nvi', 'Naum', 'na', 2, 4, 'Os carros de guerra percorrem loucamente as ruas e se cruzam velozmente pelos quarteirões. Parecem tochas de fogo e arremessam-se como relâmpagos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22705, 'nvi', 'Naum', 'na', 2, 5, 'Convocam-se as suas tropas de elite, mas elas vêm tropeçando; correm para a muralha da cidade para formar a linha de proteção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22706, 'nvi', 'Naum', 'na', 2, 6, 'As comportas dos canais são abertas, e o palácio desaba.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22707, 'nvi', 'Naum', 'na', 2, 7, 'Está decretado: a cidade irá para o exílio, será deportada. As jovens tomadas como escravas batem no peito; seu gemer é como o arrulhar das pombas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22708, 'nvi', 'Naum', 'na', 2, 8, 'Nínive é como um açude antigo cujas águas estão vazando. “Parem, parem”, eles gritam, mas ninguém sequer olha para trás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22709, 'nvi', 'Naum', 'na', 2, 9, 'Saqueiem a prata! Saqueiem o ouro! Sua riqueza não tem fim; está repleta de objetos de valor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22710, 'nvi', 'Naum', 'na', 2, 10, 'Ah! Devastação! Destruição! Desolação! Os corações se derretem, os joelhos vacilam, todos os corpos tremem e o rosto de todos empalidece!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22711, 'nvi', 'Naum', 'na', 2, 11, 'Onde está agora a toca dos leões? Onde o lugar em que alimentavam seus filhotes, para onde iam o leão, a leoa e os leõezinhos, sem nada temer?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22712, 'nvi', 'Naum', 'na', 2, 12, 'Onde está o leão que caçava o bastante para os seus filhotes e estrangulava animais para as suas leoas, e que enchia as suas covas de presas e suas tocas de vítimas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22713, 'nvi', 'Naum', 'na', 2, 13, '“Estou contra você”, declara o SENHOR dos Exércitos, “queimarei no fogo os seus carros de guerra, e a espada matará os seus leões. Eliminarei da terra a sua caça, e a voz dos seus mensageiros jamais será ouvida”.');
