-- Inserções para Neemias 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12495, 'nvi', 'Neemias', 'ne', 8, 1, 'todo o povo juntou-se como se fosse um só homem na praça, em frente da porta das Águas. Pediram ao escriba Esdras que trouxesse o Livro da Lei de Moisés, que o Senhor dera a Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12496, 'nvi', 'Neemias', 'ne', 8, 2, 'Assim, no dia primeiro do sétimo mês, o sacerdote Esdras trouxe a Lei diante da assembléia, que era constituída de homens e mulheres e de todos os que podiam entender.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12497, 'nvi', 'Neemias', 'ne', 8, 3, 'Ele a leu em voz alta desde o raiar da manhã até o meio-dia, de frente para a praça, em frente da porta das Águas, na presença dos homens, mulheres e de outros que podiam entender. E todo o povo ouvia com atenção a leitura do Livro da Lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12498, 'nvi', 'Neemias', 'ne', 8, 4, 'O escriba Esdras estava numa plataforma elevada, de madeira, construída para a ocasião. Ao seu lado, à direita, estavam Matitias, Sema, Anaías, Urias, Hilquias e Maaséias; e à esquerda estavam Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12499, 'nvi', 'Neemias', 'ne', 8, 5, 'Esdras abriu o livro diante de todo o povo, e este podia vê-lo, pois ele estava num lugar mais alto. E, quando abriu o livro, o povo todo se levantou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12500, 'nvi', 'Neemias', 'ne', 8, 6, 'Esdras louvou o Senhor, o grande Deus, e todo o povo ergueu as mãos e respondeu: "Amém! Amém! " Então eles adoraram o Senhor, prostrados, rosto em terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12501, 'nvi', 'Neemias', 'ne', 8, 7, 'Os levitas Jesua, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaséias, Quelita, Azarias, Jozabade, Hanã e Pelaías, instruíram o povo na Lei, e todos permaneciam ali.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12502, 'nvi', 'Neemias', 'ne', 8, 8, 'Leram o Livro da Lei de Deus, interpretando-o e explicando-o, a fim de que o povo entendesse o que estava sendo lido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12503, 'nvi', 'Neemias', 'ne', 8, 9, 'Então Neemias, o governador, Esdras, o sacerdote e escriba, e os levitas que estavam instruindo o povo disseram a todos: "Este dia é consagrado ao Senhor Deus. Nada de tristeza e de choro! " Pois todo o povo estava chorando enquanto ouvia as palavras da Lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12504, 'nvi', 'Neemias', 'ne', 8, 10, 'E Neemias acrescentou: "Podem sair, e comam e bebam do melhor que tiverem, e repartam com os que nada têm preparado. Este dia é consagrado ao nosso Senhor. Não se entristeçam, porque a alegria do Senhor os fortalecerá".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12505, 'nvi', 'Neemias', 'ne', 8, 11, 'Os levitas tranqüilizaram todo o povo, dizendo: "Acalmem-se porque este é um dia santo. Não fiquem tristes! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12506, 'nvi', 'Neemias', 'ne', 8, 12, 'Então todo o povo saiu para comer, beber, repartir com os que nada tinham preparado e para comemorar com grande alegria, pois agora compreendiam as palavras que lhes foram explicadas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12507, 'nvi', 'Neemias', 'ne', 8, 13, 'No segundo dia do mês, os chefes de todas as famílias, os sacerdotes e os levitas reuniram-se com o escriba Esdras para estudar as palavras da Lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12508, 'nvi', 'Neemias', 'ne', 8, 14, 'Descobriram que estava escrito na Lei, que o Senhor tinha ordenado por meio de Moisés, que os israelitas deviam morar em tendas durante a festa do sétimo mês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12509, 'nvi', 'Neemias', 'ne', 8, 15, 'Por isso anunciaram em todas as suas cidades e em Jerusalém: "Saiam às montanhas e tragam ramos de oliveiras cultivadas, de oliveiras silvestres, de murtas, de tamareiras e de árvores frondosas, para fazerem tendas", conforme está escrito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12510, 'nvi', 'Neemias', 'ne', 8, 16, 'Então o povo saiu e trouxe os ramos, e eles mesmos construíram tendas nos seus terraços, nos seus pátios, nos pátios do templo de Deus e na praça junto à porta das Águas e na que fica junto à porta de Efraim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12511, 'nvi', 'Neemias', 'ne', 8, 17, 'Todos os que tinham voltado do exílio construíram tendas e moraram nelas. Desde os dias de Josué, filho de Num, até aquele dia, os israelitas não tinham celebrado a festa dessa maneira. E a alegria deles foi muito grande.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12512, 'nvi', 'Neemias', 'ne', 8, 18, 'Dia após dia, desde o primeiro até o último dia da festa, Esdras leu o Livro da Lei de Deus. Eles celebraram a festa durante sete dias, e no oitavo dia, conforme o ritual, houve uma reunião solene.');
