-- Inserções para Neemias 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12422, 'nvi', 'Neemias', 'ne', 7, 1, 'Depois que o muro foi reconstruído e que eu coloquei as portas no lugar, foram nomeados os porteiros, os cantores e os levitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12423, 'nvi', 'Neemias', 'ne', 7, 2, 'Para governar Jerusalém encarreguei o meu irmão Hanani e, com ele, Hananias, comandante da cidade forte, pois Hananias era íntegro e temia a Deus mais do que a maioria dos homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12424, 'nvi', 'Neemias', 'ne', 7, 3, 'Eu lhes disse: As portas de Jerusalém não deverão ser abertas enquanto o sol não estiver alto. E antes de deixarem o serviço, os porteiros deverão fechar e travar as portas. Também designei moradores de Jerusalém para sentinelas, alguns em postos no muro, outros em frente das suas casas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12425, 'nvi', 'Neemias', 'ne', 7, 4, 'Ora, a cidade era grande e espaçosa, mas havia poucos moradores, e as casas ainda não tinham sido reconstruídas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12426, 'nvi', 'Neemias', 'ne', 7, 5, 'Por isso o meu Deus pôs no meu coração reunir os nobres, os oficiais e todo o povo para registrá-los por famílias. Encontrei o registro genealógico dos que foram os primeiros a voltar. E assim estava registrado ali:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12427, 'nvi', 'Neemias', 'ne', 7, 6, 'Estes são os homens da província que voltaram do exílio, os quais Nabucodonosor, rei da Babilônia, havia levado prisioneiros. Eles voltaram para Jerusalém e para Judá, cada um para a sua própria cidade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12428, 'nvi', 'Neemias', 'ne', 7, 7, 'em companhia de Zorobabel, Jesua, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Bilsã, Misperete, Bigvai, Neum e Baaná. E esta é a lista e o número dos que retornaram, pelos chefes de família e respectivas cidades:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12429, 'nvi', 'Neemias', 'ne', 7, 8, 'os descendentes de Parós 2. 172');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12430, 'nvi', 'Neemias', 'ne', 7, 9, 'de Sefatias 372');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12431, 'nvi', 'Neemias', 'ne', 7, 10, 'de Ara 652');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12432, 'nvi', 'Neemias', 'ne', 7, 11, 'de Paate-Moabe, por meio da linhagem de Jesua e Joabe, 2. 818');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12433, 'nvi', 'Neemias', 'ne', 7, 12, 'de Elão 1. 254');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12434, 'nvi', 'Neemias', 'ne', 7, 13, 'de Zatu 845');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12435, 'nvi', 'Neemias', 'ne', 7, 14, 'de Zacai 760');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12436, 'nvi', 'Neemias', 'ne', 7, 15, 'de Binui 648');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12437, 'nvi', 'Neemias', 'ne', 7, 16, 'de Bebai 628');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12438, 'nvi', 'Neemias', 'ne', 7, 17, 'de Azgade 2. 322');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12439, 'nvi', 'Neemias', 'ne', 7, 18, 'de Adonicão 667');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12440, 'nvi', 'Neemias', 'ne', 7, 19, 'de Bigvai 2. 067');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12441, 'nvi', 'Neemias', 'ne', 7, 20, 'de Adim 655');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12442, 'nvi', 'Neemias', 'ne', 7, 21, 'de Ater, por meio de Ezequias, 98');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12443, 'nvi', 'Neemias', 'ne', 7, 22, 'de Hasum 328');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12444, 'nvi', 'Neemias', 'ne', 7, 23, 'de Besai 324');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12445, 'nvi', 'Neemias', 'ne', 7, 24, 'de Harife 112');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12446, 'nvi', 'Neemias', 'ne', 7, 25, 'de Gibeom 95');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12447, 'nvi', 'Neemias', 'ne', 7, 26, 'das cidades de Belém e de Netofate 188');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12448, 'nvi', 'Neemias', 'ne', 7, 27, 'de Anatote 128');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12449, 'nvi', 'Neemias', 'ne', 7, 28, 'de Bete-Azmavete 42');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12450, 'nvi', 'Neemias', 'ne', 7, 29, 'de Quiriate-Jearim, Cefira e Beerote 743');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12451, 'nvi', 'Neemias', 'ne', 7, 30, 'de Ramá e Geba 621');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12452, 'nvi', 'Neemias', 'ne', 7, 31, 'de Micmás 122');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12453, 'nvi', 'Neemias', 'ne', 7, 32, 'de Betel e Ai 123');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12454, 'nvi', 'Neemias', 'ne', 7, 33, 'do outro Nebo 52');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12455, 'nvi', 'Neemias', 'ne', 7, 34, 'do outro Elão 1. 254');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12456, 'nvi', 'Neemias', 'ne', 7, 35, 'de Harim 320');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12457, 'nvi', 'Neemias', 'ne', 7, 36, 'de Jericó 345');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12458, 'nvi', 'Neemias', 'ne', 7, 37, 'de Lode, Hadide e Ono 721');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12459, 'nvi', 'Neemias', 'ne', 7, 38, 'de Senaá 3. 930.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12460, 'nvi', 'Neemias', 'ne', 7, 39, 'Os sacerdotes: os descendentes de Jedaías, por meio da família de Jesua, 973');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12461, 'nvi', 'Neemias', 'ne', 7, 40, 'de Imer 1. 052');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12462, 'nvi', 'Neemias', 'ne', 7, 41, 'de Pasur 1. 247');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12463, 'nvi', 'Neemias', 'ne', 7, 42, 'de Harim 1. 017.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12464, 'nvi', 'Neemias', 'ne', 7, 43, 'Os levitas: os descendentes de Jesua, por meio de Cadmiel, pela linhagem de Hodeva 74.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12465, 'nvi', 'Neemias', 'ne', 7, 44, 'Os cantores: os descendentes de Asafe 148.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12466, 'nvi', 'Neemias', 'ne', 7, 45, 'Os porteiros do templo: os descendentes de Salum, Ater, Talmom, Acube, Hatita e Sobai 138.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12467, 'nvi', 'Neemias', 'ne', 7, 46, 'Os servidores do templo: os descendentes de Zia, Hasufa, Tabaote,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12468, 'nvi', 'Neemias', 'ne', 7, 47, 'Queros, Sia, Padom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12469, 'nvi', 'Neemias', 'ne', 7, 48, 'Lebana, Hagaba, Salmai,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12470, 'nvi', 'Neemias', 'ne', 7, 49, 'Hanã, Gidel, Gaar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12471, 'nvi', 'Neemias', 'ne', 7, 50, 'Reaías, Rezim, Necoda,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12472, 'nvi', 'Neemias', 'ne', 7, 51, 'Gazão, Uzá, Paséia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12473, 'nvi', 'Neemias', 'ne', 7, 52, 'Besai, Meunim, Nefusim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12474, 'nvi', 'Neemias', 'ne', 7, 53, 'Baquebuque, Hacufa, Harur,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12475, 'nvi', 'Neemias', 'ne', 7, 54, 'Baslite, Meída, Harsa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12476, 'nvi', 'Neemias', 'ne', 7, 55, 'Barcos, Sísera, Tamá,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12477, 'nvi', 'Neemias', 'ne', 7, 56, 'Nesias e Hatifa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12478, 'nvi', 'Neemias', 'ne', 7, 57, 'Os descendentes dos servos de Salomão: os descendentes de Sotai, Soferete, Perida,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12479, 'nvi', 'Neemias', 'ne', 7, 58, 'Jaala, Darcom, Gidel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12480, 'nvi', 'Neemias', 'ne', 7, 59, 'Sefatias, Hatil, Poquerete-Hazebaim e Amom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12481, 'nvi', 'Neemias', 'ne', 7, 60, 'Os servos do templo e os descendentes dos servos de Salomão 392.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12482, 'nvi', 'Neemias', 'ne', 7, 61, 'Os que chegaram das cidades de Tel-Melá, Tel-Harsa, Querube, Adom e Imer, mas não puderam provar que suas famílias eram descendentes de Israel:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12483, 'nvi', 'Neemias', 'ne', 7, 62, 'Os descendentes de Delaías, Tobias e Necoda 642.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12484, 'nvi', 'Neemias', 'ne', 7, 63, 'E dentre os sacerdotes: os descendentes de Habaías, Coz e Barzilai, homem que se casou com uma filha de Barzilai, de Gileade, e que era chamado por aquele nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12485, 'nvi', 'Neemias', 'ne', 7, 64, 'Esses procuraram seus registros de família, mas não conseguiram achá-los e, dessa forma, foram considerados impuros para o sacerdócio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12486, 'nvi', 'Neemias', 'ne', 7, 65, 'Por isso o governador determinou que eles não comessem das ofertas santíssimas enquanto não houvesse um sacerdote para consultar o Urim e o Tumim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12487, 'nvi', 'Neemias', 'ne', 7, 66, 'O total de todos os registrados foi 42. 360 homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12488, 'nvi', 'Neemias', 'ne', 7, 67, 'além de seus 7. 337 servos e servas; havia entre eles 245 cantores e cantoras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12489, 'nvi', 'Neemias', 'ne', 7, 68, 'Possuíam 736 cavalos, 245 mulas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12490, 'nvi', 'Neemias', 'ne', 7, 69, '435 camelos e 6. 720 jumentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12491, 'nvi', 'Neemias', 'ne', 7, 70, 'Alguns dos chefes das famílias contribuíram para o trabalho. O governador deu à tesouraria oito quilos de ouro, 50 bacias e 530 vestes para os sacerdotes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12492, 'nvi', 'Neemias', 'ne', 7, 71, 'Alguns dos chefes das famílias deram à tesouraria, para a realização do trabalho, cento e sessenta quilos de ouro e uma tonelada e trezentos e vinte quilos de prata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12493, 'nvi', 'Neemias', 'ne', 7, 72, 'O total dado pelo restante do povo foi de cento e sessenta quilos de ouro, uma tonelada e duzentos quilos de prata e 67 vestes para os sacerdotes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (12494, 'nvi', 'Neemias', 'ne', 7, 73, 'Os sacerdotes, os levitas, os porteiros, os cantores e os servidores do templo, e também alguns do povo e os demais israelitas, estabeleceram-se em suas próprias cidades. Quando chegou o sétimo mês e os israelitas tinham se instalado em suas cidades,');
