-- Inserções para Números 34
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4817, 'nvi', 'Números', 'nm', 34, 1, 'Disse mais o Senhor a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4818, 'nvi', 'Números', 'nm', 34, 2, '"Dê ordem aos israelitas e diga-lhes: Quando vocês entrarem em Canaã, a terra que lhes será sorteada como herança terá estas fronteiras:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4819, 'nvi', 'Números', 'nm', 34, 3, '"O lado sul começará no deserto de Zim, junto à fronteira de Edom. No leste, sua fronteira sul começará na extremidade do mar Salgado,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4820, 'nvi', 'Números', 'nm', 34, 4, 'passará pelo sul da subida de Acrabim, prosseguirá até Zim e irá para o sul de Cades-Barnéia. Depois passará por Hazar-Adar e irá até Azmom,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4821, 'nvi', 'Números', 'nm', 34, 5, 'onde fará a volta, juntando-se ao ribeiro do Egito para terminar no Mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4822, 'nvi', 'Números', 'nm', 34, 6, 'A fronteira ocidental de vocês será o litoral do mar Grande. Será essa a fronteira do oeste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4823, 'nvi', 'Números', 'nm', 34, 7, 'Esta será a fronteira norte: façam uma linha desde o mar Grande até o monte Hor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4824, 'nvi', 'Números', 'nm', 34, 8, 'e do monte Hor até Lebo-Hamate. O limite da fronteira será Zedade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4825, 'nvi', 'Números', 'nm', 34, 9, 'prosseguirá até Zifrom e terminará em Hazar-Enã. Será essa a fronteira norte de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4826, 'nvi', 'Números', 'nm', 34, 10, 'Esta será a fronteira oriental: façam uma linha de Hazar-Enã até Sefã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4827, 'nvi', 'Números', 'nm', 34, 11, 'A fronteira descerá de Sefã até Ribla, no lado oriental de Aim, e prosseguirá ao longo das encostas a leste do mar de Quinerete.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4828, 'nvi', 'Números', 'nm', 34, 12, 'A fronteira descerá ao longo do Jordão e terminará no mar Salgado. Será essa a terra de vocês, com as suas fronteiras de todos os lados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4829, 'nvi', 'Números', 'nm', 34, 13, 'Moisés ordenou aos israelitas: "Distribuam a terra por sorteio como herança. O Senhor ordenou que seja dada às nove tribos e meia,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4830, 'nvi', 'Números', 'nm', 34, 14, 'porque as famílias da tribo de Rúben, da tribo de Gade e da metade da tribo de Manassés já receberam a herança delas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4831, 'nvi', 'Números', 'nm', 34, 15, 'Estas duas tribos e meia receberam sua herança no lado leste do Jordão, do outro lado de Jericó, na direção do nascer do sol".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4832, 'nvi', 'Números', 'nm', 34, 16, 'O Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4833, 'nvi', 'Números', 'nm', 34, 17, '"Estes são os nomes dos homens que deverão distribuir a terra a vocês como herança: o sacerdote Eleazar e Josué, filho de Num.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4834, 'nvi', 'Números', 'nm', 34, 18, 'Designem um líder de cada tribo para ajudar a distribuir a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4835, 'nvi', 'Números', 'nm', 34, 19, 'Estes são os seus nomes: "Calebe, filho de Jefoné, da tribo de Judá;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4836, 'nvi', 'Números', 'nm', 34, 20, 'Samuel, filho de Amiúde, da tribo de Simeão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4837, 'nvi', 'Números', 'nm', 34, 21, 'Elidade, filho de Quislom, da tribo de Benjamim;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4838, 'nvi', 'Números', 'nm', 34, 22, 'Buqui, filho de Jogli, o líder da tribo de Dã;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4839, 'nvi', 'Números', 'nm', 34, 23, 'Haniel, filho de Éfode, o líder da tribo de Manassés, filho de José;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4840, 'nvi', 'Números', 'nm', 34, 24, 'Quemuel, filho de Siftã, o líder da tribo de Efraim, filho de José;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4841, 'nvi', 'Números', 'nm', 34, 25, 'Elizafã, filho de Parnaque, o líder da tribo de Zebulom;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4842, 'nvi', 'Números', 'nm', 34, 26, 'Paltiel, filho de Azã, o líder da tribo de Issacar;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4843, 'nvi', 'Números', 'nm', 34, 27, 'Aiúde, filho de Selomi, o líder da tribo de Aser;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4844, 'nvi', 'Números', 'nm', 34, 28, 'Pedael, filho de Amiúde, o líder da tribo de Naftali".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4845, 'nvi', 'Números', 'nm', 34, 29, 'Foram esses os homens a quem o Senhor ordenou que distribuíssem a herança aos israelitas na terra de Canaã.');
