-- Inserções para Números 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3659, 'nvi', 'Números', 'nm', 2, 1, 'O Senhor disse a Moisés e a Arão:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3660, 'nvi', 'Números', 'nm', 2, 2, '"Os israelitas acamparão ao redor da Tenda do Encontro, a certa distância, cada homem junto à sua bandeira com os emblemas da sua família".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3661, 'nvi', 'Números', 'nm', 2, 3, 'A leste, os exércitos de Judá acamparão junto à sua bandeira. O líder de Judá será Naassom, filho de Aminadabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3662, 'nvi', 'Números', 'nm', 2, 4, 'Seu exército é de 74. 600 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3663, 'nvi', 'Números', 'nm', 2, 5, 'A tribo de Issacar acampará ao lado de Judá. O líder de Issacar será Natanael, filho de Zuar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3664, 'nvi', 'Números', 'nm', 2, 6, 'Seu exército é de 54. 400 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3665, 'nvi', 'Números', 'nm', 2, 7, 'A tribo de Zebulom virá em seguida. O líder de Zebulom será Eliabe, filho de Helom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3666, 'nvi', 'Números', 'nm', 2, 8, 'Seu exército é de 57. 400 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3667, 'nvi', 'Números', 'nm', 2, 9, 'O número total dos homens recenseados do acampamento de Judá, de acordo com os seus exércitos, foi 186. 400. Esses marcharão primeiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3668, 'nvi', 'Números', 'nm', 2, 10, 'Ao sul estarão os exércitos do acampamento de Rúben, junto à sua bandeira. O líder de Rúben será Elizur, filho de Sedeur.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3669, 'nvi', 'Números', 'nm', 2, 11, 'Seu exército é de 46. 500 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3670, 'nvi', 'Números', 'nm', 2, 12, 'A tribo de Simeão acampará ao lado de Rúben. O líder de Simeão será Selumiel, filho de Zurisadai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3671, 'nvi', 'Números', 'nm', 2, 13, 'Seu exército é de 59. 300 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3672, 'nvi', 'Números', 'nm', 2, 14, 'A tribo de Gade virá em seguida. O líder de Gade será Eliasafe, filho de Deuel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3673, 'nvi', 'Números', 'nm', 2, 15, 'Seu exército é de 45. 650 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3674, 'nvi', 'Números', 'nm', 2, 16, 'O número total dos homens recenseados do acampamento de Rúben, de acordo com os seus exércitos, foi 151. 450. Esses marcharão em segundo lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3675, 'nvi', 'Números', 'nm', 2, 17, 'Em seguida os levitas marcharão levando a Tenda do Encontro no meio dos outros acampamentos, na mesma ordem em que acamparem, cada um em seu próprio lugar, junto à sua bandeira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3676, 'nvi', 'Números', 'nm', 2, 18, 'A oeste estarão os exércitos do acampamento de Efraim, junto à sua bandeira. O líder de Efraim será Elisama, filho de Amiúde.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3677, 'nvi', 'Números', 'nm', 2, 19, 'Seu exército é de 40. 500 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3678, 'nvi', 'Números', 'nm', 2, 20, 'A tribo de Manassés acampará ao lado de Efraim. O líder de Manassés será Gamaliel, filho de Pedazur.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3679, 'nvi', 'Números', 'nm', 2, 21, 'Seu exército é de 32. 200 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3680, 'nvi', 'Números', 'nm', 2, 22, 'A tribo de Benjamim virá em seguida. O líder de Benjamim será Abidã, filho de Gideoni.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3681, 'nvi', 'Números', 'nm', 2, 23, 'Seu exército é de 35. 400 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3682, 'nvi', 'Números', 'nm', 2, 24, 'O número total dos homens recenseados do acampamento de Efraim, de acordo com os seus exércitos, foi 108. 100. Esses marcharão em terceiro lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3683, 'nvi', 'Números', 'nm', 2, 25, 'Ao norte estarão os exércitos do acampamento de Dã, junto à sua bandeira. O líder de Dã será Aieser, filho de Amisadai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3684, 'nvi', 'Números', 'nm', 2, 26, 'Seu exército é de 62. 700 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3685, 'nvi', 'Números', 'nm', 2, 27, 'A tribo de Aser acampará ao lado de Dã. O líder de Aser será Pagiel, filho de Ocrã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3686, 'nvi', 'Números', 'nm', 2, 28, 'Seu exército é de 41. 500 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3687, 'nvi', 'Números', 'nm', 2, 29, 'A tribo de Naftali virá em seguida. O líder de Naftali será Aira, filho de Enã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3688, 'nvi', 'Números', 'nm', 2, 30, 'Seu exército é de 53. 400 homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3689, 'nvi', 'Números', 'nm', 2, 31, 'O número total dos homens recenseados do acampamento de Dã, de acordo com os seus exércitos, foi 157. 600. Estes marcharão por último, junto às suas bandeiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3690, 'nvi', 'Números', 'nm', 2, 32, 'Foram esses os israelitas contados de acordo com as suas famílias. O número total dos que foram contados nos acampamentos, de acordo com os seus exércitos, foi 603. 550.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3691, 'nvi', 'Números', 'nm', 2, 33, 'Os levitas, contudo, não foram contados com os outros israelitas, conforme o Senhor tinha ordenado a Moisés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (3692, 'nvi', 'Números', 'nm', 2, 34, 'Assim os israelitas fizeram tudo o que o Senhor tinha ordenado a Moisés; eles acampavam junto às suas bandeiras e depois partiam, cada um com o seu clã e com a sua família.');
