-- Inserções para Números 36
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4880, 'nvi', 'Números', 'nm', 36, 1, 'Os chefes de família do clã de Gileade, filho de Maquir, neto de Manassés, que pertenciam aos clãs dos descendentes de José, foram falar com Moisés e com os líderes, os chefes das famílias israelitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4881, 'nvi', 'Números', 'nm', 36, 2, 'E disseram: "Quando o Senhor ordenou ao meu senhor que, por sorteio, desse a terra como herança para os israelitas, ordenou que vocês dessem a herança de nosso irmão Zelofeade às suas filhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4882, 'nvi', 'Números', 'nm', 36, 3, 'Agora, suponham que elas se casem com homens de outras tribos israelitas; nesse caso a herança delas será tirada da herança dos nossos antepassados e acrescentada à herança da tribo com a qual se unirem pelo casamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4883, 'nvi', 'Números', 'nm', 36, 4, 'Quando chegar o Ano do Jubileu para os israelitas, a herança delas será acrescentada à da tribo com a qual se unirem pelo casamento, e a propriedade delas será tirada da herança da tribo de nossos antepassados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4884, 'nvi', 'Números', 'nm', 36, 5, 'Então, instruído pelo Senhor, Moisés deu esta ordem aos israelitas: "A tribo dos descendentes de José tem razão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4885, 'nvi', 'Números', 'nm', 36, 6, 'É isto que o Senhor ordena quanto às filhas de Zelofeade: Elas poderão casar-se com quem lhes agradar, contanto que se casem dentro do clã da tribo de seu pai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4886, 'nvi', 'Números', 'nm', 36, 7, 'Nenhuma herança em Israel poderá passar de uma tribo para outra, pois todos os israelitas manterão as terras das tribos que herdaram de seus antepassados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4887, 'nvi', 'Números', 'nm', 36, 8, 'Toda filha que herdar terras em qualquer tribo israelita se casará com alguém do clã da tribo de seu pai, para que cada israelita possua a herança dos seus antepassados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4888, 'nvi', 'Números', 'nm', 36, 9, 'Nenhuma herança poderá passar de uma tribo para outra, pois cada tribo israelita deverá manter as terras que herdou".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4889, 'nvi', 'Números', 'nm', 36, 10, 'As filhas de Zelofeade fizeram conforme o Senhor havia ordenado a Moisés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4890, 'nvi', 'Números', 'nm', 36, 11, 'As filhas de Zelofeade, Maalá, Tirza, Hogla, Milca e Noa, casaram-se com seus primos paternos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4891, 'nvi', 'Números', 'nm', 36, 12, 'dentro dos clãs dos descendentes de Manassés, filho de José, e a herança delas permaneceu no clã e na tribo de seu pai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4892, 'nvi', 'Números', 'nm', 36, 13, 'São esses os mandamentos e as ordenanças que o Senhor deu aos israelitas por intermédio de Moisés nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó.');
