-- Inserções para Números 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4245, 'nvi', 'Números', 'nm', 17, 1, 'O Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4246, 'nvi', 'Números', 'nm', 17, 2, '"Peça aos israelitas que tragam doze varas, uma de cada líder das tribos. Escreva o nome de cada líder em sua vara.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4247, 'nvi', 'Números', 'nm', 17, 3, 'Na vara de Levi escreva o nome de Arão, pois é preciso que haja uma vara para cada chefe das tribos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4248, 'nvi', 'Números', 'nm', 17, 4, 'Deposite-as na Tenda do Encontro, em frente da arca das tábuas da aliança, onde eu me encontro com vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4249, 'nvi', 'Números', 'nm', 17, 5, 'A vara daquele que eu escolher florescerá, e eu me livrarei dessa constante queixa dos israelitas contra vocês".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4250, 'nvi', 'Números', 'nm', 17, 6, 'Assim Moisés falou aos israelitas, e seus líderes deram-lhe doze varas, uma de cada líder das tribos, e a vara de Arão estava entre elas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4251, 'nvi', 'Números', 'nm', 17, 7, 'Moisés depositou as varas perante o Senhor na tenda que guarda as tábuas da aliança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4252, 'nvi', 'Números', 'nm', 17, 8, 'No dia seguinte Moisés entrou na tenda e viu que a vara de Arão, que representava a tribo de Levi, tinha brotado, produzindo botões e flores, além de amêndoas maduras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4253, 'nvi', 'Números', 'nm', 17, 9, 'Então Moisés retirou todas as varas da presença do Senhor e as levou a todos os israelitas. Eles viram as varas, e cada líder pegou a sua.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4254, 'nvi', 'Números', 'nm', 17, 10, 'O Senhor disse a Moisés: "Ponha de volta a vara de Arão em frente da arca das tábuas da aliança, para ser guardada como uma advertência para os rebeldes. Isso porá fim à queixa deles contra mim, para que não morram".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4255, 'nvi', 'Números', 'nm', 17, 11, 'Moisés fez conforme o Senhor lhe havia ordenado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4256, 'nvi', 'Números', 'nm', 17, 12, 'Os israelitas disseram a Moisés: "Nós morreremos! Estamos perdidos, estamos todos perdidos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4257, 'nvi', 'Números', 'nm', 17, 13, 'Todo aquele que se aproximar do santuário do Senhor morrerá. Será que todos nós vamos morrer? "');
