-- Inserções para Números 25
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4472, 'nvi', 'Números', 'nm', 25, 1, 'Enquanto Israel estava em Sitim, o povo começou a entregar-se à imoralidade sexual com mulheres moabitas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4473, 'nvi', 'Números', 'nm', 25, 2, 'que os convidavam aos sacrifícios de seus deuses. O povo comia e se prostrava perante esses deuses.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4474, 'nvi', 'Números', 'nm', 25, 3, 'Assim Israel se juntou à adoração de Baal-Peor. E a ira do Senhor acendeu-se contra Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4475, 'nvi', 'Números', 'nm', 25, 4, 'E o Senhor disse a Moisés: "Prenda todos os chefes desse povo, enforque-os diante do Senhor, à luz do sol, para que o fogo da ira do Senhor se afaste de Israel".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4476, 'nvi', 'Números', 'nm', 25, 5, 'Então Moisés disse aos juízes de Israel: "Cada um de vocês terá que matar aqueles que dentre os seus homens se juntaram à adoração de Baal-Peor".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4477, 'nvi', 'Números', 'nm', 25, 6, 'Um israelita trouxe para casa uma mulher midianita, na presença de Moisés e de toda a comunidade de Israel, que choravam à entrada da Tenda do Encontro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4478, 'nvi', 'Números', 'nm', 25, 7, 'Quando Finéias, filho de Eleazar, neto do sacerdote Arão, viu isso, apanhou uma lança,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4479, 'nvi', 'Números', 'nm', 25, 8, 'seguiu o israelita até o interior da tenda e atravessou os dois com a lança; atravessou o corpo do israelita e o da mulher. Então cessou a praga contra os israelitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4480, 'nvi', 'Números', 'nm', 25, 9, 'Mas os que morreram por causa da praga foram vinte e quatro mil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4481, 'nvi', 'Números', 'nm', 25, 10, 'E o Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4482, 'nvi', 'Números', 'nm', 25, 11, '"Finéias, filho de Eleazar, neto do sacerdote Arão, desviou a minha ira de sobre os israelitas, pois foi zeloso, com o mesmo zelo que tenho por eles, para que em meu zelo eu não os consumisse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4483, 'nvi', 'Números', 'nm', 25, 12, 'Diga-lhe, pois, que estabeleço com ele a minha aliança de paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4484, 'nvi', 'Números', 'nm', 25, 13, 'Dele e dos seus descendentes será a aliança do sacerdócio perpétuo, porque ele foi zeloso pelo seu Deus e fez propiciação pelos israelitas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4485, 'nvi', 'Números', 'nm', 25, 14, 'O nome do israelita que foi morto com a midianita era Zinri, filho de Salu, líder de uma família simeonita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4486, 'nvi', 'Números', 'nm', 25, 15, 'E o nome da mulher midianita que morreu era Cosbi, filha de Zur, chefe de um clã midianita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4487, 'nvi', 'Números', 'nm', 25, 16, 'O Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4488, 'nvi', 'Números', 'nm', 25, 17, '"Tratem os midianitas como inimigos e matem-nos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4489, 'nvi', 'Números', 'nm', 25, 18, 'porque trataram vocês como inimigos quando os enganaram no caso de Peor e de Cosbi, filha de um líder midianita, mulher do povo deles que foi morta quando a praga que enviei por causa de Peor".');
