-- Inserções para Números 33
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4761, 'nvi', 'Números', 'nm', 33, 1, 'Estas são as jornadas dos israelitas quando saíram do Egito, organizados segundo as suas divisões, sob a liderança de Moisés e Arão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4762, 'nvi', 'Números', 'nm', 33, 2, 'Por ordem do Senhor Moisés registrou as etapas da jornada deles. Esta foi a jornada deles, por etapas:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4763, 'nvi', 'Números', 'nm', 33, 3, 'Os israelitas partiram de Ramessés no décimo quinto dia do primeiro mês, no dia seguinte ao da Páscoa. Saíram, marchando desafiadoramente à vista de todos os egípcios,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4764, 'nvi', 'Números', 'nm', 33, 4, 'enquanto estes sepultavam o primeiro filho de cada um deles, que o Senhor matou. O Senhor impôs castigo aos seus deuses.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4765, 'nvi', 'Números', 'nm', 33, 5, 'Os israelitas partiram de Ramessés e acamparam em Sucote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4766, 'nvi', 'Números', 'nm', 33, 6, 'Partiram de Sucote e acamparam em Etã, nos limites do deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4767, 'nvi', 'Números', 'nm', 33, 7, 'Partiram de Etã, voltaram para Pi-Hairote, a leste de Baal-Zefom, e acamparam perto de Migdol.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4768, 'nvi', 'Números', 'nm', 33, 8, 'Partiram de Pi-Hairote e atravessaram o mar chegando ao deserto, e, depois de viajarem três dias no deserto de Etã, acamparam em Mara.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4769, 'nvi', 'Números', 'nm', 33, 9, 'Partiram de Mara e foram para Elim, onde havia doze fontes e setenta palmeiras, e acamparam ali.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4770, 'nvi', 'Números', 'nm', 33, 10, 'Partiram de Elim e acamparam junto ao mar Vermelho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4771, 'nvi', 'Números', 'nm', 33, 11, 'Partiram do mar Vermelho e acamparam no deserto de Sim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4772, 'nvi', 'Números', 'nm', 33, 12, 'Partiram do deserto de Sim e acamparam em Dofca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4773, 'nvi', 'Números', 'nm', 33, 13, 'Partiram de Dofca e acamparam em Alus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4774, 'nvi', 'Números', 'nm', 33, 14, 'Partiram de Alus e acamparam em Refidim, onde não havia água para o povo beber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4775, 'nvi', 'Números', 'nm', 33, 15, 'Partiram de Refidim e acamparam no deserto do Sinai.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4776, 'nvi', 'Números', 'nm', 33, 16, 'Partiram do deserto do Sinai e acamparam em Quibrote-Hataavá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4777, 'nvi', 'Números', 'nm', 33, 17, 'Partiram de Quibrote-Hataavá e acamparam em Hazerote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4778, 'nvi', 'Números', 'nm', 33, 18, 'Partiram de Hazerote e acamparam em Ritmá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4779, 'nvi', 'Números', 'nm', 33, 19, 'Partiram de Ritmá e acamparam em Rimom-Perez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4780, 'nvi', 'Números', 'nm', 33, 20, 'Partiram de Rimom-Perez e acamparam em Libna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4781, 'nvi', 'Números', 'nm', 33, 21, 'Partiram de Libna e acamparam em Rissa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4782, 'nvi', 'Números', 'nm', 33, 22, 'Partiram de Rissa e acamparam em Queelata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4783, 'nvi', 'Números', 'nm', 33, 23, 'Partiram de Queelata e acamparam no monte Séfer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4784, 'nvi', 'Números', 'nm', 33, 24, 'Partiram do monte Séfer e acamparam em Harada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4785, 'nvi', 'Números', 'nm', 33, 25, 'Partiram de Harada e acamparam em Maquelote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4786, 'nvi', 'Números', 'nm', 33, 26, 'Partiram de Maquelote e acamparam em Taate.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4787, 'nvi', 'Números', 'nm', 33, 27, 'Partiram de Taate e acamparam em Terá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4788, 'nvi', 'Números', 'nm', 33, 28, 'Partiram de Terá e acamparam em Mitca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4789, 'nvi', 'Números', 'nm', 33, 29, 'Partiram de Mitca e acamparam em Hasmona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4790, 'nvi', 'Números', 'nm', 33, 30, 'Partiram de Hasmona e acamparam em Moserote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4791, 'nvi', 'Números', 'nm', 33, 31, 'Partiram de Moserote e acamparam em Benê-Jaacã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4792, 'nvi', 'Números', 'nm', 33, 32, 'Partiram de Benê-Jaacã e acamparam em Hor-Gidgade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4793, 'nvi', 'Números', 'nm', 33, 33, 'Partiram de Hor-Gidgade e acamparam em Jotbatá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4794, 'nvi', 'Números', 'nm', 33, 34, 'Partiram de Jotbatá e acamparam em Abrona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4795, 'nvi', 'Números', 'nm', 33, 35, 'Partiram de Abrona e acamparam em Eziom-Geber.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4796, 'nvi', 'Números', 'nm', 33, 36, 'Partiram de Eziom-Geber e acamparam em Cades, no deserto de Zim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4797, 'nvi', 'Números', 'nm', 33, 37, 'Partiram de Cades e acamparam no monte Hor, na fronteira de Edom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4798, 'nvi', 'Números', 'nm', 33, 38, 'Por ordem do Senhor, o sacerdote Arão subiu o monte Hor, onde morreu no dia primeiro do quinto mês do quadragésimo ano depois que os israelitas saíram do Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4799, 'nvi', 'Números', 'nm', 33, 39, 'Arão tinha cento e vinte e três anos de idade quando morreu no monte Hor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4800, 'nvi', 'Números', 'nm', 33, 40, 'O rei cananeu de Arade, que vivia no Neguebe, na terra de Canaã, soube que os israelitas estavam chegando.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4801, 'nvi', 'Números', 'nm', 33, 41, 'Eles partiram do monte Hor e acamparam em Zalmona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4802, 'nvi', 'Números', 'nm', 33, 42, 'Partiram de Zalmona e acamparam em Punom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4803, 'nvi', 'Números', 'nm', 33, 43, 'Partiram de Punom e acamparam em Obote.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4804, 'nvi', 'Números', 'nm', 33, 44, 'Partiram de Obote e acamparam em Ijé-Abarim, na fronteira de Moabe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4805, 'nvi', 'Números', 'nm', 33, 45, 'Partiram de Ijim e acamparam em Dibom-Gade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4806, 'nvi', 'Números', 'nm', 33, 46, 'Partiram de Dibom-Gade e acamparam em Almom-Diblataim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4807, 'nvi', 'Números', 'nm', 33, 47, 'Partiram de Almom-Diblataim e acamparam nos montes de Abarim, defronte de Nebo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4808, 'nvi', 'Números', 'nm', 33, 48, 'Partiram dos montes de Abarim e acamparam nas campinas de Moabe junto ao Jordão, do outro lado de Jericó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4809, 'nvi', 'Números', 'nm', 33, 49, 'Nas campinas de Moabe eles acamparam junto ao Jordão, desde Bete-Jesimote até Abel-Sitim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4810, 'nvi', 'Números', 'nm', 33, 50, 'Nas campinas de Moabe, junto ao Jordão, do outro lado de Jericó, o Senhor disse a Moisés:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4811, 'nvi', 'Números', 'nm', 33, 51, '"Diga aos israelitas: Quando vocês atravessarem o Jordão para entrar em Canaã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4812, 'nvi', 'Números', 'nm', 33, 52, 'expulsem da frente de vocês todos os habitantes da terra. Destruam todas as imagens esculpidas e todos os ídolos fundidos, e derrubem todos os altares idólatras deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4813, 'nvi', 'Números', 'nm', 33, 53, 'Apoderem-se da terra e instalem-se nela, pois eu lhes dei a terra para que dela tomem posse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4814, 'nvi', 'Números', 'nm', 33, 54, 'Distribuam a terra por sorteio, de acordo com os seus clãs. Aos clãs vocês darão uma herança maior, e aos menores, uma herança menor. Cada clã receberá a terra que lhe cair por sorte. Distribuam-na entre as tribos dos seus antepassados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4815, 'nvi', 'Números', 'nm', 33, 55, '"Se, contudo, vocês não expulsarem os habitantes da terra, aqueles que vocês permitirem ficar se tornarão farpas em seus olhos e espinhos em suas costas. Eles lhes causarão problemas na terra em que vocês irão morar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4816, 'nvi', 'Números', 'nm', 33, 56, 'Então farei a vocês o mesmo que planejo fazer a eles".');
