-- Inserções para Números 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4060, 'nvi', 'Números', 'nm', 12, 1, 'Miriã e Arão começaram a criticar Moisés porque ele havia se casado com uma mulher cuxita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4061, 'nvi', 'Números', 'nm', 12, 2, '"Será que o Senhor tem falado apenas por meio de Moisés? ", perguntaram. "Também não tem ele falado por meio de nós? " E o Senhor ouviu isso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4062, 'nvi', 'Números', 'nm', 12, 3, 'Ora, Moisés era um homem muito paciente, mais do que qualquer outro que havia na terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4063, 'nvi', 'Números', 'nm', 12, 4, 'Imediatamente o Senhor disse a Moisés, a Arão e a Miriã: "Dirijam-se à Tenda do Encontro, vocês três". E os três foram para lá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4064, 'nvi', 'Números', 'nm', 12, 5, 'Então o Senhor desceu numa coluna de nuvem e, pondo-se à entrada da Tenda, chamou Arão e Miriã. Os dois vieram à frente,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4065, 'nvi', 'Números', 'nm', 12, 6, 'e ele disse: "Ouçam as minhas palavras: Quando entre vocês há um profeta do Senhor, a ele me revelo em visões, em sonhos falo com ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4066, 'nvi', 'Números', 'nm', 12, 7, 'Não é assim, porém, com meu servo Moisés, que é fiel em toda a minha casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4067, 'nvi', 'Números', 'nm', 12, 8, 'Com ele falo face a face, claramente, e não por enigmas; e ele vê a forma do Senhor. Por que não temeram criticar meu servo Moisés? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4068, 'nvi', 'Números', 'nm', 12, 9, 'Então a ira do Senhor acendeu-se contra eles, e ele os deixou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4069, 'nvi', 'Números', 'nm', 12, 10, 'Quando a nuvem se afastou da Tenda, Miriã estava leprosa; sua aparência era como a da neve. Arão voltou-se para ela, viu que ela estava com lepra');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4070, 'nvi', 'Números', 'nm', 12, 11, 'e disse a Moisés: "Por favor, meu senhor, não nos castigue pelo pecado que tão tolamente cometemos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4071, 'nvi', 'Números', 'nm', 12, 12, 'Não permita que ela fique como um feto abortado que sai do ventre de sua mãe com a metade do corpo destruído".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4072, 'nvi', 'Números', 'nm', 12, 13, 'Então Moisés clamou ao Senhor: "Ó Deus, por misericórdia, cura-a! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4073, 'nvi', 'Números', 'nm', 12, 14, 'O Senhor respondeu a Moisés: "Se o pai dela lhe tivesse cuspido no rosto, não estaria ela envergonhada sete dias? Que fique isolada fora do acampamento sete dias; depois ela poderá ser trazida de volta".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4074, 'nvi', 'Números', 'nm', 12, 15, 'Então Miriã ficou isolada sete dias fora do acampamento, e o povo não partiu enquanto ela não foi trazida de volta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (4075, 'nvi', 'Números', 'nm', 12, 16, 'Depois disso, partiram de Hazerote e acamparam no deserto de Parã.');
