-- Inserções para Oséias 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22196, 'nvi', 'Oséias', 'os', 8, 1, '"Coloquem a trombeta em seus lábios! É como uma águia sobre o templo do Senhor, porquanto quebraram a minha aliança e se rebelaram contra a minha Lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22197, 'nvi', 'Oséias', 'os', 8, 2, 'Israel clama a mim: ‘Ó nosso Deus, nós te reconhecemos! ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22198, 'nvi', 'Oséias', 'os', 8, 3, 'Mas Israel rejeitou o que é bom; um inimigo o perseguirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22199, 'nvi', 'Oséias', 'os', 8, 4, 'Eles instituíram reis sem o meu consentimento; escolheram líderes sem a minha aprovação. Com prata e ouro fizeram ídolos para si, para a sua própria destruição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22200, 'nvi', 'Oséias', 'os', 8, 5, 'Lance fora o seu ídolo em forma de bezerro, ó Samaria! A minha ira se acende contra eles. Até quando serão incapazes de pureza?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22201, 'nvi', 'Oséias', 'os', 8, 6, 'Este bezerro procede de Israel! Um escultor o fez. Ele não é Deus. Será partido em pedaços o bezerro de Samaria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22202, 'nvi', 'Oséias', 'os', 8, 7, '"Eles semeiam vento e colhem tempestade. O talo não tem espiga; não produzirá farinha. Caso produzisse o trigo, estrangeiros o devorariam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22203, 'nvi', 'Oséias', 'os', 8, 8, 'Israel é devorado; agora está entre as nações como algo sem valor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22204, 'nvi', 'Oséias', 'os', 8, 9, 'Pois eles foram para a Assíria. O jumento selvagem mantém-se livre, mas Efraim vendeu-se para os seus amantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22205, 'nvi', 'Oséias', 'os', 8, 10, 'Embora se tenham vendido às nações, agora os ajuntarei, e logo começarão a definhar sob a opressão do rei poderoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22206, 'nvi', 'Oséias', 'os', 8, 11, '"Embora Efraim tenha construído muitos altares para ofertas pelo pecado, eles se tornaram altares para o pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22207, 'nvi', 'Oséias', 'os', 8, 12, 'Eu lhes escrevi todos os ensinos da minha Lei, mas eles os consideraram algo estranho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22208, 'nvi', 'Oséias', 'os', 8, 13, 'Eles me oferecem sacrifícios e comem a carne, mas o Senhor não se agrada deles. Doravante, ele se lembrará da impiedade deles e castigará os seus pecados: eles voltarão para o Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22209, 'nvi', 'Oséias', 'os', 8, 14, 'Israel esqueceu o seu Criador e construiu palácios; Judá fortificou muitas cidades. Mas sobre as suas cidades enviarei fogo que consumirá suas fortalezas. "');
