-- Inserções para Oséias 10
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22227, 'nvi', 'Oséias', 'os', 10, 1, 'Israel era como videira viçosa; cobria-se de frutos. Quanto mais produzia, mais altares construía; Quanto mais sua terra prosperava, mais enfeitava suas colunas sagradas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22228, 'nvi', 'Oséias', 'os', 10, 2, 'O coração deles é enganoso, e agora devem carregar sua culpa. O Senhor demolirá os seus altares e destruirá suas colunas sagradas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22229, 'nvi', 'Oséias', 'os', 10, 3, 'Então eles dirão: "Não temos nenhum rei porque não reverenciamos o Senhor. Mas, mesmo que tivéssemos um rei, o que ele poderia fazer por nós? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22230, 'nvi', 'Oséias', 'os', 10, 4, 'Eles fazem muitas promessas, fazem juramentos e acordos falsos; por isso brotam processos judiciais como ervas venenosas num campo arado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22231, 'nvi', 'Oséias', 'os', 10, 5, 'O povo que mora em Samaria teme pelo ídolo em forma de bezerro de Bete-Áven. Seu povo pranteará por ele, como também os seus sacerdotes idólatras, que se regozijavam por seu esplendor; porque foi tirado deles e levado para o exílio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22232, 'nvi', 'Oséias', 'os', 10, 6, 'Sim, até ele será levado para a Assíria como tributo para o grande rei. Efraim sofrerá humilhação; e Israel será envergonhado pelo seu ídolo de madeira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22233, 'nvi', 'Oséias', 'os', 10, 7, 'Samaria e seu rei serão arrastados como um graveto nas águas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22234, 'nvi', 'Oséias', 'os', 10, 8, 'Os altares da impiedade, que foram os pecados de Israel, serão destruídos. Espinhos e ervas daninhas crescerão e cobrirão os seus altares. Então eles dirão aos montes: "Cubram-nos! ", e às colinas: "Caiam sobre nós! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22235, 'nvi', 'Oséias', 'os', 10, 9, '"Desde os dias de Gibeá, você tem pecado, ó Israel, e não mudou. Acaso a guerra não os alcançou em Gibeá por causa dos malfeitores?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22236, 'nvi', 'Oséias', 'os', 10, 10, 'Quando eu quiser, os castigarei; nações serão reunidas contra eles para prendê-los por causa do seu duplo pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22237, 'nvi', 'Oséias', 'os', 10, 11, 'Efraim era bezerra treinada, gostava muito de trilhar; por isso colocarei o jugo sobre o seu belo pescoço. Conduzirei Efraim, Judá terá que arar, e Jacó fará sulcos no solo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22238, 'nvi', 'Oséias', 'os', 10, 12, 'Semeiem a retidão para si, colham o fruto da lealdade, e façam sulcos no seu solo não arado; pois é hora de buscar o Senhor, até que ele venha e faça chover justiça sobre vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22239, 'nvi', 'Oséias', 'os', 10, 13, 'Mas vocês plantaram a impiedade, colheram o mal e comeram o fruto do engano. Visto que vocês têm confiado na sua própria força e nos seus muitos guerreiros,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22240, 'nvi', 'Oséias', 'os', 10, 14, 'o fragor da batalha se levantará contra vocês, de maneira que todas as suas fortalezas serão devastadas, como Salmã devastou Bete-Arbel no dia da batalha, quando mães foram pisadas e estraçalhadas junto com seus filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22241, 'nvi', 'Oséias', 'os', 10, 15, 'Assim acontecerá com você, ó Betel, porque a sua impiedade é grande. Quando amanhecer aquele dia, o rei de Israel será completamente destruído.');
