-- Inserções para Oséias 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22180, 'nvi', 'Oséias', 'os', 7, 1, '"Quando eu tento curar Israel, o mal de Efraim fica exposto e os crimes de Samaria são revelados. Pois praticam o engano, ladrões entram nas casas, bandidos roubam nas ruas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22181, 'nvi', 'Oséias', 'os', 7, 2, 'mas eles não percebem que eu me lembro de todas as suas más obras. Seus pecados os envolvem; eu os vejo constantemente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22182, 'nvi', 'Oséias', 'os', 7, 3, '"Eles alegram o rei com as suas impiedades, os líderes com as suas mentiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22183, 'nvi', 'Oséias', 'os', 7, 4, 'São todos adúlteros, queimando como um forno cujo fogo o padeiro não precisa atiçar desde sova a massa até quando a faz crescer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22184, 'nvi', 'Oséias', 'os', 7, 5, 'No dia da festa de nosso rei os líderes são inflamados pelo vinho, e ele dá as mãos aos zombadores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22185, 'nvi', 'Oséias', 'os', 7, 6, 'Quando se aproximam com suas intrigas, seus corações ardem como um forno. A fúria deles arde lentamente, a noite toda; pela manhã queima como chama abrasadora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22186, 'nvi', 'Oséias', 'os', 7, 7, 'Todos eles se esquentam como um forno, e devoram os seus governantes. Todos os seus reis caem, e ninguém clama a mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22187, 'nvi', 'Oséias', 'os', 7, 8, '"Efraim mistura-se com as nações; Efraim é um bolo que não foi virado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22188, 'nvi', 'Oséias', 'os', 7, 9, 'Estrangeiros sugam sua força, mas ele não o percebe. A cinza espalha-se pelo seu cabelo, mas ele nem repara.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22189, 'nvi', 'Oséias', 'os', 7, 10, 'A arrogância de Israel testifica contra ele, mas, apesar de tudo isso, ele não se volta para o Senhor, para o seu Deus, e não o busca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22190, 'nvi', 'Oséias', 'os', 7, 11, '"Efraim é como uma pomba facilmente enganada e sem entendimento; uma hora apela para o Egito, outra hora se volta para a Assíria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22191, 'nvi', 'Oséias', 'os', 7, 12, 'Quando se forem, atirarei sobre eles a minha rede; eu os farei descer como as aves do céu. Quando os ouvir se reunindo, eu os apanharei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22192, 'nvi', 'Oséias', 'os', 7, 13, 'Ai deles, porque se afastaram de mim! Destruição sobre eles, porque se rebelaram contra mim! Eu desejo redimi-los, mas eles falam mentiras a meu respeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22193, 'nvi', 'Oséias', 'os', 7, 14, 'Eles não clamam a mim do fundo do coração quando gemem orando em suas camas. Ajuntam-se por causa do trigo e do vinho, mas se afastam de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22194, 'nvi', 'Oséias', 'os', 7, 15, 'Eu os ensinei e os fortaleci, mas eles tramam o mal contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22195, 'nvi', 'Oséias', 'os', 7, 16, 'Eles não se voltam para o Altíssimo; são como um arco defeituoso. Seus líderes serão mortos à espada por causa de suas palavras insolentes. E por isso serão ridicularizados no Egito.');
