-- Inserções para Oséias 11
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22242, 'nvi', 'Oséias', 'os', 11, 1, '"Quando Israel era menino, eu o amei, e do Egito chamei o meu filho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22243, 'nvi', 'Oséias', 'os', 11, 2, 'Mas, quanto mais eu o chamava, mais eles se afastavam de mim. Eles ofereceram sacrifícios aos baalins e queimaram incenso os ídolos esculpidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22244, 'nvi', 'Oséias', 'os', 11, 3, 'Mas fui eu quem ensinou Efraim a andar, tomando-o nos braços; mas eles não perceberam que fui eu quem os curou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22245, 'nvi', 'Oséias', 'os', 11, 4, 'Eu os conduzi com laços de bondade humana e de amor; tirei do seu pescoço o jugo e me inclinei para alimentá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22246, 'nvi', 'Oséias', 'os', 11, 5, '"Acaso não voltarão ao Egito e a Assíria não os dominará porque eles se recusam a arrepender-se?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22247, 'nvi', 'Oséias', 'os', 11, 6, 'A espada reluzirá em suas cidades, destruirá as trancas de suas portas e dará fim aos seus planos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22248, 'nvi', 'Oséias', 'os', 11, 7, 'O meu povo está decidido a desviar-se de mim. Embora sejam conclamados a servir ao Altíssimo, de modo algum o exaltam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22249, 'nvi', 'Oséias', 'os', 11, 8, '"Como posso desistir de você, Efraim? Como posso entregar você nas mãos de outros, Israel? Como posso tratá-lo como tratei Admá? Como posso fazer com você o que fiz com Zeboim? O meu coração está enternecido, despertou-se toda a minha compaixão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22250, 'nvi', 'Oséias', 'os', 11, 9, 'Não executarei a minha ira impetuosa, não tornarei a destruir Efraim. Pois sou Deus, e não homem, o Santo no meio de vocês. Não virei com ira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22251, 'nvi', 'Oséias', 'os', 11, 10, 'Eles seguirão o Senhor; ele rugirá como leão. Quando ele rugir, os seus filhos virão tremendo desde o Ocidente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22252, 'nvi', 'Oséias', 'os', 11, 11, 'Virão voando do Egito como aves, da Assíria como pombas. Eu os estabelecerei em seus lares"; palavra do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22253, 'nvi', 'Oséias', 'os', 11, 12, 'Efraim me cercou de mentiras, a casa de Israel de enganos, e Judá é rebelde contra Deus, a saber, contra o Santo fiel.');
