-- Inserções para Oséias 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22210, 'nvi', 'Oséias', 'os', 9, 1, 'Não se regozije, ó Israel; não se alegre como as outras nações. Pois você se prostituiu, abandonando o seu Deus; você ama o salário da prostituição em cada eira de trigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22211, 'nvi', 'Oséias', 'os', 9, 2, 'Os produtos da eira e do lagar não alimentarão o povo; o vinho novo lhes faltará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22212, 'nvi', 'Oséias', 'os', 9, 3, 'Eles não permanecerão na terra do Senhor; Efraim voltará para o Egito, e na Assíria comerá comida impura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22213, 'nvi', 'Oséias', 'os', 9, 4, 'Eles não derramarão ofertas de vinho para o Senhor, nem o agradarão os seus sacrifícios. Tais sacrifícios serão para eles como o pão dos pranteadores, que torna impuro quem o come. Essa comida será para eles mesmos; não entrará no templo do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22214, 'nvi', 'Oséias', 'os', 9, 5, 'O que farão vocês no dia de suas festas fixas, nos dias de festa do Senhor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22215, 'nvi', 'Oséias', 'os', 9, 6, 'Vejam! Fogem da destruição, mas o Egito os ajuntará, e Mênfis os sepultará. Os seus tesouros de prata as urtigas vão herdar; os cardos cobrirão totalmente as suas tendas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22216, 'nvi', 'Oséias', 'os', 9, 7, 'Os dias de castigo vêm, os dias de punição estão chegando. Que Israel o saiba. Por serem tantos os pecados, e tanta a hostilidade de vocês, o profeta é considerado um tolo, o homem inspirado, um louco violento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22217, 'nvi', 'Oséias', 'os', 9, 8, 'O profeta, junto ao meu Deus, é a sentinela que vigia Efraim, contudo, laços o aguardam em todas as suas veredas, e a hostilidade no templo do seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22218, 'nvi', 'Oséias', 'os', 9, 9, 'Eles mergulharam na corrupção, como nos dias de Gibeá. Deus se lembrará de sua iniqüidade e os castigará por seus pecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22219, 'nvi', 'Oséias', 'os', 9, 10, '"Quando encontrei Israel, foi como encontrar uvas no deserto; quando vi os antepassados de vocês, foi como ver os primeiros frutos de uma figueira. Mas, quando eles vieram a Baal-Peor, consagraram-se àquele ídolo vergonhoso e se tornaram tão repugnantes quanto aquilo que amaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22220, 'nvi', 'Oséias', 'os', 9, 11, 'A glória de Efraim lhe fugirá como pássaro: nenhum nascimento, nenhuma gravidez, nenhuma concepção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22221, 'nvi', 'Oséias', 'os', 9, 12, 'Mesmo que criem filhos, porei de luto cada um deles. Ai deles quando eu me afastar!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22222, 'nvi', 'Oséias', 'os', 9, 13, 'Vi Efraim, plantado num lugar agradável, como Tiro. Mas Efraim entregará seus filhos ao matador. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22223, 'nvi', 'Oséias', 'os', 9, 14, 'Ó Senhor, que darás a eles? Dá-lhes ventres que abortem e seios ressecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22224, 'nvi', 'Oséias', 'os', 9, 15, '"Toda a sua impiedade começou em Gilgal; de fato, ali eu os odiei. Por causa dos seus pecados, eu os expulsarei da minha terra. Não os amarei mais; todos os seus líderes são rebeldes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22225, 'nvi', 'Oséias', 'os', 9, 16, 'Efraim está ferido, sua raiz está seca, eles não produzem frutos. Mesmo que criem filhos, eu matarei sua querida prole. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22226, 'nvi', 'Oséias', 'os', 9, 17, 'Meu Deus os rejeitará porque não lhe deram ouvidos; serão peregrinos entre as nações.');
