-- Inserções para Oséias 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22254, 'nvi', 'Oséias', 'os', 12, 1, 'Efraim alimenta-se de vento; vai atrás do vento oriental o dia inteiro e multiplica mentiras e violência. Faz tratados com a Assíria e manda azeite para o Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22255, 'nvi', 'Oséias', 'os', 12, 2, 'O Senhor tem uma acusação contra Judá, e vai castigar Jacó de acordo com os seus caminhos; de acordo com suas ações lhe retribuirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22256, 'nvi', 'Oséias', 'os', 12, 3, 'No ventre da mãe segurou o calcanhar de seu irmão; como homem lutou com Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22257, 'nvi', 'Oséias', 'os', 12, 4, 'Ele lutou com o anjo e saiu vencedor; chorou e implorou o seu favor. Em Betel encontrou a Deus que ali conversou com ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22258, 'nvi', 'Oséias', 'os', 12, 5, 'Sim, o próprio Senhor, o Deus dos Exércitos! Senhor é o nome pelo qual ficou famoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22259, 'nvi', 'Oséias', 'os', 12, 6, 'Portanto, volte para o seu Deus; pratique a lealdade e a justiça, e confie sempre no seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22260, 'nvi', 'Oséias', 'os', 12, 7, 'Como os descendentes de Canaã, comerciantes que usam balança desonesta e gostam muito de extorquir,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22261, 'nvi', 'Oséias', 'os', 12, 8, 'Efraim orgulha-se e exclama: "Como fiquei rico e abastado! Em todos os trabalhos que realizei, não encontrarão em mim nenhum crime ou pecado".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22262, 'nvi', 'Oséias', 'os', 12, 9, '"Mas eu sou o Senhor, o seu Deus, desde a terra do Egito; farei vocês voltarem a morar em tendas, como no dia de suas festas fixas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22263, 'nvi', 'Oséias', 'os', 12, 10, 'Eu mesmo falava aos profetas, dava-lhes muitas visões, e por meio deles falava em parábolas. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22264, 'nvi', 'Oséias', 'os', 12, 11, 'Como Gileade é ímpia! Seu povo não vale nada! Eles sacrificam bois em Gilgal, mas os seus altares são como montes de pedras num campo arado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22265, 'nvi', 'Oséias', 'os', 12, 12, 'Jacó fugiu para a terra de Arã; Israel trabalhou para obter uma mulher; por ela cuidou de ovelhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22266, 'nvi', 'Oséias', 'os', 12, 13, 'O Senhor usou um profeta para tirar Israel do Egito, e por meio de um profeta cuidou dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22267, 'nvi', 'Oséias', 'os', 12, 14, 'Efraim amargamente o provocou à ira; seu Senhor fará cair sobre ele a culpa do sangue que derramou e lhe devolverá o seu desprezo.');
