-- Inserções para Oséias 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22169, 'nvi', 'Oséias', 'os', 6, 1, '"Venham, voltemos para o Senhor. Ele nos despedaçou, mas nos trará cura; ele nos feriu, mas sarará nossas feridas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22170, 'nvi', 'Oséias', 'os', 6, 2, 'Depois de dois dias ele nos dará vida novamente; ao terceiro dia nos restaurará, para que vivamos em sua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22171, 'nvi', 'Oséias', 'os', 6, 3, 'Conheçamos o Senhor; esforcemo-nos por conhecê-lo. Tão certo como nasce o sol, ele aparecerá; virá para nós como as chuvas de inverno, como as chuvas de primavera que regam a terra. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22172, 'nvi', 'Oséias', 'os', 6, 4, '"Que posso fazer com você, Efraim? Que posso fazer com você, Judá? Seu amor é como a neblina da manhã, como o primeiro orvalho que logo evapora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22173, 'nvi', 'Oséias', 'os', 6, 5, 'Por isso eu os despedacei por meio dos meus profetas, eu os matei com as palavras da minha boca; os meus juízos reluziram como relâmpagos sobre vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22174, 'nvi', 'Oséias', 'os', 6, 6, 'Pois desejo misericórdia, não sacrifícios, e conhecimento de Deus em vez de holocaustos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22175, 'nvi', 'Oséias', 'os', 6, 7, 'Na cidade de Adão, eles quebraram a aliança, e me foram infiéis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22176, 'nvi', 'Oséias', 'os', 6, 8, 'Gileade é uma cidade de ímpios, maculada de sangue.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22177, 'nvi', 'Oséias', 'os', 6, 9, 'Assim como os assaltantes ficam de emboscada à espera de um homem, assim fazem também os bandos de sacerdotes; eles assassinam na estrada de Siquém e cometem outros crimes vergonhosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22178, 'nvi', 'Oséias', 'os', 6, 10, 'Vi uma coisa terrível na terra de Israel. Ali Efraim se prostitui, e Israel está contaminado".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22179, 'nvi', 'Oséias', 'os', 6, 11, '"Também para você, Judá, foi determinada uma colheita para quando eu trouxer de volta o meu povo.');
