-- Inserções para Oséias 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22096, 'nvi', 'Oséias', 'os', 1, 1, 'Palavra do Senhor que veio a Oséias, filho de Beeri, durante os reinados de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e de Jeroboão, filho de Jeoás, rei de Israel:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22097, 'nvi', 'Oséias', 'os', 1, 2, 'Quando o Senhor começou a falar por meio de Oséias, o Senhor lhe disse: "Vá, tome uma mulher adúltera e filhos da infidelidade, porque a nação é culpada do mais vergonhoso adultério por afastar-se do Senhor".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22098, 'nvi', 'Oséias', 'os', 1, 3, 'Por isso ele se casou com Gômer, filha de Diblaim; ela engravidou e lhe deu um filho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22099, 'nvi', 'Oséias', 'os', 1, 4, 'Então o Senhor disse a Oséias: "Dê a ele o nome de Jezreel, porque logo castigarei a dinastia de Jeú por causa do massacre ocorrido em Jezreel, e darei fim ao reino de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22100, 'nvi', 'Oséias', 'os', 1, 5, 'Naquele dia quebrarei o arco de Israel no vale de Jezreel".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22101, 'nvi', 'Oséias', 'os', 1, 6, 'Gômer engravidou novamente e deu à luz uma filha. Então o Senhor disse a Oséias: "Dê a ela o nome de Lo-Ruama, pois não mais mostrarei amor para com a nação de Israel, a ponto de perdoá-la.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22102, 'nvi', 'Oséias', 'os', 1, 7, 'Contudo, tratarei com amor a nação de Judá; e eu lhes concederei vitória, não pelo arco, pela espada ou por combate, nem por cavalos e cavaleiros, mas pelo Senhor, o seu Deus".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22103, 'nvi', 'Oséias', 'os', 1, 8, 'Depois de ter desmamado Lo-Ruama, Gômer teve outro filho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22104, 'nvi', 'Oséias', 'os', 1, 9, 'Então o Senhor disse: "Dê a ele o nome de Lo-Ami, pois vocês não são meu povo, e eu não sou seu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22105, 'nvi', 'Oséias', 'os', 1, 10, '"Contudo os israelitas ainda serão como a areia da praia, que não se pode medir nem contar. No lugar onde se dizia a eles: ‘Vocês não são meu povo’, eles serão chamados ‘filhos do Deus vivo’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22106, 'nvi', 'Oséias', 'os', 1, 11, 'O povo de Judá e o povo de Israel serão reunidos, e eles designarão para si um só líder, e se levantarão da terra, pois será grande o dia de Jezreel.');
