-- Inserções para Oséias 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22268, 'nvi', 'Oséias', 'os', 13, 1, 'Quando Efraim falava, os homens tremiam; ele era exaltado em Israel. Mas tornou-se culpado da adoração de Baal e começou a morrer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22269, 'nvi', 'Oséias', 'os', 13, 2, 'Agora eles pecam cada vez mais; com sua prata fazem ídolos de metal para si, imagens modeladas com muita inteligência, todas elas obras de artesãos. Dizem desse povo: "Eles oferecem sacrifício humano e beijam os ídolos feitos em forma de bezerro".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22270, 'nvi', 'Oséias', 'os', 13, 3, 'Por isso serão como a neblina da manhã, como o orvalho que bem cedo evapora, como palha que num redemoinho vai-se de uma eira, como a fumaça que sai pela chaminé.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22271, 'nvi', 'Oséias', 'os', 13, 4, '"Mas eu sou o Senhor, o seu Deus, desde a terra do Egito. Vocês não reconhecerão nenhum outro Deus além de mim, nenhum outro Salvador senão a mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22272, 'nvi', 'Oséias', 'os', 13, 5, 'Eu cuidei de vocês no deserto, naquela terra de calor ardente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22273, 'nvi', 'Oséias', 'os', 13, 6, 'Quando eu os alimentava, ficavam satisfeitos; quando ficavam satisfeitos, se orgulhavam, e então me esqueciam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22274, 'nvi', 'Oséias', 'os', 13, 7, 'Por isso virei sobre eles como leão, como leopardo, ficarei à espreita junto ao caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22275, 'nvi', 'Oséias', 'os', 13, 8, 'Como uma ursa de quem roubaram os filhotes, eu os atacarei e os rasgarei. Como leão eu os devorarei; um animal selvagem os despedaçará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22276, 'nvi', 'Oséias', 'os', 13, 9, '"Você foi destruído, ó Israel, porque está contra mim, contra o seu ajudador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22277, 'nvi', 'Oséias', 'os', 13, 10, 'E agora? Onde está o seu rei que havia de salvá-lo em todas as suas cidades? E os oficiais que você pediu, dizendo: ‘Dá-me um rei e líderes’?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22278, 'nvi', 'Oséias', 'os', 13, 11, 'Dei-lhe um rei na minha ira, e o tirei na minha indignação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22279, 'nvi', 'Oséias', 'os', 13, 12, 'A culpa de Efraim foi anotada, seus pecados são mantidos em registro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22280, 'nvi', 'Oséias', 'os', 13, 13, 'Chegam-lhe dores como as da mulher em trabalho de parto, mas ele não é uma criança inteligente; quando chega a hora, não sai do ventre que abrigou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22281, 'nvi', 'Oséias', 'os', 13, 14, '"Eu os redimirei do poder da sepultura; eu os resgatarei da morte. Onde estão, ó morte, as suas pragas? Onde está, ó sepultura, a sua destruição? "Não terei compaixão alguma,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22282, 'nvi', 'Oséias', 'os', 13, 15, 'embora ele floresça entre os seus irmãos. Um vento oriental virá da parte do Senhor, soprando desde o deserto; sua fonte falhará, e seu poço secará. Todos os seus tesouros serão saqueados dos seus depósitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22283, 'nvi', 'Oséias', 'os', 13, 16, 'O povo de Samaria carregará sua culpa, porque se rebelou contra o seu Deus. Eles serão mortos à espada; seus pequeninos serão pisados e despedaçados, suas mulheres grávidas terão rasgados os seus ventres. "');
