-- Inserções para Provérbios 15
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16809, 'nvi', 'Provérbios', 'pv', 15, 1, 'A resposta calma desvia a fúria, mas a palavra ríspida desperta a ira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16810, 'nvi', 'Provérbios', 'pv', 15, 2, 'A língua dos sábios torna atraente o conhecimento, mas a boca dos tolos derrama insensatez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16811, 'nvi', 'Provérbios', 'pv', 15, 3, 'Os olhos do Senhor estão em toda parte, observando atentamente os maus e os bons.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16812, 'nvi', 'Provérbios', 'pv', 15, 4, 'O falar amável é árvore de vida, mas o falar enganoso esmaga o espírito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16813, 'nvi', 'Provérbios', 'pv', 15, 5, 'O insensato faz pouco caso da disciplina de seu pai, mas quem acolhe a repreensão revela prudência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16814, 'nvi', 'Provérbios', 'pv', 15, 6, 'A casa do justo contém grande tesouro, mas os rendimentos dos ímpios lhes trazem inquietação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16815, 'nvi', 'Provérbios', 'pv', 15, 7, 'As palavras dos sábios espalham conhecimento; mas o coração dos tolos não é assim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16816, 'nvi', 'Provérbios', 'pv', 15, 8, 'O Senhor detesta o sacrifício dos ímpios, mas a oração do justo o agrada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16817, 'nvi', 'Provérbios', 'pv', 15, 9, 'O Senhor detesta o caminho dos ímpios, mas ama quem busca a justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16818, 'nvi', 'Provérbios', 'pv', 15, 10, 'Há uma severa lição para quem abandona o seu caminho; quem despreza a repreensão morrerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16819, 'nvi', 'Provérbios', 'pv', 15, 11, 'A Sepultura e a Destruição estão abertas diante do Senhor; quanto mais os corações dos homens!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16820, 'nvi', 'Provérbios', 'pv', 15, 12, 'O zombador não gosta de quem o corrige, nem procura a ajuda do sábio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16821, 'nvi', 'Provérbios', 'pv', 15, 13, 'A alegria do coração transparece no rosto, mas o coração angustiado oprime o espírito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16822, 'nvi', 'Provérbios', 'pv', 15, 14, 'O coração que sabe discernir busca o conhecimento, mas a boca dos tolos alimenta-se de insensatez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16823, 'nvi', 'Provérbios', 'pv', 15, 15, 'Todos os dias do oprimido são infelizes, mas o coração bem disposto está sempre em festa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16824, 'nvi', 'Provérbios', 'pv', 15, 16, 'É melhor ter pouco com o temor do Senhor do que grande riqueza com inquietação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16825, 'nvi', 'Provérbios', 'pv', 15, 17, 'É melhor ter verduras na refeição onde há amor do que um boi gordo acompanhado de ódio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16826, 'nvi', 'Provérbios', 'pv', 15, 18, 'O homem irritável provoca dissensão, mas quem é paciente acalma a discussão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16827, 'nvi', 'Provérbios', 'pv', 15, 19, 'O caminho do preguiçoso é cheio de espinhos, mas o caminho do justo é uma estrada plana.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16828, 'nvi', 'Provérbios', 'pv', 15, 20, 'O filho sábio dá alegria a seu pai, mas o tolo despreza a sua mãe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16829, 'nvi', 'Provérbios', 'pv', 15, 21, 'A insensatez alegra quem não tem bom senso, mas o homem de entendimento procede com retidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16830, 'nvi', 'Provérbios', 'pv', 15, 22, 'Os planos fracassam por falta de conselho, mas são bem sucedidos quando há muitos conselheiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16831, 'nvi', 'Provérbios', 'pv', 15, 23, 'Dar resposta apropriada é motivo de alegria; e como é bom um conselho na hora certa!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16832, 'nvi', 'Provérbios', 'pv', 15, 24, 'O caminho da vida conduz para cima quem é sensato, para que ele não desça à sepultura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16833, 'nvi', 'Provérbios', 'pv', 15, 25, 'O Senhor derruba a casa do orgulhoso, mas mantém intactos os limites da propriedade da viúva.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16834, 'nvi', 'Provérbios', 'pv', 15, 26, 'O Senhor detesta os pensamentos dos maus, mas se agrada de palavras sem maldade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16835, 'nvi', 'Provérbios', 'pv', 15, 27, 'O avarento põe sua família em apuros, mas quem repudia o suborno viverá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16836, 'nvi', 'Provérbios', 'pv', 15, 28, 'O justo pensa bem antes de responder, mas a boca dos ímpios jorra o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16837, 'nvi', 'Provérbios', 'pv', 15, 29, 'O Senhor está longe dos ímpios, mas ouve a oração dos justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16838, 'nvi', 'Provérbios', 'pv', 15, 30, 'Um olhar animador dá alegria ao coração, e as boas notícias revigoram os ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16839, 'nvi', 'Provérbios', 'pv', 15, 31, 'Quem ouve a repreensão construtiva terá lugar permanente entre os sábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16840, 'nvi', 'Provérbios', 'pv', 15, 32, 'Quem recusa a disciplina faz pouco caso de si mesmo, mas quem ouve a repreensão obtém entendimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16841, 'nvi', 'Provérbios', 'pv', 15, 33, 'O temor do Senhor ensina a sabedoria, e a humildade antecede a honra.');
