-- Inserções para Provérbios 8
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16604, 'nvi', 'Provérbios', 'pv', 8, 1, 'A sabedoria está clamando, o discernimento ergue a sua voz;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16605, 'nvi', 'Provérbios', 'pv', 8, 2, 'nos lugares altos, junto ao caminho, nos cruzamentos ela se coloca;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16606, 'nvi', 'Provérbios', 'pv', 8, 3, 'ao lado das portas, à entrada da cidade, portas adentro, ela clama em alta voz:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16607, 'nvi', 'Provérbios', 'pv', 8, 4, '"A vocês, homens, eu clamo; a todos levanto a minha voz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16608, 'nvi', 'Provérbios', 'pv', 8, 5, 'Vocês, inexperientes, adquiram a prudência; e vocês, tolos, tenham bom senso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16609, 'nvi', 'Provérbios', 'pv', 8, 6, 'Ouçam, pois tenho coisas importantes para dizer; os meus lábios falarão do que é certo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16610, 'nvi', 'Provérbios', 'pv', 8, 7, 'Minha boca fala a verdade, pois a maldade causa repulsa aos meus lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16611, 'nvi', 'Provérbios', 'pv', 8, 8, 'Todas as minhas palavras são justas; nenhuma delas é distorcida ou perversa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16612, 'nvi', 'Provérbios', 'pv', 8, 9, 'Para os que têm discernimento, são todas claras, e retas para os que têm conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16613, 'nvi', 'Provérbios', 'pv', 8, 10, 'Prefiram a minha instrução à prata, e o conhecimento ao ouro puro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16614, 'nvi', 'Provérbios', 'pv', 8, 11, 'pois a sabedoria é mais preciosa do que rubis; nada do que vocês possam desejar compara-se a ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16615, 'nvi', 'Provérbios', 'pv', 8, 12, '"Eu, a sabedoria, moro com a prudência, e tenho o conhecimento que vem do bom senso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16616, 'nvi', 'Provérbios', 'pv', 8, 13, 'Temer ao Senhor é odiar o mal; odeio o orgulho e a arrogância, o mau comportamento e o falar perverso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16617, 'nvi', 'Provérbios', 'pv', 8, 14, 'Meu é o conselho sensato; a mim pertencem o entendimento e o poder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16618, 'nvi', 'Provérbios', 'pv', 8, 15, 'Por meu intermédio os reis governam, e as autoridades exercem a justiça;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16619, 'nvi', 'Provérbios', 'pv', 8, 16, 'também por meu intermédio governam os nobres, todos os juízes da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16620, 'nvi', 'Provérbios', 'pv', 8, 17, 'Amo os que me amam, e quem me procura me encontra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16621, 'nvi', 'Provérbios', 'pv', 8, 18, 'Comigo estão riquezas e honra, prosperidade e justiça duradouras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16622, 'nvi', 'Provérbios', 'pv', 8, 19, 'Meu fruto é melhor do que o ouro, do que o ouro puro; o que ofereço é superior à prata escolhida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16623, 'nvi', 'Provérbios', 'pv', 8, 20, 'Ando pelo caminho da retidão, pelas veredas da justiça,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16624, 'nvi', 'Provérbios', 'pv', 8, 21, 'concedendo riqueza aos que me amam e enchendo os seus tesouros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16625, 'nvi', 'Provérbios', 'pv', 8, 22, '"O Senhor me criou como o princípio de seu caminho, antes das suas obras mais antigas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16626, 'nvi', 'Provérbios', 'pv', 8, 23, 'fui formada desde a eternidade, desde o princípio, antes de existir a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16627, 'nvi', 'Provérbios', 'pv', 8, 24, 'Nasci quando ainda não havia abismos, quando não existiam fontes de águas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16628, 'nvi', 'Provérbios', 'pv', 8, 25, 'antes de serem estabelecidos os montes e de existirem colinas eu nasci.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16629, 'nvi', 'Provérbios', 'pv', 8, 26, 'Ele ainda não havia feito a terra, nem os campos, nem o pó com o qual formou o mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16630, 'nvi', 'Provérbios', 'pv', 8, 27, 'Quando ele estabeleceu os céus, lá estava eu, quando traçou o horizonte sobre a superfície do abismo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16631, 'nvi', 'Provérbios', 'pv', 8, 28, 'quando colocou as nuvens em cima e estabeleceu as fontes do abismo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16632, 'nvi', 'Provérbios', 'pv', 8, 29, 'quando determinou as fronteiras do mar para que as águas não violassem a sua ordem, quando marcou os limites dos alicerces da terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16633, 'nvi', 'Provérbios', 'pv', 8, 30, 'eu estava ao seu lado, e era o seu arquiteto; dia a dia eu era o seu prazer e me alegrava continuamente com a sua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16634, 'nvi', 'Provérbios', 'pv', 8, 31, 'Eu me alegrava com o mundo que ele criou, e a humanidade me dava alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16635, 'nvi', 'Provérbios', 'pv', 8, 32, '"Ouçam-me agora, meus filhos: Como são felizes os que guardam os meus caminhos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16636, 'nvi', 'Provérbios', 'pv', 8, 33, 'Ouçam a minha instrução, e serão sábios. Não a desprezem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16637, 'nvi', 'Provérbios', 'pv', 8, 34, 'Como é feliz o homem que me ouve, vigiando diariamente à minha porta, esperando junto às portas da minha casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16638, 'nvi', 'Provérbios', 'pv', 8, 35, 'Pois todo aquele que me encontra, encontra a vida e recebe o favor do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16639, 'nvi', 'Provérbios', 'pv', 8, 36, 'Mas aquele que de mim se afasta, a si mesmo se agride; todos os que me odeiam amam a morte".');
