-- Inserções para Provérbios 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16435, 'nvi', 'Provérbios', 'pv', 2, 1, 'Meu filho, se você aceitar as minhas palavras e guardar no coração os meus mandamentos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16436, 'nvi', 'Provérbios', 'pv', 2, 2, 'se der ouvidos à sabedoria e inclinar o coração para o discernimento;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16437, 'nvi', 'Provérbios', 'pv', 2, 3, 'se clamar por entendimento e por discernimento gritar bem alto,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16438, 'nvi', 'Provérbios', 'pv', 2, 4, 'se procurar a sabedoria como se procura a prata e buscá-la como quem busca um tesouro escondido,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16439, 'nvi', 'Provérbios', 'pv', 2, 5, 'então você entenderá o que é temer ao Senhor e achará o conhecimento de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16440, 'nvi', 'Provérbios', 'pv', 2, 6, 'Pois o Senhor é quem dá sabedoria; de sua boca procedem o conhecimento e o discernimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16441, 'nvi', 'Provérbios', 'pv', 2, 7, 'Ele reserva a sensatez para o justo; como um escudo protege quem anda com integridade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16442, 'nvi', 'Provérbios', 'pv', 2, 8, 'pois guarda a vereda do justo e protege o caminho de seus fiéis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16443, 'nvi', 'Provérbios', 'pv', 2, 9, 'Então você entenderá o que é justo, direito e certo, e aprenderá os caminhos do bem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16444, 'nvi', 'Provérbios', 'pv', 2, 10, 'Pois a sabedoria entrará em seu coração, e o conhecimento será agradável à sua alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16445, 'nvi', 'Provérbios', 'pv', 2, 11, 'O bom senso o guardará, e o discernimento o protegerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16446, 'nvi', 'Provérbios', 'pv', 2, 12, 'A sabedoria o livrará do caminho dos maus, dos homens de palavras perversas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16447, 'nvi', 'Provérbios', 'pv', 2, 13, 'que abandonam as veredas retas para andar por caminhos de trevas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16448, 'nvi', 'Provérbios', 'pv', 2, 14, 'têm prazer em fazer o mal e exultam com a maldade dos perversos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16449, 'nvi', 'Provérbios', 'pv', 2, 15, 'gente que anda por veredas tortuosas, e no caminho se extraviam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16450, 'nvi', 'Provérbios', 'pv', 2, 16, 'Ela também o livrará da mulher imoral, da pervertida que seduz com suas palavras,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16451, 'nvi', 'Provérbios', 'pv', 2, 17, 'que abandona aquele que desde a juventude foi seu companheiro e ignora a aliança que fez diante de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16452, 'nvi', 'Provérbios', 'pv', 2, 18, 'Ela se dirige para morte, que é a sua casa, e os seus caminhos levam às sombras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16453, 'nvi', 'Provérbios', 'pv', 2, 19, 'Os que a ela procuram jamais voltarão, nem tornarão a encontrar as veredas da vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16454, 'nvi', 'Provérbios', 'pv', 2, 20, 'A sabedoria o fará andar nos caminhos dos homens de bem e a manter-se nas veredas dos justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16455, 'nvi', 'Provérbios', 'pv', 2, 21, 'Pois os justos habitarão na terra, e os íntegros nela permanecerão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16456, 'nvi', 'Provérbios', 'pv', 2, 22, 'mas os ímpios serão eliminados da terra, e dela os infiéis serão arrancados.');
