-- Inserções para Provérbios 19
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16927, 'nvi', 'Provérbios', 'pv', 19, 1, 'Melhor é o pobre que vive com integridade do que o tolo que fala perversamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16928, 'nvi', 'Provérbios', 'pv', 19, 2, 'Não é bom ter zelo sem conhecimento, nem ser precipitado e perder o caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16929, 'nvi', 'Provérbios', 'pv', 19, 3, 'É a insensatez do homem que arruína a sua vida, mas o seu coração se ira contra o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16930, 'nvi', 'Provérbios', 'pv', 19, 4, 'A riqueza traz muitos amigos, mas até o amigo do pobre o abandona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16931, 'nvi', 'Provérbios', 'pv', 19, 5, 'A testemunha falsa não ficará sem castigo, e aquele que despeja mentiras não sairá livre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16932, 'nvi', 'Provérbios', 'pv', 19, 6, 'Muitos adulam o governante, e todos são amigos de quem dá presentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16933, 'nvi', 'Provérbios', 'pv', 19, 7, 'O pobre é desprezado por todos os seus parentes, quanto mais por seus amigos! Embora os procure, para pedir-lhes ajuda, não os encontra em lugar nenhum.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16934, 'nvi', 'Provérbios', 'pv', 19, 8, 'Quem obtém sabedoria ama-se a si mesmo; quem acalenta o entendimento prospera.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16935, 'nvi', 'Provérbios', 'pv', 19, 9, 'A testemunha falsa não ficará sem castigo, e aquele que despeja mentiras perecerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16936, 'nvi', 'Provérbios', 'pv', 19, 10, 'Não fica bem o tolo viver no luxo; quanto pior é o servo dominar príncipes!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16937, 'nvi', 'Provérbios', 'pv', 19, 11, 'A sabedoria do homem lhe dá paciência; sua glória é ignorar as ofensas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16938, 'nvi', 'Provérbios', 'pv', 19, 12, 'A ira do rei é como o rugido do leão, mas a sua bondade é como o orvalho sobre a relva.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16939, 'nvi', 'Provérbios', 'pv', 19, 13, 'O filho tolo é a ruína de seu pai, e a esposa briguenta é como uma goteira constante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16940, 'nvi', 'Provérbios', 'pv', 19, 14, 'Casas e riquezas herdam-se dos pais, mas a esposa prudente vem do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16941, 'nvi', 'Provérbios', 'pv', 19, 15, 'A preguiça leva ao sono profundo, e o preguiçoso passa fome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16942, 'nvi', 'Provérbios', 'pv', 19, 16, 'Quem obedece aos mandamentos preserva a sua vida, mas quem despreza os seus caminhos morrerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16943, 'nvi', 'Provérbios', 'pv', 19, 17, 'Quem trata bem os pobres empresta ao Senhor, e ele o recompensará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16944, 'nvi', 'Provérbios', 'pv', 19, 18, 'Discipline seu filho, pois nisso há esperança; não queiras a morte dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16945, 'nvi', 'Provérbios', 'pv', 19, 19, 'O homem de gênio difícil precisa do castigo; se você o poupar, terá que poupá-lo de novo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16946, 'nvi', 'Provérbios', 'pv', 19, 20, 'Ouça conselhos e aceite instruções, e acabará sendo sábio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16947, 'nvi', 'Provérbios', 'pv', 19, 21, 'Muitos são os planos no coração do homem, mas o que prevalece é o propósito do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16948, 'nvi', 'Provérbios', 'pv', 19, 22, 'O que se deseja ver num homem é amor perene; melhor é ser pobre do que mentiroso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16949, 'nvi', 'Provérbios', 'pv', 19, 23, 'O temor do Senhor conduz à vida: Quem o teme pode descansar em paz, livre de problemas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16950, 'nvi', 'Provérbios', 'pv', 19, 24, 'O preguiçoso põe a mão no prato, e não se dá ao trabalho de levá-la à boca!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16951, 'nvi', 'Provérbios', 'pv', 19, 25, 'Açoite o zombador, e os inexperientes aprenderão a prudência; repreenda o homem de discernimento, e ele obterá conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16952, 'nvi', 'Provérbios', 'pv', 19, 26, 'O filho que rouba o pai e expulsa a mãe é causador de vergonha e desonra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16953, 'nvi', 'Provérbios', 'pv', 19, 27, 'Se você parar de ouvir a instrução, meu filho, irá afastar-se das palavras que dão conhecimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16954, 'nvi', 'Provérbios', 'pv', 19, 28, 'A testemunha corrupta zomba da justiça, e a boca dos ímpios tem fome de iniqüidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16955, 'nvi', 'Provérbios', 'pv', 19, 29, 'Os castigos estão preparados para os zombadores, e os açoites para as costas dos tolos.');
