-- Inserções para Provérbios 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16542, 'nvi', 'Provérbios', 'pv', 6, 1, 'Meu filho, se você serviu de fiador do seu próximo, se, com um aperto de mãos, empenhou-se por um estranho');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16543, 'nvi', 'Provérbios', 'pv', 6, 2, 'e caiu na armadilha das palavras que você mesmo disse, está prisioneiro do que falou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16544, 'nvi', 'Provérbios', 'pv', 6, 3, 'Então, meu filho, uma vez que você caiu nas mãos do seu próximo, vá e humilhe-se; insista, incomode o seu próximo!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16545, 'nvi', 'Provérbios', 'pv', 6, 4, 'Não se entregue ao sono, não procure descansar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16546, 'nvi', 'Provérbios', 'pv', 6, 5, 'Livre-se como a gazela se livra do caçador, como a ave do laço que a pode prender.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16547, 'nvi', 'Provérbios', 'pv', 6, 6, 'Observe a formiga, preguiçoso, reflita nos caminhos dela e seja sábio!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16548, 'nvi', 'Provérbios', 'pv', 6, 7, 'Ela não tem nem chefe, nem supervisor, nem governante,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16549, 'nvi', 'Provérbios', 'pv', 6, 8, 'e ainda assim armazena as suas provisões no verão e na época da colheita ajunta o seu alimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16550, 'nvi', 'Provérbios', 'pv', 6, 9, 'Até quando você vai ficar deitado, preguiçoso? Quando se levantará de seu sono?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16551, 'nvi', 'Provérbios', 'pv', 6, 10, 'Tirando uma soneca, cochilando um pouco, cruzando um pouco os braços para descansar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16552, 'nvi', 'Provérbios', 'pv', 6, 11, 'a sua pobreza o surpreenderá como um assaltante, e a sua necessidade lhe virá como um homem armado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16553, 'nvi', 'Provérbios', 'pv', 6, 12, 'O perverso não tem caráter. Anda de um lado para o outro dizendo coisas maldosas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16554, 'nvi', 'Provérbios', 'pv', 6, 13, 'pisca o olho, arrasta os pés e faz sinais com os dedos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16555, 'nvi', 'Provérbios', 'pv', 6, 14, 'tem no coração o propósito de enganar; planeja sempre o mal e semeia discórdia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16556, 'nvi', 'Provérbios', 'pv', 6, 15, 'Por isso a desgraça se abaterá repentinamente sobre ele; de um golpe será destruído, irremediavelmente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16557, 'nvi', 'Provérbios', 'pv', 6, 16, 'Há seis coisas que o Senhor odeia, sete coisas que ele detesta:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16558, 'nvi', 'Provérbios', 'pv', 6, 17, 'olhos altivos, língua mentirosa, mãos que derramam sangue inocente,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16559, 'nvi', 'Provérbios', 'pv', 6, 18, 'coração que traça planos perversos, pés que se apressam para fazer o mal,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16560, 'nvi', 'Provérbios', 'pv', 6, 19, 'a testemunha falsa que espalha mentiras e aquele que provoca discórdia entre irmãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16561, 'nvi', 'Provérbios', 'pv', 6, 20, 'Meu filho, obedeça aos mandamentos de seu pai e não abandone o ensino de sua mãe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16562, 'nvi', 'Provérbios', 'pv', 6, 21, 'Amarre-os sempre junto ao coração; ate-os ao redor do pescoço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16563, 'nvi', 'Provérbios', 'pv', 6, 22, 'Quando você andar, eles o guiarão; quando dormir, o estarão protegendo; quando acordar, falarão com você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16564, 'nvi', 'Provérbios', 'pv', 6, 23, 'Pois o mandamento é lâmpada, a instrução é luz, e as advertências da disciplina são o caminho que conduz à vida,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16565, 'nvi', 'Provérbios', 'pv', 6, 24, 'eles o protegerão da mulher imoral, e dos falsos elogios da mulher leviana.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16566, 'nvi', 'Provérbios', 'pv', 6, 25, 'Não cobice em seu coração a sua beleza nem se deixe seduzir por seus olhares,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16567, 'nvi', 'Provérbios', 'pv', 6, 26, 'pois o preço de uma prostituta é um pedaço de pão, mas a adúltera sai à caça de vidas preciosas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16568, 'nvi', 'Provérbios', 'pv', 6, 27, 'Pode alguém colocar fogo no peito sem queimar a roupa?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16569, 'nvi', 'Provérbios', 'pv', 6, 28, 'Pode alguém andar sobre brasas sem queimar os pés?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16570, 'nvi', 'Provérbios', 'pv', 6, 29, 'Assim acontece com quem se deita com mulher alheia; ninguém que a toque ficará sem castigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16571, 'nvi', 'Provérbios', 'pv', 6, 30, 'O ladrão não é desprezado se, faminto, rouba para matar a fome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16572, 'nvi', 'Provérbios', 'pv', 6, 31, 'Contudo, se for pego, deverá pagar sete vezes o que roubou, embora isso lhe custe tudo o que tem em casa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16573, 'nvi', 'Provérbios', 'pv', 6, 32, 'Mas o homem que comete adultério não tem juízo; todo aquele que assim procede a si mesmo se destrói.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16574, 'nvi', 'Provérbios', 'pv', 6, 33, 'Sofrerá ferimentos e vergonha, e a sua humilhação jamais se apagará,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16575, 'nvi', 'Provérbios', 'pv', 6, 34, 'pois o ciúme desperta a fúria do marido, que não terá misericórdia quando se vingar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16576, 'nvi', 'Provérbios', 'pv', 6, 35, 'Não aceitará nenhuma compensação; os melhores presentes não o acalmarão.');
