-- Inserções para Provérbios 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16457, 'nvi', 'Provérbios', 'pv', 3, 1, 'Meu filho, não se esqueça da minha lei, mas guarde no coração os meus mandamentos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16458, 'nvi', 'Provérbios', 'pv', 3, 2, 'pois eles prolongarão a sua vida por muitos anos e lhe darão prosperidade e paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16459, 'nvi', 'Provérbios', 'pv', 3, 3, 'Que o amor e a fidelidade jamais o abandonem; prenda-os ao redor do seu pescoço, escreva-os na tábua do seu coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16460, 'nvi', 'Provérbios', 'pv', 3, 4, 'Então você terá o favor de Deus e dos homens, e boa reputação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16461, 'nvi', 'Provérbios', 'pv', 3, 5, 'Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16462, 'nvi', 'Provérbios', 'pv', 3, 6, 'reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16463, 'nvi', 'Provérbios', 'pv', 3, 7, 'Não seja sábio aos seus próprios olhos; tema ao Senhor e evite o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16464, 'nvi', 'Provérbios', 'pv', 3, 8, 'Isso lhe dará saúde ao corpo e vigor aos ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16465, 'nvi', 'Provérbios', 'pv', 3, 9, 'Honre o Senhor com todos os seus recursos e com os primeiros frutos de todas as suas plantações;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16466, 'nvi', 'Provérbios', 'pv', 3, 10, 'os seus celeiros ficarão plenamente cheios, e os seus barris transbordarão de vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16467, 'nvi', 'Provérbios', 'pv', 3, 11, 'Meu filho, não despreze a disciplina do Senhor nem se magoe com a sua repreensão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16468, 'nvi', 'Provérbios', 'pv', 3, 12, 'pois o Senhor disciplina a quem ama, assim como o pai faz ao filho de quem deseja o bem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16469, 'nvi', 'Provérbios', 'pv', 3, 13, 'Como é feliz o homem que acha a sabedoria, o homem que obtém entendimento,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16470, 'nvi', 'Provérbios', 'pv', 3, 14, 'pois a sabedoria é mais proveitosa do que a prata e rende mais do que o ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16471, 'nvi', 'Provérbios', 'pv', 3, 15, 'É mais preciosa do que rubis; nada do que você possa desejar se compara a ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16472, 'nvi', 'Provérbios', 'pv', 3, 16, 'Na mão direita, a sabedoria lhe garante vida longa; na mão esquerda, riquezas e honra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16473, 'nvi', 'Provérbios', 'pv', 3, 17, 'Os caminhos da sabedoria são caminhos agradáveis, e todas as suas veredas são paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16474, 'nvi', 'Provérbios', 'pv', 3, 18, 'A sabedoria é árvore que dá vida a quem a abraça; quem a ela se apega será abençoado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16475, 'nvi', 'Provérbios', 'pv', 3, 19, 'Por sua sabedoria o Senhor lançou os alicerces da terra, por seu entendimento fixou no lugar os céus;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16476, 'nvi', 'Provérbios', 'pv', 3, 20, 'por seu conhecimento as fontes profundas se rompem, e as nuvens gotejam o orvalho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16477, 'nvi', 'Provérbios', 'pv', 3, 21, 'Meu filho, guarde consigo a sensatez e o equilíbrio, nunca os perca de vista;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16478, 'nvi', 'Provérbios', 'pv', 3, 22, 'trarão vida a você e serão um enfeite para o seu pescoço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16479, 'nvi', 'Provérbios', 'pv', 3, 23, 'Então você seguirá o seu caminho em segurança, e não tropeçará;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16480, 'nvi', 'Provérbios', 'pv', 3, 24, 'quando se deitar, não terá medo, e o seu sono será tranqüilo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16481, 'nvi', 'Provérbios', 'pv', 3, 25, 'Não terá medo da calamidade repentina nem da ruína que atinge os ímpios,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16482, 'nvi', 'Provérbios', 'pv', 3, 26, 'pois o Senhor será a sua segurança e o impedirá de cair em armadilha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16483, 'nvi', 'Provérbios', 'pv', 3, 27, 'Quanto lhe for possível, não deixe de fazer o bem a quem dele precisa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16484, 'nvi', 'Provérbios', 'pv', 3, 28, 'Não diga ao seu próximo: "Volte amanhã, e eu lhe darei algo", se pode ajudá-lo hoje.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16485, 'nvi', 'Provérbios', 'pv', 3, 29, 'Não planeje o mal contra o seu próximo, que confiantemente mora perto de você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16486, 'nvi', 'Provérbios', 'pv', 3, 30, 'Não acuse alguém sem motivo, se ele não lhe fez nenhum mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16487, 'nvi', 'Provérbios', 'pv', 3, 31, 'Não tenha inveja de quem é violento nem adote nenhum dos seus procedimentos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16488, 'nvi', 'Provérbios', 'pv', 3, 32, 'pois o Senhor detesta o perverso, mas o justo é seu grande amigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16489, 'nvi', 'Provérbios', 'pv', 3, 33, 'A maldição do Senhor está sobre a casa dos ímpios, mas ele abençoa o lar dos justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16490, 'nvi', 'Provérbios', 'pv', 3, 34, 'Ele zomba dos zombadores, mas concede graça aos humildes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16491, 'nvi', 'Provérbios', 'pv', 3, 35, 'A honra é herança dos sábios, mas o Senhor expõe os tolos ao ridículo.');
