-- Inserções para Provérbios 29
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17226, 'nvi', 'Provérbios', 'pv', 29, 1, 'Quem insiste no erro depois de muita repreensão, será destruído, sem aviso e irremediavelmente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17227, 'nvi', 'Provérbios', 'pv', 29, 2, 'Quando os justos florescem, o povo se alegra; quando os ímpios governam, o povo geme.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17228, 'nvi', 'Provérbios', 'pv', 29, 3, 'O homem que ama a sabedoria dá alegria a seu pai, mas quem anda com prostitutas dá fim à sua fortuna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17229, 'nvi', 'Provérbios', 'pv', 29, 4, 'O rei que exerce a justiça dá estabilidade ao país, mas o que gosta de subornos o leva à ruína.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17230, 'nvi', 'Provérbios', 'pv', 29, 5, 'Quem adula seu próximo está armando uma rede para os pés dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17231, 'nvi', 'Provérbios', 'pv', 29, 6, 'O pecado do homem mau o apanha na sua própria armadilha, mas o justo pode cantar e alegrar-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17232, 'nvi', 'Provérbios', 'pv', 29, 7, 'Os justos levam em conta os direitos dos pobres, mas os ímpios nem se importam com isso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17233, 'nvi', 'Provérbios', 'pv', 29, 8, 'Os zombadores agitam a cidade, mas os sábios a apaziguam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17234, 'nvi', 'Provérbios', 'pv', 29, 9, 'Se o sábio for ao tribunal contra o insensato, não haverá paz, pois o insensato se enfurecerá e zombará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17235, 'nvi', 'Provérbios', 'pv', 29, 10, 'Os violentos odeiam os honestos e procuram matar o homem íntegro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17236, 'nvi', 'Provérbios', 'pv', 29, 11, 'O tolo dá vazão à sua ira, mas o sábio domina-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17237, 'nvi', 'Provérbios', 'pv', 29, 12, 'Para o governante que dá ouvidos a mentiras, todos os seus oficiais são ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17238, 'nvi', 'Provérbios', 'pv', 29, 13, 'O pobre e o opressor têm algo em comum: O Senhor dá vista a ambos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17239, 'nvi', 'Provérbios', 'pv', 29, 14, 'Se o rei julga os pobres com justiça, seu trono estará sempre seguro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17240, 'nvi', 'Provérbios', 'pv', 29, 15, 'A vara da correção dá sabedoria, mas a criança entregue a si mesma envergonha a sua mãe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17241, 'nvi', 'Provérbios', 'pv', 29, 16, 'Quando os ímpios prosperam, prospera o pecado, mas os justos verão a queda deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17242, 'nvi', 'Provérbios', 'pv', 29, 17, 'Discipline seu filho, e este lhe dará paz; trará grande prazer à sua alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17243, 'nvi', 'Provérbios', 'pv', 29, 18, 'Onde não há revelação divina, o povo se desvia; mas como é feliz quem obedece à lei!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17244, 'nvi', 'Provérbios', 'pv', 29, 19, 'Meras palavras não bastam para corrigir o escravo; mesmo que entenda, não reagirá bem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17245, 'nvi', 'Provérbios', 'pv', 29, 20, 'Você já viu alguém que se precipita no falar? Há mais esperança para o insensato do que para ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17246, 'nvi', 'Provérbios', 'pv', 29, 21, 'Se alguém mima seu escravo desde jovem, no fim terá tristezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17247, 'nvi', 'Provérbios', 'pv', 29, 22, 'O homem irado provoca brigas, e o de gênio violento comete muitos pecados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17248, 'nvi', 'Provérbios', 'pv', 29, 23, 'O orgulho do homem o humilha, mas o de espírito humilde obtém honra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17249, 'nvi', 'Provérbios', 'pv', 29, 24, 'O cúmplice do ladrão odeia a si mesmo; posto sob juramento, não ousa testemunhar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17250, 'nvi', 'Provérbios', 'pv', 29, 25, 'Quem teme ao homem cai em armadilhas, mas quem confia no Senhor está seguro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17251, 'nvi', 'Provérbios', 'pv', 29, 26, 'Muitos desejam os favores do governante, mas é do Senhor que procede a justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17252, 'nvi', 'Provérbios', 'pv', 29, 27, 'Os justos detestam os desonestos, já os ímpios detestam os íntegros.');
