-- Inserções para Provérbios 16
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16842, 'nvi', 'Provérbios', 'pv', 16, 1, 'Ao homem pertencem os planos do coração, mas do Senhor vem a resposta da língua.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16843, 'nvi', 'Provérbios', 'pv', 16, 2, 'Todos os caminhos do homem lhe parecem puros, mas o Senhor avalia o espírito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16844, 'nvi', 'Provérbios', 'pv', 16, 3, 'Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16845, 'nvi', 'Provérbios', 'pv', 16, 4, 'O Senhor faz tudo com um propósito; até os ímpios para o dia do castigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16846, 'nvi', 'Provérbios', 'pv', 16, 5, 'O Senhor detesta os orgulhosos de coração. Sem dúvida serão punidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16847, 'nvi', 'Provérbios', 'pv', 16, 6, 'Com amor e fidelidade se faz expiação pelo pecado; com o temor do Senhor o homem evita o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16848, 'nvi', 'Provérbios', 'pv', 16, 7, 'Quando os caminhos de um homem são agradáveis ao Senhor, ele faz que até os seus inimigos vivam em paz com ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16849, 'nvi', 'Provérbios', 'pv', 16, 8, 'É melhor ter pouco com retidão do que muito com injustiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16850, 'nvi', 'Provérbios', 'pv', 16, 9, 'Em seu coração o homem planeja o seu caminho, mas o Senhor determina os seus passos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16851, 'nvi', 'Provérbios', 'pv', 16, 10, 'Os lábios do rei falam com grande autoridade; sua boca não deve trair a justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16852, 'nvi', 'Provérbios', 'pv', 16, 11, 'Balanças e pesos honestos vêm do Senhor; todos os pesos da bolsa são feitos por ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16853, 'nvi', 'Provérbios', 'pv', 16, 12, 'Os reis detestam a prática da maldade, porquanto o trono se firma pela justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16854, 'nvi', 'Provérbios', 'pv', 16, 13, 'O rei se agrada dos lábios honestos; e dá valor ao homem que fala a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16855, 'nvi', 'Provérbios', 'pv', 16, 14, 'A ira do rei é um mensageiro da morte, mas o homem sábio a acalmará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16856, 'nvi', 'Provérbios', 'pv', 16, 15, 'Alegria no rosto do rei é sinal de vida; seu favor é como nuvem de chuva na primavera.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16857, 'nvi', 'Provérbios', 'pv', 16, 16, 'É melhor obter sabedoria do que ouro! É melhor obter entendimento do que prata!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16858, 'nvi', 'Provérbios', 'pv', 16, 17, 'A vereda do justo evita o mal; quem guarda o seu caminho preserva a sua vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16859, 'nvi', 'Provérbios', 'pv', 16, 18, 'O orgulho vem antes da destruição; o espírito altivo, antes da queda.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16860, 'nvi', 'Provérbios', 'pv', 16, 19, 'Melhor é ter espírito humilde entre os oprimidos do que partilhar despojos com os orgulhosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16861, 'nvi', 'Provérbios', 'pv', 16, 20, 'Quem examina cada questão com cuidado, prospera, e feliz é aquele que confia no Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16862, 'nvi', 'Provérbios', 'pv', 16, 21, 'O sábio de coração é considerado prudente; quem fala com equilíbrio promove a instrução.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16863, 'nvi', 'Provérbios', 'pv', 16, 22, 'O entendimento é fonte de vida para aqueles que o têm, mas a insensatez traz castigo aos insensatos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16864, 'nvi', 'Provérbios', 'pv', 16, 23, 'O coração do sábio ensina a sua boca, e os seus lábios promovem a instrução.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16865, 'nvi', 'Provérbios', 'pv', 16, 24, 'As palavras agradáveis são como um favo de mel, são doces para a alma e trazem cura para os ossos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16866, 'nvi', 'Provérbios', 'pv', 16, 25, 'Há caminho que parece reto ao homem, mas no final conduz à morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16867, 'nvi', 'Provérbios', 'pv', 16, 26, 'O apetite do trabalhador o obriga a trabalhar; a sua fome o impulsiona.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16868, 'nvi', 'Provérbios', 'pv', 16, 27, 'O homem sem caráter maquina o mal, suas palavras são um fogo devorador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16869, 'nvi', 'Provérbios', 'pv', 16, 28, 'O homem perverso provoca dissensão, e o que espalha boatos afasta bons amigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16870, 'nvi', 'Provérbios', 'pv', 16, 29, 'O violento recruta o seu próximo e o leva por um caminho ruim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16871, 'nvi', 'Provérbios', 'pv', 16, 30, 'Quem pisca os olhos planeja o mal; quem franze os lábios já o vai praticar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16872, 'nvi', 'Provérbios', 'pv', 16, 31, 'O cabelo grisalho é uma coroa de esplendor, e se obtém mediante uma vida justa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16873, 'nvi', 'Provérbios', 'pv', 16, 32, 'Melhor é o homem paciente do que o guerreiro, mais vale controlar o seu espírito do que conquistar uma cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16874, 'nvi', 'Provérbios', 'pv', 16, 33, 'A sorte é lançada no colo, mas a decisão vem do Senhor.');
