-- Inserções para Provérbios 31
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17286, 'nvi', 'Provérbios', 'pv', 31, 1, 'Ditados do rei Lemuel; uma exortação que sua mãe lhe fez:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17287, 'nvi', 'Provérbios', 'pv', 31, 2, '"Ó meu filho, filho do meu ventre, filho de meus votos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17288, 'nvi', 'Provérbios', 'pv', 31, 3, 'não gaste sua força com mulheres, seu vigor com aquelas que destroem reis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17289, 'nvi', 'Provérbios', 'pv', 31, 4, '"Não convém aos reis, ó Lemuel; não convém aos reis beber vinho, não convém aos governantes desejar bebida fermentada,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17290, 'nvi', 'Provérbios', 'pv', 31, 5, 'para não suceder que bebam e se esqueçam do que a lei determina, e deixem de fazer justiça aos oprimidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17291, 'nvi', 'Provérbios', 'pv', 31, 6, 'Dê bebida fermentada aos que estão prestes a morrer, vinho aos que estão angustiados;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17292, 'nvi', 'Provérbios', 'pv', 31, 7, 'para que bebam e se esqueçam da sua pobreza, e não mais se lembrem da sua infelicidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17293, 'nvi', 'Provérbios', 'pv', 31, 8, '"Erga a voz em favor dos que não podem defender-se, seja o defensor de todos os desamparados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17294, 'nvi', 'Provérbios', 'pv', 31, 9, 'Erga a voz e julgue com justiça; defenda os direitos dos pobres e dos necessitados".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17295, 'nvi', 'Provérbios', 'pv', 31, 10, 'Uma esposa exemplar; feliz quem a encontrar! É muito mais valiosa que os rubis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17296, 'nvi', 'Provérbios', 'pv', 31, 11, 'Seu marido tem plena confiança nela e nunca lhe falta coisa alguma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17297, 'nvi', 'Provérbios', 'pv', 31, 12, 'Ela só lhe faz o bem, e nunca o mal, todos os dias da sua vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17298, 'nvi', 'Provérbios', 'pv', 31, 13, 'Escolhe a lã e o linho e com prazer trabalha com as mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17299, 'nvi', 'Provérbios', 'pv', 31, 14, 'Como os navios mercantes, ela traz de longe as suas provisões.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17300, 'nvi', 'Provérbios', 'pv', 31, 15, 'Antes de clarear o dia ela se levanta, prepara comida para todos os de casa, e dá tarefas as suas servas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17301, 'nvi', 'Provérbios', 'pv', 31, 16, 'Ela avalia um campo e o compra; com o que ganha planta uma vinha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17302, 'nvi', 'Provérbios', 'pv', 31, 17, 'Entrega-se com vontade ao seu trabalho; seus braços são fortes e vigorosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17303, 'nvi', 'Provérbios', 'pv', 31, 18, 'Administra bem o seu comércio lucrativo, e a sua lâmpada fica acesa durante a noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17304, 'nvi', 'Provérbios', 'pv', 31, 19, 'Nas mãos segura o fuso e com os dedos pega a roca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17305, 'nvi', 'Provérbios', 'pv', 31, 20, 'Acolhe os necessitados e estende as mãos aos pobres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17306, 'nvi', 'Provérbios', 'pv', 31, 21, 'Não receia a neve por seus familiares, pois todos eles vestem agasalhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17307, 'nvi', 'Provérbios', 'pv', 31, 22, 'Faz cobertas para a sua cama; veste-se de linho fino e de púrpura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17308, 'nvi', 'Provérbios', 'pv', 31, 23, 'Seu marido é respeitado na porta da cidade, onde toma assento entre as autoridades da sua terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17309, 'nvi', 'Provérbios', 'pv', 31, 24, 'Ela faz vestes de linho e as vende, e fornece cintos aos comerciantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17310, 'nvi', 'Provérbios', 'pv', 31, 25, 'Reveste-se de força e dignidade; sorri diante do futuro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17311, 'nvi', 'Provérbios', 'pv', 31, 26, 'Fala com sabedoria e ensina com amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17312, 'nvi', 'Provérbios', 'pv', 31, 27, 'Cuida dos negócios de sua casa e não dá lugar à preguiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17313, 'nvi', 'Provérbios', 'pv', 31, 28, 'Seus filhos se levantam e a elogiam; seu marido também a elogia, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17314, 'nvi', 'Provérbios', 'pv', 31, 29, '"Muitas mulheres são exemplares, mas você a todas supera".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17315, 'nvi', 'Provérbios', 'pv', 31, 30, 'A beleza é enganosa, e a formosura é passageira; mas a mulher que teme ao Senhor será elogiada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (17316, 'nvi', 'Provérbios', 'pv', 31, 31, 'Que ela receba a recompensa merecida, e as suas obras sejam elogiadas à porta da cidade.');
