-- Inserções para Provérbios 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16577, 'nvi', 'Provérbios', 'pv', 7, 1, 'Meu filho, obedeça às minhas palavras e no íntimo guarde os meus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16578, 'nvi', 'Provérbios', 'pv', 7, 2, 'Obedeça aos meus mandamentos, e você terá vida; guarde os meus ensinos como a pupila dos seus olhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16579, 'nvi', 'Provérbios', 'pv', 7, 3, 'Amarre-os aos dedos; escreva-os na tábua do seu coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16580, 'nvi', 'Provérbios', 'pv', 7, 4, 'Diga à sabedoria: "Você é minha irmã", e chame ao entendimento seu parente;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16581, 'nvi', 'Provérbios', 'pv', 7, 5, 'eles o manterão afastado da mulher imoral, da mulher leviana e suas palavras sedutoras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16582, 'nvi', 'Provérbios', 'pv', 7, 6, 'Da janela de minha casa olhei através da grade');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16583, 'nvi', 'Provérbios', 'pv', 7, 7, 'e vi entre os inexperientes, no meio dos jovens, um rapaz sem juízo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16584, 'nvi', 'Provérbios', 'pv', 7, 8, 'Ele vinha pela rua, próximo à esquina de certa mulher, andando em direção à casa dela');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16585, 'nvi', 'Provérbios', 'pv', 7, 9, 'Era crepúsculo, o entardecer do dia, chegavam as sombras da noite, crescia a escuridão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16586, 'nvi', 'Provérbios', 'pv', 7, 10, 'A mulher veio então ao seu encontro, vestida como prostituta, cheia de astúcia no coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16587, 'nvi', 'Provérbios', 'pv', 7, 11, '( Ela é espalhafatosa e provocadora, seus pés nunca param em casa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16588, 'nvi', 'Provérbios', 'pv', 7, 12, 'uma hora na rua, outra nas praças, em cada esquina fica à espreita. )');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16589, 'nvi', 'Provérbios', 'pv', 7, 13, 'Ela agarrou o rapaz, beijou-o e lhe disse descaradamente:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16590, 'nvi', 'Provérbios', 'pv', 7, 14, '"Tenho em casa a carne dos sacrifícios de comunhão, que hoje fiz para cumprir os meus votos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16591, 'nvi', 'Provérbios', 'pv', 7, 15, 'Por isso saí para encontrá-lo; vim à sua procura e o encontrei!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16592, 'nvi', 'Provérbios', 'pv', 7, 16, 'Estendi sobre o meu leito cobertas de linho fino do Egito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16593, 'nvi', 'Provérbios', 'pv', 7, 17, 'Perfumei a minha cama com mirra, aloés e canela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16594, 'nvi', 'Provérbios', 'pv', 7, 18, 'Venha, vamos embriagar-nos de carícias até o amanhecer; gozemos as delícias do amor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16595, 'nvi', 'Provérbios', 'pv', 7, 19, 'Pois o meu marido não está em casa; partiu para uma longa viagem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16596, 'nvi', 'Provérbios', 'pv', 7, 20, 'Levou uma bolsa cheia de prata e não voltará antes da lua cheia".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16597, 'nvi', 'Provérbios', 'pv', 7, 21, 'Com a sedução das palavras o persuadiu, e o atraiu com o dulçor dos lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16598, 'nvi', 'Provérbios', 'pv', 7, 22, 'Imediatamente ele a seguiu como o boi levado ao matadouro, ou como o cervo que vai cair no laço');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16599, 'nvi', 'Provérbios', 'pv', 7, 23, 'até que uma flecha lhe atravesse o fígado, ou como o pássaro que salta para dentro do alçapão, sem saber que isso lhe custará a vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16600, 'nvi', 'Provérbios', 'pv', 7, 24, 'Então, meu filho, ouça-me; dê atenção às minhas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16601, 'nvi', 'Provérbios', 'pv', 7, 25, 'Não deixe que o seu coração se volte para os caminhos dela, nem se perca em tais veredas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16602, 'nvi', 'Provérbios', 'pv', 7, 26, 'Muitas foram as suas vítimas; os que matou são uma grande multidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16603, 'nvi', 'Provérbios', 'pv', 7, 27, 'A casa dela é um caminho que desce para a sepultura, para as moradas da morte.');
