-- Inserções para Romanos 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28268, 'nvi', 'Romanos', 'rm', 13, 1, 'Todos devem sujeitar-se às autoridades governamentais, pois não há autoridade que não venha de Deus; as autoridades que existem foram por ele estabelecidas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28269, 'nvi', 'Romanos', 'rm', 13, 2, 'Portanto, aquele que se rebela contra a autoridade está se colocando contra o que Deus instituiu, e aqueles que assim procedem trazem condenação sobre si mesmos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28270, 'nvi', 'Romanos', 'rm', 13, 3, 'Pois os governantes não devem ser temidos, a não ser pelos que praticam o mal. Você quer viver livre do medo da autoridade? Pratique o bem, e ela o enaltecerá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28271, 'nvi', 'Romanos', 'rm', 13, 4, 'Pois é serva de Deus para o seu bem. Mas se você praticar o mal, tenha medo, pois ela não porta a espada sem motivo. É serva de Deus, agente da justiça para punir quem pratica o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28272, 'nvi', 'Romanos', 'rm', 13, 5, 'Portanto, é necessário que sejamos submissos às autoridades, não apenas por causa da possibilidade de uma punição, mas também por questão de consciência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28273, 'nvi', 'Romanos', 'rm', 13, 6, 'É por isso também que vocês pagam imposto, pois as autoridades estão a serviço de Deus, sempre dedicadas a esse trabalho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28274, 'nvi', 'Romanos', 'rm', 13, 7, 'Dêem a cada um o que lhe é devido: Se imposto, imposto; se tributo, tributo; se temor, temor; se honra, honra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28275, 'nvi', 'Romanos', 'rm', 13, 8, 'Não devam nada a ninguém, a não ser o amor de uns pelos outros, pois aquele que ama seu próximo tem cumprido a lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28276, 'nvi', 'Romanos', 'rm', 13, 9, 'Pois estes mandamentos: "Não adulterarás", "não matarás", "não furtarás", "não cobiçarás", e qualquer outro mandamento, todos se resumem neste preceito: "Ame o seu próximo como a si mesmo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28277, 'nvi', 'Romanos', 'rm', 13, 10, 'O amor não pratica o mal contra o próximo. Portanto, o amor é o cumprimento da lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28278, 'nvi', 'Romanos', 'rm', 13, 11, 'Façam isso, compreendendo o tempo em que vivemos. Chegou a hora de vocês despertarem do sono, porque agora a nossa salvação está mais próxima do que quando cremos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28279, 'nvi', 'Romanos', 'rm', 13, 12, 'A noite está quase acabando; o dia logo vem. Portanto, deixemos de lado as obras das trevas e vistamo-nos a armadura da luz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28280, 'nvi', 'Romanos', 'rm', 13, 13, 'Comportemo-nos com decência, como quem age à luz do dia, não em orgias e bebedeiras, não em imoralidade sexual e depravação, não em desavença e inveja.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (28281, 'nvi', 'Romanos', 'rm', 13, 14, 'Pelo contrário, revistam-se do Senhor Jesus Cristo, e não fiquem premeditando como satisfazer os desejos da carne.');
