-- Inserções para Rute 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7173, 'nvi', 'Rute', 'rt', 3, 1, 'Certo dia, Noemi, sua sogra, lhe disse: "Minha filha, tenho que procurar um lar seguro, para sua felicidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7174, 'nvi', 'Rute', 'rt', 3, 2, 'Boaz, aquele com cujas servas você esteve, é nosso parente próximo. Esta noite ele estará limpando cevada na eira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7175, 'nvi', 'Rute', 'rt', 3, 3, 'Lave-se, perfume-se, vista sua melhor roupa e desça para a eira. Mas não deixe que ele perceba você até que tenha comido e bebido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7176, 'nvi', 'Rute', 'rt', 3, 4, 'Quando ele for dormir, note bem o lugar em que ele se deitar. Então vá, descubra os pés dele e deite-se. Ele lhe dirá o que fazer".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7177, 'nvi', 'Rute', 'rt', 3, 5, 'Respondeu Rute: "Farei tudo o que você está me dizendo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7178, 'nvi', 'Rute', 'rt', 3, 6, 'Então ela desceu para a eira e fez tudo o que a sua sogra lhe tinha recomendado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7179, 'nvi', 'Rute', 'rt', 3, 7, 'Quando Boaz terminou de comer e beber, ficou alegre e foi deitar-se perto do monte de grãos. Rute aproximou-se sem ser notada, descobriu os pés dele, e deitou-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7180, 'nvi', 'Rute', 'rt', 3, 8, 'No meio da noite, o homem acordou de repente. Ele se virou e assustou-se ao ver uma mulher deitada a seus pés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7181, 'nvi', 'Rute', 'rt', 3, 9, '"Quem é você? ", perguntou ele. "Sou sua serva Rute", disse ela. "Estenda a sua capa sobre a sua serva, pois o senhor é resgatador. "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7182, 'nvi', 'Rute', 'rt', 3, 10, 'Boaz lhe respondeu: "O Senhor a abençoe, minha filha! Este seu gesto de bondade é ainda maior do que o primeiro, pois você poderia ter ido atrás dos mais jovens, ricos ou pobres!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7183, 'nvi', 'Rute', 'rt', 3, 11, 'Agora, minha filha, não tenha medo; farei por você tudo o que me pedir. Todos os meus concidadãos sabem que você é mulher virtuosa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7184, 'nvi', 'Rute', 'rt', 3, 12, 'É verdade que sou resgatador, mas há um outro que é parente mais próximo do que eu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7185, 'nvi', 'Rute', 'rt', 3, 13, 'Passe a noite aqui. De manhã veremos: se ele quiser resgatá-la, muito bem, que resgate. Se não quiser, juro pelo nome do Senhor que eu a resgatarei. Deite-se aqui até de manhã".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7186, 'nvi', 'Rute', 'rt', 3, 14, 'Ela ficou deitada aos pés dele até de manhã, mas levantou-se antes de clarear a ponto de alguém poder ser reconhecido. Boaz pensou: "Ninguém deve saber que esta mulher esteve na eira".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7187, 'nvi', 'Rute', 'rt', 3, 15, 'Por isso disse: "Traga-me o manto que você está usando e segure-o". Ela o segurou, e o homem despejou nele seis medidas de cevada e o pôs sobre os ombros dela. Depois ele voltou para a cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7188, 'nvi', 'Rute', 'rt', 3, 16, 'Quando Rute voltou à sua sogra, esta lhe perguntou: "Como foi, minha filha? " Rute lhe contou tudo o que Boaz lhe tinha feito,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7189, 'nvi', 'Rute', 'rt', 3, 17, 'e acrescentou: "Ele me deu estas seis medidas de cevada, dizendo: ‘Não volte para a sua sogra de mãos vazias’ ".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (7190, 'nvi', 'Rute', 'rt', 3, 18, 'Disse então Noemi: "Agora espere, minha filha, até saber o que acontecerá. Sem dúvida aquele homem não descansará enquanto não resolver esta questão hoje mesmo".');
