-- Inserções para Sofonias 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22789, 'nvi', 'Sofonias', 'sf', 1, 1, 'Palavra do Senhor que veio a Sofonias, filho de Cuchi, neto de Gedalias, bisneto de Amarias e trineto de Ezequias, durante o reinado de Josias, filho de Amom, rei de Judá:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22790, 'nvi', 'Sofonias', 'sf', 1, 2, '"Destruirei todas as coisas na face da terra"; palavra do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22791, 'nvi', 'Sofonias', 'sf', 1, 3, '"Destruirei tanto os homens quanto os animais; destruirei as aves do céu e os peixes do mar, os que causam tropeço junto com os ímpios. Farei isso quando eu ceifar o homem da face da terra", declara o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22792, 'nvi', 'Sofonias', 'sf', 1, 4, '"Estenderei a mão contra Judá e contra todos os habitantes de Jerusalém. Eliminarei deste lugar o remanescente de Baal, os nomes dos oficiantes idólatras e dos sacerdotes,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22793, 'nvi', 'Sofonias', 'sf', 1, 5, 'aqueles que no alto dos terraços adoram o exército de estrelas, que se prostram jurando pelo Senhor, e também por Moloque;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22794, 'nvi', 'Sofonias', 'sf', 1, 6, 'aqueles que se desviam de seguir o Senhor; não o buscam nem o consultam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22795, 'nvi', 'Sofonias', 'sf', 1, 7, 'Calem-se diante do Soberano Senhor, pois o dia do Senhor está próximo. O Senhor preparou um sacrifício; consagrou os seus convidados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22796, 'nvi', 'Sofonias', 'sf', 1, 8, 'No dia do sacrifício do Senhor castigarei os líderes e os filhos do rei e todos os que estão vestidos com roupas estrangeiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22797, 'nvi', 'Sofonias', 'sf', 1, 9, 'Naquele dia castigarei todos os que evitam pisar na soleira dos ídolos, que enchem o templo de seus deuses com violência e engano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22798, 'nvi', 'Sofonias', 'sf', 1, 10, '"Naquele dia", declara o Senhor, "haverá gritos perto da porta dos Peixes, lamentos no novo distrito, e estrondos nas colinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22799, 'nvi', 'Sofonias', 'sf', 1, 11, 'Lamentem, vocês que moram na cidade baixa; todos os seus comerciantes serão completamente destruídos, todos os que negociam com prata serão arruinados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22800, 'nvi', 'Sofonias', 'sf', 1, 12, 'Nessa época vasculharei Jerusalém com lamparinas e castigarei os que são complacentes, que são como vinho envelhecido, deixado com os seus resíduos, que pensam: ‘O Senhor nada fará, nem bem nem mal’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22801, 'nvi', 'Sofonias', 'sf', 1, 13, 'A riqueza deles será saqueada, suas casas serão demolidas. Embora construam novas casas, nelas não morarão; plantarão vinhas, mas não beberão o vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22802, 'nvi', 'Sofonias', 'sf', 1, 14, '"O grande dia do Senhor está próximo; está próximo e logo vem. Ouçam! O dia do Senhor será amargo; até os guerreiros gritarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22803, 'nvi', 'Sofonias', 'sf', 1, 15, 'Aquele dia será um dia de ira, dia de aflição e angústia, dia de sofrimento e ruína, dia de trevas e escuridão, dia de nuvens e negridão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22804, 'nvi', 'Sofonias', 'sf', 1, 16, 'dia de toques de trombeta e gritos de guerra contra as cidades fortificadas e contra as torres elevadas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22805, 'nvi', 'Sofonias', 'sf', 1, 17, 'Trarei aflição aos homens; andarão como se fossem cegos, porque pecaram contra o Senhor. O sangue deles será derramado como poeira, e suas entranhas como lixo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22806, 'nvi', 'Sofonias', 'sf', 1, 18, 'Nem a sua prata nem o seu ouro poderão livrá-los no dia da ira do Senhor. No fogo do seu zelo o mundo inteiro será consumido, pois ele dará fim repentino a todos os que vivem na terra. "');
