-- Inserções para Salmos 55
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14734, 'nvi', 'Salmos', 'sl', 55, 1, 'Escuta a minha oração, ó Deus, não ignores a minha súplica;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14735, 'nvi', 'Salmos', 'sl', 55, 2, 'ouve-me e responde-me! Os meus pensamentos me perturbam, e estou atordoado');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14736, 'nvi', 'Salmos', 'sl', 55, 3, 'diante do barulho do inimigo, diante da gritaria dos ímpios; pois aumentam o meu sofrimento e, irados, mostram seu rancor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14737, 'nvi', 'Salmos', 'sl', 55, 4, 'O meu coração está acelerado; os pavores da morte me assaltam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14738, 'nvi', 'Salmos', 'sl', 55, 5, 'Temor e tremor me dominam; o medo tomou conta de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14739, 'nvi', 'Salmos', 'sl', 55, 6, 'Então eu disse: "Quem dera eu tivesse asas como a pomba; voaria até encontrar repouso!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14740, 'nvi', 'Salmos', 'sl', 55, 7, 'Sim, eu fugiria para bem longe, e no deserto eu teria o meu abrigo. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14741, 'nvi', 'Salmos', 'sl', 55, 8, 'Eu me apressaria em achar refúgio longe do vendaval e da tempestade".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14742, 'nvi', 'Salmos', 'sl', 55, 9, 'Destrói os ímpios, Senhor, confunde a língua deles, pois vejo violência e brigas na cidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14743, 'nvi', 'Salmos', 'sl', 55, 10, 'Dia e noite eles rondam por seus muros; nela permeiam o crime e a maldade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14744, 'nvi', 'Salmos', 'sl', 55, 11, 'A destruição impera na cidade; a opressão e a fraude jamais deixam suas ruas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14745, 'nvi', 'Salmos', 'sl', 55, 12, 'Se um inimigo me insultasse, eu poderia suportar; se um adversário se levantasse contra mim, eu poderia defender-me;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14746, 'nvi', 'Salmos', 'sl', 55, 13, 'mas logo você, meu colega, meu companheiro, meu amigo chegado,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14747, 'nvi', 'Salmos', 'sl', 55, 14, 'você, com quem eu partilhava agradável comunhão enquanto íamos com a multidão festiva para a casa de Deus!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14748, 'nvi', 'Salmos', 'sl', 55, 15, 'Que a morte apanhe os meus inimigos de surpresa! Desçam eles vivos para a sepultura, pois entre eles o mal acha guarida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14749, 'nvi', 'Salmos', 'sl', 55, 16, 'Eu, porém, clamo a Deus, e o Senhor me salvará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14750, 'nvi', 'Salmos', 'sl', 55, 17, 'À tarde, pela manhã e ao meio-dia choro angustiado, e ele ouve a minha voz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14751, 'nvi', 'Salmos', 'sl', 55, 18, 'Ele me guarda ileso na batalha, ainda que muitos estejam contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14752, 'nvi', 'Salmos', 'sl', 55, 19, 'Deus, que reina desde a eternidade, me ouvirá e os castigará. Pausa Pois jamais mudam sua conduta e não têm temor de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14753, 'nvi', 'Salmos', 'sl', 55, 20, 'Aquele homem se voltou contra os seus aliados, violando o seu acordo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14754, 'nvi', 'Salmos', 'sl', 55, 21, 'Macia como manteiga é a sua fala, mas a guerra está no seu coração; suas palavras são mais suaves que o óleo, mas são afiadas como punhais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14755, 'nvi', 'Salmos', 'sl', 55, 22, 'Entregue suas preocupações ao Senhor, e ele o susterá; jamais permitirá que o justo venha a cair.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14756, 'nvi', 'Salmos', 'sl', 55, 23, 'Mas tu, ó Deus, farás descer à cova da destruição aqueles assassinos e traidores, os quais não viverão a metade dos seus dias. Quanto a mim, porém, confio em ti.');
