-- Inserções para Salmos 89
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15328, 'nvi', 'Salmos', 'sl', 89, 1, 'Cantarei para sempre o amor do Senhor; com minha boca anunciarei a tua fidelidade por todas as gerações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15329, 'nvi', 'Salmos', 'sl', 89, 2, 'Sei que firme está o teu amor para sempre, e que firmaste nos céus a tua fidelidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15330, 'nvi', 'Salmos', 'sl', 89, 3, 'Tu disseste: "Fiz aliança com o meu escolhido, jurei ao meu servo Davi:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15331, 'nvi', 'Salmos', 'sl', 89, 4, 'Estabelecerei a tua linhagem para sempre e firmarei o teu trono por todas as gerações". Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15332, 'nvi', 'Salmos', 'sl', 89, 5, 'Os céus louvam as tuas maravilhas, Senhor, e a tua fidelidade na assembléia dos santos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15333, 'nvi', 'Salmos', 'sl', 89, 6, 'Pois, quem nos céus poderá comparar-se ao Senhor? Quem dentre os seres celestiais assemelha-se ao Senhor?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15334, 'nvi', 'Salmos', 'sl', 89, 7, 'Na assembléia dos santos Deus é temível, mais do que todos os que o rodeiam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15335, 'nvi', 'Salmos', 'sl', 89, 8, 'Ó Senhor, Deus dos Exércitos, quem é semelhante a ti? És poderoso, Senhor, envolto em tua fidelidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15336, 'nvi', 'Salmos', 'sl', 89, 9, 'Tu dominas o revolto mar; quando se agigantam as suas ondas, tu as acalmas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15337, 'nvi', 'Salmos', 'sl', 89, 10, 'Esmagaste e mataste o Monstro dos Mares; com teu braço forte dispersaste os teus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15338, 'nvi', 'Salmos', 'sl', 89, 11, 'Os céus são teus, e tua também é a terra; fundaste o mundo e tudo o que nele existe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15339, 'nvi', 'Salmos', 'sl', 89, 12, 'Tu criaste o Norte e o Sul; o Tabor e o Hermom cantam de alegria pelo teu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15340, 'nvi', 'Salmos', 'sl', 89, 13, 'O teu braço é poderoso; a tua mão é forte, exaltada é tua mão direita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15341, 'nvi', 'Salmos', 'sl', 89, 14, 'A retidão e a justiça são os alicerces do teu trono; o amor e a fidelidade vão à tua frente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15342, 'nvi', 'Salmos', 'sl', 89, 15, 'Como é feliz o povo que aprendeu a aclamar-te, Senhor, e que anda na luz da tua presença!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15343, 'nvi', 'Salmos', 'sl', 89, 16, 'Sem cessar exultam no teu nome, e alegram-se na tua retidão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15344, 'nvi', 'Salmos', 'sl', 89, 17, 'pois tu és a nossa glória e a nossa força, e pelo teu favor exaltas a nossa força.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15345, 'nvi', 'Salmos', 'sl', 89, 18, 'Sim, Senhor, tu és o nosso escudo, ó Santo de Israel, tu és o nosso rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15346, 'nvi', 'Salmos', 'sl', 89, 19, 'Numa visão falaste um dia, e aos teus fiéis disseste: "Cobri de forças um guerreiro, exaltei um homem escolhido dentre o povo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15347, 'nvi', 'Salmos', 'sl', 89, 20, 'Encontrei o meu servo Davi; ungi-o com o meu óleo sagrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15348, 'nvi', 'Salmos', 'sl', 89, 21, 'A minha mão o susterá, e o meu braço o fará forte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15349, 'nvi', 'Salmos', 'sl', 89, 22, 'Nenhum inimigo o sujeitará a tributos; nenhum injusto o oprimirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15350, 'nvi', 'Salmos', 'sl', 89, 23, 'Esmagarei diante dele os seus adversários e destruirei os seus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15351, 'nvi', 'Salmos', 'sl', 89, 24, 'A minha fidelidade e o meu amor o acompanharão, e pelo meu nome aumentará o seu poder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15352, 'nvi', 'Salmos', 'sl', 89, 25, 'A sua mão dominará até o mar, e a sua mão direita, até os rios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15353, 'nvi', 'Salmos', 'sl', 89, 26, 'Ele me dirá: ‘Tu és o meu Pai, o meu Deus, a Rocha que me salva’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15354, 'nvi', 'Salmos', 'sl', 89, 27, 'Também o nomearei meu primogênito, o mais exaltado dos reis da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15355, 'nvi', 'Salmos', 'sl', 89, 28, 'Manterei o meu amor por ele para sempre, e a minha aliança com ele jamais se quebrará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15356, 'nvi', 'Salmos', 'sl', 89, 29, 'Firmarei a sua linhagem para sempre, o seu trono durará enquanto existirem céus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15357, 'nvi', 'Salmos', 'sl', 89, 30, 'Se os seus filhos abandonarem a minha lei e não seguirem as minhas ordenanças,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15358, 'nvi', 'Salmos', 'sl', 89, 31, 'se violarem os meus decretos e deixarem de obedecer aos meus mandamentos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15359, 'nvi', 'Salmos', 'sl', 89, 32, 'com a vara castigarei o seu pecado, e a sua iniqüidade com açoites;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15360, 'nvi', 'Salmos', 'sl', 89, 33, 'mas não afastarei dele o meu amor; jamais desistirei da minha fidelidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15361, 'nvi', 'Salmos', 'sl', 89, 34, 'Não violarei a minha aliança nem modificarei as promessas dos meus lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15362, 'nvi', 'Salmos', 'sl', 89, 35, 'De uma vez para sempre jurei pela minha santidade, e não mentirei a Davi,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15363, 'nvi', 'Salmos', 'sl', 89, 36, 'que a sua linhagem permanecerá para sempre, e o seu trono durará como o sol;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15364, 'nvi', 'Salmos', 'sl', 89, 37, 'e será estabelecido para sempre como a lua, a fiel testemunha no céu". Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15365, 'nvi', 'Salmos', 'sl', 89, 38, 'Mas tu o rejeitaste, recusaste-o e te enfureceste com o teu ungido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15366, 'nvi', 'Salmos', 'sl', 89, 39, 'Revogaste a aliança com o teu servo e desonraste a sua coroa, lançando-a ao chão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15367, 'nvi', 'Salmos', 'sl', 89, 40, 'Derrubaste todos os seus muros e reduziste a ruínas as suas fortalezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15368, 'nvi', 'Salmos', 'sl', 89, 41, 'Todos os que passam o saqueiam; tornou-se motivo de zombaria para os seus vizinhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15369, 'nvi', 'Salmos', 'sl', 89, 42, 'Tu exaltaste a mão direita dos seus adversários e encheste de alegria todos os seus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15370, 'nvi', 'Salmos', 'sl', 89, 43, 'Tiraste o fio da sua espada e não o apoiaste na batalha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15371, 'nvi', 'Salmos', 'sl', 89, 44, 'Deste fim ao seu esplendor e atiraste ao chão o seu trono.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15372, 'nvi', 'Salmos', 'sl', 89, 45, 'Encurtaste os dias da sua juventude; com um manto de vergonha o cobriste. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15373, 'nvi', 'Salmos', 'sl', 89, 46, 'Até quando, Senhor? Para sempre te esconderás? Até quando a tua ira queimará como fogo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15374, 'nvi', 'Salmos', 'sl', 89, 47, 'Lembra-te de como é passageira a minha vida. Terás criado em vão todos os homens?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15375, 'nvi', 'Salmos', 'sl', 89, 48, 'Que homem pode viver e não ver a morte, ou livrar-se do poder da sepultura? Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15376, 'nvi', 'Salmos', 'sl', 89, 49, 'Ó Senhor, onde está o teu antigo amor, que com fidelidade juraste a Davi?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15377, 'nvi', 'Salmos', 'sl', 89, 50, 'Lembra-te, Senhor, das afrontas que o teu servo tem sofrido, das zombarias que no íntimo tenho que suportar de todos os povos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15378, 'nvi', 'Salmos', 'sl', 89, 51, 'das zombarias dos teus inimigos, Senhor, com que afrontam a cada passo o teu ungido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15379, 'nvi', 'Salmos', 'sl', 89, 52, 'Bendito seja o Senhor para sempre! Amém e amém.');
