-- Inserções para Salmos 33
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14368, 'nvi', 'Salmos', 'sl', 33, 1, 'Cantem de alegria ao Senhor, vocês que são justos; aos que são retos fica bem louvá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14369, 'nvi', 'Salmos', 'sl', 33, 2, 'Louvem o Senhor com harpa; ofereçam-lhe música com lira de dez cordas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14370, 'nvi', 'Salmos', 'sl', 33, 3, 'Cantem-lhe uma nova canção; toquem com habilidade ao aclamá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14371, 'nvi', 'Salmos', 'sl', 33, 4, 'Pois a palavra do Senhor é verdadeira; ele é fiel em tudo o que faz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14372, 'nvi', 'Salmos', 'sl', 33, 5, 'Ele ama a justiça e a retidão; a terra está cheia da bondade do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14373, 'nvi', 'Salmos', 'sl', 33, 6, 'Mediante a palavra do Senhor foram feitos os céus, e os corpos celestes, pelo sopro de sua boca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14374, 'nvi', 'Salmos', 'sl', 33, 7, 'Ele ajunta as águas do mar num só lugar; das profundezas faz reservatórios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14375, 'nvi', 'Salmos', 'sl', 33, 8, 'Toda a terra tema o Senhor; tremam diante dele todos os habitantes do mundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14376, 'nvi', 'Salmos', 'sl', 33, 9, 'Pois ele falou, e tudo se fez; ele ordenou, e tudo surgiu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14377, 'nvi', 'Salmos', 'sl', 33, 10, 'O Senhor desfaz os planos das nações e frustra os propósitos dos povos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14378, 'nvi', 'Salmos', 'sl', 33, 11, 'Mas os planos do Senhor permanecem para sempre, os propósitos do seu coração, por todas as gerações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14379, 'nvi', 'Salmos', 'sl', 33, 12, 'Como é feliz a nação que tem o Senhor como Deus, o povo que ele escolheu para lhe pertencer!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14380, 'nvi', 'Salmos', 'sl', 33, 13, 'Dos céus olha o Senhor e vê toda a humanidade;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14381, 'nvi', 'Salmos', 'sl', 33, 14, 'do seu trono ele observa todos os habitantes da terra;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14382, 'nvi', 'Salmos', 'sl', 33, 15, 'ele, que forma o coração de todos, que conhece tudo o que fazem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14383, 'nvi', 'Salmos', 'sl', 33, 16, 'Nenhum rei se salva pelo tamanho do seu exército; nenhum guerreiro escapa por sua grande força.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14384, 'nvi', 'Salmos', 'sl', 33, 17, 'O cavalo é vã esperança de vitória; apesar da sua grande força, é incapaz de salvar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14385, 'nvi', 'Salmos', 'sl', 33, 18, 'Mas o Senhor protege aqueles que o temem, e os que firmam a esperança no seu amor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14386, 'nvi', 'Salmos', 'sl', 33, 19, 'para livrá-los da morte e garantir-lhes vida, mesmo em tempos de fome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14387, 'nvi', 'Salmos', 'sl', 33, 20, 'Nossa esperança está no Senhor; ele é o nosso auxílio e a nossa proteção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14388, 'nvi', 'Salmos', 'sl', 33, 21, 'Nele se alegra o nosso coração, pois confiamos no seu santo nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14389, 'nvi', 'Salmos', 'sl', 33, 22, 'Esteja sobre nós o teu amor, Senhor, como está em ti a nossa esperança.');
