-- Inserções para Salmos 145
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16322, 'nvi', 'Salmos', 'sl', 145, 1, 'Eu te exaltarei, meu Deus e meu rei; bendirei o teu nome para todo o sempre!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16323, 'nvi', 'Salmos', 'sl', 145, 2, 'Todos os dias te bendirei e louvarei o teu nome para todo o sempre!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16324, 'nvi', 'Salmos', 'sl', 145, 3, 'Grande é o Senhor e digno de ser louvado; sua grandeza não tem limites.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16325, 'nvi', 'Salmos', 'sl', 145, 4, 'Uma geração contará à outra a grandiosidade dos teus feitos; eles anunciarão os teus atos poderosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16326, 'nvi', 'Salmos', 'sl', 145, 5, 'Proclamarão o glorioso esplendor da tua majestade, e meditarei nas maravilhas que fazes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16327, 'nvi', 'Salmos', 'sl', 145, 6, 'Anunciarão o poder dos teus feitos temíveis, e eu falarei das tuas grandes obras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16328, 'nvi', 'Salmos', 'sl', 145, 7, 'Comemorarão a tua imensa bondade e celebrarão a tua justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16329, 'nvi', 'Salmos', 'sl', 145, 8, 'O Senhor é misericordioso e compassivo, paciente e transbordante de amor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16330, 'nvi', 'Salmos', 'sl', 145, 9, 'O Senhor é bom para todos; a sua compaixão alcança todas as suas criaturas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16331, 'nvi', 'Salmos', 'sl', 145, 10, 'Rendam-te graças todas as tuas criaturas, Senhor; e os teus fiéis te bendigam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16332, 'nvi', 'Salmos', 'sl', 145, 11, 'Eles anunciarão a glória do teu reino e falarão do teu poder,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16333, 'nvi', 'Salmos', 'sl', 145, 12, 'para que todos saibam dos teus feitos poderosos e do glorioso esplendor do teu reino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16334, 'nvi', 'Salmos', 'sl', 145, 13, 'O teu reino é reino eterno, e o teu domínio permanece de geração em geração. O Senhor é fiel em todas as suas promessas e é bondoso em tudo o que faz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16335, 'nvi', 'Salmos', 'sl', 145, 14, 'O Senhor ampara todos os que caem e levanta todos os que estão prostrados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16336, 'nvi', 'Salmos', 'sl', 145, 15, 'Os olhos de todos estão voltados para ti, e tu lhes dás o alimento no devido tempo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16337, 'nvi', 'Salmos', 'sl', 145, 16, 'Abres a tua mão e satisfazes os desejos de todos os seres vivos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16338, 'nvi', 'Salmos', 'sl', 145, 17, 'O Senhor é justo em todos os seus caminhos e é bondoso em tudo o que faz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16339, 'nvi', 'Salmos', 'sl', 145, 18, 'O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16340, 'nvi', 'Salmos', 'sl', 145, 19, 'Realiza os desejos daqueles que o temem; ouve-os gritar por socorro e os salva.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16341, 'nvi', 'Salmos', 'sl', 145, 20, 'O Senhor cuida de todos os que o amam, mas a todos os ímpios destruirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16342, 'nvi', 'Salmos', 'sl', 145, 21, 'Com meus lábios louvarei ao Senhor. Que todo ser vivo bendiga o seu santo nome para todo o sempre!');
