-- Inserções para Salmos 102
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15523, 'nvi', 'Salmos', 'sl', 102, 1, 'Ouve a minha oração, Senhor! Chegue a ti o meu grito de socorro!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15524, 'nvi', 'Salmos', 'sl', 102, 2, 'Não escondas de mim o teu rosto, quando estou atribulado. Inclina para mim os teus ouvidos; quando eu clamar, responde-me depressa!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15525, 'nvi', 'Salmos', 'sl', 102, 3, 'Esvaem-se os meus dias como fumaça; meus ossos queimam como brasas vivas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15526, 'nvi', 'Salmos', 'sl', 102, 4, 'Como a relva ressequida está o meu coração; esqueço até de comer!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15527, 'nvi', 'Salmos', 'sl', 102, 5, 'De tanto gemer estou reduzido a pele e osso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15528, 'nvi', 'Salmos', 'sl', 102, 6, 'Sou como a coruja do deserto, como uma coruja entre as ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15529, 'nvi', 'Salmos', 'sl', 102, 7, 'Não consigo dormir; tornei-me como um pássaro solitário no telhado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15530, 'nvi', 'Salmos', 'sl', 102, 8, 'Os meus inimigos zombam de mim o tempo todo; os que me insultam usam o meu nome para lançar maldições.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15531, 'nvi', 'Salmos', 'sl', 102, 9, 'Cinzas são a minha comida, e com lágrimas misturo o que bebo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15532, 'nvi', 'Salmos', 'sl', 102, 10, 'por causa da tua indignação e da tua ira, pois me rejeitaste e me expulsaste para longe de ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15533, 'nvi', 'Salmos', 'sl', 102, 11, 'Meus dias são como sombras crescentes; sou como a relva que vai murchando.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15534, 'nvi', 'Salmos', 'sl', 102, 12, 'Tu, porém, Senhor, no trono reinarás para sempre; o teu nome será lembrado de geração em geração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15535, 'nvi', 'Salmos', 'sl', 102, 13, 'Tu te levantarás e terás misericórdia de Sião, pois é hora de lhe mostrares compaixão; o tempo certo é chegado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15536, 'nvi', 'Salmos', 'sl', 102, 14, 'Pois as suas pedras são amadas pelos teus servos, as suas ruínas os enchem de compaixão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15537, 'nvi', 'Salmos', 'sl', 102, 15, 'Então as nações temerão o nome do Senhor, e todos os reis da terra a sua glória.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15538, 'nvi', 'Salmos', 'sl', 102, 16, 'Porque o Senhor reconstruirá Sião e se manifestará na glória que ele tem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15539, 'nvi', 'Salmos', 'sl', 102, 17, 'Responderá à oração dos desamparados; as suas súplicas não desprezará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15540, 'nvi', 'Salmos', 'sl', 102, 18, 'Escreva-se isto para as futuras gerações, e um povo que ainda será criado louvará o Senhor, proclamando:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15541, 'nvi', 'Salmos', 'sl', 102, 19, '"Do seu santuário nas alturas o Senhor olhou; dos céus observou a terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15542, 'nvi', 'Salmos', 'sl', 102, 20, 'para ouvir os gemidos dos prisioneiros e libertar os condenados à morte".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15543, 'nvi', 'Salmos', 'sl', 102, 21, 'Assim o nome do Senhor será anunciado em Sião e o seu louvor, em Jerusalém,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15544, 'nvi', 'Salmos', 'sl', 102, 22, 'quando os povos e os reinos se reunirem para adorar ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15545, 'nvi', 'Salmos', 'sl', 102, 23, 'No meio da minha vida ele me abateu com sua força; abreviou os meus dias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15546, 'nvi', 'Salmos', 'sl', 102, 24, 'Então pedi: "Ó meu Deus, não me leves no meio dos meus dias. Os teus dias duram por todas as gerações!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15547, 'nvi', 'Salmos', 'sl', 102, 25, 'No princípio firmaste os fundamentos da terra, e os céus são obras das tuas mãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15548, 'nvi', 'Salmos', 'sl', 102, 26, 'Eles perecerão, mas tu permanecerás; envelhecerão como vestimentas. Como roupas tu os trocarás e serão jogados fora.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15549, 'nvi', 'Salmos', 'sl', 102, 27, 'Mas tu permaneces o mesmo, e os teus dias jamais terão fim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15550, 'nvi', 'Salmos', 'sl', 102, 28, 'Os filhos dos teus servos terão uma habitação; os seus descendentes serão estabelecidos na tua presença".');
