-- Inserções para Salmos 18
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14120, 'nvi', 'Salmos', 'sl', 18, 1, 'Eu te amo, ó Senhor, minha força.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14121, 'nvi', 'Salmos', 'sl', 18, 2, 'O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14122, 'nvi', 'Salmos', 'sl', 18, 3, 'Clamo ao Senhor, que é digno de louvor, e estou salvo dos meus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14123, 'nvi', 'Salmos', 'sl', 18, 4, 'As cordas da morte me enredaram; as torrentes da destruição me surpreenderam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14124, 'nvi', 'Salmos', 'sl', 18, 5, 'As cordas do Sheol me envolveram; os laços da morte me alcançaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14125, 'nvi', 'Salmos', 'sl', 18, 6, 'Na minha aflição clamei ao Senhor; gritei por socorro ao meu Deus. Do seu templo ele ouviu a minha voz; meu grito chegou à sua presença, aos seus ouvidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14126, 'nvi', 'Salmos', 'sl', 18, 7, 'A terra tremeu e agitou-se, e os fundamentos dos montes se abalaram; estremeceram porque ele se irou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14127, 'nvi', 'Salmos', 'sl', 18, 8, 'Das suas narinas subiu fumaça; da sua boca saíram brasas vivas e fogo consumidor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14128, 'nvi', 'Salmos', 'sl', 18, 9, 'Ele abriu os céus e desceu; nuvens escuras estavam sob os seus pés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14129, 'nvi', 'Salmos', 'sl', 18, 10, 'Montou um querubim e voou, deslizando sobre as asas do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14130, 'nvi', 'Salmos', 'sl', 18, 11, 'Fez das trevas o seu esconderijo, das escuras nuvens, cheias de água, o abrigo que o envolvia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14131, 'nvi', 'Salmos', 'sl', 18, 12, 'Com o fulgor da sua presença as nuvens se desfizeram em granizo e raios,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14132, 'nvi', 'Salmos', 'sl', 18, 13, 'quando dos céus trovejou o Senhor, e ressoou a voz do Altíssimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14133, 'nvi', 'Salmos', 'sl', 18, 14, 'Atirou suas flechas e dispersou os inimigos, com seus raios os derrotou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14134, 'nvi', 'Salmos', 'sl', 18, 15, 'O fundo do mar apareceu, e os fundamentos da terra foram expostos pela tua repreensão, ó Senhor, com o forte sopro das tuas narinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14135, 'nvi', 'Salmos', 'sl', 18, 16, 'Das alturas estendeu a mão e me segurou; tirou-me das águas profundas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14136, 'nvi', 'Salmos', 'sl', 18, 17, 'Livrou-me do meu inimigo poderoso, dos meus adversários, fortes demais para mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14137, 'nvi', 'Salmos', 'sl', 18, 18, 'Eles me atacaram no dia da minha desgraça, mas o Senhor foi o meu amparo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14138, 'nvi', 'Salmos', 'sl', 18, 19, 'Ele me deu total libertação; livrou-me porque me quer bem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14139, 'nvi', 'Salmos', 'sl', 18, 20, 'O Senhor me tratou conforme a minha justiça; conforme a pureza das minhas mãos recompensou-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14140, 'nvi', 'Salmos', 'sl', 18, 21, 'Pois segui os caminhos do Senhor; não agi como ímpio, afastando-me do meu Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14141, 'nvi', 'Salmos', 'sl', 18, 22, 'Todas as suas ordenanças estão diante de mim; não me desviei dos seus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14142, 'nvi', 'Salmos', 'sl', 18, 23, 'Tenho sido irrepreensível para com ele e guardei-me de praticar o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14143, 'nvi', 'Salmos', 'sl', 18, 24, 'O Senhor me recompensou conforme a minha justiça, conforme a pureza das minhas mãos diante dos seus olhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14144, 'nvi', 'Salmos', 'sl', 18, 25, 'Ao fiel te revelas fiel, ao irrepreensível te revelas irrepreensível,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14145, 'nvi', 'Salmos', 'sl', 18, 26, 'ao puro te revelas puro, mas com o perverso reages à altura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14146, 'nvi', 'Salmos', 'sl', 18, 27, 'Salvas os que são humildes, mas humilhas os de olhos altivos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14147, 'nvi', 'Salmos', 'sl', 18, 28, 'Tu, Senhor, manténs acesa a minha lâmpada; o meu Deus transforma em luz as minhas trevas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14148, 'nvi', 'Salmos', 'sl', 18, 29, 'Com o teu auxílio posso atacar uma tropa; com o meu Deus posso transpor muralhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14149, 'nvi', 'Salmos', 'sl', 18, 30, 'Este é o Deus cujo caminho é perfeito; a palavra do Senhor é comprovadamente genuína. Ele é um escudo para todos os que nele se refugiam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14150, 'nvi', 'Salmos', 'sl', 18, 31, 'Pois quem é Deus além do Senhor? E quem é rocha senão o nosso Deus?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14151, 'nvi', 'Salmos', 'sl', 18, 32, 'Ele é o Deus que me reveste de força e torna perfeito o meu caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14152, 'nvi', 'Salmos', 'sl', 18, 33, 'Torna os meus pés ágeis como os da corça, sustenta-me firme nas alturas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14153, 'nvi', 'Salmos', 'sl', 18, 34, 'Ele treina as minhas mãos para a batalha e os meus braços para vergar um arco de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14154, 'nvi', 'Salmos', 'sl', 18, 35, 'Tu me dás o teu escudo de vitória; tua mão direita me sustém; desces ao meu encontro para exaltar-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14155, 'nvi', 'Salmos', 'sl', 18, 36, 'Deixaste livre o meu caminho, para que não se torçam os meus tornozelos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14156, 'nvi', 'Salmos', 'sl', 18, 37, 'Persegui os meus inimigos e os alcancei; e não voltei enquanto não foram destruídos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14157, 'nvi', 'Salmos', 'sl', 18, 38, 'Massacrei-os, e não puderam levantar-se; jazem debaixo dos meus pés.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14158, 'nvi', 'Salmos', 'sl', 18, 39, 'Deste-me força para o combate; subjugaste os que se rebelaram contra mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14159, 'nvi', 'Salmos', 'sl', 18, 40, 'Puseste os meus inimigos em fuga e exterminei os que me odiavam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14160, 'nvi', 'Salmos', 'sl', 18, 41, 'Gritaram por socorro, mas não houve quem os salvasse; clamaram ao Senhor, mas ele não respondeu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14161, 'nvi', 'Salmos', 'sl', 18, 42, 'Eu os reduzi a pó, pó que o vento leva. Pisei-os como à lama das ruas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14162, 'nvi', 'Salmos', 'sl', 18, 43, 'Tu me livraste de um povo em revolta; fizeste-me o cabeça de nações; um povo que não conheci sujeita-se a mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14163, 'nvi', 'Salmos', 'sl', 18, 44, 'Assim que me ouvem, me obedecem; são estrangeiros que se submetem a mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14164, 'nvi', 'Salmos', 'sl', 18, 45, 'Todos eles perderam a coragem; tremendo, saem das suas fortalezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14165, 'nvi', 'Salmos', 'sl', 18, 46, 'O Senhor vive! Bendita seja a minha Rocha! Exaltado seja Deus, o meu Salvador!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14166, 'nvi', 'Salmos', 'sl', 18, 47, 'Este é o Deus que em meu favor executa vingança, que a mim sujeita nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14167, 'nvi', 'Salmos', 'sl', 18, 48, 'Tu me livraste dos meus inimigos; Sim, fizeste-me triunfar sobre os meus agressores, e de homens violentos me libertaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14168, 'nvi', 'Salmos', 'sl', 18, 49, 'Por isso eu te louvarei entre as nações, ó Senhor; cantarei louvores ao teu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14169, 'nvi', 'Salmos', 'sl', 18, 50, 'Ele dá grandes vitórias ao seu rei; é bondoso com o seu ungido, com Davi e os seus descendentes para sempre.');
