-- Inserções para Salmos 106
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15653, 'nvi', 'Salmos', 'sl', 106, 1, 'Aleluia! Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15654, 'nvi', 'Salmos', 'sl', 106, 2, 'Quem poderá descrever os feitos poderosos do Senhor, ou declarar todo o louvor que lhe é devido?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15655, 'nvi', 'Salmos', 'sl', 106, 3, 'Como são felizes os que perseveram na retidão, que sempre praticam a justiça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15656, 'nvi', 'Salmos', 'sl', 106, 4, 'Lembra-te de mim, Senhor, quando tratares com bondade o teu povo; vem em meu auxílio quando o salvares,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15657, 'nvi', 'Salmos', 'sl', 106, 5, 'para que eu possa testemunhar o bem-estar dos teus escolhidos, alegrar-me com a alegria do teu povo, e louvar-te junto com a tua herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15658, 'nvi', 'Salmos', 'sl', 106, 6, 'Pecamos como os nossos antepassados; fizemos o mal e fomos rebeldes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15659, 'nvi', 'Salmos', 'sl', 106, 7, 'No Egito, os nossos antepassados não deram atenção às tuas maravilhas; não se lembraram das muitas manifestações do teu amor leal e rebelaram-se junto ao mar, o mar Vermelho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15660, 'nvi', 'Salmos', 'sl', 106, 8, 'Contudo, ele os salvou por causa do seu nome, para manifestar o seu poder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15661, 'nvi', 'Salmos', 'sl', 106, 9, 'Repreendeu o mar Vermelho, e este secou; ele os conduziu pelas profundezas como por um deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15662, 'nvi', 'Salmos', 'sl', 106, 10, 'Salvou-os das mãos daqueles que os odiavam; das mãos dos inimigos os resgatou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15663, 'nvi', 'Salmos', 'sl', 106, 11, 'As águas cobriram os seus adversários; nenhum deles sobreviveu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15664, 'nvi', 'Salmos', 'sl', 106, 12, 'Então creram nas suas promessas e a ele cantaram louvores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15665, 'nvi', 'Salmos', 'sl', 106, 13, 'Mas logo se esqueceram do que ele tinha feito e não esperaram para saber o seu plano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15666, 'nvi', 'Salmos', 'sl', 106, 14, 'Dominados pela gula no deserto, puseram Deus à prova nas regiões áridas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15667, 'nvi', 'Salmos', 'sl', 106, 15, 'Deu-lhes o que pediram, mas mandou sobre eles uma doença terrível.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15668, 'nvi', 'Salmos', 'sl', 106, 16, 'No acampamento tiveram inveja de Moisés e de Arão, daquele que fora consagrado ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15669, 'nvi', 'Salmos', 'sl', 106, 17, 'A terra abriu-se, engoliu Data e sepultou o grupo de Abirão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15670, 'nvi', 'Salmos', 'sl', 106, 18, 'fogo surgiu entre os seus seguidores; as chamas consumiram os ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15671, 'nvi', 'Salmos', 'sl', 106, 19, 'Em Horebe fizeram um bezerro, adoraram um ídolo de metal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15672, 'nvi', 'Salmos', 'sl', 106, 20, 'Trocaram a Glória deles pela imagem de um boi que come capim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15673, 'nvi', 'Salmos', 'sl', 106, 21, 'Esqueceram-se de Deus, seu Salvador, que fizera coisas grandiosas no Egito,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15674, 'nvi', 'Salmos', 'sl', 106, 22, 'maravilhas na terra de Cam e feitos temíveis junto ao mar Vermelho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15675, 'nvi', 'Salmos', 'sl', 106, 23, 'Por isso, ele ameaçou destruí-los; mas Moisés, seu escolhido, intercedeu diante dele, para evitar que a sua ira os destruísse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15676, 'nvi', 'Salmos', 'sl', 106, 24, 'Também rejeitaram a terra desejável; não creram na promessa dele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15677, 'nvi', 'Salmos', 'sl', 106, 25, 'Queixaram-se em suas tendas e não obedeceram ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15678, 'nvi', 'Salmos', 'sl', 106, 26, 'Assim, de mão levantada, ele jurou que os abateria no deserto');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15679, 'nvi', 'Salmos', 'sl', 106, 27, 'e dispersaria os seus descendentes entre as nações e os espalharia por outras terras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15680, 'nvi', 'Salmos', 'sl', 106, 28, 'Sujeitaram-se ao jugo de Baal-Peor e comeram sacrifícios oferecidos a ídolos mortos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15681, 'nvi', 'Salmos', 'sl', 106, 29, 'provocaram a ira do Senhor com os seus atos, e uma praga irrompeu no meio deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15682, 'nvi', 'Salmos', 'sl', 106, 30, 'Mas Finéias se interpôs para executar o juízo, e a praga foi interrompida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15683, 'nvi', 'Salmos', 'sl', 106, 31, 'Isso lhe foi creditado como um ato de justiça que para sempre será lembrado, por todas as gerações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15684, 'nvi', 'Salmos', 'sl', 106, 32, 'Provocaram a ira de Deus junto às águas de Meribá; e, por causa deles, Moisés foi castigado;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15685, 'nvi', 'Salmos', 'sl', 106, 33, 'rebelaram-se contra o Espírito de Deus, e Moisés falou sem refletir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15686, 'nvi', 'Salmos', 'sl', 106, 34, 'Eles não destruíram os povos, como o Senhor tinha ordenado,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15687, 'nvi', 'Salmos', 'sl', 106, 35, 'em vez disso, misturaram-se com as nações e imitaram as suas práticas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15688, 'nvi', 'Salmos', 'sl', 106, 36, 'Prestaram culto aos seus ídolos, que se tornaram uma armadilha para eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15689, 'nvi', 'Salmos', 'sl', 106, 37, 'Sacrificaram seus filhos e suas filhas aos demônios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15690, 'nvi', 'Salmos', 'sl', 106, 38, 'Derramaram sangue inocente, o sangue de seus filhos e filhas sacrificados aos ídolos de Canaã; e a terra foi profanada pelo sangue deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15691, 'nvi', 'Salmos', 'sl', 106, 39, 'Tornaram-se impuros pelos seus atos; prostituíram-se por suas ações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15692, 'nvi', 'Salmos', 'sl', 106, 40, 'Por isso acendeu-se a ira do Senhor contra o seu povo e ele sentiu aversão por sua herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15693, 'nvi', 'Salmos', 'sl', 106, 41, 'Entregou-os nas mãos das nações, e os seus adversários dominaram sobre eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15694, 'nvi', 'Salmos', 'sl', 106, 42, 'Os seus inimigos os oprimiram e os subjugaram com o seu poder.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15695, 'nvi', 'Salmos', 'sl', 106, 43, 'Ele os libertou muitas vezes, embora eles persistissem em seus planos de rebelião e afundassem em sua maldade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15696, 'nvi', 'Salmos', 'sl', 106, 44, 'Mas Deus atentou para o sofrimento deles quando ouviu o seu clamor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15697, 'nvi', 'Salmos', 'sl', 106, 45, 'Lembrou-se da sua aliança com eles, e arrependeu-se, por causa do seu imenso amor leal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15698, 'nvi', 'Salmos', 'sl', 106, 46, 'Fez com que os seus captores tivessem misericórdia deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15699, 'nvi', 'Salmos', 'sl', 106, 47, 'Salva-nos, Senhor, nosso Deus! Ajunta-nos dentre as nações, para que demos graças ao teu santo nome e façamos do teu louvor a nossa glória.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15700, 'nvi', 'Salmos', 'sl', 106, 48, 'Bendito seja o Senhor, o Deus de Israel, por toda a eternidade. Que todo o povo diga: "Amém! " Aleluia!');
