-- Inserções para Salmos 78
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15115, 'nvi', 'Salmos', 'sl', 78, 1, 'Povo meu, escute o meu ensino; incline os ouvidos para o que eu tenho a dizer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15116, 'nvi', 'Salmos', 'sl', 78, 2, 'Em parábolas abrirei a minha boca, proferirei enigmas do passado;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15117, 'nvi', 'Salmos', 'sl', 78, 3, 'o que ouvimos e aprendemos, o que nossos pais nos contaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15118, 'nvi', 'Salmos', 'sl', 78, 4, 'Não os esconderemos dos nossos filhos; contaremos à próxima geração os louváveis feitos do Senhor, o seu poder e as maravilhas que fez.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15119, 'nvi', 'Salmos', 'sl', 78, 5, 'Ele decretou estatutos para Jacó, e em Israel estabeleceu a lei, e ordenou aos nossos antepassados que a ensinassem aos seus filhos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15120, 'nvi', 'Salmos', 'sl', 78, 6, 'de modo que a geração seguinte a conhecesse, e também os filhos que ainda nasceriam, e eles, por sua vez, contassem aos seus próprios filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15121, 'nvi', 'Salmos', 'sl', 78, 7, 'Então eles porão a confiança em Deus; não esquecerão os seus feitos e obedecerão aos seus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15122, 'nvi', 'Salmos', 'sl', 78, 8, 'Eles não serão como os seus antepassados, obstinados e rebeldes, povo de coração desleal para com Deus, gente de espírito infiel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15123, 'nvi', 'Salmos', 'sl', 78, 9, 'Os homens de Efraim, flecheiros armados, viraram as costas no dia da batalha;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15124, 'nvi', 'Salmos', 'sl', 78, 10, 'não guardaram a aliança de Deus e se recusaram a viver de acordo com a sua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15125, 'nvi', 'Salmos', 'sl', 78, 11, 'Esqueceram o que ele tinha feito, as maravilhas que lhes havia mostrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15126, 'nvi', 'Salmos', 'sl', 78, 12, 'Ele fez milagres diante dos seus antepassados, na terra do Egito, na região de Zoã.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15127, 'nvi', 'Salmos', 'sl', 78, 13, 'Dividiu o mar para que pudessem passar; fez a água erguer-se como um muro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15128, 'nvi', 'Salmos', 'sl', 78, 14, 'Ele os guiou com a nuvem de dia e com a luz do fogo de noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15129, 'nvi', 'Salmos', 'sl', 78, 15, 'Fendeu as rochas no deserto e deu-lhes tanta água como a que flui das profundezas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15130, 'nvi', 'Salmos', 'sl', 78, 16, 'da pedra fez sair regatos e fluir água como um rio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15131, 'nvi', 'Salmos', 'sl', 78, 17, 'Mas contra ele continuaram a pecar, revoltando-se no deserto contra o Altíssimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15132, 'nvi', 'Salmos', 'sl', 78, 18, 'Deliberadamente puseram Deus à prova, exigindo o que desejavam comer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15133, 'nvi', 'Salmos', 'sl', 78, 19, 'Duvidaram de Deus, dizendo: "Poderá Deus preparar uma mesa no deserto?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15134, 'nvi', 'Salmos', 'sl', 78, 20, 'Sabemos que quando ele feriu a rocha a água brotou e jorrou em torrentes. Mas conseguirá também dar-nos de comer? Poderá suprir de carne o seu povo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15135, 'nvi', 'Salmos', 'sl', 78, 21, 'O Senhor os ouviu e enfureceu-se; atacou Jacó com fogo, e sua ira levantou-se contra Israel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15136, 'nvi', 'Salmos', 'sl', 78, 22, 'pois eles não creram em Deus nem confiaram no seu poder salvador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15137, 'nvi', 'Salmos', 'sl', 78, 23, 'Contudo, ele deu ordens às nuvens e abriu as portas dos céus;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15138, 'nvi', 'Salmos', 'sl', 78, 24, 'fez chover maná para que o povo comesse, deu-lhe o pão dos céus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15139, 'nvi', 'Salmos', 'sl', 78, 25, 'Os homens comeram o pão dos anjos; enviou-lhes comida à vontade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15140, 'nvi', 'Salmos', 'sl', 78, 26, 'Enviou dos céus o vento oriental e pelo seu poder fez avançar o vento sul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15141, 'nvi', 'Salmos', 'sl', 78, 27, 'Fez chover carne sobre eles como pó, bandos de aves como a areia da praia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15142, 'nvi', 'Salmos', 'sl', 78, 28, 'Levou-as a cair dentro do acampamento, ao redor das suas tendas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15143, 'nvi', 'Salmos', 'sl', 78, 29, 'Comeram à vontade, e assim ele satisfez o desejo deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15144, 'nvi', 'Salmos', 'sl', 78, 30, 'Mas, antes de saciarem o apetite, quando ainda tinham a comida na boca,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15145, 'nvi', 'Salmos', 'sl', 78, 31, 'acendeu-se contra eles a ira de Deus; e ele feriu de morte os mais fortes dentre eles, matando os jovens de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15146, 'nvi', 'Salmos', 'sl', 78, 32, 'A despeito disso tudo, continuaram pecando; não creram nos seus prodígios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15147, 'nvi', 'Salmos', 'sl', 78, 33, 'Por isso ele encerrou os dias deles como um sopro e os anos deles em repentino pavor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15148, 'nvi', 'Salmos', 'sl', 78, 34, 'Sempre que Deus os castigava com a morte, eles o buscavam; com fervor se voltavam de novo para ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15149, 'nvi', 'Salmos', 'sl', 78, 35, 'Lembravam-se de que Deus era a sua Rocha, de que o Deus Altíssimo era o seu Redentor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15150, 'nvi', 'Salmos', 'sl', 78, 36, 'Com a boca o adulavam, com a língua o enganavam;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15151, 'nvi', 'Salmos', 'sl', 78, 37, 'o coração deles não era sincero; não foram fiéis à sua aliança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15152, 'nvi', 'Salmos', 'sl', 78, 38, 'Contudo, ele foi misericordioso; perdoou-lhes as maldades e não os destruiu. Vez após vez conteve a sua ira, sem despertá-la totalmente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15153, 'nvi', 'Salmos', 'sl', 78, 39, 'Lembrou-se de que eram meros mortais, brisa passageira que não retorna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15154, 'nvi', 'Salmos', 'sl', 78, 40, 'Quantas vezes mostraram-se rebeldes contra ele no deserto e o entristeceram na terra solitária!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15155, 'nvi', 'Salmos', 'sl', 78, 41, 'Repetidas vezes puseram Deus à prova; irritaram o Santo de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15156, 'nvi', 'Salmos', 'sl', 78, 42, 'Não se lembravam da sua mão poderosa, do dia em que os redimiu do opressor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15157, 'nvi', 'Salmos', 'sl', 78, 43, 'do dia em que mostrou os seus prodígios no Egito, as suas maravilhas na região de Zoã,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15158, 'nvi', 'Salmos', 'sl', 78, 44, 'quando transformou os rios e os riachos dos egípcios em sangue, e não mais conseguiam beber das suas águas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15159, 'nvi', 'Salmos', 'sl', 78, 45, 'e enviou enxames de moscas que os devoraram, e rãs que os devastaram;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15160, 'nvi', 'Salmos', 'sl', 78, 46, 'quando entregou as suas plantações às larvas, a produção da terra aos gafanhotos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15161, 'nvi', 'Salmos', 'sl', 78, 47, 'e destruiu as suas vinhas com a saraiva e as suas figueiras bravas, com a geada;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15162, 'nvi', 'Salmos', 'sl', 78, 48, 'quando entregou o gado deles ao granizo, os seus rebanhos aos raios;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15163, 'nvi', 'Salmos', 'sl', 78, 49, 'quando os atingiu com a sua ira ardente, com furor, indignação e hostilidade, com muitos anjos destruidores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15164, 'nvi', 'Salmos', 'sl', 78, 50, 'Abriu caminho para a sua ira; não os poupou da morte, mas os entregou à peste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15165, 'nvi', 'Salmos', 'sl', 78, 51, 'Matou todos os primogênitos do Egito, as primícias do vigor varonil das tendas de Cam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15166, 'nvi', 'Salmos', 'sl', 78, 52, 'Mas tirou o seu povo como ovelhas e o conduziu como a um rebanho pelo deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15167, 'nvi', 'Salmos', 'sl', 78, 53, 'Ele os guiou em segurança, e não tiveram medo; e os seus inimigos afundaram-se no mar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15168, 'nvi', 'Salmos', 'sl', 78, 54, 'Assim os trouxe à fronteira da sua terra santa, aos montes que a sua mão direita conquistou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15169, 'nvi', 'Salmos', 'sl', 78, 55, 'Expulsou nações que lá estavam, distribuiu-lhes as terras por herança e deu suas tendas às tribos de Israel para que nelas habitassem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15170, 'nvi', 'Salmos', 'sl', 78, 56, 'Mas eles puseram Deus à prova e foram rebeldes contra o Altíssimo; não obedeceram aos seus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15171, 'nvi', 'Salmos', 'sl', 78, 57, 'Foram desleais e infiéis, como os seus antepassados, confiáveis como um arco defeituoso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15172, 'nvi', 'Salmos', 'sl', 78, 58, 'Eles o irritaram com os altares idólatras; com os seus ídolos lhe provocaram ciúmes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15173, 'nvi', 'Salmos', 'sl', 78, 59, 'Sabendo-o Deus, enfureceu-se e rejeitou totalmente a Israel;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15174, 'nvi', 'Salmos', 'sl', 78, 60, 'abandonou o tabernáculo de Siló, a tenda onde habitava entre os homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15175, 'nvi', 'Salmos', 'sl', 78, 61, 'Entregou o símbolo do seu poder ao cativeiro, e o seu esplendor, nas mãos do adversário.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15176, 'nvi', 'Salmos', 'sl', 78, 62, 'Deixou que o seu povo fosse morto à espada, pois enfureceu-se com a sua herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15177, 'nvi', 'Salmos', 'sl', 78, 63, 'O fogo consumiu os seus jovens, e as suas moças não tiveram canções de núpcias;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15178, 'nvi', 'Salmos', 'sl', 78, 64, 'os sacerdotes foram mortos à espada! As viúvas já nem podiam chorar!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15179, 'nvi', 'Salmos', 'sl', 78, 65, 'Então o Senhor despertou como que de um sono, como um guerreiro exaltado pelo vinho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15180, 'nvi', 'Salmos', 'sl', 78, 66, 'Fez retroceder a golpes os seus adversários e os entregou a permanente humilhação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15181, 'nvi', 'Salmos', 'sl', 78, 67, 'Também rejeitou as tendas de José, e não escolheu a tribo de Efraim;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15182, 'nvi', 'Salmos', 'sl', 78, 68, 'ao contrário, escolheu a tribo de Judá e o monte Sião, o qual amou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15183, 'nvi', 'Salmos', 'sl', 78, 69, 'Construiu o seu santuário como as alturas; como a terra o firmou para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15184, 'nvi', 'Salmos', 'sl', 78, 70, 'Escolheu o seu servo Davi e o tirou do aprisco das ovelhas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15185, 'nvi', 'Salmos', 'sl', 78, 71, 'do pastoreio de ovelhas para ser o pastor de Jacó, seu povo, de Israel, sua herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15186, 'nvi', 'Salmos', 'sl', 78, 72, 'E de coração íntegro Davi os pastoreou, com mãos experientes os conduziu.');
