-- Inserções para Salmos 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14023, 'nvi', 'Salmos', 'sl', 9, 1, 'Senhor, quero dar-te graças de todo o coração e falar de todas as tuas maravilhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14024, 'nvi', 'Salmos', 'sl', 9, 2, 'Em ti quero alegrar-me e exultar, e cantar louvores ao teu nome, ó Altíssimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14025, 'nvi', 'Salmos', 'sl', 9, 3, 'Quando os meus inimigos contigo se defrontam, tropeçam e são destruídos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14026, 'nvi', 'Salmos', 'sl', 9, 4, 'Pois defendeste o meu direito e a minha causa; em teu trono te assentaste, julgando com justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14027, 'nvi', 'Salmos', 'sl', 9, 5, 'Repreendeste as nações e destruíste os ímpios; para todo o sempre apagaste o nome deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14028, 'nvi', 'Salmos', 'sl', 9, 6, 'O inimigo foi totalmente arrasado, para sempre; desarraigaste as suas cidades; já não há quem delas se lembre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14029, 'nvi', 'Salmos', 'sl', 9, 7, 'O Senhor reina para sempre; estabeleceu o seu trono para julgar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14030, 'nvi', 'Salmos', 'sl', 9, 8, 'Ele mesmo julga o mundo com justiça; governa os povos com retidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14031, 'nvi', 'Salmos', 'sl', 9, 9, 'O Senhor é refúgio para os oprimidos, uma torre segura na hora da adversidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14032, 'nvi', 'Salmos', 'sl', 9, 10, 'Os que conhecem o teu nome confiam em ti, pois tu, Senhor, jamais abandonas os que te buscam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14033, 'nvi', 'Salmos', 'sl', 9, 11, 'Cantem louvores ao Senhor, que reina em Sião; proclamem entre as nações os seus feitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14034, 'nvi', 'Salmos', 'sl', 9, 12, 'Aquele que pede contas do sangue derramado não esquece; ele não ignora o clamor dos oprimidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14035, 'nvi', 'Salmos', 'sl', 9, 13, 'Misericórdia, Senhor! Vê o sofrimento que me causam os que me odeiam. Salva-me das portas da morte,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14036, 'nvi', 'Salmos', 'sl', 9, 14, 'para que, junto às portas da cidade de Sião, eu cante louvores a ti e ali exulte em tua salvação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14037, 'nvi', 'Salmos', 'sl', 9, 15, 'Caíram as nações na cova que abriram; os seus pés ficaram presos no laço que esconderam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14038, 'nvi', 'Salmos', 'sl', 9, 16, 'O Senhor é conhecido pela justiça que executa; os ímpios caem em suas próprias armadilhas. Interlúdio. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14039, 'nvi', 'Salmos', 'sl', 9, 17, 'Voltem os ímpios ao pó, todas as nações que se esquecem de Deus!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14040, 'nvi', 'Salmos', 'sl', 9, 18, 'Mas os pobres nunca serão esquecidos, nem se frustrará a esperança dos necessitados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14041, 'nvi', 'Salmos', 'sl', 9, 19, 'Levanta-te, Senhor! Não permitas que o mortal triunfe! Julgadas sejam as nações na tua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14042, 'nvi', 'Salmos', 'sl', 9, 20, 'Infunde-lhes terror, Senhor; saibam as nações que não passam de seres humanos. Pausa');
