-- Inserções para Salmos 40
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14527, 'nvi', 'Salmos', 'sl', 40, 1, 'Coloquei toda minha esperança no Senhor; ele se inclinou para mim e ouviu o meu grito de socorro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14528, 'nvi', 'Salmos', 'sl', 40, 2, 'Ele me tirou de um poço de destruição, de um atoleiro de lama; pôs os meus pés sobre uma rocha e firmou-me num local seguro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14529, 'nvi', 'Salmos', 'sl', 40, 3, 'Pôs um novo cântico na minha boca, um hino de louvor ao nosso Deus. Muitos verão isso e temerão, e confiarão no Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14530, 'nvi', 'Salmos', 'sl', 40, 4, 'Como é feliz o homem que põe no Senhor a sua confiança, e não vai atrás dos orgulhosos, dos que se afastam para seguir deuses falsos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14531, 'nvi', 'Salmos', 'sl', 40, 5, 'Senhor meu Deus! Quantas maravilhas tens feito! Não se pode relatar os planos que preparaste para nós! Eu queria proclamá-los e anunciá-los, mas são por demais numerosos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14532, 'nvi', 'Salmos', 'sl', 40, 6, 'Sacrifício e oferta não pediste, mas abriste os meus ouvidos; holocaustos e ofertas pelo pecado, não exigiste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14533, 'nvi', 'Salmos', 'sl', 40, 7, 'Então eu disse: Aqui estou! No livro está escrito a meu respeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14534, 'nvi', 'Salmos', 'sl', 40, 8, 'Tenho grande alegria em fazer a tua vontade, ó meu Deus; a tua lei está no fundo do meu coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14535, 'nvi', 'Salmos', 'sl', 40, 9, 'Eu proclamo as novas de justiça na grande assembléia; como sabes, Senhor, não fecho os meus lábios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14536, 'nvi', 'Salmos', 'sl', 40, 10, 'Não oculto no coração a tua justiça; falo da tua fidelidade e da tua salvação. Não escondo da grande assembléia a tua fidelidade e a tua verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14537, 'nvi', 'Salmos', 'sl', 40, 11, 'Não me negues a tua misericórdia, Senhor; que o teu amor e a tua verdade sempre me protejam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14538, 'nvi', 'Salmos', 'sl', 40, 12, 'Pois incontáveis problemas me cercam e as minhas culpas me alcançaram, e já não consigo ver. Mais numerosos são que os cabelos da minha cabeça, e o meu coração perdeu o ânimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14539, 'nvi', 'Salmos', 'sl', 40, 13, 'Agrada-te, Senhor, em libertar-me; Apressa-te, Senhor, a ajudar-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14540, 'nvi', 'Salmos', 'sl', 40, 14, 'Sejam humilhados e frustrados todos os que procuram tirar-me a vida; retrocedam desprezados os que desejam a minha ruína.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14541, 'nvi', 'Salmos', 'sl', 40, 15, 'Fiquem chocados com a sua própria desgraça os que zombam de mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14542, 'nvi', 'Salmos', 'sl', 40, 16, 'Mas regozijem-se e alegrem-se em ti todos os que te buscam; digam sempre aqueles que amam a tua salvação: "Grande é o Senhor! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14543, 'nvi', 'Salmos', 'sl', 40, 17, 'Quanto a mim, sou pobre e necessitado, mas o Senhor preocupa-se comigo. Tu és o meu socorro e o meu libertador; meu Deus, não te demores!');
