-- Inserções para Salmos 144
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16307, 'nvi', 'Salmos', 'sl', 144, 1, 'Bendito seja o Senhor, a minha Rocha, que treina as minhas mãos para a guerra e os meus dedos para a batalha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16308, 'nvi', 'Salmos', 'sl', 144, 2, 'Ele é o meu aliado fiel, a minha fortaleza, a minha torre de proteção e o meu libertador, é o meu escudo, aquele em quem me refugio. Ele subjuga a mim os povos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16309, 'nvi', 'Salmos', 'sl', 144, 3, 'Senhor, que é o homem para que te importes com ele, ou o filho do homem para que por ele te interesses?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16310, 'nvi', 'Salmos', 'sl', 144, 4, 'O homem é como um sopro; seus dias são como uma sombra passageira.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16311, 'nvi', 'Salmos', 'sl', 144, 5, 'Estende, Senhor, os teus céus e desce; toca os montes para que fumeguem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16312, 'nvi', 'Salmos', 'sl', 144, 6, 'Envia relâmpagos e dispersa os inimigos; atira as tuas flechas e faze-os debandar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16313, 'nvi', 'Salmos', 'sl', 144, 7, 'Das alturas, estende a tua mão e liberta-me; salva-me da imensidão das águas, das mãos desses estrangeiros,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16314, 'nvi', 'Salmos', 'sl', 144, 8, 'que têm lábios mentirosos e com a mão direita erguida juram falsamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16315, 'nvi', 'Salmos', 'sl', 144, 9, 'Cantarei uma nova canção a ti, ó Deus; tocarei para ti a lira de dez cordas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16316, 'nvi', 'Salmos', 'sl', 144, 10, 'para aquele que dá vitória aos reis, que livra o seu servo Davi da espada mortal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16317, 'nvi', 'Salmos', 'sl', 144, 11, 'Dá-me libertação; salva-me das mãos dos estrangeiros, que têm lábios mentirosos e que, com a mão direita erguida, juram falsamente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16318, 'nvi', 'Salmos', 'sl', 144, 12, 'Então, na juventude, os nossos filhos serão como plantas viçosas, e as nossas filhas, como colunas esculpidas para ornar um palácio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16319, 'nvi', 'Salmos', 'sl', 144, 13, 'Os nossos celeiros estarão cheios das mais variadas provisões. Os nossos rebanhos se multiplicarão aos milhares, às dezenas de milhares em nossos campos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16320, 'nvi', 'Salmos', 'sl', 144, 14, 'o nosso gado dará suas crias; não haverá praga alguma nem aborto. Não haverá gritos de aflição em nossas ruas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16321, 'nvi', 'Salmos', 'sl', 144, 15, 'Como é feliz o povo assim abençoado! Como é feliz o povo cujo Deus é o Senhor!');
