-- Inserções para Salmos 139
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16241, 'nvi', 'Salmos', 'sl', 139, 1, 'Senhor, tu me sondas e me conheces.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16242, 'nvi', 'Salmos', 'sl', 139, 2, 'Sabes quando me sento e quando me levanto; de longe percebes os meus pensamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16243, 'nvi', 'Salmos', 'sl', 139, 3, 'Sabes muito bem quando trabalho e quando descanso; todos os meus caminhos te são bem conhecidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16244, 'nvi', 'Salmos', 'sl', 139, 4, 'Antes mesmo que a palavra me chegue à língua, tu já a conheces inteiramente, Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16245, 'nvi', 'Salmos', 'sl', 139, 5, 'Tu me cercas, por trás e pela frente, e pões a tua mão sobre mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16246, 'nvi', 'Salmos', 'sl', 139, 6, 'Tal conhecimento é maravilhoso demais e está além do meu alcance, é tão elevado que não o posso atingir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16247, 'nvi', 'Salmos', 'sl', 139, 7, 'Para onde poderia eu escapar do teu Espírito? Para onde poderia fugir da tua presença?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16248, 'nvi', 'Salmos', 'sl', 139, 8, 'Se eu subir aos céus, lá estás; se eu fizer a minha cama na sepultura, também lá estás.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16249, 'nvi', 'Salmos', 'sl', 139, 9, 'Se eu subir com as asas da alvorada e morar na extremidade do mar,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16250, 'nvi', 'Salmos', 'sl', 139, 10, 'mesmo ali a tua mão direita me guiará e me susterá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16251, 'nvi', 'Salmos', 'sl', 139, 11, 'Mesmo que eu dissesse que as trevas me encobrirão, e que a luz se tornará noite ao meu redor,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16252, 'nvi', 'Salmos', 'sl', 139, 12, 'verei que nem as trevas são escuras para ti. A noite brilhará como o dia, pois para ti as trevas são luz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16253, 'nvi', 'Salmos', 'sl', 139, 13, 'Tu criaste o íntimo do meu ser e me teceste no ventre de minha mãe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16254, 'nvi', 'Salmos', 'sl', 139, 14, 'Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16255, 'nvi', 'Salmos', 'sl', 139, 15, 'Meus ossos não estavam escondidos de ti quando em secreto fui formado e entretecido como nas profundezas da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16256, 'nvi', 'Salmos', 'sl', 139, 16, 'Os teus olhos viram o meu embrião; todos os dias determinados para mim foram escritos no teu livro antes de qualquer deles existir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16257, 'nvi', 'Salmos', 'sl', 139, 17, 'Como são preciosos para mim os teus pensamentos, ó Deus! Como é grande a soma deles!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16258, 'nvi', 'Salmos', 'sl', 139, 18, 'Se eu os contasse seriam mais do que os grãos de areia. Se terminasse de contá-los, eu ainda estaria contigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16259, 'nvi', 'Salmos', 'sl', 139, 19, 'Quem dera matasses os ímpios, ó Deus! Afastem-se de mim os assassinos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16260, 'nvi', 'Salmos', 'sl', 139, 20, 'Porque falam de ti com maldade; em vão rebelam-se contra ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16261, 'nvi', 'Salmos', 'sl', 139, 21, 'Acaso não odeio os que te odeiam, Senhor? E não detesto os que se revoltam contra ti?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16262, 'nvi', 'Salmos', 'sl', 139, 22, 'Tenho por eles ódio implacável! Considero-os inimigos meus!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16263, 'nvi', 'Salmos', 'sl', 139, 23, 'Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece as minhas inquietações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16264, 'nvi', 'Salmos', 'sl', 139, 24, 'Vê se em minha conduta algo que te ofende, e dirige-me pelo caminho eterno.');
