-- Inserções para Salmos 109
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15757, 'nvi', 'Salmos', 'sl', 109, 1, 'Ó Deus, a quem louvo, não fiques indiferente,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15758, 'nvi', 'Salmos', 'sl', 109, 2, 'pois homens ímpios e falsos dizem calúnias contra mim, e falam mentiras a meu respeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15759, 'nvi', 'Salmos', 'sl', 109, 3, 'Eles me cercaram com palavras carregadas de ódio; atacaram-me sem motivo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15760, 'nvi', 'Salmos', 'sl', 109, 4, 'Em troca da minha amizade eles me acusam, mas eu permaneço em oração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15761, 'nvi', 'Salmos', 'sl', 109, 5, 'Retribuem-me o bem com o mal, e a minha amizade com ódio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15762, 'nvi', 'Salmos', 'sl', 109, 6, 'Designe-se um ímpio como seu oponente; à sua direita esteja um acusador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15763, 'nvi', 'Salmos', 'sl', 109, 7, 'Seja declarado culpado no julgamento, e que até a sua oração seja considerada pecado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15764, 'nvi', 'Salmos', 'sl', 109, 8, 'Seja a sua vida curta, e outro ocupe o seu lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15765, 'nvi', 'Salmos', 'sl', 109, 9, 'Fiquem órfãos os seus filhos e a sua esposa, viúva.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15766, 'nvi', 'Salmos', 'sl', 109, 10, 'Vivam os seus filhos vagando como mendigos, e saiam rebuscando o pão longe de suas casas em ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15767, 'nvi', 'Salmos', 'sl', 109, 11, 'Que um credor se aposse de todos os seus bens, e estranhos saqueiem o fruto do seu trabalho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15768, 'nvi', 'Salmos', 'sl', 109, 12, 'Que ninguém o trate com bondade nem tenha misericórdia dos seus filhos órfãos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15769, 'nvi', 'Salmos', 'sl', 109, 13, 'Sejam exterminados os seus descendentes e desapareçam os seus nomes na geração seguinte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15770, 'nvi', 'Salmos', 'sl', 109, 14, 'Que o Senhor se lembre da iniqüidade dos seus antepassados, e não se apague o pecado de sua mãe.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15771, 'nvi', 'Salmos', 'sl', 109, 15, 'Estejam os seus pecados sempre perante o Senhor, e na terra ninguém jamais se lembre da sua família.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15772, 'nvi', 'Salmos', 'sl', 109, 16, 'Pois ele jamais pensou em praticar um ato de bondade, mas perseguiu até à morte o pobre, o necessitado e o de coração partido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15773, 'nvi', 'Salmos', 'sl', 109, 17, 'Ele gostava de amaldiçoar: venha sobre ele a maldição! Não tinha prazer em abençoar: afaste-se dele a bênção!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15774, 'nvi', 'Salmos', 'sl', 109, 18, 'Ele vestia a maldição como uma roupa: entre ela em seu corpo como água e em seus ossos como óleo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15775, 'nvi', 'Salmos', 'sl', 109, 19, 'Envolva-o como um manto e aperte-o sempre como um cinto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15776, 'nvi', 'Salmos', 'sl', 109, 20, 'Assim retribua o Senhor aos meus acusadores, aos que me caluniam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15777, 'nvi', 'Salmos', 'sl', 109, 21, 'Mas tu, Soberano Senhor, intervém em meu favor, por causa do teu nome. Livra-me, pois é sublime o teu amor leal!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15778, 'nvi', 'Salmos', 'sl', 109, 22, 'Sou pobre e necessitado e, no íntimo, o meu coração está abatido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15779, 'nvi', 'Salmos', 'sl', 109, 23, 'Vou definhando como a sombra vespertina; para longe sou lançado, como um gafanhoto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15780, 'nvi', 'Salmos', 'sl', 109, 24, 'De tanto jejuar os meus joelhos fraquejam e o meu corpo definha de magreza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15781, 'nvi', 'Salmos', 'sl', 109, 25, 'Sou motivo de zombaria para os meus acusadores; logo que me vêem, meneiam a cabeça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15782, 'nvi', 'Salmos', 'sl', 109, 26, 'Socorro, Senhor, meu Deus! Salva-me pelo teu amor leal!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15783, 'nvi', 'Salmos', 'sl', 109, 27, 'Que eles reconheçam que foi a tua mão, que foste tu, Senhor, que o fizeste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15784, 'nvi', 'Salmos', 'sl', 109, 28, 'Eles podem amaldiçoar, tu, porém, me abençoas. Quando atacarem, serão humilhados, mas o teu servo se alegrará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15785, 'nvi', 'Salmos', 'sl', 109, 29, 'Sejam os meus acusadores vestidos de desonra; que a vergonha os cubra como um manto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15786, 'nvi', 'Salmos', 'sl', 109, 30, 'Em alta voz, darei muitas graças ao Senhor; no meio da assembléia eu o louvarei,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15787, 'nvi', 'Salmos', 'sl', 109, 31, 'pois ele se põe ao lado do pobre para salvá-lo daqueles que o condenam.');
