-- Inserções para Salmos 118
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15871, 'nvi', 'Salmos', 'sl', 118, 1, 'Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15872, 'nvi', 'Salmos', 'sl', 118, 2, 'Que Israel diga: "O seu amor dura para sempre! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15873, 'nvi', 'Salmos', 'sl', 118, 3, 'Os sacerdotes digam: "O seu amor dura para sempre! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15874, 'nvi', 'Salmos', 'sl', 118, 4, 'Os que temem o Senhor digam: "O seu amor dura para sempre! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15875, 'nvi', 'Salmos', 'sl', 118, 5, 'Na minha angústia clamei ao Senhor; e o Senhor me respondeu, dando-me ampla liberdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15876, 'nvi', 'Salmos', 'sl', 118, 6, 'O Senhor está comigo, não temerei. O que me podem fazer os homens?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15877, 'nvi', 'Salmos', 'sl', 118, 7, 'O Senhor está comigo; ele é o meu ajudador. Verei a derrota dos meus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15878, 'nvi', 'Salmos', 'sl', 118, 8, 'É melhor buscar refúgio no Senhor do que confiar nos homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15879, 'nvi', 'Salmos', 'sl', 118, 9, 'É melhor buscar refúgio no Senhor do que confiar em príncipes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15880, 'nvi', 'Salmos', 'sl', 118, 10, 'Todas as nações me cercaram, mas em nome do Senhor eu as derrotei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15881, 'nvi', 'Salmos', 'sl', 118, 11, 'Cercaram-me por todos os lados, mas em nome do Senhor eu as derrotei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15882, 'nvi', 'Salmos', 'sl', 118, 12, 'Cercaram-me como um enxame de abelhas, mas logo se extinguiram como espinheiros em chamas. Em nome do Senhor eu as derrotei!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15883, 'nvi', 'Salmos', 'sl', 118, 13, 'Empurraram-me para forçar a minha queda, mas o Senhor me ajudou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15884, 'nvi', 'Salmos', 'sl', 118, 14, 'O Senhor é a minha força e o meu cântico; ele é a minha salvação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15885, 'nvi', 'Salmos', 'sl', 118, 15, 'Alegres brados de vitória ressoam nas tendas dos justos: "A mão direita do Senhor age com poder!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15886, 'nvi', 'Salmos', 'sl', 118, 16, 'A mão direita do Senhor é exaltada! A mão direita do Senhor age com poder! "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15887, 'nvi', 'Salmos', 'sl', 118, 17, 'Não morrerei; mas vivo ficarei para anunciar os feitos do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15888, 'nvi', 'Salmos', 'sl', 118, 18, 'O Senhor me castigou com severidade, mas não me entregou à morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15889, 'nvi', 'Salmos', 'sl', 118, 19, 'Abram as portas da justiça para mim, pois quero entrar para dar graças ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15890, 'nvi', 'Salmos', 'sl', 118, 20, 'Esta é a porta do Senhor, pela qual entram os justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15891, 'nvi', 'Salmos', 'sl', 118, 21, 'Dou-te graças, porque me respondeste e foste a minha salvação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15892, 'nvi', 'Salmos', 'sl', 118, 22, 'A pedra que os construtores rejeitaram tornou-se a pedra angular.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15893, 'nvi', 'Salmos', 'sl', 118, 23, 'Isso vem do Senhor, e é algo maravilhoso para nós.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15894, 'nvi', 'Salmos', 'sl', 118, 24, 'Este é o dia em que o Senhor agiu; alegremo-nos e exultemos neste dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15895, 'nvi', 'Salmos', 'sl', 118, 25, 'Salva-nos, Senhor! Nós imploramos. Faze-nos prosperar, Senhor! Nós suplicamos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15896, 'nvi', 'Salmos', 'sl', 118, 26, 'Bendito é o que vem em nome do Senhor. Da casa do Senhor nós os abençoamos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15897, 'nvi', 'Salmos', 'sl', 118, 27, 'O Senhor é Deus, fez resplandecer sobre nós a sua luz. Juntem-se ao cortejo festivo, levando ramos até as pontas do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15898, 'nvi', 'Salmos', 'sl', 118, 28, 'Tu és o meu Deus; graças te darei! Ó meu Deus, eu te exaltarei!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15899, 'nvi', 'Salmos', 'sl', 118, 29, 'Dêem graças ao Senhor, porque ele é bom; o seu amor dura para sempre.');
