-- Inserções para Salmos 138
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16233, 'nvi', 'Salmos', 'sl', 138, 1, 'Eu te louvarei, Senhor, de todo o coração; diante dos deuses cantarei louvores a ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16234, 'nvi', 'Salmos', 'sl', 138, 2, 'Voltado para o teu santo templo eu me prostrarei e renderei graças ao teu nome, por causa do teu amor e da tua fidelidade; pois exaltaste acima de todas as coisas o teu nome e a tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16235, 'nvi', 'Salmos', 'sl', 138, 3, 'Quando clamei, tu me respondeste; deste-me força e coragem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16236, 'nvi', 'Salmos', 'sl', 138, 4, 'Todos os reis da terra te renderão graças, Senhor, pois saberão das tuas promessas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16237, 'nvi', 'Salmos', 'sl', 138, 5, 'Celebrarão os feitos do Senhor, pois grande é a glória do Senhor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16238, 'nvi', 'Salmos', 'sl', 138, 6, 'Embora esteja nas alturas, o Senhor olha para os humildes, e de longe reconhece os arrogantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16239, 'nvi', 'Salmos', 'sl', 138, 7, 'Ainda que eu passe por angústias, tu me preservas a vida da ira dos meus inimigos; estendes a tua mão direita e me livras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16240, 'nvi', 'Salmos', 'sl', 138, 8, 'O Senhor cumprirá o seu propósito para comigo! Teu amor, Senhor, permanece para sempre; não abandones as obras das tuas mãos!');
