-- Inserções para Salmos 42
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14557, 'nvi', 'Salmos', 'sl', 42, 1, 'Como a corça anseia por águas correntes, a minha alma anseia por ti, ó Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14558, 'nvi', 'Salmos', 'sl', 42, 2, 'A minha alma tem sede de Deus, do Deus vivo. Quando poderei entrar para apresentar-me a Deus?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14559, 'nvi', 'Salmos', 'sl', 42, 3, 'Minhas lágrimas têm sido o meu alimento de dia e de noite, pois me perguntam o tempo todo: "Onde está o seu Deus? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14560, 'nvi', 'Salmos', 'sl', 42, 4, 'Quando me lembro destas coisas choro angustiado. Pois eu costumava ir com a multidão, conduzindo a procissão à casa de Deus, com cantos de alegria e de ação de graças entre a multidão que festejava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14561, 'nvi', 'Salmos', 'sl', 42, 5, 'Por que você está assim tão triste, ó minha alma? Por que está assim tão perturbada dentro de mim? Ponha a sua esperança em Deus! Pois ainda o louvarei; ele é o meu Salvador e');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14562, 'nvi', 'Salmos', 'sl', 42, 6, 'o meu Deus. A minha alma está profundamente triste; por isso de ti me lembro desde a terra do Jordão, das alturas do Hermom, desde o monte Mizar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14563, 'nvi', 'Salmos', 'sl', 42, 7, 'Abismo chama abismo ao rugir das tuas cachoeiras; todas as tuas ondas e vagalhões se abateram sobre mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14564, 'nvi', 'Salmos', 'sl', 42, 8, 'Conceda-me o Senhor o seu fiel amor de dia; de noite esteja comigo a sua canção. É a minha oração ao Deus que me dá vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14565, 'nvi', 'Salmos', 'sl', 42, 9, 'Direi a Deus, minha Rocha: "Por que te esqueceste de mim? Por que devo sair vagueando e pranteando, oprimido pelo inimigo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14566, 'nvi', 'Salmos', 'sl', 42, 10, 'Até os meus ossos sofrem agonia mortal quando os meus adversários zombam de mim, perguntando-me o tempo todo: "Onde está o seu Deus? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14567, 'nvi', 'Salmos', 'sl', 42, 11, 'Por que você está assim tão triste, ó minha alma? Por que está assim tão perturbada dentro de mim? Ponha a sua esperança em Deus! Pois ainda o louvarei; ele é o meu Salvador e o meu Deus.');
