-- Inserções para Salmos 94
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15433, 'nvi', 'Salmos', 'sl', 94, 1, 'Ó Senhor, Deus vingador; Deus vingador! Intervém!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15434, 'nvi', 'Salmos', 'sl', 94, 2, 'Levanta-te, Juiz da terra; retribui aos orgulhosos o que merecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15435, 'nvi', 'Salmos', 'sl', 94, 3, 'Até quando os ímpios, Senhor, até quando os ímpios exultarão?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15436, 'nvi', 'Salmos', 'sl', 94, 4, 'Eles despejam palavras arrogantes, todos esses malfeitores enchem-se de vanglória.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15437, 'nvi', 'Salmos', 'sl', 94, 5, 'Massacram o teu povo, Senhor, e oprimem a tua herança;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15438, 'nvi', 'Salmos', 'sl', 94, 6, 'matam as viúvas e os estrangeiros, assassinam os órfãos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15439, 'nvi', 'Salmos', 'sl', 94, 7, 'e ainda dizem: "O Senhor não nos vê; o Deus de Jacó nada percebe".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15440, 'nvi', 'Salmos', 'sl', 94, 8, 'Insensatos, procurem entender! E vocês, tolos, quando se tornarão sábios?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15441, 'nvi', 'Salmos', 'sl', 94, 9, 'Será que quem fez o ouvido não ouve? Será que quem formou o olho não vê?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15442, 'nvi', 'Salmos', 'sl', 94, 10, 'Aquele que disciplina as nações os deixará sem castigo? Não tem sabedoria aquele que dá ao homem o conhecimento?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15443, 'nvi', 'Salmos', 'sl', 94, 11, 'O Senhor conhece os pensamentos do homem, e sabe como são fúteis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15444, 'nvi', 'Salmos', 'sl', 94, 12, 'Como é feliz o homem a quem disciplinas, Senhor, aquele a quem ensinas a tua lei;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15445, 'nvi', 'Salmos', 'sl', 94, 13, 'tranqüilo, enfrentará os dias maus, enquanto que, para os ímpios, uma cova se abrirá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15446, 'nvi', 'Salmos', 'sl', 94, 14, 'O Senhor não desamparará o seu povo; jamais abandonará a sua herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15447, 'nvi', 'Salmos', 'sl', 94, 15, 'Voltará a haver justiça nos julgamentos, e todos os retos de coração a seguirão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15448, 'nvi', 'Salmos', 'sl', 94, 16, 'Quem se levantará a meu favor contra os ímpios? Quem ficará a meu lado contra os malfeitores?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15449, 'nvi', 'Salmos', 'sl', 94, 17, 'Não fosse a ajuda do Senhor, eu já estaria habitando no silêncio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15450, 'nvi', 'Salmos', 'sl', 94, 18, 'Quando eu disse: "Os meus pés escorregaram", o teu amor leal, Senhor, me amparou!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15451, 'nvi', 'Salmos', 'sl', 94, 19, 'Quando a ansiedade já me dominava no íntimo, o teu consolo trouxe alívio à minha alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15452, 'nvi', 'Salmos', 'sl', 94, 20, 'Poderá um trono corrupto estar em aliança contigo?, um trono que faz injustiças em nome da lei?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15453, 'nvi', 'Salmos', 'sl', 94, 21, 'Eles planejam contra a vida dos justos e condenam os inocentes à morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15454, 'nvi', 'Salmos', 'sl', 94, 22, 'Mas o Senhor é a minha torre segura; o meu Deus é a rocha em que encontro refúgio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15455, 'nvi', 'Salmos', 'sl', 94, 23, 'Fará cair sobre eles os seus crimes, e os destruirá por causa dos seus pecados; o Senhor, o nosso Deus, os destruirá!');
