-- Inserções para Salmos 49
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14650, 'nvi', 'Salmos', 'sl', 49, 1, 'Ouçam isto vocês, todos os povos; escutem, todos os que vivem neste mundo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14651, 'nvi', 'Salmos', 'sl', 49, 2, 'gente do povo, homens importantes, ricos e pobres igualmente:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14652, 'nvi', 'Salmos', 'sl', 49, 3, 'A minha boca falará com sabedoria; a meditação do meu coração trará entendimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14653, 'nvi', 'Salmos', 'sl', 49, 4, 'Inclinarei os meus ouvidos a um provérbio; com a harpa exporei o meu enigma:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14654, 'nvi', 'Salmos', 'sl', 49, 5, 'Por que deverei temer quando vierem dias maus, quando inimigos traiçoeiros me cercarem,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14655, 'nvi', 'Salmos', 'sl', 49, 6, 'aqueles que confiam em seus bens e se gabam de suas muitas riquezas?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14656, 'nvi', 'Salmos', 'sl', 49, 7, 'Homem algum pode redimir seu irmão ou pagar a Deus o preço de sua vida,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14657, 'nvi', 'Salmos', 'sl', 49, 8, 'pois o resgate de uma vida não tem preço. Não há pagamento que o livre');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14658, 'nvi', 'Salmos', 'sl', 49, 9, 'para que viva para sempre e não sofra decomposição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14659, 'nvi', 'Salmos', 'sl', 49, 10, 'Pois todos podem ver que os sábios morrem, como perecem o tolo e o insensato e para outros deixam os seus bens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14660, 'nvi', 'Salmos', 'sl', 49, 11, 'Seus túmulos serão suas moradas para sempre, suas habitações de geração em geração, ainda que tenham dado seus nomes a terras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14661, 'nvi', 'Salmos', 'sl', 49, 12, 'O homem, mesmo que muito importante, não vive para sempre; é como os animais, que perecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14662, 'nvi', 'Salmos', 'sl', 49, 13, 'Este é o destino dos que confiam em si mesmos, e dos seus seguidores, que aprovam o que eles dizem. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14663, 'nvi', 'Salmos', 'sl', 49, 14, 'Como ovelhas, estão destinados à sepultura, e a morte lhes servirá de pastor. Pela manhã os justos triunfarão sobre eles! A aparência deles se desfará na sepultura, longe das suas gloriosas mansões.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14664, 'nvi', 'Salmos', 'sl', 49, 15, 'Mas Deus redimirá a minha vida da sepultura e me levará para si. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14665, 'nvi', 'Salmos', 'sl', 49, 16, 'Não se aborreça quando alguém se enriquece e aumenta o luxo de sua casa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14666, 'nvi', 'Salmos', 'sl', 49, 17, 'pois nada levará consigo quando morrer; não descerá com ele o seu esplendor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14667, 'nvi', 'Salmos', 'sl', 49, 18, 'Embora em vida ele se parabenize: "Todos o elogiam, pois você está prosperando",');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14668, 'nvi', 'Salmos', 'sl', 49, 19, 'ele se juntará aos seus antepassados, que nunca mais verão a luz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14669, 'nvi', 'Salmos', 'sl', 49, 20, 'O homem, mesmo que muito importante, não tem entendimento; é como os animais, que perecem.');
