-- Inserções para Salmos 34
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14390, 'nvi', 'Salmos', 'sl', 34, 1, 'Bendirei o Senhor o tempo todo! Os meus lábios sempre o louvarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14391, 'nvi', 'Salmos', 'sl', 34, 2, 'Minha alma se gloriará no Senhor; ouçam os oprimidos e se alegrem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14392, 'nvi', 'Salmos', 'sl', 34, 3, 'Proclamem a grandeza do Senhor comigo; juntos exaltemos o seu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14393, 'nvi', 'Salmos', 'sl', 34, 4, 'Busquei o Senhor, e ele me respondeu; livrou-me de todos os meus temores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14394, 'nvi', 'Salmos', 'sl', 34, 5, 'Os que olham para ele estão radiantes de alegria; seus rostos jamais mostrarão decepção.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14395, 'nvi', 'Salmos', 'sl', 34, 6, 'Este pobre homem clamou, e o Senhor o ouviu; e o libertou de todas as suas tribulações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14396, 'nvi', 'Salmos', 'sl', 34, 7, 'O anjo do Senhor é sentinela ao redor daqueles que o temem, e os livra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14397, 'nvi', 'Salmos', 'sl', 34, 8, 'Provem, e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14398, 'nvi', 'Salmos', 'sl', 34, 9, 'Temam o Senhor, vocês que são os seus santos, pois nada falta aos que o temem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14399, 'nvi', 'Salmos', 'sl', 34, 10, 'Os leões podem passar necessidade e fome, mas os que buscam o Senhor de nada têm falta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14400, 'nvi', 'Salmos', 'sl', 34, 11, 'Venham, meus filhos, ouçam-me; eu lhes ensinarei o temor do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14401, 'nvi', 'Salmos', 'sl', 34, 12, 'Quem de vocês quer amar a vida e deseja ver dias felizes?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14402, 'nvi', 'Salmos', 'sl', 34, 13, 'Guarde a sua língua do mal e os seus lábios da falsidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14403, 'nvi', 'Salmos', 'sl', 34, 14, 'Afaste-se do mal e faça o bem; busque a paz com perseverança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14404, 'nvi', 'Salmos', 'sl', 34, 15, 'Os olhos do Senhor voltam-se para os justos e os seus ouvidos estão atentos ao seu grito de socorro;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14405, 'nvi', 'Salmos', 'sl', 34, 16, 'o rosto do Senhor volta-se contra os que praticam o mal, para apagar da terra a memória deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14406, 'nvi', 'Salmos', 'sl', 34, 17, 'Os justos clamam, o Senhor os ouve e os livra de todas as suas tribulações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14407, 'nvi', 'Salmos', 'sl', 34, 18, 'O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14408, 'nvi', 'Salmos', 'sl', 34, 19, 'O justo passa por muitas adversidades, mas o Senhor o livra de todas;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14409, 'nvi', 'Salmos', 'sl', 34, 20, 'protege todos os seus ossos; nenhum deles será quebrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14410, 'nvi', 'Salmos', 'sl', 34, 21, 'A desgraça matará os ímpios; os que odeiam o justo serão condenados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14411, 'nvi', 'Salmos', 'sl', 34, 22, 'O Senhor redime a vida dos seus servos; ninguém que nele se refugia será condenado.');
