-- Inserções para Salmos 28
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14301, 'nvi', 'Salmos', 'sl', 28, 1, 'A ti eu clamo, Senhor, minha Rocha; não fiques indiferente para comigo. Se permaneceres calado, serei como os que descem à cova.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14302, 'nvi', 'Salmos', 'sl', 28, 2, 'Ouve as minhas súplicas quando clamo a ti por socorro, quando ergo as mãos para o teu Lugar Santíssimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14303, 'nvi', 'Salmos', 'sl', 28, 3, 'Não me dês o castigo reservado para os ímpios e para os malfeitores, que falam como amigos com o próximo, mas abrigam maldade no coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14304, 'nvi', 'Salmos', 'sl', 28, 4, 'Retribui-lhes conforme os seus atos, conforme as suas más obras; retribui-lhes pelo que as suas mãos têm feito e dá-lhes o que merecem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14305, 'nvi', 'Salmos', 'sl', 28, 5, 'Visto que não consideram os feitos do Senhor, nem as obras de suas mãos, ele os arrasará e jamais os deixará reerguer-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14306, 'nvi', 'Salmos', 'sl', 28, 6, 'Bendito seja o Senhor, pois ouviu as minhas súplicas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14307, 'nvi', 'Salmos', 'sl', 28, 7, 'O Senhor é a minha força e o meu escudo; nele o meu coração confia, e dele recebo ajuda. Meu coração exulta de alegria, e com o meu cântico lhe darei graças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14308, 'nvi', 'Salmos', 'sl', 28, 8, 'O Senhor é a força do seu povo, a fortaleza que salva o seu ungido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14309, 'nvi', 'Salmos', 'sl', 28, 9, 'Salva o teu povo e abençoa a tua herança! Cuida deles como o seu pastor e conduze-os para sempre.');
