-- Inserções para Salmos 17
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14105, 'nvi', 'Salmos', 'sl', 17, 1, 'Ouve, Senhor, a minha justa queixa; atenta para o meu clamor. Dá ouvidos à minha oração, que não vem de lábios falsos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14106, 'nvi', 'Salmos', 'sl', 17, 2, 'Venha de ti a sentença em meu favor; vejam os teus olhos onde está a justiça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14107, 'nvi', 'Salmos', 'sl', 17, 3, 'Provas o meu coração e de noite me examinas, tu me sondas, e nada encontras; decidi que a minha boca não pecará');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14108, 'nvi', 'Salmos', 'sl', 17, 4, 'como fazem os homens. Pela palavra dos teus lábios eu evitei os caminhos do violento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14109, 'nvi', 'Salmos', 'sl', 17, 5, 'Meus passos seguem firmes nas tuas veredas; os meus pés não escorregaram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14110, 'nvi', 'Salmos', 'sl', 17, 6, 'Eu clamo a ti, ó Deus, pois tu me respondes; inclina para mim os teus ouvidos e ouve a minha oração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14111, 'nvi', 'Salmos', 'sl', 17, 7, 'Mostra a maravilha do teu amor, tu, que com a tua mão direita salvas os que em ti buscam proteção contra aqueles que os ameaçam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14112, 'nvi', 'Salmos', 'sl', 17, 8, 'Protege-me como à menina dos teus olhos; esconde-me à sombra das tuas asas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14113, 'nvi', 'Salmos', 'sl', 17, 9, 'dos ímpios que me atacam com violência, dos inimigos mortais que me cercam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14114, 'nvi', 'Salmos', 'sl', 17, 10, 'Eles fecham o coração insensível, e com a boca falam com arrogância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14115, 'nvi', 'Salmos', 'sl', 17, 11, 'Eles me seguem os passos, e já me cercam; seus olhos estão atentos, prontos para derrubar-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14116, 'nvi', 'Salmos', 'sl', 17, 12, 'São como um leão ávido pela presa, como um leão forte agachado na emboscada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14117, 'nvi', 'Salmos', 'sl', 17, 13, 'Levanta-te, Senhor! Confronta-os! Derruba-os! Com a tua espada livra-me dos ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14118, 'nvi', 'Salmos', 'sl', 17, 14, 'Com a tua mão, Senhor, livra-me de homens assim, de homens deste mundo, cuja recompensa está nesta vida. Enche-lhes o ventre de tudo o que lhes reservaste; sejam os seus filhos saciados, e o que sobrar fique para os seus pequeninos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14119, 'nvi', 'Salmos', 'sl', 17, 15, 'Quanto a mim, feita a justiça, verei a tua face; quando despertar ficarei satisfeito ao ver a tua semelhança.');
