-- Inserções para Salmos 72
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15002, 'nvi', 'Salmos', 'sl', 72, 1, 'Reveste da tua justiça o rei, ó Deus, e o filho do rei, da tua retidão,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15003, 'nvi', 'Salmos', 'sl', 72, 2, 'para que ele julgue com retidão e com justiça os teus que sofrem opressão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15004, 'nvi', 'Salmos', 'sl', 72, 3, 'Que os montes tragam prosperidade ao povo, e as colinas, o fruto da justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15005, 'nvi', 'Salmos', 'sl', 72, 4, 'Defenda ele os oprimidos entre o povo e liberte os filhos dos pobres; esmague ele o opressor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15006, 'nvi', 'Salmos', 'sl', 72, 5, 'Que ele perdure como o sol e como a lua, por todas as gerações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15007, 'nvi', 'Salmos', 'sl', 72, 6, 'Seja ele como chuva sobre uma lavoura ceifada, como aguaceiros que regam a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15008, 'nvi', 'Salmos', 'sl', 72, 7, 'Floresçam os justos nos dias do rei, e haja grande prosperidade enquanto durar a lua.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15009, 'nvi', 'Salmos', 'sl', 72, 8, 'Governe ele de mar a mar e desde o rio Eufrates até os confins da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15010, 'nvi', 'Salmos', 'sl', 72, 9, 'Inclinem-se diante dele as tribos do deserto, e os seus inimigos lambam o pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15011, 'nvi', 'Salmos', 'sl', 72, 10, 'Que os reis de Társis e das regiões litorâneas lhe tragam tributo; os reis de Sabá e de Sebá lhe ofereçam presentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15012, 'nvi', 'Salmos', 'sl', 72, 11, 'Inclinem-se diante dele todos os reis, e sirvam-no todas as nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15013, 'nvi', 'Salmos', 'sl', 72, 12, 'Pois ele liberta os pobres que pedem socorro, os oprimidos que não têm quem os ajude.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15014, 'nvi', 'Salmos', 'sl', 72, 13, 'Ele se compadece dos fracos e dos pobres, e os salva da morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15015, 'nvi', 'Salmos', 'sl', 72, 14, 'Ele os resgata da opressão e da violência, pois aos seus olhos a vida deles é preciosa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15016, 'nvi', 'Salmos', 'sl', 72, 15, 'Tenha o rei vida longa! Receba ele o ouro de Sabá. Que se ore por ele continuamente, e todo o dia se invoquem bênçãos sobre ele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15017, 'nvi', 'Salmos', 'sl', 72, 16, 'Haja fartura de trigo por toda a terra, ondulando no alto dos montes. Floresçam os seus frutos como os do Líbano e cresçam as cidades como as plantas no campo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15018, 'nvi', 'Salmos', 'sl', 72, 17, 'Permaneça para sempre o seu nome e dure a sua fama enquanto o sol brilhar. Sejam abençoadas todas as nações por meio dele, e que elas o chamem bendito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15019, 'nvi', 'Salmos', 'sl', 72, 18, 'Bendito seja o Senhor Deus, o Deus de Israel, o único que realiza feitos maravilhosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15020, 'nvi', 'Salmos', 'sl', 72, 19, 'Bendito seja o seu glorioso nome para sempre; encha-se toda a terra da sua glória. Amém e amém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15021, 'nvi', 'Salmos', 'sl', 72, 20, 'Encerram-se aqui as orações de Davi, filho de Jessé.');
