-- Inserções para Salmos 73
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15022, 'nvi', 'Salmos', 'sl', 73, 1, 'Certamente Deus é bom para Israel, para os puros de coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15023, 'nvi', 'Salmos', 'sl', 73, 2, 'Quanto a mim, os meus pés quase tropeçaram; por pouco não escorreguei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15024, 'nvi', 'Salmos', 'sl', 73, 3, 'Pois tive inveja dos arrogantes quando vi a prosperidade desses ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15025, 'nvi', 'Salmos', 'sl', 73, 4, 'Eles não passam por sofrimento e têm o corpo saudável e forte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15026, 'nvi', 'Salmos', 'sl', 73, 5, 'Estão livres dos fardos de todos; não são atingidos por doenças como os outros homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15027, 'nvi', 'Salmos', 'sl', 73, 6, 'Por isso o orgulho lhes serve de colar, e se vestem de violência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15028, 'nvi', 'Salmos', 'sl', 73, 7, 'Do seu íntimo brota a maldade; da sua mente transbordam maquinações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15029, 'nvi', 'Salmos', 'sl', 73, 8, 'Eles zombam e falam com más intenções; em sua arrogância ameaçam com opressão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15030, 'nvi', 'Salmos', 'sl', 73, 9, 'Com a boca arrogam a si os céus, e com a língua se apossam da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15031, 'nvi', 'Salmos', 'sl', 73, 10, 'Por isso o seu povo se volta para eles e bebem suas palavras até saciar-se.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15032, 'nvi', 'Salmos', 'sl', 73, 11, 'Eles dizem: "Como saberá Deus? Terá conhecimento o Altíssimo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15033, 'nvi', 'Salmos', 'sl', 73, 12, 'Assim são os ímpios; sempre despreocupados, aumentam suas riquezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15034, 'nvi', 'Salmos', 'sl', 73, 13, 'Certamente foi-me inútil manter puro o coração e lavar as mãos na inocência,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15035, 'nvi', 'Salmos', 'sl', 73, 14, 'pois o dia inteiro sou afligido, e todas as manhãs sou castigado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15036, 'nvi', 'Salmos', 'sl', 73, 15, 'Se eu tivesse dito "falarei com eles", teria traído os teus filhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15037, 'nvi', 'Salmos', 'sl', 73, 16, 'Quando tentei entender tudo isso, achei muito difícil para mim,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15038, 'nvi', 'Salmos', 'sl', 73, 17, 'até que entrei no santuário de Deus, e então compreendi o destino dos ímpios.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15039, 'nvi', 'Salmos', 'sl', 73, 18, 'Certamente os pões em terreno escorregadio e os fazes cair na ruína.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15040, 'nvi', 'Salmos', 'sl', 73, 19, 'Como são destruídos de repente, completamente tomados de pavor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15041, 'nvi', 'Salmos', 'sl', 73, 20, 'São como um sonho que se vai quando a gente acorda; quando te levantares, Senhor, tu os farás desaparecer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15042, 'nvi', 'Salmos', 'sl', 73, 21, 'Quando o meu coração estava amargurado e no íntimo eu sentia inveja,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15043, 'nvi', 'Salmos', 'sl', 73, 22, 'agi como insensato e ignorante; minha atitude para contigo era a de um animal irracional.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15044, 'nvi', 'Salmos', 'sl', 73, 23, 'Contudo, sempre estou contigo; tomas a minha mão direita e me susténs.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15045, 'nvi', 'Salmos', 'sl', 73, 24, 'Tu me diriges com o teu conselho, e depois me receberás com honras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15046, 'nvi', 'Salmos', 'sl', 73, 25, 'A quem tenho nos céus senão a ti? E na terra, nada mais desejo além de estar junto a ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15047, 'nvi', 'Salmos', 'sl', 73, 26, 'O meu corpo e o meu coração poderão fraquejar, mas Deus é a força do meu coração e a minha herança para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15048, 'nvi', 'Salmos', 'sl', 73, 27, 'Os que te abandonam sem dúvida perecerão; tu destróis todos os infiéis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15049, 'nvi', 'Salmos', 'sl', 73, 28, 'Mas, para mim, bom é estar perto de Deus; fiz do Soberano Senhor o meu refúgio; proclamarei todos os teus feitos.');
