-- Inserções para Salmos 104
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15573, 'nvi', 'Salmos', 'sl', 104, 1, 'Bendiga ao Senhor a minha alma! Ó Senhor, meu Deus, tu és tão grandioso! Estás vestido de majestade e esplendor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15574, 'nvi', 'Salmos', 'sl', 104, 2, 'Envolto de luz como numa veste, ele estende os céus como uma tenda,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15575, 'nvi', 'Salmos', 'sl', 104, 3, 'e põe sobre as águas dos céus as vigas dos seus aposentos. Faz das nuvens a sua carruagem e cavalga nas asas do vento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15576, 'nvi', 'Salmos', 'sl', 104, 4, 'Faz dos ventos seus mensageiros e dos clarões reluzentes seus servos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15577, 'nvi', 'Salmos', 'sl', 104, 5, 'Ele firmou a terra sobre os seus fundamentos para que jamais se abale;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15578, 'nvi', 'Salmos', 'sl', 104, 6, 'com as torrentes do abismo a cobriste, como se fossem uma veste; as águas subiram acima dos montes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15579, 'nvi', 'Salmos', 'sl', 104, 7, 'Diante das tuas ameaças as águas fugiram, puseram-se em fuga ao som do teu trovão;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15580, 'nvi', 'Salmos', 'sl', 104, 8, 'subiram pelos montes e escorreram pelos vales, para os lugares que tu lhes designaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15581, 'nvi', 'Salmos', 'sl', 104, 9, 'Estabeleceste um limite que não podem ultrapassar; jamais tornarão a cobrir a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15582, 'nvi', 'Salmos', 'sl', 104, 10, 'Fazes jorrar as nascentes nos vales e correrem as águas entre os montes;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15583, 'nvi', 'Salmos', 'sl', 104, 11, 'delas bebem todos os animais selvagens, e os jumentos selvagens saciam a sua sede.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15584, 'nvi', 'Salmos', 'sl', 104, 12, 'As aves do céu fazem ninho junto às águas e entre os galhos põem-se a cantar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15585, 'nvi', 'Salmos', 'sl', 104, 13, 'Dos seus aposentos celestes ele rega os montes; sacia-se a terra com o fruto das tuas obras!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15586, 'nvi', 'Salmos', 'sl', 104, 14, 'É ele que faz crescer o pasto para o gado, e as plantas que o homem cultiva, para da terra tirar o alimento:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15587, 'nvi', 'Salmos', 'sl', 104, 15, 'o vinho, que alegra o coração do homem; o azeite, que faz brilhar o rosto, e o pão que sustenta o seu vigor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15588, 'nvi', 'Salmos', 'sl', 104, 16, 'As árvores do Senhor são bem regadas, os cedros do Líbano que ele plantou;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15589, 'nvi', 'Salmos', 'sl', 104, 17, 'nelas os pássaros fazem ninho, e nos pinheiros a cegonha tem o seu lar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15590, 'nvi', 'Salmos', 'sl', 104, 18, 'Os montes elevados pertencem aos bodes selvagens, e os penhascos são um refúgio para os coelhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15591, 'nvi', 'Salmos', 'sl', 104, 19, 'Ele fez a lua para marcar estações; o sol sabe quando deve se pôr.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15592, 'nvi', 'Salmos', 'sl', 104, 20, 'Trazes trevas, e cai a noite, quando os animais da floresta vagueiam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15593, 'nvi', 'Salmos', 'sl', 104, 21, 'Os leões rugem à procura da presa, buscando de Deus o alimento,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15594, 'nvi', 'Salmos', 'sl', 104, 22, 'mas ao nascer do sol eles se vão e voltam a deitar-se em suas tocas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15595, 'nvi', 'Salmos', 'sl', 104, 23, 'Então o homem sai para o seu trabalho, para o seu labor até o entardecer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15596, 'nvi', 'Salmos', 'sl', 104, 24, 'Quantas são as tuas obras, Senhor! Fizeste todas elas com sabedoria! A terra está cheia de seres que criaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15597, 'nvi', 'Salmos', 'sl', 104, 25, 'Eis o mar, imenso e vasto. Nele vivem inúmeras criaturas, seres vivos, pequenos e grandes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15598, 'nvi', 'Salmos', 'sl', 104, 26, 'Nele passam os navios, e também o Leviatã, que formaste para com ele brincar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15599, 'nvi', 'Salmos', 'sl', 104, 27, 'Todos eles esperam em ti para que lhes dês o alimento no tempo certo;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15600, 'nvi', 'Salmos', 'sl', 104, 28, 'tu lhes dás, e eles o recolhem, abres a tua mão, e saciam-se de coisas boas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15601, 'nvi', 'Salmos', 'sl', 104, 29, 'Quando escondes o rosto, entram em pânico; quando lhes retiras o fôlego, morrem e voltam ao pó.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15602, 'nvi', 'Salmos', 'sl', 104, 30, 'Quando sopras o teu fôlego, eles são criados, e renovas a face da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15603, 'nvi', 'Salmos', 'sl', 104, 31, 'Perdure para sempre a glória do Senhor! Alegre-se o Senhor em seus feitos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15604, 'nvi', 'Salmos', 'sl', 104, 32, 'Ele olha para a terra, e ela treme, toca os montes, e eles fumegam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15605, 'nvi', 'Salmos', 'sl', 104, 33, 'Cantarei ao Senhor toda a minha vida; louvarei ao meu Deus enquanto eu viver.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15606, 'nvi', 'Salmos', 'sl', 104, 34, 'Seja-lhe agradável a minha meditação, pois no Senhor tenho alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15607, 'nvi', 'Salmos', 'sl', 104, 35, 'Sejam os pecadores eliminados da terra e deixem de existir os ímpios. Bendiga ao Senhor a minha alma! Aleluia!');
