-- Inserções para Salmos 62
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14829, 'nvi', 'Salmos', 'sl', 62, 1, 'A minha alma descansa somente em Deus; dele vem a minha salvação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14830, 'nvi', 'Salmos', 'sl', 62, 2, 'Somente ele é a rocha que me salva; ele é a minha torre segura! Jamais serei abalado!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14831, 'nvi', 'Salmos', 'sl', 62, 3, 'Até quando todos vocês atacarão um homem, que está como um muro inclinado, como uma cerca prestes a cair?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14832, 'nvi', 'Salmos', 'sl', 62, 4, 'Todo o propósito deles é derrubá-lo de sua posição elevada; eles se deliciam com mentiras. Com a boca abençoam, mas no íntimo amaldiçoam. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14833, 'nvi', 'Salmos', 'sl', 62, 5, 'Descanse somente em Deus, ó minha alma; dele vem a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14834, 'nvi', 'Salmos', 'sl', 62, 6, 'Somente ele é a rocha que me salva; ele é a minha torre alta! Não serei abalado!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14835, 'nvi', 'Salmos', 'sl', 62, 7, 'A minha salvação e a minha honra de Deus dependem; ele é a minha rocha firme, o meu refúgio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14836, 'nvi', 'Salmos', 'sl', 62, 8, 'Confiem nele em todos os momentos, ó povo; derramem diante dele o coração, pois ele é o nosso refúgio. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14837, 'nvi', 'Salmos', 'sl', 62, 9, 'Os homens de origem humilde não passam de um sopro, os de origem importante não passam de mentira; pesados na balança, juntos não chegam ao peso de um sopro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14838, 'nvi', 'Salmos', 'sl', 62, 10, 'Não confiem na extorsão, nem ponham a esperança em bens roubados; se as suas riquezas aumentam, não ponham nelas o coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14839, 'nvi', 'Salmos', 'sl', 62, 11, 'Uma vez Deus falou, duas vezes eu ouvi, que o poder pertence a Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14840, 'nvi', 'Salmos', 'sl', 62, 12, 'Contigo também, Senhor, está a fidelidade. É certo que retribuirás a cada um conforme o seu procedimento.');
