-- Inserções para Salmos 45
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14599, 'nvi', 'Salmos', 'sl', 45, 1, 'Com o coração vibrando de boas palavras recito os meus versos em honra do rei; seja a minha língua como a pena de um hábil escritor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14600, 'nvi', 'Salmos', 'sl', 45, 2, 'És dos homens o mais notável; derramou-se graça em teus lábios, visto que Deus te abençoou para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14601, 'nvi', 'Salmos', 'sl', 45, 3, 'Prende a espada à cintura, ó poderoso! Cobre-te de esplendor e majestade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14602, 'nvi', 'Salmos', 'sl', 45, 4, 'Na tua majestade cavalga vitoriosamente pela verdade, pela misericórdia e pela justiça; que a tua mão direita realize feitos gloriosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14603, 'nvi', 'Salmos', 'sl', 45, 5, 'Tuas flechas afiadas atingem o coração dos inimigos do rei; debaixo dos teus pés caem nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14604, 'nvi', 'Salmos', 'sl', 45, 6, 'O teu trono, ó Deus, subsiste para todo o sempre; cetro de justiça é o cetro do teu reino.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14605, 'nvi', 'Salmos', 'sl', 45, 7, 'Amas a justiça e odeias a iniqüidade; por isso Deus, o teu Deus, escolheu-te dentre os teus companheiros ungindo-te com óleo de alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14606, 'nvi', 'Salmos', 'sl', 45, 8, 'Todas as tuas vestes exalam aroma de mirra, aloés e cássia; nos palácios adornados de marfim ressoam os instrumentos de corda que te alegram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14607, 'nvi', 'Salmos', 'sl', 45, 9, 'Filhas de reis estão entre as mulheres da tua corte; à tua direita está a noiva real enfeitada de ouro puro de Ofir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14608, 'nvi', 'Salmos', 'sl', 45, 10, 'Ouça, ó filha, considere e incline os seus ouvidos: Esqueça o seu povo e a casa paterna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14609, 'nvi', 'Salmos', 'sl', 45, 11, 'O rei foi cativado pela sua beleza; honre-o, pois ele é o seu senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14610, 'nvi', 'Salmos', 'sl', 45, 12, 'A cidade de Tiro trará seus presentes; seus moradores mais ricos buscarão o seu favor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14611, 'nvi', 'Salmos', 'sl', 45, 13, 'Cheia de esplendor está a princesa em seus aposentos, com vestes enfeitadas de ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14612, 'nvi', 'Salmos', 'sl', 45, 14, 'Em roupas bordadas é conduzida ao rei, acompanhada de um cortejo de virgens; são levadas à tua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14613, 'nvi', 'Salmos', 'sl', 45, 15, 'Com alegria e exultação são conduzidas ao palácio do rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14614, 'nvi', 'Salmos', 'sl', 45, 16, 'Os teus filhos ocuparão o trono dos teus pais; por toda a terra os farás príncipes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14615, 'nvi', 'Salmos', 'sl', 45, 17, 'Perpetuarei a tua lembrança por todas as gerações; por isso as nações te louvarão para todo o sempre.');
