-- Inserções para Salmos 79
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15187, 'nvi', 'Salmos', 'sl', 79, 1, 'Ó Deus, as nações invadiram a tua herança, profanaram o teu santo templo, reduziram Jerusalém a ruínas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15188, 'nvi', 'Salmos', 'sl', 79, 2, 'Deram os cadáveres dos teus servos às aves do céu por alimento, a carne dos teus fiéis, aos animais selvagens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15189, 'nvi', 'Salmos', 'sl', 79, 3, 'Derramaram o sangue deles como água ao redor de Jerusalém, e não há ninguém para sepultá-los.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15190, 'nvi', 'Salmos', 'sl', 79, 4, 'Somos motivos de zombaria para os nossos vizinhos, de riso e menosprezo para os que vivem ao nosso redor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15191, 'nvi', 'Salmos', 'sl', 79, 5, 'Até quando, Senhor? Ficarás irado para sempre? Arderá o teu ciúme como o fogo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15192, 'nvi', 'Salmos', 'sl', 79, 6, 'Derrama a tua ira sobre as nações que não te reconhecem, sobre os reinos que não invocam o teu nome,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15193, 'nvi', 'Salmos', 'sl', 79, 7, 'pois devoraram Jacó, deixando em ruínas a sua terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15194, 'nvi', 'Salmos', 'sl', 79, 8, 'Não cobres de nós as maldades dos nossos antepassados; venha depressa ao nosso encontro a tua misericórdia, pois estamos totalmente desanimados!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15195, 'nvi', 'Salmos', 'sl', 79, 9, 'Ajuda-nos, ó Deus, nosso Salvador, para a glória do teu nome; livra-nos e perdoa os nossos pecados, por amor do teu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15196, 'nvi', 'Salmos', 'sl', 79, 10, 'Por que as nações haverão de dizer: "Onde está o Deus deles? " Diante dos nossos olhos, mostra às nações a tua vingança pelo sangue dos teus servos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15197, 'nvi', 'Salmos', 'sl', 79, 11, 'Cheguem à tua presença os gemidos dos prisioneiros. Pela força do teu braço preserva os condenados à morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15198, 'nvi', 'Salmos', 'sl', 79, 12, 'Retribui sete vezes mais aos nossos vizinhos as afrontas com que te insultaram, Senhor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15199, 'nvi', 'Salmos', 'sl', 79, 13, 'Então nós, o teu povo, as ovelhas das tuas pastagens, para sempre te louvaremos; de geração em geração cantaremos os teus louvores.');
