-- Inserções para Salmos 107
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15701, 'nvi', 'Salmos', 'sl', 107, 1, 'Dêem graças ao Senhor porque ele é bom; o seu amor dura para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15702, 'nvi', 'Salmos', 'sl', 107, 2, 'Assim o digam os que o Senhor resgatou, os que livrou das mãos do adversário,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15703, 'nvi', 'Salmos', 'sl', 107, 3, 'e reuniu de outras terras, do Oriente e do Ocidente, do Norte e do Sul.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15704, 'nvi', 'Salmos', 'sl', 107, 4, 'Perambularam pelo deserto e por terras áridas sem encontrar cidade habitada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15705, 'nvi', 'Salmos', 'sl', 107, 5, 'Estavam famintos e sedentos; suas vidas iam-se esvaindo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15706, 'nvi', 'Salmos', 'sl', 107, 6, 'Na sua aflição, clamaram ao Senhor, e ele os livrou da tribulação em que se encontravam');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15707, 'nvi', 'Salmos', 'sl', 107, 7, 'e os conduziu por caminho seguro a uma cidade habitada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15708, 'nvi', 'Salmos', 'sl', 107, 8, 'Que eles dêem graças ao Senhor por seu amor leal e por suas maravilhas em favor dos homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15709, 'nvi', 'Salmos', 'sl', 107, 9, 'porque ele sacia o sedento e satisfaz plenamente o faminto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15710, 'nvi', 'Salmos', 'sl', 107, 10, 'Assentaram-se nas trevas e na sombra mortal, aflitos, acorrentados,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15711, 'nvi', 'Salmos', 'sl', 107, 11, 'pois se rebelaram contra as palavras de Deus e desprezaram os desígnios do Altíssimo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15712, 'nvi', 'Salmos', 'sl', 107, 12, 'Por isso ele os sujeitou a trabalhos pesados; eles tropeçaram, e não houve quem os ajudasse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15713, 'nvi', 'Salmos', 'sl', 107, 13, 'Na sua aflição, clamaram ao Senhor, e eles os salvou da tribulação em que se encontravam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15714, 'nvi', 'Salmos', 'sl', 107, 14, 'Ele os tirou das trevas e da sombra mortal, e quebrou as correntes que os prendiam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15715, 'nvi', 'Salmos', 'sl', 107, 15, 'Que eles dêem graças ao Senhor, por seu amor leal e por suas maravilhas em favor dos homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15716, 'nvi', 'Salmos', 'sl', 107, 16, 'porque despedaçou as portas de bronze e rompeu as trancas de ferro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15717, 'nvi', 'Salmos', 'sl', 107, 17, 'Tornaram-se tolos por causa dos seus caminhos rebeldes, e sofreram por causa das suas maldades.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15718, 'nvi', 'Salmos', 'sl', 107, 18, 'Sentiram repugnância por toda comida e chegaram perto das portas da morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15719, 'nvi', 'Salmos', 'sl', 107, 19, 'Na sua aflição, clamaram ao Senhor, e ele os salvou da tribulação em que se encontravam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15720, 'nvi', 'Salmos', 'sl', 107, 20, 'Ele enviou a sua palavra e os curou, e os livrou da morte.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15721, 'nvi', 'Salmos', 'sl', 107, 21, 'Que eles dêem graças ao Senhor, por seu amor leal e por suas maravilhas em favor dos homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15722, 'nvi', 'Salmos', 'sl', 107, 22, 'Que eles ofereçam sacrifícios de ação de graças e anunciem as suas obras com cânticos de alegria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15723, 'nvi', 'Salmos', 'sl', 107, 23, 'Fizeram-se ao mar em navios, para negócios na imensidão das águas,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15724, 'nvi', 'Salmos', 'sl', 107, 24, 'e viram as obras do Senhor, as suas maravilhas nas profundezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15725, 'nvi', 'Salmos', 'sl', 107, 25, 'Deus falou e provocou um vendaval que levantava as ondas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15726, 'nvi', 'Salmos', 'sl', 107, 26, 'Subiam aos céus e desciam aos abismos; diante de tal perigo, perderam a coragem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15727, 'nvi', 'Salmos', 'sl', 107, 27, 'Cambaleavam, tontos como bêbados, e toda a sua habilidade foi inútil.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15728, 'nvi', 'Salmos', 'sl', 107, 28, 'Na sua aflição, clamaram ao Senhor, e ele os tirou da tribulação em que se encontravam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15729, 'nvi', 'Salmos', 'sl', 107, 29, 'Reduziu a tempestade a uma brisa e serenou as ondas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15730, 'nvi', 'Salmos', 'sl', 107, 30, 'As ondas sossegaram, ele se alegraram, e Deus os guiou ao porto almejado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15731, 'nvi', 'Salmos', 'sl', 107, 31, 'Que eles dêem graças ao Senhor por seu amor leal e por suas maravilhas em favor dos homens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15732, 'nvi', 'Salmos', 'sl', 107, 32, 'Que o exaltem na assembléia do povo e o louvem na reunião dos líderes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15733, 'nvi', 'Salmos', 'sl', 107, 33, 'Ele transforma os rios em deserto e as fontes em terra seca,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15734, 'nvi', 'Salmos', 'sl', 107, 34, 'faz da terra fértil um solo estéril, por causa da maldade dos seus moradores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15735, 'nvi', 'Salmos', 'sl', 107, 35, 'Transforma o deserto em açudes e a terra ressecada, em fontes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15736, 'nvi', 'Salmos', 'sl', 107, 36, 'Ali ele assenta os famintos, para fundar uma cidade habitável,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15737, 'nvi', 'Salmos', 'sl', 107, 37, 'semear lavouras, plantar vinhas e colher uma grande safra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15738, 'nvi', 'Salmos', 'sl', 107, 38, 'Ele os abençoa, e eles se multiplicam; e não deixa que diminuam os seus rebanhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15739, 'nvi', 'Salmos', 'sl', 107, 39, 'Quando, porém, reduzidos, são humilhados com opressão, desgraça e tristeza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15740, 'nvi', 'Salmos', 'sl', 107, 40, 'Deus derrama desprezo sobre os nobres e os faz vagar num deserto sem caminhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15741, 'nvi', 'Salmos', 'sl', 107, 41, 'Mas tira os pobres da miséria e aumenta as suas famílias como rebanhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15742, 'nvi', 'Salmos', 'sl', 107, 42, 'Os justos vêem tudo isso e se alegram, mas todos os perversos se calam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15743, 'nvi', 'Salmos', 'sl', 107, 43, 'Reflitam nisso os sábios e considerem a bondade do Senhor.');
