-- Inserções para Salmos 37
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14452, 'nvi', 'Salmos', 'sl', 37, 1, 'Não se aborreça por causa dos homens maus e não tenha inveja dos perversos;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14453, 'nvi', 'Salmos', 'sl', 37, 2, 'pois como o capim logo secarão, como a relva verde logo murcharão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14454, 'nvi', 'Salmos', 'sl', 37, 3, 'Confie no Senhor e faça o bem; assim você habitará na terra e desfrutará segurança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14455, 'nvi', 'Salmos', 'sl', 37, 4, 'Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14456, 'nvi', 'Salmos', 'sl', 37, 5, 'Entregue o seu caminho ao Senhor; confie nele, e ele agirá:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14457, 'nvi', 'Salmos', 'sl', 37, 6, 'Ele deixará claro como a alvorada que você é justo, e como o sol do meio-dia que você é inocente.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14458, 'nvi', 'Salmos', 'sl', 37, 7, 'Descanse no Senhor e aguarde por ele com paciência; não se aborreça com o sucesso dos outros, nem com aqueles que maquinam o mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14459, 'nvi', 'Salmos', 'sl', 37, 8, 'Evite a ira e rejeite a fúria; não se irrite: isso só leva ao mal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14460, 'nvi', 'Salmos', 'sl', 37, 9, 'Pois os maus serão eliminados, mas os que esperam no Senhor receberão a terra por herança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14461, 'nvi', 'Salmos', 'sl', 37, 10, 'Um pouco de tempo, e os ímpios não mais existirão; por mais que os procure, não serão encontrados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14462, 'nvi', 'Salmos', 'sl', 37, 11, 'Mas os humildes receberão a terra por herança e desfrutarão pleno bem-estar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14463, 'nvi', 'Salmos', 'sl', 37, 12, 'Os ímpios tramam contra os justos e rosnam contra eles;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14464, 'nvi', 'Salmos', 'sl', 37, 13, 'o Senhor, porém, ri dos ímpios, pois sabe que o dia deles está chegando.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14465, 'nvi', 'Salmos', 'sl', 37, 14, 'Os ímpios desembainham a espada e preparam o arco para abaterem o necessitado e o pobre, para matarem os que andam na retidão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14466, 'nvi', 'Salmos', 'sl', 37, 15, 'Mas as suas espadas lhes atravessará o coração, e os seus arcos serão quebrados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14467, 'nvi', 'Salmos', 'sl', 37, 16, 'Melhor é o pouco do justo do que a riqueza de muitos ímpios;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14468, 'nvi', 'Salmos', 'sl', 37, 17, 'pois o braço forte dos ímpios será quebrado, mas o Senhor sustém os justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14469, 'nvi', 'Salmos', 'sl', 37, 18, 'O Senhor cuida da vida dos íntegros, e a herança deles permanecerá para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14470, 'nvi', 'Salmos', 'sl', 37, 19, 'Em tempos de adversidade não ficarão decepcionados; em dias de fome desfrutarão fartura.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14471, 'nvi', 'Salmos', 'sl', 37, 20, 'Mas os ímpios perecerão; Os inimigos do Senhor murcharão como a beleza dos campos; desvanecerão como fumaça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14472, 'nvi', 'Salmos', 'sl', 37, 21, 'Os ímpios tomam emprestado e não devolvem, mas os justos dão com generosidade;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14473, 'nvi', 'Salmos', 'sl', 37, 22, 'aqueles que o Senhor abençoa receberão a terra por herança, mas os que ele amaldiçoa serão eliminados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14474, 'nvi', 'Salmos', 'sl', 37, 23, 'O Senhor firma os passos de um homem, quando a conduta deste o agrada;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14475, 'nvi', 'Salmos', 'sl', 37, 24, 'ainda que tropece, não cairá, pois o Senhor o toma pela mão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14476, 'nvi', 'Salmos', 'sl', 37, 25, 'Já fui jovem e agora sou velho, mas nunca vi o justo desamparado, nem seus filhos mendigando o pão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14477, 'nvi', 'Salmos', 'sl', 37, 26, 'Ele é sempre generoso e empresta com boa vontade; seus filhos serão abençoados.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14478, 'nvi', 'Salmos', 'sl', 37, 27, 'Desvie-se do mal e faça o bem; e você terá sempre onde morar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14479, 'nvi', 'Salmos', 'sl', 37, 28, 'Pois o Senhor ama quem pratica a justiça, e não abandonará os seus fiéis. Para sempre serão protegidos, mas a descendência dos ímpios será eliminada;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14480, 'nvi', 'Salmos', 'sl', 37, 29, 'os justos herdarão a terra e nela habitarão para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14481, 'nvi', 'Salmos', 'sl', 37, 30, 'A boca do justo profere sabedoria, e a sua língua fala conforme a justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14482, 'nvi', 'Salmos', 'sl', 37, 31, 'Ele traz no coração a lei do seu Deus; nunca pisará em falso.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14483, 'nvi', 'Salmos', 'sl', 37, 32, 'O ímpio fica à espreita do justo, querendo matá-lo;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14484, 'nvi', 'Salmos', 'sl', 37, 33, 'mas o Senhor não o deixará cair em suas mãos, nem permitirá que o condenem quando julgado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14485, 'nvi', 'Salmos', 'sl', 37, 34, 'Espere no Senhor e siga a sua vontade. Ele o exaltará, dando-lhe a terra por herança; quando os ímpios forem eliminados, você o verá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14486, 'nvi', 'Salmos', 'sl', 37, 35, 'Vi um homem ímpio e cruel florescendo como frondosa árvore nativa,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14487, 'nvi', 'Salmos', 'sl', 37, 36, 'mas logo desapareceu e não mais existia; embora eu o procurasse, não pôde ser encontrado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14488, 'nvi', 'Salmos', 'sl', 37, 37, 'Considere o íntegro, observe o justo; há futuro para o homem de paz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14489, 'nvi', 'Salmos', 'sl', 37, 38, 'Mas todos os rebeldes serão destruídos; futuro para os ímpios, nunca haverá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14490, 'nvi', 'Salmos', 'sl', 37, 39, 'Do Senhor vem a salvação dos justos; ele é a sua fortaleza na hora da adversidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14491, 'nvi', 'Salmos', 'sl', 37, 40, 'O Senhor os ajuda e os livra; ele os livra dos ímpios e os salva, porque nele se refugiam.');
