-- Inserções para Salmos 27
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14287, 'nvi', 'Salmos', 'sl', 27, 1, 'O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é o meu forte refúgio; de quem terei medo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14288, 'nvi', 'Salmos', 'sl', 27, 2, 'Quando homens maus avançarem contra mim para destruir-me, eles, meus inimigos e meus adversários, é que tropeçarão e cairão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14289, 'nvi', 'Salmos', 'sl', 27, 3, 'Ainda que um exército se acampe contra mim, meu coração não temerá; ainda que se declare guerra contra mim, mesmo assim estarei confiante.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14290, 'nvi', 'Salmos', 'sl', 27, 4, 'Uma coisa pedi ao Senhor, é o que procuro: que eu possa viver na casa do Senhor todos os dias da minha vida, para contemplar a bondade do Senhor e buscar sua orientação no seu templo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14291, 'nvi', 'Salmos', 'sl', 27, 5, 'Pois no dia da adversidade ele me guardará protegido em sua habitação; no seu tabernáculo me esconderá e me porá em segurança sobre um rochedo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14292, 'nvi', 'Salmos', 'sl', 27, 6, 'Então triunfarei sobre os inimigos que me cercam. Em seu tabernáculo oferecerei sacrifícios com aclamações; cantarei e louvarei ao Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14293, 'nvi', 'Salmos', 'sl', 27, 7, 'Ouve a minha voz quando clamo, ó Senhor; tem misericórdia de mim e responde-me.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14294, 'nvi', 'Salmos', 'sl', 27, 8, 'A teu respeito diz o meu coração: "Busque a minha face! " A tua face, Senhor, buscarei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14295, 'nvi', 'Salmos', 'sl', 27, 9, 'Não escondas de mim a tua face, não rejeites com ira o teu servo; tu tens sido o meu ajudador. Não me desampares nem me abandones, ó Deus, meu salvador!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14296, 'nvi', 'Salmos', 'sl', 27, 10, 'Ainda que me abandonem pai e mãe, o Senhor me acolherá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14297, 'nvi', 'Salmos', 'sl', 27, 11, 'Ensina-me o teu caminho, Senhor; conduze-me por uma vereda segura por causa dos meus inimigos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14298, 'nvi', 'Salmos', 'sl', 27, 12, 'Não me entregues ao capricho dos meus adversários, pois testemunhas falsas se levantam contra mim, respirando violência.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14299, 'nvi', 'Salmos', 'sl', 27, 13, 'Apesar disso, esta certeza eu tenho: viverei até ver a bondade do Senhor na terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14300, 'nvi', 'Salmos', 'sl', 27, 14, 'Espere no Senhor. Seja forte! Coragem! Espere no Senhor.');
