-- Inserções para Salmos 119
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15900, 'nvi', 'Salmos', 'sl', 119, 1, 'Como são felizes os que andam em caminhos irrepreensíveis, que vivem conforme a lei do Senhor!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15901, 'nvi', 'Salmos', 'sl', 119, 2, 'Como são felizes os que obedecem aos seus estatutos e de todo o coração o buscam!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15902, 'nvi', 'Salmos', 'sl', 119, 3, 'Não praticam o mal e andam nos caminhos do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15903, 'nvi', 'Salmos', 'sl', 119, 4, 'Tu mesmo ordenaste os teus preceitos para que sejam fielmente obedecidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15904, 'nvi', 'Salmos', 'sl', 119, 5, 'Quem dera fossem firmados os meus caminhos na obediência aos teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15905, 'nvi', 'Salmos', 'sl', 119, 6, 'Então não ficaria decepcionado ao considerar todos os teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15906, 'nvi', 'Salmos', 'sl', 119, 7, 'Eu te louvarei de coração sincero quando aprender as tuas justas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15907, 'nvi', 'Salmos', 'sl', 119, 8, 'Obedecerei aos teus decretos; nunca me abandones.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15908, 'nvi', 'Salmos', 'sl', 119, 9, 'Como pode o jovem manter pura a sua conduta? Vivendo de acordo com a tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15909, 'nvi', 'Salmos', 'sl', 119, 10, 'Eu te busco de todo o coração; não permitas que eu me desvie dos teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15910, 'nvi', 'Salmos', 'sl', 119, 11, 'Guardei no coração a tua palavra para não pecar contra ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15911, 'nvi', 'Salmos', 'sl', 119, 12, 'Bendito sejas, Senhor! Ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15912, 'nvi', 'Salmos', 'sl', 119, 13, 'Com os lábios repito todas as leis que promulgaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15913, 'nvi', 'Salmos', 'sl', 119, 14, 'Regozijo-me em seguir os teus testemunhos como o que se regozija com grandes riquezas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15914, 'nvi', 'Salmos', 'sl', 119, 15, 'Meditarei nos teus preceitos e darei atenção às tuas veredas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15915, 'nvi', 'Salmos', 'sl', 119, 16, 'Tenho prazer nos teus decretos; não me esqueço da tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15916, 'nvi', 'Salmos', 'sl', 119, 17, 'Trata com bondade o teu servo para que eu viva e obedeça à tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15917, 'nvi', 'Salmos', 'sl', 119, 18, 'Abre os meus olhos para que eu veja as maravilhas da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15918, 'nvi', 'Salmos', 'sl', 119, 19, 'Sou peregrino na terra; não escondas de mim os teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15919, 'nvi', 'Salmos', 'sl', 119, 20, 'A minha alma consome-se de perene desejo das tuas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15920, 'nvi', 'Salmos', 'sl', 119, 21, 'Tu repreendes os arrogantes; malditos os que se desviam dos teus mandamentos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15921, 'nvi', 'Salmos', 'sl', 119, 22, 'Tira de mim a afronta e o desprezo, pois obedeço aos teus estatutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15922, 'nvi', 'Salmos', 'sl', 119, 23, 'Mesmo que os poderosos se reúnam para conspirar contra mim, ainda assim o teu servo meditará nos teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15923, 'nvi', 'Salmos', 'sl', 119, 24, 'Sim, os teus testemunhos são o meu prazer; eles são os meus conselheiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15924, 'nvi', 'Salmos', 'sl', 119, 25, 'Agora estou prostrado no pó; preserva a minha vida conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15925, 'nvi', 'Salmos', 'sl', 119, 26, 'A ti relatei os meus caminhos e tu me respondeste; ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15926, 'nvi', 'Salmos', 'sl', 119, 27, 'Faze-me discernir o propósito dos teus preceitos, então meditarei nas tuas maravilhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15927, 'nvi', 'Salmos', 'sl', 119, 28, 'A minha alma se consome de tristeza; fortalece-me conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15928, 'nvi', 'Salmos', 'sl', 119, 29, 'Desvia-me dos caminhos enganosos; por tua graça, ensina-me a tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15929, 'nvi', 'Salmos', 'sl', 119, 30, 'Escolhi o caminho da fidelidade; decidi seguir as tuas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15930, 'nvi', 'Salmos', 'sl', 119, 31, 'Apego-me aos teus testemunhos, ó Senhor; não permitas que eu fique decepcionado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15931, 'nvi', 'Salmos', 'sl', 119, 32, 'Corro pelo caminho que os teus mandamentos apontam, pois me deste maior entendimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15932, 'nvi', 'Salmos', 'sl', 119, 33, 'Ensina-me, Senhor, o caminho dos teus decretos, e a eles obedecerei até o fim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15933, 'nvi', 'Salmos', 'sl', 119, 34, 'Dá-me entendimento, para que eu guarde a tua lei e a ela obedeça de todo o coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15934, 'nvi', 'Salmos', 'sl', 119, 35, 'Dirige-me pelo caminho dos teus mandamentos, pois nele encontro satisfação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15935, 'nvi', 'Salmos', 'sl', 119, 36, 'Inclina o meu coração para os teus estatutos, e não para a ganância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15936, 'nvi', 'Salmos', 'sl', 119, 37, 'Desvia os meus olhos das coisas inúteis; faze-me viver nos caminhos que traçaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15937, 'nvi', 'Salmos', 'sl', 119, 38, 'Cumpre a tua promessa para com o teu servo, para que sejas temido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15938, 'nvi', 'Salmos', 'sl', 119, 39, 'Livra-me da afronta que me apavora, pois as tuas ordenanças são boas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15939, 'nvi', 'Salmos', 'sl', 119, 40, 'Como anseio pelos teus preceitos! Preserva a minha vida por tua justiça!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15940, 'nvi', 'Salmos', 'sl', 119, 41, 'Que o teu amor alcance-me, Senhor, e a tua salvação, segundo a tua promessa;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15941, 'nvi', 'Salmos', 'sl', 119, 42, 'então responderei aos que me afrontam, pois confio na tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15942, 'nvi', 'Salmos', 'sl', 119, 43, 'Jamais tires da minha boca a palavra da verdade, pois nas tuas ordenanças coloquei a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15943, 'nvi', 'Salmos', 'sl', 119, 44, 'Obedecerei constantemente à tua lei, para todo o sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15944, 'nvi', 'Salmos', 'sl', 119, 45, 'Andarei em verdadeira liberdade, pois tenho buscado os teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15945, 'nvi', 'Salmos', 'sl', 119, 46, 'Falarei dos teus testemunhos diante de reis, sem ser envergonhado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15946, 'nvi', 'Salmos', 'sl', 119, 47, 'Tenho prazer nos teus mandamentos; eu os amo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15947, 'nvi', 'Salmos', 'sl', 119, 48, 'A ti levanto minhas mãos e medito nos teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15948, 'nvi', 'Salmos', 'sl', 119, 49, 'Lembra-te da tua palavra ao teu servo, pela qual me deste esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15949, 'nvi', 'Salmos', 'sl', 119, 50, 'Este é o meu consolo no meu sofrimento: A tua promessa dá-me vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15950, 'nvi', 'Salmos', 'sl', 119, 51, 'Os arrogantes zombam de mim o tempo todo, mas eu não me desvio da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15951, 'nvi', 'Salmos', 'sl', 119, 52, 'Lembro-me, Senhor, das tuas ordenanças do passado e nelas acho consolo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15952, 'nvi', 'Salmos', 'sl', 119, 53, 'Fui tomado de ira tremenda por causa dos ímpios que rejeitaram a tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15953, 'nvi', 'Salmos', 'sl', 119, 54, 'Os teus decretos são o tema da minha canção em minha peregrinação.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15954, 'nvi', 'Salmos', 'sl', 119, 55, 'De noite lembro-me do teu nome, Senhor! Vou obedecer à tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15955, 'nvi', 'Salmos', 'sl', 119, 56, 'Esta tem sido a minha prática: Obedecer aos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15956, 'nvi', 'Salmos', 'sl', 119, 57, 'Tu és a minha herança, Senhor; prometi obedecer às tuas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15957, 'nvi', 'Salmos', 'sl', 119, 58, 'De todo o coração suplico a tua graça; tem misericórdia de mim, conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15958, 'nvi', 'Salmos', 'sl', 119, 59, 'Refleti em meus caminhos e voltei os meus passos para os teus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15959, 'nvi', 'Salmos', 'sl', 119, 60, 'Eu me apressarei e não hesitarei em obedecer aos teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15960, 'nvi', 'Salmos', 'sl', 119, 61, 'Embora as cordas dos ímpios queiram prender-me, eu não me esqueço da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15961, 'nvi', 'Salmos', 'sl', 119, 62, 'À meia-noite me levanto para dar-te graças pelas tuas justas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15962, 'nvi', 'Salmos', 'sl', 119, 63, 'Sou amigo de todos os que te temem e obedecem aos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15963, 'nvi', 'Salmos', 'sl', 119, 64, 'A terra está cheia do teu amor, Senhor; ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15964, 'nvi', 'Salmos', 'sl', 119, 65, 'Trata com bondade o teu servo, Senhor, conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15965, 'nvi', 'Salmos', 'sl', 119, 66, 'Ensina-me o bom senso e o conhecimento, pois confio em teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15966, 'nvi', 'Salmos', 'sl', 119, 67, 'Antes de ser castigado, eu andava desviado, mas agora obedeço à tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15967, 'nvi', 'Salmos', 'sl', 119, 68, 'Tu és bom, e o que fazes é bom; ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15968, 'nvi', 'Salmos', 'sl', 119, 69, 'Os arrogantes mancharam o meu nome com mentiras, mas eu obedeço aos teus preceitos de todo o coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15969, 'nvi', 'Salmos', 'sl', 119, 70, 'O coração deles é insensível, eu, porém, tenho prazer na tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15970, 'nvi', 'Salmos', 'sl', 119, 71, 'Foi bom para mim ter sido castigado, para que aprendesse os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15971, 'nvi', 'Salmos', 'sl', 119, 72, 'Para mim vale mais a lei que decretaste do que milhares de peças de prata e ouro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15972, 'nvi', 'Salmos', 'sl', 119, 73, 'As tuas mãos me fizeram e me formaram; dá-me entendimento para aprender os teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15973, 'nvi', 'Salmos', 'sl', 119, 74, 'Quando os que têm temor de ti me virem, se alegrarão, pois na tua palavra coloquei a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15974, 'nvi', 'Salmos', 'sl', 119, 75, 'Sei, Senhor, que as tuas ordenanças são justas, e que por tua fidelidade me castigaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15975, 'nvi', 'Salmos', 'sl', 119, 76, 'Seja o teu amor o meu consolo, conforme a tua promessa ao teu servo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15976, 'nvi', 'Salmos', 'sl', 119, 77, 'Alcance-me a tua misericórdia para que eu tenha vida, porque a tua lei é o meu prazer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15977, 'nvi', 'Salmos', 'sl', 119, 78, 'Sejam humilhados os arrogantes, pois prejudicaram-me sem motivo; mas eu meditarei nos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15978, 'nvi', 'Salmos', 'sl', 119, 79, 'Venham apoiar-me aqueles que te temem, aqueles que entendem os teus estatutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15979, 'nvi', 'Salmos', 'sl', 119, 80, 'Seja o meu coração íntegro para com os teus decretos, para que eu não seja humilhado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15980, 'nvi', 'Salmos', 'sl', 119, 81, 'Estou quase desfalecido, aguardando a tua salvação, mas na tua palavra coloquei a esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15981, 'nvi', 'Salmos', 'sl', 119, 82, 'Os meus olhos fraquejam de tanto esperar pela tua promessa, e pergunto: "Quando me consolarás? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15982, 'nvi', 'Salmos', 'sl', 119, 83, 'Embora eu seja como uma vasilha inútil, não me esqueço dos teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15983, 'nvi', 'Salmos', 'sl', 119, 84, 'Até quando o teu servo deverá esperar para que castigues os meus perseguidores?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15984, 'nvi', 'Salmos', 'sl', 119, 85, 'Cavaram uma armadilha contra mim os arrogantes, os que não seguem a tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15985, 'nvi', 'Salmos', 'sl', 119, 86, 'Todos os teus mandamentos merecem confiança; ajuda-me, pois sou perseguido com mentiras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15986, 'nvi', 'Salmos', 'sl', 119, 87, 'Quase acabaram com a minha vida na terra, mas não abandonei os teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15987, 'nvi', 'Salmos', 'sl', 119, 88, 'Preserva a minha vida pelo teu amor, e obedecerei aos estatutos que decretaste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15988, 'nvi', 'Salmos', 'sl', 119, 89, 'A tua palavra, Senhor, para sempre está firmada nos céus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15989, 'nvi', 'Salmos', 'sl', 119, 90, 'A tua fidelidade é constante por todas as gerações; estabeleceste a terra, que firme subsiste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15990, 'nvi', 'Salmos', 'sl', 119, 91, 'Conforme as tuas ordens, tudo permanece até hoje, pois não há nada que não esteja a teu serviço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15991, 'nvi', 'Salmos', 'sl', 119, 92, 'Se a tua lei não fosse o meu prazer, o sofrimento já me teria destruído.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15992, 'nvi', 'Salmos', 'sl', 119, 93, 'Jamais me esquecerei dos teus preceitos, pois é por meio deles que preservas a minha vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15993, 'nvi', 'Salmos', 'sl', 119, 94, 'Salva-me, pois a ti pertenço e busco os teus preceitos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15994, 'nvi', 'Salmos', 'sl', 119, 95, 'Os ímpios estão à espera para destruir-me, mas eu considero os teus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15995, 'nvi', 'Salmos', 'sl', 119, 96, 'Tenho constatado que toda perfeição tem limite; mas não há limite para o teu mandamento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15996, 'nvi', 'Salmos', 'sl', 119, 97, 'Como eu amo a tua lei! Medito nela o dia inteiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15997, 'nvi', 'Salmos', 'sl', 119, 98, 'Os teus mandamentos me tornam mais sábio que os meus inimigos, porquanto estão sempre comigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15998, 'nvi', 'Salmos', 'sl', 119, 99, 'Tenho mais discernimento que todos os meus mestres, pois medito nos teus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15999, 'nvi', 'Salmos', 'sl', 119, 100, 'Tenho mais entendimento que os anciãos, pois obedeço aos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16000, 'nvi', 'Salmos', 'sl', 119, 101, 'Afasto os pés de todo caminho mau para obedecer à tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16001, 'nvi', 'Salmos', 'sl', 119, 102, 'Não me afasto das tuas ordenanças, pois tu mesmo me ensinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16002, 'nvi', 'Salmos', 'sl', 119, 103, 'Como são doces para o meu paladar as tuas palavras! Mais do que o mel para a minha boca!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16003, 'nvi', 'Salmos', 'sl', 119, 104, 'Ganho entendimento por meio dos teus preceitos; por isso odeio todo caminho de falsidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16004, 'nvi', 'Salmos', 'sl', 119, 105, 'A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16005, 'nvi', 'Salmos', 'sl', 119, 106, 'Prometi sob juramento e o cumprirei: vou obedecer às tuas justas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16006, 'nvi', 'Salmos', 'sl', 119, 107, 'Passei por muito sofrimento; preserva, Senhor, a minha vida, conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16007, 'nvi', 'Salmos', 'sl', 119, 108, 'Aceita, Senhor, a minha oferta de louvor dos meus lábios, e ensina-me as tuas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16008, 'nvi', 'Salmos', 'sl', 119, 109, 'A minha vida está sempre em perigo, mas não me esqueço da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16009, 'nvi', 'Salmos', 'sl', 119, 110, 'Os ímpios prepararam uma armadilha contra mim, mas não me desviei dos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16010, 'nvi', 'Salmos', 'sl', 119, 111, 'Os teus testemunhos são a minha herança permanente; são a alegria do meu coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16011, 'nvi', 'Salmos', 'sl', 119, 112, 'Dispus o meu coração para cumprir os teus decretos até o fim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16012, 'nvi', 'Salmos', 'sl', 119, 113, 'Odeio os que são inconstantes, mas amo a tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16013, 'nvi', 'Salmos', 'sl', 119, 114, 'Tu és o meu abrigo e o meu escudo; e na tua palavra coloquei a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16014, 'nvi', 'Salmos', 'sl', 119, 115, 'Afastem-se de mim os que praticam o mal! Quero obedecer aos mandamentos do meu Deus!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16015, 'nvi', 'Salmos', 'sl', 119, 116, 'Sustenta-me, segundo a tua promessa, e eu viverei; não permitas que se frustrem as minhas esperanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16016, 'nvi', 'Salmos', 'sl', 119, 117, 'Ampara-me, e estarei seguro; sempre estarei atento aos teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16017, 'nvi', 'Salmos', 'sl', 119, 118, 'Tu rejeitas todos os que se desviam dos teus decretos, pois os seus planos enganosos são inúteis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16018, 'nvi', 'Salmos', 'sl', 119, 119, 'Tu destróis como refugo todos os ímpios da terra; por isso amo os teus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16019, 'nvi', 'Salmos', 'sl', 119, 120, 'O meu corpo estremece diante de ti; as tuas ordenanças enchem-me de temor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16020, 'nvi', 'Salmos', 'sl', 119, 121, 'Tenho vivido com justiça e retidão; não me abandones nas mãos dos meus opressores.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16021, 'nvi', 'Salmos', 'sl', 119, 122, 'Garante o bem-estar do teu servo; não permitas que os arrogantes me oprimam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16022, 'nvi', 'Salmos', 'sl', 119, 123, 'Os meus olhos fraquejam, aguardando a tua salvação e o cumprimento da tua justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16023, 'nvi', 'Salmos', 'sl', 119, 124, 'Trata o teu servo conforme o teu amor leal e ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16024, 'nvi', 'Salmos', 'sl', 119, 125, 'Sou teu servo; dá-me discernimento para compreender os teus testemunhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16025, 'nvi', 'Salmos', 'sl', 119, 126, 'Já é tempo de agires, Senhor, pois a tua lei está sendo desrespeitada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16026, 'nvi', 'Salmos', 'sl', 119, 127, 'Eu amo os teus mandamentos mais do que o ouro, mais do que o ouro puro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16027, 'nvi', 'Salmos', 'sl', 119, 128, 'Por isso considero justos os teus preceitos e odeio todo caminho de falsidade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16028, 'nvi', 'Salmos', 'sl', 119, 129, 'Os teus testemunhos são maravilhosos; por isso lhes obedeço.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16029, 'nvi', 'Salmos', 'sl', 119, 130, 'A explicação das tuas palavras ilumina e dá discernimento aos inexperientes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16030, 'nvi', 'Salmos', 'sl', 119, 131, 'Abro a boca e suspiro, ansiando por teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16031, 'nvi', 'Salmos', 'sl', 119, 132, 'Volta-te para mim e tem misericórdia de mim, como sempre fazes aos que amam o teu nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16032, 'nvi', 'Salmos', 'sl', 119, 133, 'Dirige os meus passos, conforme a tua palavra; não permitas que nenhum pecado me domine.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16033, 'nvi', 'Salmos', 'sl', 119, 134, 'Resgata-me da opressão dos homens, para que eu obedeça aos teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16034, 'nvi', 'Salmos', 'sl', 119, 135, 'Faze o teu rosto resplandecer sobre o teu servo, e ensina-me os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16035, 'nvi', 'Salmos', 'sl', 119, 136, 'Rios de lágrimas correm dos meus olhos, porque a tua lei não é obedecida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16036, 'nvi', 'Salmos', 'sl', 119, 137, 'Justo és, Senhor, e retas são as tuas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16037, 'nvi', 'Salmos', 'sl', 119, 138, 'Ordenaste os teus testemunhos com justiça; dignos são de inteira confiança!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16038, 'nvi', 'Salmos', 'sl', 119, 139, 'O meu zelo me consome, pois os meus adversários se esquecem das tuas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16039, 'nvi', 'Salmos', 'sl', 119, 140, 'A tua promessa foi plenamente comprovada, e, por isso, o teu servo a ama.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16040, 'nvi', 'Salmos', 'sl', 119, 141, 'Sou pequeno e desprezado, mas não esqueço os teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16041, 'nvi', 'Salmos', 'sl', 119, 142, 'A tua justiça é eterna, e a tua lei é a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16042, 'nvi', 'Salmos', 'sl', 119, 143, 'Tribulação e angústia me atingiram, mas os teus mandamentos são o meu prazer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16043, 'nvi', 'Salmos', 'sl', 119, 144, 'Os teus testemunhos são eternamente justos, dá-me discernimento para que eu tenha vida.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16044, 'nvi', 'Salmos', 'sl', 119, 145, 'Eu clamo de todo o coração; responde-me, Senhor, e obedecerei aos teus testemunhos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16045, 'nvi', 'Salmos', 'sl', 119, 146, 'Clamo a ti; salva-me, e obedecerei aos teus estatutos!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16046, 'nvi', 'Salmos', 'sl', 119, 147, 'Antes do amanhecer me levanto e suplico o teu socorro; na tua palavra coloquei a minha esperança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16047, 'nvi', 'Salmos', 'sl', 119, 148, 'Fico acordado nas vigílias da noite, para meditar nas tuas promessas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16048, 'nvi', 'Salmos', 'sl', 119, 149, 'Ouve a minha voz pelo teu amor leal; faze-me viver, Senhor, conforme as tuas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16049, 'nvi', 'Salmos', 'sl', 119, 150, 'Os meus perseguidores aproximam-se com más intenções; mas estão distantes da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16050, 'nvi', 'Salmos', 'sl', 119, 151, 'Tu, porém, Senhor, estás perto e todos os teus mandamentos são verdadeiros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16051, 'nvi', 'Salmos', 'sl', 119, 152, 'Há muito aprendi dos teus testemunhos que os estabeleceste para sempre.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16052, 'nvi', 'Salmos', 'sl', 119, 153, 'Olha para o meu sofrimento e livra-me, pois não me esqueço da tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16053, 'nvi', 'Salmos', 'sl', 119, 154, 'Defende a minha causa e resgata-me; preserva a minha vida conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16054, 'nvi', 'Salmos', 'sl', 119, 155, 'A salvação está longe dos ímpios, pois eles não buscam os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16055, 'nvi', 'Salmos', 'sl', 119, 156, 'Grande é a tua compaixão, Senhor; preserva a minha vida conforme as tuas leis.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16056, 'nvi', 'Salmos', 'sl', 119, 157, 'Muitos são os meus adversários e os meus perseguidores, mas eu não me desvio dos teus estatutos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16057, 'nvi', 'Salmos', 'sl', 119, 158, 'Com grande desgosto vejo os infiéis, que não obedecem à tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16058, 'nvi', 'Salmos', 'sl', 119, 159, 'Vê como amo os teus preceitos! Dá-me vida, segundo o teu amor leal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16059, 'nvi', 'Salmos', 'sl', 119, 160, 'A verdade é a essência da tua palavra, e todas as tuas justas ordenanças são eternas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16060, 'nvi', 'Salmos', 'sl', 119, 161, 'Os poderosos perseguem-me sem motivo, mas é diante da tua palavra que o meu coração treme.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16061, 'nvi', 'Salmos', 'sl', 119, 162, 'Eu me regozijo na tua promessa como alguém que encontra grandes despojos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16062, 'nvi', 'Salmos', 'sl', 119, 163, 'Odeio e detesto a falsidade, mas amo a tua lei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16063, 'nvi', 'Salmos', 'sl', 119, 164, 'Sete vezes por dia eu te louvo por causa das tuas justas ordenanças.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16064, 'nvi', 'Salmos', 'sl', 119, 165, 'Os que amam a tua lei desfrutam paz, e nada há que os faça tropeçar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16065, 'nvi', 'Salmos', 'sl', 119, 166, 'Aguardo a tua salvação, Senhor, e pratico os teus mandamentos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16066, 'nvi', 'Salmos', 'sl', 119, 167, 'Obedeço aos teus testemunhos; amo-os infinitamente!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16067, 'nvi', 'Salmos', 'sl', 119, 168, 'Obedeço a todos os teus preceitos e testemunhos, pois conheces todos os meus caminhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16068, 'nvi', 'Salmos', 'sl', 119, 169, 'Chegue à tua presença o meu clamor, Senhor! Dá-me entendimento conforme a tua palavra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16069, 'nvi', 'Salmos', 'sl', 119, 170, 'Chegue a ti a minha súplica. Livra-me, conforme a tua promessa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16070, 'nvi', 'Salmos', 'sl', 119, 171, 'Meus lábios transbordarão de louvor, pois me ensinas os teus decretos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16071, 'nvi', 'Salmos', 'sl', 119, 172, 'A minha língua cantará a tua palavra, pois todos os teus mandamentos são justos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16072, 'nvi', 'Salmos', 'sl', 119, 173, 'Com tua mão vem ajudar-me, pois escolhi os teus preceitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16073, 'nvi', 'Salmos', 'sl', 119, 174, 'Anseio pela tua salvação, Senhor, e a tua lei é o meu prazer.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16074, 'nvi', 'Salmos', 'sl', 119, 175, 'Permite-me viver para que eu te louve; e que as tuas ordenanças me sustentem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16075, 'nvi', 'Salmos', 'sl', 119, 176, 'Andei vagando como ovelha perdida; vem em busca do teu servo, pois não me esqueci dos teus mandamentos.');
