-- Inserções para Salmos 105
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15608, 'nvi', 'Salmos', 'sl', 105, 1, 'Dêem graças ao Senhor, proclamem o seu nome; divulguem os seus feitos entre as nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15609, 'nvi', 'Salmos', 'sl', 105, 2, 'Cantem para ele e louvem-no; relatem todas as suas maravilhas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15610, 'nvi', 'Salmos', 'sl', 105, 3, 'Gloriem-se no seu santo nome; alegre-se o coração dos que buscam o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15611, 'nvi', 'Salmos', 'sl', 105, 4, 'Recorram ao Senhor e ao seu poder; busquem sempre a sua presença.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15612, 'nvi', 'Salmos', 'sl', 105, 5, 'Lembrem-se das maravilhas que ele fez, dos seus prodígios e das sentenças de juízo que pronunciou,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15613, 'nvi', 'Salmos', 'sl', 105, 6, 'ó descendentes de Abraão, seu servo, ó filhos de Jacó, seus escolhidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15614, 'nvi', 'Salmos', 'sl', 105, 7, 'Ele é o Senhor, o nosso Deus; seus decretos são para toda a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15615, 'nvi', 'Salmos', 'sl', 105, 8, 'Ele se lembra para sempre da sua aliança, por mil gerações, da palavra que ordenou,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15616, 'nvi', 'Salmos', 'sl', 105, 9, 'da aliança que fez com Abraão, do juramento que fez a Isaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15617, 'nvi', 'Salmos', 'sl', 105, 10, 'Ele o confirmou como decreto a Jacó, a Israel como aliança eterna, quando disse:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15618, 'nvi', 'Salmos', 'sl', 105, 11, '"Darei a você a terra de Canaã, a herança que lhe pertence".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15619, 'nvi', 'Salmos', 'sl', 105, 12, 'Quando ainda eram poucos, um punhado de peregrinos na terra,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15620, 'nvi', 'Salmos', 'sl', 105, 13, 'e vagueavam de nação em nação, de um reino a outro,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15621, 'nvi', 'Salmos', 'sl', 105, 14, 'ele não permitiu que ninguém os oprimisse, mas a favor deles repreendeu reis, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15622, 'nvi', 'Salmos', 'sl', 105, 15, '"Não toquem nos meus ungidos; não maltratem os meus profetas".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15623, 'nvi', 'Salmos', 'sl', 105, 16, 'Ele mandou vir fome sobre a terra e destruiu todo o seu sustento;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15624, 'nvi', 'Salmos', 'sl', 105, 17, 'mas enviou um homem adiante deles, José, que foi vendido como escravo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15625, 'nvi', 'Salmos', 'sl', 105, 18, 'Machucaram-lhe os pés com correntes e com ferros prenderam-lhe o pescoço,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15626, 'nvi', 'Salmos', 'sl', 105, 19, 'até cumprir-se a sua predição, e a palavra do Senhor confirmar o que dissera.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15627, 'nvi', 'Salmos', 'sl', 105, 20, 'O rei mandou soltá-lo, o governante dos povos o libertou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15628, 'nvi', 'Salmos', 'sl', 105, 21, 'Ele o constituiu senhor de seu palácio e administrador de todos os seus bens,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15629, 'nvi', 'Salmos', 'sl', 105, 22, 'para instruir os seus oficiais como desejasse e ensinar a sabedoria às autoridades do rei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15630, 'nvi', 'Salmos', 'sl', 105, 23, 'Então Israel foi para o Egito, Jacó viveu como estrangeiro na terra de Cam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15631, 'nvi', 'Salmos', 'sl', 105, 24, 'Deus fez proliferar o seu povo, tornou-o mais poderoso do que os seus adversários,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15632, 'nvi', 'Salmos', 'sl', 105, 25, 'e mudou o coração deles para que odiassem o seu povo, para que tramassem contra os seus servos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15633, 'nvi', 'Salmos', 'sl', 105, 26, 'Então enviou seu servo Moisés, e Arão, a quem tinha escolhido,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15634, 'nvi', 'Salmos', 'sl', 105, 27, 'por meio dos quais realizou os seus sinais miraculosos e as suas maravilhas na terra de Cam.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15635, 'nvi', 'Salmos', 'sl', 105, 28, 'Ele enviou trevas, e houve trevas, e eles não se rebelaram contra as suas palavras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15636, 'nvi', 'Salmos', 'sl', 105, 29, 'Ele transformou as águas deles em sangue, causando a morte dos seus peixes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15637, 'nvi', 'Salmos', 'sl', 105, 30, 'A terra deles ficou infestada de rãs, até mesmo os aposentos reais.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15638, 'nvi', 'Salmos', 'sl', 105, 31, 'Ele ordenou, e enxames de moscas e piolhos invadiram o território deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15639, 'nvi', 'Salmos', 'sl', 105, 32, 'Deu-lhes granizo, em vez de chuva, e raios flamejantes por toda a terra deles;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15640, 'nvi', 'Salmos', 'sl', 105, 33, 'arrasou as suas videiras e figueiras e destruiu as árvores do seu território.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15641, 'nvi', 'Salmos', 'sl', 105, 34, 'Ordenou, e vieram enxames de gafanhotos, gafanhotos inumeráveis,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15642, 'nvi', 'Salmos', 'sl', 105, 35, 'e devoraram toda a vegetação daquela terra, e consumiram tudo o que a lavoura produziu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15643, 'nvi', 'Salmos', 'sl', 105, 36, 'Depois matou todos os primogênitos da terra deles, todas as primícias da virilidade deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15644, 'nvi', 'Salmos', 'sl', 105, 37, 'Ele tirou de lá Israel, que saiu cheio de prata e ouro. Não havia em suas tribos quem fraquejasse.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15645, 'nvi', 'Salmos', 'sl', 105, 38, 'Os egípcios alegraram-se quando eles saíram, pois estavam com verdadeiro pavor dos israelitas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15646, 'nvi', 'Salmos', 'sl', 105, 39, 'Ele estendeu uma nuvem para lhes dar sombra, e fogo para iluminar a noite.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15647, 'nvi', 'Salmos', 'sl', 105, 40, 'Pediram, e ele enviou codornizes, e saciou-os com pão do céu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15648, 'nvi', 'Salmos', 'sl', 105, 41, 'Ele fendeu a rocha, e jorrou água, que escorreu como um rio pelo deserto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15649, 'nvi', 'Salmos', 'sl', 105, 42, 'Pois ele se lembrou da santa promessa que fizera ao seu servo Abraão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15650, 'nvi', 'Salmos', 'sl', 105, 43, 'Fez sair cheio de júbilo o seu povo, e os seus escolhidos, com cânticos alegres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15651, 'nvi', 'Salmos', 'sl', 105, 44, 'Deu-lhes as terras das nações, e eles tomaram posse do fruto do trabalho de outros povos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (15652, 'nvi', 'Salmos', 'sl', 105, 45, 'para que obedecessem aos seus decretos e guardassem as suas leis. Aleluia!');
