-- Inserções para Salmos 66
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14875, 'nvi', 'Salmos', 'sl', 66, 1, 'Aclamem a Deus, povos de toda terra!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14876, 'nvi', 'Salmos', 'sl', 66, 2, 'Cantem louvores ao seu glorioso nome; louvem-no gloriosamente!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14877, 'nvi', 'Salmos', 'sl', 66, 3, 'Digam a Deus: "Quão temíveis são os teus feitos! Tão grande é o teu poder que os teus inimigos rastejam diante de ti!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14878, 'nvi', 'Salmos', 'sl', 66, 4, 'Toda a terra te adora e canta louvores a ti, canta louvores ao teu nome". Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14879, 'nvi', 'Salmos', 'sl', 66, 5, 'Venham e vejam o que Deus tem feito; como são impressionantes as suas obras em favor dos homens!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14880, 'nvi', 'Salmos', 'sl', 66, 6, 'Ele transformou o mar em terra seca, e o povo atravessou as águas a pé; e ali nos alegramos nele.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14881, 'nvi', 'Salmos', 'sl', 66, 7, 'Ele governa para sempre com o seu poder, seus olhos vigiam as nações; que os rebeldes não se levantem contra ele! Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14882, 'nvi', 'Salmos', 'sl', 66, 8, 'Bendigam o nosso Deus, ó povos, façam ressoar o som do seu louvor;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14883, 'nvi', 'Salmos', 'sl', 66, 9, 'foi ele quem preservou as nossas vidas impedindo que os nossos pés escorregassem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14884, 'nvi', 'Salmos', 'sl', 66, 10, 'Pois tu, ó Deus, nos submeteste à prova e nos refinaste como a prata.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14885, 'nvi', 'Salmos', 'sl', 66, 11, 'Fizeste-nos cair numa armadilha e sobre nossas costas puseste fardos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14886, 'nvi', 'Salmos', 'sl', 66, 12, 'Deixaste que os inimigos cavalgassem sobre a nossa cabeça; passamos pelo fogo e pela água, mas a um lugar de fartura nos trouxeste.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14887, 'nvi', 'Salmos', 'sl', 66, 13, 'Para o teu templo virei com holocaustos e cumprirei os meus votos para contigo,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14888, 'nvi', 'Salmos', 'sl', 66, 14, 'votos que os meus lábios fizeram e a minha boca falou quando eu estava em dificuldade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14889, 'nvi', 'Salmos', 'sl', 66, 15, 'Oferecerei a ti animais gordos em holocausto; sacrificarei carneiros, cuja fumaça subirá a ti, e também novilhos e cabritos. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14890, 'nvi', 'Salmos', 'sl', 66, 16, 'Venham e ouçam, todos vocês que temem a Deus; vou contar-lhes o que ele fez por mim.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14891, 'nvi', 'Salmos', 'sl', 66, 17, 'A ele clamei com os lábios; com a língua o exaltei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14892, 'nvi', 'Salmos', 'sl', 66, 18, 'Se eu acalentasse o pecado no coração, o Senhor não me ouviria;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14893, 'nvi', 'Salmos', 'sl', 66, 19, 'mas Deus me ouviu, deu atenção à oração que lhe dirigi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (14894, 'nvi', 'Salmos', 'sl', 66, 20, 'Louvado seja Deus, que não rejeitou a minha oração nem afastou de mim o seu amor!');
