-- Inserções para Salmos 147
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16353, 'nvi', 'Salmos', 'sl', 147, 1, 'Aleluia! Como é bom cantar louvores ao nosso Deus! Como é agradável e próprio louvá-lo!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16354, 'nvi', 'Salmos', 'sl', 147, 2, 'O Senhor edifica Jerusalém; ele reúne os exilados de Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16355, 'nvi', 'Salmos', 'sl', 147, 3, 'Só ele cura os de coração quebrantado e cuida das suas feridas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16356, 'nvi', 'Salmos', 'sl', 147, 4, 'Ele determina o número de estrelas e chama cada uma pelo nome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16357, 'nvi', 'Salmos', 'sl', 147, 5, 'Grande é o nosso Soberano e tremendo é o seu poder; é impossível medir o seu entendimento.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16358, 'nvi', 'Salmos', 'sl', 147, 6, 'O Senhor sustém o oprimido, mas lança por terra o ímpio.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16359, 'nvi', 'Salmos', 'sl', 147, 7, 'Cantem ao Senhor com ações de graças; ao som da harpa façam música para o nosso Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16360, 'nvi', 'Salmos', 'sl', 147, 8, 'Ele cobre o céu de nuvens, concede chuvas à terra e faz crescer a relva nas colinas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16361, 'nvi', 'Salmos', 'sl', 147, 9, 'Ele dá alimento aos animais, e aos filhotes dos corvos quando gritam de fome.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16362, 'nvi', 'Salmos', 'sl', 147, 10, 'Não é a força do cavalo que lhe dá satisfação, nem é a agilidade do homem que lhe agrada;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16363, 'nvi', 'Salmos', 'sl', 147, 11, 'o Senhor se agrada dos que o temem, dos que colocam a esperança no seu amor leal.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16364, 'nvi', 'Salmos', 'sl', 147, 12, 'Exalte ao Senhor, ó Jerusalém! Louve o seu Deus, ó Sião,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16365, 'nvi', 'Salmos', 'sl', 147, 13, 'pois ele reforçou as trancas de suas portas e abençoou o seu povo, que lá habita.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16366, 'nvi', 'Salmos', 'sl', 147, 14, 'É ele que mantém as suas fronteiras em segurança e que a supre do melhor do trigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16367, 'nvi', 'Salmos', 'sl', 147, 15, 'Ele envia sua ordem à terra, e sua palavra corre veloz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16368, 'nvi', 'Salmos', 'sl', 147, 16, 'Faz cair a neve como lã, e espalha a geada como cinza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16369, 'nvi', 'Salmos', 'sl', 147, 17, 'Faz cair o gelo como se fosse pedra. Quem pode suportar o seu frio?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16370, 'nvi', 'Salmos', 'sl', 147, 18, 'Ele envia a sua palavra, e o gelo derrete; envia o seu sopro, e as águas tornam a correr.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16371, 'nvi', 'Salmos', 'sl', 147, 19, 'Ele revela a sua palavra a Jacó, os seus decretos e ordenanças a Israel.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16372, 'nvi', 'Salmos', 'sl', 147, 20, 'Ele não fez isso a nenhuma outra nação; todas as outras desconhecem as suas ordenanças. Aleluia!');
