-- Inserções para Salmos 143
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16295, 'nvi', 'Salmos', 'sl', 143, 1, 'Ouve, Senhor, a minha oração, dá ouvidos à minha súplica; responde-me por tua fidelidade e por tua justiça.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16296, 'nvi', 'Salmos', 'sl', 143, 2, 'Mas não leves o teu servo a julgamento, pois ninguém é justo diante de ti.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16297, 'nvi', 'Salmos', 'sl', 143, 3, 'O inimigo persegue-me e esmaga-me ao chão; ele me faz morar nas trevas, como os que há muito morreram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16298, 'nvi', 'Salmos', 'sl', 143, 4, 'O meu espírito se desanima; o meu coração está em pânico.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16299, 'nvi', 'Salmos', 'sl', 143, 5, 'Eu me recordo dos tempos antigos; medito em todas as tuas obras e considero o que as tuas mãos têm feito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16300, 'nvi', 'Salmos', 'sl', 143, 6, 'Estendo as minhas mãos para ti; como a terra árida, tenho sede de ti. Pausa');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16301, 'nvi', 'Salmos', 'sl', 143, 7, 'Apressa-te em responder-me, Senhor! O meu espírito se abate. Não escondas de mim o teu rosto, ou serei como os que descem à cova.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16302, 'nvi', 'Salmos', 'sl', 143, 8, 'Faze-me ouvir do teu amor leal pela manhã, pois em ti confio. Mostra-me o caminho que devo seguir, pois a ti elevo a minha alma.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16303, 'nvi', 'Salmos', 'sl', 143, 9, 'Livra-me dos meus inimigos, Senhor, pois em ti eu me abrigo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16304, 'nvi', 'Salmos', 'sl', 143, 10, 'Ensina-me a fazer a tua vontade, pois tu és o meu Deus; que o teu bondoso Espírito me conduza por terreno plano.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16305, 'nvi', 'Salmos', 'sl', 143, 11, 'Preserva-me a vida, Senhor, por causa do teu nome, por tua justiça, tira-me desta angústia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (16306, 'nvi', 'Salmos', 'sl', 143, 12, 'E no teu amor leal, aniquila os meus inimigos; destrói todos os meus adversários, pois sou teu servo.');
