-- Inserções para Tiago 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30321, 'nvi', 'Tiago', 'tg', 3, 1, 'Meus irmãos, não sejam muitos de vocês mestres, pois vocês sabem que nós, os que ensinamos, seremos julgados com maior rigor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30322, 'nvi', 'Tiago', 'tg', 3, 2, 'Todos tropeçamos de muitas maneiras. Se alguém não tropeça no falar, tal homem é perfeito, sendo também capaz de dominar todo o seu corpo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30323, 'nvi', 'Tiago', 'tg', 3, 3, 'Quando colocamos freios na boca dos cavalos para que eles nos obedeçam, podemos controlar o animal todo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30324, 'nvi', 'Tiago', 'tg', 3, 4, 'Tomem também como exemplo os navios; embora sejam tão grandes e impelidos por fortes ventos, são dirigidos por um leme muito pequeno, conforme a vontade do piloto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30325, 'nvi', 'Tiago', 'tg', 3, 5, 'Semelhantemente, a língua é um pequeno órgão do corpo, mas se vangloria de grandes coisas. Vejam como um grande bosque é incendiado por uma simples fagulha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30326, 'nvi', 'Tiago', 'tg', 3, 6, 'Assim também, a língua é um fogo; é um mundo de iniqüidade. Colocada entre os membros do nosso corpo, contamina a pessoa por inteiro, incendeia todo o curso de sua vida, sendo ela mesma incendiada pelo inferno.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30327, 'nvi', 'Tiago', 'tg', 3, 7, 'Toda espécie de animais, aves, répteis e criaturas do mar doma-se e é domada pela espécie humana;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30328, 'nvi', 'Tiago', 'tg', 3, 8, 'a língua, porém, ninguém consegue domar. É um mal incontrolável, cheio de veneno mortífero.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30329, 'nvi', 'Tiago', 'tg', 3, 9, 'Com a língua bendizemos ao Senhor e Pai, e com ela amaldiçoamos os homens, feitos à semelhança de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30330, 'nvi', 'Tiago', 'tg', 3, 10, 'Da mesma boca procedem bênção e maldição. Meus irmãos, não pode ser assim!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30331, 'nvi', 'Tiago', 'tg', 3, 11, 'Acaso pode sair água doce e água amarga da mesma fonte?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30332, 'nvi', 'Tiago', 'tg', 3, 12, 'Meus irmãos, pode uma figueira produzir azeitonas ou uma videira, figos? Da mesma forma, uma fonte de água salgada não pode produzir água doce.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30333, 'nvi', 'Tiago', 'tg', 3, 13, 'Quem é sábio e tem entendimento entre vocês? Que o demonstre por seu bom procedimento, mediante obras praticadas com a humildade que provém da sabedoria.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30334, 'nvi', 'Tiago', 'tg', 3, 14, 'Contudo, se vocês abrigam no coração inveja amarga e ambição egoísta, não se gloriem disso, nem neguem a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30335, 'nvi', 'Tiago', 'tg', 3, 15, 'Esse tipo de "sabedoria" não vem do céu, mas é terrena, não é espiritual e é demoníaca.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30336, 'nvi', 'Tiago', 'tg', 3, 16, 'Pois onde há inveja e ambição egoísta, aí há confusão e toda espécie de males.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30337, 'nvi', 'Tiago', 'tg', 3, 17, 'Mas a sabedoria que vem do alto é antes de tudo pura; depois, pacífica, amável, compreensiva, cheia de misericórdia e de bons frutos, imparcial e sincera.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30338, 'nvi', 'Tiago', 'tg', 3, 18, 'O fruto da justiça semeia-se em paz para os pacificadores.');
