-- Inserções para Tiago 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30339, 'nvi', 'Tiago', 'tg', 4, 1, 'De onde vêm as guerras e contendas que há entre vocês? Não vêm das paixões que guerreiam dentro de vocês?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30340, 'nvi', 'Tiago', 'tg', 4, 2, 'Vocês cobiçam coisas, e não as têm; matam e invejam, mas não conseguem obter o que desejam. Vocês vivem a lutar e a fazer guerras. Não têm, porque não pedem.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30341, 'nvi', 'Tiago', 'tg', 4, 3, 'Quando pedem, não recebem, pois pedem por motivos errados, para gastar em seus prazeres.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30342, 'nvi', 'Tiago', 'tg', 4, 4, 'Adúlteros, vocês não sabem que a amizade com o mundo é inimizade com Deus? Quem quer ser amigo do mundo faz-se inimigo de Deus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30343, 'nvi', 'Tiago', 'tg', 4, 5, 'Ou vocês acham que é sem razão que a Escritura diz que o Espírito que ele fez habitar em nós tem fortes ciúmes?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30344, 'nvi', 'Tiago', 'tg', 4, 6, 'Mas ele nos concede graça maior. Por isso diz a Escritura: "Deus se opõe aos orgulhosos, mas concede graça aos humildes".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30345, 'nvi', 'Tiago', 'tg', 4, 7, 'Portanto, submetam-se a Deus. Resistam ao diabo, e ele fugirá de vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30346, 'nvi', 'Tiago', 'tg', 4, 8, 'Aproximem-se de Deus, e ele se aproximará de vocês! Pecadores, limpem as mãos, e vocês, que têm a mente dividida, purifiquem o coração.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30347, 'nvi', 'Tiago', 'tg', 4, 9, 'Entristeçam-se, lamentem e chorem. Troquem o riso por lamento e a alegria por tristeza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30348, 'nvi', 'Tiago', 'tg', 4, 10, 'Humilhem-se diante do Senhor, e ele os exaltará.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30349, 'nvi', 'Tiago', 'tg', 4, 11, 'Irmãos, não falem mal uns dos outros. Quem fala contra o seu irmão ou julga o seu irmão, fala contra a Lei e a julga. Quando você julga a Lei, não a está cumprindo, mas está se colocando como juiz.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30350, 'nvi', 'Tiago', 'tg', 4, 12, 'Há apenas um Legislador e Juiz, aquele que pode salvar e destruir. Mas quem é você para julgar o seu próximo?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30351, 'nvi', 'Tiago', 'tg', 4, 13, 'Ouçam agora, vocês que dizem: "Hoje ou amanhã iremos para esta ou aquela cidade, passaremos um ano ali, faremos negócios e ganharemos dinheiro".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30352, 'nvi', 'Tiago', 'tg', 4, 14, 'Vocês nem sabem o que lhes acontecerá amanhã! Que é a sua vida? Vocês são como a neblina que aparece por um pouco de tempo e depois se dissipa.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30353, 'nvi', 'Tiago', 'tg', 4, 15, 'Ao invés disso, deveriam dizer: "Se o Senhor quiser, viveremos e faremos isto ou aquilo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30354, 'nvi', 'Tiago', 'tg', 4, 16, 'Agora, porém, vocês se vangloriam das suas pretensões. Toda vanglória como essa é maligna.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (30355, 'nvi', 'Tiago', 'tg', 4, 17, 'Pensem nisto, pois: Quem sabe que deve fazer o bem e não o faz, comete pecado.');
