-- Inserções para Tito 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29910, 'nvi', 'Tito', 'tt', 2, 1, 'Você, porém, fale o que está de acordo com a sã doutrina.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29911, 'nvi', 'Tito', 'tt', 2, 2, 'Ensine os homens mais velhos a serem sóbrios, dignos de respeito, sensatos, e sadios na fé, no amor e na perseverança.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29912, 'nvi', 'Tito', 'tt', 2, 3, 'Semelhantemente, ensine as mulheres mais velhas a serem reverentes na sua maneira de viver, a não serem caluniadoras nem escravizadas a muito vinho, mas a serem capazes de ensinar o que é bom.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29913, 'nvi', 'Tito', 'tt', 2, 4, 'Assim, poderão orientar as mulheres mais jovens a amarem seus maridos e seus filhos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29914, 'nvi', 'Tito', 'tt', 2, 5, 'a serem prudentes e puras, a estarem ocupadas em casa, e a serem bondosas e sujeitas a seus próprios maridos, a fim de que a palavra de Deus não seja difamada.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29915, 'nvi', 'Tito', 'tt', 2, 6, 'Da mesma maneira, encoraje os jovens a serem prudentes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29916, 'nvi', 'Tito', 'tt', 2, 7, 'Em tudo seja você mesmo um exemplo para eles, fazendo boas obras. Em seu ensino, mostre integridade e seriedade;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29917, 'nvi', 'Tito', 'tt', 2, 8, 'use linguagem sadia, contra a qual nada se possa dizer, para que aqueles que se lhe opõem fiquem envergonhados por não terem nada de mal para dizer a nosso respeito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29918, 'nvi', 'Tito', 'tt', 2, 9, 'Ensine os escravos a se submeterem em tudo a seus senhores, a procurarem agradá-los, a não serem respondões e');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29919, 'nvi', 'Tito', 'tt', 2, 10, 'a não roubá-los, mas a mostrarem que são inteiramente dignos de confiança, para que assim tornem atraente, em tudo, o ensino de Deus, nosso Salvador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29920, 'nvi', 'Tito', 'tt', 2, 11, 'Porque a graça de Deus se manifestou salvadora a todos os homens.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29921, 'nvi', 'Tito', 'tt', 2, 12, 'Ela nos ensina a renunciar à impiedade e às paixões mundanas e a viver de maneira sensata, justa e piedosa nesta era presente,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29922, 'nvi', 'Tito', 'tt', 2, 13, 'enquanto aguardamos a bendita esperança: a gloriosa manifestação de nosso grande Deus e Salvador, Jesus Cristo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29923, 'nvi', 'Tito', 'tt', 2, 14, 'Ele se entregou por nós a fim de nos remir de toda a maldade e purificar para si mesmo um povo particularmente seu, dedicado à prática de boas obras.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29924, 'nvi', 'Tito', 'tt', 2, 15, 'É isso que você deve ensinar, exortando-os e repreendendo-os com toda a autoridade. Ninguém o despreze.');
