-- Inserções para Tito 1
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29894, 'nvi', 'Tito', 'tt', 1, 1, 'Paulo, servo de Deus e apóstolo de Jesus Cristo para levar os eleitos de Deus à fé e ao conhecimento da verdade que conduz à piedade,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29895, 'nvi', 'Tito', 'tt', 1, 2, 'fé e conhecimento que se fundamentam na esperança da vida eterna, a qual o Deus que não mente prometeu antes dos tempos eternos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29896, 'nvi', 'Tito', 'tt', 1, 3, 'No devido tempo, ele trouxe à luz a sua palavra, por meio da pregação a mim confiada por ordem de Deus, nosso Salvador,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29897, 'nvi', 'Tito', 'tt', 1, 4, 'a Tito, meu verdadeiro filho em nossa fé comum: Graça e paz da parte de Deus Pai e de Cristo Jesus, nosso Salvador.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29898, 'nvi', 'Tito', 'tt', 1, 5, 'A razão de tê-lo deixado em Creta foi para que você pusesse em ordem o que ainda faltava e constituísse presbíteros em cada cidade, como eu o instruí.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29899, 'nvi', 'Tito', 'tt', 1, 6, 'É preciso que o presbítero seja irrepreensível, marido de uma só mulher, e tenha filhos crentes que não sejam acusados de libertinagem ou de insubmissão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29900, 'nvi', 'Tito', 'tt', 1, 7, 'Por ser encarregado da obra de Deus, é necessário que o bispo seja irrepreensível: não orgulhoso, não briguento, não apegado ao vinho, não violento, nem ávido por lucro desonesto.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29901, 'nvi', 'Tito', 'tt', 1, 8, 'É preciso, porém, que ele seja hospitaleiro, amigo do bem, sensato, justo, consagrado, tenha domínio próprio');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29902, 'nvi', 'Tito', 'tt', 1, 9, 'e apegue-se firmemente à mensagem fiel, da maneira como foi ensinada, para que seja capaz de encorajar outros pela sã doutrina e de refutar os que se opõem a ela.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29903, 'nvi', 'Tito', 'tt', 1, 10, 'Pois há muitos insubordinados, que não passam de faladores e enganadores, especialmente os do grupo da circuncisão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29904, 'nvi', 'Tito', 'tt', 1, 11, 'É necessário que eles sejam silenciados, pois estão arruinando famílias inteiras, ensinando coisas que não devem, e tudo por ganância.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29905, 'nvi', 'Tito', 'tt', 1, 12, 'Um dos seus próprios profetas chegou a dizer: "Cretenses, sempre mentirosos, feras malignas, glutões preguiçosos".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29906, 'nvi', 'Tito', 'tt', 1, 13, 'Tal testemunho é verdadeiro. Portanto, repreenda-os severamente, para que sejam sadios na fé');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29907, 'nvi', 'Tito', 'tt', 1, 14, 'e não dêem atenção a lendas judaicas nem a mandamentos de homens que rejeitam a verdade.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29908, 'nvi', 'Tito', 'tt', 1, 15, 'Para os puros, todas as coisas são puras; mas para os impuros e descrentes, nada é puro. De fato, tanto a mente como a consciência deles estão corrompidas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (29909, 'nvi', 'Tito', 'tt', 1, 16, 'Eles afirmam que conhecem a Deus, mas por seus atos o negam; são detestáveis, desobedientes e desqualificados para qualquer boa obra.');
