-- Inserções para Zacarias 4
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22924, 'nvi', 'Zacarias', 'zc', 4, 1, 'Depois o anjo que falava comigo tornou a despertar-me, como se desperta alguém do sono,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22925, 'nvi', 'Zacarias', 'zc', 4, 2, 'e me perguntou: "O que você está vendo? " Respondi: "Vejo um candelabro de ouro maciço com um recipiente para azeite na parte superior e sete lâmpadas e sete canos para as lâmpadas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22926, 'nvi', 'Zacarias', 'zc', 4, 3, 'Há também duas oliveiras junto ao recipiente, uma à direita e outra à esquerda".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22927, 'nvi', 'Zacarias', 'zc', 4, 4, 'Perguntei ao anjo que falava comigo: "O que significa isto, meu senhor? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22928, 'nvi', 'Zacarias', 'zc', 4, 5, 'Ele disse: "Você não sabe? " "Não, meu senhor", respondi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22929, 'nvi', 'Zacarias', 'zc', 4, 6, '"Esta é a palavra do Senhor para Zorobabel: ‘Não por força nem por violência, mas pelo meu Espírito’, diz o Senhor dos Exércitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22930, 'nvi', 'Zacarias', 'zc', 4, 7, '"Quem você pensa que é, ó montanha majestosa? Diante de Zorobabel você se tornará uma planície. Ele colocará a pedra principal aos gritos de ‘Deus abençoe! Deus abençoe! ’ "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22931, 'nvi', 'Zacarias', 'zc', 4, 8, 'Então o Senhor me falou:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22932, 'nvi', 'Zacarias', 'zc', 4, 9, '"As mãos de Zorobabel colocacaram os fundamentos deste templo; suas mãos também o terminarão. Assim saberão que o Senhor dos Exércitos me enviou a vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22933, 'nvi', 'Zacarias', 'zc', 4, 10, '"Pois aqueles que desprezaram o dia das pequenas coisas terão grande alegria ao verem a pedra principal nas mãos de Zorobabel". Então ele me disse: "Estas sete lâmpadas são os olhos do Senhor, que sondam toda a terra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22934, 'nvi', 'Zacarias', 'zc', 4, 11, 'A seguir perguntei ao anjo: "O que significam estas duas oliveiras à direita e à esquerda do candelabro? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22935, 'nvi', 'Zacarias', 'zc', 4, 12, 'E perguntei também: "O que significam estes dois ramos de oliveira ao lado dos dois tubos de ouro que derramam azeite dourado? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22936, 'nvi', 'Zacarias', 'zc', 4, 13, 'Ele disse: "Você não sabe? " "Não, meu senhor", respondi.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22937, 'nvi', 'Zacarias', 'zc', 4, 14, 'Então ele me disse: "São os dois homens que foram ungidos para servir ao Soberano de toda a terra! "');
