-- Inserções para Zacarias 3
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22914, 'nvi', 'Zacarias', 'zc', 3, 1, 'Depois disso ele me mostrou o sumo sacerdote Josué diante do anjo do Senhor, e Satanás, à sua direita, para acusá-lo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22915, 'nvi', 'Zacarias', 'zc', 3, 2, 'O anjo do Senhor disse a Satanás: "O Senhor o repreenda, Satanás! O Senhor que escolheu Jerusalém o repreenda! Este homem não parece um tição tirado do fogo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22916, 'nvi', 'Zacarias', 'zc', 3, 3, 'Ora, Josué, vestido de roupas impuras, estava de pé diante do anjo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22917, 'nvi', 'Zacarias', 'zc', 3, 4, 'O anjo disse aos que estavam diante dele: "Tirem as roupas impuras dele". Depois disse a Josué: "Veja, eu tirei de você o seu pecado, e coloquei vestes nobres sobre você".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22918, 'nvi', 'Zacarias', 'zc', 3, 5, 'Disse também: "Coloquem um turbante limpo em sua cabeça". Colocaram o turbante nele e o vestiram, enquanto o anjo do Senhor observava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22919, 'nvi', 'Zacarias', 'zc', 3, 6, 'O anjo do Senhor exortou a Josué, dizendo:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22920, 'nvi', 'Zacarias', 'zc', 3, 7, '"Assim diz o Senhor dos Exércitos: ‘Se você andar nos meus caminhos e obedecer aos meus preceitos, você governará a minha casa e também estará encarregado das minhas cortes, e eu lhe darei um lugar entre estes que estão aqui.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22921, 'nvi', 'Zacarias', 'zc', 3, 8, '" ‘Ouçam bem, sumo sacerdote Josué e seus companheiros sentados diante de você, homens que prefiguram coisas que virão: Vou trazer o meu servo, o Renovo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22922, 'nvi', 'Zacarias', 'zc', 3, 9, 'Vejam a pedra que coloquei na frente de Josué! Ela tem sete pares de olhos, e eu gravarei nela uma inscrição’, declara o Senhor dos Exércitos, ‘e removerei o pecado desta terra num único dia.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22923, 'nvi', 'Zacarias', 'zc', 3, 10, '" ‘Naquele dia’, declara o Senhor dos Exércitos, ‘cada um de vocês convidará seu próximo para assentar-se debaixo da sua videira e debaixo da sua figueira’ ".');
