-- Inserções para Zacarias 13
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23061, 'nvi', 'Zacarias', 'zc', 13, 1, '"Naquele dia uma fonte jorrará para os descendentes de Davi e para os habitantes de Jerusalém, para purificá-los do pecado e da impureza.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23062, 'nvi', 'Zacarias', 'zc', 13, 2, '"Naquele dia eliminarei da terra de Israel os nomes dos ídolos, e nunca mais serão lembrados", diz o Senhor dos Exércitos. "Removerei da terra tanto os profetas como o espírito imundo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23063, 'nvi', 'Zacarias', 'zc', 13, 3, 'E se alguém ainda profetizar, seu próprio pai e sua mãe lhe advertirão: ‘Você tem que morrer porque disse mentiras em nome do Senhor’. Quando ele profetizar, os seus próprios pais o esfaquearão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23064, 'nvi', 'Zacarias', 'zc', 13, 4, '"Naquele dia todo profeta se envergonhará de sua visão profética. Não usará o manto de profeta feito de pele, para enganar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23065, 'nvi', 'Zacarias', 'zc', 13, 5, 'Ele dirá: ‘Eu não sou profeta. Sou um homem do campo; a terra tem sido o meu sustento desde a minha mocidade’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23066, 'nvi', 'Zacarias', 'zc', 13, 6, 'Se alguém lhe perguntar: ‘Que feridas são estas no seu corpo? ’, ele responderá: ‘Eu fui ferido na casa de meus amigos’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23067, 'nvi', 'Zacarias', 'zc', 13, 7, '"Levante-se, ó espada, contra o meu pastor, contra o meu companheiro! ", declara o Senhor dos Exércitos. "Fira o pastor, e as ovelhas se dispersarão, e voltarei minha mão para os pequeninos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23068, 'nvi', 'Zacarias', 'zc', 13, 8, 'Na terra toda, dois terços serão ceifados e morrerão; todavia a terça parte permanecerá", diz o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23069, 'nvi', 'Zacarias', 'zc', 13, 9, '"Colocarei essa terça parte no fogo, e a refinarei como prata, e a purificarei como ouro. Ela invocará o meu nome, e eu lhe responderei. É o meu povo, direi; e ela dirá: ‘O Senhor é o meu Deus’. "');
