-- Inserções para Zacarias 10
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23018, 'nvi', 'Zacarias', 'zc', 10, 1, 'Peça ao Senhor a chuva de primavera, pois, é o Senhor quem faz o trovão, quem manda a chuva e lhes dá as plantas do campo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23019, 'nvi', 'Zacarias', 'zc', 10, 2, 'Porque os ídolos falam mentiras, os adivinhadores têm falsas visões, e contam sonhos enganadores; o consolo que trazem é vão. Por isso o povo vagueia como ovelhas, aflitas pela falta de um pastor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23020, 'nvi', 'Zacarias', 'zc', 10, 3, '"Contra os pastores acende-se a minha ira, e contra os líderes eu agirei". Porque o Senhor dos Exércitos cuida de seu rebanho, o povo de Judá. Ele fará dele o seu brioso corcel na batalha.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23021, 'nvi', 'Zacarias', 'zc', 10, 4, 'Dele virão a pedra fundamental, e a estaca da tenda, o arco da batalha e os governantes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23022, 'nvi', 'Zacarias', 'zc', 10, 5, 'Juntos serão como guerreiros que pisam a lama das ruas na batalha. Lutarão e derrubarão os cavaleiros porque o Senhor estará com eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23023, 'nvi', 'Zacarias', 'zc', 10, 6, '"Assim, eu fortalecerei a tribo de Judá e salvarei a casa de José. Eu os restaurarei porque tenho compaixão deles. Eles serão como se eu nunca os tivesse rejeitado, porque eu sou o Senhor, o Deus deles, e lhes responderei.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23024, 'nvi', 'Zacarias', 'zc', 10, 7, 'Efraim será como um homem poderoso; seu coração se alegrará como se fosse com vinho, seus filhos o verão e se alegrarão; seus corações exultarão no Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23025, 'nvi', 'Zacarias', 'zc', 10, 8, 'Assobiarei para eles e os ajuntarei, pois eu já os resgatei. Serão numerosos como antes.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23026, 'nvi', 'Zacarias', 'zc', 10, 9, 'Embora eu os espalhe por entre os povos de terras distantes, eles se lembrarão de mim. Criarão seus filhos e voltarão.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23027, 'nvi', 'Zacarias', 'zc', 10, 10, 'Eu os farei retornar do Egito e os ajuntarei de volta da Assíria. Eu os levarei para as terras de Gileade e do Líbano, e mesmo assim não haverá espaço suficiente para eles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23028, 'nvi', 'Zacarias', 'zc', 10, 11, 'Passarei pelo mar da aflição, ferirei o mar revoltoso, e as profundezas do Nilo se secarão. O orgulho da Assíria será abatido e o poder do Egito será derrubado.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23029, 'nvi', 'Zacarias', 'zc', 10, 12, 'Eu os fortalecerei no Senhor, em meu nome marcharão", diz o Senhor.');
