-- Inserções para Zacarias 12
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23047, 'nvi', 'Zacarias', 'zc', 12, 1, 'Esta é a palavra do Senhor para Israel. Palavra do Senhor, que estende os céus, assenta o alicerce da terra e forma o espírito do homem dentro dele:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23048, 'nvi', 'Zacarias', 'zc', 12, 2, '"Farei de Jerusalém uma taça que embriague todos os povos ao seu redor, que estarão no cerco contra Judá e Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23049, 'nvi', 'Zacarias', 'zc', 12, 3, 'Naquele dia, quando todas as nações da terra estiverem reunidas para atacá-la, farei de Jerusalém uma pedra pesada para todas as nações. Todos que tentarem levantá-la se machucarão muito.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23050, 'nvi', 'Zacarias', 'zc', 12, 4, 'Naquele dia deixarei todos os cavalos em pânico e os seus cavaleiros loucos", diz o Senhor. "Protegerei o povo de Judá, mas cegarei todos os cavalos das nações.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23051, 'nvi', 'Zacarias', 'zc', 12, 5, 'Então os líderes de Judá pensarão: ‘Os habitantes de Jerusalém são fortes porque o Senhor dos Exércitos é o seu Deus! ’');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23052, 'nvi', 'Zacarias', 'zc', 12, 6, '"Naquele dia farei que os líderes de Judá sejam semelhantes a um braseiro no meio de um monte de lenha, como uma tocha incandescente entre gravetos. Eles consumirão à direita e à esquerda todos os povos ao redor, mas Jerusalém permanecerá intacta em seu lugar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23053, 'nvi', 'Zacarias', 'zc', 12, 7, '"O Senhor salvará primeiro as tendas de Judá, para que a honra da família de Davi e dos habitantes de Jerusalém não seja superior à de Judá.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23054, 'nvi', 'Zacarias', 'zc', 12, 8, 'Naquele dia o Senhor protegerá os que vivem em Jerusalém, de forma que o mais fraco dentre eles será como Davi, e a família de Davi será como Deus, como o anjo do Senhor que vai adiante deles.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23055, 'nvi', 'Zacarias', 'zc', 12, 9, '"Naquele dia procurarei destruir todas as nações que atacarem Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23056, 'nvi', 'Zacarias', 'zc', 12, 10, 'E derramarei sobre a família de Davi e sobre os habitantes de Jerusalém um espírito de ação de graças e de súplicas. Olharão para mim, aquele a quem traspassaram, e chorarão por ele como quem chora a perda de um filho único, e lamentarão amargamente por ele como quem lamenta a perda do filho mais velho.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23057, 'nvi', 'Zacarias', 'zc', 12, 11, 'Naquele dia muitos chorarão em Jerusalém, como os que choraram em Hadade-Rimon no vale de Megido.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23058, 'nvi', 'Zacarias', 'zc', 12, 12, 'Todo o país chorará, separadamente cada família com suas mulheres chorará: a família de Davi com suas mulheres; a família de Natã com suas mulheres;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23059, 'nvi', 'Zacarias', 'zc', 12, 13, 'a família de Levi com suas mulheres; a família de Simei com suas mulheres,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23060, 'nvi', 'Zacarias', 'zc', 12, 14, 'e todas as demais famílias com suas mulheres.');
