-- Inserções para Zacarias 6
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22949, 'nvi', 'Zacarias', 'zc', 6, 1, 'Olhei novamente, e vi diante de mim quatro carruagens que vinham saindo do meio de duas montanhas de bronze.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22950, 'nvi', 'Zacarias', 'zc', 6, 2, 'À primeira estavam atrelados cavalos vermelhos, à segunda, cavalos pretos,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22951, 'nvi', 'Zacarias', 'zc', 6, 3, 'à terceira, cavalos brancos, e à quarta, cavalos malhados. Todos eram vigorosos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22952, 'nvi', 'Zacarias', 'zc', 6, 4, 'Perguntei ao anjo que falava comigo: "Que representam estes cavalos atrelados, meu senhor? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22953, 'nvi', 'Zacarias', 'zc', 6, 5, 'O anjo me respondeu: "Estes são os quatro espíritos do céu, que acabam de sair da presença do Soberano de toda a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22954, 'nvi', 'Zacarias', 'zc', 6, 6, 'A carruagem puxada pelos cavalos pretos vai em direção à terra do norte, a que tem cavalos brancos vai em direção ao oriente, e a que tem cavalos malhados vai para a terra do sul".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22955, 'nvi', 'Zacarias', 'zc', 6, 7, 'Os vigorosos cavalos avançavam, impacientes por percorrer a terra. E o anjo lhes disse: "Percorram toda a terra! " E eles foram.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22956, 'nvi', 'Zacarias', 'zc', 6, 8, 'Então ele me chamou e disse: "Veja, os que foram para a terra do norte deram repouso ao meu Espírito naquela terra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22957, 'nvi', 'Zacarias', 'zc', 6, 9, 'E o Senhor me ordenou:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22958, 'nvi', 'Zacarias', 'zc', 6, 10, '"Tome prata e ouro dos exilados Heldai, Tobias e Jedaías, que chegaram da Babilônia. No mesmo dia vá à casa de Josias, filho de Sofonias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22959, 'nvi', 'Zacarias', 'zc', 6, 11, 'Pegue a prata e o ouro, faça uma coroa, e coloque-a na cabeça do sumo sacerdote Josué, filho de Jeozadaque.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22960, 'nvi', 'Zacarias', 'zc', 6, 12, 'Diga-lhe que assim diz o Senhor dos Exércitos: ‘Aqui está o homem cujo nome é Renovo, e ele sairá do seu lugar e construirá o templo do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22961, 'nvi', 'Zacarias', 'zc', 6, 13, 'Ele construirá o templo do Senhor, será revestido de majestade e se assentará em seu trono para governar. E ele será sacerdote no trono. E haverá harmonia entre os dois’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22962, 'nvi', 'Zacarias', 'zc', 6, 14, 'A coroa será para Heldai, Tobias, Jedaías e Hem, filho de Sofonias como um memorial no templo do Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22963, 'nvi', 'Zacarias', 'zc', 6, 15, 'Gente de longe virá ajudar a construir o templo do Senhor. Então vocês saberão que o Senhor dos Exércitos me enviou a vocês. Isto só acontecerá se obedecerem fielmente à voz do Senhor, o seu Deus".');
