-- Inserções para Zacarias 2
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22901, 'nvi', 'Zacarias', 'zc', 2, 1, 'Olhei em seguida, e vi um homem segurando uma corda de medir.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22902, 'nvi', 'Zacarias', 'zc', 2, 2, 'Eu lhe perguntei: "Aonde você vai? " Ele me respondeu: "Vou medir Jerusalém para saber o seu comprimento e a sua largura".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22903, 'nvi', 'Zacarias', 'zc', 2, 3, 'Então o anjo que falava comigo retirou-se, e outro anjo foi ao seu encontro');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22904, 'nvi', 'Zacarias', 'zc', 2, 4, 'e lhe disse: "Corra e diga àquele jovem: ‘Jerusalém será habitada como uma cidade sem muros por causa dos seus muitos habitantes e rebanhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22905, 'nvi', 'Zacarias', 'zc', 2, 5, 'E eu mesmo serei para ela um muro de fogo ao seu redor’, declara o Senhor, ‘e dentro dela serei a sua glória’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22906, 'nvi', 'Zacarias', 'zc', 2, 6, '"Atenção! Atenção! Fujam da terra do norte", declara o Senhor, "porque eu os espalhei aos quatro ventos da terra", diz o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22907, 'nvi', 'Zacarias', 'zc', 2, 7, '"Atenção, ó Sião! Escapem, vocês que vivem na cidade da Babilônia!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22908, 'nvi', 'Zacarias', 'zc', 2, 8, 'Porque assim diz o Senhor dos Exércitos: ‘Ele me enviou para buscar a sua glória entre as nações que saquearam vocês, porque todo o que neles tocar, toca na pupila dos olhos dele’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22909, 'nvi', 'Zacarias', 'zc', 2, 9, 'Certamente levantarei a minha mão contra elas de forma que serão um espólio para os seus servos. Então vocês saberão que foi o Senhor dos Exércitos que me enviou.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22910, 'nvi', 'Zacarias', 'zc', 2, 10, '"Cante e alegre-se, ó cidade de Sião! Porque venho fazer de você a minha habitação", declara o Senhor.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22911, 'nvi', 'Zacarias', 'zc', 2, 11, '"Muitas nações se unirão ao Senhor naquele dia e se tornarão meu povo. Então você será a minha habitação e você reconhecerá que o Senhor dos Exércitos me enviou a você.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22912, 'nvi', 'Zacarias', 'zc', 2, 12, 'O Senhor herdará Judá como sua propriedade na terra santa e escolherá de novo Jerusalém.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22913, 'nvi', 'Zacarias', 'zc', 2, 13, 'Aquietem-se todos perante o Senhor, porque ele se levantou de sua santa habitação".');
