-- Inserções para Zacarias 9
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23001, 'nvi', 'Zacarias', 'zc', 9, 1, 'A advertência do Senhor é contra a terra de Hadraque e cairá sobre Damasco, porque os olhos do Senhor estão sobre toda a humanidade e sobre todas as tribos de Israel,');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23002, 'nvi', 'Zacarias', 'zc', 9, 2, 'e também sobre Hamate que faz fronteira com Damasco, e sobre Tiro e Sidom, embora sejam muito sábias.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23003, 'nvi', 'Zacarias', 'zc', 9, 3, 'Tiro construiu para si uma fortaleza; acumulou prata como pó, e ouro como lama das ruas.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23004, 'nvi', 'Zacarias', 'zc', 9, 4, 'Mas o Senhor se apossará dela e lançará no mar suas riquezas, e ela será consumida pelo fogo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23005, 'nvi', 'Zacarias', 'zc', 9, 5, 'Ao ver isso Ascalom ficará com medo; Gaza também se contorcerá de agonia, assim como Ecrom, porque a sua esperança fracassou. Gaza perderá o seu rei, e Ascalom ficará deserta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23006, 'nvi', 'Zacarias', 'zc', 9, 6, 'Um povo bastardo ocupará Asdode, e assim eu acabarei com o orgulho dos filisteus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23007, 'nvi', 'Zacarias', 'zc', 9, 7, 'Tirarei o sangue de suas bocas, e a comida proibida dentre os seus dentes. Aquele que restar pertencerá ao nosso Deus e se tornará chefe em Judá, e Ecrom será como os jebuseus.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23008, 'nvi', 'Zacarias', 'zc', 9, 8, 'Defenderei a minha casa contra os invasores. Nunca mais um opressor passará por cima do meu povo, porque agora eu vejo isso com os meus próprios olhos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23009, 'nvi', 'Zacarias', 'zc', 9, 9, 'Alegre-se muito, cidade de Sião! Exulte, Jerusalém! Eis que o seu rei vem a você, justo e vitorioso, humilde e montado num jumento, um jumentinho, cria de jumenta.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23010, 'nvi', 'Zacarias', 'zc', 9, 10, 'Ele destruirá os carros de guerra de Efraim e os cavalos de Jerusalém, e os arcos de batalha serão quebrados. Ele proclamará paz às nações e dominará de um mar a outro, e do Eufrates até aos confins da terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23011, 'nvi', 'Zacarias', 'zc', 9, 11, 'Quanto a você, por causa do sangue da minha aliança com você, libertarei os seus prisioneiros de um poço sem água.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23012, 'nvi', 'Zacarias', 'zc', 9, 12, 'Voltem à sua fortaleza, ó prisioneiros da esperança; pois hoje mesmo anuncio que restaurarei tudo em dobro para vocês.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23013, 'nvi', 'Zacarias', 'zc', 9, 13, 'Quando eu curvar Judá como se curva um arco e usar Efraim como flecha, levantarei os filhos de Sião contra os filhos da Grécia, e farei você semelhante à espada de um guerreiro.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23014, 'nvi', 'Zacarias', 'zc', 9, 14, 'Então o Senhor aparecerá sobre eles; sua flecha brilhará como o relâmpago. O Soberano Senhor tocará a trombeta e marchará em meio às tempestades do sul;');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23015, 'nvi', 'Zacarias', 'zc', 9, 15, 'o Senhor dos Exércitos os protegerá. Eles pisotearão e destruirão as pedras das atiradeiras. Eles beberão o sangue do inimigo como se fosse vinho; estarão cheios como a bacia usada para aspergir água nos cantos do altar.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23016, 'nvi', 'Zacarias', 'zc', 9, 16, 'Naquele dia o Senhor, o seu Deus, os salvará como rebanho do seu povo, e como jóias de uma coroa brilharão em sua terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (23017, 'nvi', 'Zacarias', 'zc', 9, 17, 'Ah! Como serão belos! Como serão formosos! O trigo dará vigor aos rapazes, e o vinho novo às moças.');
