-- Inserções para Zacarias 7
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22964, 'nvi', 'Zacarias', 'zc', 7, 1, 'No quarto ano do reinado do rei Dario, a palavra do Senhor veio a Zacarias, no quarto dia do nono mês, o mês de quisleu.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22965, 'nvi', 'Zacarias', 'zc', 7, 2, 'Foi quando o povo de Betel enviou Sarezer e Régen-Meleque com seus homens, para suplicarem ao Senhor');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22966, 'nvi', 'Zacarias', 'zc', 7, 3, 'perguntando aos sacerdotes do templo do Senhor dos Exércitos e aos profetas: "Devemos lamentar e jejuar no quinto mês, como já faz tantos anos que estamos fazendo? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22967, 'nvi', 'Zacarias', 'zc', 7, 4, 'Então o Senhor dos Exércitos me falou:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22968, 'nvi', 'Zacarias', 'zc', 7, 5, '"Pergunte a todo o povo e aos sacerdotes: Quando vocês jejuaram no quinto e no sétimo meses durante os últimos setenta anos, foi de fato para mim que jejuaram?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22969, 'nvi', 'Zacarias', 'zc', 7, 6, 'E quando comiam e bebiam, não era para vocês mesmos que o faziam?');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22970, 'nvi', 'Zacarias', 'zc', 7, 7, 'Não são essas as palavras do Senhor proclamadas pelos antigos profetas quando Jerusalém e as cidades ao seu redor estavam em paz e prosperavam, e o Neguebe e a Sefelá eram habitados? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22971, 'nvi', 'Zacarias', 'zc', 7, 8, 'E a palavra do Senhor veio novamente a Zacarias:');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22972, 'nvi', 'Zacarias', 'zc', 7, 9, '"Assim diz o Senhor dos Exércitos: ‘Administrem a verdadeira justiça, mostrem misericórdia e compaixão uns para com os outros.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22973, 'nvi', 'Zacarias', 'zc', 7, 10, 'Não oprimam a viúva e o órfão, nem o estrangeiro e o necessitado. Nem tramem maldades uns contra os outros’.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22974, 'nvi', 'Zacarias', 'zc', 7, 11, '"Mas eles se recusaram a dar atenção; teimosamente viraram as costas e taparam os ouvidos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22975, 'nvi', 'Zacarias', 'zc', 7, 12, 'Endureceram o coração para não ouvirem a Lei e as palavras que o Senhor dos Exércitos tinha falado pelo seu Espírito por meio dos antigos profetas. Por isso o Senhor dos Exércitos irou-se muito".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22976, 'nvi', 'Zacarias', 'zc', 7, 13, '" ‘Quando eu os chamei, não deram ouvidos; por isso, quando eles me chamarem, também não ouvirei’, diz o Senhor dos Exércitos.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22977, 'nvi', 'Zacarias', 'zc', 7, 14, '‘Eu os espalhei com um vendaval entre nações que eles nem conhecem. A terra que deixaram para trás ficou tão destruída que ninguém podia atravessá-la. Foi assim que transformaram a terra aprazível em ruínas’ ".');
