-- Inserções para Zacarias 5
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22938, 'nvi', 'Zacarias', 'zc', 5, 1, 'Levantei novamente os olhos, e vi diante de mim um pergaminho que voava.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22939, 'nvi', 'Zacarias', 'zc', 5, 2, 'O anjo me perguntou: "O que você está vendo? " Respondi: "Vejo um pergaminho voando, com nove metros de comprimento por quatro e meio de largura".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22940, 'nvi', 'Zacarias', 'zc', 5, 3, 'Então ele me disse: "Nele está escrita a maldição que está sendo derramada sobre toda a terra: porque tanto o ladrão como o que jura falsamente serão expulsos, conforme essa maldição.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22941, 'nvi', 'Zacarias', 'zc', 5, 4, 'Assim declara o Senhor dos Exércitos: ‘Eu lancei essa maldição para que ela entre na casa do ladrão e na casa do que jura falsamente pelo meu nome. Ela ficará em sua casa e destruirá tanto as vigas como os tijolos! ’ "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22942, 'nvi', 'Zacarias', 'zc', 5, 5, 'Em seguida o anjo que falava comigo se adiantou e me disse: "Olhe e veja o que vem surgindo".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22943, 'nvi', 'Zacarias', 'zc', 5, 6, 'Perguntei o que era aquilo, e ele me respondeu: "É um cesto". E disse mais: "Aí está o pecado de todo o povo desta terra".');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22944, 'nvi', 'Zacarias', 'zc', 5, 7, 'Então a tampa de chumbo foi retirada, e ali dentro do cesto estava uma mulher sentada!');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22945, 'nvi', 'Zacarias', 'zc', 5, 8, 'Ele disse: "Esta é a Perversidade", e a empurrou para dentro do cesto e o tapou de novo com a tampa de chumbo.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22946, 'nvi', 'Zacarias', 'zc', 5, 9, 'De novo ergui os olhos e vi chegarem à minha frente duas mulheres com asas como de cegonha; o vento impeliu suas asas, e elas ergueram o cesto entre o céu e a terra.');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22947, 'nvi', 'Zacarias', 'zc', 5, 10, 'Perguntei ao anjo: "Para onde estão levando o cesto? "');
INSERT INTO bible (id, version, book, abbrev, chapter, verse, text) VALUES (22948, 'nvi', 'Zacarias', 'zc', 5, 11, 'Ele respondeu: "Para a Babilônia, onde vão construir um santuário para ele. Quando ficar pronto, o cesto será colocado lá, em seu pedestal".');
